import { notFound } from "next/navigation";
import { ChapterLessonPager, ChapterPartStrip, ChapterShell } from "@/components/notes/canonical";
import { dBlockLessonBySlug, D_BLOCK_LESSONS } from "../content";
import { dBlockLessonRef, dBlockTabs } from "../_chapter";
import { DBlockMarkdown } from "../_markdown";
import { DBlockVisual } from "../_visual";
export const dynamic = "force-dynamic";
export function generateStaticParams() { return D_BLOCK_LESSONS.map((lesson) => ({ part: lesson.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ part: string }> }) { const lesson = dBlockLessonBySlug((await params).part); return lesson ? { title: `D-block Elements — ${lesson.title} | SYNERGIC BOND`, description: `D-block JEE Advanced notes, Lesson ${lesson.number}: ${lesson.title}.` } : {}; }
export default async function DBlockPartPage({ params }: { params: Promise<{ part: string }> }) { const lesson = dBlockLessonBySlug((await params).part); if (!lesson) notFound(); return <ChapterShell kicker="JEE Inorganic Chemistry" subtitle="D-block Elements" tabs={dBlockTabs(lesson.number)}><ChapterPartStrip hubHref="/notes/d-block" hubLabel="D-block — all lessons" positionLabel={`Lesson ${lesson.number} of ${D_BLOCK_LESSONS.length}`}/><article className="mx-auto max-w-5xl space-y-6 text-white"><header style={{ background: "#122232", border: "1px solid #24405c", borderLeft: "4px solid #5fd4ea", borderRadius: 13, padding: "18px 20px" }}><p style={{ color: "#5fd4ea", fontSize: 11.5, fontWeight: 900, letterSpacing: ".14em", textTransform: "uppercase" }}>D-block Elements · Lesson {lesson.number} · {lesson.group}</p><h1 style={{ marginTop: 8, color: "#eef3f8", fontSize: 30, fontWeight: 900, lineHeight: 1.15, fontFamily: "Georgia, 'Iowan Old Style', 'Times New Roman', serif" }}>{lesson.title}</h1></header><div className="space-y-5 rounded-3xl border border-[#24405c] bg-[#122232]/60 px-5 py-8 sm:px-8 lg:px-10"><DBlockVisual kind={lesson.visual}/><DBlockMarkdown markdown={lesson.markdown}/></div><ChapterLessonPager prev={dBlockLessonRef(lesson.number - 1)} next={dBlockLessonRef(lesson.number + 1)} hubHref="/notes/d-block" hubLabel="All lessons"/></article></ChapterShell>; }
