import type { Mechanism } from "@/lib/mechanismSchema";
import { SCHEMA_VERSION } from "@/lib/mechanismSchema";

// Hand-authored reference implementation (benchmark + offline-verifiable).
// Example used: 2 × ethyl acetate → acetoin (3-hydroxybutan-2-one).
export const ACYLOIN: Mechanism = {
  schemaVersion: SCHEMA_VERSION,
  slug: "acyloin-condensation",
  name: "Acyloin Condensation",
  category: "named-reaction",
  dashboard: {
    reactionType: "Reductive coupling (radical)",
    difficulty: "Hard",
    examFrequency: "Medium",
    reagents: ["Na metal", "dry inert solvent (xylene/toluene)", "then H₃O⁺"],
    products: ["α-Hydroxy ketone (acyloin)"],
    chapter: "Carboxylic acid derivatives — esters",
    mechanismType: "SET → radical coupling",
    rds: "Ketyl–ketyl radical coupling",
    stereochemistry: "α-Carbon becomes a stereocentre → racemic",
    conditions: "Anhydrous, inert atmosphere, Na dispersion",
    timeToLearn: "8 min",
  },
  flowMap: [
    { label: "Ester", kind: "reactant" },
    { label: "Na (SET)", kind: "reagent" },
    { label: "Ketyl radical", kind: "intermediate" },
    { label: "Radical coupling", kind: "transition" },
    { label: "1,2-Diketone", kind: "intermediate" },
    { label: "2e⁻ reduction", kind: "transition" },
    { label: "Ene-diolate", kind: "intermediate" },
    { label: "H₃O⁺ workup", kind: "transition" },
    { label: "Acyloin", kind: "product" },
  ],
  steps: [
    {
      n: 1,
      title: "Single electron transfer (SET)",
      beforeSmiles: "CC(=O)OCC",
      afterSmiles: "C[C]([O-])OCC",
      electronMove: "Na donates 1 e⁻ into the C=O π* → ketyl radical anion",
      intermediate: "Ketyl radical anion",
      reason: "Na is a strong 1e⁻ reductant; the carbonyl π* accepts the electron",
      trap: "It is SET (radical), not nucleophilic acyl substitution",
      hook: "Ketyl = ketone + radical",
    },
    {
      n: 2,
      title: "Radical coupling",
      beforeSmiles: "C[C]([O-])OCC",
      afterSmiles: "CCOC([O-])(C)C(C)([O-])OCC",
      electronMove: "Two ketyl carbons pair (C•＋•C) → new C–C σ bond",
      intermediate: "1,2-Dialkoxide dimer",
      reason: "Radical–radical coupling builds the central C–C bond (the RDS)",
      trap: "Coupling happens at carbon, not at oxygen",
      hook: "Two radicals shake hands",
    },
    {
      n: 3,
      title: "Alkoxide elimination",
      beforeSmiles: "CCOC([O-])(C)C(C)([O-])OCC",
      afterSmiles: "CC(=O)C(=O)C",
      electronMove: "Each alkoxide expels ⁻OEt, reforming two C=O",
      intermediate: "1,2-Diketone (butane-2,3-dione)",
      reason: "Alkoxide collapses to carbonyl, ejecting ethoxide",
      trap: "Both OEt groups leave — not one",
    },
    {
      n: 4,
      title: "Second reduction",
      beforeSmiles: "CC(=O)C(=O)C",
      afterSmiles: "CC([O-])=C([O-])C",
      electronMove: "2 more e⁻ from Na reduce the 1,2-diketone → ene-diolate",
      intermediate: "Ene-diolate dianion",
      reason: "Excess Na keeps reducing the easily-reduced 1,2-diketone",
      hook: "Diketone is a great electron sink",
    },
    {
      n: 5,
      title: "Acid workup",
      beforeSmiles: "CC([O-])=C([O-])C",
      afterSmiles: "CC(=O)C(O)C",
      electronMove: "H₃O⁺ protonates O; keto–enol tautomerism fixes the product",
      intermediate: "Acyloin (α-hydroxy ketone)",
      reason: "Protonation + tautomerisation gives the α-hydroxy ketone",
      trap: "Product is an α-hydroxy ketone, NOT a 1,2-diol",
      hook: "Acyl + -oin → α-hydroxy ketone",
    },
  ],
  quickView: {
    reaction: "2 esters + Na → acyloin (α-hydroxy ketone)",
    keyIntermediate: "Ketyl radical anion",
    rds: "Ketyl–ketyl radical coupling",
    keyReagent: "Sodium metal (1e⁻ reductant)",
    trap: "Radical SET — not nucleophilic acyl substitution",
    mnemonic: "Ketyl couples, ethoxide leaves, workup gives acyloin",
  },
  stereochemistry: {
    applicable: true,
    summary: "The α-carbon (CHOH) becomes a stereocentre formed without facial bias → racemic.",
    outcomes: ["Racemic α-hydroxy ketone", "Intramolecular variant builds large rings"],
  },
  examples: [
    { tier: "Basic", prompt: "Product of acyloin condensation of ethyl acetate?", answer: "Acetoin (3-hydroxybutan-2-one)" },
    { tier: "Basic", prompt: "Reagent for acyloin condensation?", answer: "Sodium metal in dry, inert solvent" },
    { tier: "JEE Main", prompt: "Key intermediate?", answer: "Ketyl radical anion" },
    { tier: "JEE Advanced", prompt: "Why high dilution for intramolecular (diester) acyloin?", answer: "Favours intramolecular coupling on the Na surface → large rings" },
    { tier: "JEE Advanced", prompt: "Role of TMSCl (Rühlmann modification)?", answer: "Traps the ene-diolate as a bis(silyl enol ether), boosting yield" },
    { tier: "Olympiad", prompt: "Acyloin vs benzoin condensation — mechanism?", answer: "Acyloin: Na SET/radical; Benzoin: CN⁻/NHC nucleophilic (umpolung)" },
    { tier: "PYQ", prompt: "Acyloin condensation is classified as?", answer: "Reductive (radical) coupling of esters" },
  ],
  relatedReactions: [
    "Benzoin Condensation",
    "Pinacol Coupling Reaction",
    "McMurry Reaction",
    "Bouveault-Blanc Reduction",
    "Birch Reduction",
  ],
};
