import { z } from "zod";
import { mechanismGeometrySamples } from "./data";
import type { MechanismGeometry } from "./schema";

export const MechanismPracticeSkillSchema = z.enum([
  "mechanism-step-identification",
  "intermediate-recognition",
  "nucleophile-base-role",
  "stereochemistry-outcome",
  "rate-determining-step",
  "product-prediction",
]);

export const MechanismQuestionTypeSchema = z.enum(["mcq", "assertion-reason", "product-prediction"]);

export const MechanismPracticeQuestionSchema = z.object({
  id: z.string().min(1),
  reactionClass: z.enum(["SN1", "SN2", "E2"]),
  skill: MechanismPracticeSkillSchema,
  questionType: MechanismQuestionTypeSchema.default("mcq"),
  prompt: z.string().min(1),
  options: z.array(z.object({
    id: z.string().min(1),
    label: z.string().min(1),
  })).min(2),
  correctOptionId: z.string().min(1),
  explanation: z.string().min(1),
  source: z.enum(["geometry-derived", "conceptual"]),
  auditNote: z.string().min(1),
  linkedStepId: z.string().optional(),
  linkedFrameId: z.string().optional(),
  linkedArrowId: z.string().optional(),
  linkedMarkerId: z.string().optional(),
  linkedOrbitalOverlapId: z.string().optional(),
});

export type MechanismPracticeSkill = z.infer<typeof MechanismPracticeSkillSchema>;
export type MechanismQuestionType = z.infer<typeof MechanismQuestionTypeSchema>;
export type MechanismPracticeQuestion = z.infer<typeof MechanismPracticeQuestionSchema>;

const q = (question: z.input<typeof MechanismPracticeQuestionSchema>) => MechanismPracticeQuestionSchema.parse(question);

export const mechanismPracticeQuestions = [
  q({
    id: "sn1-step-rds",
    reactionClass: "SN1",
    skill: "mechanism-step-identification",
    prompt: "In the verified SN1 sample, which step happens first?",
    options: [
      { id: "a", label: "Water attacks before chloride leaves" },
      { id: "b", label: "The C-Cl bond ionises to form a carbocation" },
      { id: "c", label: "A beta hydrogen is removed by base" },
      { id: "d", label: "A concerted backside attack occurs" },
    ],
    correctOptionId: "b",
    explanation: "SN1 begins with leaving-group ionisation. The C-Cl bond electrons move to chlorine, forming chloride and a carbocation.",
    source: "geometry-derived",
    auditNote: "Derived from the verified SN1 ionisation step and curved-arrow source/target.",
    linkedStepId: "sn1-ionization",
    linkedFrameId: "sn1-reactant",
    linkedArrowId: "sn1-arrow-ionization",
  }),
  q({
    id: "sn1-intermediate",
    reactionClass: "SN1",
    skill: "intermediate-recognition",
    prompt: "Which intermediate is explicitly shown in the SN1 geometry sample?",
    options: [
      { id: "a", label: "Planar tert-butyl carbocation" },
      { id: "b", label: "Pentavalent carbon transition state" },
      { id: "c", label: "Carbanion" },
      { id: "d", label: "Bromonium ion" },
    ],
    correctOptionId: "a",
    explanation: "The sample includes a frame labeled planar tert-butyl carbocation with an empty p orbital marker.",
    source: "geometry-derived",
    auditNote: "Derived from the verified frame role and empty-p-orbital metadata.",
    linkedStepId: "sn1-ionization",
    linkedFrameId: "sn1-carbocation",
    linkedOrbitalOverlapId: "sn1-empty-p",
  }),
  q({
    id: "sn1-nucleophile-role",
    reactionClass: "SN1",
    skill: "nucleophile-base-role",
    prompt: "What is water doing in the second SN1 step?",
    options: [
      { id: "a", label: "Acting as a nucleophile that donates a lone pair to the carbocation" },
      { id: "b", label: "Removing a beta hydrogen as a strong base" },
      { id: "c", label: "Leaving with the bonding electron pair" },
      { id: "d", label: "Forming a pi bond between two carbons" },
    ],
    correctOptionId: "a",
    explanation: "Water donates a lone pair into the electron-deficient carbocation center to form a C-O bond.",
    source: "geometry-derived",
    auditNote: "Linked to the verified water lone-pair attack arrow.",
    linkedStepId: "sn1-nucleophile-attack",
    linkedFrameId: "sn1-attack-frame",
    linkedArrowId: "sn1-arrow-water",
  }),
  q({
    id: "sn1-stereo",
    reactionClass: "SN1",
    skill: "stereochemistry-outcome",
    prompt: "Why can an SN1 reaction show racemization at a stereogenic reacting carbon?",
    options: [
      { id: "a", label: "The carbocation is planar and can be attacked from either face" },
      { id: "b", label: "Backside attack forces one inversion pathway only" },
      { id: "c", label: "The beta C-H bond must be anti-periplanar" },
      { id: "d", label: "The leaving group never departs" },
    ],
    correctOptionId: "a",
    explanation: "The SN1 geometry sample marks the carbocation as planar, so nucleophile attack can occur from either face.",
    source: "geometry-derived",
    auditNote: "Derived from the verified planar/racemization stereochemistry markers.",
    linkedStepId: "sn1-ionization",
    linkedFrameId: "sn1-carbocation",
    linkedMarkerId: "sn1-racemization",
  }),
  q({
    id: "sn1-rds",
    reactionClass: "SN1",
    skill: "rate-determining-step",
    prompt: "For the SN1 sample, which event is the rate-determining step?",
    options: [
      { id: "a", label: "Leaving group ionisation" },
      { id: "b", label: "Final deprotonation only" },
      { id: "c", label: "Concerted beta-hydrogen removal" },
      { id: "d", label: "Backside collision of nucleophile and substrate" },
    ],
    correctOptionId: "a",
    explanation: "SN1 rate depends on substrate ionisation because carbocation formation is the slow first step.",
    source: "conceptual",
    auditNote: "Conceptual NCERT/JEE mechanism fact linked to the verified ionisation step; not a geometric measurement.",
    linkedStepId: "sn1-ionization",
  }),
  q({
    id: "sn1-product",
    reactionClass: "SN1",
    skill: "product-prediction",
    questionType: "product-prediction",
    prompt: "What product class follows when water captures the tert-butyl carbocation and deprotonation occurs?",
    options: [
      { id: "a", label: "Tertiary alcohol" },
      { id: "b", label: "Alkene only" },
      { id: "c", label: "Vicinal dibromide" },
      { id: "d", label: "Terminal alkyne" },
    ],
    correctOptionId: "a",
    explanation: "Water attack forms a C-O bond at the carbocation; after proton transfer, the solvolysis product is a tertiary alcohol.",
    source: "conceptual",
    auditNote: "Conceptual product prediction from the verified water attack step; deprotonation frame is not separately drawn.",
    linkedStepId: "sn1-nucleophile-attack",
    linkedArrowId: "sn1-arrow-water",
  }),

  q({
    id: "sn2-step",
    reactionClass: "SN2",
    skill: "mechanism-step-identification",
    prompt: "Which phrase best describes the SN2 geometry sample?",
    options: [
      { id: "a", label: "Two-step carbocation formation followed by attack" },
      { id: "b", label: "Concerted backside attack with simultaneous leaving-group departure" },
      { id: "c", label: "Base removes beta hydrogen while pi bond forms" },
      { id: "d", label: "Radical chain substitution" },
    ],
    correctOptionId: "b",
    explanation: "The SN2 sample has one concerted step with nucleophile attack and C-Br bond cleavage in the same transition state.",
    source: "geometry-derived",
    auditNote: "Derived from the verified SN2 transition-state frame and two curved arrows.",
    linkedStepId: "sn2-concerted-step",
    linkedFrameId: "sn2-transition",
    linkedArrowId: "sn2-arrow-attack",
  }),
  q({
    id: "sn2-intermediate",
    reactionClass: "SN2",
    skill: "intermediate-recognition",
    prompt: "Which intermediate is present in the verified SN2 sample?",
    options: [
      { id: "a", label: "No discrete intermediate is shown" },
      { id: "b", label: "Planar carbocation" },
      { id: "c", label: "Carbanion" },
      { id: "d", label: "Free radical" },
    ],
    correctOptionId: "a",
    explanation: "SN2 is concerted. The sample shows reactant, transition state, and product, but no discrete carbocation or carbanion intermediate.",
    source: "geometry-derived",
    auditNote: "Derived from frame roles in the SN2 sample.",
    linkedStepId: "sn2-concerted-step",
    linkedFrameId: "sn2-transition",
  }),
  q({
    id: "sn2-nucleophile",
    reactionClass: "SN2",
    skill: "nucleophile-base-role",
    prompt: "What is hydroxide doing in the SN2 sample?",
    options: [
      { id: "a", label: "Acting as a nucleophile attacking the alpha carbon" },
      { id: "b", label: "Acting only as a bulky base" },
      { id: "c", label: "Leaving as bromide" },
      { id: "d", label: "Forming an empty p orbital" },
    ],
    correctOptionId: "a",
    explanation: "The hydroxide lone pair attacks the carbon bearing bromine from the backside.",
    source: "geometry-derived",
    auditNote: "Linked to the verified hydroxide lone-pair attack arrow.",
    linkedStepId: "sn2-concerted-step",
    linkedFrameId: "sn2-reactant",
    linkedArrowId: "sn2-arrow-attack",
  }),
  q({
    id: "sn2-stereo",
    reactionClass: "SN2",
    skill: "stereochemistry-outcome",
    prompt: "What stereochemical outcome is tied to backside SN2 attack on a chiral center?",
    options: [
      { id: "a", label: "Inversion of configuration" },
      { id: "b", label: "Complete racemization through planar carbocation" },
      { id: "c", label: "Retention only" },
      { id: "d", label: "No stereochemical consequence is possible" },
    ],
    correctOptionId: "a",
    explanation: "The SN2 sample includes an inversion marker because backside attack inverts configuration at a chiral alpha carbon.",
    source: "geometry-derived",
    auditNote: "Derived from the verified SN2 inversion stereochemistry marker.",
    linkedStepId: "sn2-concerted-step",
    linkedFrameId: "sn2-reactant",
    linkedMarkerId: "sn2-inversion-marker",
  }),
  q({
    id: "sn2-rds",
    reactionClass: "SN2",
    skill: "rate-determining-step",
    prompt: "What is the rate-determining step in the SN2 sample?",
    options: [
      { id: "a", label: "The single concerted substitution step" },
      { id: "b", label: "Slow carbocation rearrangement" },
      { id: "c", label: "Separate ionisation before attack" },
      { id: "d", label: "Final acid workup" },
    ],
    correctOptionId: "a",
    explanation: "SN2 has one concerted step, so bond formation and leaving-group departure occur in the rate-determining event.",
    source: "conceptual",
    auditNote: "Conceptual rate-law/mechanism fact linked to the verified concerted transition-state frame.",
    linkedStepId: "sn2-concerted-step",
    linkedFrameId: "sn2-transition",
  }),
  q({
    id: "sn2-product",
    reactionClass: "SN2",
    skill: "product-prediction",
    questionType: "product-prediction",
    prompt: "In the SN2 hydroxide plus bromomethane sample, what product is shown after substitution?",
    options: [
      { id: "a", label: "Methanol plus bromide" },
      { id: "b", label: "tert-Butyl alcohol" },
      { id: "c", label: "Ethene plus bromide" },
      { id: "d", label: "Bromonium ion" },
    ],
    correctOptionId: "a",
    explanation: "The product frame shows an O-C bond in methanol and a separate bromide ion.",
    source: "geometry-derived",
    auditNote: "Derived from the verified SN2 product frame.",
    linkedStepId: "sn2-concerted-step",
    linkedFrameId: "sn2-product",
  }),

  q({
    id: "e2-step",
    reactionClass: "E2",
    skill: "mechanism-step-identification",
    prompt: "Which step pattern matches the E2 geometry sample?",
    options: [
      { id: "a", label: "Concerted beta-H abstraction, pi-bond formation, and leaving-group departure" },
      { id: "b", label: "Carbocation formation followed by water attack" },
      { id: "c", label: "Backside substitution at the alpha carbon only" },
      { id: "d", label: "Ozonide formation and reductive workup" },
    ],
    correctOptionId: "a",
    explanation: "The E2 sample has one concerted elimination step with three verified arrows.",
    source: "geometry-derived",
    auditNote: "Derived from E2 curved arrows for base attack, pi-bond formation, and leaving-group departure.",
    linkedStepId: "e2-concerted-elimination",
    linkedFrameId: "e2-reactant",
    linkedArrowId: "e2-arrow-pi",
  }),
  q({
    id: "e2-intermediate",
    reactionClass: "E2",
    skill: "intermediate-recognition",
    prompt: "Which discrete intermediate is shown in the E2 sample?",
    options: [
      { id: "a", label: "No discrete intermediate is shown" },
      { id: "b", label: "Planar carbocation" },
      { id: "c", label: "Carbanion intermediate" },
      { id: "d", label: "Ketyl radical" },
    ],
    correctOptionId: "a",
    explanation: "E2 is concerted. The sample shows a reactant-like frame and a transition-state frame, not a discrete intermediate.",
    source: "geometry-derived",
    auditNote: "Derived from E2 frame roles.",
    linkedStepId: "e2-concerted-elimination",
    linkedFrameId: "e2-transition",
  }),
  q({
    id: "e2-base",
    reactionClass: "E2",
    skill: "nucleophile-base-role",
    prompt: "What is ethoxide doing in the E2 sample?",
    options: [
      { id: "a", label: "Acting as a base that removes a beta hydrogen" },
      { id: "b", label: "Leaving as bromide" },
      { id: "c", label: "Attacking the alpha carbon as the only event" },
      { id: "d", label: "Stabilising an ozonide" },
    ],
    correctOptionId: "a",
    explanation: "The base lone pair forms an O-H bond to the beta hydrogen while elimination proceeds.",
    source: "geometry-derived",
    auditNote: "Linked to the verified base-to-beta-H arrow.",
    linkedStepId: "e2-concerted-elimination",
    linkedFrameId: "e2-reactant",
    linkedArrowId: "e2-arrow-base",
  }),
  q({
    id: "e2-stereo",
    reactionClass: "E2",
    skill: "stereochemistry-outcome",
    prompt: "Which geometric relationship is marked as important for the E2 sample?",
    options: [
      { id: "a", label: "Anti-periplanar beta C-H and C-Br alignment" },
      { id: "b", label: "Planar carbocation attack from both faces" },
      { id: "c", label: "Backside attack causing Walden inversion" },
      { id: "d", label: "Syn addition across a double bond" },
    ],
    correctOptionId: "a",
    explanation: "The E2 sample marks anti-periplanar alignment because the C-H sigma bond must align with the C-Br sigma-star orbital.",
    source: "geometry-derived",
    auditNote: "Derived from the verified anti-periplanar stereochemistry marker and orbital overlap metadata.",
    linkedStepId: "e2-concerted-elimination",
    linkedFrameId: "e2-reactant",
    linkedMarkerId: "e2-anti",
    linkedOrbitalOverlapId: "e2-sigma-overlap",
  }),
  q({
    id: "e2-rds",
    reactionClass: "E2",
    skill: "rate-determining-step",
    prompt: "What is the rate-determining event in the E2 sample?",
    options: [
      { id: "a", label: "The one concerted elimination transition state" },
      { id: "b", label: "Slow carbocation ionisation" },
      { id: "c", label: "A separate nucleophile capture step" },
      { id: "d", label: "Final protonation after an intermediate" },
    ],
    correctOptionId: "a",
    explanation: "E2 is a one-step elimination; the transition state includes C-H breaking, C=C formation, and C-Br breaking.",
    source: "conceptual",
    auditNote: "Conceptual kinetics fact linked to the verified E2 transition-state frame.",
    linkedStepId: "e2-concerted-elimination",
    linkedFrameId: "e2-transition",
  }),
  q({
    id: "e2-product",
    reactionClass: "E2",
    skill: "product-prediction",
    questionType: "product-prediction",
    prompt: "What product type is formed by the E2 dehydrohalogenation shown?",
    options: [
      { id: "a", label: "Alkene" },
      { id: "b", label: "Alcohol by substitution" },
      { id: "c", label: "Carbocation salt" },
      { id: "d", label: "Vicinal diol" },
    ],
    correctOptionId: "a",
    explanation: "The C-H bond electrons form a C=C pi bond while bromide leaves, giving an alkene product type.",
    source: "geometry-derived",
    auditNote: "Derived from the verified E2 pi-bond formation arrow.",
    linkedStepId: "e2-concerted-elimination",
    linkedArrowId: "e2-arrow-pi",
  }),

  q({
    id: "sn1-substrate-choice",
    reactionClass: "SN1",
    skill: "mechanism-step-identification",
    prompt: "Which substrate pattern best supports the SN1 pathway in exam conditions?",
    options: [
      { id: "a", label: "Tertiary alkyl halide in polar protic solvent" },
      { id: "b", label: "Methyl halide with strong nucleophile" },
      { id: "c", label: "Primary halide with bulky base and heat" },
      { id: "d", label: "Alkene with bromine water" },
    ],
    correctOptionId: "a",
    explanation: "SN1 is favoured when ionisation gives a stable carbocation; tertiary substrates are the classic exam case.",
    source: "conceptual",
    auditNote: "Conceptual substrate-order question linked to the verified carbocation intermediate frame.",
    linkedFrameId: "sn1-carbocation",
  }),
  q({
    id: "sn1-solvent-role",
    reactionClass: "SN1",
    skill: "nucleophile-base-role",
    prompt: "Why does polar protic solvent support an SN1 mechanism?",
    options: [
      { id: "a", label: "It stabilises ions formed during leaving-group ionisation" },
      { id: "b", label: "It forces backside attack" },
      { id: "c", label: "It prevents carbocation formation" },
      { id: "d", label: "It creates anti-periplanar beta hydrogens" },
    ],
    correctOptionId: "a",
    explanation: "SN1 begins by ionising the C-LG bond, and polar protic solvent stabilises the ion pair.",
    source: "conceptual",
    auditNote: "Conceptual solvent effect linked to the verified ionisation step; not a measured geometry claim.",
    linkedStepId: "sn1-ionization",
  }),
  q({
    id: "sn1-assertion-rate",
    reactionClass: "SN1",
    skill: "rate-determining-step",
    questionType: "assertion-reason",
    prompt: "Assertion: SN1 rate is independent of nucleophile concentration. Reason: The slow step is carbocation formation by leaving-group ionisation.",
    options: [
      { id: "a", label: "Both are true, and the reason explains the assertion" },
      { id: "b", label: "Both are true, but the reason does not explain the assertion" },
      { id: "c", label: "Assertion is true, reason is false" },
      { id: "d", label: "Assertion is false, reason is true" },
    ],
    correctOptionId: "a",
    explanation: "The rate-determining ionisation step involves only the substrate, so nucleophile concentration is absent from the rate law.",
    source: "conceptual",
    auditNote: "Conceptual kinetics question linked to the verified leaving-group ionisation step.",
    linkedStepId: "sn1-ionization",
  }),
  q({
    id: "sn1-assertion-racemization",
    reactionClass: "SN1",
    skill: "stereochemistry-outcome",
    questionType: "assertion-reason",
    prompt: "Assertion: SN1 at a chiral centre can give racemization tendency. Reason: The intermediate carbocation is planar.",
    options: [
      { id: "a", label: "Both are true, and the reason explains the assertion" },
      { id: "b", label: "Both are true, but unrelated" },
      { id: "c", label: "Assertion is false, reason is true" },
      { id: "d", label: "Both are false" },
    ],
    correctOptionId: "a",
    explanation: "Planarity allows attack from either face, which explains racemization tendency.",
    source: "geometry-derived",
    auditNote: "Derived from the verified planar carbocation and racemization marker.",
    linkedFrameId: "sn1-carbocation",
    linkedMarkerId: "sn1-racemization",
  }),
  q({
    id: "sn1-product-tertiary-alcohol",
    reactionClass: "SN1",
    skill: "product-prediction",
    questionType: "product-prediction",
    prompt: "tert-Butyl chloride reacts with water under solvolysis conditions. What is the main substitution product class?",
    options: [
      { id: "a", label: "Tertiary alcohol" },
      { id: "b", label: "Primary alcohol" },
      { id: "c", label: "Alkyne" },
      { id: "d", label: "Epoxide" },
    ],
    correctOptionId: "a",
    explanation: "Ionisation gives tert-butyl carbocation, water attacks, and deprotonation gives tert-butanol.",
    source: "conceptual",
    auditNote: "Conceptual product prediction based on the verified SN1 water-attack step.",
    linkedStepId: "sn1-nucleophile-attack",
    linkedArrowId: "sn1-arrow-water",
  }),
  q({
    id: "sn1-product-rearrangement-warning",
    reactionClass: "SN1",
    skill: "product-prediction",
    questionType: "product-prediction",
    prompt: "An SN1 substrate can rearrange to a more stable carbocation. What should be checked before naming the final product?",
    options: [
      { id: "a", label: "Possible hydride or alkyl shift before nucleophile capture" },
      { id: "b", label: "Mandatory backside attack" },
      { id: "c", label: "Anti-periplanar beta hydrogen only" },
      { id: "d", label: "Formation of a bromonium ion" },
    ],
    correctOptionId: "a",
    explanation: "Because SN1 has a discrete carbocation, rearrangement can alter the carbon skeleton before product formation.",
    source: "conceptual",
    auditNote: "Conceptual rearrangement trap linked to the verified carbocation frame; no rearrangement geometry is drawn.",
    linkedFrameId: "sn1-carbocation",
  }),
  q({
    id: "sn1-competition-e2",
    reactionClass: "SN1",
    skill: "mechanism-step-identification",
    prompt: "Which condition should make you recheck SN1 against elimination competition?",
    options: [
      { id: "a", label: "Strong base or heat with a tertiary substrate" },
      { id: "b", label: "Weak nucleophile in polar protic solvent" },
      { id: "c", label: "Stable carbocation formation without base" },
      { id: "d", label: "Solvolysis in water only" },
    ],
    correctOptionId: "a",
    explanation: "Strong base or heat can shift tertiary substrates toward elimination rather than clean SN1 substitution.",
    source: "conceptual",
    auditNote: "Conceptual competition rule; no E1/E2 branching geometry is drawn in the SN1 sample.",
  }),
  q({
    id: "sn1-leaving-group",
    reactionClass: "SN1",
    skill: "mechanism-step-identification",
    prompt: "Which feature is necessary for the first SN1 step to occur readily?",
    options: [
      { id: "a", label: "A leaving group able to depart with the bonding electron pair" },
      { id: "b", label: "A bulky base removing beta hydrogen first" },
      { id: "c", label: "A mandatory backside attack path" },
      { id: "d", label: "A pi bond already present in the substrate" },
    ],
    correctOptionId: "a",
    explanation: "The verified first step is ionisation of the C-Cl bond, so leaving-group ability matters.",
    source: "geometry-derived",
    auditNote: "Derived from the verified C-Cl ionisation arrow.",
    linkedStepId: "sn1-ionization",
    linkedArrowId: "sn1-arrow-ionization",
  }),
  q({
    id: "sn1-planar-attack",
    reactionClass: "SN1",
    skill: "intermediate-recognition",
    prompt: "In the SN1 sample, what geometry at the carbocation explains attack from either face?",
    options: [
      { id: "a", label: "Planar carbocation with an empty p orbital" },
      { id: "b", label: "Tetrahedral pentavalent transition state" },
      { id: "c", label: "Linear alkyne carbon" },
      { id: "d", label: "Anti-periplanar C-H and C-Br bonds" },
    ],
    correctOptionId: "a",
    explanation: "The carbocation frame marks planarity and empty p orbital character.",
    source: "geometry-derived",
    auditNote: "Derived from verified SN1 carbocation frame and orbital metadata.",
    linkedFrameId: "sn1-carbocation",
    linkedOrbitalOverlapId: "sn1-empty-p",
  }),

  q({
    id: "sn2-substrate-choice",
    reactionClass: "SN2",
    skill: "mechanism-step-identification",
    prompt: "Which substrate is most favourable for a standard SN2 exam question?",
    options: [
      { id: "a", label: "Methyl or primary alkyl halide" },
      { id: "b", label: "Tertiary alkyl halide" },
      { id: "c", label: "Tertiary alcohol in water" },
      { id: "d", label: "A substrate with no leaving group" },
    ],
    correctOptionId: "a",
    explanation: "Low steric hindrance allows backside attack, making methyl and primary substrates favourable.",
    source: "conceptual",
    auditNote: "Conceptual substrate-order question linked to verified backside attack geometry.",
    linkedArrowId: "sn2-arrow-attack",
  }),
  q({
    id: "sn2-solvent-role",
    reactionClass: "SN2",
    skill: "nucleophile-base-role",
    prompt: "Which solvent pattern usually supports SN2 by keeping anionic nucleophiles strong?",
    options: [
      { id: "a", label: "Polar aprotic solvent" },
      { id: "b", label: "Strongly ionising polar protic solvent only" },
      { id: "c", label: "No solvent effect exists" },
      { id: "d", label: "Only alcoholic base with heat" },
    ],
    correctOptionId: "a",
    explanation: "Polar aprotic solvents are the standard exam condition that favours many SN2 reactions.",
    source: "conceptual",
    auditNote: "Conceptual solvent effect; not a geometry measurement.",
  }),
  q({
    id: "sn2-assertion-rate",
    reactionClass: "SN2",
    skill: "rate-determining-step",
    questionType: "assertion-reason",
    prompt: "Assertion: SN2 rate depends on both substrate and nucleophile. Reason: Bond formation and leaving-group departure occur in one concerted step.",
    options: [
      { id: "a", label: "Both are true, and the reason explains the assertion" },
      { id: "b", label: "Both are true, but unrelated" },
      { id: "c", label: "Assertion is true, reason is false" },
      { id: "d", label: "Assertion is false, reason is true" },
    ],
    correctOptionId: "a",
    explanation: "The nucleophile participates in the rate-determining collision, so the rate law is bimolecular.",
    source: "geometry-derived",
    auditNote: "Derived from the verified concerted transition-state frame with nucleophile attack.",
    linkedStepId: "sn2-concerted-step",
    linkedFrameId: "sn2-transition",
  }),
  q({
    id: "sn2-assertion-inversion",
    reactionClass: "SN2",
    skill: "stereochemistry-outcome",
    questionType: "assertion-reason",
    prompt: "Assertion: SN2 gives inversion at a chiral reacting carbon. Reason: The nucleophile attacks from the backside.",
    options: [
      { id: "a", label: "Both are true, and the reason explains the assertion" },
      { id: "b", label: "Both are true, but unrelated" },
      { id: "c", label: "Assertion is false, reason is true" },
      { id: "d", label: "Both are false" },
    ],
    correctOptionId: "a",
    explanation: "Backside attack forces the geometry to invert at the reacting centre.",
    source: "geometry-derived",
    auditNote: "Derived from verified backside attack and inversion marker.",
    linkedArrowId: "sn2-arrow-attack",
    linkedMarkerId: "sn2-inversion-marker",
  }),
  q({
    id: "sn2-product-alkyl-iodide",
    reactionClass: "SN2",
    skill: "product-prediction",
    questionType: "product-prediction",
    prompt: "A primary alkyl bromide reacts with iodide ion in acetone. What product pattern is expected?",
    options: [
      { id: "a", label: "Alkyl iodide by substitution" },
      { id: "b", label: "Alkene by mandatory elimination" },
      { id: "c", label: "Racemized alcohol" },
      { id: "d", label: "Carbocation rearranged product" },
    ],
    correctOptionId: "a",
    explanation: "Iodide is a strong nucleophile in polar aprotic acetone, favouring SN2 substitution.",
    source: "conceptual",
    auditNote: "Conceptual product prediction based on SN2 solvent/nucleophile rules; sample geometry uses hydroxide plus bromomethane.",
  }),
  q({
    id: "sn2-product-alcohol",
    reactionClass: "SN2",
    skill: "product-prediction",
    questionType: "product-prediction",
    prompt: "Bromomethane reacts with hydroxide by SN2. Which product is expected?",
    options: [
      { id: "a", label: "Methanol" },
      { id: "b", label: "tert-Butyl alcohol" },
      { id: "c", label: "Ethene" },
      { id: "d", label: "Acetone" },
    ],
    correctOptionId: "a",
    explanation: "The verified SN2 sample shows hydroxide replacing bromide to form methanol.",
    source: "geometry-derived",
    auditNote: "Derived from the verified SN2 product frame.",
    linkedFrameId: "sn2-product",
  }),
  q({
    id: "sn2-no-rearrangement",
    reactionClass: "SN2",
    skill: "intermediate-recognition",
    prompt: "Why are carbocation rearrangements absent in SN2?",
    options: [
      { id: "a", label: "No discrete carbocation intermediate forms" },
      { id: "b", label: "The carbocation rearranges instantly" },
      { id: "c", label: "The solvent blocks the leaving group" },
      { id: "d", label: "The product is always an alkene" },
    ],
    correctOptionId: "a",
    explanation: "SN2 is concerted, so there is no carbocation intermediate that could rearrange.",
    source: "geometry-derived",
    auditNote: "Derived from verified SN2 frame roles.",
    linkedFrameId: "sn2-transition",
  }),
  q({
    id: "sn2-bulky-warning",
    reactionClass: "SN2",
    skill: "nucleophile-base-role",
    prompt: "A secondary alkyl halide is treated with tert-butoxide. What should you check before choosing SN2?",
    options: [
      { id: "a", label: "Bulky base may favour E2 instead" },
      { id: "b", label: "A carbocation must always form first" },
      { id: "c", label: "Racemization is mandatory" },
      { id: "d", label: "No leaving group is needed" },
    ],
    correctOptionId: "a",
    explanation: "Bulky bases are poor backside attackers and often push secondary substrates toward elimination.",
    source: "conceptual",
    auditNote: "Conceptual competition rule; no tert-butoxide geometry is drawn.",
  }),
  q({
    id: "sn2-transition-state",
    reactionClass: "SN2",
    skill: "mechanism-step-identification",
    prompt: "What does the SN2 transition state contain?",
    options: [
      { id: "a", label: "Partial bond to nucleophile and partial bond to leaving group" },
      { id: "b", label: "A fully formed free carbocation" },
      { id: "c", label: "A separate carbanion intermediate" },
      { id: "d", label: "Only a beta C-H bond breaking" },
    ],
    correctOptionId: "a",
    explanation: "The transition-state frame marks simultaneous bond formation and bond breaking.",
    source: "geometry-derived",
    auditNote: "Derived from verified SN2 transition-state frame.",
    linkedFrameId: "sn2-transition",
  }),

  q({
    id: "e2-substrate-choice",
    reactionClass: "E2",
    skill: "mechanism-step-identification",
    prompt: "Which condition strongly points toward E2 in a substitution-elimination choice?",
    options: [
      { id: "a", label: "Strong base with secondary or tertiary substrate" },
      { id: "b", label: "Weak nucleophile with methyl halide" },
      { id: "c", label: "Neutral water attacking a carbocation only" },
      { id: "d", label: "Bromine addition to alkene" },
    ],
    correctOptionId: "a",
    explanation: "E2 requires a strong base and is common for secondary/tertiary substrates.",
    source: "conceptual",
    auditNote: "Conceptual mechanism-selection rule linked to verified E2 base role.",
    linkedArrowId: "e2-arrow-base",
  }),
  q({
    id: "e2-heat-role",
    reactionClass: "E2",
    skill: "mechanism-step-identification",
    prompt: "In exam conditions, what does heat often do in a substitution versus elimination competition?",
    options: [
      { id: "a", label: "It increases elimination tendency" },
      { id: "b", label: "It guarantees SN2 inversion" },
      { id: "c", label: "It prevents alkene formation" },
      { id: "d", label: "It creates a carbocation in all substrates" },
    ],
    correctOptionId: "a",
    explanation: "Heat commonly favours elimination products in exam heuristics.",
    source: "conceptual",
    auditNote: "Conceptual exam-selection rule; not a geometry measurement.",
  }),
  q({
    id: "e2-assertion-rate",
    reactionClass: "E2",
    skill: "rate-determining-step",
    questionType: "assertion-reason",
    prompt: "Assertion: E2 is bimolecular. Reason: Substrate and base are both involved in the concerted transition state.",
    options: [
      { id: "a", label: "Both are true, and the reason explains the assertion" },
      { id: "b", label: "Both are true, but unrelated" },
      { id: "c", label: "Assertion is true, reason is false" },
      { id: "d", label: "Assertion is false, reason is true" },
    ],
    correctOptionId: "a",
    explanation: "The base removes beta hydrogen in the same rate-determining event where the leaving group departs.",
    source: "geometry-derived",
    auditNote: "Derived from the verified E2 transition-state frame and base arrow.",
    linkedFrameId: "e2-transition",
    linkedArrowId: "e2-arrow-base",
  }),
  q({
    id: "e2-assertion-anti",
    reactionClass: "E2",
    skill: "stereochemistry-outcome",
    questionType: "assertion-reason",
    prompt: "Assertion: Anti-periplanar beta H and leaving group alignment is important in standard E2. Reason: The sigma C-H bond must align for pi-bond formation as the leaving group departs.",
    options: [
      { id: "a", label: "Both are true, and the reason explains the assertion" },
      { id: "b", label: "Both are true, but unrelated" },
      { id: "c", label: "Assertion is false, reason is true" },
      { id: "d", label: "Both are false" },
    ],
    correctOptionId: "a",
    explanation: "The verified E2 sample marks anti-periplanar geometry and sigma overlap metadata.",
    source: "geometry-derived",
    auditNote: "Derived from anti-periplanar marker and orbital-overlap metadata.",
    linkedMarkerId: "e2-anti",
    linkedOrbitalOverlapId: "e2-sigma-overlap",
  }),
  q({
    id: "e2-product-zaitsev",
    reactionClass: "E2",
    skill: "product-prediction",
    questionType: "product-prediction",
    prompt: "With a small strong base, which alkene is usually major in a simple E2 exam question?",
    options: [
      { id: "a", label: "More substituted Zaitsev alkene" },
      { id: "b", label: "Less substituted Hofmann alkene always" },
      { id: "c", label: "Alcohol by substitution" },
      { id: "d", label: "Carbocation rearranged product" },
    ],
    correctOptionId: "a",
    explanation: "Small strong bases usually favour the more substituted alkene as the major E2 product.",
    source: "conceptual",
    auditNote: "Conceptual product rule; exact alkene structures are not drawn in the sample.",
  }),
  q({
    id: "e2-product-hofmann",
    reactionClass: "E2",
    skill: "product-prediction",
    questionType: "product-prediction",
    prompt: "A bulky strong base is used in E2. Which product trend becomes more likely?",
    options: [
      { id: "a", label: "Less substituted Hofmann alkene" },
      { id: "b", label: "Mandatory SN1 alcohol" },
      { id: "c", label: "Racemized substitution product only" },
      { id: "d", label: "Carbocation rearrangement first" },
    ],
    correctOptionId: "a",
    explanation: "Bulky bases remove more accessible beta hydrogens and can favour Hofmann product.",
    source: "conceptual",
    auditNote: "Conceptual bulky-base product rule; no bulky-base geometry is drawn.",
  }),
  q({
    id: "e2-no-beta-h",
    reactionClass: "E2",
    skill: "product-prediction",
    prompt: "What must be present for E2 alkene formation?",
    options: [
      { id: "a", label: "A beta hydrogen that the base can remove" },
      { id: "b", label: "A planar carbocation" },
      { id: "c", label: "A nucleophile attacking the alpha carbon only" },
      { id: "d", label: "A bromonium ion intermediate" },
    ],
    correctOptionId: "a",
    explanation: "The base removes a beta hydrogen while the leaving group departs and the pi bond forms.",
    source: "geometry-derived",
    auditNote: "Derived from the verified E2 base-to-beta-H arrow.",
    linkedArrowId: "e2-arrow-base",
  }),
  q({
    id: "e2-no-rearrangement",
    reactionClass: "E2",
    skill: "intermediate-recognition",
    prompt: "Why are carbocation rearrangements not expected in E2?",
    options: [
      { id: "a", label: "The elimination is concerted and has no carbocation intermediate" },
      { id: "b", label: "The carbocation rearranges after product formation" },
      { id: "c", label: "The base never participates in the slow step" },
      { id: "d", label: "The leaving group stays attached" },
    ],
    correctOptionId: "a",
    explanation: "E2 proceeds through a single concerted transition state.",
    source: "geometry-derived",
    auditNote: "Derived from verified E2 frame roles.",
    linkedFrameId: "e2-transition",
  }),
  q({
    id: "e2-arrow-count",
    reactionClass: "E2",
    skill: "mechanism-step-identification",
    prompt: "Which electron-flow events happen together in the verified E2 sample?",
    options: [
      { id: "a", label: "Base attack on beta H, pi-bond formation, and leaving-group departure" },
      { id: "b", label: "Carbocation formation, rearrangement, and water attack" },
      { id: "c", label: "Only nucleophile attack at alpha carbon" },
      { id: "d", label: "Only protonation of an alkene" },
    ],
    correctOptionId: "a",
    explanation: "The verified sample contains three coordinated arrows for the concerted E2 step.",
    source: "geometry-derived",
    auditNote: "Derived from the verified E2 curved arrows.",
    linkedStepId: "e2-concerted-elimination",
    linkedArrowId: "e2-arrow-pi",
  }),
] satisfies MechanismPracticeQuestion[];

export function getMechanismPracticeQuestions(reactionClass: MechanismGeometry["reactionClass"]) {
  return mechanismPracticeQuestions.filter((question) => question.reactionClass === reactionClass);
}

export function getMechanismPracticeAudit() {
  return mechanismGeometrySamples.map((sample) => {
    const questions = getMechanismPracticeQuestions(sample.reactionClass);
    const stepIds = new Set(sample.steps.map((step) => step.id));
    const frameIds = new Set(sample.steps.flatMap((step) => step.frames.map((frame) => frame.id)));
    const arrowIds = new Set(sample.steps.flatMap((step) => step.curvedArrows.map((arrow) => arrow.id)));
    const markerIds = new Set(sample.steps.flatMap((step) => step.frames.flatMap((frame) => frame.stereochemistry.map((marker) => marker.id))));
    const orbitalIds = new Set(sample.steps.flatMap((step) => step.frames.flatMap((frame) => frame.orbitalOverlaps.map((overlap) => overlap.id))));

    const brokenLinks = questions.flatMap((question) => {
      const errors: string[] = [];
      if (question.linkedStepId && !stepIds.has(question.linkedStepId)) errors.push(`${question.id}: missing step ${question.linkedStepId}`);
      if (question.linkedFrameId && !frameIds.has(question.linkedFrameId)) errors.push(`${question.id}: missing frame ${question.linkedFrameId}`);
      if (question.linkedArrowId && !arrowIds.has(question.linkedArrowId)) errors.push(`${question.id}: missing arrow ${question.linkedArrowId}`);
      if (question.linkedMarkerId && !markerIds.has(question.linkedMarkerId)) errors.push(`${question.id}: missing marker ${question.linkedMarkerId}`);
      if (question.linkedOrbitalOverlapId && !orbitalIds.has(question.linkedOrbitalOverlapId)) errors.push(`${question.id}: missing orbital overlap ${question.linkedOrbitalOverlapId}`);
      if (!question.options.some((option) => option.id === question.correctOptionId)) errors.push(`${question.id}: missing correct option ${question.correctOptionId}`);
      return errors;
    });

    return {
      reactionClass: sample.reactionClass,
      questionCount: questions.length,
      byType: {
        mcq: questions.filter((question) => question.questionType === "mcq").length,
        assertionReason: questions.filter((question) => question.questionType === "assertion-reason").length,
        productPrediction: questions.filter((question) => question.questionType === "product-prediction").length,
      },
      geometryDerived: questions.filter((question) => question.source === "geometry-derived").length,
      conceptual: questions.filter((question) => question.source === "conceptual").length,
      brokenLinks,
    };
  });
}
