export type PYQChemistryDomain = "physical-chemistry" | "inorganic-chemistry" | "organic-chemistry";

export interface PYQChapterMap {
  id: string;
  name: string;
  classLevel: "11" | "12";
  domain: PYQChemistryDomain;
  aliases: string[];
  active: boolean;
}

export const NEET_CHEMISTRY_CHAPTERS: PYQChapterMap[] = [
  {
    id: "some-basic-concepts",
    name: "Some Basic Concepts",
    classLevel: "11",
    domain: "physical-chemistry",
    aliases: ["Mole Concept", "Some Basic Concepts in Chemistry", "Stoichiometry"],
    active: true,
  },
  {
    id: "atomic-structure",
    name: "Atomic Structure",
    classLevel: "11",
    domain: "physical-chemistry",
    aliases: ["Structure of Atom", "Atoms"],
    active: true,
  },
  {
    id: "chemical-bonding",
    name: "Chemical Bonding",
    classLevel: "11",
    domain: "inorganic-chemistry",
    aliases: ["Chemical Bonding and Molecular Structure", "Molecular Structure"],
    active: true,
  },
  {
    id: "states-of-matter",
    name: "States of Matter",
    classLevel: "11",
    domain: "physical-chemistry",
    aliases: ["Gaseous State", "Liquid State"],
    active: true,
  },
  {
    id: "thermodynamics",
    name: "Thermodynamics",
    classLevel: "11",
    domain: "physical-chemistry",
    aliases: ["Chemical Thermodynamics", "Thermochemistry"],
    active: true,
  },
  {
    id: "equilibrium",
    name: "Equilibrium",
    classLevel: "11",
    domain: "physical-chemistry",
    aliases: ["Chemical Equilibrium", "Ionic Equilibrium"],
    active: true,
  },
  {
    id: "redox-reactions",
    name: "Redox Reactions",
    classLevel: "11",
    domain: "physical-chemistry",
    aliases: ["Oxidation and Reduction", "Redox"],
    active: true,
  },
  {
    id: "hydrogen",
    name: "Hydrogen",
    classLevel: "11",
    domain: "inorganic-chemistry",
    aliases: [],
    active: true,
  },
  {
    id: "s-block-elements",
    name: "s-Block Elements",
    classLevel: "11",
    domain: "inorganic-chemistry",
    aliases: ["s Block", "Alkali and Alkaline Earth Metals"],
    active: true,
  },
  {
    id: "organic-basic-principles",
    name: "General Organic Chemistry",
    classLevel: "11",
    domain: "organic-chemistry",
    aliases: ["Organic Chemistry - Basic Principles", "GOC", "Basic Principles of Organic Chemistry"],
    active: true,
  },
  {
    id: "hydrocarbons",
    name: "Hydrocarbons",
    classLevel: "11",
    domain: "organic-chemistry",
    aliases: [],
    active: true,
  },
  {
    id: "solid-state",
    name: "Solid State",
    classLevel: "12",
    domain: "physical-chemistry",
    aliases: ["The Solid State"],
    active: true,
  },
  {
    id: "solutions",
    name: "Solutions",
    classLevel: "12",
    domain: "physical-chemistry",
    aliases: [],
    active: true,
  },
  {
    id: "electrochemistry",
    name: "Electrochemistry",
    classLevel: "12",
    domain: "physical-chemistry",
    aliases: ["Electrode Potential", "Nernst Equation"],
    active: true,
  },
  {
    id: "chemical-kinetics",
    name: "Chemical Kinetics",
    classLevel: "12",
    domain: "physical-chemistry",
    aliases: [],
    active: true,
  },
  {
    id: "surface-chemistry",
    name: "Surface Chemistry",
    classLevel: "12",
    domain: "physical-chemistry",
    aliases: ["Adsorption", "Colloids"],
    active: true,
  },
  {
    id: "p-block-elements",
    name: "p-Block Elements",
    classLevel: "12",
    domain: "inorganic-chemistry",
    aliases: ["p Block", "Group 15 to 18 Elements"],
    active: true,
  },
  {
    id: "d-f-block-elements",
    name: "d and f Block Elements",
    classLevel: "12",
    domain: "inorganic-chemistry",
    aliases: ["d- and f-Block Elements", "Transition and Inner Transition Elements"],
    active: true,
  },
  {
    id: "coordination-compounds",
    name: "Coordination Compounds",
    classLevel: "12",
    domain: "inorganic-chemistry",
    aliases: ["Coordination Chemistry"],
    active: true,
  },
  {
    id: "haloalkanes-haloarenes",
    name: "Haloalkanes and Haloarenes",
    classLevel: "12",
    domain: "organic-chemistry",
    aliases: ["Organic Compounds Containing Halogens", "Haloalkanes", "Haloarenes"],
    active: true,
  },
  {
    id: "alcohols-phenols-ethers",
    name: "Alcohols Phenols Ethers",
    classLevel: "12",
    domain: "organic-chemistry",
    aliases: ["Alcohols, Phenols and Ethers", "Organic Compounds Containing Oxygen"],
    active: true,
  },
  {
    id: "aldehydes-ketones-carboxylic-acids",
    name: "Aldehydes Ketones and Carboxylic Acids",
    classLevel: "12",
    domain: "organic-chemistry",
    aliases: ["Aldehydes Ketones", "Carboxylic Acids", "Carbonyl Compounds"],
    active: true,
  },
  {
    id: "amines",
    name: "Amines",
    classLevel: "12",
    domain: "organic-chemistry",
    aliases: ["Organic Compounds Containing Nitrogen"],
    active: true,
  },
  {
    id: "biomolecules",
    name: "Biomolecules",
    classLevel: "12",
    domain: "organic-chemistry",
    aliases: [],
    active: true,
  },
  {
    id: "polymers",
    name: "Polymers",
    classLevel: "12",
    domain: "organic-chemistry",
    aliases: [],
    active: true,
  },
  {
    id: "chemistry-in-everyday-life",
    name: "Chemistry in Everyday Life",
    classLevel: "12",
    domain: "organic-chemistry",
    aliases: ["Environmental Chemistry"],
    active: true,
  },
];

export function getNEETChemistryChapterById(id: string) {
  return NEET_CHEMISTRY_CHAPTERS.find((chapter) => chapter.id === id && chapter.active);
}
