"use client";

import {
  ChapterSection,
  ConceptCard,
  DataTable,
  DipoleStructureFigure,
  ExamTrap,
  FigureFrame,
  K,
  KeyIdea,
  PartShell,
} from "../../dipole-moment-shared";

export default function DipoleMomentPart08() {
  return (
    <PartShell
      part={8}
      title="Advanced Exceptions"
      description="CO, B–N dative bonds, Pt complexes, ozone, SO₂, interhalogens, hydrazine/peroxide conformations, TBP phosphorus systems, and maleic vs. fumaric acid."
    >
      <ChapterSection
        id="co-and-bn"
        index="01"
        eyebrow="Advanced exceptions"
        title="CO and B–N — dative bonds fighting the naive prediction"
        intro="Two molecules where the μd factor from Part D isn't a minor correction — it's the whole story."
      >
        <FigureFrame title="CO resonance" caption="Structure I (:C≡O:) versus Structure II, the dative contributor (⁻C≡O⁺). The dative moment opposes the electronegativity-based moment, nearly cancelling it.">
          <DipoleStructureFigure id="co-resonance" />
        </FigureFrame>

        <ConceptCard title="CO — three competing effects nearly cancel" tone="rose" eyebrow="μ ≈ 0.11–0.12 D, toward carbon">
          <p>Directed toward carbon — opposite the electronegativity prediction.</p>
        </ConceptCard>

        <DataTable
          headers={["Contribution", "Direction", "Reasoning"]}
          rows={[
            ["Lone-pair moments (μL)", "≈ cancel", "Lone pair on C opposes lone pair on O"],
            ["Intrinsic homopolar (μh)", "toward O", "O uses more compact orbitals than C"],
            ["σ/π electronegativity (μe)", "toward O", "O is more electronegative than C"],
            ["Dative bond (μd): ⁻C≡O⁺", "toward C", "Opposes and nearly cancels all of the above"],
          ]}
        />

        <ConceptCard title="B–N dative linkage" tone="violet" eyebrow="A coordinate π-bond partially cancels the σ moment">
          <p><K>{String.raw`R_3B \leftarrow NR_3 \leftrightarrow R_3\bar{B}=N^+R_3`}</K>: the dative N→B π-contribution opposes the σ-bond moment generated by the electronegativity difference (N more electronegative than B), lowering the net B–N moment below the naive electronegativity-only prediction.</p>
        </ConceptCard>

        <KeyIdea>
          CO&apos;s final vector sum is small and points toward carbon precisely because the dative contribution overwhelms the sum of the other three — the same μd factor introduced generically in Part D, now shown doing all the work.
        </KeyIdea>
      </ChapterSection>

      <ChapterSection
        id="coordination-resonance"
        index="02"
        eyebrow="Advanced exceptions"
        title="Coordination and resonance exceptions"
        intro="A rigid ligand lone pair, a resonance-charged ozone, and a lone-pair-directed SO₂ — three more cases where the naive symmetry or electronegativity picture fails."
      >
        <FigureFrame title="trans-PtCl₂(PEt₃)₂ vs. trans-PtCl₂(SEt₂)₂" caption="μ = 0 versus μ = 2.4 D — the S lone pair is not cancelled by the trans arrangement.">
          <DipoleStructureFigure id="pt-complexes" />
        </FigureFrame>
        <ConceptCard title="A rigid-ligand lone-pair exception" tone="cyan">
          <p>Both are square-planar complexes where naive symmetry predicts μ = 0. This holds for PEt₃ (P has no lone pair left after coordinate bonding). But sulfur in SEt₂ retains an unshared lone pair whose moment — plus the rigid, non-freely-rotating S–Et bond moments — is not fully cancelled by the trans arrangement, giving a substantial residual μ = 2.4 D.</p>
        </ConceptCard>

        <FigureFrame title="Ozone resonance" caption="Formal positive charge on the central O, formal negative charge on a terminal O.">
          <DipoleStructureFigure id="ozone" />
        </FigureFrame>
        <ConceptCard title="Bent, resonance-stabilised, and unavoidably polar" tone="violet">
          <p>Lewis resonance places formal + charge on the central O and formal − on a terminal O. The two O–O bond moments are not fully cancelled by the lone-pair moment on the central atom, leaving ozone measurably polar despite consisting of only one element.</p>
        </ConceptCard>

        <FigureFrame title="SO₂" caption="Bent AX₂E geometry. The S=O bond resultant is opposed by the sulfur lone-pair moment, and the net dipole points away from the two S=O bonds, along the lone-pair direction.">
          <DipoleStructureFigure id="so2" />
        </FigureFrame>
        <ConceptCard title="SO₂ — net dipole points toward the S lone pair" tone="amber" eyebrow="μ = 1.63 D">
          <p>The same lone-pair-vs-bond-resultant tug-of-war as NH₃/H₂O (Part E), now in a molecule with two double bonds instead of two single bonds: the sulfur lone-pair moment reinforces against the S=O bond resultant strongly enough to set the direction of the net molecular dipole.</p>
        </ConceptCard>
      </ChapterSection>

      <ChapterSection
        id="conformations-interhalogens"
        index="03"
        eyebrow="Advanced exceptions"
        title="Nonplanar conformations and interhalogens"
        intro="Four related hydrides/fluorides that adopt nonplanar shapes from lone-pair repulsion, plus the interhalogen family as a clean generalisation of the bond-moment framework."
      >
        <FigureFrame title="N₂H₄ and H₂O₂ conformations" caption="N₂H₄: gauche/skew, H–N–N–H dihedral ≈95°. H₂O₂: open-book about the O–O spine, dihedral ≈111.5° (gas).">
          <DipoleStructureFigure id="n2h4-h2o2-conformations" />
        </FigureFrame>

        <div className="grid gap-5 xl:grid-cols-2">
          <ConceptCard title="N₂H₄, H₂O₂" tone="cyan" eyebrow="Gauche/skew, open-book">
            <p><strong className="text-white">N₂H₄</strong>: μ ≈ 1.85 D; gas-phase gauche/skew conformation, NH₂ halves rotated ≈95° from eclipsed. Rotation barrier: through-trans ≈16 kJ/mol; through-cis ≈49.8 kJ/mol.</p>
            <p><strong className="text-white">H₂O₂</strong>: μ ≈ 2.0 D; open-book structure with O–O as spine, dihedral ≈111.5° (gas), ≈90–94.8° (crystalline), 80–145° range in organic peroxides. Rotation barrier: trans ≈4.6 kJ/mol; cis ≈29.5 kJ/mol.</p>
          </ConceptCard>
          <ConceptCard title="N₂F₄, P₂H₄" tone="violet" eyebrow="Related fluorides/hydrides">
            <p><strong className="text-white">N₂F₄(g)</strong> exists as a mixture of gauche and staggered forms, showing anomalous dipole behaviour.</p>
            <p><strong className="text-white">P₂H₄(g)</strong> exists predominantly in the gauche form.</p>
          </ConceptCard>
        </div>

        <FigureFrame title="Bond dipole of Cl–F" caption="Every interhalogen X–Y is necessarily polar, since the two atoms are never identical and always differ in electronegativity.">
          <DipoleStructureFigure id="clf-bond" />
        </FigureFrame>
        <ConceptCard title="Interhalogen ClF" tone="amber" eyebrow="μ ≈ 0.88 D">
          <p>The same <K>{String.raw`\mu = q\times d`}</K> bond-moment framework built in Part A, applied here to a family beyond the hydrogen halides — confirming the concept generalises cleanly to any two different halogens.</p>
        </ConceptCard>
      </ChapterSection>

      <ChapterSection
        id="tbp-fluorine-systems"
        index="04"
        eyebrow="Advanced exceptions"
        title="Trigonal-bipyramidal phosphorus and fluorine geometry exceptions"
        intro="Real dipole moments that give the AX₄E/AX₃E₂/AX₅E geometry rules from Part F concrete experimental teeth."
      >
        <FigureFrame title="The PClₓFᵧ series" caption="Axial/equatorial fluorine substitution pattern determines whether μ is zero or nonzero.">
          <DipoleStructureFigure id="pclxfy-series" />
        </FigureFrame>
        <ConceptCard title="Polarity depends on position, not formula" tone="cyan">
          <p>Trigonal bipyramidal geometry: three equatorial positions (120° apart) + two axial positions (180° apart). Substituting F for Cl gives μ = 0 only when the substitution pattern preserves an axis or plane of symmetry (PCl₅, PCl₃F₂ with both F axial, PF₅) and μ ≠ 0 for asymmetric patterns (PCl₄F, PCl₂F₃, PClF₄).</p>
        </ConceptCard>

        <ExamTrap>
          P(CH₃)₃(CF₃)₂ and P(CH₃)₂(CF₃)₃ test the same axial/equatorial group-vector cancellation: CF₃ is a strong electron-withdrawing group while CH₃ is weakly donating, so their placement — not the formula alone — determines whether the molecule&apos;s overall vector arrangement cancels to zero.
        </ExamTrap>

        <FigureFrame title="SF₄, ClF₃, BrF₅" caption="See-saw (AX₄E, μ≈0.63 D), T-shaped (AX₃E₂, μ≈0.56 D), square pyramidal (AX₅E, μ≈1.51 D) — lone pairs shown explicitly.">
          <DipoleStructureFigure id="sf4-clf3-brf5" />
        </FigureFrame>
        <ConceptCard title="Lone pairs break the parent symmetry" tone="violet">
          <p>Each species has a lone pair occupying a nominal vertex, breaking the symmetry that would otherwise cancel the fluorine bond moments — unlike the parent-symmetry cases PF₅ and SF₆ (μ = 0).</p>
        </ConceptCard>
      </ChapterSection>

      <ChapterSection
        id="maleic-fumaric"
        index="05"
        eyebrow="Advanced exceptions"
        title="Maleic acid vs. fumaric acid"
        intro="A biologically relevant cis/trans pair — the same geometric-isomer logic as 1,2-dichloroethene (Part F), applied to a real, well-known molecule pair."
      >
        <FigureFrame title="Maleic acid (cis) vs. fumaric acid (trans)" caption="Maleic acid, cis (μ ≠ 0) vs. fumaric acid, trans (μ ≈ 0).">
          <DipoleStructureFigure id="maleic-fumaric" />
        </FigureFrame>
        <ConceptCard title="Using dipole moment to assign configuration" tone="amber">
          <p>Maleic acid (cis) is polar; fumaric acid (trans) is essentially nonpolar — a textbook illustration of using dipole moment to assign geometrical configuration in real, biologically important molecules.</p>
        </ConceptCard>
      </ChapterSection>
    </PartShell>
  );
}
