export const saltAnalysisParts = [
  { id: 1, href: "/learn/jee-advanced/salt-analysis/parts/part01", title: "Foundations, Equilibria and Laboratory Method" },
  { id: 2, href: "/learn/jee-advanced/salt-analysis/parts/part02", title: "Preliminary Examination and Dry Tests" },
  { id: 3, href: "/learn/jee-advanced/salt-analysis/parts/part03", title: "Anion Strategy and Carbonate System" },
  { id: 4, href: "/learn/jee-advanced/salt-analysis/parts/part04", title: "Sulphur-Containing Acid Radicals" },
  { id: 5, href: "/learn/jee-advanced/salt-analysis/parts/part05", title: "Nitrite, Nitrate and Halide Analysis" },
  { id: 6, href: "/learn/jee-advanced/salt-analysis/parts/part06", title: "Sulphate, Phosphate, Oxalate and Acetate" },
  { id: 7, href: "/learn/jee-advanced/salt-analysis/parts/part07", title: "Borate, Fluoride, Silicate and Coloured Oxoanions" },
  { id: 8, href: "/learn/jee-advanced/salt-analysis/parts/part08", title: "Original Solution, Group Scheme and Ammonium" },
  { id: 9, href: "/learn/jee-advanced/salt-analysis/parts/part09", title: "Group I: Silver, Lead and Mercury(I)" },
  { id: 10, href: "/learn/jee-advanced/salt-analysis/parts/part10", title: "Group II: Acidic Sulphide Group" },
  { id: 11, href: "/learn/jee-advanced/salt-analysis/parts/part11", title: "Group III: Iron, Aluminium and Chromium" },
  { id: 12, href: "/learn/jee-advanced/salt-analysis/parts/part12", title: "Group IV: Nickel, Cobalt, Manganese and Zinc" },
  { id: 13, href: "/learn/jee-advanced/salt-analysis/parts/part13", title: "Groups V and VI: Alkaline Earths and Alkali Metals" },
  { id: 14, href: "/learn/jee-advanced/salt-analysis/parts/part14", title: "Amphoterism, Complexes and Analytical Reasoning" },
  { id: 15, href: "/learn/jee-advanced/salt-analysis/parts/part15", title: "Observation Atlas, False Positives and Solubility Patterns" },
  { id: 16, href: "/learn/jee-advanced/salt-analysis/parts/part16", title: "JEE Advanced Worked Illustrations" },
  { id: 17, href: "/learn/jee-advanced/salt-analysis/parts/part17", title: "Complete Decision Flows and Rapid Revision" },
  { id: 18, href: "/learn/jee-advanced/salt-analysis/parts/part18", title: "Practice Set, Answer Key and Final Audit" },
] as const;
