export const saltAnalysisParts = [
  { id: 1, href: "/learn/jee-advanced/salt-analysis/parts/part01", title: "Foundations, Equilibria and Laboratory Method" },
  { id: 2, href: "/learn/jee-advanced/salt-analysis/parts/part02", title: "Preliminary Examination, Heating Effects and Dry Tests" },
  { id: 3, href: "/learn/jee-advanced/salt-analysis/parts/part03", title: "Acid-Radical Strategy: Carbonate, Bicarbonate, Sulphite and Bisulphite" },
  { id: 4, href: "/learn/jee-advanced/salt-analysis/parts/part04", title: "Sulphide, Thiosulphate and Sulphur-Oxyanion Chemistry" },
  { id: 5, href: "/learn/jee-advanced/salt-analysis/parts/part05", title: "Nitrite, Nitrate and Complete Halide Analysis" },
  { id: 6, href: "/learn/jee-advanced/salt-analysis/parts/part06", title: "Acetate, Formate, Oxalate, Sulphate and Phosphate" },
  { id: 7, href: "/learn/jee-advanced/salt-analysis/parts/part07", title: "Borate, Fluoride, Silicate and Coloured Oxoanions" },
  { id: 8, href: "/learn/jee-advanced/salt-analysis/parts/part08", title: "Original Solution, Soda Extract and the Cation Group Scheme" },
  { id: 9, href: "/learn/jee-advanced/salt-analysis/parts/part09", title: "Group I Cations: Silver, Lead and Mercury(I)" },
  { id: 10, href: "/learn/jee-advanced/salt-analysis/parts/part10", title: "Group II Cations: Acidic Sulphide Group" },
  { id: 11, href: "/learn/jee-advanced/salt-analysis/parts/part11", title: "Group III Cations: Iron, Aluminium and Chromium" },
  { id: 12, href: "/learn/jee-advanced/salt-analysis/parts/part12", title: "Group IV Cations: Nickel, Cobalt, Manganese and Zinc" },
  { id: 13, href: "/learn/jee-advanced/salt-analysis/parts/part13", title: "Groups V and VI: Alkaline Earths, Magnesium, Ammonium and Alkali Metals" },
  { id: 14, href: "/learn/jee-advanced/salt-analysis/parts/part14", title: "Amphoterism, Complexation, Masking and Analytical Selectivity" },
  { id: 15, href: "/learn/jee-advanced/salt-analysis/parts/part15", title: "Observation Atlas, Solubility Matrix and Complete Data Tables" },
  { id: 16, href: "/learn/jee-advanced/salt-analysis/parts/part16", title: "JEE Advanced Worked Illustrations" },
  { id: 17, href: "/learn/jee-advanced/salt-analysis/parts/part17", title: "Master Decision Flows, Error Analysis and Rapid Revision" },
  { id: 18, href: "/learn/jee-advanced/salt-analysis/parts/part18", title: "Comprehensive Practice Set, Answer Key and Final Audit" },
] as const;
