import { notFound } from "next/navigation";
import { ChapterLessonPager, ChapterPartStrip, ChapterShell } from "@/components/notes/canonical";
import { S_BLOCK_PARTS, sBlockPartBySlug, sBlockPartMarkdown } from "../parts";
import { sBlockLessonRef, sBlockTabs, sectionRangeLabel } from "../_chapter";
import { SBlockMarkdown } from "../_markdown";
export const dynamic = "force-dynamic";
export function generateStaticParams() { return S_BLOCK_PARTS.map((part) => ({ part: part.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ part: string }> }) { const part = sBlockPartBySlug((await params).part); return part ? { title: `S-block Elements — ${part.title} | SYNERGIC BOND`, description: `S-block JEE Advanced notes, Lesson ${part.number}: ${part.title}.` } : {}; }
export default async function SBlockPartPage({ params }: { params: Promise<{ part: string }> }) { const part = sBlockPartBySlug((await params).part); if (!part) notFound(); return <ChapterShell kicker="JEE Inorganic Chemistry" subtitle="S-block Elements" tabs={sBlockTabs(part.number)}><ChapterPartStrip hubHref="/notes/s-block" hubLabel="S-block — all lessons" positionLabel={`Lesson ${part.number} of ${S_BLOCK_PARTS.length}`}/><article className="mx-auto max-w-5xl space-y-6 text-white"><header style={{ background: "#122232", border: "1px solid #24405c", borderLeft: "4px solid #5fd4ea", borderRadius: 13, padding: "18px 20px" }}><p style={{ color: "#5fd4ea", fontSize: 11.5, fontWeight: 900, letterSpacing: ".14em", textTransform: "uppercase" }}>S-block Elements · Lesson {part.number} · {sectionRangeLabel(part)}</p><h1 style={{ marginTop: 8, color: "#eef3f8", fontSize: 30, fontWeight: 900, lineHeight: 1.15, fontFamily: "Georgia, 'Iowan Old Style', 'Times New Roman', serif" }}>{part.title}</h1></header><div className="space-y-5 rounded-3xl border border-[#24405c] bg-[#122232]/60 px-5 py-8 sm:px-8 lg:px-10"><SBlockMarkdown markdown={sBlockPartMarkdown(part)}/></div><ChapterLessonPager prev={sBlockLessonRef(part.number - 1)} next={sBlockLessonRef(part.number + 1)} hubHref="/notes/s-block" hubLabel="All lessons"/></article></ChapterShell>; }
