// Selector metadata for the source-specific lesson modules. The rendered
// lesson remains in its own module; this keeps the route registry compact.
export const extendedSourcePartTitles: Record<number, string> = {
  79: "Higher cumulenes and spiranes: source decision bank",
  80: "Ring + π-bond: every source accept/reject case",
  81: "Terphenyl axes and rigid bridge systems",
  82: "Exercise 1: identify structures that show geometrical isomerism",
  83: "Exercise 1 continued: rings, oximes, diazenes and imines",
  84: "Exercise 1 continued: cumulenes and crowded aromatic axes",
  85: "Exercise 1 final source structures: biaryls and cumulenes",
  86: "Exercise 2: cyclic geometrical-isomerism decision bank",
  87: "Exercise 2 continued: constrained rings and bridges",
  88: "Exercise 2 continued: bridged, cyclic and macrocyclic systems",
  89: "Exercise 2 finale: macrocycles and spiranes",
  90: "Exercise 3: linked rings, constrained frameworks and cycloalkenes",
  91: "Exercise 3 continued and physical consequences of GI",
  92: "Physical properties of geometrical isomers",
  93: "Dipole moment and relative stability of geometrical isomers",
  94: "Nomenclature of geometrical isomerism: cis/trans, syn/anti and E/Z",
  95: "E/Z assignments: source worked examples and special priority rules",
  96: "CIP priorities for cyclic groups",
  97: "Advanced E/Z source assignment bank",
  98: "E/Z nomenclature when a lone pair is present",
  99: "Calculating the number of geometrical isomers",
  100: "Geometrical-isomer counting: extended source examples",
  101: "Enumerating symmetry-reduced geometrical configurations",
  102: "Mixed stereogenic-element counting examples",
  103: "Counting GI in mixed chains and rigid face-defined frameworks",
  104: "Counting cis/trans configurations in substituted rings",
  105: "Truxilic acid: ring stereochemistry source set",
  106: "Conformational isomerism: concept and representations",
  107: "Newman projection: proximal, distal and dihedral angle",
  108: "Staggered and eclipsed conformations",
  109: "Skew conformers and the rotation-energy profile",
  110: "van der Waals strain and torsional strain",
  111: "Ethane and propane conformations",
  112: "Propane profile and the C₂-C₃ bond of n-butane",
  113: "n-Butane: anti, gauche and eclipsed energy levels",
  114: "Orbital-overlap explanation of ethane’s rotational barrier",
  115: "Ethyl-substituted bond rotation",
  116: "Incremental contributions to the eclipsing barrier",
  117: "The 1,2-dihaloethanes and ΔG°",
  118: "Butane: eclipsing estimate and torsional-energy profile",
  119: "Butane continued: Me–Me eclipsing interaction",
  120: "Nomenclature for staggered conformers",
  121: "Three types of strain",
  122: "Isobutane and ethylene-glycol conformations",
  123: "Gauche stabilisation in polar chains",
  124: "Gauche/anti outcomes: ionic, polar and size effects",
  125: "The gauche effect",
  126: "Lone pairs in conformational analysis",
  127: "Hydrazine: lone-pair delocalisation and gauche effect",
  128: "Hydrogen peroxide, H₂O₂: a gauche conformer",
  129: "Sulfonium ions A and B: reactivity comparison",
  130: "Dipole moment of a conformer mixture",
  131: "Identify the stable conformer: questions 47–56",
  132: "Conformations of cyclic compounds: Baeyer’s strain theory",
  133: "Coulson–Moffitt model of cyclopropane",
  134: "Sachse–Mohr theory: strain-free puckered rings",
  135: "Cyclopropane: formation, planarity and stereochemistry",
  136: "Cyclopropane MO picture and cyclopropene derivatives",
  137: "Twist-boat cyclohexane and puckered cyclobutane",
  138: "Cyclobutane butterfly conformation and 1,3-diesters",
  139: "Cyclopentane: envelope, half-chair and pseudorotation",
  140: "Cyclopentane Newman view and energy profile",
  141: "Cyclohexane chair conformation",
  142: "Boat and twist-boat conformations of cyclohexane",
  143: "Cyclohexane chair–chair interconversion",
  144: "Half-chair strain and cyclohexane flipping",
  145: "Numerical energy profile for a cyclohexane flip",
  146: "Chair flipping and axial–equatorial energy",
  147: "A-values and substituted-chair equilibria",
  148: "Phenylcyclohexane conformational preference",
  149: "Pyramidal inversion in piperidine",
  150: "Ring inversion versus nitrogen inversion",
  151: "Heterocycles and 1,3-diaxial interactions",
  152: "Heteroatom substituents and the anomeric effect",
  153: "Anomeric effect: conformer and orbital explanation",
  154: "Dipolar contributions and factors affecting the anomeric effect",
  155: "Anomeric-effect consequences: solvent and bond distances",
  156: "Chemical reactivity and reverse anomeric effect",
  157: "Reverse, double and rabbit-ear anomeric effects",
  158: "Rabbit-ear and repulsive-gauche effects",
  159: "Hockey-sticks effect in 1,4-oxathianes",
  160: "Through-space attractive interactions in heterocycles",
  161: "Spectral consequence of a transannular interaction",
  162: "Decalin (6/6) ring system",
  163: "Quantifying the anomeric effect",
  164: "σ* acceptors and the exo-anomeric effect",
  165: "σ–σ* hyperconjugative anomeric stabilization",
  166: "Geometrical isomers of disubstituted cyclohexane",
  167: "Fused tricycles and steroid ring junctions",
  168: "Worked equilibrium: chair versus twist-boat cyclohexane",
  169: "Cycloheptane and cyclooctane conformations",
};
