import Link from "next/link";

type Form = "cyclohexanone" | "acetone" | "enone" | "dienone" | "quinonedione" | "chloroethanal" | "ethanal";
const caption: Record<Form, string> = { cyclohexanone: "cyclohexanone", acetone: "acetone", enone: "cyclohex-2-enone", dienone: "cyclohexa-2,5-dienone", quinonedione: "cyclohexene-1,4-dione", chloroethanal: "2-chloroethanal", ethanal: "ethanal" };

function Structure({ form }: { form: Form }) {
  const b = { stroke: "currentColor", strokeWidth: 2.6, fill: "none", strokeLinecap: "round" as const };
  const ring = form === "cyclohexanone" || form === "enone" || form === "dienone" || form === "quinonedione";
  if (!ring) return <svg fill="currentColor" viewBox="0 0 190 130" className="h-auto w-full" role="img" aria-label={caption[form]}><path d="M24 95L80 60L136 95" {...b}/><path d="M77 60L77 20M83 60L83 20" {...b}/><text x="80" y="16" fontSize="15" textAnchor="middle">O</text><text x="13" y="102" fontSize="14">{form === "chloroethanal" ? "ClCH₂" : "CH₃"}</text><text x="147" y="102" fontSize="14">H</text></svg>;
  return <svg fill="currentColor" viewBox="0 0 190 150" className="h-auto w-full" role="img" aria-label={caption[form]}><path d="M46 108L46 65L82 43L122 65L122 108L82 130Z" {...b}/><path d="M79 43L79 14M85 43L85 14" {...b}/><text x="82" y="13" fontSize="15" textAnchor="middle">O</text>{(form === "enone" || form === "dienone") && <path d="M46 61L82 39M46 68L82 46" {...b}/>} {form === "dienone" && <path d="M122 104L82 126M122 111L82 133" {...b}/>} {form === "quinonedione" && <><path d="M122 65L122 28M128 65L128 28" {...b}/><text x="125" y="24" fontSize="15" textAnchor="middle">O</text><path d="M46 104L46 76M52 104L52 76" {...b}/></>}</svg>;
}

const pairs = [
  { id: "(a)", a: "cyclohexanone" as Form, b: "acetone" as Form, lower: "acetone", why: "Its enol has no ring-assisted conjugation; the cyclic ketone has a slightly more favourable enol geometry." },
  { id: "(b)", a: "cyclohexanone" as Form, b: "enone" as Form, lower: "cyclohexanone", why: "The α,β-unsaturated ketone has a conjugated enol/enone system unavailable to the saturated ketone." },
  { id: "(c)", a: "dienone" as Form, b: "cyclohexanone" as Form, lower: "cyclohexanone", why: "Additional conjugation stabilises the dienone-derived enol more strongly." },
  { id: "(d)", a: "cyclohexanone" as Form, b: "quinonedione" as Form, lower: "cyclohexanone", why: "The dicarbonyl system can gain extra delocalisation on enolisation." },
  { id: "(e)", a: "chloroethanal" as Form, b: "ethanal" as Form, lower: "ethanal", why: "The chlorine substituent withdraws inductively and increases α-H acidity, so chloroethanal enolises more readily." },
];

export default function IsomerismPart64() { return <main className="min-h-screen bg-[#08111f] px-4 py-8 text-white sm:px-6 sm:py-12"><article className="mx-auto max-w-6xl"><Link href="/learn/isomerism" className="rounded-full border border-cyan-300/30 bg-cyan-300/10 px-4 py-2 text-sm font-bold text-cyan-100">Isomerism</Link><header className="mt-6 rounded-3xl border border-cyan-300/15 bg-[radial-gradient(circle_at_top_right,_rgba(34,211,238,.18),_transparent_35%),linear-gradient(135deg,rgba(34,211,238,.08),rgba(2,6,23,.7),rgba(139,92,246,.1))] p-6 sm:p-9"><p className="text-xs font-black uppercase tracking-[.24em] text-cyan-200">Isomerism source · page 54 · Part 64</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Enol content: source comparison bank III</h1><p className="mt-3 text-sm text-slate-300">Source question: <i>In each pair which will have less enol content?</i></p></header><section className="mt-7 grid gap-4 md:grid-cols-2">{pairs.map((p) => <article key={p.id} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><h2 className="font-black text-cyan-100">{p.id} {caption[p.a]} and {caption[p.b]}</h2><div className="mt-3 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><Structure form={p.a}/><span className="text-cyan-200">vs</span><Structure form={p.b}/></div><ol className="mt-3 list-decimal space-y-1 pl-5 text-sm leading-6 text-slate-300"><li>Identify conjugation and electron-withdrawing effects in each carbonyl framework.</li><li>Compare the stabilisation available to its enol.</li><li><b>Lower enol content:</b> {p.lower}. {p.why}</li></ol></article>)}</section><nav className="mt-8 flex justify-between border-t border-white/10 pt-6"><Link href="/learn/isomerism/63" className="rounded-xl border border-white/15 px-4 py-3 text-sm font-bold text-slate-200">← 63</Link><Link href="/learn/isomerism" className="rounded-xl border border-cyan-300/30 bg-cyan-300/10 px-4 py-3 text-sm font-bold text-cyan-100">Chapter overview</Link></nav></article></main>; }
