import Link from "next/link";

const aromaticCases = [
  ["a/b terminally differentiated terphenyl", true, "The terminal ring paths are different (a ≠ b), and ortho crowding restricts both aryl–aryl rotations."],
  ["F/Cl-substituted terphenyl", true, "F and Cl make the terminal ring paths non-equivalent while the ortho substituents hold the rings out of plane."],
  ["1,1′-biphenyl", false, "An unsubstituted biphenyl rotates readily and has symmetry-equivalent paths; it does not give isolable geometrical forms."],
  ["symmetrically substituted terphenyl", false, "Restricted rotation does not help when the paths about an axis remain symmetry equivalent."],
  ["diazaterphenyl, matching N positions", false, "The matching heteroaryl paths retain the source’s symmetry restriction."],
  ["diazaterphenyl, unlike N positions", true, "Moving one nitrogen makes the two axis termini constitutionally distinguishable."],
  ["ortho-crowded unsymmetrical terphenyl", true, "This source structure has both a high rotation barrier and distinguishable aromatic paths."],
] as const;

function Benzene({ x, y }: { x: number; y: number }) { return <g fill="none" stroke="currentColor" strokeWidth="2.2"><polygon points={`${x-22},${y} ${x-11},${y-19} ${x+11},${y-19} ${x+22},${y} ${x+11},${y+19} ${x-11},${y+19}`} /><circle cx={x} cy={y} r="10" /></g>; }
function Terphenyl({ index, accepted }: { index: number; accepted: boolean }) { const hetero = index === 4 || index === 5; return <svg fill="currentColor" viewBox="0 0 300 135" className="mt-3 w-full" role="img" aria-label={aromaticCases[index][0]}><Benzene x={65} y={66}/><Benzene x={150} y={66}/><Benzene x={235} y={66}/><path d="M87 66H128M172 66H213" stroke="currentColor" strokeWidth="2.8" />{index !== 2 && <><text x="43" y="28" fill="#f0abfc">{index===1?"F":"Me"}</text><text x="42" y="117" fill="#f0abfc">{index===1?"Cl":"Me"}</text><text x="247" y="28" fill="#f0abfc">{index===1?"F":"Me"}</text><text x="246" y="117" fill="#f0abfc">{index===1?"Cl":"Et"}</text></>}{hetero && <><text x="48" y="70" fill="#f0abfc">N</text><text x="248" y="70" fill="#f0abfc">{index===4?"N":"C"}</text></>}<text x="150" y="132" textAnchor="middle" fill={accepted?"#86efac":"#fda4af"} fontWeight="700">{accepted?"✓ source accepts GI":"× source rejects GI"}</text></svg>; }
function Bridge() { return <svg fill="currentColor" viewBox="0 0 290 150" className="mt-3 w-full" role="img" aria-label="rigid bridged source pair"><path d="M45 110 90 65 145 32 194 65 239 110M45 110 65 47 145 32 225 47 239 110M90 65 115 115 145 32 175 115 194 65" stroke="currentColor" strokeWidth="2.5" fill="none"/><path d="M45 110 112 82M239 110 178 82" stroke="#f0abfc" strokeWidth="2.8"/><text x="127" y="27" fill="#f0abfc">a / b</text><text x="145" y="143" textAnchor="middle" fill="#86efac" fontWeight="700">✓ distinguishable locked bridge paths</text></svg>; }
export default function IsomerismPart81(){return <main className="min-h-screen bg-[#08111f] px-4 py-8 text-white sm:px-6 sm:py-12"><article className="mx-auto max-w-6xl"><Link href="/learn/isomerism" className="rounded-full border border-cyan-300/30 bg-cyan-300/10 px-4 py-2 text-sm font-bold text-cyan-100">Isomerism</Link><header className="mt-6 rounded-3xl border border-cyan-300/15 bg-[#08111f] p-6 sm:p-9"><p className="text-xs font-black uppercase tracking-[.24em] text-cyan-200">Isomerism source · page 71 · Part 81</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Terphenyl axes and rigid bridge systems</h1><p className="mt-4 text-slate-300">The source page tests whether crowded aryl axes and rigid bridges have the two prerequisites for geometrical/axis-based stereoisomerism: restricted motion and non-equivalent paths at the relevant ends.</p></header><section className="mt-7 grid gap-4 md:grid-cols-2">{aromaticCases.map(([label,accepted,reason],index)=><article key={label} className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="font-black text-cyan-100">{label}</h2><Terphenyl index={index} accepted={accepted}/><p className="text-sm leading-6 text-slate-300"><b className={accepted?"text-emerald-300":"text-rose-300"}>{accepted?"GI possible.":"No GI."}</b> {reason}</p></article>)}</section><section className="mt-7 rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="font-black text-cyan-100">Rigid bridged comparison in the source</h2><Bridge/><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm leading-6 text-slate-300"><li>Identify the fixed framework: deformation, not simple bond rotation, would be required to exchange the highlighted paths.</li><li>Compare a with b and l₁ with l₂ at the bridge termini.</li><li>Because both pairs are unlike, the source accepts distinct geometrical arrangements.</li></ol></section></article></main>}
