import Link from "next/link";

const pairs=[
  {type:"Nitro–aci-nitro", left:"R–CH–N⁺(=O)–O⁻", right:"R–C(OH)=N⁺–O⁻", labels:["Nitro form","Aci-nitro form"]},
  {type:"Amido–imidol", left:"R–NH–C(=O)–R′", right:"R–N=C(OH)–R′", labels:["Amido form","Imidol form"]},
  {type:"Imine–enamine", left:"R–CH–C(=NH)–R′", right:"R–C(=C–NH₂)–R′", labels:["Imine form","Enamine form"]},
  {type:"Nitroso–oximino", left:"R–CH–N=O", right:"R–C=N–OH", labels:["Nitroso form","Oximino form"]},
  {type:"Azo–hydrazono", left:"R–N=N–CH–R′", right:"R–NH–N=C–R′", labels:["Azo form","Hydrazono form"]},
] as const;
function Pair({pair}:{pair:(typeof pairs)[number]}){return <article className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><h3 className="font-black text-cyan-100">{pair.type} tautomerism</h3><svg viewBox="0 0 640 115" className="mt-2 h-auto w-full text-slate-100" role="img" aria-label={`${pair.type} tautomeric pair`}><text x="132" y="49" textAnchor="middle" fontSize="18">{pair.left}</text><text x="320" y="55" textAnchor="middle" fontSize="30" fill="#67e8f9">⇌</text><text x="508" y="49" textAnchor="middle" fontSize="18">{pair.right}</text><text x="132" y="91" textAnchor="middle" fontSize="14" fill="#a5f3fc">{pair.labels[0]}</text><text x="508" y="91" textAnchor="middle" fontSize="14" fill="#a5f3fc">{pair.labels[1]}</text></svg></article>}
function Heterocycle({n}:{n:150|151|152|153|154|155}){const atom=n===154||n===155?"S":n===150||n===153?"O":"OH";return <svg viewBox="0 0 150 130" className="h-auto w-full text-slate-100" role="img" aria-label={`source heterocyclic tautomer ${n}`}><path d="M43 77 43 42 73 25 104 42 104 77 73 95Z" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M48 44 70 31M78 31 99 44M99 74 78 88" fill="none" stroke="currentColor" strokeWidth="1.2"/><text x="68" y="96" fontSize="16">N{n===150||n===153||n===155?"H":""}</text><text x="104" y="47" fontSize="16">{atom}</text>{n===151||n===152||n===154?<text x="100" y="25" fontSize="13">H</text>:null}</svg>}
export default function IsomerismPart60(){return <main className="min-h-screen bg-[#08111f] px-4 py-8 text-white sm:px-6 sm:py-12"><article className="mx-auto max-w-6xl"><Link href="/learn/isomerism" className="rounded-full border border-cyan-300/30 bg-cyan-300/10 px-4 py-2 text-sm font-bold text-cyan-100">Isomerism</Link><header className="mt-6 rounded-3xl border border-cyan-300/15 bg-[radial-gradient(circle_at_top_right,_rgba(34,211,238,.18),_transparent_35%),linear-gradient(135deg,rgba(34,211,238,.08),rgba(2,6,23,.7),rgba(139,92,246,.1))] p-6 sm:p-9"><p className="text-xs font-black uppercase tracking-[.24em] text-cyan-200">Isomerism source · page 19 · Part 60</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Further prototropic tautomerism</h1><p className="mt-3 text-sm leading-7 text-slate-300">The source lists five additional prototropic types and then explains how aromaticity, solvent and heterocyclic structure govern keto/hydroxy and thione/thiol equilibria.</p></header><section className="mt-7 grid gap-5">{pairs.map(pair=><Pair key={pair.type} pair={pair}/>)}</section><section className="mt-9 rounded-2xl border border-amber-300/25 bg-amber-300/[.07] p-5"><h2 className="text-xl font-black text-amber-100">Phenol and heterocycle stability points</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-7 text-amber-50"><li>For simple phenols, the equilibrium lies overwhelmingly toward the aromatic phenol; phenol itself has no detectable ordinary keto form.</li><li>Keto contribution becomes important with strongly stabilising substituents, fused aromatic rings, or heterocyclic systems.</li><li>Solvent matters: source pair 150/151 is represented by 150 in ethanol solution, while 151 predominates in vapour phase.</li><li>For the displayed 152/153 and 154/155 heterocycles, the hydroxy or thiol forms predominate under the stated conditions.</li></ul></section><section className="mt-9"><h2 className="text-xl font-black text-cyan-100">Source heterocycle pairs 150–155</h2><div className="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{([150,151,152,153,154,155] as const).map(n=><article key={n} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><b>{n}</b><Heterocycle n={n}/><p className="text-sm text-slate-300">{n===150?"4-pyridone form":n===151?"4-hydroxypyridine form":n===152?"2-hydroxypyridine form":n===153?"2-pyridone form":n===154?"pyridine-2-thiol form":"pyridine-2-thione form"}</p></article>)}</div></section><nav className="mt-8 flex justify-between border-t border-white/10 pt-6"><Link href="/learn/isomerism/59" className="rounded-xl border border-white/15 px-4 py-3 text-sm font-bold text-slate-200">← 59</Link><Link href="/learn/isomerism" className="rounded-xl border border-cyan-300/30 bg-cyan-300/10 px-4 py-3 text-sm font-bold text-cyan-100">Chapter overview</Link></nav></article></main>}
