import Link from "next/link";

type RingPiCase = { id: string; ring: 4 | 6; label: string; substituents: string[]; accepted: boolean; reason: string; kind?: "diene" | "oxime" | "sulfone" };
const cases: RingPiCase[] = [
  { id: "1", ring: 4, label: "gem-F/Cl cyclobutylidene-F/Cl", substituents: ["F", "Cl", "F", "Cl"], accepted: false, reason: "The two ring paths at the exocyclic alkene carbon are equivalent." },
  { id: "2", ring: 4, label: "bis(exocyclic) difluorodichloro cyclobutane", substituents: ["F", "Cl", "F", "Cl"], accepted: true, reason: "The two exocyclic C=C elements have distinguishable F/Cl ends in the locked ring framework." },
  { id: "3", ring: 4, label: "cumulated exocyclic diene on cyclobutane", substituents: ["F", "Cl", "F", "Cl"], accepted: true, kind: "diene", reason: "The source accepts this cumulene-ring arrangement: the terminal groups are distinguishable." },
  { id: "4", ring: 4, label: "methyl cyclobutylidene-F/Cl", substituents: ["CH₃", "F", "Cl"], accepted: true, reason: "The methyl substituent breaks equivalence of the two ring paths." },
  { id: "5", ring: 4, label: "unsubstituted cyclobutylidene-F/Cl", substituents: ["F", "Cl"], accepted: false, reason: "Without a ring substituent the two paths from the alkene carbon remain identical." },
  { id: "6", ring: 4, label: "methyl cyclobutylidene-Cl/F", substituents: ["CH₃", "Cl", "F"], accepted: true, reason: "Changing F/Cl order does not restore ring-path equivalence; GI remains possible." },
  { id: "7", ring: 4, label: "gem-dimethyl cyclobutylidene-F/Cl", substituents: ["CH₃", "CH₃", "F", "Cl"], accepted: true, reason: "The source marks the substituted ring framework as a valid ring-plus-π stereogenic unit." },
  { id: "8", ring: 4, label: "ethyl/methyl cyclobutylidene-F/Cl", substituents: ["CH₃", "Et", "F", "Cl"], accepted: true, reason: "Different methyl and ethyl paths make the cyclic alkene end distinguishable." },
  { id: "9", ring: 6, label: "unsubstituted cyclohexanone oxime", substituents: [], accepted: false, kind: "oxime", reason: "The two ring paths attached to C=N are equivalent." },
  { id: "10", ring: 6, label: "methylcyclohexanone oxime", substituents: ["CH₃"], accepted: true, kind: "oxime", reason: "Methyl substitution differentiates the two ring paths, so syn/anti geometry is meaningful." },
  { id: "11", ring: 6, label: "dimethylcyclohexanone oxime", substituents: ["CH₃", "CH₃"], accepted: true, kind: "oxime", reason: "The source marks this substituted oxime as a distinct geometrical case." },
  { id: "12", ring: 6, label: "methyl-bridged cyclohexanone oxime", substituents: ["CH₃"], accepted: true, kind: "oxime", reason: "The altered ring path gives two non-equivalent groups at the C=N carbon." },
  { id: "13", ring: 6, label: "cyclic sulfone (S=O)₂", substituents: [], accepted: true, kind: "sulfone", reason: "The source includes this locked cyclic S=O system as a ring-plus-π geometrical example." },
];

function RingPiStructure({ item }: { item: RingPiCase }) {
  const points = item.ring === 4 ? "88,28 132,68 88,108 44,68" : "62,30 112,30 142,68 112,106 62,106 32,68";
  const centreX = item.ring === 4 ? 88 : 142;
  return <svg viewBox="0 0 250 145" className="mt-3 w-full" role="img" aria-label={item.label}>
    <polygon points={points} fill="none" stroke="currentColor" strokeWidth="2.8" />
    {item.kind === "oxime" ? <><path d={`M${centreX} 68H205M${centreX} 74H205`} stroke="#67e8f9" strokeWidth="2.5" /><text x="210" y="76" fill="#f0abfc">N−OH</text></> : item.kind === "sulfone" ? <><text x="51" y="71" fill="#f0abfc">S</text><text x="118" y="71" fill="#f0abfc">S</text><text x="20" y="61" fill="#f0abfc">O</text><text x="130" y="61" fill="#f0abfc">O</text><path d="M34 65H49M34 71H49M119 65H134M119 71H134" stroke="#67e8f9" strokeWidth="2" /></> : <><path d={`M${centreX} 65H184M${centreX} 71H184`} stroke="#67e8f9" strokeWidth="2.5" />{item.kind === "diene" && <><path d="M184 65H213M184 71H213" stroke="#67e8f9" strokeWidth="2.5" /><text x="215" y="50" fill="#f0abfc">F</text><text x="215" y="96" fill="#f0abfc">Cl</text></>}<text x="191" y="51" fill="#f0abfc">F</text><text x="191" y="96" fill="#f0abfc">Cl</text></>}
    {item.substituents.filter(x => x === "CH₃" || x === "Et").map((x, index) => <g key={`${x}-${index}`}><path d={`M${60 + index * 32} ${item.ring === 4 ? 42 : 31}L${60 + index * 32} 12`} stroke="#f0abfc" strokeWidth="2.3" /><text x={48 + index * 32} y="12" fill="#f0abfc" fontSize="13">{x}</text></g>)}
    <text x="125" y="137" textAnchor="middle" fill={item.accepted ? "#86efac" : "#fda4af"} fontWeight="700">{item.accepted ? "✓ source accepts GI" : "× source rejects GI"}</text>
  </svg>;
}

export default function IsomerismPart80() { return <main className="min-h-screen bg-[#08111f] px-4 py-8 text-white sm:px-6 sm:py-12"><article className="mx-auto max-w-6xl"><Link href="/learn/isomerism" className="rounded-full border border-cyan-300/30 bg-cyan-300/10 px-4 py-2 text-sm font-bold text-cyan-100">Isomerism</Link><header className="mt-6 rounded-3xl border border-cyan-300/15 bg-[#08111f] p-6 sm:p-9"><p className="text-xs font-black uppercase tracking-[.24em] text-cyan-200">Isomerism source · page 70 · Part 80</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Ring + π-bond: every source accept/reject case</h1><p className="mt-4 max-w-3xl text-slate-300">For an exocyclic C=C or C=N attached to a ring, treat the two routes around the ring as the two groups on that end. A substituent only matters if it makes those routes genuinely non-equivalent.</p></header><section className="mt-7 grid gap-4 md:grid-cols-2">{cases.map(item => <article key={item.id} className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="font-black text-cyan-100">Source case {item.id}: {item.label}</h2><RingPiStructure item={item} /><p className="text-sm leading-6 text-slate-300"><b className={item.accepted ? "text-emerald-300" : "text-rose-300"}>{item.accepted ? "GI possible." : "No GI."}</b> {item.reason}</p></article>)}</section><aside className="mt-7 rounded-2xl border border-amber-300/25 bg-amber-300/[.07] p-5 text-sm leading-6 text-amber-50"><b>Common error:</b> an exocyclic double bond is not automatically E/Z-capable. Trace both ring paths away from its ring carbon; if they are constitutionally identical, that end fails the two-different-groups test.</aside></article></main>; }
