import Link from "next/link";
import { HashedWedge, SolidWedge } from "../components/ChemistryDiagram";

const variants = [
  { n: 38, faces: ["solid", "hash", "solid", "solid"] },
  { n: 39, faces: ["solid", "solid", "hash", "hash"] },
  { n: 40, faces: ["hash", "solid", "hash", "solid"] },
  { n: 41, faces: ["hash", "solid", "solid", "hash"] },
  { n: 42, faces: ["hash", "hash", "hash", "hash"] },
] as const;
type Face = (typeof variants)[number]["faces"][number];
function StereoBond({ from, to, face }: { from: {x:number;y:number}; to: {x:number;y:number}; face: Face }) { return face === "solid" ? <SolidWedge from={from} to={to} width={10}/> : <HashedWedge from={from} to={to} width={12}/>; }
function ChlorinatedAlkene({ n, faces }: { n: number; faces: readonly Face[] }) { const centres = [{x:72,y:52},{x:72,y:106},{x:188,y:52},{x:188,y:106}]; const chlorineEnds = [{x:72,y:22},{x:72,y:136},{x:188,y:22},{x:188,y:136}]; const methylEnds = [{x:18,y:54},{x:18,y:108},{x:242,y:54},{x:242,y:108}]; return <svg viewBox="0 0 260 150" className="h-auto w-full text-slate-100" role="img" aria-label={`source structure ${n}: tetrachlorinated substituted alkene`}><g fill="none" stroke="currentColor" strokeWidth="2.8" strokeLinecap="round"><line x1="72" y1="52" x2="116" y2="79"/><line x1="72" y1="106" x2="116" y2="79"/><line x1="144" y1="79" x2="188" y2="52"/><line x1="144" y1="79" x2="188" y2="106"/><line x1="116" y1="76" x2="144" y2="76"/><line x1="116" y1="82" x2="144" y2="82"/><line x1="72" y1="52" x2="18" y2="54"/><line x1="72" y1="106" x2="18" y2="108"/><line x1="188" y1="52" x2="242" y2="54"/><line x1="188" y1="106" x2="242" y2="108"/></g>{centres.map((centre, index) => <StereoBond key={index} from={centre} to={chlorineEnds[index]} face={faces[index]}/>)}{methylEnds.map((point,index)=><text key={index} x={point.x + (index < 2 ? -16 : 2)} y={point.y + 5} fontSize="16">CH₃</text>)}{chlorineEnds.map((point,index)=><text key={index} x={point.x - 8} y={point.y + (index % 2 === 0 ? -3 : 15)} fontSize="16">Cl</text>)}</svg>; }
export default function IsomerismPart35(){return <main className="min-h-screen bg-[#08111f] px-4 py-8 text-white sm:px-6 sm:py-12"><article className="mx-auto max-w-6xl"><Link href="/learn/isomerism" className="rounded-full border border-cyan-300/30 bg-cyan-300/10 px-4 py-2 text-sm font-bold text-cyan-100">Isomerism</Link><header className="mt-6 rounded-3xl border border-cyan-300/15 bg-[radial-gradient(circle_at_top_right,_rgba(34,211,238,.18),_transparent_35%),linear-gradient(135deg,rgba(34,211,238,.08),rgba(2,6,23,.7),rgba(139,92,246,.1))] p-6 sm:p-9"><p className="text-xs font-black uppercase tracking-[.24em] text-cyan-200">Optical Isomerism source · page 110 · Part 35</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Chirality exercise: chlorinated alkene configurations</h1><p className="mt-3 text-sm leading-7 text-slate-300">Source structures 38–42 retain the same carbon skeleton but change the visible forward/backward chlorine positions. They must not be merged: each is a distinct stereochemical case.</p></header><section className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{variants.map((item)=><article key={item.n} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><span className="rounded bg-slate-700 px-2 py-1 text-xs font-black">{item.n}</span><ChlorinatedAlkene n={item.n} faces={item.faces}/><p className="border-t border-white/10 pt-3 text-sm leading-6 text-slate-300">Keep the C=C framework fixed, then compare all four explicitly drawn chlorine faces. A mirror plane or inversion centre must be located in the full configuration before classifying optical activity.</p></article>)}</section><aside className="mt-6 rounded-2xl border border-amber-300/25 bg-amber-300/[.07] p-5 text-sm leading-7 text-amber-50"><strong>Source rule:</strong> changing one solid wedge to a hashed wedge changes configuration. Do not infer an enantiomeric relationship from a two-dimensional resemblance; draw the reflected, non-superimposable form.</aside><nav className="mt-8 flex justify-between border-t border-white/10 pt-6"><Link href="/learn/isomerism/34" className="rounded-xl border border-white/15 px-4 py-3 text-sm font-bold text-slate-200">← 34</Link><Link href="/learn/isomerism" className="rounded-xl border border-cyan-300/30 bg-cyan-300/10 px-4 py-3 text-sm font-bold text-cyan-100">Chapter overview</Link></nav></article></main>}
