import Link from "next/link";

const rad=(n:number)=>n*Math.PI/180;
function Newman({mode, propane=false}:{mode:"staggered"|"eclipsed"|"skew";propane?:boolean}) {
  const front=[-90,30,150]; const rear=mode==="staggered"?[-30,90,210]:mode==="eclipsed"?[-90,30,150]:[-60,60,180];
  const at=(d:number,r=45)=>({x:100+r*Math.cos(rad(d)),y:72+r*Math.sin(rad(d))});
  const f=propane?["H","H","H"]:["H","H","H"]; const r=propane?["Me","H","H"]:["H","H","H"];
  return <svg viewBox="0 0 200 145" className="w-full" role="img" aria-label={`${mode} ${propane?"propane":"ethane"} Newman projection`}><circle cx="100" cy="72" r="35" fill="none" stroke="#e2e8f0" strokeWidth="2.5"/>{rear.map((d,i)=>{const p=at(d);return <g key={`r${i}`}><path d={`M100 72L${p.x} ${p.y}`} stroke="#67e8f9" strokeWidth="2.5"/><text x={p.x+(p.x<100?-12:4)} y={p.y+(p.y<72?-4:8)} fill="#a5f3fc" fontSize="15">{r[i]}</text></g>})}{front.map((d,i)=>{const p=at(d);return <g key={`f${i}`}><path d={`M100 72L${p.x} ${p.y}`} stroke="#f0abfc" strokeWidth="2.8"/><text x={p.x+(p.x<100?-12:4)} y={p.y+(p.y<72?-4:8)} fill="#f9a8d4" fontSize="15">{f[i]}</text></g>})}<circle cx="100" cy="72" r="6" fill="#f0abfc"/></svg>;
}
function EthaneCurve(){return <svg viewBox="0 0 440 220" className="mt-3 w-full" role="img" aria-label="Ethane eclipsed to staggered energy curve"><path d="M55 20V180H410M55 55H400" fill="none" stroke="#e2e8f0" strokeWidth="2"/><path d="M55 55 Q150 185 245 55 Q330 185 400 55" fill="none" stroke="#60a5fa" strokeWidth="3"/><path d="M150 180V158M245 180V55M340 180V158" stroke="#22c55e" strokeDasharray="4 4"/><text x="50" y="200" fill="#cbd5e1">0°</text><text x="137" y="200" fill="#cbd5e1">60°</text><text x="225" y="200" fill="#cbd5e1">120°</text><text x="8" y="58" fill="#93c5fd">eclipsed</text><text x="8" y="165" fill="#93c5fd">staggered</text></svg>}
export default function IsomerismPart111(){return <main className="min-h-screen bg-[#08111f] px-4 py-8 text-white sm:px-6 sm:py-12"><article className="mx-auto max-w-5xl"><Link href="/learn/isomerism" className="rounded-full border border-cyan-300/30 bg-cyan-300/10 px-4 py-2 text-sm font-bold text-cyan-100">Isomerism</Link><header className="mt-6 rounded-3xl border border-cyan-300/15 bg-[#08111f] p-6 sm:p-9"><p className="text-xs font-black uppercase tracking-[.24em] text-cyan-200">Isomerism source · page 101 · Part 111</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Ethane and propane conformations</h1></header><section className="mt-7 rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="text-2xl font-black text-cyan-100">1. Conformation of ethane</h2><p className="mt-3 text-sm leading-7 text-slate-300">Rotation about the C-C bond continuously interconverts the staggered and eclipsed ethane views. The staggered arrangement is more stable; total conformers are infinite.</p><div className="mt-4 grid gap-4 md:grid-cols-3"><figure><Newman mode="staggered"/><figcaption className="text-center text-sm font-bold text-emerald-200">staggered, 60° offset</figcaption></figure><figure><Newman mode="eclipsed"/><figcaption className="text-center text-sm font-bold text-rose-200">eclipsed, 0° offset</figcaption></figure><figure><Newman mode="skew"/><figcaption className="text-center text-sm font-bold text-slate-300">skew, 0° &lt; θ &lt; 60°</figcaption></figure></div><EthaneCurve/></section><section className="mt-7 rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="text-2xl font-black text-cyan-100">2. Conformation of propane</h2><p className="mt-3 text-sm leading-7 text-slate-300">Propane, CH₃-CH₂-CH₃, gives equivalent views on rotation by 60°. The methyl group is displayed explicitly on the rear carbon in each source Newman projection.</p><div className="mt-4 grid gap-4 md:grid-cols-3"><figure><Newman mode="eclipsed" propane/><figcaption className="text-center text-sm font-bold text-slate-300">a: eclipsed</figcaption></figure><figure><Newman mode="staggered" propane/><figcaption className="text-center text-sm font-bold text-emerald-200">b: staggered (60°)</figcaption></figure><figure><Newman mode="eclipsed" propane/><figcaption className="text-center text-sm font-bold text-slate-300">c: eclipsed (another 60°)</figcaption></figure></div><p className="mt-4 text-sm leading-7 text-slate-300"><b>Conclusion:</b> the three drawings are consecutive rotational positions; repeated staggered minima are equivalent for propane.</p></section></article></main>}
