import Link from "next/link";
import { NewmanProjection } from "../components/ChemistryDiagram";

const diagrams = [
  ["Ethane staggered", ["H", "H", "H", "H", "H", "H"], 60], ["Ethane eclipsed", ["H", "H", "H", "H", "H", "H"], 0], ["Propane staggered", ["CH₃", "H", "H", "H", "H", "H"], 60],
  ["Butane anti", ["CH₃", "H", "H", "H", "CH₃", "H"], 180], ["Butane gauche", ["CH₃", "H", "H", "CH₃", "H", "H"], 60], ["Butane partially eclipsed", ["CH₃", "H", "H", "H", "CH₃", "H"], 0], ["Butane fully eclipsed", ["CH₃", "H", "H", "CH₃", "H", "H"], 0],
] as const;
function Projection({ index }: { index: number }) { const [title, labels, dihedral] = diagrams[index]; return <NewmanProjection title={title} labels={labels} dihedral={dihedral}/>; }

export default function IsomerismPart08() { return <main className="min-h-screen bg-[#08111f] px-4 py-8 text-white sm:px-6 sm:py-12"><article className="mx-auto max-w-6xl"><Link href="/learn/isomerism" className="rounded-full border border-cyan-300/30 bg-cyan-300/10 px-4 py-2 text-sm font-bold text-cyan-100">Isomerism</Link><header className="mt-6 rounded-3xl border border-cyan-300/15 bg-[radial-gradient(circle_at_top_right,_rgba(34,211,238,.18),_transparent_35%),linear-gradient(135deg,rgba(34,211,238,.08),rgba(2,6,23,.7),rgba(139,92,246,.1))] p-6 sm:p-9"><p className="text-xs font-black uppercase tracking-[.24em] text-cyan-200">Isomerism source · pages 95–116 · Part 8</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Conformational analysis: σ-bond rotation</h1></header><section className="mt-7 space-y-6"><section className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="text-xl font-black text-cyan-200">Projection rule</h2><p className="mt-3 text-sm leading-7 text-slate-200">View along C1 → C2. The central dot is front carbon C1; the circle is rear carbon C2. Three bonds from each carbon are 120° apart. A staggered array is offset by 60°, eclipsed bonds align at 0°, and anti methyl groups are 180° apart.</p></section><section className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="text-xl font-black text-cyan-200">Ethane and propane</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><Projection index={0}/><Projection index={1}/><Projection index={2}/></div></section><section className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="text-xl font-black text-cyan-200">n-Butane: distinct source conformers</h2><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Projection index={3}/><Projection index={4}/><Projection index={5}/><Projection index={6}/></div><ol className="mt-4 list-decimal space-y-2 pl-5 text-sm leading-6 text-slate-300"><li>Anti: methyl groups are 180° apart; least steric and torsional strain.</li><li>Gauche: methyl groups are 60° apart; a local minimum.</li><li>Partially eclipsed: unequal groups align.</li><li>Fully eclipsed: methyl groups align; maximum along the butane rotational profile.</li></ol></section></section><nav className="mt-8 flex justify-between border-t border-white/10 pt-6"><Link href="/learn/isomerism/7" className="rounded-xl border border-white/15 px-4 py-3 text-sm font-bold text-slate-200">← 7</Link><Link href="/learn/isomerism/9" className="rounded-xl border border-cyan-300/30 bg-cyan-300/10 px-4 py-3 text-sm font-bold text-cyan-100">9 →</Link></nav></article></main>; }
