import Link from "next/link";
const examples=[
  ["Br/F versus I/Cl", "Z", "I > Br and Cl > F; the two priority-1 groups are together."],
  ["D/H versus CH₃/T", "Z", "Isotope mass resolves H/D/T: T > D > H; CH₃ outranks D at the other end."],
  ["alkyl/alkyl versus OH/alkyl", "Z", "Apply CIP at both ends; the higher-priority paths lie on the same side."],
  ["ClCH₂/OH versus ICH₂CH₂/C(CH₃)₃", "Z", "Atomic number and the first point of difference give the shown priorities."],
  ["HO/Ph versus CF₃/NH₂", "E", "O beats C; on the other carbon CF₃ wins over NH₂ by the source comparison."],
  ["alkyl versus vinyl/ethynyl", "E", "Use multiple-bond duplication before comparing the vinyl and ethynyl substituents."],
  ["I/ethyl versus F/hexyl", "E", "I and F decide the directly attached-atom comparison."],
  ["OHC/branched alkyl versus COOH/C≡CH", "Z", "The displayed carboxyl/ethynyl comparison uses the duplicate-atom rule."],
  ["N≡C/CHO versus C≡CH/C(CH₃)₃", "E", "Cyano and carbonyl attachment sets are compared before the alkyl paths."],
  ["CH₃/NC versus COCl/CH₂NH₂", "E", "The source ranks the carbonyl chloride path and the nitrogen-containing path by CIP sequence."],
] as const;
function EzExample({item,index}:{item:readonly[string,string,string];index:number}){const [label,result,reason]=item;return <article className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="font-black text-cyan-100">Source E/Z example {index+1}</h2><svg fill="currentColor" viewBox="0 0 310 130" className="mt-3 w-full" role="img" aria-label={label}><path d="M120 60H190M120 66H190" stroke="#67e8f9" strokeWidth="3"/><path d="M120 63 80 30m40 33-40 35M190 63l40-33m-40 33 40 35" stroke="currentColor" strokeWidth="2.5"/><circle cx="77" cy="27" r="12" fill="#155e75"/><text x="77" y="32" textAnchor="middle" fontSize="12">1</text><circle cx="231" cy={result==="Z"?27:101} r="12" fill="#155e75"/><text x="231" y={result==="Z"?32:106} textAnchor="middle" fontSize="12">1</text><text x="155" y="123" textAnchor="middle" fill={result==="Z"?"#86efac":"#fbbf24"} fontWeight="700">{result}</text></svg><p className="text-sm font-bold text-white">{label}</p><p className="mt-2 text-sm leading-6 text-slate-300">{reason}</p></article>}
export default function IsomerismPart95(){return <main className="min-h-screen bg-[#08111f] px-4 py-8 text-white sm:px-6 sm:py-12"><article className="mx-auto max-w-6xl"><Link href="/learn/isomerism" className="rounded-full border border-cyan-300/30 bg-cyan-300/10 px-4 py-2 text-sm font-bold text-cyan-100">Isomerism</Link><header className="mt-6 rounded-3xl border border-cyan-300/15 bg-[#08111f] p-6 sm:p-9"><p className="text-xs font-black uppercase tracking-[.24em] text-cyan-200">Isomerism source · page 85 · Part 95</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">E/Z assignments: source worked examples and special priority rules</h1><p className="mt-4 text-slate-300">Each source case assigns 1 and 2 on both alkene carbons, then reads the relative position of the two priority-1 groups. The structural comparisons below retain that workflow.</p></header><section className="mt-7 grid gap-4 md:grid-cols-2">{examples.map((item,index)=><EzExample key={item[0]} item={item} index={index}/>)}</section><section className="mt-8 grid gap-5 md:grid-cols-2"><article className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="text-xl font-black text-cyan-100">Real versus pseudo ligands</h2><p className="mt-3 text-sm leading-7 text-slate-300">The source states: when a real and a pseudo ligand are isostructural, the real ligand has priority. Apply this only after the normal atomic-number and sequence comparisons have tied.</p><p className="mt-3 text-sm text-amber-100">Reason: a real atom/path is preferred over its phantom-atom representation in the CIP construction.</p></article><article className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="text-xl font-black text-cyan-100">Stereoisomeric ligand convention</h2><p className="mt-3 text-sm leading-7 text-slate-300">When otherwise comparable stereoisomeric groups occur, the source convention gives cis priority over trans, Z over E, and R over S. Use this late in the comparison, never ahead of atomic-number rules.</p><p className="mt-3 text-sm text-amber-100">This is a tie-breaker for enantiomorphic/diastereomorphic ligand comparisons.</p></article></section></article></main>}
