import Link from "next/link";

type PairKind = "acid" | "aryl" | "ester" | "nitrile" | "anhydride";

const data: Record<PairKind, { id: string; question: string; result: string; reason: string }> = {
  acid: { id: "(a)", question: "CH₃COCl (I) and CH₂=C(OH)Cl (II)", result: "II is less stable.", reason: "The carbonyl C=O bond of the acid chloride is strongly stabilising; its enol lacks compensating conjugation or chelation." },
  aryl: { id: "(b)", question: "acetophenone (I) and its enol Ph–C(OH)=CH₂ (II)", result: "II is less stable.", reason: "The keto form retains C=O; the displayed enol is not additionally aromatic." },
  ester: { id: "(c)", question: "methyl acetate (I) and CH₂=C(OH)–OCH₃ (II)", result: "II is less stable.", reason: "The ester carbonyl is stabilised by n→π conjugation; ordinary enolisation does not outweigh it." },
  nitrile: { id: "(d)", question: "CH₃–C≡N (I) and CH₂=C=NH (II)", result: "II is less stable.", reason: "The nitrile triple bond is strongly stabilised; the ketenimine tautomer has no listed compensating stabilisation." },
  anhydride: { id: "(e)", question: "acetic anhydride (I) and its vinyl ester enol (II)", result: "I is less stable.", reason: "The printed source key selects I for this specific pair; retain that source conclusion rather than applying a generic carbonyl-bond shortcut." },
};

function PairStructure({ kind }: { kind: PairKind }) {
  const b = { stroke: "currentColor", strokeWidth: 2.8, fill: "none", strokeLinecap: "round" as const };
  const dbl = (x: number, y: number, x2: number, y2: number) => <><path d={`M${x} ${y - 3}L${x2} ${y2 - 3}`} {...b}/><path d={`M${x} ${y + 3}L${x2} ${y2 + 3}`} {...b}/></>;
  const triple = (x: number, y: number, x2: number, y2: number) => <><path d={`M${x} ${y - 5}L${x2} ${y2 - 5}`} {...b}/><path d={`M${x} ${y}L${x2} ${y2}`} {...b}/><path d={`M${x} ${y + 5}L${x2} ${y2 + 5}`} {...b}/></>;
  const t = (x: number, y: number, s: string) => <text x={x} y={y} fill="currentColor" fontSize="15" textAnchor="middle">{s}</text>;
  const left = kind === "nitrile" ? <>{t(42,102,"CH₃")}{triple(66,95,116,95)}{t(132,102,"N")}</> : kind === "anhydride" ? <><path d="M35 100L82 72L128 100L174 72" {...b}/>{t(24,108,"CH₃")}{t(82,79,"C")}{dbl(82,72,82,30)}{t(82,24,"O")}{t(133,108,"O")}{t(174,79,"C")}{dbl(174,72,174,30)}{t(174,24,"O")}{t(194,72,"CH₃")}</> : <><path d="M38 100L84 72L130 100" {...b}/>{t(23,108,"CH₃")}{t(84,79,"C")}{dbl(84,72,84,30)}{t(84,24,"O")}{t(145,108,kind === "acid" ? "Cl" : kind === "ester" ? "OCH₃" : "Ph")}</>;
  const right = kind === "nitrile" ? <>{t(352,102,"CH₂")}{dbl(380,95,430,95)}{t(450,102,"C")}{dbl(465,95,510,95)}{t(530,102,"NH")}</> : kind === "anhydride" ? <><path d="M350 100L396 72L442 100L488 72" {...b}/>{t(335,108,"CH₃")}{t(402,79,"C")}{dbl(396,72,442,100)}{t(450,108,"C")}<path d="M442 100L442 38" {...b}/>{t(442,30,"OH")}{t(510,72,"O")}{t(528,72,"CH₂")}</> : <><path d="M350 100L396 72L442 100" {...b}/>{t(335,108,kind === "aryl" ? "Ph" : "CH₂")}{t(402,79,"C")}{dbl(396,72,442,100)}{t(450,108,kind === "acid" ? "Cl" : kind === "ester" ? "OCH₃" : "CH₂")}<path d="M396 72L396 32" {...b}/>{t(396,25,"OH")}</>;
  return <svg viewBox="0 0 560 132" className="mt-3 w-full min-w-[470px]" role="img" aria-label={data[kind].question}>{left}<path d="M244 78h50m-10-8 10 8-10 8M294 98h-50m10-8-10 8 10 8" stroke="#67e8f9" strokeWidth="2.5" fill="none"/>{right}<text x="270" y="55" fill="#a5f3fc" fontSize="12" textAnchor="middle">tautomeric pair</text></svg>;
}

export default function IsomerismPart62() { return <main className="min-h-screen bg-[#08111f] px-4 py-8 text-white sm:px-6 sm:py-12"><article className="mx-auto max-w-6xl"><Link href="/learn/isomerism" className="rounded-full border border-cyan-300/30 bg-cyan-300/10 px-4 py-2 text-sm font-bold text-cyan-100">Isomerism</Link><header className="mt-6 rounded-3xl border border-cyan-300/15 bg-[radial-gradient(circle_at_top_right,_rgba(34,211,238,.18),_transparent_35%),linear-gradient(135deg,rgba(34,211,238,.08),rgba(2,6,23,.7),rgba(139,92,246,.1))] p-6 sm:p-9"><p className="text-xs font-black uppercase tracking-[.24em] text-cyan-200">Isomerism source · page 54 · Part 62</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Tautomer stability: source pair bank I</h1><p className="mt-3 text-sm leading-7 text-slate-300">Source question: <i>In each of the following pairs which is less stable?</i> Each pair is kept separate because its functional-group stabilisation differs.</p></header><section className="mt-7 grid gap-4"><>{(Object.keys(data) as PairKind[]).map((kind) => <article key={kind} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><h2 className="font-black text-cyan-100">{data[kind].id} {data[kind].question}</h2><div className="overflow-x-auto"><PairStructure kind={kind}/></div><ol className="mt-3 list-decimal space-y-1 pl-5 text-sm leading-6 text-slate-300"><li>Compare the carbonyl/nitrile π-bond stabilisation in I with the relocated π bond in II.</li><li>Check for a special gain such as aromaticity, conjugation or intramolecular chelation.</li><li><b>Conclusion:</b> {data[kind].result} {data[kind].reason}</li></ol></article>)}</></section><nav className="mt-8 flex justify-between border-t border-white/10 pt-6"><Link href="/learn/isomerism/61" className="rounded-xl border border-white/15 px-4 py-3 text-sm font-bold text-slate-200">← 61</Link><Link href="/learn/isomerism" className="rounded-xl border border-cyan-300/30 bg-cyan-300/10 px-4 py-3 text-sm font-bold text-cyan-100">Chapter overview</Link></nav></article></main>; }
