import Link from "next/link";
function Configuration({labels}:{labels:string[]}){return <svg viewBox="0 0 230 105" className="w-full" role="img" aria-label={`configuration ${labels.join(" ")}`}><path d="M80 48H150M80 54H150" stroke="#67e8f9" strokeWidth="3"/><path d="M80 51 52 24m28 27-28 27M150 51l28-27m-28 27 28 27" stroke="currentColor" strokeWidth="2.3"/><text x="43" y="22" fill="#f0abfc">{labels[0]}</text><text x="43" y="86" fill="#f0abfc">{labels[1]}</text><text x="178" y="22" fill="#f0abfc">{labels[2]}</text><text x="178" y="86" fill="#f0abfc">{labels[3]}</text></svg>}
const banks=[
{number:12,title:"Two identical diene arms attached to C=CH₂",forms:[["E","E","E","E"],["E","Z","Z","E"],["Z","Z","Z","Z"]]},
{number:13,title:"Two identical diene arms attached to C=CHCH₃",forms:[["E","E","E","E"],["E","Z","Z","E"],["Z","E","E","Z"],["Z","Z","Z","Z"]]},
{number:14,title:"Symmetrical four-arm cumulene system",forms:[["Z","Z","Z","Z"],["E","Z","Z","E"],["E","E","Z","Z"],["E","Z","E","Z"],["E","E","E","E"]]},
{number:15,title:"Unsymmetrical terminal diene arms",forms:[["Z","Z","Z","Z"],["Z","E","E","Z"],["E","Z","Z","E"],["E","E","E","E"]]},
] as const;
export default function IsomerismPart101(){return <main className="min-h-screen bg-[#08111f] px-4 py-8 text-white sm:px-6 sm:py-12"><article className="mx-auto max-w-6xl"><Link href="/learn/isomerism" className="rounded-full border border-cyan-300/30 bg-cyan-300/10 px-4 py-2 text-sm font-bold text-cyan-100">Isomerism</Link><header className="mt-6 rounded-3xl border border-cyan-300/15 bg-[#08111f] p-6 sm:p-9"><p className="text-xs font-black uppercase tracking-[.24em] text-cyan-200">Isomerism source · page 91 · Part 101</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Enumerating symmetry-reduced geometrical configurations</h1><p className="mt-4 text-slate-300">The source writes each geometry rather than trusting a numerical shortcut. These banks retain the separate E/Z layouts that survive the displayed molecular symmetry.</p></header><section className="mt-7 space-y-7">{banks.map(bank=><section key={bank.number} className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="text-2xl font-black text-cyan-100">Source example {bank.number}: {bank.title}</h2><p className="mt-2 text-sm leading-6 text-slate-300">Write every valid E/Z arrangement, then merge only those related by the actual symmetry of the complete molecular framework.</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{bank.forms.map((form,index)=><article key={`${bank.number}-${index}`} className="rounded-xl border border-cyan-300/20 p-4"><Configuration labels={[...form]}/><p className="text-center text-sm font-bold text-slate-200">{form.join(" / ")}</p></article>)}</div><p className="mt-4 text-sm text-amber-100"><b>Conclusion:</b> the source retains {bank.forms.length} distinct displayed configurations for this framework after symmetry equivalences are removed.</p></section>)}</section><aside className="mt-7 rounded-2xl border border-amber-300/25 bg-amber-300/[.07] p-5 text-sm leading-6 text-amber-50"><b>Counting discipline:</b> configurations that look different as an isolated double bond may coincide after the entire symmetric arm system is reversed. Conversely, changing a terminal group removes that equivalence.</aside></article></main>}
