import type { MoleculeRegistry, MoleculeSpec } from "@/lib/chemistry/molecule-types";

const molecule = <T extends MoleculeSpec>(spec: T): T => spec;

export const ISOMERISM_MOLECULES = {
  nButane: molecule({
    id: "n-butane",
    structure: { kind: "smiles", value: "CCCC" },
    alt: "Skeletal structure of normal butane",
    label: "n-Butane: unbranched four-carbon skeleton, C₄H₁₀.",
    theme: "dark",
  }),
  isobutane: molecule({
    id: "isobutane",
    structure: { kind: "smiles", value: "CC(C)C" },
    alt: "Skeletal structure of 2-methylpropane, also called isobutane",
    label:
      "2-Methylpropane: branched four-carbon skeleton, C₄H₁₀. Connectivity differs from n-butane.",
    theme: "dark",
  }),
  propan1ol: molecule({
    id: "propan-1-ol",
    structure: { kind: "smiles", value: "CCCO" },
    alt: "Skeletal structure of propan-1-ol",
    label: "Propan-1-ol: hydroxyl group on terminal carbon.",
    theme: "dark",
  }),
  propan2ol: molecule({
    id: "propan-2-ol",
    structure: { kind: "smiles", value: "CC(O)C" },
    alt: "Skeletal structure of propan-2-ol",
    label:
      "Propan-2-ol: hydroxyl group on middle carbon. Same three-carbon skeleton and formula C₃H₈O.",
    theme: "dark",
  }),
  propene: molecule({
    id: "propene",
    structure: { kind: "smiles", value: "CC=C" },
    alt: "Skeletal structure of propene",
    label: "Propene: acyclic C₃H₆ with one carbon–carbon double bond.",
    theme: "dark",
  }),
  cyclopropane: molecule({
    id: "cyclopropane",
    structure: { kind: "smiles", value: "C1CC1" },
    alt: "Skeletal ring structure of cyclopropane",
    label: "Cyclopropane: cyclic C₃H₆ with a three-membered ring.",
    theme: "dark",
  }),
  ethanol: molecule({
    id: "ethanol",
    structure: { kind: "smiles", value: "CCO" },
    alt: "Skeletal structure of ethanol",
    label: "Ethanol: alcohol connectivity, C₂H₆O.",
    theme: "dark",
  }),
  dimethylEther: molecule({
    id: "dimethyl-ether",
    structure: { kind: "smiles", value: "COC" },
    alt: "Skeletal structure of dimethyl ether",
    label: "Dimethyl ether: ether connectivity, C₂H₆O.",
    theme: "dark",
  }),
  nPentane: molecule({
    id: "n-pentane",
    structure: { kind: "smiles", value: "CCCCC" },
    alt: "Skeletal structure of normal pentane",
    label: "n-Pentane",
    theme: "dark",
  }),
  isopentane: molecule({
    id: "isopentane",
    structure: { kind: "smiles", value: "CCC(C)C" },
    alt: "Skeletal structure of 2-methylbutane",
    label: "2-Methylbutane",
    theme: "dark",
  }),
  neopentane: molecule({
    id: "neopentane",
    structure: { kind: "smiles", value: "CC(C)(C)C" },
    alt: "Skeletal structure of 2,2-dimethylpropane",
    label: "2,2-Dimethylpropane",
    theme: "dark",
  }),
  ethoxyethane: molecule({
    id: "ethoxyethane",
    structure: { kind: "smiles", value: "CCOCC" },
    alt: "Skeletal structure of ethoxyethane",
    label: "Ethoxyethane",
    theme: "dark",
  }),
  methoxypropane: molecule({
    id: "methoxypropane",
    structure: { kind: "smiles", value: "COCCC" },
    alt: "Skeletal structure of 1-methoxypropane",
    label: "1-Methoxypropane",
    theme: "dark",
  }),
  butanal: molecule({
    id: "butanal",
    structure: { kind: "smiles", value: "CCCC=O" },
    alt: "Skeletal structure of butanal",
    label: "Butanal",
    theme: "dark",
  }),
  butan2one: molecule({
    id: "butan-2-one",
    structure: { kind: "smiles", value: "CC(=O)CC" },
    alt: "Skeletal structure of butan-2-one",
    label: "Butan-2-one",
    theme: "dark",
  }),
  but1en2ol: molecule({
    id: "but-1-en-2-ol",
    structure: { kind: "smiles", value: "C=C(O)CC" },
    alt: "Skeletal structure of but-1-en-2-ol",
    label: "But-1-en-2-ol",
    theme: "dark",
  }),
  propanoicAcid: molecule({
    id: "propanoic-acid",
    structure: { kind: "smiles", value: "CCC(=O)O" },
    alt: "Skeletal structure of propanoic acid",
    label: "Propanoic acid",
    theme: "dark",
  }),
  methylEthanoate: molecule({
    id: "methyl-ethanoate",
    structure: { kind: "smiles", value: "CC(=O)OC" },
    alt: "Skeletal structure of methyl ethanoate",
    label: "Methyl ethanoate",
    theme: "dark",
  }),
  cis2Butene: molecule({
    id: "cis-2-butene",
    structure: { kind: "smiles", value: "C/C=C\\C" },
    alt: "Stereochemical structure of cis-2-butene",
    label: "Z (cis): priority-1 groups are on the same side.",
    showStereoAnnotation: true,
    theme: "dark",
  }),
  trans2Butene: molecule({
    id: "trans-2-butene",
    structure: { kind: "smiles", value: "C/C=C/C" },
    alt: "Stereochemical structure of trans-2-butene",
    label: "E (trans): priority-1 groups are on opposite sides.",
    showStereoAnnotation: true,
    theme: "dark",
  }),
  acetylacetoneKeto: molecule({
    id: "acetylacetone-keto",
    structure: { kind: "smiles", value: "CC(=O)CC(=O)C" },
    alt: "Diketo form of acetylacetone",
    label: "Diketo form",
    theme: "dark",
  }),
  acetylacetoneEnol: molecule({
    id: "acetylacetone-enol",
    structure: { kind: "smiles", value: "CC(O)=CC(=O)C" },
    alt: "Chelated enol form of acetylacetone",
    label: "Chelated enol form",
    theme: "dark",
  }),
  lacticAcidStereoA: molecule({
    id: "lactic-acid-stereoisomer-a",
    structure: { kind: "smiles", value: "C[C@H](O)C(=O)O" },
    alt: "One stereoisomer of lactic acid",
    label: "Lactic acid stereoisomer",
    theme: "dark",
  }),
  lacticAcidStereoB: molecule({
    id: "lactic-acid-stereoisomer-b",
    structure: { kind: "smiles", value: "C[C@@H](O)C(=O)O" },
    alt: "Mirror-image stereoisomer of lactic acid",
    label: "Mirror stereoisomer",
    theme: "dark",
  }),
  benzene: molecule({
    id: "benzene",
    structure: { kind: "smiles", value: "c1ccccc1" },
    alt: "Aromatic skeletal structure of benzene",
    label: "Benzene",
    theme: "dark",
  }),
  methylcyclohexane: molecule({
    id: "methylcyclohexane",
    structure: { kind: "smiles", value: "CC1CCCCC1" },
    alt: "Skeletal structure of methylcyclohexane",
    label: "Methylcyclohexane",
    theme: "dark",
  }),
  cyclobutane: molecule({
    id: "cyclobutane",
    structure: { kind: "smiles", value: "C1CCC1" },
    alt: "Skeletal ring structure of cyclobutane",
    label: "Cyclobutane: cyclic C₄H₈, four-membered ring.",
    theme: "dark",
  }),
  methylcyclopropane: molecule({
    id: "methylcyclopropane",
    structure: { kind: "smiles", value: "CC1CC1" },
    alt: "Skeletal structure of methylcyclopropane",
    label: "Methylcyclopropane: cyclic C₄H₈, three-membered ring with a methyl substituent.",
    theme: "dark",
  }),
  propylcyclopropane: molecule({
    id: "propylcyclopropane",
    structure: { kind: "smiles", value: "CCCC1CC1" },
    alt: "Skeletal structure of propylcyclopropane",
    label: "Propylcyclopropane: C₆H₁₂, three-membered ring.",
    theme: "dark",
  }),
  ethylcyclobutane: molecule({
    id: "ethylcyclobutane",
    structure: { kind: "smiles", value: "CCC1CCC1" },
    alt: "Skeletal structure of ethylcyclobutane",
    label: "Ethylcyclobutane: C₆H₁₂, four-membered ring.",
    theme: "dark",
  }),
  methylcyclopentane: molecule({
    id: "methylcyclopentane",
    structure: { kind: "smiles", value: "CC1CCCC1" },
    alt: "Skeletal structure of methylcyclopentane",
    label: "Methylcyclopentane: C₆H₁₂, five-membered ring.",
    theme: "dark",
  }),
  cyclohexane: molecule({
    id: "cyclohexane",
    structure: { kind: "smiles", value: "C1CCCCC1" },
    alt: "Skeletal ring structure of cyclohexane",
    label: "Cyclohexane: C₆H₁₂, six-membered ring.",
    theme: "dark",
  }),
  chlorobutane1: molecule({
    id: "1-chlorobutane",
    structure: { kind: "smiles", value: "CCCCCl" },
    alt: "Skeletal structure of 1-chlorobutane",
    label: "1-Chlorobutane: unbranched C₄H₉Cl.",
    theme: "dark",
  }),
  tertButylChloride: molecule({
    id: "2-chloro-2-methylpropane",
    structure: { kind: "smiles", value: "CC(C)(C)Cl" },
    alt: "Skeletal structure of 2-chloro-2-methylpropane",
    label: "2-Chloro-2-methylpropane: branched C₄H₉Cl.",
    theme: "dark",
  }),
  butanenitrile: molecule({
    id: "butanenitrile",
    structure: { kind: "smiles", value: "CCCC#N" },
    alt: "Skeletal structure of butanenitrile",
    label: "Butanenitrile: unbranched C₄H₇N.",
    theme: "dark",
  }),
  isobutyronitrile: molecule({
    id: "2-methylpropanenitrile",
    structure: { kind: "smiles", value: "CC(C)C#N" },
    alt: "Skeletal structure of 2-methylpropanenitrile",
    label: "2-Methylpropanenitrile: branched C₄H₇N.",
    theme: "dark",
  }),
  butanoicAcid: molecule({
    id: "butanoic-acid",
    structure: { kind: "smiles", value: "CCCC(=O)O" },
    alt: "Skeletal structure of butanoic acid",
    label: "Butanoic acid: unbranched C₄H₈O₂.",
    theme: "dark",
  }),
  isobutyricAcid: molecule({
    id: "2-methylpropanoic-acid",
    structure: { kind: "smiles", value: "CC(C)C(=O)O" },
    alt: "Skeletal structure of 2-methylpropanoic acid",
    label: "2-Methylpropanoic acid: branched C₄H₈O₂.",
    theme: "dark",
  }),
  butanamide: molecule({
    id: "butanamide",
    structure: { kind: "smiles", value: "CCCC(N)=O" },
    alt: "Skeletal structure of butanamide",
    label: "Butanamide: unbranched C₄H₉NO.",
    theme: "dark",
  }),
  isobutyramide: molecule({
    id: "2-methylpropanamide",
    structure: { kind: "smiles", value: "CC(C)C(N)=O" },
    alt: "Skeletal structure of 2-methylpropanamide",
    label: "2-Methylpropanamide: branched C₄H₉NO.",
    theme: "dark",
  }),
  dimethylmalononitrile: molecule({
    id: "2,2-dimethylpropanedinitrile",
    structure: { kind: "smiles", value: "CC(C)(C#N)C#N" },
    alt: "Skeletal structure of 2,2-dimethylpropanedinitrile",
    label: "2,2-Dimethylpropanedinitrile: both nitriles on one quaternary carbon.",
    theme: "dark",
  }),
  methylpentanedinitrile: molecule({
    id: "2-methylpentanedinitrile",
    structure: { kind: "smiles", value: "N#CC(C)CC#N" },
    alt: "Skeletal structure of 2-methylpentanedinitrile",
    label: "2-Methylpentanedinitrile: same C₅H₆N₂ formula, chain-distributed nitriles.",
    theme: "dark",
  }),
  bromopropane1: molecule({
    id: "1-bromopropane",
    structure: { kind: "smiles", value: "CCCBr" },
    alt: "Skeletal structure of 1-bromopropane",
    label: "1-Bromopropane: bromine on the terminal carbon.",
    theme: "dark",
  }),
  bromopropane2: molecule({
    id: "2-bromopropane",
    structure: { kind: "smiles", value: "CC(Br)C" },
    alt: "Skeletal structure of 2-bromopropane",
    label: "2-Bromopropane: bromine on the middle carbon, same C₃H₇Br skeleton.",
    theme: "dark",
  }),
  nHexane: molecule({
    id: "n-hexane",
    structure: { kind: "smiles", value: "CCCCCC" },
    alt: "Skeletal structure of n-hexane",
    label: "n-Hexane: (6,0) unbranched hexane isomer.",
    theme: "dark",
  }),
  methylpentane2: molecule({
    id: "2-methylpentane",
    structure: { kind: "smiles", value: "CC(C)CCC" },
    alt: "Skeletal structure of 2-methylpentane",
    label: "2-Methylpentane: (5,1) hexane isomer, methyl on C2.",
    theme: "dark",
  }),
  methylpentane3: molecule({
    id: "3-methylpentane",
    structure: { kind: "smiles", value: "CCC(C)CC" },
    alt: "Skeletal structure of 3-methylpentane",
    label: "3-Methylpentane: (5,1) hexane isomer, methyl on C3 — position isomer of 2-methylpentane.",
    theme: "dark",
  }),
  nHeptane: molecule({
    id: "n-heptane",
    structure: { kind: "smiles", value: "CCCCCCC" },
    alt: "Skeletal structure of n-heptane",
    label: "n-Heptane: (7,0) unbranched heptane isomer.",
    theme: "dark",
  }),
  methylhexane2: molecule({
    id: "2-methylhexane",
    structure: { kind: "smiles", value: "CC(C)CCCC" },
    alt: "Skeletal structure of 2-methylhexane",
    label: "2-Methylhexane: (6,1) heptane isomer, methyl on C2.",
    theme: "dark",
  }),
  methylhexane3: molecule({
    id: "3-methylhexane",
    structure: { kind: "smiles", value: "CCC(C)CCC" },
    alt: "Skeletal structure of 3-methylhexane",
    label: "3-Methylhexane: (6,1) heptane isomer, methyl on C3 — position isomer of 2-methylhexane.",
    theme: "dark",
  }),
  but1yne: molecule({
    id: "but-1-yne",
    structure: { kind: "smiles", value: "CCC#C" },
    alt: "Skeletal structure of but-1-yne",
    label: "But-1-yne: triple bond at the terminal position.",
    theme: "dark",
  }),
  but2yne: molecule({
    id: "but-2-yne",
    structure: { kind: "smiles", value: "CC#CC" },
    alt: "Skeletal structure of but-2-yne",
    label: "But-2-yne: triple bond at the internal position, same C₄H₆ skeleton.",
    theme: "dark",
  }),
  pentan1ol: molecule({
    id: "pentan-1-ol",
    structure: { kind: "smiles", value: "CCCCCO" },
    alt: "Skeletal structure of pentan-1-ol",
    label: "Pentan-1-ol: hydroxyl on the terminal carbon.",
    theme: "dark",
  }),
  pentan2ol: molecule({
    id: "pentan-2-ol",
    structure: { kind: "smiles", value: "CCCC(O)C" },
    alt: "Skeletal structure of pentan-2-ol",
    label: "Pentan-2-ol: hydroxyl on C2, same C₅H₁₂O skeleton.",
    theme: "dark",
  }),
  catechol: molecule({
    id: "catechol",
    structure: { kind: "smiles", value: "Oc1ccccc1O" },
    alt: "Skeletal structure of catechol",
    label: "Catechol: benzene-1,2-diol.",
    theme: "dark",
  }),
  resorcinol: molecule({
    id: "resorcinol",
    structure: { kind: "smiles", value: "Oc1cccc(O)c1" },
    alt: "Skeletal structure of resorcinol",
    label: "Resorcinol: benzene-1,3-diol — position isomer of catechol.",
    theme: "dark",
  }),
  quinol: molecule({
    id: "quinol",
    structure: { kind: "smiles", value: "Oc1ccc(O)cc1" },
    alt: "Skeletal structure of quinol",
    label: "Quinol (hydroquinone): benzene-1,4-diol — position isomer of catechol and resorcinol.",
    theme: "dark",
  }),
  propene2: molecule({
    id: "propene-ring-chain",
    structure: { kind: "smiles", value: "CC=C" },
    alt: "Skeletal structure of propene",
    label: "Propene: acyclic, one degree of unsaturation as a π bond.",
    theme: "dark",
  }),
  but2yneRingChain: molecule({
    id: "but-2-yne-ring-chain",
    structure: { kind: "smiles", value: "CC#CC" },
    alt: "Skeletal structure of but-2-yne",
    label: "But-2-yne: acyclic, two degrees of unsaturation as a triple bond.",
    theme: "dark",
  }),
  cyclobutene: molecule({
    id: "cyclobutene",
    structure: { kind: "smiles", value: "C1=CCC1" },
    alt: "Skeletal structure of cyclobutene",
    label: "Cyclobutene: cyclic, two degrees of unsaturation as a ring plus a π bond.",
    theme: "dark",
  }),
  but3en1ol: molecule({
    id: "but-3-en-1-ol",
    structure: { kind: "smiles", value: "C=CCCO" },
    alt: "Skeletal structure of but-3-en-1-ol",
    label: "But-3-en-1-ol: open-chain form, one ring-equivalent degree of unsaturation as C=C.",
    theme: "dark",
  }),
  methyloxetane2: molecule({
    id: "2-methyloxetane",
    structure: { kind: "smiles", value: "CC1CCO1" },
    alt: "Skeletal structure of 2-methyloxetane",
    label: "2-Methyloxetane: cyclic ether form, same degree of unsaturation as a ring.",
    theme: "dark",
  }),
  cyclobutanol: molecule({
    id: "cyclobutanol",
    structure: { kind: "smiles", value: "OC1CCC1" },
    alt: "Skeletal structure of cyclobutanol",
    label: "Cyclobutanol: cyclic alcohol form, same degree of unsaturation as a ring.",
    theme: "dark",
  }),
  allylMercaptan: molecule({
    id: "prop-2-ene-1-thiol",
    structure: { kind: "smiles", value: "C=CCS" },
    alt: "Skeletal structure of prop-2-ene-1-thiol",
    label: "Prop-2-ene-1-thiol (allyl mercaptan): open-chain form.",
    theme: "dark",
  }),
  thietane: molecule({
    id: "thietane",
    structure: { kind: "smiles", value: "C1CSC1" },
    alt: "Skeletal ring structure of thietane",
    label: "Thietane: cyclic sulfur-containing ring form — ring-chain isomer of prop-2-ene-1-thiol.",
    theme: "dark",
  }),
  glucopyranose: molecule({
    id: "beta-d-glucopyranose",
    structure: { kind: "smiles", value: "OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O" },
    alt: "Skeletal ring structure of beta-D-glucopyranose",
    label: "β-D-Glucopyranose: cyclic hemiacetal form.",
    theme: "dark",
  }),
  methoxyethane: molecule({
    id: "methoxyethane",
    structure: { kind: "smiles", value: "CCOC" },
    alt: "Skeletal structure of methoxyethane",
    label: "Methoxyethane (methyl ethyl ether): ether functional group, C₃H₈O.",
    theme: "dark",
  }),
  methylPropanoate: molecule({
    id: "methyl-propanoate",
    structure: { kind: "smiles", value: "CCC(=O)OC" },
    alt: "Skeletal structure of methyl propanoate",
    label: "Methyl propanoate: ester functional group, same C₄H₈O₂ formula as butanoic acid.",
    theme: "dark",
  }),
  propanal: molecule({
    id: "propanal",
    structure: { kind: "smiles", value: "CCC=O" },
    alt: "Skeletal structure of propanal",
    label: "Propanal: aldehyde functional group, C₃H₆O.",
    theme: "dark",
  }),
  acetone: molecule({
    id: "acetone",
    structure: { kind: "smiles", value: "CC(=O)C" },
    alt: "Skeletal structure of acetone",
    label: "Acetone (propan-2-one): ketone functional group, same C₃H₆O formula as propanal.",
    theme: "dark",
  }),
  propanenitrile: molecule({
    id: "propanenitrile",
    structure: { kind: "smiles", value: "CCC#N" },
    alt: "Skeletal structure of propanenitrile",
    label: "Propanenitrile: R–C≡N.",
    theme: "dark",
  }),
  propylIsocyanide: molecule({
    id: "1-propyl-isocyanide",
    structure: { kind: "smiles", value: "CCC[N+]#[C-]" },
    alt: "Skeletal structure of 1-propyl isocyanide",
    label: "1-Propyl isocyanide: R–N≡C, functional isomer of propanenitrile.",
    theme: "dark",
  }),
  butan1amine: molecule({
    id: "butan-1-amine",
    structure: { kind: "smiles", value: "CCCCN" },
    alt: "Skeletal structure of butan-1-amine",
    label: "Butan-1-amine: primary (1°) amine.",
    theme: "dark",
  }),
  nMethylpropan1amine: molecule({
    id: "n-methylpropan-1-amine",
    structure: { kind: "smiles", value: "CCCNC" },
    alt: "Skeletal structure of N-methylpropan-1-amine",
    label: "N-Methylpropan-1-amine: secondary (2°) amine, same C₄H₁₁N formula.",
    theme: "dark",
  }),
  nnDimethylethanamine: molecule({
    id: "n-n-dimethylethanamine",
    structure: { kind: "smiles", value: "CCN(C)C" },
    alt: "Skeletal structure of N,N-dimethylethanamine",
    label: "N,N-Dimethylethanamine: tertiary (3°) amine, same C₄H₁₁N formula.",
    theme: "dark",
  }),
  benzylAlcohol: molecule({
    id: "benzyl-alcohol",
    structure: { kind: "smiles", value: "OCc1ccccc1" },
    alt: "Skeletal structure of benzyl alcohol",
    label: "Benzyl alcohol: aliphatic alcohol on an aromatic ring, C₇H₈O.",
    theme: "dark",
  }),
  oCresol: molecule({
    id: "o-cresol",
    structure: { kind: "smiles", value: "Cc1ccccc1O" },
    alt: "Skeletal structure of o-cresol",
    label: "o-Cresol: aromatic alcohol, same C₇H₈O formula as benzyl alcohol.",
    theme: "dark",
  }),
  anisole: molecule({
    id: "anisole",
    structure: { kind: "smiles", value: "COc1ccccc1" },
    alt: "Skeletal structure of anisole",
    label: "Anisole: ether functional group, same C₇H₈O formula.",
    theme: "dark",
  }),
  nMethylpropanamide: molecule({
    id: "n-methylpropanamide",
    structure: { kind: "smiles", value: "CCC(=O)NC" },
    alt: "Skeletal structure of N-methylpropanamide",
    label: "N-Methylpropanamide: secondary (2°) amide, same C₄H₉NO formula as butanamide.",
    theme: "dark",
  }),
  nnDimethylacetamide: molecule({
    id: "n-n-dimethylacetamide",
    structure: { kind: "smiles", value: "CC(=O)N(C)C" },
    alt: "Skeletal structure of N,N-dimethylacetamide",
    label: "N,N-Dimethylacetamide: tertiary (3°) amide, same C₄H₉NO formula.",
    theme: "dark",
  }),
  nitrobenzene: molecule({
    id: "nitrobenzene",
    structure: { kind: "smiles", value: "[O-][N+](=O)c1ccccc1" },
    alt: "Skeletal structure of nitrobenzene",
    label: "Nitrobenzene: nitro functional group.",
    theme: "dark",
  }),
  phenylNitrite: molecule({
    id: "phenyl-nitrite",
    structure: { kind: "smiles", value: "c1ccccc1ON=O" },
    alt: "Skeletal structure of phenyl nitrite",
    label: "Phenyl nitrite: nitrito functional group, same C₆H₅NO₂ formula as nitrobenzene.",
    theme: "dark",
  }),
  butanalOxime: molecule({
    id: "butanal-oxime",
    structure: { kind: "smiles", value: "CCCC=NO" },
    alt: "Skeletal structure of butanal oxime",
    label: "Butanal oxime: same C₄H₉NO formula as butanamide.",
    theme: "dark",
  }),
  allene: molecule({
    id: "propa-1,2-diene",
    structure: { kind: "smiles", value: "C=C=C" },
    alt: "Skeletal structure of allene",
    label: "Propa-1,2-diene (allene): C₃H₄.",
    theme: "dark",
  }),
  propyne: molecule({
    id: "propyne",
    structure: { kind: "smiles", value: "CC#C" },
    alt: "Skeletal structure of propyne",
    label: "Propyne: same C₃H₄ formula as allene — functional isomer.",
    theme: "dark",
  }),
  buta12diene: molecule({
    id: "buta-1,2-diene",
    structure: { kind: "smiles", value: "CC=C=C" },
    alt: "Skeletal structure of buta-1,2-diene",
    label: "Buta-1,2-diene: C₄H₆.",
    theme: "dark",
  }),
  buta13diene: molecule({
    id: "buta-1,3-diene",
    structure: { kind: "smiles", value: "C=CC=C" },
    alt: "Skeletal structure of buta-1,3-diene",
    label: "Buta-1,3-diene: C₄H₆.",
    theme: "dark",
  }),
  but1yneFunc: molecule({
    id: "but-1-yne-functional",
    structure: { kind: "smiles", value: "CCC#C" },
    alt: "Skeletal structure of but-1-yne",
    label: "But-1-yne: same C₄H₆ formula as the butadienes — functional isomer of each.",
    theme: "dark",
  }),
  but2yneFunc: molecule({
    id: "but-2-yne-functional",
    structure: { kind: "smiles", value: "CC#CC" },
    alt: "Skeletal structure of but-2-yne",
    label: "But-2-yne: same C₄H₆ formula as the butadienes — functional isomer of each.",
    theme: "dark",
  }),
  tertButylMethylEther: molecule({
    id: "tert-butyl-methyl-ether",
    structure: { kind: "smiles", value: "COC(C)(C)C" },
    alt: "Skeletal structure of tert-butyl methyl ether",
    label: "tert-Butyl methyl ether: one of the four methyl-ether-side C₅H₁₂O isomers.",
    theme: "dark",
  }),
  ethoxypropane1: molecule({
    id: "ethoxypropane-metamer-1",
    structure: { kind: "smiles", value: "CCOCCC" },
    alt: "Skeletal structure of ethoxypropane",
    label: "1-Ethoxypropane.",
    theme: "dark",
  }),
  methoxybutane: molecule({
    id: "1-methoxybutane",
    structure: { kind: "smiles", value: "COCCCC" },
    alt: "Skeletal structure of 1-methoxybutane",
    label: "1-Methoxybutane.",
    theme: "dark",
  }),
  methoxybutane2: molecule({
    id: "2-methoxybutane",
    structure: { kind: "smiles", value: "COC(C)CC" },
    alt: "Skeletal structure of 2-methoxybutane",
    label: "2-Methoxybutane.",
    theme: "dark",
  }),
  methoxyisobutane: molecule({
    id: "1-methoxy-2-methylpropane",
    structure: { kind: "smiles", value: "COCC(C)C" },
    alt: "Skeletal structure of 1-methoxy-2-methylpropane",
    label: "1-Methoxy-2-methylpropane.",
    theme: "dark",
  }),
  ethoxypropane2: molecule({
    id: "2-ethoxypropane",
    structure: { kind: "smiles", value: "CCOC(C)C" },
    alt: "Skeletal structure of 2-ethoxypropane",
    label: "2-Ethoxypropane.",
    theme: "dark",
  }),
  diethylamineMeta: molecule({
    id: "diethylamine",
    structure: { kind: "smiles", value: "CCNCC" },
    alt: "Skeletal structure of diethylamine",
    label: "Diethylamine: 2+2 alkyl distribution.",
    theme: "dark",
  }),
  dimethylSulfide: molecule({
    id: "dimethyl-sulfide",
    structure: { kind: "smiles", value: "CSC" },
    alt: "Skeletal structure of dimethyl sulfide",
    label: "Dimethyl sulfide: too few carbons for a metameric alternative.",
    theme: "dark",
  }),
  methylEthylSulfide: molecule({
    id: "methyl-ethyl-sulfide",
    structure: { kind: "smiles", value: "CSCC" },
    alt: "Skeletal structure of methyl ethyl sulfide",
    label: "Methyl ethyl sulfide: too few carbons for a metameric alternative.",
    theme: "dark",
  }),
  diethylSulfide: molecule({
    id: "diethyl-sulfide",
    structure: { kind: "smiles", value: "CCSCC" },
    alt: "Skeletal structure of diethyl sulfide",
    label: "Diethyl sulfide: 2+2 alkyl distribution.",
    theme: "dark",
  }),
  methylPropylSulfide: molecule({
    id: "methyl-propyl-sulfide",
    structure: { kind: "smiles", value: "CSCCC" },
    alt: "Skeletal structure of methyl propyl sulfide",
    label: "Methyl propyl sulfide: 1+3 alkyl distribution — metamer of diethyl sulfide.",
    theme: "dark",
  }),
  methylButanoate: molecule({
    id: "methyl-butanoate",
    structure: { kind: "smiles", value: "CCCC(=O)OC" },
    alt: "Skeletal structure of methyl butanoate",
    label: "Methyl butanoate.",
    theme: "dark",
  }),
  ethylPropanoate: molecule({
    id: "ethyl-propanoate",
    structure: { kind: "smiles", value: "CCC(=O)OCC" },
    alt: "Skeletal structure of ethyl propanoate",
    label: "Ethyl propanoate: metamer of methyl butanoate.",
    theme: "dark",
  }),
  nMethylbutanamide: molecule({
    id: "n-methylbutanamide",
    structure: { kind: "smiles", value: "CCCC(=O)NC" },
    alt: "Skeletal structure of N-methylbutanamide",
    label: "N-Methylbutanamide.",
    theme: "dark",
  }),
  nEthylpropanamide: molecule({
    id: "n-ethylpropanamide",
    structure: { kind: "smiles", value: "CCC(=O)NCC" },
    alt: "Skeletal structure of N-ethylpropanamide",
    label: "N-Ethylpropanamide: metamer of N-methylbutanamide.",
    theme: "dark",
  }),
  aceticButanoicAnhydride: molecule({
    id: "acetic-butanoic-anhydride",
    structure: { kind: "smiles", value: "CC(=O)OC(=O)CCC" },
    alt: "Skeletal structure of acetic butanoic anhydride",
    label: "Acetic butanoic anhydride.",
    theme: "dark",
  }),
  propanoicAnhydride: molecule({
    id: "propanoic-anhydride",
    structure: { kind: "smiles", value: "CCC(=O)OC(=O)CC" },
    alt: "Skeletal structure of propanoic anhydride",
    label: "Propanoic anhydride: metamer of acetic butanoic anhydride.",
    theme: "dark",
  }),
  heptan2one: molecule({
    id: "heptan-2-one",
    structure: { kind: "smiles", value: "CCCCCC(=O)C" },
    alt: "Skeletal structure of heptan-2-one",
    label: "Heptan-2-one: 1+5 alkyl distribution.",
    theme: "dark",
  }),
  heptan4one: molecule({
    id: "heptan-4-one",
    structure: { kind: "smiles", value: "CCCC(=O)CCC" },
    alt: "Skeletal structure of heptan-4-one",
    label: "Heptan-4-one: 3+3 alkyl distribution — metamer of heptan-2-one.",
    theme: "dark",
  }),
  ethylEthanesulfonate: molecule({
    id: "ethyl-ethanesulfonate",
    structure: { kind: "smiles", value: "CCS(=O)(=O)OCC" },
    alt: "Skeletal structure of ethyl ethanesulfonate",
    label: "Ethyl ethanesulfonate.",
    theme: "dark",
  }),
  methylPropanesulfonate: molecule({
    id: "methyl-propanesulfonate",
    structure: { kind: "smiles", value: "CCCS(=O)(=O)OC" },
    alt: "Skeletal structure of methyl propanesulfonate",
    label: "Methyl propanesulfonate: metamer of ethyl ethanesulfonate.",
    theme: "dark",
  }),
  cyclobutylCyclopropanesulfonate: molecule({
    id: "cyclobutyl-cyclopropanesulfonate",
    structure: { kind: "smiles", value: "O=S(=O)(C1CC1)OC1CCC1" },
    alt: "Skeletal structure of cyclobutyl cyclopropanesulfonate",
    label: "Cyclobutyl cyclopropanesulfonate.",
    theme: "dark",
  }),
  cyclopropylCyclobutanesulfonate: molecule({
    id: "cyclopropyl-cyclobutanesulfonate",
    structure: { kind: "smiles", value: "O=S(=O)(C1CCC1)OC1CC1" },
    alt: "Skeletal structure of cyclopropyl cyclobutanesulfonate",
    label: "Cyclopropyl cyclobutanesulfonate: metamer of cyclobutyl cyclopropanesulfonate.",
    theme: "dark",
  }),
  phenylCyclohexylEther: molecule({
    id: "phenyl-cyclohexyl-ether",
    structure: { kind: "smiles", value: "C1CCCCC1Oc1ccccc1" },
    alt: "Skeletal structure of phenyl cyclohexyl ether",
    label: "Phenyl cyclohexyl ether.",
    theme: "dark",
  }),
  cyclohexylBenzoate: molecule({
    id: "cyclohexyl-benzoate",
    structure: { kind: "smiles", value: "O=C(OC1CCCCC1)c1ccccc1" },
    alt: "Skeletal structure of cyclohexyl benzoate",
    label: "Cyclohexyl benzoate.",
    theme: "dark",
  }),
  phenylCyclohexanecarboxylate: molecule({
    id: "phenyl-cyclohexanecarboxylate",
    structure: { kind: "smiles", value: "O=C(Oc1ccccc1)C1CCCCC1" },
    alt: "Skeletal structure of phenyl cyclohexanecarboxylate",
    label: "Phenyl cyclohexanecarboxylate: metamer of cyclohexyl benzoate.",
    theme: "dark",
  }),
  mTolylBenzenesulfonate: molecule({
    id: "m-tolyl-benzenesulfonate",
    structure: { kind: "smiles", value: "Cc1cccc(OS(=O)(=O)c2ccccc2)c1" },
    alt: "Skeletal structure of m-tolyl benzenesulfonate",
    label: "m-Tolyl benzenesulfonate.",
    theme: "dark",
  }),
  phenylMToluenesulfonate: molecule({
    id: "phenyl-m-toluenesulfonate",
    structure: { kind: "smiles", value: "O=S(=O)(Oc1ccccc1)c1cccc(C)c1" },
    alt: "Skeletal structure of phenyl m-toluenesulfonate",
    label: "Phenyl m-toluenesulfonate: metamer of m-tolyl benzenesulfonate.",
    theme: "dark",
  }),
  nEthylpropan1amine: molecule({
    id: "n-ethylpropan-1-amine",
    structure: { kind: "smiles", value: "CCCNCC" },
    alt: "Skeletal structure of N-ethylpropan-1-amine",
    label: "N-Ethylpropan-1-amine: secondary (2°) amine.",
    theme: "dark",
  }),
  nnDimethylpropan1amine: molecule({
    id: "n-n-dimethylpropan-1-amine",
    structure: { kind: "smiles", value: "CCCN(C)C" },
    alt: "Skeletal structure of N,N-dimethylpropan-1-amine",
    label: "N,N-Dimethylpropan-1-amine: tertiary (3°) amine, same C₅H₁₃N formula.",
    theme: "dark",
  }),
  but1ene: molecule({
    id: "but-1-ene",
    structure: { kind: "smiles", value: "C=CCC" },
    alt: "Skeletal structure of but-1-ene",
    label: "But-1-ene: acyclic C₄H₈ isomer.",
    theme: "dark",
  }),
  but2ene: molecule({
    id: "but-2-ene",
    structure: { kind: "smiles", value: "CC=CC" },
    alt: "Skeletal structure of but-2-ene",
    label: "But-2-ene: acyclic C₄H₈ isomer.",
    theme: "dark",
  }),
  isobutylene: molecule({
    id: "2-methylprop-1-ene",
    structure: { kind: "smiles", value: "C=C(C)C" },
    alt: "Skeletal structure of 2-methylprop-1-ene",
    label: "2-Methylprop-1-ene (isobutylene): acyclic C₄H₈ isomer.",
    theme: "dark",
  }),
} as const satisfies MoleculeRegistry;

export type IsomerismMoleculeKey = keyof typeof ISOMERISM_MOLECULES;
