import type { MoleculeRegistry, MoleculeSpec } from "@/lib/chemistry/molecule-types";

const molecule = <T extends MoleculeSpec>(spec: T): T => spec;

export const ISOMERISM_MOLECULES = {
  nButane: molecule({
    id: "n-butane",
    structure: { kind: "smiles", value: "CCCC" },
    alt: "Skeletal structure of normal butane",
    label: "n-Butane: unbranched four-carbon skeleton, C₄H₁₀.",
    theme: "dark",
  }),
  isobutane: molecule({
    id: "isobutane",
    structure: { kind: "smiles", value: "CC(C)C" },
    alt: "Skeletal structure of 2-methylpropane, also called isobutane",
    label:
      "2-Methylpropane: branched four-carbon skeleton, C₄H₁₀. Connectivity differs from n-butane.",
    theme: "dark",
  }),
  propan1ol: molecule({
    id: "propan-1-ol",
    structure: { kind: "smiles", value: "CCCO" },
    alt: "Skeletal structure of propan-1-ol",
    label: "Propan-1-ol: hydroxyl group on terminal carbon.",
    theme: "dark",
  }),
  propan2ol: molecule({
    id: "propan-2-ol",
    structure: { kind: "smiles", value: "CC(O)C" },
    alt: "Skeletal structure of propan-2-ol",
    label:
      "Propan-2-ol: hydroxyl group on middle carbon. Same three-carbon skeleton and formula C₃H₈O.",
    theme: "dark",
  }),
  propene: molecule({
    id: "propene",
    structure: { kind: "smiles", value: "CC=C" },
    alt: "Skeletal structure of propene",
    label: "Propene: acyclic C₃H₆ with one carbon–carbon double bond.",
    theme: "dark",
  }),
  cyclopropane: molecule({
    id: "cyclopropane",
    structure: { kind: "smiles", value: "C1CC1" },
    alt: "Skeletal ring structure of cyclopropane",
    label: "Cyclopropane: cyclic C₃H₆ with a three-membered ring.",
    theme: "dark",
  }),
  ethanol: molecule({
    id: "ethanol",
    structure: { kind: "smiles", value: "CCO" },
    alt: "Skeletal structure of ethanol",
    label: "Ethanol: alcohol connectivity, C₂H₆O.",
    theme: "dark",
  }),
  dimethylEther: molecule({
    id: "dimethyl-ether",
    structure: { kind: "smiles", value: "COC" },
    alt: "Skeletal structure of dimethyl ether",
    label: "Dimethyl ether: ether connectivity, C₂H₆O.",
    theme: "dark",
  }),
  nPentane: molecule({
    id: "n-pentane",
    structure: { kind: "smiles", value: "CCCCC" },
    alt: "Skeletal structure of normal pentane",
    label: "n-Pentane",
    theme: "dark",
  }),
  isopentane: molecule({
    id: "isopentane",
    structure: { kind: "smiles", value: "CCC(C)C" },
    alt: "Skeletal structure of 2-methylbutane",
    label: "2-Methylbutane",
    theme: "dark",
  }),
  neopentane: molecule({
    id: "neopentane",
    structure: { kind: "smiles", value: "CC(C)(C)C" },
    alt: "Skeletal structure of 2,2-dimethylpropane",
    label: "2,2-Dimethylpropane",
    theme: "dark",
  }),
  ethoxyethane: molecule({
    id: "ethoxyethane",
    structure: { kind: "smiles", value: "CCOCC" },
    alt: "Skeletal structure of ethoxyethane",
    label: "Ethoxyethane",
    theme: "dark",
  }),
  methoxypropane: molecule({
    id: "methoxypropane",
    structure: { kind: "smiles", value: "COCCC" },
    alt: "Skeletal structure of 1-methoxypropane",
    label: "1-Methoxypropane",
    theme: "dark",
  }),
  butanal: molecule({
    id: "butanal",
    structure: { kind: "smiles", value: "CCCC=O" },
    alt: "Skeletal structure of butanal",
    label: "Butanal",
    theme: "dark",
  }),
  butan2one: molecule({
    id: "butan-2-one",
    structure: { kind: "smiles", value: "CC(=O)CC" },
    alt: "Skeletal structure of butan-2-one",
    label: "Butan-2-one",
    theme: "dark",
  }),
  but1en2ol: molecule({
    id: "but-1-en-2-ol",
    structure: { kind: "smiles", value: "C=C(O)CC" },
    alt: "Skeletal structure of but-1-en-2-ol",
    label: "But-1-en-2-ol",
    theme: "dark",
  }),
  propanoicAcid: molecule({
    id: "propanoic-acid",
    structure: { kind: "smiles", value: "CCC(=O)O" },
    alt: "Skeletal structure of propanoic acid",
    label: "Propanoic acid",
    theme: "dark",
  }),
  methylEthanoate: molecule({
    id: "methyl-ethanoate",
    structure: { kind: "smiles", value: "CC(=O)OC" },
    alt: "Skeletal structure of methyl ethanoate",
    label: "Methyl ethanoate",
    theme: "dark",
  }),
  cis2Butene: molecule({
    id: "cis-2-butene",
    structure: { kind: "smiles", value: "C/C=C\\C" },
    alt: "Stereochemical structure of cis-2-butene",
    label: "Z (cis): priority-1 groups are on the same side.",
    showStereoAnnotation: true,
    theme: "dark",
  }),
  trans2Butene: molecule({
    id: "trans-2-butene",
    structure: { kind: "smiles", value: "C/C=C/C" },
    alt: "Stereochemical structure of trans-2-butene",
    label: "E (trans): priority-1 groups are on opposite sides.",
    showStereoAnnotation: true,
    theme: "dark",
  }),
  acetylacetoneKeto: molecule({
    id: "acetylacetone-keto",
    structure: { kind: "smiles", value: "CC(=O)CC(=O)C" },
    alt: "Diketo form of acetylacetone",
    label: "Diketo form",
    theme: "dark",
  }),
  acetylacetoneEnol: molecule({
    id: "acetylacetone-enol",
    structure: { kind: "smiles", value: "CC(O)=CC(=O)C" },
    alt: "Chelated enol form of acetylacetone",
    label: "Chelated enol form",
    theme: "dark",
  }),
  lacticAcidStereoA: molecule({
    id: "lactic-acid-stereoisomer-a",
    structure: { kind: "smiles", value: "C[C@H](O)C(=O)O" },
    alt: "One stereoisomer of lactic acid",
    label: "Lactic acid stereoisomer",
    theme: "dark",
  }),
  lacticAcidStereoB: molecule({
    id: "lactic-acid-stereoisomer-b",
    structure: { kind: "smiles", value: "C[C@@H](O)C(=O)O" },
    alt: "Mirror-image stereoisomer of lactic acid",
    label: "Mirror stereoisomer",
    theme: "dark",
  }),
  benzene: molecule({
    id: "benzene",
    structure: { kind: "smiles", value: "c1ccccc1" },
    alt: "Aromatic skeletal structure of benzene",
    label: "Benzene",
    theme: "dark",
  }),
  methylcyclohexane: molecule({
    id: "methylcyclohexane",
    structure: { kind: "smiles", value: "CC1CCCCC1" },
    alt: "Skeletal structure of methylcyclohexane",
    label: "Methylcyclohexane",
    theme: "dark",
  }),
} as const satisfies MoleculeRegistry;

export type IsomerismMoleculeKey = keyof typeof ISOMERISM_MOLECULES;
