"use client";

import EnvironmentalChemistryPart, { type PartData } from "./EnvironmentalChemistryPart";

const statementOptions = [
  "Both statements are correct.",
  "Only statement I is correct.",
  "Only statement II is correct.",
  "Both statements are incorrect.",
];

export const part13Data: PartData = {
  part: 13,
  title: "Supplied JEE Main PYQs 1–24",
  subtitle: "A source-faithful concept reconstruction of the first 24 supplied questions, with independently written reasoning, equation checks and warnings wherever the source key or wording is chemically imperfect.",
  goals: [
    "Convert every supplied question into a retrievable chemical principle.",
    "Separate textbook convention from broader scientific qualification.",
    "Use equations to reject distractors rather than relying on memory alone.",
    "Recognise common statement-pair and match-list patterns.",
    "Retain the supplied answer while explicitly marking defective wording.",
    "Build a compact error log for final revision.",
  ],
  sourceNote: "Question coverage: Environmental Chemistry – JEE Mains PYQ 2020–2022, PDF pages 1–48 (question/solution pairs for supplied questions 1–24). Wording is compactly reconstructed and every explanation is original. The source's keyed answer is retained; any chemistry caveat is stated rather than silently corrected.",
  sections: [
    {
      eyebrow: "Method",
      title: "How to use a PYQ as a diagnostic instrument",
      paragraphs: [
        "Attempt each question without opening the solution. For a factual option, write the governing fact in a few words. For a reaction option, balance atoms and charge. For statement questions, judge each statement independently before mapping the truth pair to an option.",
        "After revealing the answer, classify the error: missing fact, confused definition, mechanism error, numerical slip or overthinking beyond the prescribed text. Reattempt only the missed class after one day and again after one week.",
      ],
      flow: [
        "Identify tested chapter node",
        "Recall definition or equation",
        "Judge each option independently",
        "Check units and qualifiers",
        "Record the exact trap",
      ],
    },
    {
      eyebrow: "High-frequency facts",
      title: "The minimum network behind questions 1–24",
      table: {
        headers: ["Node", "Fast recall"],
        rows: [
          ["Greenhouse gases", "CO₂, H₂O vapour, CH₄, N₂O, O₃ and CFCs absorb terrestrial infrared; N₂ and O₂ are not important greenhouse gases"],
          ["BOD", "Oxygen required by aerobic microorganisms to oxidise biodegradable organic matter under specified conditions"],
          ["Acid rain", "SO₂/SO₃ and NOₓ oxidation gives H₂SO₄/HNO₃; pH below about 5.6 in the textbook convention"],
          ["Smog", "Classical/reducing: SO₂ + smoke + fog; photochemical/oxidising: NOₓ + VOC + sunlight → O₃, PAN, aldehydes"],
          ["Ozone", "Tropospheric O₃ is harmful; stratospheric O₃ is protective; Cl· converts O₃ to O₂ through ClO·"],
          ["Water quality", "Higher biodegradable load → higher BOD and generally lower DO; clean water has low BOD"],
          ["Green chemistry", "Liquid CO₂ dry cleaning is the prescribed replacement example"],
        ],
      },
    },
    {
      eyebrow: "Source criticism",
      title: "Two source items require a scientific footnote",
      paragraphs: [
        "Supplied question 8 keys an option that combines methane's greenhouse role with a cancer claim. Methane is a potent greenhouse gas and an asphyxiant at high concentration, but it is not generally classified as a human carcinogen. The item likely conflates methane with carcinogenic components of polluted hydrocarbon mixtures.",
        "When a supplied key contains such a defect, a trustworthy note set should preserve the historical key for source traceability and label the scientific problem. This prevents the learner from memorising an error as general chemistry.",
      ],
      boxes: [
        {
          title: "Exam-safe rule",
          body: "Use the stated syllabus model when the question is clearly textbook-bound, but never convert a defective statement into an unqualified scientific fact.",
          tone: "warning",
        },
      ],
    },
  ],
  questions: [
    {
      number: "PYQ 1",
      tag: "Greenhouse gases",
      question: "Which set contains only greenhouse gases?",
      options: ["CO₂, N₂, O₂ and Ne", "H₂O, O₂, N₂ and H₂", "CO₂, CO, NO and He", "CO₂, H₂O vapour, CFCs and O₃"],
      answer: "D",
      solution: "CO₂, water vapour, ozone and CFCs absorb outgoing terrestrial infrared radiation. Homonuclear N₂ and O₂ are not important greenhouse absorbers.",
    },
    {
      number: "PYQ 2",
      tag: "BOD",
      question: "Biochemical oxygen demand is associated most directly with:",
      options: ["Bacteria breaking down organic waste in water", "Evaporation of pure water", "Precipitation of NaCl", "Photolysis of stratospheric oxygen"],
      answer: "A",
      solution: "BOD measures the oxygen consumed by aerobic microorganisms while oxidising biodegradable organic matter under specified test conditions.",
    },
    {
      number: "PYQ 3",
      tag: "Ozone depletion",
      question: "Which statement about ozone-layer chemistry is false?",
      options: ["UV radiation can release Cl· from CFCs", "Cl· reacts with O₃ to form ClO· and O₂", "Cl· reacts with O₃ to form chlorine dioxide radical, ClO₂·, as the standard catalytic step", "Cl· can be regenerated and destroy additional ozone"],
      answer: "C",
      solution: "The elementary propagation step is Cl· + O₃ → ClO· + O₂, not formation of ClO₂·. ClO· then helps regenerate Cl·.",
    },
    {
      number: "PYQ 4",
      tag: "Acid rain",
      question: "A major environmental consequence associated with coal-based thermal power plants is:",
      options: ["Only ozone formation in the stratosphere", "Only fluoride deficiency", "Elimination of particulate matter", "Acid rain from sulfur and nitrogen oxides"],
      answer: "D",
      solution: "Combustion releases SO₂ and NOₓ. Atmospheric oxidation and hydration form strong acids that contribute to acid deposition.",
    },
    {
      number: "PYQ 5",
      tag: "Metallurgy and emissions",
      question: "Calcination of carbonate ores and roasting of sulfide ores contribute respectively, most directly, to:",
      options: ["Ozone depletion and eutrophication", "Acid rain and greenhouse effect", "Photochemical smog and fluoride mottling", "Greenhouse effect and acid rain"],
      answer: "D",
      solution: "Calcination releases CO₂, while roasting a sulfide can release SO₂. CO₂ contributes to warming and SO₂ to acid rain.",
    },
    {
      number: "PYQ 6",
      tag: "Eutrophication",
      question: "Excessive nutrient enrichment followed by dense algal growth and oxygen depletion is called:",
      options: ["Desalination", "Calcination", "Biomagnification", "Eutrophication"],
      answer: "D",
      solution: "Nitrate and phosphate enrichment stimulates biomass. Decomposition then raises oxygen demand and may create hypoxia.",
    },
    {
      number: "PYQ 7",
      tag: "Fluoride",
      question: "Which statement best matches the prescribed drinking-water description of fluoride?",
      options: ["It is always toxic at any concentration", "It has no relation to teeth", "Around 1 ppm can be beneficial for teeth, whereas excess causes fluorosis", "Only concentrations above 100 ppm are relevant"],
      answer: "C",
      solution: "Low fluoride near the stated optimum supports enamel resistance; excessive long-term intake causes dental and skeletal fluorosis. Use the exact value specified by the question or syllabus source.",
    },
    {
      number: "PYQ 8",
      tag: "Source caveat",
      question: "Anaerobic decomposition of vegetation in waterlogged regions such as paddy fields releases which major gas?",
      options: ["CH₄", "O₂", "Cl₂", "SO₃"],
      answer: "A (source option attached an invalid cancer claim)",
      solution: "Methanogenic microorganisms generate CH₄, which is an important greenhouse gas. The supplied option/key also associated methane with cancer; that extra claim is not generally scientifically valid and should not be memorised.",
    },
    {
      number: "PYQ 9",
      tag: "Statement pair",
      question: "I. BOD is an important water-quality parameter. II. The optimum pH of ordinary drinking water is exactly 6.5 under every standard.",
      options: statementOptions,
      answer: "B — only statement I is correct",
      solution: "BOD indicates biodegradable organic load. Drinking-water pH is normally specified as an acceptable range rather than one universally exact optimum value.",
    },
    {
      number: "PYQ 10",
      tag: "Smog statements",
      question: "I. An allotrope of oxygen is a characteristic intermediate/product of reducing smog. II. Tropospheric NOₓ and sulfur compounds together define photochemical smog.",
      options: statementOptions,
      answer: "D — both statements are incorrect",
      solution: "Ozone belongs to oxidising photochemical smog, whereas classical reducing smog is dominated by smoke, fog and sulfur dioxide. Photochemical smog is chiefly the sunlight-driven NOₓ–VOC system; sulfur pollution points toward classical smog/acid deposition.",
    },
    {
      number: "PYQ 11",
      tag: "Water chemistry",
      question: "Which reaction is not a normal process involving atmospheric CO₂ dissolved in water?",
      options: ["CO₂ + H₂O ⇌ H₂CO₃", "H₂CO₃ ⇌ H⁺ + HCO₃⁻", "HCO₃⁻ ⇌ H⁺ + CO₃²⁻", "CO₂ + H₂O → CO + H₂O₂ under ordinary environmental conditions"],
      answer: "D",
      solution: "CO₂ participates in carbonate equilibria. Ordinary dissolution in water does not reduce CO₂ to CO.",
    },
    {
      number: "PYQ 12",
      tag: "Acid rain",
      question: "I. Normal rain is mildly acidic because dissolved CO₂ forms carbonic acid. II. Rain with pH below about 5.6 is conventionally called acid rain in the prescribed text.",
      options: statementOptions,
      answer: "A — both statements are correct",
      solution: "Carbonate equilibrium makes unpolluted rain mildly acidic. Additional strong acids derived mainly from SOₓ and NOₓ lower pH further.",
    },
    {
      number: "PYQ 13",
      tag: "Tropospheric ozone",
      question: "Ozone in the troposphere is best described as:",
      options: ["A harmless nutrient", "The only component of reducing smog", "A groundwater disinfectant only", "A secondary oxidant and component of photochemical smog"],
      answer: "D",
      solution: "NO₂ photolysis followed by O + O₂ produces O₃. Near the surface it damages lungs, crops and materials.",
    },
    {
      number: "PYQ 14",
      tag: "Smog identification",
      question: "A smog episode becomes more intense during sunny daytime and contains appreciable ozone. It is:",
      options: ["Reducing sulfurous smog", "Photochemical oxidising smog", "Only natural fog", "Stratospheric ozone hole"],
      answer: "B",
      solution: "Sunlight drives radical chemistry involving NOₓ and hydrocarbons, producing O₃, PAN and aldehydes. These are oxidising components.",
    },
    {
      number: "PYQ 15",
      tag: "Reducing smog",
      question: "Which species is characteristically associated with reducing or classical smog?",
      options: ["Acrolein", "O₃", "SO₂", "PAN"],
      answer: "C",
      solution: "Classical smog forms in cool humid conditions from smoke, fog and sulfur dioxide. The other listed oxidants/organics are associated more with photochemical smog.",
    },
    {
      number: "PYQ 16",
      tag: "Eutrophication",
      question: "Which explanation of eutrophication is incorrect?",
      options: ["Nutrient input can stimulate algal growth", "Decomposition can consume dissolved oxygen", "Fish may die under hypoxia", "It results because the water lacks nutrients and therefore cannot support algae"],
      answer: "D",
      solution: "Eutrophication is excessive nutrient enrichment, not nutrient deficiency. Its later oxygen crisis follows high productivity and decomposition.",
    },
    {
      number: "PYQ 17",
      tag: "Methane",
      question: "Select the correct statements: I. Methane contributes to global warming. II. Waterlogged paddy fields can emit methane. III. Methane has a stronger per-molecule warming effect than CO₂ over common assessment horizons. IV. Methane is the defining pollutant of classical reducing smog.",
      answer: "I, II and III",
      solution: "Anaerobic methanogenesis explains paddy emissions. Methane is a strong greenhouse gas, but classical smog is characterised mainly by SO₂, smoke and fog.",
    },
    {
      number: "PYQ 18",
      tag: "Statement pair",
      question: "I. Thermal power generation produces non-biodegradable fly ash. II. Even biodegradable detergent-derived nutrient loading can promote eutrophication.",
      options: statementOptions,
      answer: "A — both statements are correct",
      solution: "Fly ash is mineral residue. Biodegradability does not prevent a substance or its phosphate/nutrient load from stimulating eutrophication.",
    },
    {
      number: "PYQ 19",
      tag: "Green chemistry",
      question: "The prescribed greener medium for dry cleaning is:",
      options: ["Liquid ammonia", "Benzene", "Carbon tetrachloride", "Liquid CO₂ with suitable detergent"],
      answer: "D",
      solution: "Compressed liquid CO₂ can replace a chlorinated dry-cleaning solvent and is separated by depressurisation.",
    },
    {
      number: "PYQ 20",
      tag: "Eutrophication",
      question: "Which statement is not correct for eutrophication?",
      options: ["Nutrient enrichment occurs", "Algal blooms may form", "Dissolved oxygen necessarily increases during decomposition", "Aquatic biodiversity may decline"],
      answer: "C",
      solution: "Microbial decomposition consumes oxygen, so DO commonly decreases while BOD rises.",
    },
    {
      number: "PYQ 21",
      tag: "Assertion–reason",
      question: "Assertion: Rubber can crack during photochemical-smog exposure. Reason: Oxidising components such as ozone attack unsaturated bonds in rubber.",
      options: ["Both true; reason explains assertion", "Both true; no explanation", "Assertion true; reason false", "Assertion false; reason true"],
      answer: "A",
      solution: "Ozone reacts at C=C sites, cleaving or weakening polymer chains and producing characteristic cracking.",
    },
    {
      number: "PYQ 22",
      tag: "Ozone formation",
      question: "Formation of stratospheric ozone begins with:",
      options: ["Thermal decomposition of N₂", "Hydrolysis of CFCs", "UV photodissociation of O₂", "Combustion of methane"],
      answer: "C",
      solution: "O₂ + hν → 2O; then O + O₂ + M → O₃ + M. The third body removes excess energy.",
    },
    {
      number: "PYQ 23",
      tag: "BOD values",
      question: "Which comparison follows the prescribed BOD classification?",
      options: ["Clean water >17 ppm; polluted water <5 ppm", "Both exactly zero", "Clean water <5 ppm; highly polluted water >17 ppm", "BOD is unrelated to pollution"],
      answer: "C",
      solution: "Higher biodegradable load demands more oxygen. The supplied material uses below 5 ppm for clean and above 17 ppm for highly polluted water.",
    },
    {
      number: "PYQ 24",
      tag: "Acid deposition",
      question: "Match the deposition form: X = wet deposition carried in rain/fog; Y = dry deposition of acidic gas/particles. Which pair is representative?",
      options: ["X: O₂; Y: N₂", "X: NaCl only; Y: water vapour", "X: dissolved ammonium/acidic salts; Y: SO₂ and acidic particles", "X: methane; Y: glucose"],
      answer: "C",
      solution: "Wet deposition transports dissolved ions and acids in precipitation. Dry deposition transfers gases such as SO₂ and acidic particles directly to surfaces.",
    },
  ],
  recap: [
    "Greenhouse gases absorb terrestrial infrared; do not include N₂ and O₂ merely because they are abundant.",
    "BOD rises with biodegradable organic load; DO generally falls as aerobic decomposition proceeds.",
    "Cl· + O₃ forms ClO·, not ClO₂·, in the standard ozone-depletion cycle.",
    "Classical smog is sulfurous and reducing; photochemical smog is NOₓ–VOC–sunlight driven and oxidising.",
    "Tropospheric ozone is a pollutant; stratospheric ozone is a shield.",
    "Calcination of carbonate releases CO₂; roasting of sulfide releases SO₂.",
    "Retain the source trace for PYQ 8, but do not memorise methane as a human carcinogen.",
    "The prescribed thresholds are exam conventions; use the value supplied in the question.",
  ],
};

export default function Part13() {
  return <EnvironmentalChemistryPart data={part13Data} />;
}
