"use client";

import EnvironmentalChemistryPart, { type PartData } from "./EnvironmentalChemistryPart";

export const part14Data: PartData = {
  part: 14,
  title: "Supplied JEE Main PYQs 25–48",
  subtitle: "The remaining 24 supplied questions, rebuilt as an exam workshop with traceable source answers, complete match logic and scientifically qualified textbook conventions.",
  goals: [
    "Finish all 48 supplied PYQs without skipping match-list or statement items.",
    "Link BOD numbers to the underlying oxygen-demand concept.",
    "Master polar-stratospheric-cloud reactions and chlorine activation.",
    "Recall pollutant–source and pollutant–effect mappings.",
    "Use chemical equations to solve acid-rain and ozone questions.",
    "Mark narrow textbook classification where broader terminology differs.",
  ],
  sourceNote: "Question coverage: Environmental Chemistry – JEE Mains PYQ 2020–2022, PDF pages 49–100 (question/solution pairs for supplied questions 25–48); page 101 is blank. Explanations are independently written. Source spelling and formula slips are normalised while answer traceability is preserved.",
  sections: [
    {
      eyebrow: "Cluster map",
      title: "What the second half repeatedly tests",
      table: {
        headers: ["Questions", "Dominant concept", "Fast discriminator"],
        rows: [
          ["25, 29, 31, 44", "BOD, DO and eutrophication", "Polluted organic water: BOD high, DO low"],
          ["26, 48", "Greenhouse gases", "CO₂, H₂O and CH₄ yes; O₂/N₂ no"],
          ["27, 39, 42", "Water ions and health", "Dose matters; map sulfate, nitrate, lead and fluoride"],
          ["30, 32, 40", "Polar ozone depletion", "PSC surfaces activate reservoir chlorine; sunlight releases radicals"],
          ["33, 35, 38", "Smog", "Photochemical: warm/sunny, NOₓ + VOC, oxidising"],
          ["34, 45", "Pesticide/herbicide examples", "Separate textbook labels from umbrella terminology"],
          ["36, 37, 46", "Acid rain", "SO₂ oxidation + water; stone, pipes, plants and respiration affected"],
          ["41, 43, 47", "Matching and waste", "Build one certain pair first, then eliminate"],
        ],
      },
    },
    {
      eyebrow: "Mechanism bridge",
      title: "Polar stratospheric clouds convert reservoir chlorine",
      paragraphs: [
        "In the polar night, very low temperature permits polar stratospheric cloud particles. Their surfaces enable heterogeneous reactions that convert relatively unreactive reservoir species such as HCl and ClONO₂ into photolabile chlorine compounds.",
        "Hydrolysis of chlorine nitrate produces hypochlorous acid and nitric acid. Reaction of chlorine nitrate with hydrogen chloride produces molecular chlorine and nitric acid. When sunlight returns, Cl₂ and HOCl photolyse or enter sequences that release chlorine radicals, causing rapid ozone loss.",
      ],
      equations: [
        "ClONO₂ + H₂O → HOCl + HNO₃",
        "ClONO₂ + HCl → Cl₂ + HNO₃",
        "Cl₂ + hν → 2Cl·",
        "Cl· + CH₄ → HCl + CH₃·",
      ],
      boxes: [
        {
          title: "Reservoir versus active",
          body: "HCl and ClONO₂ store chlorine relatively quietly; PSC chemistry creates HOCl/Cl₂, and returning sunlight releases active radical chlorine.",
          tone: "jee",
        },
      ],
    },
    {
      eyebrow: "Convention warning",
      title: "Herbicides belong to the broad pesticide family",
      paragraphs: [
        "The supplied question 34 keys sodium arsenite as “not a pesticide,” following a narrow textbook contrast between named insecticides and herbicides. In modern umbrella usage, pesticides include substances used against pests such as weeds; herbicides are therefore a pesticide class.",
        "For source traceability the keyed answer is retained below, but the broader definition is explicitly stated. Question 45 separately uses sodium chlorate and sodium arsenite as prescribed herbicide examples.",
      ],
      boxes: [
        {
          title: "Do not propagate the ambiguity",
          body: "Write “source-keyed under a narrow classification” instead of claiming universally that sodium arsenite is not a pesticide.",
          tone: "warning",
        },
      ],
    },
  ],
  questions: [
    {
      number: "PYQ 25",
      tag: "BOD",
      question: "Which water sample is the cleanest on the basis of BOD?",
      options: ["11 ppm", "15 ppm", "3 ppm", "21 ppm"],
      answer: "C",
      solution: "Lower BOD means less biodegradable organic load. The supplied classification treats BOD below 5 ppm as clean, making 3 ppm the best value.",
    },
    {
      number: "PYQ 26",
      tag: "Greenhouse gases",
      question: "Which gaseous species does not produce the greenhouse effect to an important extent?",
      options: ["CH₄", "O₃", "H₂O vapour", "N₂"],
      answer: "D",
      solution: "Methane, ozone and water vapour absorb terrestrial infrared. Symmetric homonuclear N₂ lacks the relevant changing dipole vibration.",
    },
    {
      number: "PYQ 27",
      tag: "Tooth enamel",
      question: "Which elemental/ionic form is not present in tooth enamel?",
      options: ["Ca²⁺", "P³⁺", "F⁻", "P⁵⁺"],
      answer: "B",
      solution: "Enamel mineral is hydroxyapatite/fluorapatite-type calcium phosphate. Phosphorus in phosphate is +5, not +3; Ca²⁺ and fluoride may be present.",
    },
    {
      number: "PYQ 28",
      tag: "Eutrophication",
      question: "Eutrophication of a water body commonly results in:",
      options: ["Loss of biodiversity", "Only harmless breakdown of matter", "Increase in biodiversity under all conditions", "Decrease in BOD"],
      answer: "A",
      solution: "Nutrient enrichment can progress to blooms, decomposition, hypoxia and loss of oxygen-sensitive species.",
    },
    {
      number: "PYQ 29",
      tag: "Assertion–reason",
      question: "Assertion: Highly polluted water may have BOD around 17 ppm or more. Reason: BOD measures oxygen needed to oxidise both biodegradable and non-biodegradable organic material.",
      options: ["Both true; reason explains assertion", "Both true; no explanation", "Assertion true; reason false", "Assertion false; reason true"],
      answer: "C",
      solution: "The assertion follows the supplied threshold. BOD specifically reflects biologically oxidisable material under the test; persistent non-biodegradable matter is not counted simply by being organic.",
    },
    {
      number: "PYQ 30",
      tag: "Polar ozone",
      question: "Polar stratospheric clouds facilitate formation of:",
      options: ["ClONO₂ only", "HOCl", "CH₄", "NH₃"],
      answer: "B",
      solution: "Heterogeneous hydrolysis on PSC particles gives HOCl: ClONO₂ + H₂O → HOCl + HNO₃.",
    },
    {
      number: "PYQ 31",
      tag: "BOD classification",
      question: "Four samples have BOD A = 3, B = 18, C = 21 and D = 4 ppm. Which are highly polluted with organic waste under the supplied classification?",
      options: ["A and B", "A and D", "B and C", "B and D"],
      answer: "C",
      solution: "The source uses at least about 17 ppm as highly polluted. Samples B and C exceed that level.",
    },
    {
      number: "PYQ 32",
      tag: "PSC reactions",
      question: "ClONO₂ hydrolysis gives A and B, while reaction with HCl gives B and C. Identify A, B and C.",
      options: ["HOCl, HNO₃, Cl₂", "Cl₂, HNO₃, HOCl", "HClO₂, HNO₂, HOCl", "HOCl, HNO₂, Cl₂O"],
      answer: "A",
      solution: "ClONO₂ + H₂O → HOCl + HNO₃ and ClONO₂ + HCl → HNO₃ + Cl₂. Therefore A = HOCl, B = HNO₃ and C = Cl₂.",
    },
    {
      number: "PYQ 33",
      tag: "Smog statements",
      question: "I. Classical smog occurs in cool humid conditions and is a reducing mixture of smoke, fog and SO₂. II. Photochemical smog contains species such as O₃, NOₓ, acrolein, formaldehyde and PAN.",
      options: ["Both statements are correct", "Both are incorrect", "Only I is correct", "Only II is correct"],
      answer: "A",
      solution: "The two statements correctly contrast sulfurous classical smog with sunlight-driven oxidising photochemical smog.",
    },
    {
      number: "PYQ 34",
      tag: "Source classification caveat",
      question: "Under the narrow classification used by the supplied source, which is keyed as not a pesticide?",
      options: ["DDT", "Organophosphates", "Dieldrin", "Sodium arsenite"],
      answer: "D (source-keyed; terminology caveat applies)",
      solution: "The source separates sodium arsenite as a herbicide. In broad modern usage, herbicides are pesticides because weeds are target pests; therefore the wording is taxonomically ambiguous.",
    },
    {
      number: "PYQ 35",
      tag: "Photochemical smog",
      question: "Which statement about photochemical smog is correct?",
      options: ["It requires a cool humid climate", "It is smoke + fog + SO₂", "It is reducing", "It results from sunlight-driven reactions involving unsaturated hydrocarbons and NOₓ"],
      answer: "D",
      solution: "Warm sunny conditions drive radical oxidation of VOCs in the presence of NOₓ, forming ozone and secondary oxidants.",
    },
    {
      number: "PYQ 36",
      tag: "Acid rain and marble",
      question: "Which acid is believed to be mainly responsible, in the prescribed example, for acid-deposition damage to the Taj Mahal?",
      options: ["H₂SO₄", "HF", "H₃PO₄", "HCl"],
      answer: "A",
      solution: "Sulfur dioxide oxidation produces sulfuric acid, which attacks CaCO₃ in marble and forms sulfate-containing material.",
    },
    {
      number: "PYQ 37",
      tag: "Balanced equation",
      question: "Which is the correct overall reaction representing sulfuric-acid formation from SO₂ in acid rain?",
      options: ["2SO₂ + O₂ → 2SO₃", "SO₂ + O₃ → SO₃ + O₂", "SO₂ + H₂O₂ → H₂SO₄", "2SO₂ + O₂ + 2H₂O → 2H₂SO₄"],
      answer: "D",
      solution: "Options A–C are possible oxidation steps or pathways, but D is the balanced complete overall conversion including water to sulfuric acid.",
    },
    {
      number: "PYQ 38",
      tag: "Smog composition",
      question: "Photochemical smog does not generally contain which species as a characteristic component?",
      options: ["NO", "NO₂", "SO₂", "HCHO"],
      answer: "C",
      solution: "NO, NO₂ and formaldehyde participate in or result from photochemical smog. SO₂ is associated more strongly with classical sulfurous smog and acid deposition.",
    },
    {
      number: "PYQ 39",
      tag: "Match list",
      question: "Match: A sulfate; B fluoride; C nicotine; D sodium arsenite with I pesticide; II bending of bones; III laxative effect; IV herbicide.",
      options: ["A-II, B-III, C-IV, D-I", "A-IV, B-III, C-II, D-I", "A-III, B-II, C-I, D-IV", "A-III, B-II, C-IV, D-I"],
      answer: "C",
      solution: "Excess sulfate can cause laxative effects; excess fluoride skeletal fluorosis/bending; nicotine has pesticidal use; sodium arsenite is listed as a herbicide.",
    },
    {
      number: "PYQ 40",
      tag: "Radical reaction",
      question: "In the atmospheric step Cl· + CH₄ → A + B, A and B are:",
      options: ["C₂H₆ and Cl₂", "CH₃Cl and H₂", "CH₃· and HCl", "C₂H₆ and HCl"],
      answer: "C",
      solution: "Chlorine radical abstracts hydrogen from methane, forming HCl and the methyl radical: Cl· + CH₄ → HCl + CH₃·.",
    },
    {
      number: "PYQ 41",
      tag: "Pollutant–source match",
      question: "Match A microorganisms, B plant nutrients, C toxic heavy metals and D sediment with I strip mining, II domestic sewage, III chemical fertiliser and IV chemical factory.",
      options: ["A-II, B-III, C-IV, D-I", "A-II, B-I, C-IV, D-III", "A-I, B-IV, C-II, D-III", "A-I, B-IV, C-III, D-II"],
      answer: "A",
      solution: "Sewage supplies pathogens, fertiliser supplies nutrients, chemical industry may supply toxic metals and exposed land from strip mining supplies sediment.",
    },
    {
      number: "PYQ 42",
      tag: "Pollutant–effect match",
      question: "Match A sulfate >500 ppm, B nitrate >50 ppm, C lead >50 ppb and D fluoride >2 ppm with I methemoglobinemia, II brown mottling, III laxative effect and IV kidney damage.",
      options: ["A-IV, B-I, C-II, D-III", "A-III, B-I, C-IV, D-II", "A-II, B-IV, C-I, D-III", "A-II, B-IV, C-III, D-I"],
      answer: "B",
      solution: "Sulfate → laxative effect; nitrate → methemoglobinemia; lead → kidney/neurological injury; fluoride → dental mottling at excess exposure.",
    },
    {
      number: "PYQ 43",
      tag: "Waste statements",
      question: "I. Fly ash and steel slag can be used by the cement industry subject to suitability. II. The prescribed fuel obtained from plastic waste is described as lead-free.",
      options: ["Both statements are correct", "Both are incorrect", "Only I is correct", "Only II is correct"],
      answer: "A",
      solution: "Both are statements from the prescribed source. Real applications still require composition, emission and leaching controls.",
    },
    {
      number: "PYQ 44",
      tag: "DO versus BOD",
      question: "I. In polluted water both dissolved oxygen and BOD are very low. II. Eutrophication can decrease dissolved oxygen.",
      options: ["Both true", "Both false", "Only I true", "Only II true"],
      answer: "D",
      solution: "Organic pollution generally gives low DO but high BOD, so I is false. Decomposition of eutrophic biomass consumes oxygen, so II is true.",
    },
    {
      number: "PYQ 45",
      tag: "Herbicides",
      question: "Which pair contains only herbicides in the prescribed examples?",
      options: ["Aldrin and dieldrin", "Sodium chlorate and aldrin", "Sodium arsenite and dieldrin", "Sodium chlorate and sodium arsenite"],
      answer: "D",
      solution: "The source lists NaClO₃ and sodium arsenite, Na₃AsO₃, as inorganic herbicides; aldrin and dieldrin are organochlorine insecticide examples.",
    },
    {
      number: "PYQ 46",
      tag: "Acid-rain effects",
      question: "Identify the incorrect statements: A acid rain can corrode water pipes; B it can damage stone structures; C it cannot cause respiratory ailments in animals; D it is not harmful to trees.",
      options: ["A, B and D", "A, C and D", "C and D", "C only"],
      answer: "C",
      solution: "A and B are true effects. Acidic aerosol and associated pollutants can aggravate respiration, and acid deposition harms vegetation; therefore statements C and D are incorrect.",
    },
    {
      number: "PYQ 47",
      tag: "Effect match",
      question: "Match a CO, b SO₂, c PCBs and d NOₓ with i carcinogenic, ii metabolised by Pyrus plants, iii haemoglobin and iv stiffness of flower buds.",
      options: ["a-iii, b-iv, c-i, d-ii", "a-iv, b-i, c-iii, d-ii", "a-i, b-ii, c-iii, d-iv", "a-iii, b-iv, c-ii, d-i"],
      answer: "A",
      solution: "CO binds haemoglobin; SO₂ injures plants including flower buds; PCBs are persistent toxic/carcinogenic pollutants; the prescribed source associates NOₓ uptake/metabolism with Pyrus plants.",
    },
    {
      number: "PYQ 48",
      tag: "Greenhouse gases",
      question: "From A CO₂, B O₂, C water vapour and D CH₄, choose the greenhouse gases.",
      options: ["A and C only", "A and B only", "A, C and D only", "A only"],
      answer: "C",
      solution: "CO₂, water vapour and methane absorb terrestrial infrared. O₂ is not an important greenhouse gas.",
    },
  ],
  recap: [
    "The cleanest sample has the lowest BOD; highly organic-polluted samples have high BOD and usually low DO.",
    "PSC surface reactions: ClONO₂ + H₂O → HOCl + HNO₃; ClONO₂ + HCl → Cl₂ + HNO₃.",
    "Enamel contains calcium phosphate with P(V), not P(III).",
    "Photochemical smog is oxidising and sunlight-driven; SO₂ characterises classical smog.",
    "Sulfate–laxative, nitrate–methemoglobinemia, lead–kidney/neurological injury, fluoride–mottling.",
    "Cl· abstracts H from methane to produce CH₃· and HCl.",
    "For acid rain, distinguish a mechanistic oxidation step from the complete overall acid-forming equation.",
    "Question 34 uses a narrow source convention; in umbrella terminology herbicides are pesticides.",
  ],
};

export default function Part14() {
  return <EnvironmentalChemistryPart data={part14Data} />;
}
