"use client";

import EnvironmentalChemistryPart, { type PartData } from "./EnvironmentalChemistryPart";

export const part15Data: PartData = {
  part: 15,
  title: "JEE Advanced Workshop and Master Revision",
  subtitle: "Integrated multi-correct, numerical, mechanism, assertion–reason and matching problems that connect atmospheric, water, soil, waste and green chemistry.",
  goals: [
    "Solve chained questions that combine two or more chapter domains.",
    "Balance radical cycles and identify regenerated catalysts.",
    "Calculate pH, hardness, BOD dilution, half-life and green metrics.",
    "Distinguish concentration, dose, persistence and biomagnification.",
    "Audit each answer for assumptions, units and system boundaries.",
    "Finish with a one-pass mechanism and trap sheet.",
  ],
  sourceNote: "This capstone is original practice built from concepts audited across all available chapter PDFs and the supplied 48-question PYQ set. It does not reproduce coaching solutions. Questions are intentionally more integrated than the source set to match JEE Advanced reasoning.",
  sections: [
    {
      eyebrow: "Big picture",
      title: "One chemical-fate model connects the entire chapter",
      paragraphs: [
        "Every environmental problem can be organised by source, release form, transport, transformation, sink, exposure, effect and intervention. A primary pollutant may transform into a secondary pollutant; the secondary species may partition into water or particles; organisms may then take it up. Control at the source usually has the greatest leverage.",
        "Do not confuse disappearance from one compartment with destruction. SO₂ absorbed into a scrubber becomes a sulfite/sulfate stream. A metal precipitated from water becomes contaminated sludge. A pesticide sorbed to soil may be less mobile temporarily but can persist and remobilise.",
      ],
      flow: [
        "Source and emission",
        "Atmospheric or aqueous transport",
        "Reaction and partition",
        "Exposure and effect",
        "Prevention, control and residual management",
      ],
      table: {
        headers: ["Domain", "Characteristic transformation", "Most common exam trap"],
        rows: [
          ["Air", "NO₂ photolysis; SO₂/NOₓ oxidation; radical chains", "Calling every emitted pollutant secondary"],
          ["Water", "Oxygen consumption, carbonate equilibria, coagulation and redox", "Equating BOD with total pollution"],
          ["Soil/biota", "Sorption, persistence, uptake and trophic transfer", "Confusing bioaccumulation with biomagnification"],
          ["Waste", "Biological, thermal or containment pathway", "Assuming volume reduction destroys atoms"],
          ["Green chemistry", "Route, reagent, catalyst and product redesign", "Using high yield as the only metric"],
        ],
      },
    },
    {
      eyebrow: "Master reaction sheet",
      title: "Equations worth being able to reconstruct",
      equations: [
        "CO + Hb ⇌ HbCO",
        "2SO₂ + O₂ + 2H₂O → 2H₂SO₄",
        "4NO₂ + O₂ + 2H₂O → 4HNO₃",
        "CaCO₃ + H₂SO₄ → CaSO₄ + CO₂ + H₂O",
        "NO₂ + hν → NO + O ; O + O₂ + M → O₃ + M",
        "RH + OH· → R· + H₂O ; R· + O₂ → RO₂·",
        "RO₂· + NO → RO· + NO₂",
        "O₂ + hν → 2O ; O + O₂ + M → O₃ + M",
        "Cl· + O₃ → ClO· + O₂ ; ClO· + O → Cl· + O₂",
        "ClONO₂ + H₂O → HOCl + HNO₃ ; ClONO₂ + HCl → Cl₂ + HNO₃",
        "CO₂ + H₂O ⇌ H₂CO₃ ⇌ H⁺ + HCO₃⁻ ⇌ 2H⁺ + CO₃²⁻",
        "Al³⁺ + 3H₂O ⇌ Al(OH)₃(s) + 3H⁺",
        "Cl₂ + H₂O ⇌ HOCl + H⁺ + Cl⁻ ; HOCl ⇌ H⁺ + OCl⁻",
        "2H₂O₂ → 2H₂O + O₂",
        "2CH₂=CH₂ + O₂ → 2CH₃CHO",
      ],
      boxes: [
        {
          title: "Catalytic-cycle test",
          body: "Add elementary steps and cancel intermediates. A catalyst is consumed early and regenerated later; an intermediate is formed and then consumed.",
          tone: "jee",
        },
      ],
    },
    {
      eyebrow: "Quantitative toolkit",
      title: "Units and proportional reasoning",
      table: {
        headers: ["Quantity", "Working relation", "Unit caution"],
        rows: [
          ["ppm in dilute water", "≈ mg L⁻¹ when density ≈ 1 kg L⁻¹", "Not universally identical outside dilute aqueous systems"],
          ["ppb in dilute water", "≈ μg L⁻¹", "1000 ppb = 1 ppm"],
          ["pH", "−log₁₀[H⁺]", "One pH unit is a tenfold concentration change"],
          ["Hardness as CaCO₃", "mg L⁻¹ species × 50/equivalent mass of species", "Use charge in equivalent mass"],
          ["Dilution BOD", "(DOinitial − DOfinal)/sample fraction", "Correct for blank/seed if problem provides them"],
          ["First-order decay", "N/N₀ = (1/2)^(t/t½)", "Activity follows the same fraction"],
          ["Atom economy", "desired stoichiometric product mass/reactant mass", "Use balanced equation, not isolated mass"],
          ["PMI and E", "PMI = total input/product; E = waste/product", "State whether water and recycled material are counted"],
        ],
      },
    },
    {
      eyebrow: "Comparison sheet",
      title: "Pairs that examiners deliberately blur",
      table: {
        headers: ["Pair", "First", "Second"],
        rows: [
          ["Primary vs secondary pollutant", "Emitted directly: CO, SO₂, NO, primary PM", "Formed in environment: O₃, PAN, much sulfate/nitrate PM"],
          ["DO vs BOD", "Oxygen currently dissolved", "Oxygen demanded by biodegradable matter"],
          ["COD vs BOD", "Chemical oxidation equivalent under specified test", "Biological oxygen use; slower and narrower"],
          ["Bioaccumulation vs biomagnification", "Build-up within one organism over time", "Increase across successive trophic levels"],
          ["Classical vs photochemical smog", "Cool, humid, sulfurous, reducing", "Warm, sunny, NOₓ–VOC, oxidising"],
          ["Tropospheric vs stratospheric O₃", "Pollutant and greenhouse gas", "Protective UV shield"],
          ["Absorption vs adsorption", "Penetration into bulk phase", "Accumulation on a surface"],
          ["Coagulation vs disinfection", "Destabilise/remove colloids", "Inactivate pathogens"],
          ["Atom economy vs yield", "Theoretical atom incorporation", "Experimental recovery relative to theoretical"],
          ["Treatment vs green chemistry", "Controls existing pollutant", "Prevents hazard/waste through design"],
        ],
      },
    },
    {
      eyebrow: "Reasoning traps",
      title: "Twelve statements to challenge before accepting",
      bullets: [
        "Natural means safe — false; identity, dose and exposure determine hazard.",
        "Biodegradable means harmless — false; rapid decay can raise BOD and cause hypoxia.",
        "Low BOD means chemically pure — false; toxic metals may give low BOD.",
        "Ozone is always beneficial — false; location determines role.",
        "A catalyst changes equilibrium — false; it accelerates forward and reverse pathways.",
        "A scrubber eliminates sulfur — false; it transfers sulfur into a captured stream.",
        "Incineration eliminates waste — false; gases and ash remain.",
        "Adsorbed means destroyed — false; the sorbate remains on a surface.",
        "A high-yield process is green — incomplete; examine atom economy, solvent, hazard and energy.",
        "A renewable feedstock is automatically sustainable — false; land, water and conversion burdens matter.",
        "A degradable plastic necessarily mineralises — false; fragmentation can form persistent microplastics.",
        "Every environmental standard uses one universal number — false; standards and endpoints differ. Use the value named in the source/question.",
      ],
    },
    {
      eyebrow: "Answer protocol",
      title: "A five-line advanced solution",
      flow: [
        "State the governing principle",
        "Write the decisive equation",
        "Track units or atoms",
        "Apply the condition or boundary",
        "State the result with one qualification",
      ],
      paragraphs: [
        "This structure prevents long unfocused solutions. In multiple-correct questions, test each option independently against the governing principle. In numerical questions, carry units through every line and report the requested precision only at the end.",
      ],
    },
    {
      eyebrow: "Final memory map",
      title: "Source → signature pollutant → signature consequence",
      table: {
        headers: ["Source/activity", "Signature emission or pollutant", "Characteristic consequence/control"],
        rows: [
          ["Incomplete combustion", "CO and soot", "HbCO formation; improve combustion/catalytic oxidation"],
          ["Coal/oil sulfur", "SO₂", "Acid deposition, respiratory/plant injury; desulfurise/scrub"],
          ["High-temperature combustion", "NOₓ", "Ozone/smog, nitric acid; combustion and catalytic NOₓ control"],
          ["Vehicles + sunlight", "NOₓ and VOC precursors", "O₃, PAN and aldehydes; reduce both precursor classes"],
          ["CFC release", "Stratospheric Cl radicals after photolysis", "Catalytic ozone loss; phase out ozone-depleting substances"],
          ["Sewage/food waste", "Biodegradable organic matter and pathogens", "High BOD, low DO, disease; biological treatment + disinfection"],
          ["Fertiliser runoff", "Nitrate and phosphate", "Eutrophication; source nutrient management"],
          ["Persistent pesticide", "Hydrophobic long-lived toxicant", "Bioaccumulation and biomagnification; safer design/restriction"],
          ["Thermal power", "Fly ash, SO₂, NOₓ and CO₂", "Capture particles, control gases, lower carbon intensity"],
          ["Mixed municipal waste", "Leachate, methane, plastics and vectors", "Source segregation, biological treatment, recovery, sanitary disposal"],
        ],
      },
    },
  ],
  examples: [
    {
      title: "Acid-rain pH comparison",
      problem: "Sample X has pH 4.2 and sample Y pH 5.2. How do their hydrogen-ion concentrations compare?",
      steps: [
        "[H⁺]X/[H⁺]Y = 10^(−4.2)/10^(−5.2).",
        "Subtract exponents: 10^(1.0).",
      ],
      answer: "Sample X has 10 times the hydrogen-ion concentration of sample Y.",
    },
    {
      title: "Dilution BOD",
      problem: "A 15.0 mL wastewater sample is diluted to 300 mL. DO falls from 8.8 to 5.8 mg L⁻¹ with no blank correction. Find BOD.",
      steps: [
        "DO depletion in bottle = 8.8 − 5.8 = 3.0 mg L⁻¹.",
        "Sample fraction P = 15/300 = 0.050.",
        "BOD = depletion/P = 3.0/0.050.",
      ],
      answer: "60 mg L⁻¹ under the stated simplified conditions.",
    },
    {
      title: "Hardness as CaCO₃",
      problem: "Water contains 48.6 mg L⁻¹ Ca(HCO₃)₂. Calculate hardness as CaCO₃. M[Ca(HCO₃)₂] = 162.",
      steps: [
        "Equivalent mass of Ca(HCO₃)₂ for Ca²⁺ hardness = 162/2 = 81.",
        "CaCO₃ equivalent mass = 100/2 = 50.",
        "Hardness = 48.6 × 50/81.",
      ],
      answer: "30.0 mg L⁻¹ as CaCO₃.",
    },
    {
      title: "Catalytic ozone-loss net reaction",
      problem: "Add Cl· + O₃ → ClO· + O₂ and ClO· + O → Cl· + O₂.",
      steps: [
        "Cancel Cl· because it is consumed then regenerated.",
        "Cancel ClO· because it is formed then consumed.",
        "Retain O₃ and O on the reactant side and two O₂ on the product side.",
      ],
      answer: "O₃ + O → 2O₂; Cl· is the catalyst and ClO· an intermediate.",
    },
    {
      title: "Green-process mass balance",
      problem: "A batch uses 50 kg reactants and 150 kg solvent, isolates 40 kg product, and recovers 120 kg solvent for reuse outside the stated batch boundary. Find gross and net PMI if recovered solvent is credited.",
      steps: [
        "Gross input = 200 kg, so gross PMI = 200/40 = 5.0.",
        "With the stated recovery credit, net input = 200 − 120 = 80 kg.",
        "Net PMI = 80/40 = 2.0.",
        "The boundary and recovery credit must be reported with the value.",
      ],
      answer: "Gross PMI = 5.0; net PMI with the specified solvent-recovery credit = 2.0.",
    },
  ],
  questions: [
    {
      number: "A1",
      tag: "Multiple correct",
      question: "Which are secondary pollutants?",
      options: ["Tropospheric O₃ produced from NO₂ photolysis chemistry", "PAN", "CO emitted by an engine", "Sulfate aerosol formed by SO₂ oxidation"],
      answer: "A, B and D",
      solution: "Ozone, PAN and much sulfate form in the atmosphere. Engine CO is emitted directly and is primary.",
    },
    {
      number: "A2",
      tag: "Multiple correct",
      question: "A water sample has high COD, low BOD and low DO. Which explanations are possible?",
      options: ["Chemically oxidisable but poorly biodegradable matter is present", "A toxicant inhibits microorganisms", "Low DO proves the water is chemically pure", "Reducing inorganic species may contribute to COD"],
      answer: "A, B and D",
      solution: "COD can include chemically oxidisable substances not reflected in BOD. Toxic inhibition can depress BOD. Low DO never proves purity.",
    },
    {
      number: "A3",
      tag: "Integer",
      question: "How many of the following are greenhouse gases: CO₂, H₂O vapour, CH₄, N₂, O₂, O₃, CFC-12?",
      answer: "5",
      solution: "CO₂, H₂O vapour, CH₄, O₃ and CFC-12 are counted; N₂ and O₂ are not.",
    },
    {
      number: "A4",
      tag: "Mechanism",
      question: "In NO₂ + hν → NO + O; O + O₂ + M → O₃ + M; O₃ + NO → NO₂ + O₂, what is the net reaction after cancelling intermediates?",
      answer: "No net ozone accumulation; the cycle interconverts O₂/O₃ and NO/NO₂",
      solution: "Adding the steps cancels NO₂, NO, O and O₃, leaving no net chemical change. VOC radical chemistry converts NO to NO₂ without consuming O₃, allowing ozone to accumulate.",
    },
    {
      number: "A5",
      tag: "Multiple correct",
      question: "Which changes can decrease photochemical ozone formation?",
      options: ["Reduce NOₓ emissions", "Reduce reactive VOC emissions", "Increase intense sunlight", "Control evaporative fuel losses"],
      answer: "A, B and D",
      solution: "NOₓ and VOCs are precursors; evaporative loss is a VOC source. More sunlight generally accelerates photochemistry.",
    },
    {
      number: "A6",
      tag: "Numerical",
      question: "Rain pH changes from 5.6 to 4.6. By what factor does [H⁺] increase?",
      answer: "10",
      solution: "A decrease of one pH unit means a tenfold increase in hydrogen-ion concentration.",
    },
    {
      number: "A7",
      tag: "Assertion–reason",
      question: "Assertion: Liming an acidified lake may raise pH. Reason: Carbonate consumes hydrogen ions, but liming does not remove the upstream SO₂/NOₓ source.",
      options: ["Both true; reason correctly qualifies the assertion", "Both true but unrelated", "Assertion true; reason false", "Assertion false; reason true"],
      answer: "A",
      solution: "Carbonate neutralises acidity. The second clause explains why this is remediation, not emission prevention.",
    },
    {
      number: "A8",
      tag: "Multiple correct",
      question: "Which favour biomagnification?",
      options: ["Environmental persistence", "Lipophilicity", "Rapid metabolism to harmless products", "Slow organismal elimination"],
      answer: "A, B and D",
      solution: "A persistent lipophilic compound that is absorbed faster than eliminated can build up and transfer across food webs.",
    },
    {
      number: "A9",
      tag: "Numerical",
      question: "A contaminant is 0.02 μg L⁻¹ in water and 4.0 μg kg⁻¹ in fish tissue. Using the stated numerical concentrations, calculate the concentration ratio.",
      answer: "200",
      solution: "4.0/0.02 = 200. A rigorous bioconcentration factor also requires consistent mass/volume conventions and exposure conditions.",
    },
    {
      number: "A10",
      tag: "Multiple correct",
      question: "Which devices mainly control particulate rather than gaseous pollution?",
      options: ["Cyclone separator", "Electrostatic precipitator", "Fabric filter", "Wet limestone flue-gas desulfurisation absorber"],
      answer: "A, B and C",
      solution: "Cyclones, ESPs and fabric filters capture particles. Limestone scrubbing is primarily for SO₂, though a wet system may incidentally capture some particles.",
    },
    {
      number: "A11",
      tag: "Assertion–reason",
      question: "Assertion: Very fine particles are often harder to remove in a simple gravity chamber. Reason: Their settling velocity is low and Brownian/aerodynamic behaviour keeps them suspended.",
      options: ["Both true; reason explains assertion", "Both true but unrelated", "Assertion true; reason false", "Assertion false; reason true"],
      answer: "A",
      solution: "Gravity chambers work best for coarse particles; fine PM needs filters, ESPs or other high-efficiency control.",
    },
    {
      number: "A12",
      tag: "Multiple correct",
      question: "Which statements about ozone are correct?",
      options: ["Stratospheric ozone absorbs damaging UV", "Tropospheric ozone can injure lungs and crops", "CFC-derived chlorine can catalyse ozone destruction", "Ozone is emitted as the principal primary pollutant from vehicle exhaust"],
      answer: "A, B and C",
      solution: "Ground-level ozone is largely secondary, made from precursor photochemistry rather than emitted as the main exhaust pollutant.",
    },
    {
      number: "A13",
      tag: "Numerical",
      question: "A radionuclide has t½ = 6 h. What percentage remains after 24 h?",
      answer: "6.25%",
      solution: "Four half-lives pass; fraction = (1/2)⁴ = 1/16 = 6.25%.",
    },
    {
      number: "A14",
      tag: "Green metrics",
      question: "A process has atom economy 100% but E-factor 25. Which conclusion is valid?",
      options: ["It must be green", "It has no stoichiometric co-product in the ideal equation but generates much process waste", "Yield must be 100%", "Solvent cannot be present"],
      answer: "B",
      solution: "Atom economy ignores actual yield, solvent and work-up. A high E-factor reveals large waste per product despite ideal incorporation.",
    },
    {
      number: "A15",
      tag: "Multiple correct",
      question: "Replacing chlorine bleaching with selective H₂O₂ can be greener because:",
      options: ["Ideal reduced by-product is water", "Chlorinated organic by-products may be reduced", "H₂O₂ is harmless at every concentration", "Selectivity and dose still require control"],
      answer: "A, B and D",
      solution: "Hydrogen peroxide can offer cleaner by-products, but it remains a reactive oxidant and must be managed.",
    },
    {
      number: "A16",
      tag: "Water treatment",
      question: "Arrange a conventional treatment train logically: I filtration; II coagulation/flocculation; III disinfection; IV sedimentation.",
      answer: "II → IV → I → III",
      solution: "Coagulation forms flocs, sedimentation removes most, filtration polishes particles and disinfection inactivates remaining pathogens.",
    },
    {
      number: "A17",
      tag: "Multiple correct",
      question: "Which statements about activated carbon are correct?",
      options: ["It removes every dissolved ion quantitatively", "It adsorbs many organic micropollutants", "Spent carbon requires regeneration or disposal", "Adsorption is the same as chemical destruction"],
      answer: "B and C",
      solution: "Activated carbon offers high surface area for adsorption. Capacity is finite; adsorption transfers the pollutant to a solid phase.",
    },
    {
      number: "A18",
      tag: "Integer",
      question: "How many are source-prevention actions: switching to low-sulfur feed, installing an ESP, redesigning a synthesis to avoid toxic solvent, recycling solvent, diluting effluent?",
      answer: "3",
      solution: "Low-sulfur feed, process redesign and solvent recycling reduce pollution generation/input. ESP is end-of-pipe capture; dilution is not treatment.",
    },
    {
      number: "A19",
      tag: "Integrated matching",
      question: "Match: a CO; b nitrate-rich runoff; c CFC; d persistent lipophilic pesticide with i ozone depletion; ii HbCO; iii eutrophication; iv biomagnification.",
      options: ["a-ii, b-iii, c-i, d-iv", "a-i, b-iv, c-iii, d-ii", "a-iii, b-ii, c-iv, d-i", "a-iv, b-i, c-ii, d-iii"],
      answer: "A",
      solution: "Each source-effect pair follows its characteristic mechanism: competitive Hb binding, nutrient enrichment, stratospheric radical release and trophic accumulation.",
    },
    {
      number: "A20",
      tag: "Boundary reasoning",
      question: "A company claims “zero liquid discharge” because all wastewater is evaporated, leaving a salt cake. Which assessment is best?",
      options: ["All pollution has been destroyed", "The claim proves zero energy use", "Liquid release may be avoided, but energy, air emission and solid-residue fate must be assessed", "The salt cake is automatically edible"],
      answer: "C",
      solution: "Evaporation changes the waste form. A full mass and energy balance must track volatile emissions and the concentrated residue.",
    },
  ],
  recap: [
    "Trace source → transformation → compartment → exposure → effect → intervention.",
    "Cancelling elementary steps reveals catalysts, intermediates and net reactions.",
    "High BOD usually accompanies low DO, but BOD is not a universal measure of every pollutant.",
    "One pH unit equals a tenfold change in [H⁺].",
    "Persistence + uptake + slow elimination enable bioaccumulation and biomagnification.",
    "Every control device creates or concentrates a residual stream that must be tracked.",
    "A green claim needs balanced mass, hazard, energy and life-cycle boundaries.",
    "Use textbook values for the exam while recognising that real standards depend on jurisdiction and endpoint.",
  ],
};

export default function Part15() {
  return <EnvironmentalChemistryPart data={part15Data} />;
}
