import Link from "next/link";
import type { ReactNode } from "react";

function Section({ title, children }: { title: string; children: ReactNode }) {
  return <section className="mt-7 rounded-2xl border border-white/10 bg-[#102235] p-5 sm:p-7"><h2 className="font-serif text-2xl font-black text-white sm:text-3xl">{title}</h2><div className="mt-4 space-y-4 text-sm leading-7 text-slate-300">{children}</div></section>;
}
function Callout({ title, children, tone = "cyan" }: { title: string; children: ReactNode; tone?: "cyan" | "amber" | "rose" }) {
  const colour = { cyan: "border-cyan-300/25 bg-cyan-300/[.07] text-cyan-50", amber: "border-amber-300/25 bg-amber-300/[.07] text-amber-50", rose: "border-rose-300/25 bg-rose-300/[.07] text-rose-50" }[tone];
  return <aside className={`rounded-xl border p-4 ${colour}`}><b className="font-bold">{title}</b><div className="mt-1">{children}</div></aside>;
}
function Equation({ children }: { children: ReactNode }) { return <div className="overflow-x-auto rounded-xl border border-white/10 bg-[#091826] px-4 py-3 font-mono text-sm font-bold text-cyan-100">{children}</div>; }

export default function SBlockMasterNotesPage() {
  return <main className="min-h-screen bg-[#0a1622] px-4 pb-20 pt-24 text-white sm:px-6"><article className="mx-auto max-w-5xl"><Link href="/programs/jee-advanced/chapter/s-block" className="text-sm font-bold text-cyan-300">← S-block course map</Link><header className="mt-5 rounded-3xl border border-cyan-300/20 bg-[radial-gradient(circle_at_top_left,rgba(34,211,238,.22),transparent_38%),linear-gradient(135deg,#143247,#102235)] p-7 sm:p-11"><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-300">NCERT-first · JEE Advanced & Olympiad master notes</p><h1 className="mt-3 font-serif text-4xl font-black sm:text-6xl">s-Block Elements</h1><p className="mt-4 max-w-3xl leading-7 text-slate-200">Alkali metals and alkaline-earth metals: trends, exceptions, structures, reactions and the reasoning needed for multi-concept questions.</p></header>

<Section title="Group 1 — alkali metals: identity and general trends"><p><b className="text-white">Configuration:</b> ns¹ (Li to Cs); the dominant oxidation state is +1. Down the group, atomic/ionic radius increases, first ionisation enthalpy and electronegativity decrease, and metallic/electropositive character increases. Their salts are usually colourless because M⁺ has a noble-gas configuration.</p><ul className="list-disc space-y-2 pl-5"><li><b className="text-white">Density:</b> generally rises down the group, but <b>K is less dense than Na</b>; a periodic trend is not a substitute for experimental data.</li><li><b className="text-white">Hydration:</b> magnitude of hydration enthalpy decreases Li⁺ &gt; Na⁺ &gt; K⁺ &gt; Rb⁺ &gt; Cs⁺. Small, strongly hydrated Li⁺ has lower ionic mobility than its small bare radius might suggest.</li><li><b className="text-white">Standard potential:</b> in aqueous solution Li is the strongest reducing alkali metal because Li⁺ is exceptionally stabilised by hydration. This differs from a simple gaseous ionisation-enthalpy argument.</li></ul><Callout title="NCERT-first pivot" tone="amber">For aqueous comparisons, use the complete thermodynamic picture: atomisation + ionisation + hydration. Do not equate “larger atom” with “stronger reducing agent in water”.</Callout></Section>

<Section title="Flame coloration and excitation"><p>In a flame, thermal energy promotes an outer electron to an excited state. Emission during return to a lower level produces characteristic wavelengths. <b>Li:</b> crimson red; <b>Na:</b> golden yellow; <b>K:</b> lilac/violet (observed through cobalt glass when sodium is present); <b>Ca:</b> brick red; <b>Sr:</b> crimson; <b>Ba:</b> apple green.</p><p><b>Be and Mg do not impart a characteristic flame colour</b> under the usual test because their excitation energies are high; the flame does not populate an emitting state sufficiently.</p><Callout title="JEE trap" tone="rose">A flame test is supportive, not a confirmatory analysis. Sodium contamination is exceptionally intense and can mask potassium.</Callout></Section>

<Section title="Alkali metals in liquid ammonia"><p>Alkali metals dissolve in dry liquid NH₃ to give solvated cations and <b>ammoniated (solvated) electrons</b>. The dilute solution is deep blue, conducting and paramagnetic; the blue colour is associated with solvated electrons, not a coloured metal ion.</p><Equation>M + (x + y)NH₃ → [M(NH₃)ₓ]⁺ + [e(NH₃)ᵧ]⁻</Equation><ul className="list-disc space-y-2 pl-5"><li>At low concentration, the solution is deep blue and <b>paramagnetic</b> because electrons are unpaired.</li><li>At high concentration, it becomes bronze/metallic-looking, conductivity rises strongly, and the standard NCERT treatment describes electron pairing leading to <b>diamagnetic</b> behaviour.</li><li>The system is a powerful reducing medium. The solvent and moisture must be rigorously controlled.</li></ul><Callout title="Do not oversimplify" tone="amber">The concentration-dependent metallic phase is structurally and electronically complex. For JEE/NCERT questions, use the stated blue-paramagnetic dilute and bronze-diamagnetic concentrated description.</Callout></Section>

<Section title="Anomalous lithium and diagonal relation with magnesium"><p>Lithium differs from the rest of Group 1 because Li⁺ is exceptionally small, strongly hydrated and strongly polarising. It therefore shows greater covalent character and several parallels with Mg²⁺.</p><ul className="list-disc space-y-2 pl-5"><li>Li is harder and has higher melting point than other alkali metals; it reacts directly with nitrogen to form Li₃N.</li><li>Li forms chiefly Li₂O, whereas Na favours Na₂O₂ and K/Rb/Cs favour superoxides in excess oxygen.</li><li>Li₂CO₃ decomposes on heating; most other Group 1 carbonates are thermally stable.</li><li>LiNO₃ gives oxide + NO₂ + O₂ on heating, like Group 2 nitrates; NaNO₃/KNO₃ give nitrite + O₂.</li><li>LiF, Li₂CO₃ and Li₃PO₄ are relatively sparingly soluble; LiCl is deliquescent and has appreciable covalent character.</li></ul><Equation>4LiNO₃  Δ→  2Li₂O + 4NO₂ + O₂</Equation><Equation>Li₂CO₃  Δ→  Li₂O + CO₂</Equation></Section>

<Section title="Chemical reactivity of Group 1"><h3 className="font-bold text-cyan-200">Air and oxygen</h3><Equation>4Li + O₂ → 2Li₂O</Equation><Equation>2Na + O₂ → Na₂O₂</Equation><Equation>K + O₂ → KO₂</Equation><p>Oxide contains O²⁻, peroxide O₂²⁻ (O = −1) and superoxide O₂⁻ (average O = −½). Superoxide is paramagnetic; peroxide is diamagnetic.</p><h3 className="font-bold text-cyan-200">Water, hydrides and halides</h3><Equation>2M + 2H₂O → 2MOH + H₂↑</Equation><Equation>2M + H₂ → 2MH</Equation><Equation>2M + X₂ → 2MX</Equation><p>Ionic hydrides contain H⁻ and hydrolyse vigorously: <b>MH + H₂O → MOH + H₂</b>. Covalent character of lithium halides rises from F⁻ to I⁻ because anion polarisability rises.</p><h3 className="font-bold text-cyan-200">Carbon-rich anions</h3><p>Alkali metals can form acetylides such as Na₂C₂ under specialised conditions. Hydrolysis of C₂²⁻ gives ethyne, whereas methanide C⁴⁻ gives methane; identify the carbide anion before predicting hydrolysis.</p><Equation>CaC₂ + 2H₂O → Ca(OH)₂ + C₂H₂↑</Equation></Section>

<Section title="Important sodium compounds"><h3 className="font-bold text-amber-200">Sodium carbonate — Solvay process</h3><p>Ammoniated brine is treated with CO₂; sparingly soluble NaHCO₃ precipitates and is heated. The selectivity works because NaHCO₃ is less soluble in this medium; the corresponding potassium bicarbonate is too soluble, so <b>K₂CO₃ is not prepared by the Solvay process</b>.</p><Equation>NaCl + NH₃ + CO₂ + H₂O → NaHCO₃↓ + NH₄Cl</Equation><Equation>2NaHCO₃  Δ→  Na₂CO₃ + CO₂ + H₂O</Equation><p>Na₂CO₃·10H₂O is washing soda; it softens water by precipitating Ca²⁺/Mg²⁺ carbonates. NaHCO₃ is baking soda and a mild base.</p><h3 className="font-bold text-amber-200">NaCl and NaOH</h3><p>Brine electrolysis (the mercury-cell/Castner–Kellner process is a historical industrial route) gives chlorine, hydrogen and NaOH. Modern plants preferentially use membrane technology because mercury creates serious environmental hazards.</p><Equation>2NaCl + 2H₂O → 2NaOH + Cl₂↑ + H₂↑</Equation></Section>

<Section title="Group 2 — alkaline-earth metals: trends and beryllium anomaly"><p><b>Configuration:</b> ns²; usual oxidation state +2. Group 2 metals are generally harder and higher-melting than Group 1 analogues because they contribute two valence electrons to metallic bonding. Size increases and ionisation enthalpy decreases down the group.</p><p><b>Be is anomalous</b>: its high charge density gives covalent, often polymeric compounds; BeO and Be(OH)₂ are amphoteric; BeCl₂ is polymeric in solid state and electron-deficient. Be resembles Al diagonally in amphoterism, covalent halides and complex formation.</p><Equation>Be(OH)₂ + 2OH⁻ → [Be(OH)₄]²⁻</Equation><Equation>BeO + 2H⁺ → Be²⁺ + H₂O</Equation><p>With water: Be does not react, Mg is very slow with cold water but reacts with steam, and Ca/Sr/Ba react readily with cold water.</p><Equation>Mg + H₂O(g) → MgO + H₂↑</Equation><Equation>Ca + 2H₂O → Ca(OH)₂ + H₂↑</Equation></Section>

<Section title="Group 2 solubility and thermal stability"><p>These trends are controlled by a competition between <b>lattice enthalpy</b> (opposes dissolution) and <b>hydration enthalpy</b> (favours dissolution). State both when explaining a trend.</p><ul className="list-disc space-y-2 pl-5"><li><b>Hydroxide solubility increases down Group 2:</b> Mg(OH)₂ &lt; Ca(OH)₂ &lt; Sr(OH)₂ &lt; Ba(OH)₂; basicity correspondingly rises.</li><li><b>Sulfate solubility decreases down Group 2:</b> MgSO₄ is soluble, CaSO₄ sparingly soluble, BaSO₄ extremely insoluble.</li><li><b>Carbonate thermal stability increases down Group 2:</b> small M²⁺ polarises CO₃²⁻ more strongly and destabilises it.</li><li><b>Group 2 nitrates:</b> heat to oxide + NO₂ + O₂; thermal stability rises down the group.</li><li>Group 2 bicarbonates exist principally in solution and decompose on heating.</li></ul><Equation>MCO₃  Δ→  MO + CO₂</Equation><Equation>2M(NO₃)₂  Δ→  2MO + 4NO₂ + O₂</Equation><Callout title="Frequent JEE trap" tone="rose">Hydroxides and sulfates have opposite solubility trends down Group 2. Never use one mnemonic for all salts.</Callout></Section>

<Section title="Calcium compounds and cement"><h3 className="font-bold text-amber-200">Lime cycle</h3><Equation>CaCO₃  Δ→  CaO + CO₂</Equation><Equation>CaO + H₂O → Ca(OH)₂</Equation><Equation>Ca(OH)₂ + CO₂ → CaCO₃↓ + H₂O</Equation><Equation>CaCO₃ + CO₂ + H₂O → Ca(HCO₃)₂(aq)</Equation><p>CaO is quicklime; Ca(OH)₂ is slaked lime. Lime water turns milky with limited CO₂ due to CaCO₃, then clears in excess CO₂ because soluble bicarbonate forms.</p><h3 className="font-bold text-amber-200">Gypsum, plaster and Portland cement</h3><p>Gypsum is CaSO₄·2H₂O. Partial dehydration gives plaster of Paris, CaSO₄·½H₂O, which sets by rehydration. Strong heating gives anhydrous CaSO₄ (“dead-burnt plaster”), which does not set readily.</p><Equation>2(CaSO₄·2H₂O)  Δ→  2CaSO₄·½H₂O + 3H₂O</Equation><p><b>Portland cement</b> is chiefly calcium silicates and aluminates: approximate clinker phases are 3CaO·SiO₂, 2CaO·SiO₂, 3CaO·Al₂O₃ and 4CaO·Al₂O₃·Fe₂O₃. Gypsum is added to regulate setting; treat composition as approximate, not a single compound.</p></Section>

<Section title="Biological importance"><ul className="list-disc space-y-2 pl-5"><li><b>Na⁺/K⁺:</b> gradients maintained by the sodium–potassium pump support nerve impulses and osmotic balance.</li><li><b>Mg²⁺:</b> central ion in chlorophyll and an important enzyme cofactor.</li><li><b>Ca²⁺:</b> structural role in bones/teeth and key function in muscle contraction, nerve signalling and blood clotting.</li></ul><Callout title="Scope note" tone="cyan">These are application facts; chemical questions still require ion charge, hydration, solubility and reaction logic.</Callout></Section>

<Section title="Advanced edge — Olympiad and AITS-style exceptions"><ul className="list-disc space-y-3 pl-5"><li><b>Crown ethers:</b> 18-crown-6 can strongly complex K⁺. Complexation changes ion pairing and can dissolve otherwise ionic salts in organic solvents; cavity-size matching is a tendency, not an absolute law.</li><li><b>Carbide hydrolysis:</b> Be₂C is methanide-like and hydrolyses to CH₄; CaC₂ is an acetylide and hydrolyses to C₂H₂. The hydrocarbon reveals the carbide anion.</li><li><b>Polymeric structures:</b> BeH₂ and BeCl₂ are electron-deficient/polymeric in the solid state; do not draw them as simple isolated ionic Be²⁺ salts.</li><li><b>Heating sequences:</b> inspect cation size, anion and temperature. LiNO₃ follows Group 2 nitrate chemistry; NaHCO₃ first gives Na₂CO₃; excess CO₂ converts CaCO₃ to bicarbonate in water.</li><li><b>Qualitative analysis:</b> acidify before the Ba²⁺ sulfate test to avoid precipitation from carbonate/sulfite interference; BaSO₄ is safe as a contrast agent because it is insoluble, unlike soluble Ba²⁺ salts.</li></ul><Equation>Be₂C + 4H₂O → 2Be(OH)₂ + CH₄↑</Equation><Equation>CaC₂ + 2H₂O → Ca(OH)₂ + C₂H₂↑</Equation></Section>

<Section title="Final revision grid"><div className="grid gap-3 sm:grid-cols-2"><Callout title="Must derive" tone="cyan">Aqueous reducing power, solubility and thermal stability: use size + hydration + lattice + polarisation, not a single periodic arrow.</Callout><Callout title="Must memorise" tone="amber">Li anomaly; oxide/peroxide/superoxide products; Group 2 hydroxide versus sulfate solubility; major lime and sodium compound reactions.</Callout><Callout title="Must check in equations" tone="rose">Medium, heating, excess reagent and water availability. These conditions change many s-block products.</Callout><Callout title="Verification hierarchy" tone="cyan">NCERT is first authority for curriculum facts. Advanced texts supply mechanisms; Olympiad/coaching patterns guide question depth, never replace verified chemistry.</Callout></div></Section>
      </article></main>;
}
