// AUTO-GENERATED — do not hand-edit.
// Maps each standalone chemistry-notes SVG to the minimum CSS pixel width
// at which its smallest annotation renders at >= 10px (its native font-size
// in user units == its native rendered px at 1:1 scale, since every SVG here
// is authored with viewBox units equal to CSS px). Used by chemistryMarkdown's
// `img` renderer to size figures on narrow (< sm) viewports: below that width
// the figure is held at this floor and scrolls inside its own card; at sm and
// above the original fixed 680px-cap desktop rendering is unchanged.
//
// Regenerate by re-running the QA harness's per-file (viewBox width, minimum
// rendered font-size) extraction and this script's scale computation.
export const SVG_MOBILE_MIN_WIDTH: Record<string, number> = {
  "/notes/boron-family/b_boricacid.svg": 690,
  "/notes/boron-family/b_boronprep.svg": 667,
  "/notes/boron-family/b_diborane.svg": 750,
  "/notes/carbon-family/c_blastfurnace.svg": 561,
  "/notes/carbon-family/c_caco2furnace.svg": 659,
  "/notes/carbon-family/c_cementkiln.svg": 1133,
  "/notes/carbon-family/c_limekiln.svg": 1133,
  "/notes/carbon-family/c_prepco.svg": 659,
  "/notes/carbon-family/c_prepco2.svg": 1134,
  "/notes/carbon-family/c_sicfurnace.svg": 675,
  "/notes/carbon-family/c_silicates.svg": 1134,
  "/notes/carbon-family/c_silicone.svg": 853,
  "/notes/carbon-family/c_siliconpure.svg": 1027,
  "/notes/halogen-family/h_bleach.svg": 816,
  "/notes/halogen-family/h_bondenthalpy.svg": 612,
  "/notes/halogen-family/h_cloanions.svg": 824,
  "/notes/halogen-family/h_cloxides.svg": 650,
  "/notes/halogen-family/h_cloxoacids.svg": 847,
  "/notes/halogen-family/h_colour.svg": 659,
  "/notes/halogen-family/h_f2cell.svg": 827,
  "/notes/halogen-family/h_hf.svg": 612,
  "/notes/halogen-family/h_hxbp.svg": 612,
  "/notes/halogen-family/h_i3.svg": 565,
  "/notes/halogen-family/h_interhalogen.svg": 900,
  "/notes/halogen-family/h_membranecell.svg": 706,
  "/notes/halogen-family/h_prepcl2.svg": 750,
  "/notes/halogen-family/h_prephcl.svg": 700,
  "/notes/halogen-family/h_trends.svg": 810,
  "/notes/hydrogen/01_periodic_position.svg": 1400,
  "/notes/hydrogen/02_isotopes.svg": 1400,
  "/notes/hydrogen/03_zero_point_energy.svg": 1400,
  "/notes/hydrogen/04_industrial_hydrogen.svg": 1400,
  "/notes/hydrogen/06_hydride_classification.svg": 1400,
  "/notes/hydrogen/07_diborane.svg": 1400,
  "/notes/hydrogen/08_hydrogen_bonding.svg": 1400,
  "/notes/hydrogen/10_hard_water.svg": 1400,
  "/notes/hydrogen/11_ion_exchange.svg": 1400,
  "/notes/hydrogen/13_hydrogen_economy.svg": 1400,
  "/notes/hydrogen/14_steam_reforming_shift.svg": 1400,
  "/notes/hydrogen/15_atomic_hydrogen_torch.svg": 1400,
  "/notes/hydrogen/16_ortho_para_temperature_graph.svg": 1400,
  "/notes/hydrogen/17_hydride_periodic_map.svg": 1400,
  "/notes/hydrogen/18_metallic_interstitial_hydride.svg": 1400,
  "/notes/hydrogen/20_ice_3d_lattice.svg": 1400,
  "/notes/hydrogen/21_zeolite_column.svg": 1400,
  "/notes/hydrogen/22_d2o_comparison.svg": 1400,
  "/notes/hydrogen/23_h2o2_dihedral.svg": 1400,
  "/notes/hydrogen/24_anthraquinone_process.svg": 1400,
  "/notes/hydrogen/25_h2o2_redox_map.svg": 1400,
  "/notes/hydrogen/26_h2_mo_energy.svg": 1400,
  "/notes/hydrogen/27_ortho_para_spin.svg": 1400,
  "/notes/hydrogen/28_surface_hydrogen_activation.svg": 1400,
  "/notes/hydrogen/29_diborane_3c2e_mo.svg": 1400,
  "/notes/hydrogen/30_hbond_orbital_donation.svg": 1400,
  "/notes/hydrogen/31_water_mo_geometry.svg": 1400,
  "/notes/hydrogen/32_h2o2_redox_mechanism.svg": 1400,
  "/notes/hydrogen/33_hydride_transfer_mechanism.svg": 1400,
  "/notes/hydrogen/h_d2ocell.svg": 635,
  "/notes/hydrogen/h_electrolysis.svg": 659,
  "/notes/hydrogen/h_preph2.svg": 729,
  "/notes/nitrogen-family/n_allotropes.svg": 1134,
  "/notes/nitrogen-family/n_brownring.svg": 933,
  "/notes/nitrogen-family/n_condensedphosphate.svg": 974,
  "/notes/nitrogen-family/n_fountain.svg": 862,
  "/notes/nitrogen-family/n_haber.svg": 1027,
  "/notes/nitrogen-family/n_hno2.svg": 718,
  "/notes/nitrogen-family/n_hno3.svg": 718,
  "/notes/nitrogen-family/n_holme.svg": 732,
  "/notes/nitrogen-family/n_hydrides.svg": 974,
  "/notes/nitrogen-family/n_n2mo.svg": 846,
  "/notes/nitrogen-family/n_nh3.svg": 708,
  "/notes/nitrogen-family/n_ostwald.svg": 1000,
  "/notes/nitrogen-family/n_oxides.svg": 1051,
  "/notes/nitrogen-family/n_p4.svg": 862,
  "/notes/nitrogen-family/n_p4furnace.svg": 1029,
  "/notes/nitrogen-family/n_pcl5.svg": 842,
  "/notes/nitrogen-family/n_poxides.svg": 974,
  "/notes/nitrogen-family/n_poxoacids.svg": 1051,
  "/notes/nitrogen-family/n_prephno3.svg": 886,
  "/notes/nitrogen-family/n_prepn2.svg": 857,
  "/notes/nitrogen-family/n_prepnh3.svg": 886,
  "/notes/nitrogen-family/n_prepph3.svg": 886,
  "/notes/nitrogen-family/n_smallstruct.svg": 974,
  "/notes/noble-gases/ng_bartlett.svg": 850,
  "/notes/noble-gases/ng_clathrate.svg": 886,
  "/notes/noble-gases/ng_distillation.svg": 895,
  "/notes/noble-gases/ng_prepxef2.svg": 886,
  "/notes/noble-gases/ng_trends.svg": 659,
  "/notes/noble-gases/ng_xef.svg": 847,
  "/notes/noble-gases/ng_xef5.svg": 700,
  "/notes/noble-gases/ng_xeo.svg": 824,
  "/notes/oxygen-family/o_allotropes.svg": 1134,
  "/notes/oxygen-family/o_contact.svg": 1108,
  "/notes/oxygen-family/o_frasch.svg": 1000,
  "/notes/oxygen-family/o_h2o2.svg": 706,
  "/notes/oxygen-family/o_kipp.svg": 950,
  "/notes/oxygen-family/o_o2mo.svg": 846,
  "/notes/oxygen-family/o_ozone.svg": 954,
  "/notes/oxygen-family/o_ozoniser.svg": 971,
  "/notes/oxygen-family/o_prepo2.svg": 943,
  "/notes/oxygen-family/o_prepso2.svg": 868,
  "/notes/oxygen-family/o_s8.svg": 667,
  "/notes/oxygen-family/o_sf6.svg": 612,
  "/notes/oxygen-family/o_so3forms.svg": 875,
  "/notes/oxygen-family/o_sooxides.svg": 612,
  "/notes/oxygen-family/o_soxoacids.svg": 894,
  "/notes/oxygen-family/o_soxoacids2.svg": 900,
  "/notes/oxygen-family/o_sviscosity.svg": 659,
  "/notes/s-block/s_chloralkali.svg": 683,
  "/notes/s-block/s_downs.svg": 683,
  "/notes/s-block/s_flametest.svg": 789,
  "/notes/s-block/s_solvay.svg": 667,
};

export const SVG_MOBILE_MIN_WIDTH_DEFAULT = 720;
