import { SolidStatePartPage, type SolidStatePartData } from "./_shared";

export const partInfo = {
  part: 5,
  slug: "crystal-lattice-lattice-point-and-unit-cell",
  title: "Crystal Lattice, Lattice Point and Unit Cell",
} as const;

const data = {
  "part": 5,
  "slug": "crystal-lattice-lattice-point-and-unit-cell",
  "title": "Crystal Lattice, Lattice Point and Unit Cell",
  "sourcePages": "pp. 5–6 and the unit-cell illustrations on pp. 28–30",
  "intro": "KOHINOOR defines the crystal/space lattice, lattice point and unit cell before moving into counting and cell classification.",
  "sections": [
    {
      "title": "1. Crystal Lattice / Space Lattice",
      "blocks": [
        {
          "type": "p",
          "text": "A crystal lattice is an infinite regular three-dimensional array of equivalent points. The points encode translational periodicity; they are geometrical entities, not automatically literal atoms."
        },
        {
          "type": "formula",
          "latex": "\\\\mathbf R=n_1\\\\mathbf a+n_2\\\\mathbf b+n_3\\\\mathbf c",
          "display": "R = n₁a + n₂b + n₃c, where n₁,n₂,n₃ are integers."
        },
        {
          "type": "p",
          "text": "A crystal structure is generated by attaching the same basis or motif to every lattice point."
        }
      ]
    },
    {
      "title": "2. Meaning of a Lattice Point",
      "blocks": [
        {
          "type": "table",
          "headers": [
            "Solid type",
            "What a lattice point may represent"
          ],
          "rows": [
            [
              "Metallic solid",
              "A metal atom or equivalent atomic motif"
            ],
            [
              "Ionic solid",
              "An equivalent ionic motif; a complete ionic crystal generally needs a multi-ion basis"
            ],
            [
              "Noble-gas solid",
              "A noble-gas atom"
            ],
            [
              "Molecular solid",
              "A molecular centre/orientation; e.g. centre of a CH₄ molecule"
            ]
          ]
        },
        {
          "type": "callout",
          "label": "Key identity",
          "text": "Crystal structure = lattice + basis (motif).",
          "tone": "result"
        }
      ]
    },
    {
      "title": "3. Unit Cell",
      "blocks": [
        {
          "type": "p",
          "text": "A unit cell is a repeating region which, by translation, generates the whole crystal. A useful unit cell must reproduce the full translational structure without gaps or overlaps."
        },
        {
          "type": "p",
          "text": "The choice of origin is not unique. Different-looking cells can describe the same structure if translation reproduces the identical motif. A conventional cell is often chosen to make symmetry obvious."
        }
      ]
    },
    {
      "title": "4. Cube Geometry Inventory",
      "blocks": [
        {
          "type": "table",
          "headers": [
            "Geometrical feature",
            "Number in a cube"
          ],
          "rows": [
            [
              "Corners",
              "8"
            ],
            [
              "Faces",
              "6"
            ],
            [
              "Edges",
              "12"
            ],
            [
              "Body centre",
              "1"
            ],
            [
              "Face diagonals",
              "12"
            ],
            [
              "Body diagonals",
              "4"
            ],
            [
              "Edge centres",
              "12"
            ],
            [
              "Face centres",
              "6"
            ]
          ]
        },
        {
          "type": "ascii",
          "text": "z=1     (0,1,1)------(1,1,1)\n         /|              /|\n        / |             / |\n(0,0,1)------(1,0,1)   |\n       |  |            |  |\n       | (0,1,0)-------|-(1,1,0)\n       | /             | /\n       |/              |/\nz=0  (0,0,0)------(1,0,0)",
          "title": "Fractional-coordinate frame"
        }
      ]
    }
  ],
  "traps": [
    "A lattice point is not necessarily one atom.",
    "A conventional unit cell need not be primitive.",
    "The smallest-looking drawn shape is not automatically a valid unit cell; translation must reproduce an identical environment everywhere."
  ],
  "examples": [
    {
      "title": "Example 1 — Basis logic",
      "question": "A primitive lattice carries an AB₂ motif at every lattice point. What is the chemical content associated with one primitive cell?",
      "steps": [
        "A primitive cell contains one lattice point.",
        "Each lattice point carries one AB₂ motif."
      ],
      "answer": "One primitive cell contains AB₂."
    },
    {
      "title": "Example 2 — Unit-cell validity",
      "question": "A proposed repeat unit alternates its top-right corner between Na and Cl after translation. Is it a valid unit cell?",
      "steps": [
        "Equivalent translated cells must be identical.",
        "Changing the identity at an equivalent corner violates translational equivalence."
      ],
      "answer": "No. The proposed repeat unit is invalid."
    }
  ]
} satisfies SolidStatePartData;

export default function SolidStatePart05() {
  return <SolidStatePartPage data={data} />;
}
