import type { HighYieldReaction } from "./schema";

export const highYieldReactions = [
  {
    id: "alkene-catalytic-hydrogenation",
    name: "Catalytic Hydrogenation of Alkenes",
    category: "Hydrocarbons",
    reactionType: "Addition",
    reagents: ["H2", "Ni, Pt, or Pd catalyst"],
    products: ["Alkane"],
    conditions: ["Moderate temperature", "Catalytic surface"],
    mechanism: ["Syn addition of hydrogen on a metal surface to the C=C bond."],
    exceptions: ["Sterically hindered alkenes hydrogenate more slowly."],
    relatedReactions: ["alkene-bromination", "alkene-hydroboration-oxidation"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["alkene addition", "hydrogenation"] },
    ncertReference: { class: 11, chapter: "Hydrocarbons", topic: "Addition reactions of alkenes" },
  },
  {
    id: "alkene-hx-markovnikov-addition",
    name: "Markovnikov Addition of HX to Alkenes",
    category: "Hydrocarbons",
    reactionType: "Addition",
    reagents: ["HX (HCl, HBr, or HI)"],
    products: ["Alkyl halide"],
    conditions: ["No peroxide", "Polar medium"],
    mechanism: ["Protonation gives the more stable carbocation, then halide attacks."],
    exceptions: ["HBr gives anti-Markovnikov product in peroxide conditions."],
    relatedReactions: ["alkene-hbr-peroxide-addition", "haloalkane-sn1-hydrolysis"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["Markovnikov rule", "carbocation stability"] },
    ncertReference: { class: 11, chapter: "Hydrocarbons", topic: "Markovnikov addition" },
  },
  {
    id: "alkene-hbr-peroxide-addition",
    name: "Anti-Markovnikov Addition of HBr",
    category: "Hydrocarbons",
    reactionType: "Addition",
    reagents: ["HBr", "Organic peroxide"],
    products: ["Anti-Markovnikov bromoalkane"],
    conditions: ["Peroxide effect", "Radical chain conditions"],
    mechanism: ["Bromine radical adds to form the more stable carbon radical, followed by H abstraction."],
    exceptions: ["Peroxide effect is reliable for HBr, not for HCl or HI."],
    relatedReactions: ["alkene-hx-markovnikov-addition"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["peroxide effect", "anti-Markovnikov"] },
    ncertReference: { class: 11, chapter: "Hydrocarbons", topic: "Peroxide effect" },
  },
  {
    id: "alkene-hydroboration-oxidation",
    name: "Hydroboration-Oxidation of Alkenes",
    category: "Hydrocarbons",
    reactionType: "Addition",
    reagents: ["BH3.THF", "H2O2", "OH-"],
    products: ["Anti-Markovnikov alcohol"],
    conditions: ["Anhydrous THF then alkaline peroxide"],
    mechanism: ["Concerted syn hydroboration followed by oxidation with retention at carbon."],
    exceptions: ["Rearrangement is avoided because no carbocation is formed."],
    relatedReactions: ["alcohol-pcc-oxidation"],
    examRelevance: { exams: ["JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["hydroboration", "anti-Markovnikov alcohol"] },
    ncertReference: { class: 11, chapter: "Hydrocarbons", topic: "Addition reactions of alkenes" },
  },
  {
    id: "alkene-ozonolysis",
    name: "Ozonolysis of Alkenes",
    category: "Hydrocarbons",
    reactionType: "Oxidation",
    reagents: ["O3", "Zn/H2O or (CH3)2S"],
    products: ["Aldehydes and/or ketones"],
    conditions: ["Low temperature", "Reductive workup"],
    mechanism: ["Ozone forms ozonide; reductive cleavage gives carbonyl fragments."],
    exceptions: ["Oxidative workup can convert aldehyde fragments to acids."],
    relatedReactions: ["aldehyde-tollens-test", "ketone-iodoform-test"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["ozonolysis", "structure determination"] },
    ncertReference: { class: 11, chapter: "Hydrocarbons", topic: "Ozonolysis" },
  },
  {
    id: "alkene-bromination",
    name: "Bromination of Alkenes",
    category: "Hydrocarbons",
    reactionType: "Addition",
    reagents: ["Br2", "CCl4"],
    products: ["Vicinal dibromide"],
    conditions: ["Inert solvent", "Room temperature"],
    mechanism: ["Bromonium ion formation followed by backside bromide attack."],
    exceptions: ["Conjugated dienes can give 1,2- and 1,4-addition products."],
    relatedReactions: ["alkene-catalytic-hydrogenation"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["test for unsaturation", "vicinal dihalide"] },
    ncertReference: { class: 11, chapter: "Hydrocarbons", topic: "Addition of halogens" },
  },
  {
    id: "benzene-nitration",
    name: "Nitration of Benzene",
    category: "Hydrocarbons",
    reactionType: "Substitution",
    reagents: ["Conc. HNO3", "Conc. H2SO4"],
    products: ["Nitrobenzene"],
    conditions: ["Warm acid mixture"],
    mechanism: ["Electrophilic aromatic substitution by nitronium ion."],
    exceptions: ["Strongly deactivated rings need harsher conditions."],
    relatedReactions: ["friedel-crafts-acylation"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["electrophilic aromatic substitution", "nitration"] },
    ncertReference: { class: 11, chapter: "Hydrocarbons", topic: "Aromatic substitution" },
  },
  {
    id: "friedel-crafts-acylation",
    name: "Friedel-Crafts Acylation",
    category: "Hydrocarbons",
    reactionType: "Substitution",
    reagents: ["Acyl chloride or acid anhydride", "Anhydrous AlCl3"],
    products: ["Aryl ketone"],
    conditions: ["Anhydrous Lewis acid conditions"],
    mechanism: ["Acylium ion attacks benzene followed by deprotonation."],
    exceptions: ["Strongly deactivated rings do not undergo Friedel-Crafts acylation."],
    relatedReactions: ["benzene-nitration", "ketone-clemmensen-reduction"],
    examRelevance: { exams: ["JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["Friedel-Crafts", "acylation"] },
    ncertReference: { class: 11, chapter: "Hydrocarbons", topic: "Friedel-Crafts reactions" },
  },
  {
    id: "wurtz-reaction",
    name: "Wurtz Reaction",
    category: "Haloalkanes",
    reactionType: "Coupling",
    reagents: ["Alkyl halide", "Na", "Dry ether"],
    products: ["Higher alkane"],
    conditions: ["Anhydrous dry ether"],
    mechanism: ["Sodium-mediated coupling of alkyl halides through radical/organosodium pathways."],
    exceptions: ["Best for symmetrical alkanes; mixed halides give product mixtures."],
    relatedReactions: ["wurtz-fittig-reaction", "grignard-reagent-formation"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["Wurtz reaction", "alkane preparation"] },
    ncertReference: { class: 12, chapter: "Haloalkanes and Haloarenes", topic: "Reactions with metals" },
  },
  {
    id: "wurtz-fittig-reaction",
    name: "Wurtz-Fittig Reaction",
    category: "Haloalkanes",
    reactionType: "Coupling",
    reagents: ["Aryl halide", "Alkyl halide", "Na", "Dry ether"],
    products: ["Alkyl arene"],
    conditions: ["Anhydrous dry ether"],
    mechanism: ["Sodium-mediated cross-coupling of aryl and alkyl halides."],
    exceptions: ["Competing Wurtz and Fittig couplings can lower selectivity."],
    relatedReactions: ["wurtz-reaction"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["Wurtz-Fittig", "haloarenes"] },
    ncertReference: { class: 12, chapter: "Haloalkanes and Haloarenes", topic: "Reactions with metals" },
  },
  {
    id: "finkelstein-reaction",
    name: "Finkelstein Reaction",
    category: "Haloalkanes",
    reactionType: "Substitution",
    reagents: ["Alkyl chloride or bromide", "NaI", "Acetone"],
    products: ["Alkyl iodide"],
    conditions: ["Dry acetone"],
    mechanism: ["SN2 halide exchange driven by precipitation of NaCl or NaBr."],
    exceptions: ["Tertiary halides do not undergo efficient SN2 exchange."],
    relatedReactions: ["haloalkane-sn2-hydrolysis", "swarts-reaction"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["Finkelstein", "halogen exchange"] },
    ncertReference: { class: 12, chapter: "Haloalkanes and Haloarenes", topic: "Nucleophilic substitution" },
  },
  {
    id: "swarts-reaction",
    name: "Swarts Reaction",
    category: "Haloalkanes",
    reactionType: "Substitution",
    reagents: ["Alkyl chloride or bromide", "AgF, Hg2F2, CoF2, or SbF3"],
    products: ["Alkyl fluoride"],
    conditions: ["Halogen exchange conditions"],
    mechanism: ["Metal fluoride supplies fluoride for halogen exchange."],
    exceptions: ["Competing elimination can occur with suitable secondary/tertiary substrates."],
    relatedReactions: ["finkelstein-reaction"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "medium", pyqTags: ["Swarts reaction", "alkyl fluoride"] },
    ncertReference: { class: 12, chapter: "Haloalkanes and Haloarenes", topic: "Preparation of alkyl halides" },
  },
  {
    id: "haloalkane-sn2-hydrolysis",
    name: "SN2 Hydrolysis of Primary Alkyl Halides",
    category: "Haloalkanes",
    reactionType: "Substitution",
    reagents: ["Primary alkyl halide", "Aqueous KOH or NaOH"],
    products: ["Alcohol"],
    conditions: ["Aqueous medium", "Primary substrate preferred"],
    mechanism: ["One-step backside attack by hydroxide with leaving group departure."],
    exceptions: ["Tertiary halides favor SN1 or elimination instead of SN2."],
    relatedReactions: ["haloalkane-sn1-hydrolysis", "alcohol-lucas-test"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["SN2", "Walden inversion"] },
    ncertReference: { class: 12, chapter: "Haloalkanes and Haloarenes", topic: "Nucleophilic substitution" },
  },
  {
    id: "haloalkane-sn1-hydrolysis",
    name: "SN1 Hydrolysis of Tertiary Alkyl Halides",
    category: "Haloalkanes",
    reactionType: "Substitution",
    reagents: ["Tertiary alkyl halide", "Water or aqueous base"],
    products: ["Tertiary alcohol"],
    conditions: ["Polar protic solvent", "Stable carbocation substrate"],
    mechanism: ["Ionization to carbocation, nucleophile attack, then deprotonation."],
    exceptions: ["Primary halides do not form stable carbocations under normal SN1 conditions."],
    relatedReactions: ["haloalkane-sn2-hydrolysis", "alcohol-lucas-test"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["SN1", "racemization", "carbocation"] },
    ncertReference: { class: 12, chapter: "Haloalkanes and Haloarenes", topic: "Nucleophilic substitution" },
  },
  {
    id: "haloalkane-dehydrohalogenation",
    name: "Dehydrohalogenation of Alkyl Halides",
    category: "Haloalkanes",
    reactionType: "Elimination",
    reagents: ["Alkyl halide", "Alcoholic KOH"],
    products: ["Alkene"],
    conditions: ["Heat", "Alcoholic base"],
    mechanism: ["Base removes beta-H while halide leaves, commonly E2."],
    exceptions: ["Bulky bases can favor Hofmann product over Saytzeff product."],
    relatedReactions: ["alkene-hx-markovnikov-addition"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["elimination", "Saytzeff rule"] },
    ncertReference: { class: 12, chapter: "Haloalkanes and Haloarenes", topic: "Elimination reactions" },
  },
  {
    id: "grignard-reagent-formation",
    name: "Formation of Grignard Reagents",
    category: "Haloalkanes",
    reactionType: "Preparation",
    reagents: ["Alkyl or aryl halide", "Mg", "Dry ether"],
    products: ["Organomagnesium halide"],
    conditions: ["Absolutely dry ether"],
    mechanism: ["Magnesium inserts into the carbon-halogen bond."],
    exceptions: ["Moisture destroys Grignard reagents by protonation."],
    relatedReactions: ["ketone-grignard-addition", "wurtz-reaction"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["Grignard reagent", "dry ether"] },
    ncertReference: { class: 12, chapter: "Haloalkanes and Haloarenes", topic: "Reactions with metals" },
  },
  {
    id: "alcohol-lucas-test",
    name: "Lucas Test for Alcohols",
    category: "Alcohols",
    reactionType: "Test",
    reagents: ["Conc. HCl", "Anhydrous ZnCl2"],
    products: ["Alkyl chloride", "Turbidity"],
    conditions: ["Room temperature"],
    mechanism: ["ZnCl2 activates -OH; chloride substitution gives insoluble alkyl chloride."],
    exceptions: ["Aryl alcohols such as phenol do not give the usual Lucas test."],
    relatedReactions: ["haloalkane-sn1-hydrolysis", "haloalkane-sn2-hydrolysis"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["Lucas test", "alcohol classification"] },
    ncertReference: { class: 12, chapter: "Alcohols, Phenols and Ethers", topic: "Reactions of alcohols" },
  },
  {
    id: "alcohol-sodium-reaction",
    name: "Reaction of Alcohols with Sodium",
    category: "Alcohols",
    reactionType: "Substitution",
    reagents: ["Alcohol", "Na metal"],
    products: ["Sodium alkoxide", "H2 gas"],
    conditions: ["Dry alcohol"],
    mechanism: ["Acidic O-H proton is replaced by sodium with hydrogen evolution."],
    exceptions: ["Phenols react faster than most aliphatic alcohols because phenoxide is resonance-stabilized."],
    relatedReactions: ["williamson-ether-synthesis"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "medium", pyqTags: ["acidic hydrogen", "alkoxide"] },
    ncertReference: { class: 12, chapter: "Alcohols, Phenols and Ethers", topic: "Acidity of alcohols and phenols" },
  },
  {
    id: "fischer-esterification",
    name: "Fischer Esterification",
    category: "Alcohols",
    reactionType: "Condensation",
    reagents: ["Alcohol", "Carboxylic acid", "Conc. H2SO4"],
    products: ["Ester", "Water"],
    conditions: ["Acid catalyst", "Reflux"],
    mechanism: ["Acid-catalyzed nucleophilic acyl substitution followed by water loss."],
    exceptions: ["Equilibrium is driven forward by removing water or using excess reactant."],
    relatedReactions: ["carboxylic-acid-acid-chloride-formation"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["esterification", "acid catalyst"] },
    ncertReference: { class: 12, chapter: "Alcohols, Phenols and Ethers", topic: "Esterification" },
  },
  {
    id: "alcohol-dehydration",
    name: "Dehydration of Alcohols",
    category: "Alcohols",
    reactionType: "Elimination",
    reagents: ["Alcohol", "Conc. H2SO4 or Al2O3"],
    products: ["Alkene"],
    conditions: ["Heat"],
    mechanism: ["Acid protonates -OH; water leaves and beta-H elimination gives alkene."],
    exceptions: ["Carbocation rearrangement can occur in acid-catalyzed dehydration."],
    relatedReactions: ["haloalkane-dehydrohalogenation"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["dehydration", "alkene preparation"] },
    ncertReference: { class: 12, chapter: "Alcohols, Phenols and Ethers", topic: "Dehydration of alcohols" },
  },
  {
    id: "alcohol-pcc-oxidation",
    name: "PCC Oxidation of Primary Alcohols",
    category: "Alcohols",
    reactionType: "Oxidation",
    reagents: ["Primary alcohol", "PCC"],
    products: ["Aldehyde"],
    conditions: ["Anhydrous CH2Cl2"],
    mechanism: ["Chromate ester formation followed by elimination to aldehyde."],
    exceptions: ["PCC normally stops at aldehyde under anhydrous conditions."],
    relatedReactions: ["aldehyde-tollens-test", "alcohol-dichromate-oxidation"],
    examRelevance: { exams: ["JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["PCC", "selective oxidation"] },
    ncertReference: { class: 12, chapter: "Alcohols, Phenols and Ethers", topic: "Oxidation of alcohols" },
  },
  {
    id: "alcohol-dichromate-oxidation",
    name: "Dichromate Oxidation of Primary Alcohols",
    category: "Alcohols",
    reactionType: "Oxidation",
    reagents: ["Primary alcohol", "K2Cr2O7/H2SO4"],
    products: ["Carboxylic acid"],
    conditions: ["Acidic aqueous oxidant", "Heating"],
    mechanism: ["Alcohol oxidizes through aldehyde to acid in aqueous oxidizing conditions."],
    exceptions: ["Aldehyde intermediate is usually not isolated under strong aqueous oxidation."],
    relatedReactions: ["alcohol-pcc-oxidation", "carboxylic-acid-lialh4-reduction"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["oxidation of alcohols", "dichromate"] },
    ncertReference: { class: 12, chapter: "Alcohols, Phenols and Ethers", topic: "Oxidation of alcohols" },
  },
  {
    id: "secondary-alcohol-oxidation",
    name: "Oxidation of Secondary Alcohols",
    category: "Alcohols",
    reactionType: "Oxidation",
    reagents: ["Secondary alcohol", "K2Cr2O7/H2SO4 or PCC"],
    products: ["Ketone"],
    conditions: ["Controlled oxidation"],
    mechanism: ["Chromate ester formation followed by elimination to ketone."],
    exceptions: ["Ketones resist mild further oxidation."],
    relatedReactions: ["ketone-iodoform-test", "ketone-clemmensen-reduction"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["secondary alcohol oxidation", "ketone"] },
    ncertReference: { class: 12, chapter: "Alcohols, Phenols and Ethers", topic: "Oxidation of alcohols" },
  },
  {
    id: "williamson-ether-synthesis",
    name: "Williamson Ether Synthesis",
    category: "Alcohols",
    reactionType: "Substitution",
    reagents: ["Sodium alkoxide", "Primary alkyl halide"],
    products: ["Ether"],
    conditions: ["Dry conditions", "Primary halide preferred"],
    mechanism: ["Alkoxide performs SN2 attack on alkyl halide."],
    exceptions: ["Tertiary halides give elimination instead of ether by SN2."],
    relatedReactions: ["haloalkane-sn2-hydrolysis"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["Williamson synthesis", "ether"] },
    ncertReference: { class: 12, chapter: "Alcohols, Phenols and Ethers", topic: "Preparation of ethers" },
  },
  {
    id: "aldehyde-tollens-test",
    name: "Tollens' Test",
    category: "Aldehydes",
    reactionType: "Test",
    reagents: ["Aldehyde", "Ammoniacal AgNO3"],
    products: ["Carboxylate", "Silver mirror"],
    conditions: ["Mild alkaline medium"],
    mechanism: ["Aldehyde reduces Ag(I) to metallic silver while being oxidized."],
    exceptions: ["Most simple ketones do not give Tollens' test."],
    relatedReactions: ["fehlings-test", "alcohol-pcc-oxidation"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["Tollens test", "aldehyde test"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Chemical tests for aldehydes" },
  },
  {
    id: "fehlings-test",
    name: "Fehling's Test",
    category: "Aldehydes",
    reactionType: "Test",
    reagents: ["Aliphatic aldehyde", "Fehling solution"],
    products: ["Carboxylate", "Red Cu2O precipitate"],
    conditions: ["Alkaline medium", "Warm"],
    mechanism: ["Aldehyde reduces Cu(II) to Cu(I) oxide."],
    exceptions: ["Aromatic aldehydes generally do not give Fehling's test."],
    relatedReactions: ["aldehyde-tollens-test"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["Fehling test", "aldehyde identification"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Chemical tests for aldehydes" },
  },
  {
    id: "cannizzaro-reaction",
    name: "Cannizzaro Reaction",
    category: "Aldehydes",
    reactionType: "Redox",
    reagents: ["Aldehyde without alpha-H", "Conc. NaOH or KOH"],
    products: ["Alcohol", "Carboxylate salt"],
    conditions: ["Strong base"],
    mechanism: ["Hydride transfer between two aldehyde molecules after hydroxide addition."],
    exceptions: ["Aldehydes with alpha-H usually prefer aldol reaction."],
    relatedReactions: ["aldol-condensation"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["Cannizzaro", "no alpha hydrogen"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Cannizzaro reaction" },
  },
  {
    id: "aldol-condensation",
    name: "Aldol Condensation",
    category: "Aldehydes",
    reactionType: "Condensation",
    reagents: ["Aldehyde or ketone with alpha-H", "Dilute base"],
    products: ["Beta-hydroxy carbonyl", "Alpha,beta-unsaturated carbonyl on heating"],
    conditions: ["Dilute NaOH or KOH", "Heat for dehydration"],
    mechanism: ["Base forms enolate, enolate adds to carbonyl, then dehydration may occur."],
    exceptions: ["Carbonyl compounds without alpha-H do not self-aldol."],
    relatedReactions: ["cannizzaro-reaction", "ketone-hcn-addition"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["aldol", "alpha hydrogen"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Aldol condensation" },
  },
  {
    id: "rosenmund-reduction",
    name: "Rosenmund Reduction",
    category: "Aldehydes",
    reactionType: "Reduction",
    reagents: ["Acid chloride", "H2", "Pd/BaSO4"],
    products: ["Aldehyde"],
    conditions: ["Poisoned palladium catalyst"],
    mechanism: ["Controlled catalytic hydrogenation of acid chloride to aldehyde."],
    exceptions: ["Formyl chloride is unstable; formaldehyde is not prepared by this route."],
    relatedReactions: ["carboxylic-acid-acid-chloride-formation", "aldehyde-tollens-test"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["Rosenmund reduction", "aldehyde preparation"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Preparation of aldehydes" },
  },
  {
    id: "stephen-reduction",
    name: "Stephen Reduction",
    category: "Aldehydes",
    reactionType: "Reduction",
    reagents: ["Nitrile", "SnCl2", "HCl", "Water"],
    products: ["Aldehyde"],
    conditions: ["Acidic reduction then hydrolysis"],
    mechanism: ["Nitrile is reduced to iminium salt, then hydrolyzed to aldehyde."],
    exceptions: ["Works for nitriles; ketones are not the direct product."],
    relatedReactions: ["rosenmund-reduction"],
    examRelevance: { exams: ["JEE MAIN", "JEE ADVANCED"], priority: "medium", pyqTags: ["Stephen reduction", "nitrile to aldehyde"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Preparation of aldehydes" },
  },
  {
    id: "gattermann-koch-formylation",
    name: "Gattermann-Koch Formylation",
    category: "Aldehydes",
    reactionType: "Substitution",
    reagents: ["Benzene or arene", "CO", "HCl", "AlCl3/CuCl"],
    products: ["Aromatic aldehyde"],
    conditions: ["Anhydrous Lewis acid conditions"],
    mechanism: ["Formyl electrophile substitutes on the aromatic ring."],
    exceptions: ["Not suitable for strongly deactivated aromatic rings."],
    relatedReactions: ["friedel-crafts-acylation", "benzene-nitration"],
    examRelevance: { exams: ["JEE MAIN", "JEE ADVANCED"], priority: "medium", pyqTags: ["Gattermann-Koch", "benzaldehyde"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Preparation of aromatic aldehydes" },
  },
  {
    id: "ketone-iodoform-test",
    name: "Iodoform Test",
    category: "Ketones",
    reactionType: "Test",
    reagents: ["Methyl ketone or ethanol/acetaldehyde", "I2", "NaOH"],
    products: ["CHI3 yellow precipitate", "Carboxylate"],
    conditions: ["Alkaline iodine"],
    mechanism: ["Repeated alpha-iodination followed by cleavage of triiodomethyl carbonyl."],
    exceptions: ["Only compounds containing CH3CO- or oxidizable to CH3CO- respond."],
    relatedReactions: ["secondary-alcohol-oxidation", "aldehyde-tollens-test"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["iodoform", "methyl ketone"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Iodoform reaction" },
  },
  {
    id: "ketone-clemmensen-reduction",
    name: "Clemmensen Reduction",
    category: "Ketones",
    reactionType: "Reduction",
    reagents: ["Aldehyde or ketone", "Zn-Hg", "Conc. HCl"],
    products: ["Alkane"],
    conditions: ["Strongly acidic medium"],
    mechanism: ["Carbonyl group is reduced to methylene under acidic metal conditions."],
    exceptions: ["Acid-sensitive substrates are unsuitable."],
    relatedReactions: ["wolff-kishner-reduction", "friedel-crafts-acylation"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["Clemmensen reduction", "carbonyl to alkane"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Reduction of carbonyl compounds" },
  },
  {
    id: "wolff-kishner-reduction",
    name: "Wolff-Kishner Reduction",
    category: "Ketones",
    reactionType: "Reduction",
    reagents: ["Aldehyde or ketone", "NH2NH2", "KOH"],
    products: ["Alkane", "N2"],
    conditions: ["Strong base", "Heat", "High-boiling solvent"],
    mechanism: ["Hydrazone formation followed by base-promoted nitrogen loss."],
    exceptions: ["Base-sensitive substrates are unsuitable."],
    relatedReactions: ["ketone-clemmensen-reduction", "ketone-oxime-formation"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["Wolff-Kishner", "carbonyl reduction"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Reduction of carbonyl compounds" },
  },
  {
    id: "ketone-grignard-addition",
    name: "Grignard Addition to Carbonyl Compounds",
    category: "Ketones",
    reactionType: "Addition",
    reagents: ["Aldehyde or ketone", "RMgX", "H3O+"],
    products: ["Alcohol"],
    conditions: ["Dry ether then acidic workup"],
    mechanism: ["Carbanion-like R group attacks carbonyl carbon; alkoxide is protonated."],
    exceptions: ["Water, alcohols, and acids destroy Grignard reagents before addition."],
    relatedReactions: ["grignard-reagent-formation", "ketone-hcn-addition"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["Grignard addition", "alcohol synthesis"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Nucleophilic addition reactions" },
  },
  {
    id: "ketone-oxime-formation",
    name: "Oxime Formation",
    category: "Ketones",
    reactionType: "Condensation",
    reagents: ["Aldehyde or ketone", "NH2OH"],
    products: ["Oxime", "Water"],
    conditions: ["Mild acidic or buffered medium"],
    mechanism: ["Nucleophilic addition to carbonyl followed by dehydration."],
    exceptions: ["Strong acid can protonate the nucleophile and slow the reaction."],
    relatedReactions: ["ketone-hcn-addition"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "medium", pyqTags: ["oxime", "carbonyl derivatives"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Addition of ammonia derivatives" },
  },
  {
    id: "ketone-hcn-addition",
    name: "Cyanohydrin Formation",
    category: "Ketones",
    reactionType: "Addition",
    reagents: ["Aldehyde or ketone", "HCN", "Base catalyst"],
    products: ["Cyanohydrin"],
    conditions: ["Controlled pH"],
    mechanism: ["CN- attacks carbonyl carbon; alkoxide is protonated."],
    exceptions: ["Sterically hindered ketones react more slowly."],
    relatedReactions: ["ketone-grignard-addition", "aldol-condensation"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["cyanohydrin", "nucleophilic addition"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Nucleophilic addition reactions" },
  },
  {
    id: "hvz-reaction",
    name: "Hell-Volhard-Zelinsky Reaction",
    category: "Carboxylic Acids",
    reactionType: "Substitution",
    reagents: ["Carboxylic acid with alpha-H", "Br2", "Red P"],
    products: ["Alpha-bromocarboxylic acid"],
    conditions: ["Phosphorus halide formation in situ"],
    mechanism: ["Acid is converted to acyl halide; enol bromination occurs at alpha carbon."],
    exceptions: ["Carboxylic acids without alpha-H do not undergo HVZ."],
    relatedReactions: ["carboxylic-acid-acid-chloride-formation"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["HVZ", "alpha halogenation"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Reactions of carboxylic acids" },
  },
  {
    id: "soda-lime-decarboxylation",
    name: "Soda-Lime Decarboxylation",
    category: "Carboxylic Acids",
    reactionType: "Preparation",
    reagents: ["Sodium carboxylate", "NaOH/CaO"],
    products: ["Alkane with one less carbon", "Na2CO3"],
    conditions: ["Heat with soda lime"],
    mechanism: ["Decarboxylation removes CO2 as carbonate under strongly basic heating."],
    exceptions: ["Product has one carbon fewer than the carboxylate salt."],
    relatedReactions: ["kolbe-electrolysis"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["decarboxylation", "soda lime"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Decarboxylation" },
  },
  {
    id: "kolbe-electrolysis",
    name: "Kolbe Electrolysis",
    category: "Carboxylic Acids",
    reactionType: "Coupling",
    reagents: ["Aqueous sodium or potassium carboxylate", "Electrolysis"],
    products: ["Symmetrical alkane", "CO2"],
    conditions: ["Electrolysis of concentrated carboxylate solution"],
    mechanism: ["Carboxylate radical decarboxylates; alkyl radicals couple at anode."],
    exceptions: ["Methanoate gives different oxidation behavior and no alkyl radical coupling."],
    relatedReactions: ["soda-lime-decarboxylation", "wurtz-reaction"],
    examRelevance: { exams: ["JEE MAIN", "JEE ADVANCED"], priority: "medium", pyqTags: ["Kolbe electrolysis", "radical coupling"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Decarboxylation reactions" },
  },
  {
    id: "carboxylic-acid-acid-chloride-formation",
    name: "Formation of Acid Chlorides",
    category: "Carboxylic Acids",
    reactionType: "Substitution",
    reagents: ["Carboxylic acid", "SOCl2, PCl5, or PCl3"],
    products: ["Acid chloride"],
    conditions: ["Dry conditions preferred"],
    mechanism: ["Nucleophilic acyl substitution replaces -OH by chloride."],
    exceptions: ["SOCl2 is preferred because gaseous byproducts escape."],
    relatedReactions: ["rosenmund-reduction", "fischer-esterification"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["acid chloride", "SOCl2"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Reactions of carboxylic acids" },
  },
  {
    id: "carboxylic-acid-lialh4-reduction",
    name: "Reduction of Carboxylic Acids with LiAlH4",
    category: "Carboxylic Acids",
    reactionType: "Reduction",
    reagents: ["Carboxylic acid", "LiAlH4", "H3O+"],
    products: ["Primary alcohol"],
    conditions: ["Dry ether then acidic workup"],
    mechanism: ["Hydride reduction of carboxyl derivative followed by workup."],
    exceptions: ["NaBH4 does not normally reduce isolated carboxylic acids."],
    relatedReactions: ["alcohol-dichromate-oxidation"],
    examRelevance: { exams: ["JEE MAIN", "JEE ADVANCED"], priority: "medium", pyqTags: ["LiAlH4", "acid reduction"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Reduction of carboxylic acids" },
  },
  {
    id: "carboxylic-acid-bicarbonate-test",
    name: "Sodium Bicarbonate Test for Carboxylic Acids",
    category: "Carboxylic Acids",
    reactionType: "Test",
    reagents: ["Carboxylic acid", "NaHCO3"],
    products: ["Carboxylate salt", "CO2 effervescence", "Water"],
    conditions: ["Aqueous sodium bicarbonate"],
    mechanism: ["Acid-base reaction releases carbon dioxide from bicarbonate."],
    exceptions: ["Phenols are usually too weakly acidic to give brisk CO2 with NaHCO3."],
    relatedReactions: ["fischer-esterification"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["bicarbonate test", "carboxylic acid"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Acidity of carboxylic acids" },
  },
  {
    id: "carbylamine-reaction",
    name: "Carbylamine Reaction",
    category: "Amines",
    reactionType: "Test",
    reagents: ["Primary amine", "CHCl3", "Alcoholic KOH"],
    products: ["Isocyanide"],
    conditions: ["Heat with alcoholic KOH"],
    mechanism: ["Primary amine reacts with dichlorocarbene generated from chloroform and base."],
    exceptions: ["Secondary and tertiary amines do not give the carbylamine test."],
    relatedReactions: ["gabriel-phthalimide-synthesis", "hofmann-bromamide-degradation"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["carbylamine", "primary amine test"] },
    ncertReference: { class: 12, chapter: "Amines", topic: "Chemical tests for amines" },
  },
  {
    id: "gabriel-phthalimide-synthesis",
    name: "Gabriel Phthalimide Synthesis",
    category: "Amines",
    reactionType: "Preparation",
    reagents: ["Phthalimide", "KOH", "Primary alkyl halide", "Hydrolysis"],
    products: ["Primary aliphatic amine"],
    conditions: ["SN2 alkylation then hydrolysis"],
    mechanism: ["Potassium phthalimide displaces halide; hydrolysis releases primary amine."],
    exceptions: ["Aryl halides do not undergo this SN2 step efficiently."],
    relatedReactions: ["carbylamine-reaction", "hofmann-bromamide-degradation"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["Gabriel synthesis", "primary amine"] },
    ncertReference: { class: 12, chapter: "Amines", topic: "Preparation of amines" },
  },
  {
    id: "hofmann-bromamide-degradation",
    name: "Hofmann Bromamide Degradation",
    category: "Amines",
    reactionType: "Preparation",
    reagents: ["Amide", "Br2", "NaOH"],
    products: ["Primary amine with one less carbon"],
    conditions: ["Alkaline bromine"],
    mechanism: ["N-bromoamide rearranges to isocyanate; hydrolysis gives amine."],
    exceptions: ["Product loses the carbonyl carbon of the starting amide."],
    relatedReactions: ["gabriel-phthalimide-synthesis", "carbylamine-reaction"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["Hofmann degradation", "amide to amine"] },
    ncertReference: { class: 12, chapter: "Amines", topic: "Preparation of amines" },
  },
  {
    id: "aniline-diazotization",
    name: "Diazotization of Aniline",
    category: "Amines",
    reactionType: "Preparation",
    reagents: ["Aniline", "NaNO2", "HCl"],
    products: ["Benzenediazonium chloride"],
    conditions: ["273-278 K"],
    mechanism: ["Nitrous acid generates nitrosonium ion; aniline forms diazonium salt."],
    exceptions: ["Arenediazonium salts are stable only at low temperature in solution."],
    relatedReactions: ["sandmeyer-reaction", "azo-coupling-reaction"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["diazotization", "diazonium salt"] },
    ncertReference: { class: 12, chapter: "Amines", topic: "Diazonium salts" },
  },
  {
    id: "sandmeyer-reaction",
    name: "Sandmeyer Reaction",
    category: "Amines",
    reactionType: "Substitution",
    reagents: ["Arenediazonium salt", "CuCl, CuBr, or CuCN"],
    products: ["Aryl chloride, bromide, or nitrile"],
    conditions: ["Copper(I) salt"],
    mechanism: ["Diazonium group is replaced through copper-mediated radical substitution."],
    exceptions: ["Fluorination is done by Balz-Schiemann, not Sandmeyer."],
    relatedReactions: ["aniline-diazotization", "azo-coupling-reaction"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["Sandmeyer", "diazonium substitution"] },
    ncertReference: { class: 12, chapter: "Amines", topic: "Reactions of diazonium salts" },
  },
  {
    id: "azo-coupling-reaction",
    name: "Azo Coupling Reaction",
    category: "Amines",
    reactionType: "Coupling",
    reagents: ["Arenediazonium salt", "Phenol or aniline"],
    products: ["Azo dye"],
    conditions: ["Mild alkaline medium for phenol", "Low temperature"],
    mechanism: ["Electrophilic coupling at activated aromatic ring forms -N=N- linkage."],
    exceptions: ["Strongly deactivated rings do not couple readily."],
    relatedReactions: ["aniline-diazotization", "sandmeyer-reaction"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["azo coupling", "diazonium"] },
    ncertReference: { class: 12, chapter: "Amines", topic: "Coupling reactions of diazonium salts" },
  },
  {
    id: "amine-acylation",
    name: "Acylation of Amines",
    category: "Amines",
    reactionType: "Substitution",
    reagents: ["Amine", "Acid chloride or acid anhydride"],
    products: ["Amide"],
    conditions: ["Base or pyridine often used"],
    mechanism: ["Amine attacks acyl carbon; leaving group departs after proton transfer."],
    exceptions: ["Tertiary amines lack N-H and do not form neutral amides by simple acylation."],
    relatedReactions: ["hofmann-bromamide-degradation", "carboxylic-acid-acid-chloride-formation"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "medium", pyqTags: ["acylation", "amine protection"] },
    ncertReference: { class: 12, chapter: "Amines", topic: "Chemical reactions of amines" },
  },
  {
    id: "alkane-free-radical-halogenation",
    name: "Free Radical Halogenation of Alkanes",
    category: "Hydrocarbons",
    reactionType: "Substitution",
    reagents: ["Alkane", "Cl2 or Br2"],
    products: ["Haloalkane"],
    conditions: ["UV light or heat"],
    mechanism: ["Initiation forms halogen radicals; propagation abstracts H and substitutes halogen."],
    exceptions: ["Mixtures form when multiple nonequivalent hydrogens are present."],
    relatedReactions: ["wurtz-reaction", "haloalkane-dehydrohalogenation"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["free radical substitution", "alkanes"] },
    ncertReference: { class: 11, chapter: "Hydrocarbons", topic: "Substitution reactions of alkanes" },
  },
  {
    id: "kolbe-electrolysis-alkane",
    name: "Kolbe Electrolysis of Carboxylate Salts",
    category: "Hydrocarbons",
    reactionType: "Preparation",
    reagents: ["Sodium or potassium carboxylate", "Electrolysis"],
    products: ["Symmetrical alkane", "CO2"],
    conditions: ["Aqueous solution", "Anodic oxidation"],
    mechanism: ["Carboxylate radicals decarboxylate and couple to form R-R."],
    exceptions: ["Best for symmetrical alkane synthesis from one carboxylate salt."],
    relatedReactions: ["wurtz-reaction", "soda-lime-decarboxylation"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "medium", pyqTags: ["Kolbe electrolysis", "alkane preparation"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Decarboxylation and electrolysis" },
  },
  {
    id: "alkyne-lindlar-reduction",
    name: "Partial Reduction of Alkynes with Lindlar Catalyst",
    category: "Hydrocarbons",
    reactionType: "Reduction",
    reagents: ["Alkyne", "H2", "Lindlar catalyst"],
    products: ["cis-Alkene"],
    conditions: ["Poisoned Pd catalyst"],
    mechanism: ["Syn hydrogenation stops at alkene because catalyst is poisoned."],
    exceptions: ["Does not normally reduce further to alkane under Lindlar conditions."],
    relatedReactions: ["alkyne-birch-reduction"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["Lindlar", "cis alkene"] },
    ncertReference: { class: 11, chapter: "Hydrocarbons", topic: "Alkynes: addition reactions" },
  },
  {
    id: "alkyne-birch-reduction",
    name: "Dissolving Metal Reduction of Alkynes",
    category: "Hydrocarbons",
    reactionType: "Reduction",
    reagents: ["Alkyne", "Na or Li", "Liquid NH3"],
    products: ["trans-Alkene"],
    conditions: ["Low temperature", "Liquid ammonia"],
    mechanism: ["Electron-proton-electron-proton sequence gives anti addition overall."],
    exceptions: ["Terminal alkynes can also be deprotonated by strong base conditions."],
    relatedReactions: ["alkyne-lindlar-reduction"],
    examRelevance: { exams: ["JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["dissolving metal reduction", "trans alkene"] },
    ncertReference: { class: 11, chapter: "Hydrocarbons", topic: "Alkynes: addition reactions" },
  },
  {
    id: "terminal-alkyne-silver-salt",
    name: "Silver Salt Test for Terminal Alkynes",
    category: "Hydrocarbons",
    reactionType: "Test",
    reagents: ["Terminal alkyne", "Ammoniacal AgNO3"],
    products: ["Silver acetylide precipitate"],
    conditions: ["Ammoniacal solution"],
    mechanism: ["Acidic terminal hydrogen is replaced by Ag+ to form insoluble acetylide."],
    exceptions: ["Internal alkynes do not give this test."],
    relatedReactions: ["terminal-alkyne-copper-salt"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["terminal alkyne test", "acidic hydrogen"] },
    ncertReference: { class: 11, chapter: "Hydrocarbons", topic: "Acidity of alkynes" },
  },
  {
    id: "terminal-alkyne-copper-salt",
    name: "Copper Salt Test for Terminal Alkynes",
    category: "Hydrocarbons",
    reactionType: "Test",
    reagents: ["Terminal alkyne", "Ammoniacal Cu2Cl2"],
    products: ["Copper acetylide precipitate"],
    conditions: ["Ammoniacal cuprous chloride"],
    mechanism: ["Terminal alkyne forms insoluble copper acetylide."],
    exceptions: ["Internal alkynes lack acidic terminal hydrogen."],
    relatedReactions: ["terminal-alkyne-silver-salt"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "medium", pyqTags: ["terminal alkyne", "cuprous chloride"] },
    ncertReference: { class: 11, chapter: "Hydrocarbons", topic: "Acidity of alkynes" },
  },
  {
    id: "benzene-sulfonation",
    name: "Sulfonation of Benzene",
    category: "Hydrocarbons",
    reactionType: "Substitution",
    reagents: ["Fuming H2SO4 or SO3/H2SO4"],
    products: ["Benzenesulfonic acid"],
    conditions: ["Heat with fuming sulfuric acid"],
    mechanism: ["Electrophilic aromatic substitution by SO3 or protonated SO3."],
    exceptions: ["Sulfonation is reversible under hot dilute acid conditions."],
    relatedReactions: ["benzene-nitration"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "medium", pyqTags: ["sulfonation", "EAS"] },
    ncertReference: { class: 11, chapter: "Hydrocarbons", topic: "Aromatic substitution" },
  },
  {
    id: "benzene-halogenation",
    name: "Halogenation of Benzene",
    category: "Hydrocarbons",
    reactionType: "Substitution",
    reagents: ["Cl2/FeCl3 or Br2/FeBr3"],
    products: ["Halobenzene"],
    conditions: ["Anhydrous Lewis acid"],
    mechanism: ["Lewis acid generates stronger electrophile; benzene undergoes electrophilic substitution."],
    exceptions: ["Without Lewis acid, benzene does not readily react with chlorine or bromine in dark."],
    relatedReactions: ["benzene-nitration", "friedel-crafts-acylation"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["halogenation of benzene", "EAS"] },
    ncertReference: { class: 11, chapter: "Hydrocarbons", topic: "Aromatic substitution" },
  },
  {
    id: "friedel-crafts-alkylation",
    name: "Friedel-Crafts Alkylation",
    category: "Hydrocarbons",
    reactionType: "Substitution",
    reagents: ["Alkyl halide", "Anhydrous AlCl3"],
    products: ["Alkylbenzene"],
    conditions: ["Anhydrous Lewis acid"],
    mechanism: ["Carbocation-like electrophile attacks aromatic ring followed by deprotonation."],
    exceptions: ["Polyalkylation and carbocation rearrangement can occur."],
    relatedReactions: ["friedel-crafts-acylation"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["Friedel-Crafts alkylation", "rearrangement"] },
    ncertReference: { class: 11, chapter: "Hydrocarbons", topic: "Friedel-Crafts reactions" },
  },
  {
    id: "toluene-side-chain-halogenation",
    name: "Benzylic Halogenation of Toluene",
    category: "Hydrocarbons",
    reactionType: "Substitution",
    reagents: ["Toluene", "Cl2 or Br2"],
    products: ["Benzyl halide"],
    conditions: ["hv or heat"],
    mechanism: ["Radical substitution occurs at benzylic C-H due to resonance-stabilised benzyl radical."],
    exceptions: ["Ring halogenation occurs with Lewis acid instead of light."],
    relatedReactions: ["benzene-halogenation", "toluene-side-chain-oxidation"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["benzylic substitution", "toluene"] },
    ncertReference: { class: 11, chapter: "Hydrocarbons", topic: "Aromatic hydrocarbons" },
  },
  {
    id: "toluene-side-chain-oxidation",
    name: "Side Chain Oxidation of Alkylbenzenes",
    category: "Hydrocarbons",
    reactionType: "Oxidation",
    reagents: ["Alkylbenzene", "Hot alkaline KMnO4"],
    products: ["Benzoic acid"],
    conditions: ["Benzylic hydrogen required", "Heat"],
    mechanism: ["Benzylic carbon is oxidised completely to carboxyl group."],
    exceptions: ["Tert-butylbenzene lacks benzylic hydrogen and resists this oxidation."],
    relatedReactions: ["benzene-halogenation"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["side chain oxidation", "benzoic acid"] },
    ncertReference: { class: 11, chapter: "Hydrocarbons", topic: "Aromatic hydrocarbons" },
  },
  {
    id: "haloalkane-cyanide-substitution",
    name: "Cyanide Substitution of Alkyl Halides",
    category: "Haloalkanes",
    reactionType: "Substitution",
    reagents: ["Alkyl halide", "Alcoholic KCN"],
    products: ["Alkyl cyanide"],
    conditions: ["Alcoholic solution", "Primary substrate favoured"],
    mechanism: ["CN- attacks through carbon in SN2 substitution."],
    exceptions: ["AgCN favours isocyanide formation through nitrogen."],
    relatedReactions: ["haloalkane-isocyanide-substitution", "amine-carbylamine-reaction"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["KCN", "alkyl cyanide"] },
    ncertReference: { class: 12, chapter: "Haloalkanes and Haloarenes", topic: "Nucleophilic substitution" },
  },
  {
    id: "haloalkane-isocyanide-substitution",
    name: "Isocyanide Formation from Alkyl Halides",
    category: "Haloalkanes",
    reactionType: "Substitution",
    reagents: ["Alkyl halide", "AgCN"],
    products: ["Alkyl isocyanide"],
    conditions: ["Silver cyanide"],
    mechanism: ["Covalent AgCN presents nitrogen end for substitution."],
    exceptions: ["KCN usually gives alkyl cyanide because cyanide attacks through carbon."],
    relatedReactions: ["haloalkane-cyanide-substitution"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["AgCN", "isocyanide"] },
    ncertReference: { class: 12, chapter: "Haloalkanes and Haloarenes", topic: "Nucleophilic substitution" },
  },
  {
    id: "alcohol-dehydration-alkene",
    name: "Dehydration of Alcohols to Alkenes",
    category: "Alcohols",
    reactionType: "Elimination",
    reagents: ["Alcohol", "Conc. H2SO4 or Al2O3"],
    products: ["Alkene"],
    conditions: ["Heat"],
    mechanism: ["Acid protonates OH; water leaves and beta-H is removed to form alkene."],
    exceptions: ["Carbocation rearrangement may occur in acid-catalysed dehydration."],
    relatedReactions: ["alkene-hx-markovnikov-addition"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["dehydration", "Saytzeff"] },
    ncertReference: { class: 12, chapter: "Alcohols, Phenols and Ethers", topic: "Reactions of alcohols" },
  },
  {
    id: "phenol-bromination",
    name: "Bromination of Phenol",
    category: "Alcohols",
    reactionType: "Substitution",
    reagents: ["Phenol", "Bromine water"],
    products: ["2,4,6-Tribromophenol"],
    conditions: ["Aqueous bromine", "Room temperature"],
    mechanism: ["Highly activated phenoxide/phenol ring undergoes electrophilic substitution at ortho and para positions."],
    exceptions: ["In non-polar solvent, monobromination can be controlled."],
    relatedReactions: ["benzene-halogenation"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["phenol test", "tribromophenol"] },
    ncertReference: { class: 12, chapter: "Alcohols, Phenols and Ethers", topic: "Chemical reactions of phenols" },
  },
  {
    id: "kolbe-schmitt-reaction",
    name: "Kolbe-Schmitt Reaction",
    category: "Alcohols",
    reactionType: "Substitution",
    reagents: ["Sodium phenoxide", "CO2", "H+"],
    products: ["Salicylic acid"],
    conditions: ["Pressure", "Heat", "Acid workup"],
    mechanism: ["Phenoxide undergoes ortho carboxylation with carbon dioxide followed by protonation."],
    exceptions: ["Ortho product dominates due to chelation and directing effect."],
    relatedReactions: ["reimer-tiemann-reaction"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "medium", pyqTags: ["Kolbe reaction", "salicylic acid"] },
    ncertReference: { class: 12, chapter: "Alcohols, Phenols and Ethers", topic: "Chemical reactions of phenols" },
  },
  {
    id: "reimer-tiemann-reaction",
    name: "Reimer-Tiemann Reaction",
    category: "Alcohols",
    reactionType: "Substitution",
    reagents: ["Phenol", "CHCl3", "NaOH"],
    products: ["Salicylaldehyde"],
    conditions: ["Alkaline medium", "Acid workup"],
    mechanism: ["Dichlorocarbene electrophile formylates activated phenoxide mainly at ortho position."],
    exceptions: ["Para product may form in smaller amount."],
    relatedReactions: ["kolbe-schmitt-reaction"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["Reimer-Tiemann", "salicylaldehyde"] },
    ncertReference: { class: 12, chapter: "Alcohols, Phenols and Ethers", topic: "Chemical reactions of phenols" },
  },
  {
    id: "hell-volhard-zelinsky",
    name: "Hell-Volhard-Zelinsky Reaction",
    category: "Carboxylic Acids",
    reactionType: "Substitution",
    reagents: ["Carboxylic acid", "Br2", "Red phosphorus"],
    products: ["Alpha-bromo carboxylic acid"],
    conditions: ["Carboxylic acid with alpha hydrogen"],
    mechanism: ["Acid bromide enolises and brominates at alpha carbon; hydrolysis restores acid."],
    exceptions: ["Carboxylic acids without alpha hydrogen do not undergo HVZ."],
    relatedReactions: ["carboxylic-acid-acid-chloride-formation"],
    examRelevance: { exams: ["NEET", "JEE MAIN", "JEE ADVANCED"], priority: "high", pyqTags: ["HVZ", "alpha halogenation"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Reactions involving alpha hydrogen" },
  },
  {
    id: "esterification-fischer",
    name: "Fischer Esterification",
    category: "Carboxylic Acids",
    reactionType: "Condensation",
    reagents: ["Carboxylic acid", "Alcohol", "Conc. H2SO4"],
    products: ["Ester", "Water"],
    conditions: ["Acid catalyst", "Heat"],
    mechanism: ["Protonated acid undergoes nucleophilic acyl substitution by alcohol."],
    exceptions: ["Equilibrium is driven forward by removing water or using excess alcohol."],
    relatedReactions: ["ester-hydrolysis-acidic", "ester-hydrolysis-basic"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["esterification", "carboxylic acid"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Carboxylic acid derivatives" },
  },
  {
    id: "ester-hydrolysis-acidic",
    name: "Acidic Hydrolysis of Esters",
    category: "Carboxylic Acids",
    reactionType: "Substitution",
    reagents: ["Ester", "Dilute acid", "Water"],
    products: ["Carboxylic acid", "Alcohol"],
    conditions: ["Heat", "Acid catalyst"],
    mechanism: ["Acid-catalysed nucleophilic acyl substitution reverses esterification."],
    exceptions: ["Reaction is reversible under acidic conditions."],
    relatedReactions: ["esterification-fischer", "ester-hydrolysis-basic"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "medium", pyqTags: ["ester hydrolysis", "acidic"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Carboxylic acid derivatives" },
  },
  {
    id: "ester-hydrolysis-basic",
    name: "Saponification of Esters",
    category: "Carboxylic Acids",
    reactionType: "Substitution",
    reagents: ["Ester", "NaOH or KOH"],
    products: ["Carboxylate salt", "Alcohol"],
    conditions: ["Heat with aqueous alkali"],
    mechanism: ["Hydroxide attacks acyl carbon and forms carboxylate after leaving group departure."],
    exceptions: ["Base hydrolysis is effectively irreversible because carboxylate is formed."],
    relatedReactions: ["esterification-fischer", "ester-hydrolysis-acidic"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["saponification", "ester"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Carboxylic acid derivatives" },
  },
  {
    id: "carboxylic-acid-ammonia-amide",
    name: "Amide Formation from Carboxylic Acids",
    category: "Carboxylic Acids",
    reactionType: "Condensation",
    reagents: ["Carboxylic acid", "NH3"],
    products: ["Amide"],
    conditions: ["Ammonium salt formation then heat"],
    mechanism: ["Ammonium carboxylate dehydrates on heating to form amide."],
    exceptions: ["Direct room-temperature mixing gives ammonium salt, not amide."],
    relatedReactions: ["hofmann-bromamide-degradation"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "medium", pyqTags: ["amide preparation", "carboxylic acid"] },
    ncertReference: { class: 12, chapter: "Aldehydes, Ketones and Carboxylic Acids", topic: "Carboxylic acid derivatives" },
  },
  {
    id: "benzoylation-schotten-baumann",
    name: "Schotten-Baumann Benzoylation",
    category: "Amines",
    reactionType: "Substitution",
    reagents: ["Amine or phenol", "Benzoyl chloride", "NaOH"],
    products: ["Benzamide or phenyl benzoate"],
    conditions: ["Aqueous alkaline medium"],
    mechanism: ["Nucleophile attacks benzoyl chloride; base neutralises HCl."],
    exceptions: ["Tertiary amines do not form amides because they lack N-H."],
    relatedReactions: ["amine-acylation"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "medium", pyqTags: ["benzoylation", "Schotten-Baumann"] },
    ncertReference: { class: 12, chapter: "Amines", topic: "Chemical reactions of amines" },
  },
  {
    id: "diazonium-hypophosphorous-reduction",
    name: "Reduction of Diazonium Salts by Hypophosphorous Acid",
    category: "Amines",
    reactionType: "Reduction",
    reagents: ["Arenediazonium salt", "H3PO2", "Water"],
    products: ["Arene"],
    conditions: ["Aqueous hypophosphorous acid"],
    mechanism: ["Diazonium group is replaced by hydrogen with nitrogen loss."],
    exceptions: ["Useful for removing -NH2 after using it as a directing group."],
    relatedReactions: ["aniline-diazotization", "sandmeyer-reaction"],
    examRelevance: { exams: ["JEE MAIN", "JEE ADVANCED"], priority: "medium", pyqTags: ["diazonium reduction", "H3PO2"] },
    ncertReference: { class: 12, chapter: "Amines", topic: "Reactions of diazonium salts" },
  },
  {
    id: "balz-schiemann-reaction",
    name: "Balz-Schiemann Reaction",
    category: "Amines",
    reactionType: "Substitution",
    reagents: ["Arenediazonium fluoroborate", "Heat"],
    products: ["Aryl fluoride"],
    conditions: ["Thermal decomposition"],
    mechanism: ["Diazonium fluoroborate decomposes with loss of nitrogen and BF3 to form aryl fluoride."],
    exceptions: ["Fluoroarenes are not prepared by ordinary Sandmeyer CuF conditions."],
    relatedReactions: ["sandmeyer-reaction", "aniline-diazotization"],
    examRelevance: { exams: ["NEET", "JEE MAIN"], priority: "high", pyqTags: ["Balz-Schiemann", "aryl fluoride"] },
    ncertReference: { class: 12, chapter: "Amines", topic: "Reactions of diazonium salts" },
  },
] satisfies HighYieldReaction[];
