import { z } from "zod";

// ───────────────────────────────────────────────────────────────────────────
// Mechanism SSOT — the single typed contract every reaction page renders from.
// Generated by the API (AI → Zod-validated) or hand-authored as a seed.
// Bump SCHEMA_VERSION to invalidate all cached rows when the shape changes.
// Text fields are kept to one line by the generator prompt (RULE 1).
// ───────────────────────────────────────────────────────────────────────────

export const SCHEMA_VERSION = 1 as const;

export const DashboardSchema = z.object({
  reactionType: z.string(),
  difficulty: z.enum(["Easy", "Moderate", "Hard", "Olympiad"]),
  examFrequency: z.enum(["Low", "Medium", "High", "Very High"]),
  reagents: z.array(z.string()),
  products: z.array(z.string()),
  chapter: z.string(),
  mechanismType: z.string(),
  rds: z.string(),
  stereochemistry: z.string(),
  conditions: z.string(),
  timeToLearn: z.string(),
});

export const FlowNodeSchema = z.object({
  label: z.string(),
  kind: z.enum(["reactant", "reagent", "intermediate", "transition", "product"]).default("intermediate"),
});

export const MechanismStepSchema = z.object({
  n: z.number(),
  title: z.string(),
  beforeSmiles: z.string().optional(),
  afterSmiles: z.string().optional(),
  electronMove: z.string(), // schematic one-liner (which bond/lone pair → where)
  intermediate: z.string().optional(),
  reason: z.string(),
  trap: z.string().optional(),
  hook: z.string().optional(),
});

export const ExampleSchema = z.object({
  tier: z.enum(["Basic", "JEE Main", "JEE Advanced", "Olympiad", "PYQ"]),
  prompt: z.string(),
  answer: z.string(),
});

export const QuickViewSchema = z.object({
  reaction: z.string(),
  keyIntermediate: z.string(),
  rds: z.string(),
  keyReagent: z.string(),
  trap: z.string(),
  mnemonic: z.string(),
});

export const StereoSchema = z.object({
  applicable: z.boolean(),
  summary: z.string(),
  outcomes: z.array(z.string()).default([]),
});

export const MechanismSchema = z.object({
  schemaVersion: z.literal(SCHEMA_VERSION),
  slug: z.string(),
  name: z.string(),
  category: z.string().default("named-reaction"),
  dashboard: DashboardSchema,
  flowMap: z.array(FlowNodeSchema),
  steps: z.array(MechanismStepSchema),
  quickView: QuickViewSchema,
  stereochemistry: StereoSchema,
  examples: z.array(ExampleSchema),
  relatedReactions: z.array(z.string()),
});

export type Mechanism = z.infer<typeof MechanismSchema>;
export type MechanismStep = z.infer<typeof MechanismStepSchema>;
export type FlowNode = z.infer<typeof FlowNodeSchema>;
export type Example = z.infer<typeof ExampleSchema>;
