// Chemistry OS — Name Reactions index (organic). ~700 standard named reactions.
// Detail (mechanism / reagents / type / exam-importance) is generated on demand
// via /api/reaction so the data stays accurate and maintainable.

export const HIGH_YIELD = new Set<string>([
  "Aldol Reaction and Aldol Condensation", "Cannizzaro Reaction", "Diels-Alder Reaction",
  "Wittig Reaction", "Grignard Reaction", "Friedel-Crafts Acylation", "Friedel-Crafts Alkylation",
  "Reimer-Tiemann Reaction", "Clemmensen Reduction", "Wolff-Kishner Reduction", "Hofmann Elimination",
  "Hofmann Degradation", "Sandmeyer Reaction", "Gattermann Reaction", "Gattermann-Koch Formylation",
  "Kolbe-Schmidt Reaction", "Kolbe Electrolysis", "Williamson Ether Synthesis", "Wurtz Synthesis",
  "Wurtz-Fittig Reaction", "Hell-Volhard-Zelinsky Reaction", "Markownikoff Rule and Anti-Markownikoff Rule",
  "Saytzeff Rule", "Benzoin Condensation", "Perkin Reaction", "Claisen-Schmidt Condensation",
  "Mannich Reaction", "Michael Addition", "Birch Reduction", "Rosenmund Reduction", "Stephen Reaction",
  "Etard Reaction", "Lindlar Hydrogenation", "Sabatier-Senderens Reduction", "Finkelstein Reaction",
  "Swarts Reaction", "Wohler Synthesis", "Beckmann Rearrangement", "Pinacol Rearrangement",
  "Curtius Rearrangement", "Schmidt Reaction", "Baeyer-Villiger Oxidation", "Cope Elimination",
  "Carbylamine Reaction", "Hofmann Isonitrile Synthesis", "Knoevenagel Condensation",
  "Claisen Rearrangement", "Cope Rearrangement", "Aldol Reaction", "Suzuki Coupling", "Heck Reaction",
  "Stille Coupling", "Sonogashira Coupling", "Corey-Bakshi-Shibata Reduction", "Sharpless Epoxidation",
  "Simmons-Smith Reaction", "Reformatsky Reaction", "Strecker Synthesis", "Gabriel Primary Amine Synthesis",
  "Wolff Rearrangement", "Arndt-Eistert Synthesis", "Fischer Indole Synthesis", "Hantzsch Dihydropyridine Synthesis",
  "Skraup Reaction", "Paal-Knorr Pyrrole Synthesis", "Robinson Annulation", "Dieckmann Condensation",
  "Acetoacetic Ester Synthesis", "Malonic Ester Synthesis", "Balz-Schiemann Reaction", "Rosenmund Reaction",
  "Oppenauer Oxidation", "Meerwein-Ponndorf-Verley Reduction", "Jones Oxidation", "Dess-Martin Periodinane Oxidation",
  "Wacker Oxidation", "Ozonolysis", "Mitsunobu Reaction", "Appel Reaction",
]);

export const NAME_REACTIONS: string[] = [
  "Abnormal Claisen Rearrangement", "Acetoacetic Ester Condensation", "Acetoacetic Ester Synthesis",
  "Acyloin Condensation", "Acyloin Rearrangement", "Adkins Catalyst", "Ainley and King Synthesis",
  "Akabori Amino Acid Reaction", "Albright-Goldman Oxidation", "Alder Ene Reaction", "Alder-Rickert Reaction",
  "Aldol Reaction and Aldol Condensation", "Algar-Flynn-Oyamada (AFO) Reaction", "Alkene Metathesis",
  "Allan-Robinson Condensation", "Allylic Rearrangement", "Amadori Rearrangement", "Andrussow Process",
  "Angeli-Remini Reaction", "ANRORC Rearrangement", "Anschutz Anthracene Synthesis", "Appel Reaction",
  "Arens-Van Dorp Reaction", "Arndt-Eistert Synthesis", "Asinger Reaction", "Aston-Greenburg Rearrangement",
  "Atherton-Todd Reaction", "Auwers-Skita Rule", "Aza-Claisen Rearrangement", "Baddeley Isomerization",
  "Baeyer Diarylmethane Synthesis", "Baeyer-Drewson Reaction", "Baeyer Indole Synthesis", "Baeyer Oxindole Synthesis",
  "Baeyer Pyridine Synthesis", "Baeyer-Villiger Oxidation", "Bailey Peptide Synthesis", "Bakelite Process",
  "Baker-Ollis Sydnones Synthesis", "Baker-Venkataraman Rearrangement", "Ball-Goodwin-Morton Oxidation",
  "Bally-Scholl Reaction", "Balsohn Alkylation", "Balz-Schiemann Reaction", "Bamberger Rearrangement",
  "Bamford-Stevens Reaction", "Barbier Reaction", "Barbier-Wieland Degradation", "Bardhan Sengupta Synthesis",
  "Bargellini Condensation", "Bart Reaction", "Bartoli Indole Synthesis", "Barton Decarboxylation",
  "Barton Deoxygenation", "Barton Reaction", "Barton-Kellogg Olefination", "Barton-Zard Pyrrole Synthesis",
  "Batcho-Leimgruber Indole Synthesis", "Baudisch Reaction", "Baumann-Fromm Thiophene Synthesis",
  "Baumgarten α-Amino Ketone Synthesis", "Baylis-Hillman Reaction", "Béchamp Reduction",
  "Beckmann Rearrangement and Beckmann Fragmentation", "Bedoukian Halogenation", "Béhal-Sommelet Rearrangement",
  "Beirut Reaction", "Bellus-Claisen Rearrangement", "Bénary Reaction", "Benkeser Reduction",
  "Benzidine Rearrangement", "Benzilic Acid Rearrangement", "Benzoin Condensation", "Bergius Process",
  "Bergman Cyclization", "Bergmann Degradation", "Bergmann-Stern Azlactone Synthesis",
  "Bergmann-Zervas Peptide Synthesis", "Bernthsen Reaction", "Berti Olefination", "Bertram-Walbaum Reaction",
  "Betti Reaction", "Biginelli Reaction", "Birch Reduction", "Birckenbach-Goubeau Halogenation",
  "Birnbaum-Simonini Reaction", "Bischler Reaction", "Bischler-Napieralski Isoquinoline Synthesis",
  "Black Rearrangement", "Blaise Ketone Synthesis", "Blaise Reaction", "Blanc Chloromethylation", "Blanc Rule",
  "Blomquist Cyclic Ketone Synthesis", "Bobbitt Reaction", "Bodroux Amide Synthesis", "Bodroux-Chichibabin Reaction",
  "Böeseken Oxidation", "Bogert-Cook Synthesis", "Bohn-Schmidt Reaction", "Boord Olefin Synthesis",
  "Borsche-Berkhout Reaction", "Borsche-Drechsel Reaction", "Borsche-Koelsch Cinnoline Synthesis",
  "Bougault Reaction", "Boulton-Katritzky Rearrangement", "Bourgel Alkyne Synthesis", "Bouveault Aldehyde Synthesis",
  "Bouveault-Blanc Reduction", "Boyland-Sims Oxidation", "Bradsher Cyclization", "Bradsher Cycloaddition",
  "Bradsher Pyridinium Salt Synthesis", "Brandi-Guarna Reaction", "Breckpot β-Lactam Synthesis", "Bredt's Rule",
  "Brook Rearrangement", "Brown Hydroboration", "Bruckner Isoquinoline Synthesis", "Bucherer Carbazole Synthesis",
  "Bucherer Reaction", "Bucherer-Bergs Hydantoin Synthesis", "Büchner Ring Expansion",
  "Büchner-Curtius-Schlotterbeck Reaction", "Buchwald Indoline Synthesis", "Buchwald-Hartwig Amination",
  "Burton Trifluoromethylation", "Cadogan-Sundberg Indole Synthesis", "Caglioti Reaction", "Cahours-Hofmann Reaction",
  "Camps Reaction", "Cannizzaro Reaction", "Carboni-Lindsey Reaction", "Carroll Rearrangement",
  "Castro Indole Synthesis", "Castro-Stephens Coupling", "Chan Rearrangement", "Chapman Rearrangement",
  "Chichibabin Amination", "Chichibabin Pyridine Synthesis", "Chretien-Longi Reaction", "Chugaev Reaction",
  "Ciamician-Dennstedt Reaction", "Claisen Rearrangement", "Claisen-Schmidt Condensation", "Clauson-Kaas Reaction",
  "Clay-Kinnear-Perren Condensation", "Clayton-Jensen Chlorophosphonation", "Clemmensen Reduction",
  "Cohen Reductive Lithiation", "Combes Quinoline Synthesis", "Conrad-Limpach Quinoline Synthesis",
  "Cope Elimination", "Cope Rearrangement", "Corey-Bakshi-Shibata Reduction", "Corey-Chaykovsky Epoxidation",
  "Corey-Fuchs Reaction", "Corey-Gilman-Ganem Oxidation", "Corey-Kim Oxidation", "Corey-Kwiatkowski Reaction",
  "Corey-Link Reaction", "Corey-Schmidt Oxidation", "Corey-Suggs Oxidation", "Corey-Winter Olefination",
  "Cornforth Rearrangement", "Craig 2-Bromo-Pyridine Synthesis", "Cram's Rule", "Criegee Glycol Oxidation",
  "Criegee Ozonolysis", "Criegee Rearrangement", "Crum-Brown-Gibson Substitution Rule", "Curtius Rearrangement",
  "[m+n] Cycloaddition", "[2+2] Cycloaddition", "Dakin Reaction", "Dakin-West Reaction", "Danheiser Annulation",
  "Darzens Condensation", "Darzens Halogenation", "Darzens Olefin Acylation", "Darzens-Nenitzescu Reaction",
  "Davidson Oxazole Cyclization", "de Mayo Reaction", "Decker-Becker Secondary Amine Synthesis", "Délépine Reaction",
  "Demjanov Rearrangement", "Dess-Martin Periodinane Oxidation", "D-Homo Rearrangement", "Dieckmann Condensation",
  "Diels-Alder Reaction", "Diels-Reese Reaction", "Dienol-Benzene Rearrangement", "Dienone-Phenol Rearrangement",
  "Dimroth Rearrangement", "Di-π-Methane Rearrangement", "1,3-Dipolar Cycloaddition", "Doebner Reaction",
  "Doebner-Miller Reaction", "Doering-Moore-Skattebøl Reaction", "Dotz Benzannulation", "Dowd-Beckwith Ring Expansion",
  "Duff Reaction", "Dutt-Wormall Reaction", "Eastwood Olefination", "Eder Reaction", "Edman Degradation",
  "Eglinton Coupling", "Ehrlich-Sachs Reaction", "Einhorn Acylation", "Einhorn-Brunner Reaction", "Eisleb Alkylation",
  "Elbs Persulfate Oxidation", "Elbs Reaction", "Eltekoff Hydrolysis", "Emde Degradation", "Emmert Reaction",
  "Erlenmeyer-Plochl Azlactone Synthesis", "Eschenmoser Coupling", "Eschenmoser Fragmentation",
  "Eschweiler-Clarke Methylation", "Ester Pyrolysis", "Étard Reaction", "Evans Aldol Reaction",
  "Favorskii Rearrangement", "Favorskii-Babayan Reaction", "Feist-Benary Reaction", "Fenton Reaction",
  "Ferrier Reaction", "Ferrier-II Rearrangement", "Fétizon Oxidation", "Finkelstein Reaction",
  "Fischer Carbene Complexes", "Fischer Indole Synthesis", "Fischer Oxazole Synthesis",
  "Fischer Phenylhydrazine Synthesis", "Fischer Phenylhydrazone and Osazone Synthesis",
  "Fischer-Helferich Glycosylation", "Fischer-Hepp Rearrangement", "Fischer-Speier Esterification",
  "Fischer-Tropsch Synthesis", "Fleming-Tamao Oxidation", "Flood Reaction", "Forster Reaction",
  "Franchimont Condensation", "Frankland Reaction", "Fräter-Seebach Alkylation", "Freund Reaction",
  "Friedel-Crafts Acylation", "Friedel-Crafts Alkylation", "Friedländer Condensation", "Fries Rearrangement",
  "Fritsch-Buttenberg-Wiechell Rearrangement", "Fujimoto-Belleau Reaction", "Fukuyama Amine Synthesis",
  "Fukuyama Indole Synthesis", "Fürstner Indole Synthesis", "Gabriel Primary Amine Synthesis", "Gabriel Reaction",
  "Gabriel-Colman Rearrangement", "Garner Aldehyde", "Gassman Indole Synthesis", "Gassman Oxindole Synthesis",
  "Gassman Reaction", "Gattermann Aldehyde Synthesis", "Gattermann Reaction", "Gattermann-Koch Formylation",
  "Gewald Reaction", "Ghosez Cyclization", "Ghosez Keteniminium-Olefin Cyclization", "Gibbs-Wohl Naphthalene Oxidation",
  "Gilman-Cason Ketone Synthesis", "Gilman-Speeter Reaction", "Gomberg Free Radical Reaction",
  "Gomberg-Bachmann Pinacol Synthesis", "Gomberg-Bachmann Reaction", "Gould-Jacobs Reaction",
  "Graebe-Ullmann Synthesis", "Gränacher Synthesis", "Gribble Reductive Amination", "Griess Diazotization",
  "Grignard Degradation", "Grignard Reaction", "Grob Fragmentation", "Grosheintz-Fischer-Reissert Aldehyde Synthesis",
  "Grundmann Aldehyde Synthesis", "Gryszkiewicz-Trochimowski and McCombie Fluorination", "Guareschi Reaction",
  "Guerbet Condensation", "Gutknecht Condensation", "Hajos-Parrish-Eder-Sauer-Wiechert Reaction",
  "Haller-Bauer Cleavage", "Hammick Reaction", "Hansley-Prelog Acyloin Condensation",
  "Hantzsch Dihydropyridine Synthesis", "Hantzsch Pyrrole Synthesis", "Hantzsch Thiazole Synthesis",
  "Hass-Bender Oxidation", "Haworth Methylation", "Haworth Synthesis", "Hayashi Rearrangement", "Heck Reaction",
  "Hegedus Indole Synthesis", "Helferich Condensation", "Helferich Glycosylation", "Hell-Volhard-Zelinsky Reaction",
  "Hemetsberger Indole Synthesis", "Henkel Reaction", "Henry Reaction", "Herbst-Engel Transamination",
  "Heron Rearrangement", "Herz Reaction", "Heumann Indigo Process", "Heyns Rearrangement", "Hilbert-Johnson Reaction",
  "Hinsberg Oxindole Synthesis", "Hinsberg Reaction", "Hinsberg Sulfone Synthesis", "Hinsberg Thiophene Synthesis",
  "Hiyama Coupling", "Hoch-Campbell Reaction", "Hock Rearrangement", "Hofer-Moest Reaction", "Hofmann Degradation",
  "Hofmann Elimination", "Hofmann Isonitrile Synthesis", "Hofmann Rule", "Hofmann-Loffler-Freytag Reaction",
  "Hofmann-Martius Rearrangement", "Hofmann-Sand Reaction", "Hooker Oxidation", "Horenstein-Pählicke Reaction",
  "Horner-Wadsworth-Emmons Olefination", "Hosomi-Sakurai Allylation", "Houben-Hoesch Reaction",
  "Houdry Cracking Process", "Huisgen Pyrrole Synthesis", "Hunsdiecker Condensation", "Hunsdiecker Reaction",
  "Hydroformylation", "Iodolactonization", "Irvine-Purdie Methylation", "Jacobsen Rearrangement",
  "Jacobsen-Katsuki Epoxidation", "Janovsky Reaction", "Japp-Klingemann Fischer Indole Synthesis",
  "Japp-Klingemann Reaction", "Japp-Maitland Condensation", "Johnson Orthoester Claisen Rearrangement",
  "Jones Oxidation", "Jourdan-Ullmann Reaction", "Julia Olefination", "Juliá-Colonna Asymmetric Epoxidation",
  "Kabachnik-Fields Reaction", "Kahne Glycosylation", "Keck Allylation", "Keck Macrolactonization", "Kemp Elimination",
  "Kennedy Oxidative Cyclization", "Kiliani-Fischer Cyanohydrin Synthesis", "Kishner Decomposition",
  "Knoevenagel Condensation", "Knoevenagel Diazotization Method", "Knorr Pyrazole Synthesis", "Knorr Pyrrole Synthesis",
  "Knorr Quinoline Synthesis", "Koch-Haaf Carboxylation", "Kochi Reaction", "Koenigs-Knorr Reaction",
  "Kolbe Electrolysis", "Kolbe Nitrile Synthesis", "Kolbe-Schmidt Reaction", "Kondrat'eva Pyridine Synthesis",
  "Kornblum Oxidation", "Kornblum-DeLaMare Rearrangement", "Kostanecki-Robinson Reaction", "Kowalski Ester Homologation",
  "Krapcho Decarboxylation", "Kriewitz Condensation", "Kröhnke Pyridine Synthesis", "Kuhn-Roth Oxidation",
  "Kuhn-Winterstein Reduction", "Kulinkovich Cyclopropanation", "Kutscheroff Acetylene Hydration", "Lander Rearrangement",
  "Larock Indole Synthesis", "Lawesson's Reagent", "Lebedev Process", "Lehmstedt-Tanasescu Reaction",
  "Lemieux-Johnson Oxidation", "Leuckart Reaction", "Leuckart Thiophenol Synthesis", "Levinstein Process",
  "Lieben Iodoform Reaction", "Liebeskind-Srogl Cross-Coupling", "Lindlar Hydrogenation",
  "Lobry de Bruyn-Alberda van Ekenstein Transformation", "Lombardo Methylenation", "Lossen Rearrangement",
  "Luche Reaction", "Luche Reduction", "MacDonald-Fischer Degradation", "Madelung Indole Synthesis",
  "Maillard Reaction", "Maitland-Japp Reaction", "Majetich Annulation", "Malaprade Reaction", "Malonic Ester Synthesis",
  "Mandelic Acid Synthesis", "Mannich Reaction", "Marckwald Asymmetric Synthesis",
  "Markownikoff Rule and Anti-Markownikoff Rule", "Martinet Reaction", "Martin's Sulfurane", "Mattox-Kendall Reaction",
  "McCormack Cycloaddition", "McFadyen-Stevens Reaction", "McLafferty Rearrangement", "McMurry Coupling",
  "Meerwein Arylation", "Meerwein-Ponndorf-Verley Reduction", "Meerwein's Salt", "Meinwald Rearrangement",
  "Meisenheimer Complexes", "Meisenheimer Rearrangement", "Menke Nitration", "Menschutkin Reaction",
  "Mentzer Pyrone Synthesis", "Merrifield Solid-Phase Peptide Synthesis", "Meyer-Hartmann Reaction",
  "Meyers Aldehyde Synthesis", "Meyer-Schuster Rearrangement", "Michael Addition", "Michaelis-Arbuzov Rearrangement",
  "Michael-Stetter Reaction", "Miescher Degradation", "Mignonac Reaction", "Milas Hydroxylation",
  "Mislow-Evans Rearrangement", "Mitsunobu Reaction", "Moffatt-Swern Oxidation", "Moore Cyclization",
  "Morgan-Walls Cyclization", "Mori-Ban Indole Synthesis", "Morin Rearrangement", "Mosher's Acid",
  "Moureau-Mignonac Ketimine Synthesis", "Mukaiyama Aldol Reaction", "Mukaiyama-Michael Reaction",
  "Müller-Cunradi-Pieroh Process", "Myers-Saito Cyclization", "Nagata Reaction", "Nazarov Cyclization",
  "Neber Rearrangement", "Neber-Bossel Synthesis", "Nef Reaction", "Negishi Cross-Coupling", "Nencki Reaction",
  "Nenitzescu Synthesis", "Nenitzescu Indole Synthesis", "Newman-Kwart Rearrangement", "Nicholas Reaction",
  "Niementowski Reaction", "Nierenstein Reaction", "Norrish Type I Reaction", "Norrish Type II Reaction",
  "Noyori Hydrogenation", "Nozaki-Hiyama-Kishi Reaction", "Nysted Reagent", "Ohle Quinoxaline Synthesis",
  "Oppenauer Oxidation", "Orton Rearrangement", "Ostromislensky Process", "Overman Rearrangement",
  "Paal-Knorr Furan Synthesis", "Paal-Knorr Pyrrole Synthesis", "Paneth Technique", "Parham Cyclization",
  "Parikh-Doering Oxidation", "Passerini Reaction", "Paterno-Buchi Reaction", "Pauson-Khand Reaction",
  "Payne Rearrangement", "Pearlman's Catalyst", "Pechmann Pyrazole Synthesis", "Pechmann Reaction",
  "Pellizzari Reaction", "Perkin Reaction", "Perkin Synthesis", "Perkow Reaction", "Petasis-Ferrier Rearrangement",
  "Peterson Olefination", "Petrenko-Kritschenko Piperidone Synthesis", "Pfau-Plattner Azulene Synthesis",
  "Pfitzinger Reaction", "Pfitzner-Moffatt Oxidation", "Phillips-Ladenburg Benzimidazole Synthesis",
  "Photo-Fries Rearrangement", "Pictet-Gams Synthesis", "Pictet-Spengler Reaction", "Piloty-Robinson Pyrrole Synthesis",
  "Pinacol Coupling Reaction", "Pinacol Rearrangement", "Pinner Condensation", "Pinner Reaction",
  "Pinner S-Triazine Synthesis", "Piria Reaction", "Plancher Rearrangement", "Polonovski Reaction",
  "Pomeranz-Fritsch Reaction", "Ponzio Reaction", "Prévost Reaction", "Prey Ether Cleavage", "Prilezhaev Reaction",
  "Prins Reaction", "Pudovik Reaction", "Pummerer Rearrangement", "Quelet Reaction", "Radziszewski Reaction",
  "Ramberg-Bäcklund Reaction", "Raney Nickel", "Rauhut-Currier Reaction", "Reed Reaction", "Reformatsky Reaction",
  "Regitz Diazo Transfer", "Reilly-Rickinbottom Rearrangement", "Reimer-Tiemann Reaction", "Reissert Compound",
  "Reissert Indole Synthesis", "Reppe Alkyne Cyclotrimerization", "Reppe Carbonylation", "Reppe Cyclization",
  "Reppe Vinylation", "Retro-Diels-Alder Reaction", "Retro-Ene Reaction", "Retropinacol Rearrangement",
  "Reverdin Rearrangement", "Riehm Quinoline Synthesis", "Rieke Metal", "Riemenschneider Reaction", "Riley Oxidation",
  "Ritter Reaction", "Robinson Annulation", "Robinson-Gabriel Oxazole Synthesis", "Robinson-Schopf Condensation",
  "Rosenmund Reaction", "Rosenmund Reduction", "Rosenmund-von Braun Reaction", "Rothemund Reaction",
  "Roush Crotylboration", "Rowe Rearrangement", "Rubottom Oxidation", "Ruff Degradation", "Rupe Rearrangement",
  "Sabatier-Senderens Reduction", "Saegusa Cyclization", "Saegusa Oxidation", "Sandmeyer Isatin Synthesis",
  "Sandmeyer Reaction", "Sarett Oxidation", "Saytzeff Rule", "Schiff Base", "Schlack-Kumpf Reaction",
  "Schlotterbeck Reaction", "Schmidlin Ketene Synthesis", "Schmidt Glycosylation", "Schmidt Reaction",
  "Schmidt-Rutz Reaction", "Schmittel Cyclization", "Scholl Reaction", "Schöllkopf Bis-Lactim Ether Method",
  "Schöllkopf Oxazole Synthesis", "Schönberg Rearrangement", "Schotten-Baumann Reaction", "Schwartz Reagent",
  "Screttas Lithiation", "Selenoxide Elimination", "Semmler-Wolff Aromatization", "Serini Reaction",
  "Seyferth-Gilbert Homologation", "Shapiro Reaction", "Sharpless Aminohydroxylation", "Sharpless Dihydroxylation",
  "Sharpless Epoxidation", "Shechter-Kaplan Oxidative Nitration", "Shi Epoxidation", "Simmons-Smith Reaction",
  "Simonini Reaction", "Skraup Reaction", "Smiles Rearrangement", "Sommelet Reaction", "Sommelet-Hauser Rearrangement",
  "Sonn-Muller Reaction", "Sonogashira Coupling", "Staudinger [2+2] Cycloaddition", "Staudinger Reaction",
  "Stec Reaction", "Steglich Catalyst", "Steglich Rearrangement", "Stephen Reaction", "Stetter Reaction",
  "Stevens Rearrangement", "Stieglitz Rearrangement", "Stille Coupling", "Stobbe Condensation",
  "Stolle-Becker Synthesis", "Stork Reaction", "Strecker Degradation", "Strecker Reaction", "Strecker Synthesis",
  "Suárez Cleavage", "Sugasawa Indole Synthesis", "Sugasawa Reaction", "Sundberg Indole Synthesis", "Suzuki Coupling",
  "Swarts Reaction", "Takai Olefination", "Tebbe Olefination", "ter Meer Reaction", "Thiele-Winter Acetoxylation",
  "Thorpe-Ziegler Cyclization", "Tiemann Cyanohydrin Amination", "Tiemann Rearrangement",
  "Tiffeneau-Demjanov Ring Expansion", "Tishchenko Reaction", "Traube Purine Synthesis", "Trofimov Reaction",
  "Trost Desymmetrization", "Truce-Smiles Rearrangement", "Tscherniac-Einhorn Reaction", "Tsuji-Trost Reaction",
  "Twitchell Process", "Tyrer Process", "Ueno-Stork Cyclization", "Ugi Reaction", "Ullmann Acridine Synthesis",
  "Ullmann Coupling", "Ullmann Diaryl Ether Synthesis", "Urech Cyanohydrin Method", "van Slyke Method",
  "Varrentrapp Reaction", "Victor Meyer Reaction", "Vilsmeier Formylation", "Vinylcyclopropane Rearrangement",
  "Voigt Reaction", "von Auwers Rearrangement", "von Braun Cyanogen Bromide Reaction", "von Braun Degradation",
  "von Braun-Rudolf Synthesis", "von Richter Cinnoline Synthesis", "von Richter Reaction", "Vorbrüggen Glycosylation",
  "Wacker Oxidation", "Wagner-Jauregg Reaction", "Wagner-Meerwein Rearrangement", "Walden Inversion",
  "Wallach Rearrangement", "Weerman Reaction", "Weidenhagen Synthesis", "Weinreb Amide Formation",
  "Weinreb Ketone Synthesis", "Weiss-Cook Condensation", "Weitz-Scheffer Epoxidation", "Wender Indole Synthesis",
  "Wessely-Moser Rearrangement", "Westphalen Rearrangement", "Wharton Rearrangement", "Wibaut-Arens Alkylation",
  "Wichterle Reaction", "Widman-Stoermer Synthesis", "Wilkinson's Catalyst", "Willgerodt-Kindler Reaction",
  "Williamson Ether Synthesis", "Wittig Reaction", "[1,2]-Wittig Rearrangement", "[2,3]-Wittig Rearrangement",
  "Wohl Degradation", "Wohl-Aue Reaction", "Wöhler Synthesis", "Wohl-Ziegler Bromination", "Wolff Rearrangement",
  "Wolffenstein-Böters Reaction", "Wolff-Kishner Reduction", "Woodward Cis-Hydroxylation", "Wurtz Synthesis",
  "Wurtz-Fittig Reaction", "Yamada Coupling", "Yamaguchi Esterification", "Zeisel Determination",
  "Zelinsky-Stadnikoff Reaction", "Zemplén Deacetylation", "Zerewitinoff Determination", "Ziegler Alcohol Synthesis",
  "Ziegler-Hafner Azulene Synthesis", "Ziegler-Natta Polymerization", "Zimmermann Reaction", "Zincke Disulfide Cleavage",
  "Zincke Nitration", "Zincke Reaction", "Zincke-Suhl Reaction", "Zinke Synthesis",
];
