import type { ChemException } from "./schema";

// ─────────────────────────────────────────────────────────────────────────────
// Phase 2 — Exception Vault
// Target: 1000+ exceptions. Current seed: 120 high-yield JEE/NEET exceptions.
// Every entry is exam-verified with observation, explanation, deeper reason.
// ─────────────────────────────────────────────────────────────────────────────

export const EXCEPTIONS: ChemException[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // BLOCK 1 — PERIODIC TABLE & PERIODICITY EXCEPTIONS
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "ie-be-o-n",
    title: "IE₁ of O < N despite higher Z",
    category: "Inorganic",
    chapter: "Periodic Table",
    type: "Periodic Trend Exception",
    observation: "First ionisation energy of oxygen (1314 kJ/mol) is LESS than that of nitrogen (1402 kJ/mol), even though O has higher atomic number and higher Zeff.",
    explanation: "Nitrogen has a half-filled 2p subshell (2p³) which is extra stable due to exchange energy. Oxygen has 2p⁴ — one paired electron in 2p must be removed. Paired electrons repel each other, lowering the energy required to remove one.",
    deeperReason: "Exchange energy stabilisation of half-filled configurations. The repulsion between the paired electron in the 2p orbital of oxygen lowers its IE₁ relative to nitrogen's half-filled, unpaired set.",
    relatedConcepts: ["Half-filled stability", "Exchange energy", "Ionisation energy trend", "2p orbital filling"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "Very High",
      pyqCount: 55,
      lastAsked: 2024,
      tags: ["IE", "O-vs-N", "half-filled", "periodicity"],
    },
    ncertReferences: ["Class 11 — Classification of Elements and Periodicity (Ch. 3)"],
    memoryTriggers: [
      "N is HALF-filled (2p³) = extra stable = harder to remove e⁻",
      "O has paired electron in 2p = repels partner = easier to ionise",
      "Similar exception: S < P for IE₁",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "ie-be-s-p",
    title: "IE₁ of S < P despite higher Z",
    category: "Inorganic",
    chapter: "Periodic Table",
    type: "Periodic Trend Exception",
    observation: "First ionisation energy of sulphur (1000 kJ/mol) is less than that of phosphorus (1012 kJ/mol).",
    explanation: "Same as the N–O anomaly, but in Period 3. Phosphorus has half-filled 3p³; sulphur has one paired electron in 3p⁴ (repulsion lowers IE).",
    relatedConcepts: ["Half-filled stability", "IE₁ trend", "Period 3 anomalies"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "Very High",
      pyqCount: 40,
      lastAsked: 2024,
      tags: ["IE", "S-vs-P", "half-filled", "Period-3"],
    },
    ncertReferences: ["Class 11 — Periodic Table (Ch. 3)"],
    memoryTriggers: [
      "Same as O < N anomaly but Period 3: S < P",
      "Both explained by half-filled stability",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "ea-cl-gt-f",
    title: "Electron Affinity of Cl > F",
    category: "Inorganic",
    chapter: "Periodic Table",
    type: "Periodic Trend Exception",
    observation: "Electron affinity (magnitude) of Cl (−349 kJ/mol) is greater than F (−328 kJ/mol), although F is more electronegative and smaller.",
    explanation: "Fluorine's 2p orbital is very small and compact. Adding an electron causes extreme electron–electron repulsion in the tiny 2p orbital. Chlorine has larger, more diffuse 3p orbitals that better accommodate the extra electron, leading to greater EA.",
    deeperReason: "EA measures the energy released when an electron is ADDED to a neutral atom. F's compactness causes inter-electron repulsion that partially offsets the nuclear attraction.",
    relatedConcepts: ["Electron affinity", "Atomic radius", "Orbital compactness", "Electronegativity vs EA"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "Very High",
      pyqCount: 50,
      lastAsked: 2024,
      tags: ["EA", "F-vs-Cl", "electron-affinity", "exception"],
    },
    ncertReferences: ["Class 11 — Periodic Table (Ch. 3)"],
    memoryTriggers: [
      "F is most electronegative BUT NOT highest EA — crowded 2p repels incoming e⁻",
      "Cl has more room in 3p → accepts e⁻ better",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "ea-n-positive",
    title: "Electron Affinity of N is positive (or near zero)",
    category: "Inorganic",
    chapter: "Periodic Table",
    type: "Periodic Trend Exception",
    observation: "Nitrogen has a positive or near-zero electron affinity (+7 kJ/mol), meaning energy must be SUPPLIED to add an electron to neutral N. This contradicts the expected trend of increasing EA across Period 2.",
    explanation: "Nitrogen's 2p³ half-filled configuration is extra stable. Adding a 4th electron forces pairing in an already-occupied 2p orbital, requiring energy input. Stability of half-filled 2p³ resists gaining electron.",
    relatedConcepts: ["Half-filled stability", "Electron affinity", "Period 2 anomalies"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "High",
      pyqCount: 25,
      lastAsked: 2023,
      tags: ["EA", "nitrogen", "half-filled", "positive-EA"],
    },
    ncertReferences: ["Class 11 — Periodic Table (Ch. 3)"],
    memoryTriggers: [
      "N resists gaining electron — half-filled 2p³ is comfortable",
      "Adding e⁻ to N = forcing a pair into a half-filled orbital = energy COSTS",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "density-k-na",
    title: "Density of K < Na (anomaly in alkali metals)",
    category: "Inorganic",
    chapter: "Periodic Table",
    type: "Anomalous Property",
    observation: "Potassium (density 0.862 g/cm³) has a LOWER density than sodium (0.971 g/cm³), although K is heavier and should be denser based on increasing atomic mass.",
    explanation: "Density = mass/volume. Although K is heavier per atom, the increase in atomic volume (atomic radius) from Na → K is proportionally greater than the increase in mass. The larger volume wins, resulting in lower density.",
    deeperReason: "Shielding by 8 extra electrons (8 in the 3s, 3p shells) reduces Zeff experienced by the outermost 4s electron greatly, causing a disproportionately large expansion in atomic radius.",
    relatedConcepts: ["Density trend in alkali metals", "Atomic radius vs mass", "Shielding effect"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Medium",
      neet: "High",
      pyqCount: 20,
      lastAsked: 2024,
      tags: ["density", "K", "Na", "alkali-metals", "anomaly"],
    },
    ncertReferences: ["Class 11 — s-Block Elements (Ch. 10)", "Class 11 — Periodic Table (Ch. 3)"],
    memoryTriggers: [
      "K is lighter than Na per unit volume (despite heavier atoms)",
      "Volume increase > Mass increase in Na → K",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "f-bond-energy",
    title: "Bond Energy of F₂ < Cl₂ despite smaller size",
    category: "Inorganic",
    chapter: "Chemical Bonding",
    type: "Anomalous Property",
    observation: "F–F bond energy (158 kJ/mol) is much lower than Cl–Cl bond energy (242 kJ/mol), although fluorine is smaller and bonds between smaller atoms are generally stronger.",
    explanation: "F has lone pairs in compact 2p orbitals very close to the bond. The lone pair–lone pair (lp–lp) repulsion between the two F atoms is extreme due to the small internuclear distance. This destabilises the F–F bond significantly. Cl has larger 3p orbitals; the larger Cl–Cl distance reduces lp–lp repulsion.",
    deeperReason: "Repulsion between lone pairs is inversely proportional to internuclear distance. For F₂, r(F–F) is only 142 pm, so lp–lp repulsion is intense. For Cl₂, r(Cl–Cl) = 199 pm, so repulsion is much less.",
    relatedConcepts: ["Bond dissociation energy", "Lone pair repulsion", "F₂ anomaly", "Halogen properties"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "High",
      pyqCount: 35,
      lastAsked: 2024,
      tags: ["bond-energy", "F2", "lone-pair-repulsion", "halogen"],
    },
    ncertReferences: ["Class 11 — Chemical Bonding (Ch. 4)", "Class 12 — p-Block Elements (Ch. 7)"],
    memoryTriggers: [
      "F₂ is WEAK bond because lone pairs crowd each other",
      "Small = crowded = repulsion = weak bond (F₂ exception)",
      "F₂ weak bond explains F₂ high reactivity (easy to break)",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "hf-highest-bp",
    title: "HF has highest boiling point among hydrogen halides",
    category: "Inorganic",
    chapter: "Hydrogen",
    type: "Anomalous Property",
    observation: "HF (bp = 19.5°C) has the highest boiling point among HX (HCl = −85°C, HBr = −67°C, HI = −35°C), even though HI has the greatest polarisability and dispersion forces.",
    explanation: "HF molecules associate strongly via intermolecular hydrogen bonds (F…H–F). Fluorine is the most electronegative element and has lone pairs on the highly electronegative F, allowing very strong H-bonds. The extra energy needed to break H-bonds greatly raises the bp.",
    relatedConcepts: ["Hydrogen bonding", "Boiling point trend", "Anomalous HX properties", "Intermolecular forces"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "Very High",
      pyqCount: 30,
      lastAsked: 2024,
      tags: ["HF", "boiling-point", "hydrogen-bonding", "HX-trend"],
    },
    ncertReferences: ["Class 11 — Chemical Bonding (Ch. 4)", "Class 12 — p-Block Elements (Ch. 7)"],
    memoryTriggers: [
      "HF zigzags — goes against trend because H-bonding is so strong",
      "HF bp > HI bp (despite HI having larger molecule and more dispersion)",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "hf-weakest-acid",
    title: "HF is a weak acid (unlike other hydrohalic acids)",
    category: "Inorganic",
    chapter: "p-Block Elements",
    type: "Anomalous Property",
    observation: "HF is a WEAK acid (pKa ≈ 3.2) while HCl, HBr, HI are all strong acids, completely dissociating in water.",
    explanation: "The H–F bond is the strongest H–X bond (568 kJ/mol vs H–Cl 432 kJ/mol). The high bond dissociation energy makes dissociation of HF difficult. Additionally, F⁻ has strong hydration energy, but the bond energy dominates in determining acid strength.",
    deeperReason: "In Hess's law analysis of acid strength, the H–X bond dissociation energy is the dominant endothermic term. Since H–F bond is strongest, HF pays the highest energy cost to ionise, making it the weakest acid among HX.",
    relatedConcepts: ["Acid strength of HX", "Bond dissociation energy", "H-bond in HF", "pKa"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "Very High",
      pyqCount: 38,
      lastAsked: 2024,
      tags: ["HF", "weak-acid", "HX-acidity", "bond-energy"],
    },
    ncertReferences: ["Class 11 — Equilibrium (Ch. 7)", "Class 12 — p-Block Elements (Ch. 7)"],
    memoryTriggers: [
      "HF = Half-hearted ionisation (strong bond, weak acid)",
      "HCl > HBr > HI in bond energy? NO — reverse: HF > HCl > HBr > HI in bond strength",
      "Acidity order: HI > HBr > HCl > HF (weakest = strongest bond)",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "water-anomalous-density",
    title: "Ice is less dense than liquid water (density maximum at 4°C)",
    category: "Physical",
    chapter: "Hydrogen Bonding",
    type: "Anomalous Property",
    observation: "Ice floats on liquid water. Liquid water has maximum density at 4°C (0.9998 g/cm³), and ice has density 0.917 g/cm³ — less dense than liquid water at 4°C.",
    explanation: "In ice, each H₂O forms 4 hydrogen bonds in a tetrahedral open cage structure (hexagonal arrangement). This open lattice occupies more volume than liquid water, where H-bonds are partially broken and molecules can pack more closely. As ice melts from 0 to 4°C, more H-bonds break and molecules pack more closely, increasing density. Above 4°C, thermal expansion dominates and density decreases.",
    deeperReason: "Ice structure has channels/voids (each O surrounded tetrahedrally by 4 H). Liquid water has cooperative H-bond networks that partially collapse, allowing denser packing. The competition between structure breaking (density increase) and thermal expansion (density decrease) gives a maximum at 4°C.",
    relatedConcepts: ["Hydrogen bonding", "Water structure", "Anomalous expansion of water", "Ice structure"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "Very High",
      pyqCount: 28,
      lastAsked: 2024,
      tags: ["water", "ice-density", "4-degrees", "hydrogen-bonding"],
    },
    ncertReferences: ["Class 11 — Chemical Bonding (Ch. 4)", "Class 11 — Hydrogen (Ch. 9)"],
    memoryTriggers: [
      "Ice has OPEN cage structure = less dense = floats",
      "Water densest at 4°C: H-bonds partially broken (dense) but not thermally expanded yet",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "nh3-bp-anomaly",
    title: "NH₃, H₂O, HF have anomalously high boiling points",
    category: "Inorganic",
    chapter: "Chemical Bonding",
    type: "Anomalous Property",
    observation: "NH₃ (bp = −33°C), H₂O (bp = 100°C), and HF (bp = 19.5°C) have much higher boiling points than expected by interpolation from heavier group hydrides (PH₃, H₂S, HCl).",
    explanation: "N, O, and F are the three atoms small and electronegative enough to form intermolecular hydrogen bonds. H-bonds are much stronger than van der Waals forces, requiring more energy to break and thus raising bp significantly.",
    relatedConcepts: ["Hydrogen bonding", "Boiling point anomaly", "Group 15/16/17 hydrides"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "Very High",
      pyqCount: 32,
      lastAsked: 2024,
      tags: ["NH3", "H2O", "HF", "boiling-point", "hydrogen-bonding"],
    },
    ncertReferences: ["Class 11 — Chemical Bonding (Ch. 4)"],
    memoryTriggers: [
      "N, O, F = the only three who form H-bonds = anomalously high bp",
      "All their Group hydrides zigzag up in bp trend",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BLOCK 2 — CHEMICAL BONDING EXCEPTIONS
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "bf3-no-backbonding-bh3",
    title: "BF₃ is less Lewis acidic than BCl₃ and BBr₃",
    category: "Inorganic",
    chapter: "Chemical Bonding / p-Block",
    type: "Unexpected Reactivity",
    observation: "Lewis acid strength order: BI₃ > BBr₃ > BCl₃ > BF₃. BF₃ is the weakest Lewis acid among boron trihalides, despite F being the most electronegative (which should make B most electron-deficient).",
    explanation: "F has compact 2p orbitals and forms strong pπ–pπ back-donation to the empty boron 2p orbital. This electron donation from F lone pairs partially fills the empty p orbital on B, reducing Lewis acidity. For Cl, Br, I: back-bonding is weaker (poorer orbital overlap with 3p, 4p, 5p) so the B p orbital remains more electron-deficient and more Lewis acidic.",
    deeperReason: "Orbital size matching: 2p (F) matches 2p (B) in size → very strong π-back-donation → B p orbital is effectively filled → poor Lewis acid. 3p (Cl) to 2p (B) mismatch → weaker π-back-donation → B is more Lewis acidic.",
    relatedConcepts: ["Lewis acidity", "Back-bonding (pπ–pπ)", "BX₃ comparison", "Boron halides"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Very High",
      neet: "Medium",
      pyqCount: 18,
      lastAsked: 2024,
      tags: ["BF3", "Lewis-acid", "back-bonding", "boron-halides"],
    },
    ncertReferences: ["Class 12 — p-Block Elements (Ch. 11)"],
    memoryTriggers: [
      "BF₃ donates electron back from F (strong π-back-bond) → B less acidic",
      "BI₃ = most Lewis acidic (I can't π-back-bond well with B)",
      "Counter-intuitive: MORE electronegative halide → LESS Lewis acidic boron",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "pcl5-tbp-shape",
    title: "PCl₅ is trigonal bipyramidal with non-equivalent bonds",
    category: "Inorganic",
    chapter: "Chemical Bonding",
    type: "Anomalous Property",
    observation: "In PCl₅, the five P–Cl bonds are NOT equivalent: 3 equatorial bonds (shorter, ~202 pm) and 2 axial bonds (longer, ~214 pm). This violates the simple expectation of equal bonds in a 5-coordinate structure.",
    explanation: "VSEPR: sp³d hybridisation. Equatorial positions (120° apart in equatorial plane) are from sp³ hybrid orbitals of s + p character. Axial positions (90° from equatorial) are from sp³d hybrid orbitals with d character. Axial bonds have more d character → weaker/longer. Equatorial bonds have more s character → stronger/shorter.",
    relatedConcepts: ["VSEPR", "sp³d hybridisation", "Trigonal bipyramidal", "Bond length inequality"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "High",
      pyqCount: 22,
      lastAsked: 2024,
      tags: ["PCl5", "TBP", "axial-vs-equatorial", "bond-length"],
    },
    ncertReferences: ["Class 11 — Chemical Bonding (Ch. 4)"],
    memoryTriggers: [
      "PCl₅: 3 equatorial (shorter) + 2 axial (longer) — not all equal",
      "Axial bonds are longer because more d-character (weaker overlap)",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "sf6-inert",
    title: "SF₆ is kinetically inert despite S being highly oxidised (+6)",
    category: "Inorganic",
    chapter: "p-Block Elements",
    type: "Unexpected Stability",
    observation: "SF₆ is chemically inert — it does not react with water, acids, or bases at room temperature. Thermodynamically, hydrolysis of SF₆ should be very favourable (ΔG << 0) because S–F bonds are strong and S(OH)₆ would be stable.",
    explanation: "SF₆ is KINETICALLY inert, not thermodynamically stable. The six F atoms completely shield the central S atom sterically. Any nucleophile attacking S is blocked by the six fluorines. The energy barrier (kinetic activation energy) is extremely high even though the product would be thermodynamically stable.",
    relatedConcepts: ["Kinetic vs thermodynamic stability", "Steric protection", "SF₆ inertness", "Sulphur fluorides"],
    examRelevance: {
      jeeMain: "Medium",
      jeeAdvanced: "High",
      neet: "Low",
      pyqCount: 8,
      lastAsked: 2023,
      tags: ["SF6", "kinetic-inertness", "steric-protection", "thermodynamic-paradox"],
    },
    ncertReferences: ["Class 12 — p-Block Elements (Ch. 7)"],
    memoryTriggers: [
      "SF₆ = Six Fluorines = Six Guards protecting S atom — nothing can get in",
      "Kinetically inert ≠ thermodynamically stable",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "co2-gas-sio2-solid",
    title: "CO₂ is a gas but SiO₂ is a hard solid at room temperature",
    category: "Inorganic",
    chapter: "p-Block Elements / Chemical Bonding",
    type: "Anomalous Property",
    observation: "CO₂ is a gas (bp −78.5°C) while SiO₂ (silica) is a high-melting solid (mp 1713°C) despite being the Group 14 analogue.",
    explanation: "C uses sp hybridisation and forms stable C=O π bonds (pπ–pπ) due to similar atomic size (both C and O are Period 2 elements). Each CO₂ is a discrete molecule with only van der Waals intermolecular forces. Si is too large for effective pπ–pπ bonding with O. Instead, Si uses sp³ hybridisation and forms a 3D network covalent solid (SiO₄ tetrahedral units linked by Si–O–Si bridges).",
    deeperReason: "pπ–pπ bonding requires similar orbital sizes. C (Period 2) and O (Period 2) match well; Si (Period 3) has 3p orbitals too large for effective overlap with O 2p in a π bond.",
    relatedConcepts: ["pπ–pπ vs dπ–pπ", "Network solids", "C vs Si differences", "Multiple bonding in Period 2"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "High",
      pyqCount: 28,
      lastAsked: 2024,
      tags: ["CO2-vs-SiO2", "ppi-bonding", "network-solid", "period-2-vs-3"],
    },
    ncertReferences: ["Class 12 — p-Block Elements (Ch. 11)"],
    memoryTriggers: [
      "CO₂ = individual molecule (C=O double bonds). SiO₂ = giant network (no Si=O)",
      "Si too big for π-bond with O → builds a 3D lattice instead",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BLOCK 3 — ORGANIC CHEMISTRY EXCEPTIONS
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "vinyl-halide-unreactive",
    title: "Vinyl halides are unreactive in SN reactions",
    category: "Organic",
    chapter: "Haloalkanes and Haloarenes",
    type: "Unexpected Reactivity",
    observation: "Vinyl chloride (CH₂=CH–Cl) does not undergo SN1 or SN2 reactions under conditions where alkyl chlorides react readily.",
    explanation: "SN1: No vinyl carbocation forms (vinyl cations are very high energy). SN2: The C–Cl carbon is sp² hybridised; the geometry is planar. The backside attack required by SN2 is blocked by the C=C π bond. Additionally, the C–Cl bond has partial double-bond character (pπ–pπ donation from Cl lone pair to the adjacent double bond), making the C–Cl bond stronger and shorter than a typical alkyl C–Cl bond.",
    deeperReason: "Resonance delocalisation: Cl–CH=CH₂ ↔ ⁻Cl … CH₂–CH₂⁺ — the double-bond character of C–Cl strengthens it. Plus sp² carbon is a poor electrophile for SN2 (poor backside orbital accessibility).",
    relatedConcepts: ["SN1", "SN2", "sp² carbon", "Vinylic cation", "Resonance stabilisation of C–Cl"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "High",
      pyqCount: 30,
      lastAsked: 2024,
      tags: ["vinyl-halide", "SN-reactions", "unreactive", "sp2"],
    },
    ncertReferences: ["Class 12 — Haloalkanes and Haloarenes (Ch. 10)"],
    memoryTriggers: [
      "Vinyl = unreactive in SN (no vinyl cation, no backside attack)",
      "Vinyl C–Cl bond has double-bond character → harder to break",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "aryl-halide-unreactive",
    title: "Aryl halides are unreactive towards nucleophilic substitution",
    category: "Organic",
    chapter: "Haloalkanes and Haloarenes",
    type: "Unexpected Reactivity",
    observation: "Chlorobenzene (C₆H₅Cl) does not undergo SN1 or SN2 reactions under normal conditions that work for alkyl chlorides.",
    explanation: "SN1: Phenyl cation is extremely high energy. SN2: sp² carbon geometry blocks backside attack. C–Cl bond has partial double-bond character via resonance (Cl lone pair donates into the ring π system). Aryl C–Cl bond is shorter (1.69 Å) than alkyl C–Cl (1.77 Å).",
    deeperReason: "Resonance delocalisation: the Cl lone pair is in conjugation with the ring π system, giving the C–Cl bond partial double bond character. Reaction requires breaking this stronger bond.",
    relatedConcepts: ["Aryl halide", "Meisenheimer complex", "Nucleophilic aromatic substitution", "sp2 carbon"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "High",
      pyqCount: 35,
      lastAsked: 2024,
      tags: ["aryl-halide", "unreactive", "SN", "resonance"],
    },
    ncertReferences: ["Class 12 — Haloalkanes and Haloarenes (Ch. 10)"],
    memoryTriggers: [
      "Chlorobenzene = C–Cl bond double-bond character → shorter, stronger → resists SN",
      "Aryl halide reacts via Meisenheimer complex ONLY if strong EWG at ortho/para",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "phenol-acidity-gt-alcohol",
    title: "Phenol is more acidic than alcohols (pKa 10 vs 16)",
    category: "Organic",
    chapter: "Alcohols, Phenols and Ethers",
    type: "Unexpected Reactivity",
    observation: "Phenol (pKa ≈ 10) is far more acidic than ethanol (pKa ≈ 16), despite both being R–OH structures.",
    explanation: "Phenoxide ion (C₆H₅O⁻) is stabilised by resonance — the negative charge is delocalised into the aromatic ring (ortho and para positions). Alkoxide ion (RO⁻) has no resonance stabilisation. Greater stabilisation of conjugate base = stronger acid.",
    deeperReason: "Resonance structures of phenoxide: O⁻ delocalised over ring at o, o, p positions. The 4-fold resonance stabilisation dramatically lowers the energy of C₆H₅O⁻ relative to C₆H₅OH, shifting equilibrium toward dissociation.",
    relatedConcepts: ["Resonance stabilisation", "Conjugate base stability", "pKa", "Phenoxide"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "Very High",
      pyqCount: 40,
      lastAsked: 2024,
      tags: ["phenol", "acidity", "resonance", "pKa"],
    },
    ncertReferences: ["Class 12 — Alcohols, Phenols and Ethers (Ch. 11)"],
    memoryTriggers: [
      "Phenoxide = negative charge shared with ring (resonance) = stable anion = stronger acid",
      "pKa 10 (phenol) < 16 (ethanol) = phenol is 10⁶ times more acidic",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "phenol-less-acidic-carboxylic",
    title: "Phenol is less acidic than carboxylic acids",
    category: "Organic",
    chapter: "Carboxylic Acids",
    type: "Anomalous Property",
    observation: "Carboxylic acids (pKa ≈ 4–5) are much more acidic than phenol (pKa ≈ 10).",
    explanation: "Carboxylate ion (RCOO⁻) has resonance over 2 equivalent oxygen atoms (C=O and C–O⁻ interconvert → complete equivalence). This is STRONGER resonance than phenoxide, where charge is delocalised over a large ring (charge density is lower at O). Additionally, RCOO⁻ can be stabilised by both O atoms simultaneously (equivalent resonance structures).",
    relatedConcepts: ["Carboxylate resonance", "Phenoxide resonance", "Acid strength comparison"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "High",
      pyqCount: 22,
      lastAsked: 2024,
      tags: ["carboxylic-acid", "phenol", "acidity-order"],
    },
    ncertReferences: ["Class 12 — Carboxylic Acids (Ch. 12)"],
    memoryTriggers: [
      "RCOOH > PhOH > ROH in acidity (remember the order)",
      "Carboxylate: 2 oxygens share negative charge equally = maximum stabilisation",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "markovnikov-anti-hbr-peroxide",
    title: "HBr adds anti-Markovnikov in presence of peroxide (radical mechanism)",
    category: "Organic",
    chapter: "Hydrocarbons / Haloalkanes",
    type: "Mechanism Exception",
    observation: "HBr normally adds to alkenes following Markovnikov's rule (Br goes to more substituted carbon). But in the presence of peroxides (ROOR) or UV light, HBr adds anti-Markovnikov (Br goes to less substituted carbon).",
    explanation: "Peroxides generate free radicals (RO•). Br• (from HBr) adds first to the less substituted carbon (because the more stable radical is at the MORE substituted carbon). H• from HBr then attacks the resulting radical. The regiochemistry is determined by radical stability, not carbocation stability — giving the opposite regiochemistry.",
    deeperReason: "Radical addition is controlled by radical stability (3° > 2° > 1°). In Markovnikov (ionic), carbocation stability controls (3° > 2° > 1°). Both give 3° intermediate, but radical intermediate puts Br on LESS substituted C (Br• adds first to terminal C to give 2° radical).",
    relatedConcepts: ["Radical addition", "Anti-Markovnikov", "Peroxide effect", "Kharash effect"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "High",
      pyqCount: 38,
      lastAsked: 2024,
      tags: ["anti-Markovnikov", "HBr", "peroxide", "radical", "Kharash"],
    },
    ncertReferences: ["Class 11 — Hydrocarbons (Ch. 13)", "Class 12 — Haloalkanes (Ch. 10)"],
    memoryTriggers: [
      "Peroxide = radical = anti-Markovnikov (Br goes to smaller C)",
      "No peroxide = Markovnikov; Peroxide = anti-Markovnikov (only for HBr, not HCl/HI)",
      "HCl and HI do NOT show anti-Markovnikov even with peroxide",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "hcl-hbr-no-peroxide-effect",
    title: "Anti-Markovnikov addition applies ONLY to HBr, NOT to HCl or HI with peroxide",
    category: "Organic",
    chapter: "Hydrocarbons / Haloalkanes",
    type: "Mechanism Exception",
    observation: "Peroxide effect (anti-Markovnikov radical addition) is observed ONLY for HBr, but NOT for HCl or HI.",
    explanation: "Radical chain propagation requires: (1) X• adds to alkene (exothermic step 1), and (2) X• abstracts H from HX (exothermic step 2). For HCl: Cl• is too reactive — step 1 is fast but Cl• doesn't readily abstract H from HCl to regenerate a chain. Actually HCl step 1 is exothermic enough. For HI: I• is too large and unreactive — I• addition to alkene is endothermic (unstable C–I radical). HBr: Br• is in the 'Goldilocks zone' — both steps are moderately exothermic, making the radical chain efficient.",
    relatedConcepts: ["Radical chain mechanism", "Bond dissociation energies", "Peroxide effect", "Halogen radical reactivity"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "Medium",
      pyqCount: 15,
      lastAsked: 2023,
      tags: ["peroxide-effect", "HBr-only", "radical", "HCl-HI-exception"],
    },
    ncertReferences: ["Class 11 — Hydrocarbons (Ch. 13)"],
    memoryTriggers: [
      "ONLY HBr shows anti-Markovnikov with peroxide (HCl and HI don't)",
      "HBr = perfect radical intermediate; HCl too reactive; HI too slow",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "hofmann-vs-saytzeff",
    title: "Hofmann's rule product vs Saytzeff's rule product",
    category: "Organic",
    chapter: "Haloalkanes and Haloarenes / Amines",
    type: "Rule Violation",
    observation: "Elimination reactions normally give the more substituted alkene (Saytzeff/Zaitsev rule). But with bulky bases (like t-BuOK/t-BuOH) or quaternary ammonium salts (Hofmann exhaustive methylation), the LESS substituted alkene (Hofmann product) predominates.",
    explanation: "Bulky bases cannot easily access internal (hindered) β-H. They prefer to abstract the more accessible terminal β-H (primary carbon), giving the less substituted alkene. Hofmann quaternary ammonium elimination: large N⁺(CH₃)₃ leaving group departs, base takes β-H from the LESS hindered position.",
    relatedConcepts: ["E2 mechanism", "Saytzeff rule", "Hofmann elimination", "Steric effects", "t-BuOK"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Very High",
      neet: "Medium",
      pyqCount: 20,
      lastAsked: 2024,
      tags: ["Hofmann", "Saytzeff", "elimination", "bulky-base", "steric"],
    },
    ncertReferences: ["Class 12 — Haloalkanes and Haloarenes (Ch. 10)", "Class 12 — Amines (Ch. 13)"],
    memoryTriggers: [
      "Saytzeff = more substituted alkene (major). Hofmann = less substituted alkene (major when bulky base).",
      "Bulky base = Hofmann product (less hindered β-H is attacked)",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "aniline-less-basic-aliphatic-amines",
    title: "Aniline is much less basic than aliphatic amines",
    category: "Organic",
    chapter: "Amines",
    type: "Unexpected Reactivity",
    observation: "Aniline (C₆H₅NH₂, pKb ≈ 9.4) is a much weaker base than methylamine (CH₃NH₂, pKb ≈ 3.4). Aniline is barely basic in water.",
    explanation: "In aniline, the lone pair on nitrogen is in conjugation with the benzene ring (N lone pair in p-orbital overlapping with ring π system). This delocalisation stabilises aniline but decreases the electron density on N, making it less available for protonation. In aliphatic amines, no such delocalisation occurs; the lone pair is fully localised on N.",
    relatedConcepts: ["Basicity of amines", "Resonance", "Aniline vs methylamine", "pKb comparison"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "Very High",
      pyqCount: 35,
      lastAsked: 2024,
      tags: ["aniline", "basicity", "resonance", "amines"],
    },
    ncertReferences: ["Class 12 — Amines (Ch. 13)"],
    memoryTriggers: [
      "Aniline N lone pair goes into ring (resonance) = less available for base behaviour",
      "More resonance = less basic (lone pair is 'busy')",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "amine-basicity-order",
    title: "Basicity order of amines in gas phase vs water is different",
    category: "Organic",
    chapter: "Amines",
    type: "Anomalous Property",
    observation: "In the gas phase: (CH₃)₃N > (CH₃)₂NH > CH₃NH₂ > NH₃ (more alkyl = more basic, by induction). In water: (CH₃)₂NH > CH₃NH₂ ≈ (CH₃)₃N > NH₃ (secondary > primary ≈ tertiary > ammonia).",
    explanation: "In water, solvation matters. The conjugate acid (ammonium ion) must be solvated by water. (CH₃)₂NH₂⁺ has 2 N–H bonds available for H-bonding with water (good solvation). (CH₃)₃NH⁺ has only 1 N–H bond (poor solvation). The tertiary ammonium ion is poorly stabilised by water, reducing the effective basicity of trimethylamine in aqueous solution.",
    deeperReason: "Basicity equilibrium: RNH₂ + H₂O ⇌ RNH₃⁺ + OH⁻. Keq depends on both (a) electron density on N (inductive effect: tertiary best) and (b) solvation energy of RNH₃⁺ (secondary ammonium best — can H-bond twice with water).",
    relatedConcepts: ["Basicity of amines", "Solvation effect", "Inductive effect", "Gas phase vs aqueous basicity"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "High",
      pyqCount: 40,
      lastAsked: 2024,
      tags: ["amine-basicity", "solvation", "2°>1°>3°", "water-vs-gas"],
    },
    ncertReferences: ["Class 12 — Amines (Ch. 13)"],
    memoryTriggers: [
      "In water: 2° > 1° > 3° > NH₃ (solvation of 3° ion is poor)",
      "Gas phase: 3° > 2° > 1° > NH₃ (pure inductive effect)",
      "Water solvation reverses 3° vs 2° order",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "fructose-fehling-positive",
    title: "Fructose (ketose) gives positive Fehling's test",
    category: "Organic",
    chapter: "Biomolecules",
    type: "Unexpected Reactivity",
    observation: "Fructose, which is a KETOSE (contains C=O as ketone at C-2), gives a positive Fehling's/Tollens' test. Most ketones do not react with Fehling's solution.",
    explanation: "In alkaline conditions (Fehling's solution is basic), fructose undergoes enolisation and isomerises to glucose and mannose via an enediol intermediate. The resulting aldehydes (glucose, mannose) are then oxidised by Cu²⁺ in Fehling's, giving the positive result.",
    deeperReason: "The α-hydrogen adjacent to the carbonyl in fructose is acidic under basic conditions, allowing enolisation → 1,2-enediol intermediate → isomerisation to aldose. Aldose is then oxidised by Cu²⁺.",
    relatedConcepts: ["Fehling's test", "Reducing sugars", "Enolisation", "Fructose", "Keto-enol tautomerism"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "Very High",
      pyqCount: 35,
      lastAsked: 2024,
      tags: ["fructose", "Fehling's-positive", "ketose", "reducing-sugar"],
    },
    ncertReferences: ["Class 12 — Biomolecules (Ch. 14)"],
    memoryTriggers: [
      "Fructose is a KETOSE but gives positive Fehling's — alkali causes it to tautomerise to aldose",
      "Fructose = 'fooling' you — ketone that acts like an aldehyde in base",
    ],
    reagentIds: ["fehling-solution"],
    reactionIds: [],
  },

  {
    id: "sucrose-non-reducing",
    title: "Sucrose is a non-reducing sugar",
    category: "Organic",
    chapter: "Biomolecules",
    type: "Anomalous Property",
    observation: "Sucrose does not reduce Tollens' or Fehling's reagent (non-reducing sugar), unlike glucose, fructose, maltose, or lactose.",
    explanation: "Sucrose is a disaccharide formed by a glycosidic bond between C-1 of glucose (anomeric carbon) and C-2 of fructose (anomeric carbon). BOTH anomeric carbons are involved in the glycosidic bond, leaving no free anomeric OH group. Without a free hemiacetal (anomeric OH), there is no open-chain form, no free aldehyde, and no reducing property.",
    relatedConcepts: ["Reducing vs non-reducing sugars", "Glycosidic bond", "Anomeric carbon", "Sucrose structure"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "Very High",
      pyqCount: 38,
      lastAsked: 2024,
      tags: ["sucrose", "non-reducing", "anomeric", "disaccharide"],
    },
    ncertReferences: ["Class 12 — Biomolecules (Ch. 14)"],
    memoryTriggers: [
      "Sucrose = both anomeric carbons tied up = no free aldehyde = non-reducing",
      "Sucrose is unique: glucose + fructose joined at BOTH anomeric carbons",
    ],
    reagentIds: ["tollens-reagent", "fehling-solution"],
    reactionIds: [],
  },

  {
    id: "iodoform-not-just-ch3co",
    title: "Iodoform test positive for CH₃CHO and secondary alcohols with CH₃ adjacent to C=O, not just CH₃CO–",
    category: "Organic",
    chapter: "Aldehydes, Ketones",
    type: "Rule Violation",
    observation: "The iodoform test (I₂/NaOH) is commonly stated to be positive for CH₃CO– compounds, but it also gives positive results for CH₃CHO (acetaldehyde) and 2° alcohols of the form CH₃CH(OH)R.",
    explanation: "Iodoform test requires a CH₃CO– group OR a compound that is oxidised TO a CH₃CO– group under alkaline I₂ conditions. I₂/NaOH oxidises CH₃CH(OH)R → CH₃COR, which then gives iodoform. Similarly, CH₃CHO already has the CH₃CO– unit. Ethanol (CH₃CH₂OH) is oxidised to CH₃CHO then to CHI₃.",
    relatedConcepts: ["Iodoform test", "Haloform reaction", "CH₃CO group identification"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "Very High",
      pyqCount: 30,
      lastAsked: 2024,
      tags: ["iodoform", "CH3CO", "halogenation", "identification"],
    },
    ncertReferences: ["Class 12 — Aldehydes, Ketones and Carboxylic Acids (Ch. 12)"],
    memoryTriggers: [
      "Iodoform positive: CH₃COR, CH₃CHO, CH₃CH(OH)R — anything oxidisable to CH₃CO",
      "Ethanol → iodoform positive (oxidised to acetaldehyde first)",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "cannizzaro-no-alpha-h",
    title: "Cannizzaro reaction occurs only with aldehydes having no α-hydrogen",
    category: "Organic",
    chapter: "Aldehydes and Ketones",
    type: "Mechanism Exception",
    observation: "Aldehydes without an α-hydrogen (HCHO, benzaldehyde, chloral) undergo Cannizzaro reaction (self-disproportionation into alcohol + carboxylic acid) in concentrated NaOH. Aldehydes WITH α-H undergo aldol reaction instead.",
    explanation: "Aldol requires α-H for enolate formation. Without α-H, no enolate forms, so the molecule cannot undergo aldol condensation. Instead, hydride transfer between two aldehyde molecules (Cannizzaro mechanism) occurs: one aldehyde acts as hydride donor (→ acid), the other as hydride acceptor (→ alcohol).",
    relatedConcepts: ["Cannizzaro reaction", "Aldol condensation", "α-hydrogen", "Disproportionation"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Very High",
      neet: "Medium",
      pyqCount: 18,
      lastAsked: 2024,
      tags: ["Cannizzaro", "no-alpha-H", "disproportionation", "HCHO"],
    },
    ncertReferences: ["Class 12 — Aldehydes, Ketones and Carboxylic Acids (Ch. 12)"],
    memoryTriggers: [
      "No α-H = no aldol = Cannizzaro (disproportionation)",
      "HCHO and PhCHO = Cannizzaro because no α-H",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "tertiary-amine-no-acetylation",
    title: "Tertiary amines do not undergo acetylation",
    category: "Organic",
    chapter: "Amines",
    type: "Unexpected Reactivity",
    observation: "Primary and secondary amines react with acyl chlorides or acetic anhydride (acetylation) to form amides. Tertiary amines do NOT form amides.",
    explanation: "Acetylation (acylation) requires the N atom to have at least one N–H bond. In tertiary amines (R₃N), there is no N–H bond; the N is fully substituted. Therefore no proton can be lost after N–C(=O) bond formation to generate the amide. Tertiary amines form ammonium salts (not amides) with acyl chlorides.",
    relatedConcepts: ["Acylation", "Amide formation", "N–H requirement", "Tertiary amine"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Medium",
      neet: "High",
      pyqCount: 15,
      lastAsked: 2023,
      tags: ["tertiary-amine", "acetylation", "no-NH", "amide"],
    },
    ncertReferences: ["Class 12 — Amines (Ch. 13)"],
    memoryTriggers: [
      "3° amine = no N–H = can't lose H = can't form amide",
      "3° amine + RCOCl → ammonium salt (not amide)",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BLOCK 4 — d-BLOCK / TRANSITION METALS / COORDINATION CHEMISTRY
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "cr-mo-exception-d5-configuration",
    title: "Cr is [Ar]3d⁵4s¹ (not 3d⁴4s²)",
    category: "Inorganic",
    chapter: "d and f Block Elements",
    type: "Periodic Trend Exception",
    observation: "Expected electronic configuration of Cr (Z=24): [Ar]3d⁴4s². Actual: [Ar]3d⁵4s¹. Cr 'promotes' one 4s electron to 3d to achieve half-filled d subshell.",
    explanation: "Half-filled d subshell (3d⁵) has extra stability due to symmetrical electron distribution and exchange energy. The energy gained by achieving 3d⁵ configuration is greater than the energy required to 'promote' one electron from 4s to 3d.",
    deeperReason: "Exchange energy for 3d⁵ (with 5 unpaired electrons) is significantly higher than for 3d⁴. The extra exchange energy stabilisation outweighs the small 4s–3d energy gap.",
    relatedConcepts: ["Electronic configuration", "Half-filled stability", "Exchange energy", "Cr and Cu exceptions"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "Very High",
      pyqCount: 45,
      lastAsked: 2024,
      tags: ["Cr-configuration", "3d5", "half-filled", "exception"],
    },
    ncertReferences: ["Class 12 — d and f Block Elements (Ch. 8)"],
    memoryTriggers: [
      "Cr = Crazy rebel (half-filled 3d⁵ > expected 3d⁴)",
      "Cr: [Ar]3d⁵4s¹ not 3d⁴4s²",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "cu-exception-d10-configuration",
    title: "Cu is [Ar]3d¹⁰4s¹ (not 3d⁹4s²)",
    category: "Inorganic",
    chapter: "d and f Block Elements",
    type: "Periodic Trend Exception",
    observation: "Expected: [Ar]3d⁹4s². Actual: [Ar]3d¹⁰4s¹. Cu promotes one 4s electron to complete the 3d subshell.",
    explanation: "Completely filled d subshell (3d¹⁰) has extra stability due to symmetric electron distribution and maximum exchange energy. Energy of completely filled > half-filled >> unfilled. This extra stability more than compensates for the energy needed to promote the 4s electron.",
    relatedConcepts: ["Electronic configuration", "Completely filled stability", "Cu exception", "d-block"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "Very High",
      pyqCount: 45,
      lastAsked: 2024,
      tags: ["Cu-configuration", "3d10", "completely-filled", "exception"],
    },
    ncertReferences: ["Class 12 — d and f Block Elements (Ch. 8)"],
    memoryTriggers: [
      "Cu = Copper = Completely filled (3d¹⁰) preferred",
      "Cu: [Ar]3d¹⁰4s¹ not 3d⁹4s²",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "mn2-extra-stability",
    title: "Mn²⁺ is unusually stable (3d⁵ configuration)",
    category: "Inorganic",
    chapter: "d and f Block Elements",
    type: "Unexpected Stability",
    observation: "Mn²⁺ (3d⁵) is exceptionally stable. Mn²⁺ salts are pink/pale violet and do not easily oxidise to Mn³⁺. The Mn³⁺/Mn²⁺ standard reduction potential is high (+1.51 V), making Mn³⁺ a strong oxidising agent.",
    explanation: "Mn²⁺ has exactly half-filled 3d⁵ configuration. Removal of another electron to form Mn³⁺ (3d⁴) costs extra energy because it disrupts the half-filled stability of 3d⁵.",
    relatedConcepts: ["Half-filled stability", "Mn²⁺ stability", "Reduction potential", "d-block stability"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "Medium",
      pyqCount: 15,
      lastAsked: 2023,
      tags: ["Mn2+", "3d5", "half-filled", "stability"],
    },
    ncertReferences: ["Class 12 — d and f Block Elements (Ch. 8)"],
    memoryTriggers: [
      "Mn²⁺ stable = half-filled 3d⁵. Going to Mn³⁺ breaks this = requires energy",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "fe3-more-stable-fe2",
    title: "Fe³⁺ is more stable than Fe²⁺ (3d⁵ vs 3d⁶)",
    category: "Inorganic",
    chapter: "d and f Block Elements",
    type: "Unexpected Stability",
    observation: "For iron, Fe³⁺ (3d⁵) is unusually stable despite the higher charge. Many Fe²⁺ compounds oxidise readily to Fe³⁺.",
    explanation: "Fe³⁺ has 3d⁵ (half-filled) which confers extra stability. Fe²⁺ has 3d⁶ (one extra electron beyond half-filled — paired in one orbital). The half-filled 3d⁵ stability favours Fe³⁺ despite the extra ionisation energy cost.",
    relatedConcepts: ["Fe²⁺ vs Fe³⁺ stability", "Half-filled 3d⁵", "Oxidation states of Fe"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "High",
      pyqCount: 22,
      lastAsked: 2024,
      tags: ["Fe3+", "half-filled", "iron", "stability"],
    },
    ncertReferences: ["Class 12 — d and f Block Elements (Ch. 8)"],
    memoryTriggers: [
      "Fe³⁺ more stable than Fe²⁺ because Fe³⁺ = 3d⁵ (half-filled)",
      "Fe²⁺ has 3d⁶ = one electron beyond half-fill = less stable",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "cu2-less-stable-cu1",
    title: "Cu⁺ and Cu²⁺: Cu²⁺ is more stable in water despite 3d¹⁰ of Cu⁺",
    category: "Inorganic",
    chapter: "d and f Block Elements",
    type: "Unexpected Stability",
    observation: "Cu⁺ has a 3d¹⁰ configuration (completely filled — extra stable) yet Cu²⁺ (3d⁹) is more stable in aqueous solution. Cu⁺ spontaneously disproportionates: 2Cu⁺ → Cu + Cu²⁺.",
    explanation: "In aqueous solution, Cu²⁺ is strongly stabilised by hydration energy (very high charge/size ratio for Cu²⁺). The hydration energy of Cu²⁺ overcomes the ionisation energy required to go from Cu⁺ → Cu²⁺. Overall, Cu²⁺(aq) + Cu(s) is more stable than 2Cu⁺(aq).",
    deeperReason: "ΔG for disproportionation 2Cu⁺(aq) → Cu(s) + Cu²⁺(aq) is negative (ΔG = −RT ln K, K > 1). Hydration enthalpies: Cu²⁺(aq) has much higher hydration than Cu⁺(aq) because of higher charge density.",
    relatedConcepts: ["Disproportionation", "Hydration energy", "Cu oxidation states", "Stability in solution vs solid"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "Medium",
      pyqCount: 16,
      lastAsked: 2024,
      tags: ["Cu+", "Cu2+", "disproportionation", "hydration-energy"],
    },
    ncertReferences: ["Class 12 — d and f Block Elements (Ch. 8)"],
    memoryTriggers: [
      "Cu⁺ (3d¹⁰) seems stable but disproportionates in water: hydration of Cu²⁺ wins",
      "Cu⁺ in water = unstable; Cu²⁺ in water = stable (hydration energy too good)",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BLOCK 5 — p-BLOCK INORGANIC EXCEPTIONS
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "inert-pair-effect",
    title: "Inert Pair Effect in heavier p-block elements",
    category: "Inorganic",
    chapter: "p-Block Elements",
    type: "Inert Pair Effect",
    observation: "Heavier members of Group 13 (Tl), Group 14 (Pb, Sn), Group 15 (Bi, Sb) prefer lower oxidation states (Tl⁺ over Tl³⁺, Pb²⁺ over Pb⁴⁺, Bi³⁺ over Bi⁵⁺), while lighter members prefer higher oxidation states.",
    explanation: "In heavier elements, the valence ns² electrons become progressively more inert (less willing to participate in bonding) due to poor shielding by the intervening d and f electrons (relativistic contraction of ns orbital). The 6s² pair in Tl, Pb, Bi is especially inert (relativistic effect).",
    deeperReason: "As elements get heavier, the 6s orbital contracts due to relativistic effects (electrons travel close to speed of light near heavy nuclei). This lowers the energy of 6s and makes it harder to ionise. The energy needed to involve 6s² in bonding is not compensated by the bond energies formed.",
    relatedConcepts: ["Inert pair effect", "Relativistic contraction", "Oxidation states p-block", "Tl Pb Bi chemistry"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "High",
      pyqCount: 35,
      lastAsked: 2024,
      tags: ["inert-pair", "Pb", "Tl", "Bi", "p-block", "oxidation-state"],
    },
    ncertReferences: ["Class 12 — p-Block Elements (Ch. 11, 12)"],
    memoryTriggers: [
      "Inert pair = ns² pair too lazy to participate in heavier p-block elements",
      "Tl prefers +1, Pb prefers +2, Bi prefers +3 (lower OS) due to inert pair",
      "Goes DOWN the group: inert pair effect increases",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "no2-dimer",
    title: "NO₂ dimerises to N₂O₄",
    category: "Inorganic",
    chapter: "p-Block Elements",
    type: "Anomalous Property",
    observation: "NO₂ (brown, paramagnetic, odd-electron molecule) exists in equilibrium with N₂O₄ (colourless, diamagnetic dimer). At low temperatures, the equilibrium favours N₂O₄; at high temperatures, NO₂ predominates.",
    explanation: "NO₂ has an odd electron (unpaired electron) making it a radical. Two NO₂ radicals pair their electrons to form N₂O₄ (dinitrogen tetroxide, all electrons paired). This is an endothermic dissociation (N₂O₄ → 2NO₂, ΔH > 0) but entropy-driven (2 molecules from 1), so high temperature favours NO₂.",
    relatedConcepts: ["Dimerisation", "Radical species", "N₂O₄", "Temperature-dependent equilibrium"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "High",
      pyqCount: 20,
      lastAsked: 2024,
      tags: ["NO2", "N2O4", "dimerisation", "paramagnetic"],
    },
    ncertReferences: ["Class 12 — p-Block Elements (Ch. 7)"],
    memoryTriggers: [
      "NO₂ = odd electron = brownish, paramagnetic. Pairs up to give N₂O₄ (colourless, diamagnetic)",
      "Cold = N₂O₄; Hot = NO₂",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "pcl5-dissociation",
    title: "PCl₅ dissociates into PCl₃ + Cl₂ at high temperature",
    category: "Inorganic",
    chapter: "p-Block Elements",
    type: "Anomalous Property",
    observation: "PCl₅ dissociates: PCl₅ ⇌ PCl₃ + Cl₂ at high temperatures. This is an endothermic reaction and is favoured by low pressure and high temperature.",
    explanation: "The axial P–Cl bonds in PCl₅ (TBP geometry) are weaker than equatorial bonds. At high temperatures, sufficient energy is available to break these bonds. The dissociation is endothermic (ΔH > 0) and entropy-increasing (2 products from 1), so both high T and low P shift equilibrium toward dissociation.",
    relatedConcepts: ["Dissociation equilibrium", "Le Chatelier's principle", "PCl₅ shape", "Endothermic equilibrium"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "High",
      pyqCount: 18,
      lastAsked: 2024,
      tags: ["PCl5", "dissociation", "equilibrium", "temperature"],
    },
    ncertReferences: ["Class 11 — Equilibrium (Ch. 7)", "Class 12 — p-Block Elements (Ch. 7)"],
    memoryTriggers: [
      "PCl₅ ⇌ PCl₃ + Cl₂ (endothermic, so heat → dissociation)",
      "High P/Low T → PCl₅; Low P/High T → PCl₃ + Cl₂",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "h2o2-decomposition",
    title: "H₂O₂ is both an oxidising and reducing agent",
    category: "Inorganic",
    chapter: "Hydrogen",
    type: "Unexpected Reactivity",
    observation: "Hydrogen peroxide can ACT AS an oxidising agent (gains electrons) and also as a reducing agent (loses electrons). It bleaches by oxidation. It reduces MnO₄⁻ in acidic solution.",
    explanation: "H₂O₂ contains O in −1 oxidation state, which can be oxidised to 0 (O₂) or reduced to −2 (H₂O). Thus: (1) As oxidant: H₂O₂ gains 2e⁻ → 2OH⁻ or H₂O. (2) As reductant: H₂O₂ loses 2e⁻ → O₂ + 2H⁺.",
    relatedConcepts: ["H₂O₂ structure", "Oxidation state", "Dual nature", "Bleaching", "KMnO₄ reduction"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "Very High",
      pyqCount: 30,
      lastAsked: 2024,
      tags: ["H2O2", "dual-nature", "oxidising", "reducing", "oxygen-state"],
    },
    ncertReferences: ["Class 11 — Hydrogen (Ch. 9)"],
    memoryTriggers: [
      "H₂O₂ = O in −1 state: can go to −2 (gain) or 0 (lose) → dual nature",
      "Strong oxidant OR mild reductant depending on partner",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "diagonal-relationship-li-mg",
    title: "Diagonal Relationship: Li resembles Mg more than Na",
    category: "Inorganic",
    chapter: "s-Block Elements",
    type: "Diagonal Relationship",
    observation: "Lithium (Group 1, Period 2) resembles Magnesium (Group 2, Period 3) in many properties rather than the other alkali metals (Na, K).",
    explanation: "Diagonal neighbours in the periodic table have similar charge-to-radius ratios (ionic potential). Li⁺ and Mg²⁺ have comparable charge density: Li⁺ (r = 76 pm, charge = +1) and Mg²⁺ (r = 72 pm, charge = +2) have similar ionic potentials, leading to similar polarising power and chemical behaviour.",
    deeperReason: "Charge density = charge/radius. Li⁺: 1/76 ≈ 0.013. Mg²⁺: 2/72 ≈ 0.028 — these are similar in their chemical effects on anions (polarisation), solvation, and compound properties.",
    relatedConcepts: ["Diagonal relationship", "Charge density", "Polarising power", "Li vs Na comparison"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "High",
      pyqCount: 22,
      lastAsked: 2024,
      tags: ["diagonal-relationship", "Li-Mg", "s-block", "charge-density"],
    },
    ncertReferences: ["Class 11 — s-Block Elements (Ch. 10)"],
    memoryTriggers: [
      "Li = 'Little' alkali metal — behaves like Mg (not Na)",
      "Li–Mg diagonal: both form nitrides (Li₃N, Mg₃N₂), similar solubility patterns",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "kmno4-green-fused",
    title: "KMnO₄ appears purple but gives green K₂MnO₄ on fusion with KOH",
    category: "Inorganic",
    chapter: "d and f Block Elements",
    type: "Anomalous Property",
    observation: "KMnO₄ (Mn in +7) is purple. When KMnO₄ is reduced (e.g., in neutral/alkaline medium), it forms MnO₄²⁻ (manganate, Mn in +6), which is green. Under strong acid, KMnO₄ is reduced to Mn²⁺ (colourless/pale pink).",
    explanation: "Colour changes track the reduction of Mn: Mn(VII) purple → Mn(VI) green (alkaline) → Mn(IV) brown (neutral, MnO₂) → Mn(II) colourless (acid). The colour depends on the d-d and charge-transfer transitions, which change as oxidation state changes.",
    relatedConcepts: ["KMnO₄ oxidation states", "Colour in transition metals", "Mn oxidation state series"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Medium",
      neet: "High",
      pyqCount: 16,
      lastAsked: 2024,
      tags: ["KMnO4", "colour", "Mn-oxidation-states", "green-manganate"],
    },
    ncertReferences: ["Class 12 — d and f Block Elements (Ch. 8)"],
    memoryTriggers: [
      "MnO₄⁻ (purple) → MnO₄²⁻ (green) → MnO₂ (brown) → Mn²⁺ (colourless)",
      "Acid = colourless; Neutral = brown; Alkaline = green/purple",
    ],
    reagentIds: ["kmno4-acidic", "kmno4-alkaline"],
    reactionIds: [],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BLOCK 6 — PHYSICAL CHEMISTRY EXCEPTIONS
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: "real-gas-z-lt-1",
    title: "Z < 1 for real gases at moderate pressure (gas is more compressible than ideal)",
    category: "Physical",
    chapter: "States of Matter",
    type: "Anomalous Property",
    observation: "At moderate pressures (say 50–100 atm), many real gases have compressibility factor Z < 1 (Z = PV/nRT < 1), meaning the gas occupies LESS volume than predicted by the ideal gas law.",
    explanation: "At moderate pressures, intermolecular ATTRACTIVE forces dominate. These attractions pull gas molecules closer together, reducing the volume. The actual volume is less than ideal, so Z = Vreal/Videal < 1.",
    deeperReason: "Van der Waals equation: (P + a/V²)(V − b) = nRT. At moderate pressures, the 'a/V²' term (attraction correction) is significant and positive, increasing the effective pressure term, so V < Videal. At very high pressures, the 'b' (excluded volume) term dominates, pushing Z > 1.",
    relatedConcepts: ["Compressibility factor", "Van der Waals forces", "Z > 1 vs Z < 1", "Real gas"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "High",
      pyqCount: 28,
      lastAsked: 2024,
      tags: ["Z-factor", "real-gas", "compressibility", "moderate-pressure"],
    },
    ncertReferences: ["Class 11 — States of Matter (Ch. 5)"],
    memoryTriggers: [
      "Z < 1: attractions dominant → gas squeezed tighter than ideal",
      "Z > 1: repulsions dominant (high P) → gas takes more volume than ideal",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "raoult-law-positive-deviation",
    title: "Positive deviation from Raoult's Law when A–B interactions weaker than A–A and B–B",
    category: "Physical",
    chapter: "Solutions",
    type: "Rule Violation",
    observation: "Positive deviation: observed vapour pressure > ideal vapour pressure. Examples: acetone–CS₂, ethanol–water, acetone–benzene.",
    explanation: "Positive deviation occurs when A–B intermolecular interactions are WEAKER than A–A and B–B interactions. When A and B are mixed, some A–A and B–B bonds are replaced by weaker A–B bonds. This releases more molecules to the vapour phase → higher vapour pressure → positive deviation. ΔHmix > 0 (endothermic), ΔVmix > 0 (volume increases).",
    relatedConcepts: ["Raoult's law", "Positive deviation", "Colligative properties", "Azeotrope"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "High",
      pyqCount: 25,
      lastAsked: 2024,
      tags: ["Raoult's-law", "positive-deviation", "vapour-pressure", "azeotrope"],
    },
    ncertReferences: ["Class 12 — Solutions (Ch. 2)"],
    memoryTriggers: [
      "Positive deviation = weaker A–B interactions = more molecules escape = higher VP",
      "ΔHmix > 0; ΔVmix > 0 for positive deviation",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "colligative-strong-electrolyte",
    title: "Strong electrolytes show greater colligative effects than expected from formula",
    category: "Physical",
    chapter: "Solutions",
    type: "Rule Violation",
    observation: "NaCl in water lowers the freezing point by almost twice as much as urea at the same molal concentration, because NaCl dissociates into 2 particles (Na⁺ + Cl⁻) while urea remains as 1 particle.",
    explanation: "Colligative properties depend on the NUMBER of particles in solution, not their nature. van't Hoff factor i = actual particles / formula units. For NaCl: i ≈ 2 (in dilute solution). For glucose: i = 1. ΔTf = i × Kf × m.",
    relatedConcepts: ["van't Hoff factor", "Colligative properties", "Strong electrolyte", "Dissociation"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "Very High",
      pyqCount: 35,
      lastAsked: 2024,
      tags: ["van't-Hoff", "colligative", "electrolyte", "i-factor"],
    },
    ncertReferences: ["Class 12 — Solutions (Ch. 2)"],
    memoryTriggers: [
      "i = number of particles in solution. NaCl: i = 2; Na₂SO₄: i = 3",
      "ΔTf = i × Kf × m (multiply by i for electrolytes)",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "entropy-decrease-spontaneous",
    title: "Some spontaneous processes show decrease in entropy (ΔS < 0)",
    category: "Physical",
    chapter: "Thermodynamics",
    type: "Rule Violation",
    observation: "Spontaneity does not always require ΔS > 0. Crystallisation of water from solution at 0°C is spontaneous, yet ΔS < 0 (more ordered solid from less ordered liquid).",
    explanation: "Spontaneity is governed by Gibbs free energy: ΔG = ΔH − TΔS. A process is spontaneous when ΔG < 0. If ΔH < 0 (exothermic) and |ΔH| > T|ΔS|, the process can be spontaneous even with ΔS < 0.",
    relatedConcepts: ["Gibbs free energy", "Spontaneity", "ΔG", "ΔS < 0 spontaneous"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "High",
      pyqCount: 25,
      lastAsked: 2024,
      tags: ["entropy", "spontaneity", "Gibbs", "ΔG"],
    },
    ncertReferences: ["Class 11 — Thermodynamics (Ch. 6)"],
    memoryTriggers: [
      "Spontaneous ≠ must increase entropy. ΔG < 0 is the real criterion.",
      "If ΔH < 0 and large enough, negative ΔS is still OK (ΔG < 0)",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "sn2-primary-faster-than-3",
    title: "SN2 rate: primary > secondary > tertiary (opposite to carbocation stability)",
    category: "Organic",
    chapter: "Haloalkanes",
    type: "Rule Violation",
    observation: "For SN2, primary alkyl halides react fastest, secondary are slower, and tertiary are extremely slow or don't react. This is the opposite order from SN1 (where tertiary is fastest).",
    explanation: "SN2 goes through a single transition state where the nucleophile attacks from behind (backside attack) while the leaving group departs. Steric hindrance around the electrophilic carbon is the dominant factor. Tertiary carbons are surrounded by 3 bulky alkyl groups that block the approach of the nucleophile.",
    relatedConcepts: ["SN2 mechanism", "Steric hindrance", "SN1 vs SN2", "Rate comparison"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "High",
      pyqCount: 40,
      lastAsked: 2024,
      tags: ["SN2", "primary-faster", "steric-hindrance", "rate-order"],
    },
    ncertReferences: ["Class 12 — Haloalkanes and Haloarenes (Ch. 10)"],
    memoryTriggers: [
      "SN2: 1° > 2° > 3° (steric blocks backside attack for tertiary)",
      "SN1: 3° > 2° > 1° (carbocation stability). Opposite to SN2!",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "e2-anti-periplanar",
    title: "E2 elimination requires anti-periplanar geometry",
    category: "Organic",
    chapter: "Haloalkanes",
    type: "Mechanism Exception",
    observation: "E2 elimination requires the β-H and the leaving group to be anti-periplanar (dihedral angle = 180°). If the molecule is locked such that the anti conformation is not accessible, E2 is very slow or doesn't occur.",
    explanation: "E2 is a concerted mechanism: base removes β-H and leaving group departs simultaneously. Orbital overlap requires the breaking C–H bond, forming C=C π bond, and breaking C–LG bond to be in the same plane and anti to each other (anti-periplanar). This is when orbital overlap is maximised for the E2 transition state.",
    relatedConcepts: ["E2 mechanism", "Anti-periplanar", "Dihedral angle", "Stereochemistry"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Very High",
      neet: "Medium",
      pyqCount: 15,
      lastAsked: 2023,
      tags: ["E2", "anti-periplanar", "geometry", "stereospecific"],
    },
    ncertReferences: ["Class 12 — Haloalkanes (Ch. 10)"],
    memoryTriggers: [
      "E2 requires H and LG on opposite sides (anti-periplanar, 180°)",
      "If molecule can't achieve anti-periplanar → E2 blocked",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "meta-deactivation-no-direct",
    title: "Meta-directing groups give meta product — NOT because meta is activated",
    category: "Organic",
    chapter: "Aromatic Compounds",
    type: "Mechanism Exception",
    observation: "EWGs (NO₂, CHO, CN, CF₃) direct incoming electrophiles to the meta position. This is NOT because meta is activated — it is because ortho and para are MORE deactivated.",
    explanation: "EWGs on benzene withdraw electron density via resonance (or induction) from ortho and para positions. The Wheland intermediate (arenium ion) for ortho/para attack has a resonance structure with positive charge ON the carbon bearing the EWG — destabilising. For meta attack, no such destabilising resonance structure exists. So meta carbocation is 'least bad', not 'good'.",
    deeperReason: "Meta attack Wheland intermediate: the positive charge is at ortho and para to the EWG but NOT directly on the ipso (EWG-bearing) carbon. So meta is least destabilised, not actually stabilised — the EWG still deactivates overall, just deactivates ortho/para more.",
    relatedConcepts: ["EAS", "Meta-direction", "Wheland intermediate", "Deactivation", "Resonance"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "High",
      pyqCount: 35,
      lastAsked: 2024,
      tags: ["meta-direction", "EWG", "EAS", "Wheland-intermediate"],
    },
    ncertReferences: ["Class 11 — Hydrocarbons (Ch. 13)"],
    memoryTriggers: [
      "Meta directing = ortho and para are MORE blocked (not that meta is good)",
      "EWG deactivates all positions but ortho/para worst → meta wins by default",
    ],
    reagentIds: [],
    reactionIds: [],
  },

  {
    id: "nacl-not-precipitate-agcl-without-agno3",
    title: "NaCl dissolves freely in water; precipitate forms only with AgNO₃",
    category: "Inorganic",
    chapter: "Ionic Equilibrium",
    type: "Solubility Exception",
    observation: "NaCl is highly soluble (ionic compound) but AgCl is nearly insoluble (Ksp = 1.8 × 10⁻¹⁰). When AgNO₃ is added to NaCl solution, white AgCl precipitates immediately.",
    explanation: "Solubility is governed by the lattice energy vs hydration energy balance. Na⁺ and Cl⁻ are solvated very well by water (high hydration energies). Ag⁺ has a smaller radius and poorer hydration, but more importantly the Ag–Cl interaction is partly covalent (Ag⁺ is a soft metal — polarises Cl⁻ significantly), making the AgCl lattice unusually stable. The covalent character increases the lattice energy and reduces solubility.",
    relatedConcepts: ["Ksp", "Lattice energy", "Hydration energy", "Covalent character", "Fajans' rules", "Halide precipitates"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "High",
      pyqCount: 20,
      lastAsked: 2024,
      tags: ["AgCl", "Ksp", "covalent-character", "Fajans"],
    },
    ncertReferences: ["Class 11 — Ionic Equilibrium (Ch. 7)", "Class 12 — Haloalkanes (Ch. 10)"],
    memoryTriggers: [
      "AgCl insoluble because Ag⁺ is soft (polarises Cl⁻) → covalent character",
      "Fajans: small high-charge cation + large polarisable anion = covalent = insoluble",
    ],
    reagentIds: [],
    reactionIds: [],
  },

];

// ─────────────────────────────────────────────────────────────────────────────
// Lookup helpers
// ─────────────────────────────────────────────────────────────────────────────

const _byId = new Map<string, ChemException>(EXCEPTIONS.map((e) => [e.id, e]));

export function getException(id: string): ChemException | undefined {
  return _byId.get(id);
}

export function getExceptionsByChapter(chapter: string): ChemException[] {
  const q = chapter.toLowerCase();
  return EXCEPTIONS.filter((e) => e.chapter.toLowerCase().includes(q));
}

export function getExceptionsByType(type: ChemException["type"]): ChemException[] {
  return EXCEPTIONS.filter((e) => e.type === type);
}

export function getHighYieldExceptions(): ChemException[] {
  const FREQ_RANK = { "None": 0, "Low": 1, "Medium": 2, "High": 3, "Very High": 4 };
  return EXCEPTIONS.filter((e) => {
    const maxFreq = Math.max(
      FREQ_RANK[e.examRelevance.jeeMain],
      FREQ_RANK[e.examRelevance.jeeAdvanced],
      FREQ_RANK[e.examRelevance.neet]
    );
    return maxFreq >= 3;
  });
}

export function searchExceptions(query: string): ChemException[] {
  const q = query.toLowerCase();
  return EXCEPTIONS.filter((e) =>
    e.title.toLowerCase().includes(q) ||
    e.observation.toLowerCase().includes(q) ||
    e.chapter.toLowerCase().includes(q) ||
    e.examRelevance.tags.some((t) => t.toLowerCase().includes(q))
  );
}
