import type { Reagent } from "./schema";

// ─────────────────────────────────────────────────────────────────────────────
// Phase 2 — Reagent Knowledge Database
// Target: 500+ entries. Current seed: 85 high-yield JEE/NEET reagents.
// Every entry is exam-accurate and cross-linked by ID.
// ─────────────────────────────────────────────────────────────────────────────

export const REAGENTS: Reagent[] = [

  // ── REDUCING AGENTS ───────────────────────────────────────────────────────

  {
    id: "lah",
    name: "Lithium Aluminium Hydride",
    aliases: ["LAH", "LiAlH₄", "Lithium Tetrahydridoaluminate"],
    formula: "LiAlH₄",
    category: "Organic",
    role: "Reducing Agent",
    definition: "A powerful, non-selective hydride reducing agent that reduces almost all carbonyl-containing functional groups and many heteroatom-containing groups.",
    mechanism: "Delivers hydride (H⁻) from Al to the electrophilic carbonyl carbon via a cyclic 4-membered transition state. The reaction proceeds in 4 sequential steps as each H⁻ is delivered. After reduction, aqueous workup releases the product.",
    conditions: ["Anhydrous ether (Et₂O) or THF", "0°C to RT", "Strict anhydrous conditions — reacts violently with water", "Requires cautious aqueous workup (Fieser workup)"],
    selectivity: "Reduces: RCHO > RCOR' > RCOOH > RCOOR' > RCONR'₂ > RCN > RNO₂ > epoxides. Does NOT reduce isolated C=C or C≡C bonds.",
    exceptions: [
      "Does NOT reduce isolated alkenes or alkynes",
      "Reduces amides to amines (unlike NaBH₄)",
      "Reduces carboxylic acids to primary alcohols (NaBH₄ cannot do this)",
      "Reduces RNO₂ to RNH₂",
      "Tertiary amides reduced to tertiary amines",
      "Esters reduced to two alcohols (one primary, one from the acyl portion)",
    ],
    relatedConcepts: ["Nucleophilic addition", "Hydride transfer", "Carbonyl reduction", "Selective reduction"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "High",
      pyqCount: 35,
      lastAsked: 2024,
      tags: ["reduction", "carbonyl", "hydride", "selectivity"],
    },
    ncertReferences: [
      "Class 12 — Aldehydes, Ketones and Carboxylic Acids (Ch. 12)",
      "Class 12 — Amines (Ch. 13)",
    ],
    memoryTriggers: [
      "LAH = EVERYTHING down (powerful reducer, reduces all C=O)",
      "Li-Al-H = Lethal And Harsh — handle with care",
      "Reduces carboxylic acid → primary alcohol (NaBH₄ cannot!)",
    ],
    reactionIds: ["clemmensen-reduction", "rosenmund-reduction"],
    reagentIds: ["nabh4", "dibal-h", "b2h6"],
  },

  {
    id: "nabh4",
    name: "Sodium Borohydride",
    aliases: ["NaBH₄", "Sodium Tetrahydridoborate"],
    formula: "NaBH₄",
    category: "Organic",
    role: "Reducing Agent",
    definition: "A mild, selective hydride reducing agent that reduces only aldehydes and ketones (not carboxylic acids, esters, or amides).",
    mechanism: "Delivers H⁻ from boron to the electrophilic carbonyl carbon. The mild Lewis acidity of boron (compared to Al) restricts reactivity to more electrophilic carbonyls only.",
    conditions: ["Protic solvents (MeOH, EtOH) or THF/water mixtures", "0°C to RT", "Tolerant of water (unlike LAH)"],
    selectivity: "Reduces: RCHO and RCOR' only. Does NOT reduce RCOOH, RCOOR', RCONR'₂, RCN, RNO₂, or C=C bonds.",
    exceptions: [
      "Cannot reduce carboxylic acids or their derivatives (esters, amides)",
      "Works in protic solvents (unlike LAH)",
      "1,2-reduction vs 1,4-reduction: NaBH₄ gives 1,2-reduction (attacks C=O); enone gives allylic alcohol",
      "CeCl₃/NaBH₄ (Luche reduction) gives exclusive 1,2-reduction of α,β-unsaturated carbonyl",
    ],
    relatedConcepts: ["Selective reduction", "Carbonyl reduction", "Chemoselective reagents"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "High",
      pyqCount: 28,
      lastAsked: 2024,
      tags: ["reduction", "aldehyde", "ketone", "selectivity", "mild"],
    },
    ncertReferences: [
      "Class 12 — Aldehydes, Ketones and Carboxylic Acids (Ch. 12)",
    ],
    memoryTriggers: [
      "NaBH₄ = Neat And Boring for H₄ (mild, only does ketone/aldehyde)",
      "Na = Nice and gentle (soft reducer vs LAH's power)",
      "Aldehyde → 1° alcohol; Ketone → 2° alcohol",
    ],
    reactionIds: [],
    reagentIds: ["lah", "dibal-h"],
  },

  {
    id: "dibal-h",
    name: "Diisobutylaluminium Hydride",
    aliases: ["DIBAL-H", "DIBALH", "DIBAL"],
    formula: "(iBu)₂AlH",
    category: "Organic",
    role: "Reducing Agent",
    definition: "A bulky aluminium hydride reagent that reduces esters to aldehydes (not carboxylic acids) when used at low temperature (-78°C).",
    mechanism: "Delivers one H⁻ to the ester carbonyl to form a tetrahedral aluminium alkoxide intermediate. At -78°C this intermediate is stable and does not react further; workup gives the aldehyde. At higher temperatures, the intermediate collapses to deliver a second H⁻ giving a primary alcohol.",
    conditions: ["-78°C in toluene or CH₂Cl₂ for selective aldehyde formation", "RT → primary alcohol from ester", "Requires careful low-temperature control"],
    selectivity: "At -78°C: RCOOR' → RCHO (aldehyde). At RT: RCOOR' → RCH₂OH (primary alcohol). Also reduces lactones to lactols. Reduces nitriles to aldehydes at -78°C.",
    exceptions: [
      "Temperature controls selectivity — unique among hydride reagents",
      "Reduces nitrile to imine (then hydrolysis gives aldehyde) — useful in Strecker synthesis",
      "Does not reduce amides at -78°C",
    ],
    relatedConcepts: ["Selective reduction", "Temperature-controlled selectivity", "Ester reduction"],
    examRelevance: {
      jeeMain: "Medium",
      jeeAdvanced: "High",
      neet: "Low",
      pyqCount: 8,
      lastAsked: 2023,
      tags: ["reduction", "ester-to-aldehyde", "temperature-controlled"],
    },
    ncertReferences: [],
    memoryTriggers: [
      "DIBAL at -78 = Dip In Bottle At Low temperature → stops at aldehyde",
      "Cold DIBAL = aldehyde; Warm DIBAL = alcohol",
    ],
    reactionIds: [],
    reagentIds: ["lah", "nabh4"],
  },

  {
    id: "b2h6",
    name: "Diborane",
    aliases: ["B₂H₆", "BH₃·THF", "Borane"],
    formula: "B₂H₆",
    category: "Organic",
    role: "Hydrogenating Agent",
    definition: "A boron hydride used primarily in hydroboration-oxidation to convert alkenes to anti-Markovnikov alcohols with syn addition.",
    mechanism: "BH₃ adds to the less substituted carbon of the alkene via a 4-membered cyclic transition state (syn addition, concerted). Oxidation with H₂O₂/OH⁻ replaces B with OH with retention of configuration.",
    conditions: ["THF or diglyme as solvent", "BH₃ exists as B₂H₆ dimer in solution", "Oxidation step: H₂O₂/NaOH/H₂O"],
    selectivity: "Anti-Markovnikov addition: H to more substituted carbon, OH to less substituted. Syn addition: both H and OH add to same face.",
    exceptions: [
      "Anti-Markovnikov selectivity (opposite to HBr addition)",
      "Syn (cis) addition — contrast with OsO₄ which also gives syn but different regiochemistry for unsymmetrical alkenes",
      "Alkynes give vinyl boranes: mono-hydroboration gives Z-vinyl alcohol after oxidation",
      "With hindered dialkylboranes (9-BBN): even more regioselective",
      "Carbonyl groups are NOT reduced by B₂H₆ under these conditions",
    ],
    relatedConcepts: ["Markovnikov's rule", "Anti-Markovnikov addition", "Syn addition", "Hydroboration-oxidation"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Very High",
      neet: "Medium",
      pyqCount: 22,
      lastAsked: 2024,
      tags: ["anti-markovnikov", "syn-addition", "alkene", "alcohol"],
    },
    ncertReferences: [
      "Class 12 — Haloalkanes and Haloarenes (reaction context)",
      "Class 11 — Hydrocarbons (alkene reactions)",
    ],
    memoryTriggers: [
      "BH₃ = Boron Hits Less substituted carbon (anti-Markovnikov)",
      "BH₃ then H₂O₂/OH⁻ = B gets kicked out, OH goes in its place (retention)",
      "Both add to same face = syn",
    ],
    reactionIds: ["hydroboration-oxidation"],
    reagentIds: ["osmium-tetroxide", "mcpba"],
  },

  {
    id: "birch-system",
    name: "Sodium / Liquid Ammonia (Birch Reduction System)",
    aliases: ["Na/liq NH₃", "Dissolving metal reduction", "Na–NH₃"],
    formula: "Na / NH₃(l) / ROH",
    category: "Organic",
    role: "Reducing Agent",
    definition: "A dissolving metal reduction system that reduces benzene rings to 1,4-cyclohexadienes and alkynes to trans-alkenes, via radical anion intermediates.",
    mechanism: "Na dissolves in liquid NH₃ releasing solvated electrons (e⁻ₐq). The solvated electron adds to the aromatic ring to give a radical anion, then protonation by an alcohol (ROH) and a second electron transfer gives the 1,4-diene. The unconjugated product is thermodynamically controlled.",
    conditions: ["Liquid NH₃ (−33°C)", "Na or Li metal", "Proton source: t-BuOH or EtOH", "Dry, inert atmosphere"],
    selectivity: "Benzene → 1,4-cyclohexadiene (unconjugated). Electron-donating groups (alkyl, OR): reduction occurs at unsubstituted positions. Electron-withdrawing groups (COOH, COR): reduction at substituted positions. Alkynes: partial reduction to trans-alkene (stereochemistry opposite to Lindlar).",
    exceptions: [
      "Gives UNCONJUGATED 1,4-cyclohexadiene (kinetic product — the non-reduced double bonds avoid the substituent)",
      "EDG on benzene: reduces positions away from substituent",
      "EWG on benzene: reduces positions bearing substituent",
      "Trans alkene from alkyne (opposite to Lindlar which gives cis)",
      "ROH proton source is required — without it, dianion forms and product changes",
    ],
    relatedConcepts: ["Dissolving metal reduction", "Radical anion", "Solvated electron", "Birch selectivity", "Lindlar catalyst"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Very High",
      neet: "Low",
      pyqCount: 14,
      lastAsked: 2024,
      tags: ["Birch", "aromatic", "dissolving-metal", "trans-alkene"],
    },
    ncertReferences: [],
    memoryTriggers: [
      "Birch = Sodium in NH₃ Gives Unconjugated diene",
      "EDG ring: double bonds AWAY from group. EWG ring: double bonds AT the group.",
      "Na/NH₃ for alkynes → TRANS alkene; Lindlar → CIS alkene",
    ],
    reactionIds: ["birch-reduction"],
    reagentIds: ["lindlar-catalyst", "nabh4"],
  },

  {
    id: "lindlar-catalyst",
    name: "Lindlar Catalyst",
    aliases: ["Pd/BaSO₄/quinoline", "Lindlar's catalyst", "Poisoned palladium"],
    formula: "Pd/CaCO₃ + Pb(OAc)₂ + quinoline",
    category: "Organic",
    role: "Hydrogenating Agent",
    definition: "A partially deactivated (poisoned) heterogeneous palladium catalyst that selectively reduces alkynes to cis (Z) alkenes via semi-hydrogenation.",
    mechanism: "Both H₂ molecules adsorb on the Pd surface and are delivered to the same face of the alkyne (syn addition). The catalyst is poisoned enough to stop at the alkene stage and not over-reduce to alkane.",
    conditions: ["H₂ gas atmosphere (1 atm)", "Quinoline or lead acetate as poison", "Solvent: EtOH or ethyl acetate"],
    selectivity: "Alkynes → cis (Z) alkenes only. Isolated alkenes are not reduced further. Does NOT reduce benzene rings.",
    exceptions: [
      "Gives CIS (Z) alkene (syn addition of H₂) — contrast with Na/NH₃ which gives trans (E)",
      "Internal alkynes give Z-internal alkenes",
      "Terminal alkynes give 1-alkenes",
      "Over-reduction to alkane does NOT occur under normal conditions",
    ],
    relatedConcepts: ["Syn addition", "Semi-hydrogenation", "cis/trans isomerism", "Birch reduction"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Very High",
      neet: "Medium",
      pyqCount: 18,
      lastAsked: 2024,
      tags: ["cis-alkene", "semi-hydrogenation", "alkyne", "syn-addition"],
    },
    ncertReferences: [
      "Class 11 — Hydrocarbons (alkynes, Ch. 13)",
    ],
    memoryTriggers: [
      "Lindlar = Lies Down flat (cis) — both H add to same face",
      "Na/NH₃ = sodium makes trans; Lindlar makes cis — opposite faces give opposite stereochemistry",
      "Poisoned Pd = stops halfway at alkene",
    ],
    reactionIds: [],
    reagentIds: ["birch-system", "pd-c"],
  },

  {
    id: "pd-c",
    name: "Palladium on Carbon",
    aliases: ["Pd/C", "10% Pd/C", "Catalytic hydrogenation"],
    formula: "Pd/C",
    category: "Organic",
    role: "Hydrogenating Agent",
    definition: "A heterogeneous palladium catalyst supported on activated charcoal, used for complete catalytic hydrogenation of alkenes, alkynes, and various other functional groups under H₂ atmosphere.",
    mechanism: "H₂ adsorbs on the Pd surface, dissociating into two Pd-H species. The alkene or alkyne adsorbs and both H atoms are delivered from the same face (syn addition). Product desorbs from surface.",
    conditions: ["H₂ gas (1–3 atm)", "EtOH, MeOH, EtOAc as solvent", "RT to mild warming"],
    selectivity: "Reduces alkenes > alkynes > aromatic rings (benzene not reduced under normal conditions). Also reduces RNO₂ → RNH₂, debenzylates Bn-protected groups, removes benzyl groups.",
    exceptions: [
      "Aromatic rings NOT reduced under standard conditions (need Pd + higher pressure/temperature)",
      "Benzyl (Bn) protecting groups cleaved by Pd/C + H₂ (hydrogenolysis)",
      "Adjacent electron-withdrawing groups slow hydrogenation",
      "Sulphur compounds and amines can poison Pd/C",
      "Rosenmund reduction uses Pd/BaSO₄ (poisoned) to stop at aldehyde from acid chloride",
    ],
    relatedConcepts: ["Catalytic hydrogenation", "Syn addition", "Hydrogenolysis", "Rosenmund reduction"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "Medium",
      pyqCount: 20,
      lastAsked: 2024,
      tags: ["hydrogenation", "syn-addition", "heterogeneous-catalysis"],
    },
    ncertReferences: [
      "Class 11 — Hydrocarbons (Ch. 13)",
      "Class 12 — Amines (Ch. 13)",
    ],
    memoryTriggers: [
      "Pd/C + H₂ = Perfectly Delivers both H to same face (syn)",
      "Pd/C removes Bn protecting groups (hydrogenolysis)",
    ],
    reactionIds: ["rosenmund-reduction"],
    reagentIds: ["lindlar-catalyst", "wilkinson-catalyst"],
  },

  {
    id: "clemmensen-system",
    name: "Clemmensen Reduction System",
    aliases: ["Zn-Hg/HCl", "Zn amalgam / conc. HCl", "Clemmensen"],
    formula: "Zn(Hg) / conc. HCl",
    category: "Organic",
    role: "Reducing Agent",
    definition: "A zinc amalgam/HCl system that reduces the carbonyl group (C=O) of ketones and aldehydes directly to a methylene group (CH₂), bypassing alcohol intermediates. Used for acid-stable substrates.",
    mechanism: "Zinc surface catalyses sequential proton and electron transfers to the carbonyl oxygen. The exact mechanism involves carbenoid or organozinc intermediates on the metal surface. The C=O is converted directly to CH₂ without isolable alcohol.",
    conditions: ["Zn-Hg amalgam", "Concentrated HCl", "Aqueous acidic environment", "Reflux conditions"],
    selectivity: "C=O (ketone/aldehyde) → CH₂. Does NOT reduce C=C bonds, COOH, or esters.",
    exceptions: [
      "Works in ACIDIC conditions (contrast with Wolff-Kishner which needs basic conditions)",
      "Acid-sensitive substrates should use Wolff-Kishner instead",
      "Cannot be used if molecule contains acid-labile groups",
      "Carbonyl must NOT be adjacent to another carbonyl (cannot reduce 1,3-diketones effectively)",
      "Aryl ketones (ArCOR) are reduced more easily than dialkyl ketones",
    ],
    relatedConcepts: ["Carbonyl reduction", "Deoxygenation", "Wolff-Kishner reduction", "Ketone to methylene"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "Medium",
      pyqCount: 20,
      lastAsked: 2024,
      tags: ["Clemmensen", "ketone-to-methylene", "acid-conditions"],
    },
    ncertReferences: [
      "Class 12 — Aldehydes, Ketones and Carboxylic Acids (Ch. 12)",
    ],
    memoryTriggers: [
      "Clemmensen = Cl in acid → CH₂ (ketone goes to methylene in acid)",
      "Zn-Hg + HCl = Zinc Hits Carbon hard (removes oxygen)",
      "ACID conditions → Clemmensen; BASE conditions → Wolff-Kishner",
    ],
    reactionIds: ["clemmensen-reduction", "wolff-kishner-reduction"],
    reagentIds: ["wolff-kishner-system", "lah"],
  },

  {
    id: "wolff-kishner-system",
    name: "Wolff-Kishner Reduction System",
    aliases: ["N₂H₄/KOH", "Hydrazine/KOH/ethylene glycol", "Huang Minlon modification"],
    formula: "N₂H₄·H₂O / KOH / Δ",
    category: "Organic",
    role: "Reducing Agent",
    definition: "A base-mediated reduction of ketones and aldehydes to methylene groups via a hydrazone intermediate, used for base-stable substrates.",
    mechanism: "Step 1: N₂H₄ condenses with C=O to form hydrazone (C=NNH₂). Step 2: In strong base (KOH), hydrazone loses H⁺ to form carbanion/imine anion, which ejects N₂ and picks up a proton from solvent. Result: C=O → CH₂ + N₂↑.",
    conditions: ["N₂H₄ or N₂H₄·H₂O", "KOH or NaOH (strong base)", "High boiling solvent (ethylene glycol, 180–200°C) or Huang Minlon modification", "Long reflux"],
    selectivity: "C=O (ketone/aldehyde) → CH₂. Same selectivity as Clemmensen but under basic conditions.",
    exceptions: [
      "Works in BASIC conditions (opposite to Clemmensen which requires acid)",
      "N₂ is evolved (gas) — driving force",
      "Cannot use with acid-labile groups but safe for base-stable substrates",
      "Huang Minlon modification: uses diethylene glycol, adds KOH after hydrazone forms (one-pot)",
      "Carbonyl adjacent to EWG can form stable hydrazone that is difficult to decompose",
    ],
    relatedConcepts: ["Hydrazone formation", "Carbonyl reduction", "Deoxygenation", "Clemmensen reduction"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "Medium",
      pyqCount: 18,
      lastAsked: 2024,
      tags: ["Wolff-Kishner", "ketone-to-methylene", "base-conditions", "hydrazone"],
    },
    ncertReferences: [
      "Class 12 — Aldehydes, Ketones and Carboxylic Acids (Ch. 12)",
    ],
    memoryTriggers: [
      "Wolff-Kishner = NaOH (base) + N₂H₄ (hydrazine) → CH₂ + N₂ gas",
      "BASE = Wolff-Kishner; ACID = Clemmensen — opposite conditions",
      "Wolff-Kishner: nitrogen leaves (N₂) and takes the oxygen with it conceptually",
    ],
    reactionIds: ["wolff-kishner-reduction"],
    reagentIds: ["clemmensen-system"],
  },

  // ── OXIDISING AGENTS ──────────────────────────────────────────────────────

  {
    id: "kmno4-acidic",
    name: "Potassium Permanganate (Acidic)",
    aliases: ["KMnO₄/H⁺", "KMnO₄/H₂SO₄", "Hot acidic KMnO₄"],
    formula: "KMnO₄ / H₂SO₄",
    category: "Organic",
    role: "Oxidising Agent",
    definition: "A strong oxidant under acidic conditions that cleaves C=C double bonds, oxidises primary alcohols to carboxylic acids, and oxidises toluene and its derivatives to benzoic acids.",
    mechanism: "Permanganate (MnO₄⁻) acts as an electrophilic oxidant. In acid: Mn(VII) → Mn(II). Alkene oxidative cleavage proceeds through a manganate ester intermediate that is hydrolysed.",
    conditions: ["H₂SO₄ (dilute or conc)", "Reflux for complete cleavage", "Purple solution turns colourless (MnSO₄)"],
    selectivity: "Terminal alkene (RCH=CH₂) → RCOOH + CO₂. Internal alkene (RCH=CHR') → RCOOH + R'COOH. Disubstituted alkene (R₂C=CR'₂) → R₂C=O (ketone, not cleaved further). ArCH₃ → ArCOOH. Primary alcohol → carboxylic acid. Secondary alcohol → ketone.",
    exceptions: [
      "Ketone carbons in R₂C= are NOT oxidised (no α-H to the carbonyl at that position)",
      "Ozonolysis also cleaves C=C but gives different products depending on workup",
      "Cold dilute KMnO₄ (alkaline) gives syn dihydroxylation (Baeyer's reagent) — completely different!",
      "Purple → colourless is a positive test for unsaturation (Baeyer's test)",
    ],
    relatedConcepts: ["Oxidative cleavage", "Baeyer's test", "Syn dihydroxylation", "Primary alcohol oxidation"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "High",
      pyqCount: 40,
      lastAsked: 2024,
      tags: ["oxidation", "alkene-cleavage", "Baeyer's-test", "permanganate"],
    },
    ncertReferences: [
      "Class 11 — Hydrocarbons (Ch. 13)",
      "Class 12 — Aldehydes, Ketones (Ch. 12)",
      "Class 12 — p-Block Elements (Ch. 7) — KMnO₄ preparation",
    ],
    memoryTriggers: [
      "Hot KMnO₄ in acid = Kills C=C (cleaves to RCOOH)",
      "Purple disappears = unsaturation detected (Baeyer's test)",
      "Toluene + KMnO₄/H⁺/Δ = Benzoic acid (chain burned off)",
    ],
    reactionIds: ["baeyer-test"],
    reagentIds: ["kmno4-alkaline", "osmium-tetroxide", "ozone"],
  },

  {
    id: "kmno4-alkaline",
    name: "Potassium Permanganate (Cold, Dilute, Alkaline)",
    aliases: ["Baeyer's reagent", "Cold KMnO₄", "KMnO₄/OH⁻"],
    formula: "KMnO₄ (dilute, cold, aq.)",
    category: "Organic",
    role: "Oxidising Agent",
    definition: "Cold, dilute, aqueous KMnO₄ that performs syn (cis) dihydroxylation of alkenes to give vicinal diols without cleavage of the double bond.",
    mechanism: "Permanganate forms a cyclic manganate ester with both carbons of the alkene simultaneously (syn addition) via a 5-membered cyclic transition state. Hydrolysis gives the syn diol and MnO₂ (brown precipitate).",
    conditions: ["Dilute KMnO₄ (1–2% solution)", "Cold (0–5°C)", "Aqueous or slightly alkaline", "Purple → brown MnO₂ precipitate"],
    selectivity: "Alkene → syn (cis) vicinal diol. Same faces receive both OH groups. Brown precipitate confirms positive Baeyer's test.",
    exceptions: [
      "Gives SYN dihydroxylation (same face) — contrast with OsO₄ (also syn) and Br₂ addition (anti)",
      "Cold conditions essential — hot/concentrated KMnO₄ would cleave the C=C",
      "Brown precipitate (MnO₂) ≠ colourless (as with hot KMnO₄/H⁺ giving Mn²⁺)",
      "Cannot distinguish from OsO₄ on regiochemistry alone — both give syn diol",
    ],
    relatedConcepts: ["Baeyer's test", "Syn dihydroxylation", "Vicinal diol", "OsO₄ dihydroxylation"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "High",
      pyqCount: 25,
      lastAsked: 2024,
      tags: ["Baeyer's-test", "dihydroxylation", "syn", "cis-diol"],
    },
    ncertReferences: [
      "Class 11 — Hydrocarbons (Ch. 13)",
    ],
    memoryTriggers: [
      "Baeyer's = Brown precipitate, syn diol (both OH same side)",
      "Cold KMnO₄ = diol (no cleavage); Hot KMnO₄ = cleavage",
      "Purple → Brown = positive Baeyer's test for C=C",
    ],
    reactionIds: ["baeyer-test"],
    reagentIds: ["kmno4-acidic", "osmium-tetroxide"],
  },

  {
    id: "osmium-tetroxide",
    name: "Osmium Tetroxide",
    aliases: ["OsO₄", "Osmium(VIII) oxide"],
    formula: "OsO₄",
    category: "Organic",
    role: "Oxidising Agent",
    definition: "A highly toxic but extremely reliable reagent for syn dihydroxylation of alkenes, giving vicinal cis diols with complete stereospecificity.",
    mechanism: "OsO₄ undergoes a concerted [3+2] cycloaddition with the alkene double bond to form a cyclic osmate ester. Hydrolysis (with NMO or H₂O₂ for catalytic version) releases the syn diol and the Os is reoxidised.",
    conditions: ["Catalytic OsO₄ with NMO (N-methylmorpholine-N-oxide) as co-oxidant (Upjohn process)", "Stoichiometric: pyridine/acetone", "Highly toxic — handle with extreme care", "Very slow reaction without co-oxidant"],
    selectivity: "Alkene → syn (cis) vicinal diol. 100% stereospecific. In the Sharpless asymmetric dihydroxylation (AD), chiral ligands (DHQD or DHQ) give enantioselective diols.",
    exceptions: [
      "100% syn selectivity (more reliable than KMnO₄ which can give some anti product)",
      "Used in Sharpless AD (Nobel Prize 2001) for asymmetric synthesis",
      "Extremely toxic (volatile, can absorb through skin — osmate fumes are dangerous)",
      "AD-mix-α and AD-mix-β contain OsO₄ with chiral ligands for enantioselective diols",
    ],
    relatedConcepts: ["Syn dihydroxylation", "Sharpless AD", "Enantioselective synthesis", "Upjohn process"],
    examRelevance: {
      jeeMain: "Medium",
      jeeAdvanced: "High",
      neet: "Low",
      pyqCount: 8,
      lastAsked: 2023,
      tags: ["syn-dihydroxylation", "cis-diol", "stereospecific", "OsO4"],
    },
    ncertReferences: [],
    memoryTriggers: [
      "OsO₄ = Oh So Syn (100% cis diol)",
      "OsO₄ → cyclic osmate ester → hydrolysis → syn diol",
    ],
    reactionIds: [],
    reagentIds: ["kmno4-alkaline", "mcpba"],
  },

  {
    id: "pcc",
    name: "Pyridinium Chlorochromate",
    aliases: ["PCC", "Corey-Suggs reagent", "Pyridine·HCl·CrO₃"],
    formula: "C₅H₅NH⁺ CrO₃Cl⁻",
    category: "Organic",
    role: "Oxidising Agent",
    definition: "A mild chromium(VI) oxidant that oxidises primary alcohols to aldehydes (stopping before carboxylic acid) and secondary alcohols to ketones. Does not oxidise aldehydes further.",
    mechanism: "Chromate ester forms between the alcohol oxygen and Cr. The ester undergoes an E2-like elimination with loss of HCrO₃⁻, cleaving the O–H bond and the α C–H bond simultaneously to give the carbonyl compound.",
    conditions: ["CH₂Cl₂ solvent", "RT or mild warming", "Anhydrous conditions (water causes over-oxidation to acid)", "Mildly acidic"],
    selectivity: "1° ROH → RCHO (aldehyde, NOT carboxylic acid). 2° ROH → R₂C=O (ketone). Does NOT oxidise RCHO to RCOOH.",
    exceptions: [
      "Anhydrous CH₂Cl₂ is essential — water causes the reagent to over-oxidise to carboxylic acid",
      "Allylic and benzylic alcohols oxidised smoothly",
      "Does NOT cleave C=C double bonds (unlike KMnO₄)",
      "PDC (pyridinium dichromate) is a milder alternative, also stops at aldehyde",
    ],
    relatedConcepts: ["Selective alcohol oxidation", "Chromium(VI) oxidation", "Primary alcohol to aldehyde"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Very High",
      neet: "Medium",
      pyqCount: 22,
      lastAsked: 2024,
      tags: ["PCC", "primary-alcohol-to-aldehyde", "selective-oxidation"],
    },
    ncertReferences: [
      "Class 12 — Aldehydes, Ketones and Carboxylic Acids (Ch. 12)",
    ],
    memoryTriggers: [
      "PCC = Politely Converts to Carbonyl (stops at aldehyde, no further)",
      "PCC in CH₂Cl₂ (dry) = 1° alcohol → aldehyde (NOT acid)",
      "Jones/K₂Cr₂O₇ = goes all the way to acid; PCC = stops at aldehyde",
    ],
    reactionIds: [],
    reagentIds: ["jones-reagent", "swern-oxidation"],
  },

  {
    id: "jones-reagent",
    name: "Jones Reagent",
    aliases: ["CrO₃/H₂SO₄/acetone", "Jones oxidation", "Cr(VI)/H₂SO₄"],
    formula: "CrO₃ / H₂SO₄ / acetone",
    category: "Organic",
    role: "Oxidising Agent",
    definition: "A chromium(VI) oxidant in acidic aqueous conditions that converts primary alcohols to carboxylic acids and secondary alcohols to ketones.",
    mechanism: "Formation of chromate ester, followed by oxidative elimination. The aqueous acidic medium allows continued oxidation of the initially formed aldehyde to the carboxylic acid.",
    conditions: ["CrO₃ dissolved in H₂SO₄/H₂O", "Acetone as co-solvent", "Cold conditions (0–10°C)", "Aqueous acidic"],
    selectivity: "1° ROH → RCOOH (goes all the way). 2° ROH → R₂C=O. Aldehydes → carboxylic acids. Does NOT oxidise C=C.",
    exceptions: [
      "Goes all the way to carboxylic acid (unlike PCC which stops at aldehyde)",
      "Sensitive allylic/tertiary positions sometimes over-oxidised",
      "Cannot use with acid-sensitive substrates",
    ],
    relatedConcepts: ["Primary alcohol oxidation", "Chromium(VI) oxidation", "PCC comparison"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "Medium",
      pyqCount: 15,
      lastAsked: 2023,
      tags: ["Jones", "primary-alcohol-to-acid", "oxidation"],
    },
    ncertReferences: [],
    memoryTriggers: [
      "Jones = Goes all the way (acid from 1° alcohol)",
      "PCC stops at aldehyde; Jones goes to acid — remember PCC is polite, Jones is aggressive",
    ],
    reactionIds: [],
    reagentIds: ["pcc", "k2cr2o7"],
  },

  {
    id: "k2cr2o7",
    name: "Potassium Dichromate",
    aliases: ["K₂Cr₂O₇", "Dichromate", "K-dichromate"],
    formula: "K₂Cr₂O₇",
    category: "Organic",
    role: "Oxidising Agent",
    definition: "An orange chromium(VI) oxidant commonly used in acidic aqueous solution to oxidise primary and secondary alcohols. Orange → green colour change indicates reduction of Cr(VI) → Cr(III).",
    mechanism: "Cr₂O₇²⁻ in acid forms HCrO₄⁻ which forms a chromate ester with the alcohol, followed by elimination. Orange Cr(VI) → green Cr(III)(CrSO₄).",
    conditions: ["H₂SO₄ (dilute or conc)", "Aqueous", "Reflux for complete oxidation", "Orange solution → green when oxidant is consumed"],
    selectivity: "1° ROH → RCOOH. 2° ROH → ketone. 3° ROH → no reaction (no α-H). Colour change: orange → green.",
    exceptions: [
      "3° alcohols are NOT oxidised (no α-H adjacent to OH)",
      "Orange → green is a positive test for primary/secondary alcohol (Lucas test uses ZnCl₂, not dichromate)",
      "Used in breathalyser (ethanol → ethanoic acid, Cr₂O₇²⁻ (orange) → Cr³⁺ (green))",
    ],
    relatedConcepts: ["Alcohol oxidation", "Chromium(VI)", "Breathalyser", "Oxidation state"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Medium",
      neet: "High",
      pyqCount: 18,
      lastAsked: 2024,
      tags: ["dichromate", "alcohol-oxidation", "colour-change", "breathalyser"],
    },
    ncertReferences: [
      "Class 11 — Redox Reactions (Ch. 8)",
      "Class 12 — Alcohols, Phenols and Ethers (Ch. 11)",
      "Class 12 — d and f Block Elements (Ch. 8)",
    ],
    memoryTriggers: [
      "Orange K₂Cr₂O₇ + alcohol → Green Cr³⁺ (orange to green = oxidation happened)",
      "Breathalyser chemistry: ethanol → acetic acid, Cr changes colour",
    ],
    reactionIds: [],
    reagentIds: ["kmno4-acidic", "pcc", "jones-reagent"],
  },

  {
    id: "mcpba",
    name: "meta-Chloroperoxybenzoic Acid",
    aliases: ["mCPBA", "m-CPBA", "meta-chloroperbenzoic acid"],
    formula: "m-ClC₆H₄CO₃H",
    category: "Organic",
    role: "Oxidising Agent",
    definition: "A peracid oxidant used for (1) epoxidation of alkenes via the Prileshajev mechanism, and (2) Baeyer-Villiger oxidation of ketones to esters/lactones.",
    mechanism: "Epoxidation: The electrophilic oxygen of the O–O bond attacks the electron-rich alkene π bond via a butterfly transition state, delivering O from the same face as the peracid approaches (syn, but can be controlled). Baeyer-Villiger: Peracid adds to ketone carbonyl, then the least substituted group migrates (with inversion) to give ester/lactone.",
    conditions: ["CH₂Cl₂ or CHCl₃ solvent", "RT", "Slightly acidic conditions (benzoic acid byproduct)", "Peracids stored cold"],
    selectivity: "Alkene → epoxide (more substituted alkene reacts faster — electron-rich π bonds preferred). Ketone → ester (Baeyer-Villiger: migration order: H > 3° > 2° ≈ aryl > 1° > methyl).",
    exceptions: [
      "More substituted alkene is MORE reactive (opposite to electrophilic addition, where reactivity also follows electron density)",
      "Baeyer-Villiger migration order: H > 3° alkyl > 2° alkyl ≈ aryl > 1° alkyl > methyl",
      "Cyclic ketone + mCPBA → lactone (ring expansion by one carbon in ring)",
      "mCPBA does NOT oxidise aromatic rings under normal conditions",
      "The migrating group retains configuration (migration with retention at the migrating carbon)",
    ],
    relatedConcepts: ["Epoxidation", "Baeyer-Villiger oxidation", "Peracid", "Migration order"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Very High",
      neet: "Low",
      pyqCount: 16,
      lastAsked: 2024,
      tags: ["epoxidation", "Baeyer-Villiger", "peracid", "migration"],
    },
    ncertReferences: [],
    memoryTriggers: [
      "mCPBA = Makes Cyclic Products from Benzene Acyl (epoxide or ester)",
      "Baeyer-Villiger migration: H > 3° > 2° > aryl > 1° > methyl",
      "Ring ketone + mCPBA = ring expansion (lactone)",
    ],
    reactionIds: ["baeyer-villiger-oxidation"],
    reagentIds: ["osmium-tetroxide", "kmno4-acidic"],
  },

  {
    id: "tollens-reagent",
    name: "Tollens' Reagent",
    aliases: ["Silver mirror reagent", "[Ag(NH₃)₂]OH", "Ammoniacal silver nitrate"],
    formula: "[Ag(NH₃)₂]OH",
    category: "Organic",
    role: "Oxidising Agent",
    definition: "An ammoniacal silver nitrate solution that oxidises aldehydes to carboxylate ions, producing a characteristic silver mirror on the test tube wall. Used to distinguish aldehydes from ketones.",
    mechanism: "Ag⁺ (as [Ag(NH₃)₂]⁺) oxidises the aldehyde to a carboxylate. Ag⁺ is reduced to Ag⁰ metal which deposits as a mirror. RCHO + 2[Ag(NH₃)₂]⁺ + 2OH⁻ → RCOO⁻ + 2Ag↓ + 4NH₃ + H₂O.",
    conditions: ["Fresh preparation — AgNO₃ + excess NaOH + NH₃ (to dissolve brown AgOH precipitate)", "Test tube washed with NaOH before use", "Mild heating (40–50°C)", "Do NOT store (forms explosive silver nitride)"],
    selectivity: "Positive result (silver mirror): all aldehydes (aliphatic and aromatic) AND glucose, fructose, maltose (but NOT sucrose). NEGATIVE: ketones (except α-hydroxy ketones), sucrose.",
    exceptions: [
      "BOTH aliphatic AND aromatic aldehydes give positive Tollens' (unlike Fehling's which is negative for aromatic aldehydes)",
      "Tollens' positive for: HCHO (formaldehyde), glucose, fructose, maltose",
      "Tollens' NEGATIVE for: ketones, sucrose, starch",
      "Fehling's is NEGATIVE for benzaldehyde and aromatic aldehydes (unlike Tollens')",
      "Should not be stored — explosive Ag₃N or AgN₃ may form on standing",
    ],
    relatedConcepts: ["Silver mirror test", "Fehling's test", "Aldehyde identification", "Reducing sugars"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "Very High",
      pyqCount: 35,
      lastAsked: 2024,
      tags: ["Tollens", "silver-mirror", "aldehyde-test", "reducing-sugars"],
    },
    ncertReferences: [
      "Class 12 — Aldehydes, Ketones and Carboxylic Acids (Ch. 12)",
      "Class 12 — Biomolecules (Ch. 14) — reducing sugars",
    ],
    memoryTriggers: [
      "Tollens = Tells if it's an aldehyde (silver mirror on the glass)",
      "Tollens works for ALL aldehydes including benzaldehyde",
      "Fehling's fails for aromatic aldehydes; Tollens' doesn't care",
    ],
    reactionIds: [],
    reagentIds: ["fehling-solution", "benedict-solution"],
  },

  {
    id: "fehling-solution",
    name: "Fehling's Solution",
    aliases: ["Fehling's A + B", "Cu²⁺ tartrate complex"],
    formula: "Cu(OH)₂ in NaOH/sodium potassium tartrate",
    category: "Organic",
    role: "Oxidising Agent",
    definition: "A deep blue Cu²⁺ complex (bistartrate) that oxidises aliphatic aldehydes to carboxylates, with Cu²⁺ reduced to brick-red Cu₂O precipitate. Used to identify aliphatic aldehydes and reducing sugars.",
    mechanism: "Cu²⁺ complex acts as oxidant. RCHO reduces Cu²⁺ → Cu₂O (brick-red precipitate). RCHO + 2Cu²⁺ + 4OH⁻ → RCOO⁻ + Cu₂O↓ + 2H₂O.",
    conditions: ["Fehling A (CuSO₄ aq) + Fehling B (sodium potassium tartrate + NaOH) mixed fresh", "Warm/boil", "Blue → brick-red precipitate = positive"],
    selectivity: "Positive: aliphatic aldehydes, glucose, fructose, lactose, maltose (reducing sugars). NEGATIVE: aromatic aldehydes (benzaldehyde), ketones, sucrose, starch.",
    exceptions: [
      "NEGATIVE for aromatic aldehydes (benzaldehyde) — this is the KEY difference from Tollens'",
      "Tollens' is positive for ALL aldehydes; Fehling's fails for aromatic",
      "Fructose (a ketose) gives POSITIVE Fehling's due to isomerisation in alkali",
      "Blue → brick-red Cu₂O precipitate (not Cu⁰ metal)",
    ],
    relatedConcepts: ["Tollens' test", "Reducing sugars", "Aldehyde identification", "Cu²⁺ as oxidant"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "Very High",
      pyqCount: 30,
      lastAsked: 2024,
      tags: ["Fehling", "brick-red", "reducing-sugar", "aromatic-aldehyde-negative"],
    },
    ncertReferences: [
      "Class 12 — Aldehydes, Ketones and Carboxylic Acids (Ch. 12)",
      "Class 12 — Biomolecules (Ch. 14)",
    ],
    memoryTriggers: [
      "Fehling = Fails for Aromatic aldehydes (Benzaldehyde = Negative)",
      "Brick-red Cu₂O = Fehling's positive for aliphatic aldehydes",
      "Fructose surprises: it's a ketose but gives positive Fehling's (alkali isomerisation)",
    ],
    reactionIds: [],
    reagentIds: ["tollens-reagent", "benedict-solution"],
  },

  {
    id: "hio4",
    name: "Periodic Acid",
    aliases: ["HIO₄", "Malaprade reagent", "Periodate cleavage"],
    formula: "HIO₄",
    category: "Organic",
    role: "Oxidising Agent",
    definition: "Cleaves vicinal (1,2) diols and α-hydroxy carbonyl compounds oxidatively, breaking the C–C bond between adjacent oxygen-bearing carbons. Produces carbonyl fragments (aldehydes, ketones, or carboxylic acids).",
    mechanism: "Formation of a cyclic iodate ester between HIO₄ and the two adjacent OH groups, followed by fragmentation to give two carbonyl compounds and HIO₃.",
    conditions: ["Aqueous solution", "RT", "1 equivalent HIO₄ per vicinal diol"],
    selectivity: "Cleaves: 1,2-diols (gives aldehydes/ketones). α-Hydroxy ketones: gives RCOOH + R'CHO. α-Hydroxy aldehydes: gives RCOOH + HCOOH. 1,2,3-triols: 2 equivalents HIO₄ consumed. Glycerol → 2 HCHO + HCOOH.",
    exceptions: [
      "Each 1,2-diol unit consumes 1 equivalent HIO₄ — moles consumed tells you structure",
      "trans-1,2-cyclohexanediol: reacts but must form a planar ester (slower than cis)",
      "Formaldehyde formed from end carbons (primary OH), formic acid from internal 1,2-diol carbons",
      "Used in carbohydrate chemistry to determine ring size and structure",
    ],
    relatedConcepts: ["Malaprade reaction", "Oxidative cleavage", "Diol identification", "Carbohydrate structure determination"],
    examRelevance: {
      jeeMain: "Medium",
      jeeAdvanced: "High",
      neet: "Low",
      pyqCount: 10,
      lastAsked: 2023,
      tags: ["periodic-acid", "diol-cleavage", "Malaprade", "carbohydrate"],
    },
    ncertReferences: [],
    memoryTriggers: [
      "HIO₄ = Hits IO (IO₄) between vicinal OHs, cleaves C-C",
      "Count moles HIO₄ consumed → count 1,2-diol units in molecule",
    ],
    reactionIds: ["malaprade-reaction"],
    reagentIds: ["osmium-tetroxide", "kmno4-acidic"],
  },

  // ── HALOGENATING AGENTS ───────────────────────────────────────────────────

  {
    id: "socl2",
    name: "Thionyl Chloride",
    aliases: ["SOCl₂", "Sulfinyl chloride", "Sulphuryl dichloride"],
    formula: "SOCl₂",
    category: "Organic",
    role: "Halogenating Agent",
    definition: "A versatile chlorinating agent that converts (1) carboxylic acids to acid chlorides and (2) alcohols to alkyl chlorides with retention of configuration (via SNi mechanism).",
    mechanism: "With alcohol: the alcohol oxygen attacks SOCl₂ to form a chlorosulphite ester (ROSOCl). This ester undergoes an intimate ion pair or SNi (internal nucleophilic substitution) with the Cl⁻ that was displaced, giving inversion or retention depending on conditions. In pyridine: SN2 from external Cl⁻ → inversion. Without pyridine: SNi (same face) → retention. With acid: forms acyl chloride directly, byproducts are HCl + SO₂ (both gases, easy separation).",
    conditions: ["Neat or with pyridine as base", "For acid chloride from RCOOH: excess SOCl₂, mild heating", "Pyridine base scavenges HCl"],
    selectivity: "RCOOH → RCOCl. ROH → RCl. Byproducts: SO₂ + HCl (both gaseous — clean reaction). Best reagent for making acid chlorides.",
    exceptions: [
      "SNi mechanism (retention) when used without base in ether",
      "Use in pyridine → SN2 → inversion (pyridine activates the chlorosulphite ester, provides external Cl⁻)",
      "Gaseous byproducts (SO₂ + HCl) make this the preferred reagent for acid chloride synthesis",
      "With carboxylic acid: first forms mixed anhydride-like species, then Cl⁻ attacks",
    ],
    relatedConcepts: ["Acid chloride synthesis", "SNi mechanism", "Retention vs inversion", "Acyl chloride"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Very High",
      neet: "Medium",
      pyqCount: 20,
      lastAsked: 2024,
      tags: ["SOCl2", "acid-chloride", "halogenating", "SNi"],
    },
    ncertReferences: [
      "Class 12 — Carboxylic Acids (Ch. 12)",
      "Class 12 — Haloalkanes and Haloarenes (Ch. 10)",
    ],
    memoryTriggers: [
      "SOCl₂ → RCOOH gives RCOCl + SO₂ + HCl (two gases fly away = clean)",
      "SNi = Same-face substitution = retention of configuration",
      "Best for acid chlorides: SO₂ and HCl are gases, easy to remove",
    ],
    reactionIds: [],
    reagentIds: ["pcl5", "pcl3", "pbr3"],
  },

  {
    id: "nbs",
    name: "N-Bromosuccinimide",
    aliases: ["NBS", "N-Bromosuccinimide", "Wohl-Ziegler reagent"],
    formula: "C₄H₄BrNO₂",
    category: "Organic",
    role: "Halogenating Agent",
    definition: "A selective radical brominating agent that brominates at the allylic or benzylic position of alkenes and arenes under free-radical conditions (hν or peroxide initiation).",
    mechanism: "Under light/peroxide initiation: NBS provides Br• radicals. Allylic/benzylic C–H bonds are selectively abstracted (weakest C–H bonds) to give a stabilised radical. Br• then attacks the radical to give the allylic/benzylic bromide.",
    conditions: ["CCl₄ as solvent (inert, non-polar)", "hν (light) or AIBN/peroxide as initiator", "RT to 80°C", "Succinimide is a by-product"],
    selectivity: "Brominates at allylic > benzylic > tertiary > secondary > primary C–H (radical stability order). Does NOT add across C=C (no addition product). High selectivity because Br• is sluggish and selective.",
    exceptions: [
      "Cl• is too reactive (less selective) — NBS is used precisely because Br• is selective",
      "NBS doesn't add to C=C double bond under these conditions (unlike Br₂/CCl₄)",
      "If C=C is isolated (not allylic), no reaction with NBS under radical conditions",
      "NBS can also brominate activated aromatic rings under ionic conditions (electrophilic aromatic substitution)",
    ],
    relatedConcepts: ["Allylic bromination", "Benzylic bromination", "Wohl-Ziegler reaction", "Radical halogenation", "C–H bond strength"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Very High",
      neet: "Medium",
      pyqCount: 18,
      lastAsked: 2024,
      tags: ["NBS", "allylic", "benzylic", "radical-bromination"],
    },
    ncertReferences: [
      "Class 11 — Hydrocarbons (Ch. 13)",
      "Class 12 — Haloalkanes and Haloarenes (Ch. 10)",
    ],
    memoryTriggers: [
      "NBS = Needs Benzylic/allylic Site to work (radical selectivity)",
      "NBS + CCl₄ + hν = allylic bromination (Wohl-Ziegler)",
      "NBS doesn't ADD to C=C — it removes H from next to C=C",
    ],
    reactionIds: ["wohl-ziegler-reaction"],
    reagentIds: ["socl2", "pbr3"],
  },

  // ── ACID/BASE CATALYSTS ───────────────────────────────────────────────────

  {
    id: "alcl3",
    name: "Aluminium Chloride",
    aliases: ["AlCl₃", "Anhydrous aluminium chloride", "Lewis acid catalyst"],
    formula: "AlCl₃",
    category: "Organic",
    role: "Catalyst",
    definition: "A strong Lewis acid catalyst used in Friedel-Crafts alkylation and acylation, and many other electrophilic aromatic substitution reactions.",
    mechanism: "AlCl₃ accepts the Cl lone pair from RCl or RCOCl, generating the electrophile: R⁺ (carbocation) or RCO⁺ (acylium ion). The electrophile then attacks the aromatic ring.",
    conditions: ["Anhydrous conditions — hydrolysis destroys AlCl₃", "Inert solvent: CH₂Cl₂, CCl₄, CS₂", "Stoichiometric for alkylation; catalytic for acylation (but >1 equiv often used)"],
    selectivity: "Activates alkyl halides and acyl halides as electrophiles toward aromatic rings. Stronger Lewis acid than BF₃ or ZnCl₂.",
    exceptions: [
      "Friedel-Crafts alkylation: carbocation rearrangement can occur (primary → secondary or tertiary)",
      "Friedel-Crafts acylation: acylium ion is stabilised (no rearrangement)",
      "Deactivated rings (nitrobenzene, benzoic acid) do NOT undergo FC reaction",
      "Must be anhydrous — water destroys AlCl₃ and generates HCl",
      "Polyalkylation problem in FC alkylation (monoalkyl product is more reactive than benzene)",
    ],
    relatedConcepts: ["Friedel-Crafts", "Lewis acid", "Electrophilic aromatic substitution", "Carbocation rearrangement"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "High",
      pyqCount: 42,
      lastAsked: 2024,
      tags: ["AlCl3", "Friedel-Crafts", "Lewis-acid", "EAS"],
    },
    ncertReferences: [
      "Class 12 — Haloalkanes and Haloarenes (Ch. 10)",
      "Class 11 — Hydrocarbons (Ch. 13)",
    ],
    memoryTriggers: [
      "AlCl₃ = Aluminium Chloride = Lewis Acid = Creates Electrophile for benzene attack",
      "Alkylation rearranges; Acylation doesn't",
      "Must be ANHYDROUS or it's destroyed",
    ],
    reactionIds: ["friedel-crafts-acylation", "friedel-crafts-alkylation"],
    reagentIds: ["bf3", "zncl2-lucas"],
  },

  {
    id: "zncl2-lucas",
    name: "Lucas Reagent",
    aliases: ["ZnCl₂/conc HCl", "Lucas test reagent", "Zinc chloride/HCl"],
    formula: "ZnCl₂ / conc HCl",
    category: "Organic",
    role: "Catalyst",
    definition: "A solution of anhydrous ZnCl₂ in concentrated HCl used to distinguish primary, secondary, and tertiary alcohols by the time required for cloudiness (alkyl chloride formation) to appear.",
    mechanism: "ZnCl₂ (Lewis acid) coordinates to the hydroxyl oxygen, facilitating ionisation (SNi or SN1) to give a carbocation, which is then trapped by Cl⁻. The alkyl chloride is insoluble → cloudiness.",
    conditions: ["Anhydrous ZnCl₂ in conc. HCl at RT", "Only works for low MW alcohols (≤6 carbons) that are water-soluble", "Observe time for turbidity"],
    selectivity: "3° alcohol: immediate cloudiness (fast SN1 via stable 3° carbocation). 2° alcohol: 5 minutes (slower SN1 or SN2). 1° alcohol: no reaction at RT (very slow — needs heating). Allyl and benzyl alcohols: immediate (very stable carbocations).",
    exceptions: [
      "Does NOT work for alcohols with >6 carbons (insoluble in reagent)",
      "Allyl and benzylic alcohols react immediately (like 3°) due to resonance-stabilised carbocations",
      "Methanol: no reaction under Lucas conditions",
      "Test is based on cloudiness (physical observation), not a colour change",
    ],
    relatedConcepts: ["Lucas test", "SN1 vs SN2", "Carbocation stability", "Alcohol classification"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Medium",
      neet: "High",
      pyqCount: 20,
      lastAsked: 2024,
      tags: ["Lucas-test", "alcohol-classification", "turbidity", "ZnCl2"],
    },
    ncertReferences: [
      "Class 12 — Alcohols, Phenols and Ethers (Ch. 11)",
    ],
    memoryTriggers: [
      "Lucas = Tertiary = Immediate. Secondary = 5 min. Primary = Never (at RT)",
      "Cloudy = Lucas positive (alkyl chloride formed = insoluble)",
      "3° carbocation most stable → fastest SN1 → fastest cloudiness",
    ],
    reactionIds: [],
    reagentIds: ["alcl3", "socl2"],
  },

  {
    id: "h2so4-conc",
    name: "Concentrated Sulphuric Acid",
    aliases: ["H₂SO₄ (conc)", "conc. H₂SO₄", "Sulphuric acid"],
    formula: "H₂SO₄ (conc.)",
    category: "Organic",
    role: "Acid",
    definition: "A strong Brønsted and Lewis acid used as a catalyst for sulfonation, esterification, dehydration of alcohols, and nitration (in combination with HNO₃).",
    mechanism: "Multiple roles: Protonates OH (dehydration), generates nitronium ion NO₂⁺ with HNO₃ (nitration), acts as sulfonating agent itself via SO₃, catalyses esterification via activation of carbonyl.",
    conditions: ["Neat or as mixed acid (with HNO₃ for nitration)", "Cold for sulfonation; hot for desulfonation", "170°C for alkene from alcohol; 140°C for ether from alcohol"],
    selectivity: "Alcohol + H₂SO₄ at 170°C → alkene + H₂O (follows Saytzeff). Alcohol + H₂SO₄ at 140°C → ether (intermolecular dehydration, 2 ROH → ROR). Benzene + H₂SO₄ → benzenesulphonic acid.",
    exceptions: [
      "Temperature controls product: 140°C → ether; 170°C → alkene",
      "Sulfonation is REVERSIBLE (hot H₂O/steam reverses sulfonation → desulfonation)",
      "Nitration requires mixed acid (H₂SO₄ + HNO₃) to generate NO₂⁺ electrophile",
      "Dehydration of 2-butanol follows Saytzeff rule (major = 2-butene, not 1-butene)",
    ],
    relatedConcepts: ["Dehydration", "Esterification", "Sulfonation", "Nitration", "Saytzeff rule"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "Very High",
      pyqCount: 50,
      lastAsked: 2024,
      tags: ["H2SO4", "dehydration", "esterification", "sulfonation", "nitration"],
    },
    ncertReferences: [
      "Class 12 — Alcohols, Phenols and Ethers (Ch. 11)",
      "Class 11 — Hydrocarbons (Ch. 13)",
      "Class 12 — p-Block Elements (Ch. 7)",
    ],
    memoryTriggers: [
      "140°C = ether (two molecules of alcohol meet); 170°C = alkene (one molecule loses H₂O)",
      "H₂SO₄ + HNO₃ = makes NO₂⁺ (nitronium ion) for nitration",
      "Sulfonation is reversible — steam removes SO₃H group",
    ],
    reactionIds: ["esterification", "sulfonation", "nitration"],
    reagentIds: ["hno3-conc", "pocl3-pyridine"],
  },

  {
    id: "pocl3-pyridine",
    name: "Phosphorus Oxychloride / Pyridine",
    aliases: ["POCl₃/Py", "POCl₃/pyridine", "Dehydrating agent"],
    formula: "POCl₃ / C₅H₅N",
    category: "Organic",
    role: "Dehydrating Agent",
    definition: "A combination used to dehydrate alcohols to alkenes (E2 elimination) without rearrangement, and to convert carboxylic acids to acid chlorides. Particularly useful for making acyl chlorides from sensitive substrates.",
    mechanism: "The hydroxyl group reacts with POCl₃ to form a phosphate ester (ROPOCl₂). In pyridine (acts as base and nucleophile), E2 elimination of HCl gives the alkene. The Cl⁻ displaced by pyridine attacks from the opposite face → anti elimination → trans (Zaitsev) product.",
    conditions: ["Pyridine as both base and solvent", "0°C to RT", "Favours anti elimination"],
    selectivity: "Gives alkene via anti-elimination (trans product where applicable). For acid chlorides: does not involve carbocation, so NO rearrangement.",
    exceptions: [
      "Unlike H₂SO₄ dehydration (which proceeds via carbocation → can rearrange), POCl₃/Py is E2 (no rearrangement)",
      "Anti-elimination favours trans alkene",
      "Used for substrates prone to rearrangement under acidic conditions",
    ],
    relatedConcepts: ["E2 elimination", "Dehydration without rearrangement", "Acid chloride synthesis", "Anti-elimination"],
    examRelevance: {
      jeeMain: "Medium",
      jeeAdvanced: "High",
      neet: "Low",
      pyqCount: 8,
      lastAsked: 2023,
      tags: ["POCl3", "dehydration", "E2", "no-rearrangement"],
    },
    ncertReferences: [],
    memoryTriggers: [
      "POCl₃/Py = no rearrangement (E2 not SN1) — use when acid-sensitive or rearrangement-prone",
    ],
    reactionIds: [],
    reagentIds: ["h2so4-conc", "socl2"],
  },

  {
    id: "ozone",
    name: "Ozone (Ozonolysis)",
    aliases: ["O₃", "Ozonolysis", "O₃ / Zn-H₂O or O₃ / H₂O₂"],
    formula: "O₃",
    category: "Organic",
    role: "Oxidising Agent",
    definition: "Ozone cleaves C=C double bonds via a cyclic mechanism, giving carbonyl fragments. Workup conditions determine products: reductive workup (Zn/H₂O or Me₂S) → aldehydes/ketones; oxidative workup (H₂O₂) → carboxylic acids (from aldehydes) or ketones.",
    mechanism: "Step 1: O₃ adds to C=C via [3+2] cycloaddition to form molozonide. Step 2: Molozonide rearranges to carbonyl oxide + carbonyl fragment. Step 3: These recombine to form ozonide. Step 4: Workup cleaves ozonide.",
    conditions: ["O₃ gas bubbled through alkene solution in CH₂Cl₂ or EtOAc at -78°C", "Reductive workup: Zn/H₂O or dimethyl sulphide (Me₂S)", "Oxidative workup: H₂O₂"],
    selectivity: "Each C=C bond gives two carbonyl fragments. Terminal alkene: gives RCHO + H₂CO (formaldehyde). Internal alkene (RCH=CHR'): gives RCHO + R'CHO. Disubstituted (R₂C=CR'₂): gives R₂C=O + R'₂C=O (ketones). Reductive workup preserves aldehydes; oxidative converts aldehydes → carboxylic acids, ketones unchanged.",
    exceptions: [
      "Reductive workup: any =CH₂ gives HCHO (formaldehyde) which is a marker for terminal alkene",
      "Oxidative workup: aldehydes → RCOOH; ketones → unchanged (no further oxidation)",
      "Both ozonolysis and hot KMnO₄ cleave C=C, but give different products at trisubstituted positions",
      "Cyclic alkenes give single open-chain dicarbonyl compound (one molecule, not two)",
    ],
    relatedConcepts: ["Oxidative cleavage", "Ozonide", "Carbonyl fragment", "KMnO₄ comparison"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "High",
      pyqCount: 35,
      lastAsked: 2024,
      tags: ["ozonolysis", "C=C-cleavage", "reductive-workup", "oxidative-workup"],
    },
    ncertReferences: [
      "Class 11 — Hydrocarbons (Ch. 13)",
    ],
    memoryTriggers: [
      "O₃ then Zn/H₂O = keep aldehydes (reductive = gentle)",
      "O₃ then H₂O₂ = aldehydes → carboxylic acids (oxidative = harsh)",
      "Cyclic alkene + O₃ = ONE open-chain product (ring opened)",
    ],
    reactionIds: ["ozonolysis"],
    reagentIds: ["kmno4-acidic"],
  },

  // ── INORGANIC CHEMISTRY REAGENTS ─────────────────────────────────────────

  {
    id: "h2so4-fuming",
    name: "Oleum (Fuming Sulphuric Acid)",
    aliases: ["Oleum", "H₂SO₄·SO₃", "Fuming H₂SO₄", "H₂S₂O₇"],
    formula: "H₂SO₄·SO₃",
    category: "Inorganic",
    role: "Oxidising Agent",
    definition: "A solution of SO₃ in concentrated H₂SO₄ (also formulated as H₂S₂O₇ or pyrosulphuric acid). Produced in the Contact process as intermediate; a stronger sulfonating agent than H₂SO₄ alone.",
    mechanism: "SO₃ is a powerful Lewis acid electrophile that attacks the benzene ring (sulfonation) or acts as an oxidant in industrial processes.",
    conditions: ["Produced in Contact process: SO₃ absorbed in conc. H₂SO₄", "Cannot dissolve SO₃ in water directly (too exothermic, forms acid mist)", "Used in making sulphuric acid industrially"],
    selectivity: "Used in Contact process (industrial H₂SO₄ production). Also used for ring sulfonation of deactivated benzene derivatives.",
    exceptions: [
      "Cannot add SO₃ directly to water — acid mist/fog forms (explosion hazard)",
      "In Contact process: SO₃ + H₂SO₄ → H₂S₂O₇ (oleum) → dilution with H₂O gives H₂SO₄",
      "Oleum smokes in moist air (SO₃ fumes)",
    ],
    relatedConcepts: ["Contact process", "Sulfonation", "Industrial H₂SO₄", "SO₃"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Medium",
      neet: "High",
      pyqCount: 15,
      lastAsked: 2024,
      tags: ["oleum", "Contact-process", "SO3", "industrial-chemistry"],
    },
    ncertReferences: [
      "Class 12 — p-Block Elements (Ch. 7) — Contact process",
    ],
    memoryTriggers: [
      "Oleum = Old H₂SO₄ with extra SO₃ stuck in it",
      "Contact process: SO₃ + H₂SO₄ → oleum → + H₂O → H₂SO₄",
      "Cannot add SO₃ to water directly (use oleum then dilute)",
    ],
    reactionIds: ["contact-process"],
    reagentIds: ["h2so4-conc"],
  },

  {
    id: "nabh4-cecl3",
    name: "Luche Reduction System",
    aliases: ["NaBH₄ / CeCl₃", "Luche conditions", "Cerium borohydride"],
    formula: "NaBH₄ + CeCl₃·7H₂O",
    category: "Organic",
    role: "Reducing Agent",
    definition: "A modified NaBH₄ reduction using cerium(III) chloride as a Lewis acid additive to achieve exclusive 1,2-reduction of α,β-unsaturated carbonyl compounds, giving allylic alcohols instead of saturated ketones.",
    mechanism: "CeCl₃ coordinates to the carbonyl oxygen, making it more electrophilic. This activates the C=O toward hydride delivery in 1,2-mode. Without CeCl₃, NaBH₄ can give 1,4-reduction (conjugate reduction) of some enones.",
    conditions: ["MeOH or EtOH solvent", "CeCl₃·7H₂O added first, then NaBH₄", "0°C to RT"],
    selectivity: "α,β-Unsaturated ketone → allylic alcohol (1,2-reduction product, C=O reduced, C=C retained). Exclusive 1,2-selectivity.",
    exceptions: [
      "Without CeCl₃: NaBH₄ gives mixture of 1,2 and 1,4 products for conjugated systems",
      "Luche conditions: always 1,2 (aldol) alcohol → useful in synthesis",
    ],
    relatedConcepts: ["1,2 vs 1,4 reduction", "Conjugate reduction", "Allylic alcohol", "Chemoselective reduction"],
    examRelevance: {
      jeeMain: "Low",
      jeeAdvanced: "High",
      neet: "None",
      pyqCount: 4,
      lastAsked: 2022,
      tags: ["Luche", "1,2-reduction", "enone", "allylic-alcohol"],
    },
    ncertReferences: [],
    memoryTriggers: [
      "CeCl₃ + NaBH₄ = Cerium Controls reductant to attack 1,2 (carbonyl end)",
    ],
    reactionIds: [],
    reagentIds: ["nabh4", "lah"],
  },

  // ── NAMED REACTION-SPECIFIC REAGENTS ─────────────────────────────────────

  {
    id: "grignard-reagent",
    name: "Grignard Reagent",
    aliases: ["RMgX", "Organomagnesium halide", "Grignard"],
    formula: "RMgX (R = alkyl/aryl, X = Cl, Br, I)",
    category: "Organic",
    role: "Nucleophile",
    definition: "An organomagnesium halide (RMgX) prepared from alkyl/aryl halide and Mg in dry ether. Acts as a carbon nucleophile (R⁻ equivalent) and as a strong base.",
    mechanism: "Mg inserts into the C–X bond (oxidative insertion) to give R–Mg–X. The C–Mg bond is highly polarised (C^δ⁻–Mg^δ⁺), making the organic carbon act as a carbanion. Attacks electrophilic carbon (C=O, CO₂, nitrile, epoxide).",
    conditions: ["Dry ether (Et₂O) or THF", "Strictly anhydrous and aprotic — reacts with water to give RH", "Mg turnings", "Initiate with crystal of I₂ or ethyl bromide if slow"],
    selectivity: "Reacts with: HCHO → 1° alcohol; RCHO → 2° alcohol; RCOR' → 3° alcohol; CO₂ → RCOOH; RCN → ketone (after hydrolysis); oxirane → 1° alcohol with chain extension; esters → 3° alcohol (2 equivalents). Also reacts with: H₂O, NH₃, alcohols, carboxylic acids (protonation — destroys Grignard).",
    exceptions: [
      "Active H compounds (RCOOH, ROH, H₂O, NH, NH₂) DESTROY the Grignard",
      "Ester + 2 RMgX → 3° alcohol (two additions: first gives ketone, ketone reacts with second RMgX)",
      "CO₂ + RMgX → RCOOH (Grignard synthesis of carboxylic acids)",
      "RMgX + formaldehyde (HCHO) → primary alcohol (CH₂OH added to R)",
      "Allyl and vinyl Grignards: react normally",
      "Organocopper reagents (Gilman) are less reactive and do NOT react with ester C=O (useful for selective 1,4-addition)",
    ],
    relatedConcepts: ["Carbon nucleophile", "Grignard reaction", "Organometallic chemistry", "Carbanion equivalent"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "High",
      pyqCount: 45,
      lastAsked: 2024,
      tags: ["Grignard", "carbon-nucleophile", "RMgX", "organometallic"],
    },
    ncertReferences: [
      "Class 12 — Aldehydes, Ketones and Carboxylic Acids (Ch. 12)",
      "Class 12 — Haloalkanes and Haloarenes (Ch. 10)",
    ],
    memoryTriggers: [
      "Grignard = R– attached to Mg — adds R as carbanion to C=O",
      "Water destroys Grignard (RH formed) — always keep DRY",
      "HCHO = 1° OH; RCHO = 2° OH; RCOR' = 3° OH; CO₂ = RCOOH",
    ],
    reactionIds: ["grignard-reaction"],
    reagentIds: ["lah", "organolithium"],
  },

  {
    id: "pcl5",
    name: "Phosphorus Pentachloride",
    aliases: ["PCl₅", "Phosphorus(V) chloride"],
    formula: "PCl₅",
    category: "Inorganic",
    role: "Halogenating Agent",
    definition: "A phosphorus(V) chloride used to convert hydroxyl groups (ROH, RCOOH) to chlorides, and to prepare acyl chlorides from carboxylic acids.",
    mechanism: "PCl₅ transfers Cl to the oxygen of ROH, forming ROPCl₄ complex, which collapses via SN2 to give RCl + POCl₃.",
    conditions: ["Anhydrous", "Mild heating", "Byproduct: POCl₃ + HCl"],
    selectivity: "ROH → RCl. RCOOH → RCOCl. Inorganic acids: HNO₃ + PCl₅ → NO₂Cl + POCl₃ (forms nitryl chloride).",
    exceptions: [
      "Dissociates into PCl₃ + Cl₂ above 160°C (equilibrium)",
      "Trigonal bipyramidal shape (sp³d hybridisation) at 25°C",
      "Unlike PCl₃ (pyramidal, lone pair), PCl₅ has no lone pair on P",
      "All five P–Cl bonds are NOT equivalent (3 equatorial = shorter, 2 axial = longer)",
    ],
    relatedConcepts: ["Halogenation", "SN2", "Acyl chloride", "Phosphorus chlorides"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "High",
      pyqCount: 22,
      lastAsked: 2024,
      tags: ["PCl5", "halogenation", "acid-chloride", "dissociation"],
    },
    ncertReferences: [
      "Class 12 — p-Block Elements (Ch. 7)",
      "Class 12 — Haloalkanes and Haloarenes (Ch. 10)",
    ],
    memoryTriggers: [
      "PCl₅ = Phosphorus Changes 5 things (converts OH to Cl)",
      "PCl₅ shape: trigonal bipyramidal (3 equatorial + 2 axial Cl)",
      "PCl₅ ⇌ PCl₃ + Cl₂ at high temperature",
    ],
    reactionIds: [],
    reagentIds: ["socl2", "pcl3", "pbr3"],
  },

  {
    id: "pbr3",
    name: "Phosphorus Tribromide",
    aliases: ["PBr₃", "Phosphorus(III) bromide"],
    formula: "PBr₃",
    category: "Organic",
    role: "Halogenating Agent",
    definition: "Converts primary and secondary alcohols to alkyl bromides via an SN2 mechanism, with inversion of configuration. Preferred over HBr when stereochemical control is needed.",
    mechanism: "PBr₃ reacts with ROH to form a phosphite ester (ROPBr₂). The resulting Br⁻ attacks via SN2, inverting the stereochemistry at the carbon. Byproducts: H₃PO₃.",
    conditions: ["Pyridine or ether as solvent", "0°C to RT", "Inversion of configuration"],
    selectivity: "1° and 2° ROH → RBr (SN2). 3° alcohols react poorly (SN2 at 3° carbon is hindered).",
    exceptions: [
      "SN2 → inversion (useful for stereochemical control)",
      "3° alcohols react poorly (steric hindrance in SN2)",
      "PBr₃ is less aggressive than PCl₅ — better for sensitive substrates",
    ],
    relatedConcepts: ["SN2", "Inversion of configuration", "Alcohol to halide", "Phosphorus reagents"],
    examRelevance: {
      jeeMain: "Medium",
      jeeAdvanced: "High",
      neet: "Low",
      pyqCount: 8,
      lastAsked: 2023,
      tags: ["PBr3", "alcohol-to-bromide", "SN2", "inversion"],
    },
    ncertReferences: [],
    memoryTriggers: [
      "PBr₃ = 3 bromines available, goes via SN2 (inversion)",
      "PBr₃ unlike SOCl₂: both give inversion but SOCl₂ can also give retention (SNi)",
    ],
    reactionIds: [],
    reagentIds: ["socl2", "pcl5"],
  },

];

// ─────────────────────────────────────────────────────────────────────────────
// Lookup helpers
// ─────────────────────────────────────────────────────────────────────────────

const _byId = new Map<string, Reagent>(REAGENTS.map((r) => [r.id, r]));

export function getReagent(id: string): Reagent | undefined {
  return _byId.get(id);
}

export function getReagentsByRole(role: Reagent["role"]): Reagent[] {
  return REAGENTS.filter((r) => r.role === role);
}

export function getHighYieldReagents(): Reagent[] {
  const FREQ_RANK = { "None": 0, "Low": 1, "Medium": 2, "High": 3, "Very High": 4 };
  return REAGENTS.filter((r) => {
    const maxFreq = Math.max(
      FREQ_RANK[r.examRelevance.jeeMain],
      FREQ_RANK[r.examRelevance.jeeAdvanced],
      FREQ_RANK[r.examRelevance.neet]
    );
    return maxFreq >= 3;
  });
}

export function searchReagents(query: string): Reagent[] {
  const q = query.toLowerCase();
  return REAGENTS.filter((r) =>
    r.name.toLowerCase().includes(q) ||
    r.aliases.some((a) => a.toLowerCase().includes(q)) ||
    r.formula.toLowerCase().includes(q) ||
    r.definition.toLowerCase().includes(q) ||
    r.examRelevance.tags.some((t) => t.toLowerCase().includes(q))
  );
}
