import type { CSSProperties } from "react";

type VisualStep = { label: string; detail: string; symbol?: string };
type VisualSpec = {
  title: string;
  kicker: string;
  equation: string;
  insight: string;
  accent: string;
  accent2: string;
  steps: VisualStep[];
};

const V: Record<string, VisualSpec> = {
  "activator-depressant.webp": { title:"Selective Flotation Control", kicker:"ACTIVATOR · DEPRESSANT · COLLECTOR", equation:"PbS floats while ZnS is depressed by NaCN; CuSO₄ can reactivate ZnS in a later stage.", insight:"Selective reagents change mineral-surface wettability without changing the bulk ore.", accent:"#54f0b5", accent2:"#ffb14d", steps:[{label:"Collector",detail:"Adsorbs on the selected sulphide and makes its surface hydrophobic.",symbol:"C"},{label:"Depressant",detail:"NaCN suppresses ZnS during PbS–ZnS separation in the classical exam model.",symbol:"D"},{label:"Activator",detail:"CuSO₄ can activate ZnS for a subsequent flotation stage.",symbol:"A"}]},
  "bayer-leaching.webp": { title:"The Bayer Process", kicker:"BAUXITE → PURE ALUMINA", equation:"Al₂O₃ + 2NaOH + 3H₂O → 2Na[Al(OH)₄]", insight:"Hot concentrated NaOH dissolves amphoteric alumina; Fe₂O₃ and TiO₂ remain mainly in red mud.", accent:"#48a8ff", accent2:"#ff9d4d", steps:[{label:"Digestion",detail:"Finely ground bauxite is treated with hot concentrated NaOH under pressure.",symbol:"1"},{label:"Clarification",detail:"Insoluble red mud is removed from sodium aluminate liquor.",symbol:"2"},{label:"Precipitation",detail:"Al(OH)₃ is precipitated from the clarified solution.",symbol:"3"},{label:"Calcination",detail:"2Al(OH)₃ → Al₂O₃ + 3H₂O.",symbol:"4"}]},
  "blast-furnace.webp": { title:"Blast Furnace Architecture", kicker:"IRON EXTRACTION · ZONE BY ZONE", equation:"Fe₂O₃ + 3CO → 2Fe + 3CO₂", insight:"CO is the chief reducing gas; coke supplies heat and regenerates CO near the tuyeres.", accent:"#45b8ff", accent2:"#ff8a32", steps:[{label:"Reduction zone",detail:"Rising CO reduces iron oxides progressively to iron.",symbol:"500–900°C"},{label:"Slag zone",detail:"CaCO₃ → CaO; CaO + SiO₂ → CaSiO₃.",symbol:"900–1200°C"},{label:"Combustion zone",detail:"C + O₂ → CO₂; CO₂ + C → 2CO.",symbol:"≈1900°C"},{label:"Hearth",detail:"Dense molten iron settles below the lighter slag layer.",symbol:"OUT"}]},
  "calcination-roasting.webp": { title:"Calcination vs Roasting", kicker:"THERMAL PREPARATION OF ORES", equation:"MCO₃ → MO + CO₂  |  2MS + 3O₂ → 2MO + 2SO₂", insight:"Calcination uses limited or no air; roasting deliberately uses excess oxygen.", accent:"#ffb347", accent2:"#ff5f7d", steps:[{label:"Calcination",detail:"Carbonates and hydrated ores are heated in limited or absent air.",symbol:"Δ"},{label:"Roasting",detail:"Sulphide ores are heated strongly in excess air or oxygen.",symbol:"O₂"},{label:"Porosity",detail:"Gas evolution opens pores and improves later reduction.",symbol:"◌"},{label:"Control",detail:"Overheating can sinter particles and close the pore network.",symbol:"!"}]},
  "carbon-reduction.webp": { title:"Carbon Monoxide Reduction", kicker:"THE TRUE REDUCING AGENT", equation:"MOₓ + xCO → M + xCO₂", insight:"In many furnaces carbon is added, but gaseous CO performs most of the oxide reduction.", accent:"#b6ff45", accent2:"#ff8d35", steps:[{label:"Generate heat",detail:"C + O₂ → CO₂ releases heat.",symbol:"1"},{label:"Generate CO",detail:"CO₂ + C → 2CO at high temperature.",symbol:"2"},{label:"Reduce oxide",detail:"CO removes oxygen from Fe, Zn and Sn oxides.",symbol:"3"},{label:"Separate phases",detail:"Molten metal is tapped below the lighter slag.",symbol:"4"}]},
  "concentration-spectrum.webp": { title:"Four Pillars of Ore Concentration", kicker:"CHOOSE THE PROPERTY THAT DIFFERS", equation:"Density · Magnetism · Wettability · Solubility", insight:"The best concentration method exploits the largest useful difference between ore and gangue.", accent:"#67e8f9", accent2:"#f05cff", steps:[{label:"Gravity",detail:"Uses density difference between mineral and gangue.",symbol:"ρ"},{label:"Magnetic",detail:"Uses unequal response to a magnetic field.",symbol:"B"},{label:"Froth flotation",detail:"Uses selective hydrophobicity of mineral surfaces.",symbol:"○"},{label:"Leaching",detail:"Uses selective dissolution in a suitable reagent.",symbol:"aq"}]},
  "copper-self-reduction.webp": { title:"Copper Extraction by Self-Reduction", kicker:"PARTIAL ROASTING → BLISTER COPPER", equation:"2Cu₂O + Cu₂S → 6Cu + SO₂", insight:"The unroasted sulphide reduces the newly formed oxide; no external carbon is required in the decisive step.", accent:"#ff9b5a", accent2:"#45d8ff", steps:[{label:"Partial roasting",detail:"Part of Cu₂S is oxidised to Cu₂O while SO₂ leaves.",symbol:"1"},{label:"Iron removal",detail:"FeO combines with silica to form FeSiO₃ slag.",symbol:"2"},{label:"Self-reduction",detail:"Cu₂O reacts with remaining Cu₂S to form copper.",symbol:"3"},{label:"Blister copper",detail:"Escaping SO₂ produces the characteristic blistered surface.",symbol:"4"}]},
  "cyanide-process.webp": { title:"MacArthur–Forrest Cyanide Process", kicker:"GOLD AND SILVER LEACHING", equation:"4Au + 8CN⁻ + O₂ + 2H₂O → 4[Au(CN)₂]⁻ + 4OH⁻", insight:"Oxygen enables cyanide complexation; zinc then displaces the dissolved precious metal.", accent:"#ffd04d", accent2:"#9c6cff", steps:[{label:"Crush",detail:"Expose the precious-metal particles to the leach solution.",symbol:"1"},{label:"Complexation",detail:"Dilute cyanide plus air dissolves Au/Ag as dicyano complexes.",symbol:"2"},{label:"Cementation",detail:"Zn displaces Au/Ag from the pregnant solution.",symbol:"3"},{label:"Recovery",detail:"The precipitate is filtered, smelted and refined.",symbol:"4"}]},
  "electrolytic-reduction.webp": { title:"Electrolytic Reduction", kicker:"REACTIVE METALS REQUIRE ELECTRONS", equation:"Mⁿ⁺ + ne⁻ → M", insight:"Highly reactive metals cannot be reduced economically by carbon; molten-salt electrolysis is used.", accent:"#7a9cff", accent2:"#ff66c8", steps:[{label:"Molten electrolyte",detail:"The ionic compound must conduct without water.",symbol:"1"},{label:"Cathode",detail:"Metal cations gain electrons and form the metal.",symbol:"−"},{label:"Anode",detail:"Anions are oxidised; gas or halogen may be released.",symbol:"+"},{label:"Collection",detail:"The product is removed without reoxidation.",symbol:"4"}]},
  "electrorefining.webp": { title:"Electrorefining", kicker:"IMPURE ANODE · PURE CATHODE", equation:"Anode: M → Mⁿ⁺ + ne⁻   |   Cathode: Mⁿ⁺ + ne⁻ → M", insight:"The impure metal is the positive anode; pure metal plates on the negative cathode.", accent:"#38e8ff", accent2:"#ff9b62", steps:[{label:"Positive anode",detail:"The impure metal dissolves into the electrolyte.",symbol:"+"},{label:"Ion migration",detail:"Target-metal ions move through the electrolyte.",symbol:"→"},{label:"Negative cathode",detail:"Pure metal is deposited by reduction.",symbol:"−"},{label:"Anode slime",detail:"Less reactive or insoluble impurities settle below.",symbol:"↓"}]},
  "ellingham.webp": { title:"Ellingham Diagram Logic", kicker:"ΔG° OF OXIDE FORMATION VS TEMPERATURE", equation:"ΔG° = ΔH° − TΔS°", insight:"A reductant can reduce an oxide when formation of the reductant oxide is thermodynamically more favourable.", accent:"#ff6f61", accent2:"#65d6ff", steps:[{label:"Lower line",detail:"More negative ΔG° means the oxide is more stable.",symbol:"↓"},{label:"Slope",detail:"Slope reflects the entropy change of oxidation.",symbol:"m"},{label:"Crossing",detail:"A crossing temperature can change reduction feasibility.",symbol:"×"},{label:"Kinetics",detail:"Thermodynamic possibility does not guarantee a fast reaction.",symbol:"k"}]},
  "froth-chemistry.webp": { title:"Froth-Flotation Reagent Chemistry", kicker:"CONTROL THE MINERAL SURFACE", equation:"Collector adsorption → hydrophobic mineral → bubble attachment", insight:"Collectors, frothers, activators and depressants perform different jobs; they are not interchangeable.", accent:"#ca72ff", accent2:"#49efb5", steps:[{label:"Collector",detail:"Makes the selected mineral surface hydrophobic.",symbol:"C"},{label:"Frother",detail:"Stabilises a mobile froth without creating selectivity alone.",symbol:"F"},{label:"Activator",detail:"Improves collector attachment to a chosen mineral.",symbol:"A"},{label:"Depressant",detail:"Keeps an unwanted mineral wetted and in the pulp.",symbol:"D"}]},
  "froth-flotation.webp": { title:"Froth Flotation Cell", kicker:"SULPHIDE ORES · SURFACE WETTABILITY", equation:"Hydrophobic mineral + air bubble → mineral-rich froth", insight:"The valuable sulphide rises with bubbles while hydrophilic gangue remains in the aqueous pulp.", accent:"#c75cff", accent2:"#5af1d0", steps:[{label:"Condition",detail:"Add collector and other selective reagents to the pulp.",symbol:"1"},{label:"Aerate",detail:"Disperse fine air bubbles through the agitated slurry.",symbol:"2"},{label:"Attach",detail:"Hydrophobic mineral particles adhere to bubbles.",symbol:"3"},{label:"Skim",detail:"Remove and collapse the mineral-rich froth.",symbol:"4"}]},
  "gravity-separation.webp": { title:"Gravity Separation", kicker:"DENSITY-BASED ORE BENEFICIATION", equation:"Settling tendency increases with particle size and density contrast.", insight:"Liberation and controlled water flow are essential; density difference alone is not enough.", accent:"#43e6bf", accent2:"#ffad55", steps:[{label:"Feed",detail:"Crushed, size-classified ore enters the flowing-water system.",symbol:"1"},{label:"Stratify",detail:"Dense mineral settles while lighter gangue travels farther.",symbol:"2"},{label:"Riffles",detail:"Barriers retain the heavy fraction on a shaking table.",symbol:"3"},{label:"Collect",detail:"Heavy concentrate and light tailings leave separately.",symbol:"4"}]},
  "hall-heroult.webp": { title:"Hall–Héroult Process", kicker:"ALUMINIUM BY MOLTEN-SALT ELECTROLYSIS", equation:"2Al₂O₃ + 3C → 4Al + 3CO₂", insight:"Cryolite lowers the operating temperature and increases conductivity; carbon anodes are consumed.", accent:"#b56cff", accent2:"#4fd8ff", steps:[{label:"Electrolyte",detail:"Alumina dissolves in molten cryolite with CaF₂.",symbol:"1"},{label:"Cathode",detail:"Al³⁺ + 3e⁻ → Al(l) at the carbon-lined bottom.",symbol:"−"},{label:"Anode",detail:"Oxide ions oxidise carbon to CO₂.",symbol:"+"},{label:"Tap metal",detail:"Dense molten aluminium collects beneath the bath.",symbol:"4"}]},
  "leaching.webp": { title:"Selective Leaching", kicker:"DISSOLVE THE VALUE, REJECT THE GANGUE", equation:"Solid ore + selective reagent → soluble metal species + residue", insight:"A successful leach combines chemical selectivity with efficient solid–liquid separation.", accent:"#4ce0ff", accent2:"#7dff71", steps:[{label:"Contact",detail:"Finely divided ore meets the chosen leaching reagent.",symbol:"1"},{label:"React",detail:"The desired component forms a soluble complex or salt.",symbol:"2"},{label:"Separate",detail:"Undissolved gangue is filtered or settled out.",symbol:"3"},{label:"Recover",detail:"Metal is precipitated, cemented or electrowon.",symbol:"4"}]},
  "magnetic-separation.webp": { title:"Magnetic Separation Conveyor", kicker:"MAGNETIC AND NON-MAGNETIC FRACTIONS", equation:"Different magnetic susceptibility → different trajectories", insight:"Cassiterite can be separated from magnetic wolframite impurities after suitable crushing and sizing.", accent:"#38edc1", accent2:"#ff5db1", steps:[{label:"Uniform feed",detail:"A thin layer of crushed ore moves on the belt.",symbol:"1"},{label:"Magnetic pulley",detail:"Magnetic particles remain attached for longer.",symbol:"B"},{label:"Trajectory split",detail:"Non-magnetic particles fall farther from the roller.",symbol:"↘"},{label:"Separate bins",detail:"The two fractions are collected independently.",symbol:"4"}]},
  "master-matrix.webp": { title:"Metallurgy Master Matrix", kicker:"ORE → CONCENTRATION → CONVERSION → EXTRACTION → REFINING", equation:"The route is selected from ore type, metal reactivity and product purity required.", insight:"Do not memorise one universal route: each metal follows a chemically justified sequence.", accent:"#57b5ff", accent2:"#ff9c4a", steps:[{label:"Iron",detail:"Hematite → concentration → blast furnace → steelmaking/refining.",symbol:"Fe"},{label:"Aluminium",detail:"Bauxite → Bayer alumina → Hall–Héroult electrolysis.",symbol:"Al"},{label:"Copper / Zinc",detail:"Sulphide concentration → oxidation/smelting or electrowinning → refining.",symbol:"Cu/Zn"},{label:"Gold / Silver",detail:"Gravity or cyanide leaching → cementation/electrowinning → bullion refining.",symbol:"Au/Ag"}]},
  "metallurgy-hero.webp": { title:"Extractive Metallurgy", kicker:"THE ELEMENTAL BLUEPRINT", equation:"Ore → concentration → conversion → reduction/electrolysis → refining", insight:"Extraction is a linked thermodynamic and separation problem, not a single reaction.", accent:"#84ff39", accent2:"#ff5ab7", steps:[{label:"Concentrate",detail:"Remove bulk gangue using a physical or chemical property difference.",symbol:"1"},{label:"Convert",detail:"Prepare an oxide, chloride or soluble complex suitable for extraction.",symbol:"2"},{label:"Extract",detail:"Use reduction, electrolysis or displacement to obtain the metal.",symbol:"3"},{label:"Refine",detail:"Remove remaining impurities and cast the final product.",symbol:"4"}]},
  "molten-electrolysis.webp": { title:"The Molten Rule", kicker:"WHY REACTIVE METALS NEED FUSED SALTS", equation:"In water: 2H₂O + 2e⁻ → H₂ + 2OH⁻   |   Molten: Mⁿ⁺ + ne⁻ → M", insight:"For Na, Mg, Ca and Al, water is reduced preferentially; an anhydrous molten electrolyte is required.", accent:"#74ff3b", accent2:"#ff5c5c", steps:[{label:"Aqueous bath",detail:"Water competes successfully for electrons and hydrogen evolves.",symbol:"×"},{label:"Molten bath",detail:"No water is present, so target cations can be reduced.",symbol:"✓"},{label:"Dry operation",detail:"Moisture would lower current efficiency and contaminate products.",symbol:"H₂O"},{label:"Product removal",detail:"Separate the metal before it reacts with the electrolyte or air.",symbol:"M"}]},
  "mond-process.webp": { title:"Mond Process", kicker:"VAPOUR-PHASE REFINING OF NICKEL", equation:"Ni + 4CO ⇌ Ni(CO)₄(g) ⇌ Ni + 4CO", insight:"Nickel carbonyl forms at lower temperature and decomposes at higher temperature to deposit pure nickel.", accent:"#66f0cf", accent2:"#ffa75c", steps:[{label:"Carbonyl formation",detail:"Impure Ni reacts with CO near 50–60°C.",symbol:"1"},{label:"Volatilise",detail:"Ni(CO)₄ is separated as a volatile molecular species.",symbol:"2"},{label:"Decompose",detail:"At about 180°C the carbonyl deposits pure Ni.",symbol:"3"},{label:"Recycle CO",detail:"Released CO is returned to the process.",symbol:"4"}]},
  "ore-foundations.webp": { title:"Mineral, Ore and Gangue", kicker:"FOUNDATIONS OF EXTRACTIVE METALLURGY", equation:"Ore = valuable mineral + associated gangue, mined profitably", insight:"Every ore is a mineral assemblage, but not every mineral deposit is an economically workable ore.", accent:"#58e8c3", accent2:"#ff9d52", steps:[{label:"Mineral",detail:"A naturally occurring inorganic solid with characteristic composition/structure.",symbol:"M"},{label:"Ore",detail:"A mineral source from which a metal can be extracted economically.",symbol:"O"},{label:"Gangue",detail:"Earthy or rocky material associated with the valuable mineral.",symbol:"G"},{label:"Concentrate",detail:"The upgraded fraction enriched in the desired mineral.",symbol:"C"}]},
  "parkes-process.webp": { title:"Parkes Process", kicker:"DESILVERIZATION OF LEAD", equation:"Ag preferentially enters the Zn-rich phase; Zn–Ag crust is skimmed.", insight:"Molten Pb and Zn are poorly miscible, while silver is far more soluble in zinc than in lead.", accent:"#d8ff3e", accent2:"#53d8ff", steps:[{label:"Add zinc",detail:"Zinc is mixed with molten lead containing dissolved silver.",symbol:"1"},{label:"Partition",detail:"Silver transfers preferentially into the zinc-rich phase.",symbol:"2"},{label:"Cool",detail:"A Zn–Ag crust forms and floats above the lead.",symbol:"3"},{label:"Skim",detail:"Remove the crust; recover silver and recycle zinc separately.",symbol:"4"}]},
  "porosity-sintering.webp": { title:"Porosity vs Sintering", kicker:"PREPARING AN OXIDE FOR FAST REDUCTION", equation:"Open pores ↑ → gas access ↑ → reduction rate ↑", insight:"Thermal treatment should remove volatiles without fusing particles into a dense, poorly permeable mass.", accent:"#ffb450", accent2:"#60e7ff", steps:[{label:"Gas release",detail:"Calcination or roasting opens channels through the solid.",symbol:"1"},{label:"Porous oxide",detail:"CO or H₂ can reach a much larger internal surface.",symbol:"2"},{label:"Overheating",detail:"Particle necks form and pores begin to close.",symbol:"3"},{label:"Sintered mass",detail:"Gas diffusion slows and reduction becomes inefficient.",symbol:"4"}]},
  "reduction-spectrum.webp": { title:"Choosing the Reduction Method", kicker:"MATCH METAL REACTIVITY TO THE EXTRACTANT", equation:"Low reactivity: heat/self-reduction · medium: C/CO/Al · high: electrolysis", insight:"The method must be both thermodynamically possible and industrially practical.", accent:"#ff7a5f", accent2:"#7d6cff", steps:[{label:"Low-reactivity metals",detail:"Thermal decomposition or self-reduction may be sufficient.",symbol:"Cu/Hg"},{label:"Moderate metals",detail:"C, CO or H₂ can reduce many oxides.",symbol:"Fe/Zn/Sn"},{label:"Stable oxides",detail:"Aluminothermy can supply a large driving force and heat.",symbol:"Cr/Mn"},{label:"Highly reactive metals",detail:"Molten-salt electrolysis is required.",symbol:"Na/Mg/Al"}]},
  "refining-toolkit.webp": { title:"The Refining Toolkit", kicker:"SELECT BY IMPURITY AND METAL PROPERTY", equation:"Refining exploits differences in volatility, solubility, electrochemistry or phase behaviour.", insight:"The extraction method gives crude metal; refining targets the final purity specification.", accent:"#5adfff", accent2:"#ff79bb", steps:[{label:"Electrorefining",detail:"Cu, Ag, Ni and other suitable conductors.",symbol:"e⁻"},{label:"Distillation",detail:"Volatile metals such as Zn, Cd and Hg.",symbol:"vap"},{label:"Zone refining",detail:"Ultra-pure Si, Ge and related materials.",symbol:"zone"},{label:"Vapour phase",detail:"Mond for Ni; van Arkel for Ti and Zr.",symbol:"gas"}]},
  "self-reduction.webp": { title:"Self-Reduction Loop", kicker:"PARTIAL OXIDATION CREATES THE OXIDE", equation:"2PbO + PbS → 3Pb + SO₂", insight:"The sulphide already present in the ore reduces the oxide produced during partial roasting.", accent:"#59b8ff", accent2:"#73ff50", steps:[{label:"Air on",detail:"Part of the sulphide is oxidised to oxide and SO₂.",symbol:"1"},{label:"Air off",detail:"Heating continues while further oxidation is stopped.",symbol:"2"},{label:"Internal reductant",detail:"Remaining sulphide reacts directly with the oxide.",symbol:"3"},{label:"Metal forms",detail:"Pb or Cu is produced with SO₂ as the gaseous product.",symbol:"4"}]},
  "slag.webp": { title:"The Chemistry of Slag", kicker:"REMOVE GANGUE AS A FUSIBLE PHASE", equation:"CaO + SiO₂ → CaSiO₃(l)", insight:"Flux converts infusible gangue into a low-melting slag that floats above the denser molten metal.", accent:"#58efaa", accent2:"#ff8e35", steps:[{label:"Identify gangue",detail:"Acidic SiO₂ needs a basic flux; basic oxide gangue needs an acidic flux.",symbol:"1"},{label:"Add flux",detail:"Limestone commonly supplies CaO after decomposition.",symbol:"2"},{label:"Form slag",detail:"The flux and gangue react to produce a fusible compound.",symbol:"3"},{label:"Protect metal",detail:"The floating slag layer reduces reoxidation and enables phase separation.",symbol:"4"}]},
  "thermite.webp": { title:"Aluminothermic Reduction", kicker:"THE INDUSTRIAL CRUCIBLE", equation:"3Mn₃O₄ + 8Al → 9Mn + 4Al₂O₃", insight:"Aluminium has a strong affinity for oxygen; the highly exothermic reaction also supplies molten product.", accent:"#ff8f38", accent2:"#54efb4", steps:[{label:"Mix",detail:"Finely divided metal oxide is mixed with aluminium powder.",symbol:"1"},{label:"Ignite",detail:"A high activation energy must be overcome to start the reaction.",symbol:"2"},{label:"Oxygen transfer",detail:"Aluminium forms very stable Al₂O₃.",symbol:"3"},{label:"Molten metal",detail:"The reaction heat can produce a fluid metal phase.",symbol:"4"}]},
  "universal-framework.webp": { title:"Universal Framework for Metal Extraction", kicker:"CONCENTRATE → CONVERT → EXTRACT → REFINE", equation:"Raw ore → upgraded mineral → extractable compound → crude metal → pure metal", insight:"This framework organises nearly every extraction route while allowing individual metals to skip or combine stages.", accent:"#38d9e6", accent2:"#ff4f98", steps:[{label:"Concentrate",detail:"Remove most gangue by physical or chemical beneficiation.",symbol:"1"},{label:"Convert",detail:"Prepare an oxide, chloride or solution species suitable for extraction.",symbol:"2"},{label:"Extract",detail:"Break the metal–nonmetal bond using reduction or electrolysis.",symbol:"3"},{label:"Refine",detail:"Remove residual impurities and achieve the required purity.",symbol:"4"}]},
  "van-arkel.webp": { title:"Van Arkel–de Boer Process", kicker:"IODIDE REFINING OF TITANIUM AND ZIRCONIUM", equation:"Ti + 2I₂ ⇌ TiI₄(g) ⇌ Ti + 2I₂", insight:"A volatile iodide transports the metal to a hot filament where it decomposes and deposits ultra-pure metal.", accent:"#bd7cff", accent2:"#54e9cf", steps:[{label:"Form iodide",detail:"Impure Ti or Zr reacts with iodine at moderate temperature.",symbol:"1"},{label:"Transport",detail:"Volatile TiI₄ or ZrI₄ reaches the hot filament.",symbol:"2"},{label:"Decompose",detail:"The iodide decomposes on the filament.",symbol:"3"},{label:"Recycle iodine",detail:"I₂ returns to the cooler feed zone.",symbol:"4"}]},
  "vapor-phase-refining.webp": { title:"Vapour-Phase Refining", kicker:"VOLATILE INTERMEDIATE · PURE DEPOSIT", equation:"Impure M → volatile compound → pure M + recycled reagent", insight:"The intermediate must form selectively, be volatile, and decompose cleanly at a different temperature.", accent:"#76e9ff", accent2:"#dd7cff", steps:[{label:"Selective reaction",detail:"Only the target metal forms the volatile compound efficiently.",symbol:"1"},{label:"Vaporise",detail:"The compound separates from non-volatile impurities.",symbol:"2"},{label:"Decompose",detail:"A controlled hot zone releases pure metal.",symbol:"3"},{label:"Recycle",detail:"The carrier reagent is recovered for repeated use.",symbol:"4"}]},
  "zone-refining.webp": { title:"Zone Refining", kicker:"ULTRA-PURE SEMICONDUCTOR MATERIALS", equation:"k = Csolid / Cliquid < 1 for impurities rejected by the solid", insight:"A narrow molten zone sweeps impurities toward one end of a solid bar through repeated passes.", accent:"#58c9ff", accent2:"#ff65c8", steps:[{label:"Create zone",detail:"A ring heater melts a narrow section of the bar.",symbol:"1"},{label:"Partition",detail:"Most impurities prefer the liquid zone when k < 1.",symbol:"2"},{label:"Translate",detail:"The heater moves slowly along the bar.",symbol:"3"},{label:"Remove tail",detail:"The impurity-rich end is cut away after repeated passes.",symbol:"4"}]},
};

const frame: CSSProperties = {
  position:"relative", overflow:"hidden", margin:"0 auto", padding:"clamp(18px,3vw,34px)", borderRadius:24,
  border:"1px solid rgba(205,224,245,.26)", background:"linear-gradient(145deg,#020406 0%,#070b10 50%,#020304 100%)",
  boxShadow:"0 34px 100px rgba(0,0,0,.62), inset 0 1px 0 rgba(255,255,255,.06)", color:"#f7fafc"
};

export default function MetallurgyVisual({ src, alt }: { src: string; alt?: string }) {
  const key = src.split("/").pop() ?? "";
  const spec = V[key] ?? {
    title: alt || "Metallurgy Process Visual",
    kicker: "DARK · CRISP · UNBRANDED",
    equation: "Ore property → selected operation → separated or purified metal product",
    insight: "This replacement uses live vector text and a true charcoal background, so labels remain sharp and no embedded logo survives.",
    accent: "#59e7ff", accent2: "#b27cff",
    steps: [
      { label: "Principle", detail: "Identify the physical or chemical property used by the process.", symbol: "1" },
      { label: "Operation", detail: "Apply controlled temperature, reagent, field or electrical energy.", symbol: "2" },
      { label: "Separation", detail: "Remove gangue or impurities into a different phase.", symbol: "3" },
      { label: "Product", detail: "Collect the upgraded mineral or purified metal.", symbol: "4" },
    ],
  };
  const glow = `0 0 24px ${spec.accent}40`;
  return (
    <figure className="metallurgy-visual" style={{ width:"min(100%,1100px)", maxWidth:1100, padding:0, background:"transparent", border:0, boxShadow:"none" }}>
      <section style={frame} aria-label={spec.title}>
        <div aria-hidden style={{ position:"absolute", inset:0, background:`radial-gradient(circle at 12% 0%,${spec.accent}12,transparent 30%),radial-gradient(circle at 90% 15%,${spec.accent2}10,transparent 28%)`, pointerEvents:"none" }} />
        <div style={{ position:"relative" }}>
          <div style={{ color:spec.accent, fontSize:12, fontWeight:900, letterSpacing:".18em", textTransform:"uppercase", marginBottom:8 }}>{spec.kicker}</div>
          <h3 style={{ margin:"0 0 18px", color:"#fff", fontSize:"clamp(1.55rem,4vw,3rem)", lineHeight:1.02, letterSpacing:"-.035em", textShadow:glow }}>{spec.title}</h3>
          <div style={{ height:2, width:"min(420px,70%)", marginBottom:22, background:`linear-gradient(90deg,${spec.accent},${spec.accent2},transparent)`, boxShadow:glow }} />
          <div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))", gap:12 }}>
            {spec.steps.map((step,index)=>(
              <div key={step.label} style={{ minHeight:142, padding:"16px 16px 15px", borderRadius:16, border:`1px solid ${index%2?spec.accent2:spec.accent}55`, background:"linear-gradient(150deg,rgba(16,24,34,.94),rgba(4,7,11,.90))", boxShadow:"inset 0 1px 0 rgba(255,255,255,.035)" }}>
                <div style={{ display:"flex", alignItems:"center", gap:10, marginBottom:10 }}>
                  <span style={{ display:"grid", placeItems:"center", minWidth:36, height:36, padding:"0 8px", borderRadius:11, border:`1px solid ${index%2?spec.accent2:spec.accent}88`, color:index%2?spec.accent2:spec.accent, fontWeight:900, boxShadow:glow }}>{step.symbol ?? index+1}</span>
                  <strong style={{ color:"#fff", fontSize:15, lineHeight:1.15 }}>{step.label}</strong>
                </div>
                <p style={{ margin:0, color:"#cbd6e4", fontSize:13.5, lineHeight:1.52 }}>{step.detail}</p>
              </div>
            ))}
          </div>
          <div style={{ marginTop:14, padding:"14px 16px", borderRadius:14, border:"1px solid rgba(220,230,244,.22)", background:"rgba(0,0,0,.44)", color:"#f7fafc", fontSize:"clamp(.9rem,2vw,1.05rem)", lineHeight:1.45, fontFamily:"ui-monospace,SFMono-Regular,Menlo,monospace", overflowWrap:"anywhere" }}>{spec.equation}</div>
          <div style={{ marginTop:12, padding:"13px 16px", borderLeft:`4px solid ${spec.accent}`, borderRadius:"0 12px 12px 0", background:`linear-gradient(90deg,${spec.accent}16,transparent 78%)`, color:"#dce7f4", fontSize:13.5, lineHeight:1.52 }}><b style={{ color:spec.accent }}>KEY INSIGHT · </b>{spec.insight}</div>
        </div>
      </section>
      {alt && <figcaption>{alt}</figcaption>}
    </figure>
  );
}

