import Link from "next/link";
import "./metallurgy.css";

const parts = [["Foundations, Ores, Gangue & Physical Concentration", "Mineral/ore/gangue, master metallurgy flow, gravity and magnetic separation"], ["Froth Flotation, Activators, Depressants & Leaching", "Collector/frother chemistry, activation, depression and selective dissolution"], ["Ore Formula Bank, Calcination, Roasting & Sintering", "Complete ore-name bank, thermal conversion, porosity and sintering"], ["Carbon/CO Reduction, Flux–Slag, Self-Reduction & Thermite", "Smelting, Lux–Flood, lead self-reduction, aluminothermy, thermal decomposition"], ["Hydrometallurgy & Electrometallurgical Reduction", "Cementation, low-grade Cu, fused-salt electrolysis and Downs logic"], ["Complete Refining Toolkit: Poling to Electrorefining", "Poling, liquation, distillation, zone/Mond/van Arkel, cupellation, amalgamation, electrorefining"], ["Ellingham Diagram — Full Thermodynamic Treatment", "Slopes, phase changes, decomposition, carbon/H2 reduction criteria and limitations"], ["Silver, Gold, Cyanide Leaching & Parkes Process", "MacArthur–Forrest, Zn displacement, desilverisation, parting and purification"], ["Extraction & Refining of Tin", "Cassiterite beneficiation, black tin, smelting losses and refining"], ["Extraction of Magnesium", "Carnallite, Dow seawater route, dehydration problem and fused MgCl2 electrolysis"], ["Aluminium — Complete Bauxite to 99.99% Al", "Bayer/Hall/Serpek, Hall–Héroult, electrolyte roles, anode chemistry and Hoopes"], ["Lead — Galena to Refined Pb", "Flotation, roasting, carbon/self reduction, slag and refining"], ["Copper — Chalcopyrite to Pure Cu", "Roasting, matte, converter stages, blister Cu, poling and electrorefining"], ["Zinc — Sphalerite to Pure Zn", "Selective flotation, roasting, high-T reduction, vapour condensation and refining"], ["Iron — Blast Furnace & Pig Iron Chemistry", "Ore preparation, furnace zones, CO reduction, slag, bosh/hearth impurity pickup"], ["Steelmaking & Heat Treatment", "Puddling/Bessemer/open hearth/LD, carbon classes, ferroalloys, anneal/quench/temper/case hardening"], ["Source Appendix I — Reaction Chemistry", "Precipitation, lithopone, disproportionation, halogens and Frasch sulphur"], ["Source Appendix II — Redox & Nitric Acid", "Manganate, comproportionation, acid redox, HNO3 products, passivation and Cu(I)"]] as const;

export const metadata = {
 title: "Metallurgy — Complete 81-Page JEE Advanced Notes",
 description: "Full-source metallurgy reconstruction: complete 81-page content, rigorous theory, corrected chemistry and teaching graphics."
};

export default function MetallurgyPage(){return <main className="metallurgy-shell"><section className="metallurgy-hero"><p className="eyebrow">INORGANIC CHEMISTRY · COMPLETE SOURCE REBUILD</p><h1>Metallurgy</h1><p>81-page source rebuilt at full theory depth with selective high-value graphics. No summary compression.</p><img className="metallurgy-cover-art" src="/notes/metallurgy/reference/metallurgy-hero-dark-v4.webp" alt="Extractive metallurgy elemental blueprint" /><div className="coverage-strip"><b>81/81 source pages mapped</b><span>18 focused parts</span><span>Images, diagrams and SVGs restored</span></div></section><section className="part-grid">{parts.map(([title,description],i)=>{const slug=`part-${i+1}`;return <Link key={slug} href={`/notes/metallurgy/${slug}`} className="part-card"><span>{String(i+1).padStart(2,"0")}</span><div><h2>{title}</h2><p>{description}</p></div></Link>})}</section></main>}

