import { Chapter } from "./types";

export const physicalChapters: Chapter[] = [
  {
    id: "some-basic-concepts",
    title: "Some Basic Concepts of Chemistry",
    category: "physical",
    exams: ["neet", "jeeMain", "jeeAdvanced"],
    difficulty: 2,
    estimatedHours: 8,
    prerequisites: [],
    concepts: [],
    pyqTags: [],
  },
  {
    id: "structure-of-atom",
    title: "Structure of Atom",
    category: "physical",
    exams: ["neet", "jeeMain", "jeeAdvanced"],
    difficulty: 2,
    estimatedHours: 10,
    prerequisites: ["some-basic-concepts"],
    concepts: [],
    pyqTags: [],
  },
  {
    id: "states-of-matter",
    title: "States of Matter",
    category: "physical",
    exams: ["neet", "jeeMain", "jeeAdvanced"],
    difficulty: 2,
    estimatedHours: 8,
    prerequisites: ["some-basic-concepts"],
    concepts: [],
    pyqTags: [],
  },
  {
    id: "thermodynamics",
    title: "Thermodynamics",
    category: "physical",
    exams: ["neet", "jeeMain", "jeeAdvanced"],
    difficulty: 4,
    estimatedHours: 14,
    prerequisites: ["states-of-matter"],
    concepts: [],
    pyqTags: [],
  },
  {
    id: "equilibrium",
    title: "Equilibrium",
    category: "physical",
    exams: ["neet", "jeeMain", "jeeAdvanced"],
    difficulty: 4,
    estimatedHours: 14,
    prerequisites: ["thermodynamics"],
    concepts: [],
    pyqTags: [],
  },
  {
    id: "redox-reactions",
    title: "Redox Reactions",
    category: "physical",
    exams: ["neet", "jeeMain", "jeeAdvanced"],
    difficulty: 2,
    estimatedHours: 6,
    prerequisites: ["some-basic-concepts"],
    concepts: [],
    pyqTags: [],
  },
  {
    id: "solutions",
    title: "Solutions",
    category: "physical",
    exams: ["neet", "jeeMain", "jeeAdvanced"],
    difficulty: 3,
    estimatedHours: 10,
    prerequisites: ["thermodynamics"],
    concepts: [],
    pyqTags: [],
  },
  {
    id: "electrochemistry",
    title: "Electrochemistry",
    category: "physical",
    exams: ["neet", "jeeMain", "jeeAdvanced"],
    difficulty: 4,
    estimatedHours: 12,
    prerequisites: ["redox-reactions"],
    concepts: [],
    pyqTags: [],
  },
  {
    id: "chemical-kinetics",
    title: "Chemical Kinetics",
    category: "physical",
    exams: ["neet", "jeeMain", "jeeAdvanced"],
    difficulty: 3,
    estimatedHours: 10,
    prerequisites: ["thermodynamics"],
    concepts: [],
    pyqTags: [],
  },
  {
    id: "surface-chemistry",
    title: "Surface Chemistry",
    category: "physical",
    exams: ["neet"],
    difficulty: 2,
    estimatedHours: 5,
    prerequisites: [],
    concepts: [],
    pyqTags: [],
  },
  {
    id: "solid-state",
    title: "Solid State",
    category: "physical",
    exams: ["jeeMain"],
    difficulty: 3,
    estimatedHours: 8,
    prerequisites: [],
    concepts: [],
    pyqTags: [],
  },
];