import ChemicalEquilibriumPart from "./ChemicalEquilibriumPart";

const html = "<h2>Equilibrium Constant $K_c$: Derivation and Interpretation</h2>\n<h3>Axioms &amp; Definitions</h3>\n<p>For</p>\n<p>$$aA+bB\\rightleftharpoons cC+dD$$</p>\n<ul>\n<li>forward rate:</li>\n</ul>\n<p>$$r_f=k_f[A]^a[B]^b$$</p>\n<ul>\n<li>backward rate:</li>\n</ul>\n<p>$$r_b=k_b[C]^c[D]^d$$</p>\n<p>At equilibrium $r_f=r_b$.</p>\n<h3>Deep Theory &amp; Mechanics</h3>\n<p>Equating the two mass-action rate expressions gives:</p>\n<p>$$k_f[A]^a[B]^b=k_b[C]^c[D]^d$$</p>\n<p>Rearrangement produces a ratio that is constant at a fixed temperature:</p>\n<p>$$\\frac{[C]^c[D]^d}{[A]^a[B]^b}=\\frac{k_f}{k_b}=K_c$$</p>\n<p>The source defines equilibrium as <strong>dynamic</strong> because reactant and product active masses remain constant only because the two rates are equal.</p>\n<p>The numerical value of $K_c$ depends on:</p>\n<ul>\n<li>temperature;</li>\n<li>the balanced chemical equation as written;</li>\n<li>the standard concentration convention.</li>\n</ul>\n<p>It does not depend on the initial composition, provided the same equilibrium and temperature are reached.</p>\n<h3>Quantitative Data &amp; Formulas</h3>\n<p>$$K_c=\\frac{[C]^c[D]^d}{[A]^a[B]^b}$$</p>\n<p>For</p>\n<p>$$\\mathrm{N_2(g)+3H_2(g)\\rightleftharpoons 2NH_3(g)}$$</p>\n<p>$$K_c=\\frac{[NH_3]^2}{[N_2][H_2]^3}$$</p>\n<p>For</p>\n<p>$$\\mathrm{H_2(g)+I_2(g)\\rightleftharpoons 2HI(g)}$$</p>\n<p>$$K_c=\\frac{[HI]^2}{[H_2][I_2]}$$</p>\n<p>For</p>\n<p>$$\\mathrm{CaCO_3(s)\\rightleftharpoons CaO(s)+CO_2(g)}$$</p>\n<p>$$K_c=[CO_2]$$</p>\n<p>For acid ionisation in water:</p>\n<p>$$\\mathrm{CH_3COOH(aq)+H_2O(l)\\rightleftharpoons CH_3COO^-(aq)+H_3O^+(aq)}$$</p>\n<p>$$K_c=\\frac{[CH_3COO^-][H_3O^+]}{[CH_3COOH]}$$</p>\n<h3>Explicit Trend Sequences</h3>\n<ul>\n<li>$K_c\\gg1$: products predominate.</li>\n<li>$K_c\\ll1$: reactants predominate.</li>\n<li>$K_c\\approx1$: appreciable quantities of both sides are present.</li>\n</ul>\n<h3>Anomalies &amp; Special Cases</h3>\n<ul>\n<li>Pure solids, pure liquids, and the solvent in a dilute solution are omitted because their activities are constant.</li>\n<li>Units of a concentration-based $K_c$ depend on $\\Delta n$ if raw molar concentrations are used; the thermodynamic equilibrium constant is dimensionless.</li>\n</ul>\n<h3>Solved Examples &amp; Proofs</h3>\n<p>For $2A\\rightleftharpoons B$, the equilibrium expression is:</p>\n<p>$$K_c=\\frac{[B]}{[A]^2}$$</p>\n<p>For the reverse equation $B\\rightleftharpoons2A$:</p>\n<p>$$K_c'=\\frac{[A]^2}{[B]}=\\frac{1}{K_c}$$</p>\n<h3>Practice Questions</h3>\n<ol>\n<li>Write $K_c$ for $2SO_2+O_2\\rightleftharpoons2SO_3$.<br />\n<strong>Answer:</strong> $K_c=[SO_3]^2/([SO_2]^2[O_2])$.</li>\n<li>Write $K_c$ for $NH_4HS(s)\\rightleftharpoons NH_3(g)+H_2S(g)$.<br />\n<strong>Answer:</strong> $K_c=[NH_3][H_2S]$.</li>\n</ol>\n";

export const chemicalEquilibriumPart06 = {
  part: 6,
  title: "Equilibrium Constant Kc: Derivation and Interpretation",
  sourcePages: "16\u201317",
} as const;

export default function Part06() {
  return <ChemicalEquilibriumPart {...chemicalEquilibriumPart06} html={html} />;
}
