import { ChemicalBondingDeepVisual } from "../_components/ChemicalBondingDeepVisuals";
import Image from "next/image";
import { ChemBondPartShell, DataTable, DiagramBox, FormulaLine, ImportantNote, LearningObjectives, MathText, PracticeQuestion, SummaryStrip, TopicBlock, TrapCallout } from "./_shared";

const I = ({ math }: { math: string }) => <MathText math={math} />;
const T = ({ h, r }: { h: string[]; r: string[][] }) => <DataTable headers={h} rows={r} />;

export default function FajansPart() {
  return <ChemBondPartShell part={20} title="Fajans’ Rules, Polarisation & Covalent Character">
    <LearningObjectives items={["Treat ionic–covalent bonding as a continuum, not a binary label.", "Predict covalency from charge, radius, configuration and anion polarisability.", "Separate a Fajans tendency from structure-, lattice- and solvation-controlled outcomes.", "Connect polarisation with hydrolysis, oxides, thermal stability, colour and redox."]} />
    <figure className="overflow-hidden rounded-2xl border border-cyan-300/20 bg-[#07131f]"><Image src="/images/chemical-bonding/fajans/bonding-continuum-dark.png" alt="Dark visual showing the continuum from predominantly ionic through polarised ionic to enhanced covalent character" width={1536} height={1024} priority className="h-auto w-full object-cover" /><figcaption className="border-t border-cyan-300/10 px-4 py-3 text-sm text-cyan-50">Bonding is a continuum: Fajans’ rules explain the middle regime, where polarisation adds covalent character to an otherwise ionic interaction.</figcaption></figure>
    <TopicBlock number={158} title="Bonding is a continuum: polarisation introduces covalency">
      <p>A heteronuclear bond is rarely an ideal limit. A nominally ionic bond acquires covalent character when the cation distorts the anion electron cloud: this is <strong>polarisation</strong>. Fajans’ rules are qualitative rules for this enhanced covalent character, not a substitute for a complete structure or thermodynamic calculation.</p>
      <T h={["Term", "Meaning", "Usual role"]} r={[["Polarisation", "deformation of an ion cloud by a neighbour", "creates asymmetric density"], ["Polarising power", "ability of a cation to deform a cloud", "small / high-charge cation"], ["Polarisability", "ease of cloud deformation", "large, diffuse anion"]]} />
      <DiagramBox title="Three stages and electron-density overlap"><ChemicalBondingDeepVisual kind="fajans" /></DiagramBox>
      <figure className="overflow-hidden rounded-2xl border border-fuchsia-300/20 bg-[#07131f]"><Image src="/images/chemical-bonding/fajans/polarisation-stages-dark.png" alt="Dark three-stage visual of anion polarisation progressing from an ionic interaction to electron-density overlap" width={1024} height={1536} className="h-auto w-full object-cover" /><figcaption className="px-4 py-3 text-sm text-fuchsia-100">The deformation becomes chemically significant only when electron density moves into the internuclear region.</figcaption></figure>
      <p><strong>Stage I:</strong> density is mainly localised on X⁻. <strong>Stage II:</strong> Mⁿ⁺ pulls the anion cloud toward itself. <strong>Stage III:</strong> density occupies the internuclear region, so overlap and covalent character rise.</p>
      <FormulaLine math={String.raw`\text{polarisation}\uparrow\;\to\;\text{electron-density overlap}\uparrow\;\to\;\text{covalent character}\uparrow`} />
      <ImportantNote title="Redox limit">Ionic interaction → partial polarisation → partial covalency → complete electron transfer. The final limit is internal redox, not merely “very high polarisation”.</ImportantNote>
    </TopicBlock>
    <TopicBlock number={159} title="Mutual polarisation and the complete Fajans rules">
      <p>An anion can also deform a cation. For pseudo-noble-gas / d¹⁰ cations, the relatively deformable, poorly shielding d cloud is pushed rearward by the anion; the positive nuclear field is more exposed toward X⁻. Cation and anion polarisation then reinforce one another, especially in soft-ion interactions.</p>
      <FormulaLine math={String.raw`\text{cation deformation}\to\text{less screening toward X}^-\to\text{anion deformation}\to\text{covalency}`} />
      <figure className="overflow-hidden rounded-2xl border border-violet-300/20 bg-[#07131f]"><Image src="/images/chemical-bonding/fajans/mutual-polarisation-dark.png" alt="Dark feedback-loop diagram showing mutual polarisation of a d10 cation and a soft anion" width={1536} height={1024} className="h-auto w-full object-cover" /><figcaption className="px-4 py-3 text-sm text-violet-100">Mutual polarisation is a feedback effect: poor d-electron shielding exposes more positive field, which further distorts the anion.</figcaption></figure>
      <T h={["Driver", "Change increasing covalency", "Physical reason"]} r={[["Cation radius","smaller: Li⁺ > Na⁺ > K⁺","positive charge concentrated"],["Cation charge","higher: Na⁺ < Mg²⁺ < Al³⁺ < Si⁴⁺","stronger electric field"],["Configuration","pseudo-noble d¹⁰ / poor d,f shielding","greater effective field, mutual effect"],["Anion size","F⁻ < Cl⁻ < Br⁻ < I⁻","diffuse cloud deforms easily"],["Anion charge","larger negative charge","expanded cloud, e⁻–e⁻ repulsion"],["HSAB","hard polariser + soft partner","strong density response"]]} />
      <p>Ionic potential, <I math={String.raw`\phi=z/r`} />, is a useful comparative field index: <I math={String.raw`\phi\uparrow\to`} /> polarising power ↑ → covalent character ↑. It is not a universal equation for covalency.</p>
      <T h={["Cation","r / Å","φ","Cation","r / Å","φ","Cation","r / Å","φ"]} r={[["Li⁺","0.59","1.7","Be²⁺","0.31","6.4","B³⁺","0.20","15.0"],["Na⁺","0.97","1.0","Mg²⁺","0.65","3.1","Al³⁺","0.50","6.0"],["K⁺","1.33","0.75","Ca²⁺","0.99","2.0","Ga³⁺","0.62","4.8"]]} />
      <TrapCallout trap={<>“Noble-gas cations are more polarising” appears in a flawed summary.</>} reality={<>For comparable charge/radius, pseudo-noble-gas cations generally polarise more; their d¹⁰ cloud also enables stronger mutual polarisation. Na⁺/Cu⁺ and K⁺/Ag⁺ data confirm the source correction.</>} />
    </TopicBlock>
    <TopicBlock number={160} title="Electronic configuration: why size alone can fail">
      <p>Na⁺, K⁺ and Ca²⁺ have ns²np⁶ noble-gas shells. Cu⁺, Ag⁺, Cd²⁺, Hg²⁺ and Au⁺ have (n−1)d¹⁰ pseudo-noble-gas shells. Filled d electrons shield less effectively than s,p electrons, increasing the positive field felt by the anion.</p>
      <T h={["Cation","Shell","r₊ / pm","Approx. Z*","m.p. chloride / °C"]} r={[["Na⁺","8e","95","2.2","801"],["Cu⁺","18e","96","3.7","422"],["K⁺","8e","133","2.2","776"],["Ag⁺","18e","126","3.7","455"],["Ca²⁺","8e","99","3.2","772"],["Cd²⁺","18e","97","4.7","568"]]} />
      <p>Illustrative source estimate: <I math={String.raw`S_{Na^+}=8(0.85)+2(1)=8.8,\; Z^*=11-8.8=2.2`} />; Cu⁺ gives about 3.7. Use relevant ns,np valence levels in this comparison.</p>
      <ImportantNote title="d/f shielding exception">Covalent character rises approximately ZnCl₂ &lt; CdCl₂ &lt; HgCl₂ despite radius increasing: Zn²⁺ 74 pm &lt; Cd²⁺ 97 pm &lt; Hg²⁺ 110 pm. Electronic configuration/heavy-atom effects override size-only reasoning. In the broader context, corresponding 3d &lt; 4d &lt; 5d series can show increasing covalency despite increasing radius, because d and especially f shielding becomes poorer; it is a contextual tendency, not a size-free law. The source’s ZnCl₂ “essentially complete” versus HgCl₂ “~2%” dissociation comparison is condition-dependent, not a universal constant. Hard-anion Hg(II) salts can still be relatively ionic.</ImportantNote>
    </TopicBlock>
    <TopicBlock number={161} title="Melting point: a structure-sensitive consequence">
      <p>Greater covalency <em>often</em> lowers m.p./b.p. because an extended ionic lattice may become a less-connected polymer, dimer or molecular solid. It is not absolute: diamond and SiC are covalent networks with extremely high melting/sublimation temperatures. Compare connectivity, polymerisation, packing and intermolecular forces.</p>
      <T h={["M²⁺","Be²⁺","Mg²⁺","Ca²⁺","Sr²⁺","Ba²⁺"]} r={[["r / Å","0.31","0.65","0.99","1.13","1.35"],["φ","6.45","3.07","2.02","1.77","1.48"],["m.p. MCl₂ / °C","405","712","772","872","960"]]} />
      <T h={["Cation","r / Å","φ","m.p. chloride / °C","m.p. bromide / °C"]} r={[["Na⁺","0.97","1.03","800","755"],["Mg²⁺","0.65","3.07","712","700"],["Al³⁺","0.50","6.00","180","97.5"],["Si⁴⁺","0.40","10.00","57*","—"],["Ti⁴⁺","0.68","5.88","137*","—"]]} />
      <p className="text-xs text-white/55">*Marked values are boiling-point-type data in the canonical source table.</p>
      <T h={["Halide","NaX m.p. / °C","LiX m.p. / °C","CaX₂ m.p. / °C"]} r={[["F⁻","988","870","1392"],["Cl⁻","800","613","772"],["Br⁻","755","547","730"],["I⁻","651","446","575"]]} />
      <DiagramBox title="Framework → layer → molecular dimer"><ChemicalBondingDeepVisual kind="fajans-structures" /></DiagramBox>
      <p><strong>Structural chemistry.</strong> SnF₄ (and PbF₄) has 2D layers of approximately octahedral MF₆ units sharing four equatorial vertices; source Sn–F separations are ~188/202 pm. SnCl₄/SnBr₄/SnI₄ are molecular. AlF₃ is a 3D ReO₃-type corner-sharing AlF₆ network; AlCl₃ is layered with edge-sharing AlCl₆ octahedra; AlBr₃/AlI₃ form Al₂X₆ bridged dimers. FeF₃ and FeCl₃ are structurally related to AlF₃ and AlCl₃.</p>
      <T h={["Structure-sensitive sequence","Values / °C","Why a simple trend fails"]} r={[["AlF₃ > AlCl₃ > AlI₃ > AlBr₃","1291 > 192 > 189 > 98","network → layer → dimer"],["SnF₄ > SnI₄ > SnBr₄ > SnCl₄","705 > 144.5 > 31 > −33","polymeric fluoride; molecular heavier halides"],["SnCl₂ vs SnCl₄","246/652 vs −33/114 (m.p./b.p.)","Sn(IV) chloride is molecular/covalent"],["PbCl₂ vs PbCl₄","501/950 vs −15/—","higher oxidation state polarises more"],["TlCl vs TlCl₃","430/720 vs 25/—","same principle"]]} />
      <T h={["Noble-gas-type chloride","Pseudo-noble-gas-type chloride","m.p. / °C"]} r={[["NaCl (r 0.95 Å)","CuCl (r 0.96 Å)","801 / 422"],["KCl (1.33 Å)","AgCl (1.36 Å)","776 / 455"],["CaCl₂ (0.99 Å)","CdCl₂ (0.97 Å)","772 / 568"],["CaCl₂ (0.99 Å)","HgCl₂ (1.10 Å)","772 / 276"],["RbCl (1.48 Å)","AuCl (1.37 Å)","715 / 170 (decomp.)"]]} />
      <p>RbCl/AuCl reinforces the configuration lesson: the pseudo-noble Au⁺ chloride is much more covalent and molecular despite comparable radius. GeF₄ is a structural caution: despite fluoride, it has a low melting point and a molecular lattice; PbCl₄ is molecular, whereas PbBr₄/PbI₄ are unstable.</p>
    </TopicBlock>
    <TopicBlock number={162} title="Solubility, ionic-potential applications and hydrolysis">
      <p>For comparable salts, covalency generally reduces polar-solvent solubility and increases organic-medium compatibility. Actual solubility balances lattice enthalpy, hydration/solvation, entropy, complex formation and hydrolysis: BaSO₄ is a key ionic-but-insoluble caution.</p>
      <T h={["Silver halide","Covalent character","Solubility parameter in water, 25 °C"]} r={[["AgF","least","soluble"],["AgCl","↑","2 × 10⁻¹⁰"],["AgBr","↑","5 × 10⁻¹³"],["AgI","greatest","8 × 10⁻¹⁷"]]} />
      <p>KI is much more soluble in alcohol than KCl; LiCl dissolves in alcohol/pyridine. The source notes FeCl₃ (~177 °C sublimation) versus AlCl₃ (~347 °C) and greater organic-solvent compatibility for FeCl₃. CuX, AgX and AuX are often sparingly water-soluble relative to alkali salts.</p>
      <ImportantNote title="Empirical, not universal">For selected anhydrous halides, especially chlorides, <I math={String.raw`\sqrt\phi\lesssim2.2`} /> suggests predominantly ionic/fused conducting behaviour; <I math={String.raw`\sqrt\phi\gtrsim2.2`} /> suggests greater covalent/nonionic character. It is a guide, not a boundary law.</ImportantNote>
      <T h={["Application","High-φ consequence","Comparison / caution"]} r={[["Complex formation","stronger ligand attraction","Be²⁺ > Mg²⁺ > Ca²⁺"],["Hydration","stronger ion–dipole interaction","Li⁺ > Na⁺ > K⁺; Be²⁺ > Mg²⁺ > Ca²⁺"],["Oxide nature","M–O covalency ↑; basicity ↓","Na₂O > Li₂O > MgO > BeO; BeO amphoteric"],["Oxide √φ guide","<2.2 basic; 2.2–3.2 amphoteric; >3.2 acidic","empirical only, r in Å"],["Hydrolysis","coordinated O–H becomes more polar","Fe³⁺ > Fe²⁺; SnCl₄ > SnCl₂; Be²⁺/Al³⁺ high"],["Deformation","directional bonding changes mechanical response","not a universal hardness rule"]]} />
      <FormulaLine math={String.raw`[M(OH_2)_6]^{n+}\rightleftharpoons[M(OH)(H_2O)_5]^{(n-1)+}+H^+`} />
      <p>Many lithium salts are hydrated, including LiCl·2H₂O and LiClO₄·3H₂O; completely anhydrous lithium salts can be difficult to obtain. Crystal packing can modify hydration trends. AlCl₃·nH₂O cannot simply be heated to anhydrous AlCl₃: Al³⁺ promotes coordinated-water hydrolysis, so oxy/hydroxy products can form. Silicates likewise contain substantial Si–O covalency despite ionic formulations.</p>
    </TopicBlock>
    <TopicBlock number={162} title="Thermal stability, colour and the redox limit">
      <p>Polarising M²⁺ destabilises a large oxyanion: <I math={String.raw`MCO_3\to MO+CO_2`} />. Thus BeCO₃ &lt; MgCO₃ &lt; CaCO₃ &lt; SrCO₃ &lt; BaCO₃ in thermal stability; CdCO₃/PbCO₃ are electronic-configuration anomalies.</p>
      <T h={["Carbonate","r(M²⁺) / Å","φ","Decomposition / °C"]} r={[["BeCO₃","0.31","6.5","<100"],["MgCO₃","0.65","3.1","400"],["CaCO₃","0.99","2.0","900"],["SrCO₃","1.13","1.77","1290"],["BaCO₃","1.35","1.48","1360"],["CdCO₃ / PbCO₃","~1.0","—","350 / 350"]]} />
      <p>The idea extends to sulfates, nitrates, hydroxides and phosphates, but decomposition is thermodynamic: gas formation often makes <I math={String.raw`\Delta S>0`} />, and <I math={String.raw`\Delta G=\Delta H-T\Delta S`} />. Packing and oxide acid–base chemistry also matter; comparable charge density contributes to diagonal relationship.</p>
      <DiagramBox title="Ligand-to-metal charge transfer"><ChemicalBondingDeepVisual kind="fajans-lmct" /></DiagramBox>
      <p><strong>LMCT.</strong> An anion-centred occupied orbital transfers into a metal-centred acceptor orbital. Better overlap/energy matching lowers the excitation into the visible: PbCl₂ is white while PbI₂ is golden yellow; SnS₂ yellow vs white SnO₂; Sb₂S₃ coloured vs white Sb₂O₃; ZnO white vs HgO coloured.</p>
      <T h={["Pale chloride","Coloured iodide","Related insight"]} r={[["HgCl₂","HgI₂ red","iodide excitation is easier"],["AgCl","AgI yellow","higher polarisability"],["PbCl₂","PbI₂ golden yellow","I HOMO → Pb acceptor lower energy"],["SnCl₄","SnI₄ deep red","heavy-centre/iodide matching"],["GeCl₄","GeI₄ orange","same trend"],["ZnS white","CdS yellow; HgS red/black polymorphs","cinnabar red; metacinnabar black"]]} />
      <figure className="overflow-hidden rounded-2xl border border-amber-300/20 bg-amber-300/[0.04]"><Image src="/images/chemical-bonding/fajans/halide-colour-series.png" alt="Original laboratory appearance comparison of silver halides, lead iodide and lead sulfide" width={1536} height={1024} className="h-auto w-full object-cover" /><figcaption className="p-4 text-sm leading-relaxed text-amber-100"><strong>Appearance is chemical evidence.</strong> The yellow-to-golden iodide solids and black PbS connect polarisability with lower-energy charge-transfer or band-gap absorption; actual colour still depends on electronic structure and crystal form.</figcaption></figure>
      <p>Source orbital shorthand: Cd²⁺(5s) ← S²⁻(π), Hg²⁺(6s) ← S²⁻(π), and Fe³⁺(3d, e*g) ← O²⁻(π) for red iron(III) oxide. CrO₄²⁻ and MnO₄⁻ are intensely coloured through O→metal charge transfer. PbS is black both because Pb²⁺ strongly polarises S²⁻ and because the covalent crystal has a small band gap/broad visible absorption; PbCl₂ has chiefly UV transitions.</p>
      <ImportantNote title="When polarisation becomes redox">Pb⁴⁺ + I⁻: <I math={String.raw`2I^-\to I_2+2e^-`} />, <I math={String.raw`Pb^{4+}+2e^-\to Pb^{2+}`} />, overall <I math={String.raw`PbI_4\to PbI_2+I_2`} />. Likewise Fe³⁺ oxidises iodide, so simple FeI₃ is unstable, while FeCl₃ exists.</ImportantNote>
      <figure className="overflow-hidden rounded-2xl border border-rose-300/20 bg-[#07131f]"><Image src="/images/chemical-bonding/fajans/redox-limit-pbi4-dark.png" alt="Dark visual explaining the redox limit of polarisation and lead tetraiodide decomposition" width={1536} height={1024} className="h-auto w-full object-cover" /><figcaption className="px-4 py-3 text-sm text-rose-100">At the redox limit, polarisation is no longer a partial deformation: iodide is oxidised and Pb(IV) is reduced.</figcaption></figure>
    </TopicBlock>
    <TopicBlock number={162} title="Master comparison and examination practice">
      <T h={["Predominantly ionic","Enhanced covalent character"]} r={[["large, low-charge, well-shielded noble-gas cation","small, high-charge, pseudo-noble/poor d,f shielding cation"],["small compact anion","large diffuse, higher-charge anion"],["small distortion; fluoride tendency","large distortion; iodide tendency"],["often high m.p. in comparable simple series; higher molten ionic conductivity","often lower m.p. after molecularisation; lower ionic conductivity"],["polar-solvent solubility may be hydration-favoured; oxide more basic","water solubility often reduced; organic compatibility/oxide acidity increase"],["weak or UV charge-transfer absorption","visible LMCT more likely"]]} />
      <SummaryStrip items={["Compare charge → radius → electronic configuration → anion size/charge → actual structure.", "LiCl > NaCl > KCl; MI > MBr > MCl > MF; AgI > AgBr > AgCl > AgF in covalency.", "Fajans predicts tendencies; lattice, polymerisation, solvation, entropy, packing and band structure decide actual properties."]} />
      <PracticeQuestion prompt={<>Q30. In A⁺X⁻, covalent bonding is greatest when: (a) both ions are small; (b) A⁺ is small and X⁻ is large; (c) ions are similar in size; (d) X⁻ is small and A⁺ large.</>} answer={<>(b): small cation = high polarising power; large anion = high polarisability.</>} />
      <PracticeQuestion prompt={<>Q31. In which species are bonds non-directional? (a) NCl₃ (b) RbCl (c) BeCl₂ (d) BCl₃.</>} answer={<>RbCl: the predominantly ionic solid.</>} />
      <PracticeQuestion prompt={<>Q32. Which substance gives a non-conducting aqueous solution? (a) green vitriol (b) Chile/Indian saltpetre (c) alcohol (d) potash alum.</>} answer={<>Alcohol, because it does not generate mobile ions appreciably.</>} />
      <PracticeQuestion prompt={<>Q33. Which LiCl/NaCl statement is wrong? (a) LiCl has lower m.p. (b) LiCl dissolves more in organic solvents (c) LiCl ionises less in water (d) fused LiCl conducts less than fused NaCl.</>} answer={<>(c) is misleading: although LiCl is more covalent, ordinary dilute water strongly hydrates it and it is essentially fully dissociated.</>} />
      <PracticeQuestion prompt={<>Q34. Which has the highest melting point? (a) NaCl (b) KCl (c) MgO (d) BaO.</>} answer={<>MgO, owing to the very large lattice enthalpy of small Mg²⁺ and O²⁻ ions.</>} />
      <PracticeQuestion prompt={<>Q35. Ionic-crystal stability principally depends on: (a) high electron affinity of the anion-former (b) lattice energy (c) low cation-former ionisation energy (d) low heat of sublimation.</>} answer={<>Lattice energy of the crystal.</>} />
      <PracticeQuestion prompt={<>Q36. In which solvent does KI have highest solubility? (a) C₆H₆ (b) (CH₃)₂CO (c) CH₃OH (d) CCl₄.</>} answer={<>CH₃OH among these choices, because its high polarity gives strong ion–dipole solvation.</>} />
      <PracticeQuestion prompt={<>Q37. Among LiCl, BeCl₂, MgCl₂ and RbCl, greatest and least ionic character respectively are: (a) LiCl/RbCl (b) RbCl/BeCl₂ (c) RbCl/MgCl₂ (d) MgCl₂/BeCl₂.</>} answer={<>RbCl and BeCl₂.</>} />
      <PracticeQuestion prompt={<>Q38. Highest covalency: (a) NaCl (b) MgCl₂ (c) AgCl (d) CsCl.</>} answer={<>AgCl, because pseudo-noble-gas d¹⁰ Ag⁺ strongly polarises Cl⁻.</>} />
      <PracticeQuestion prompt={<>Q39. Least soluble in water: (a) BaCl₂ (b) Ba(NO₃)₂ (c) MgSO₄ (d) BaSO₄.</>} answer={<>BaSO₄.</>} />
      <PracticeQuestion prompt={<>Q40. The source gives options for Na₂SO₄, BeSO₄, MgSO₄ and BaSO₄ solubility; which treatment is correct?</>} answer={<>Do not predict this from Fajans alone: lattice and hydration energies both control sulfate solubility. BaSO₄ is unquestionably least soluble.</>} />
      <PracticeQuestion prompt={<>Q41. Alkali-metal fluoride solubility increases down the group because: (a) hydration rises/lattice falls (b) both fall, hydration faster (c) both fall, lattice faster (d) both rise, hydration faster.</>} answer={<>(c): both magnitudes decrease, but lattice enthalpy decreases more rapidly.</>} />
      <PracticeQuestion prompt={<>Q42. Covalency is favoured by: (a) smaller cation (b) larger anion (c) large charge on cation and anion (d) all of these.</>} answer={<>(d), all of these.</>} />
      <PracticeQuestion prompt={<>Q43. RbBr melts about 682 °C while NaF melts near 988 °C. Principal reason: (a) NaF molar mass (b) RbBr more covalent (c) electronegativity difference (d) larger ionic-radius sum/interionic distance in RbBr.</>} answer={<>(d): the greater interionic distance lowers Coulombic lattice attraction. This is principally a lattice-energy comparison, not merely covalency.</>} />
      <PracticeQuestion prompt={<>Q49. Incorrect order: (a) PbCl₂ &gt; CaCl₂ &gt; SrCl₂ &gt; BaCl₂ covalency (b) PbF₄ &gt; PbCl₄ &gt; PbBr₄ &gt; PbI₄ stability (c) KF &gt; KCl &gt; KBr &gt; KI m.p. (d) CHCl₃ &gt; CH₃Cl &gt; CCl₄ b.p.</>} answer={<>(d): CCl₄ boils above CHCl₃ and far above CH₃Cl.</>} />
      <PracticeQuestion prompt={<>Q50. If CdI₂ is pink, CdCl₂ will be: (a) yellow (b) red (c) blue (d) cannot be predicted.</>} answer={<>(d): colour cannot be predicted from Fajans alone; it depends on actual electronic transitions and crystal structure. CdCl₂ is ordinarily colourless/white.</>} />
      <PracticeQuestion prompt={<>Q51. Which orders are correct? I BeSO₄ &lt; MgSO₄ &lt; CaSO₄ &lt; SrSO₄ &lt; BaSO₄ thermal stability; II ZnO &gt; BeO &gt; MgO &gt; CaO basicity; III LiOH &gt; NaOH &gt; KOH &gt; RbOH &gt; CsOH solubility; IV NaCl &gt; KCl &gt; RbCl &gt; CsCl &gt; LiCl m.p.</>} answer={<>I and IV. II reverses the normal rise of basicity toward CaO; III reverses the broad rise of hydroxide solubility down Group 1.</>} />
      <PracticeQuestion prompt={<>Q52. Correct solubility order(s): I CaCO₃ &gt; SrCO₃ &gt; BaCO₃; II Li₂CO₃ &lt; Na₂CO₃ &lt; K₂CO₃; III K₂CO₃ &lt; Rb₂CO₃ &lt; Cs₂CO₃; IV Na₂CO₃ &gt; K₂CO₃ &gt; Rb₂CO₃.</>} answer={<>I, II and III; IV is opposite to the usual increasing alkali-carbonate solubility trend.</>} />
      <PracticeQuestion prompt={<>Q53. At 400–500 °C, which of LiH, NaH, Li₂CO₃ and Na₂CO₃ decomposes?</>} answer={<>This is temperature- and data-definition-dependent. The conceptual trend: alkali hydride stability decreases down the group, while Li₂CO₃ is anomalously less thermally stable than other alkali carbonates; check exact experimental conditions.</>} />
    </TopicBlock>
  </ChemBondPartShell>;
}
