const content = String.raw`
# Part 6 — Complete Refining Toolkit: Poling to Electrorefining

> **Complete-source reconstruction:** theory is preserved at full teaching depth; diagrams are used only where they explain mechanism, apparatus, phase movement or decision logic.


## 9. Refining — Why Extraction Is Not the End

Crude metal can still contain:
- other metals,
- non-metals (C, S, As, Sb, etc.),
- dissolved gases,
- entrained slag or oxide.

The source divides refining broadly into thermal methods and electrorefining. Actual achievable impurity levels depend on the specific metal/process; treat the handwritten “1%” and “0.01%” figures as illustrative, not universal limits.

## 10. Poling

Poling is a classical refining method used especially for metals such as **Cu and Sn**.

### Stage 1 — selective oxidation
Air is blown through molten impure metal. Impurities with higher oxygen affinity are oxidised preferentially. Non-metallic impurities may form volatile oxides; some target metal also becomes oxidised and forms scum.

### Stage 2 — reduction with green wood / reducing gases
Air is stopped and green wooden poles are introduced/stirred through the melt. Pyrolysis and partial combustion generate reducing gases (CO and hydrocarbons), which reduce some target-metal oxide back to metal.

The result is a balance between:
- oxidation/removal of impurity,
- recovery of metal accidentally oxidised during blowing.

## 1. Poling — Completion of the Source Treatment

During the oxidising stage, some desired metal can form oxide and enter the scum. After air blowing stops, reducing gases generated by green wood help reconvert that oxide to metal. Non-metal impurities such as C, S, As and Sb are removed by oxidation/volatilisation to the extent permitted by the process.

---

## 2. Liquation / Sweating

Liquation is used when the desired metal has a **much lower melting point** than the bulk of the impurities.

Classical examples: Sn, Pb, Bi.

- The impure solid is heated on an inclined surface.
- The lower-melting metal liquefies first and drains away.
- Higher-melting solid impurities remain behind.

> The source calls this “sweating”; in metallurgy, sweating/liquation terminology may vary with the exact operation, but the core principle is selective melting.

---

## 3. Distillation

Distillation is useful when the desired metal is sufficiently volatile relative to impurities.

Textbook examples: **Zn, Hg and Cd**.

Approximate boiling points useful for reasoning:
- Cd: $\sim767^\circ C$
- Zn: $\sim907^\circ C$ (older handwritten notes often round to $920^\circ C$)
- Pb: $\sim1749^\circ C$
- Fe: $\sim2862^\circ C$

Thus Zn/Cd can be volatilised and condensed while less volatile Pb/Fe remain.

---

## 4. Zone Refining — Ultra-Purification

![Zone refining](/notes/metallurgy/reference/zone-refining.webp)

**Principle:** an impurity may be more soluble in the **liquid** phase than in the solid phase.

A narrow molten zone is moved slowly along a solid ingot:
1. impurities enter the molten zone preferentially,
2. as the zone moves, purified solid crystallises behind it,
3. impurities travel toward one end,
4. repeated passes increase purity.

Used for ultra-pure semiconductor/material-grade elements such as Si, Ge and Ga; zone refining is also applicable to several other metals/metalloids when the distribution coefficient is favourable.

> **Source sketch question corrected:** a cylindrical rod is convenient, not a fundamental chemical requirement. What matters is the ability to maintain and translate a controlled molten zone through the material.

---

## 5. Vapour-Phase Refining

A successful vapour-phase refining route requires an intermediate that is:
1. sufficiently **volatile**, and
2. readily **decomposed at an achievable temperature** to regenerate pure metal.

### Mond process — Ni
![Mond process for nickel](/notes/metallurgy/reference/mond-process.webp)

At moderate temperature:
$$Ni+4CO\rightleftharpoons Ni(CO)_4(g)$$

Nickel tetracarbonyl is volatile. On heating:
$$Ni(CO)_4\rightarrow Ni+4CO$$

Impurities that do not form the same volatile carbonyl are left behind.

### van Arkel–de Boer / iodide process
![van Arkel iodide refining](/notes/metallurgy/reference/van-arkel.webp)

Used for very pure reactive metals such as Ti, Zr and Hf.

Formation of volatile iodide:
$$M+2I_2\rightarrow MI_4(g)$$

Decomposition on a hot filament:
$$MI_4\rightarrow M+2I_2$$

Iodine is recycled.

---

## 6. Cupellation

Cupellation is a classical method for separating noble metals from easily oxidised base metals, especially **removing Pb from Ag/Au-rich material**.

Lead is oxidised:
$$2Pb+O_2\rightarrow2PbO$$

$PbO$ (litharge) is removed by volatilisation/absorption into the porous cupel, while noble metals resist oxidation.

---

## 7. Amalgamation

Hg forms amalgams with several metals, including Ag and Au.

General idea:
$$\text{impure Ag/Au}+Hg\rightarrow \text{amalgam}$$

Heating drives off Hg because of its much greater volatility, leaving Ag/Au behind.

> **Historical/environmental note:** mercury-based extraction has major toxicological and environmental hazards. It is retained here only because it appears in the source and is historically/exam relevant.

---

## 8. Electrorefining — General Principle

![Electrorefining cell](/notes/metallurgy/reference/electrorefining.webp)

- **Anode:** impure metal.
- **Cathode:** thin sheet/starting surface of pure metal.
- **Electrolyte:** suitable soluble salt of the metal.

Anode:
$$M\rightarrow M^{n+}+ne^-$$

Cathode:
$$M^{n+}+ne^-\rightarrow M$$

Impurities fall into three broad classes:
1. more active species that enter solution but do not plate under chosen conditions,
2. noble/insoluble species that collect as **anode mud**,
3. troublesome species controlled by electrolyte chemistry and cell potential.

Anode mud can contain valuable Ag, Au and Pt-group metals, so it is processed rather than discarded.

---

![Master refining methods](/notes/metallurgy/reference/refining-toolkit.webp)



![Mond and van Arkel refining](/notes/metallurgy/reference/vapor-phase-refining.webp)


## Refining data/examples explicitly restored from the source
### Broad classification in the handwritten notes
- **Thermal refining:** impurity reduction typically to about the percent level depending on process.
- **Electrorefining:** can reach very high purity, often $99.9\%+$ and in many systems much higher.

### Poling — potential logic
During oxidative air-blowing, impurities more readily oxidised than the metal are removed as volatile oxides or slag. Some of the desired metal also oxidises. After air is stopped, green/raw wood or another reducing source generates CO/H$_2$/hydrocarbons and reduces the metal oxide back.

### Liquation / sweating
Used when desired metal melts well below major impurities. Source examples and melting points:
- Sn $\approx232^\circ C$
- Pb $\approx327^\circ C$
- Bi $\approx271^\circ C$
The source notes that liquation requires sufficiently high impurity content for effective separation; the exact threshold is process-specific, not a universal 10–12% rule.

### Distillation — source boiling-point logic
- Zn $\approx907^\circ C$ (older notes often round to 920°C)
- Cd $\approx767^\circ C$
- Hg $\approx357^\circ C$
- Pb $\approx1749^\circ C$
Volatility differences allow separation/condensation.

### Zone refining / ultra-refining
A narrow molten zone is moved slowly along a solid rod. Most impurities prefer the liquid when distribution coefficient $k=C_s/C_l<1$ and are swept toward one end.
Used for ultra-pure semiconductor-grade materials such as Si and Ge; source also mentions Ga, In and B in the broader high-purity materials context.

### Mond process (Ni)
$$Ni+4CO\xrightarrow{50-60^\circ C}Ni(CO)_4(g)$$
$$Ni(CO)_4\xrightarrow{\sim180^\circ C}Ni+4CO$$
Intermediate requirements: **volatile and thermally decomposable at an accessible temperature**.

### van Arkel–de Boer iodide process
Used for very pure Ti/Zr/Hf (and conceptually related iodide chemistry). Volatile iodide forms at lower temperature and decomposes on a hot filament.

### Cupellation
Pb impurity in Ag/Au is oxidised to PbO; PbO is removed/absorbed/volatilised depending on setup, leaving noble metal enriched.

### Amalgamation
Hg dissolves Ag/Au to form amalgam; heating distils Hg. Source note: Fe/Pt-type containers are chosen because they do not readily form amalgams with Hg.

### Electrorefining — complete electrode logic
- **Anode:** impure metal, $M\rightarrow M^{n+}+ne^-$.
- **Cathode:** pure metal sheet, $M^{n+}+ne^-\rightarrow M$.
- Electrolyte contains a soluble salt of the metal.
- More active impurities may remain in solution; noble impurities such as Ag/Au/Pt can fall as **anode mud**.
- Faraday’s law makes the rate of metal dissolution/deposition charge-controlled; under steady conditions bulk metal-ion concentration can remain approximately stable.

`;
export default content;
