const content = String.raw`
# Part 3 — Refining, Ellingham Diagram, Silver & Gold

> **Scope:** Source pages 24–43. Classical processes are retained where pedagogically useful; outdated/oversimplified statements are labelled or corrected.

## 1. Poling — Completion of the Source Treatment

During the oxidising stage, some desired metal can form oxide and enter the scum. After air blowing stops, reducing gases generated by green wood help reconvert that oxide to metal. Non-metal impurities such as C, S, As and Sb are removed by oxidation/volatilisation to the extent permitted by the process.

---

## 2. Liquation / Sweating

Liquation is used when the desired metal has a **much lower melting point** than the bulk of the impurities.

Classical examples: Sn, Pb, Bi.

- The impure solid is heated on an inclined surface.
- The lower-melting metal liquefies first and drains away.
- Higher-melting solid impurities remain behind.

> The source calls this “sweating”; in metallurgy, sweating/liquation terminology may vary with the exact operation, but the core principle is selective melting.

---

## 3. Distillation

Distillation is useful when the desired metal is sufficiently volatile relative to impurities.

Textbook examples: **Zn, Hg and Cd**.

Approximate boiling points useful for reasoning:
- Cd: $\sim767^\circ C$
- Zn: $\sim907^\circ C$ (older handwritten notes often round to $920^\circ C$)
- Pb: $\sim1749^\circ C$
- Fe: $\sim2862^\circ C$

Thus Zn/Cd can be volatilised and condensed while less volatile Pb/Fe remain.

---

## 4. Zone Refining — Ultra-Purification

![Zone refining](/notes/metallurgy/zone-refining.svg)

**Principle:** an impurity may be more soluble in the **liquid** phase than in the solid phase.

A narrow molten zone is moved slowly along a solid ingot:
1. impurities enter the molten zone preferentially,
2. as the zone moves, purified solid crystallises behind it,
3. impurities travel toward one end,
4. repeated passes increase purity.

Used for ultra-pure semiconductor/material-grade elements such as Si, Ge and Ga; zone refining is also applicable to several other metals/metalloids when the distribution coefficient is favourable.

> **Source sketch question corrected:** a cylindrical rod is convenient, not a fundamental chemical requirement. What matters is the ability to maintain and translate a controlled molten zone through the material.

---

## 5. Vapour-Phase Refining

A successful vapour-phase refining route requires an intermediate that is:
1. sufficiently **volatile**, and
2. readily **decomposed at an achievable temperature** to regenerate pure metal.

### Mond process — Ni
At moderate temperature:
$$Ni+4CO\rightleftharpoons Ni(CO)_4(g)$$

Nickel tetracarbonyl is volatile. On heating:
$$Ni(CO)_4\rightarrow Ni+4CO$$

Impurities that do not form the same volatile carbonyl are left behind.

### van Arkel–de Boer / iodide process
Used for very pure reactive metals such as Ti, Zr and Hf.

Formation of volatile iodide:
$$M+2I_2\rightarrow MI_4(g)$$

Decomposition on a hot filament:
$$MI_4\rightarrow M+2I_2$$

Iodine is recycled.

---

## 6. Cupellation

Cupellation is a classical method for separating noble metals from easily oxidised base metals, especially **removing Pb from Ag/Au-rich material**.

Lead is oxidised:
$$2Pb+O_2\rightarrow2PbO$$

$PbO$ (litharge) is removed by volatilisation/absorption into the porous cupel, while noble metals resist oxidation.

---

## 7. Amalgamation

Hg forms amalgams with several metals, including Ag and Au.

General idea:
$$\text{impure Ag/Au}+Hg\rightarrow \text{amalgam}$$

Heating drives off Hg because of its much greater volatility, leaving Ag/Au behind.

> **Historical/environmental note:** mercury-based extraction has major toxicological and environmental hazards. It is retained here only because it appears in the source and is historically/exam relevant.

---

## 8. Electrorefining — General Principle

![Electrorefining cell](/notes/metallurgy/electrorefining.svg)

- **Anode:** impure metal.
- **Cathode:** thin sheet/starting surface of pure metal.
- **Electrolyte:** suitable soluble salt of the metal.

Anode:
$$M\rightarrow M^{n+}+ne^-$$

Cathode:
$$M^{n+}+ne^-\rightarrow M$$

Impurities fall into three broad classes:
1. more active species that enter solution but do not plate under chosen conditions,
2. noble/insoluble species that collect as **anode mud**,
3. troublesome species controlled by electrolyte chemistry and cell potential.

Anode mud can contain valuable Ag, Au and Pt-group metals, so it is processed rather than discarded.

---

# 9. Ellingham Diagram — Thermodynamic Backbone of Metallurgy

![Ellingham diagram principle](/notes/metallurgy/ellingham.svg)

An Ellingham diagram plots approximately:

$$\Delta G^\circ \text{ for oxide formation versus } T$$

For a general oxidation:
$$M+\frac12O_2\rightarrow MO$$

Using:
$$\Delta G^\circ=\Delta H^\circ-T\Delta S^\circ$$

the slope of a line is approximately $-\Delta S^\circ$.

### Why most metal-oxide lines slope upward
Gas-phase $O_2$ is consumed to form condensed oxide, so entropy usually decreases:
$$\Delta S^\circ<0\Rightarrow -\Delta S^\circ>0$$
Hence a positive slope is common.

### Carbon lines
For:
$$C+O_2\rightarrow CO_2$$

the gas mole count changes little, so $\Delta S^\circ$ is relatively small and the line is nearly flat.

For:
$$2C+O_2\rightarrow2CO$$

gas moles increase, so $\Delta S^\circ$ is positive and the line has a **negative slope**.

### Zero-line crossing
Where an oxide-formation line crosses $\Delta G^\circ=0$, oxide formation ceases to be thermodynamically favourable under standard-state assumptions above that temperature; the reverse decomposition becomes favourable in the idealised sense.

The source uses Ag₂O and HgO to illustrate comparatively low thermal stability. Exact decomposition behaviour depends on oxygen pressure and kinetics, so handwritten temperatures should not be treated as universal constants.

### Kinks / slope changes
A sudden slope change commonly reflects a **phase transition** (melting, boiling or allotropy) of a reactant/product, because entropy changes discontinuously.

### Reduction criterion
At a given temperature, a reducing agent can reduce a metal oxide when oxidation of the reducing agent gives a sufficiently more negative $\Delta G^\circ$.

Graphically: the oxidation line of the reducing agent lies **below** the oxide-formation line of the metal being reduced at that temperature.

For aluminothermy:
$$Fe_2O_3+2Al\rightarrow Al_2O_3+2Fe$$

$$\Delta G^\circ_{rxn}=\Delta G^\circ_f(Al_2O_3)-\Delta G^\circ_f(Fe_2O_3)$$

A negative value means thermodynamic feasibility.

> **Critical JEE distinction:** Ellingham predicts **thermodynamic feasibility**, not reaction rate, mechanism, phase separation, reagent cost or industrial profitability.

### Why carbon becomes powerful at high temperature
The downward-sloping CO-formation line crosses many metal-oxide lines as temperature rises. This is why carbon/CO can reduce many oxides at sufficiently high temperature.

The source highlights the approximate $\sim700^\circ C$ region where the relative preference for CO vs $CO_2$ formation changes. Use the diagram qualitatively rather than memorising one universal crossing temperature.

### Hydrogen
Hydrogen can reduce oxides whose formation lines lie above the $H_2/H_2O$ line under the chosen conditions, e.g. oxides such as CuO and PbO are readily reduced. Feasibility varies with temperature and steam/hydrogen partial pressures.

---

# 10. Extraction of Silver — Cyanide (MacArthur–Forrest) Process

The source uses argentite $Ag_2S$.

## Step 1 — leaching
Finely divided ore is treated with dilute cyanide solution in the presence of oxygen. Silver enters solution as the stable dicyanoargentate(I) complex:

$$Ag^+ +2CN^-\rightarrow[Ag(CN)_2]^-$$

For sulphide ore, the overall chemistry involves cyanide complexation plus oxidation/removal of sulphide species; it is safer pedagogically to write the complexation step rather than reproduce the source’s unbalanced side equation.

Insoluble gangue is filtered off.

## Step 2 — displacement with Zn
$$2[Ag(CN)_2]^-+Zn\rightarrow2Ag+[Zn(CN)_4]^{2-}$$

Crude Ag is filtered.

## Further purification
- Zn contamination can be dissolved using suitable dilute acid treatment.
- Ag is then purified by **electrorefining** using an Ag salt electrolyte; pure Ag deposits at the cathode.

---

## 11. Parkes Process — Desilverisation of Lead

Silver-bearing lead is treated with molten Zn.

**Principle:** Ag has much greater affinity/solubility for the Zn-rich phase than for molten Pb.

1. Add Zn to molten argentiferous lead.
2. Ag partitions preferentially into Zn.
3. On cooling, a Zn–Ag-rich crust separates and is removed.
4. Zn is removed/recovered by volatilisation/distillation, leaving Ag-rich residue.
5. Ag is further purified.

The distribution idea can be expressed qualitatively as:
$$K\sim \frac{[Ag]_{Zn\ phase}}{[Ag]_{Pb\ phase}}\gg1$$

---

# 12. Extraction of Gold — Cyanide Route

Low-grade auriferous quartz is crushed and leached with dilute cyanide under aerated conditions. Gold forms dicyanoaurate(I):

$$Au+2CN^-\rightarrow[Au(CN)_2]^-$$

A commonly used overall Elsner-type equation is:
$$4Au+8CN^-+O_2+2H_2O\rightarrow4[Au(CN)_2]^-+4OH^-$$

Zn can precipitate gold:
$$2[Au(CN)_2]^-+Zn\rightarrow2Au+[Zn(CN)_4]^{2-}$$

### Purification sequence represented in the source
The handwritten pages combine several classical operations:
- remove Zn with acid,
- remove Pb by cupellation,
- use borax/borate flux to oxidise and dissolve base-metal impurities such as Cu into slag,
- **parting** to separate Ag from Au using selective acid chemistry,
- final electrorefining to very high purity.

For Cu impurity, a simplified flux logic is:
$$2Cu+O_2\rightarrow2CuO$$
$$CuO+B_2O_3\rightarrow Cu(BO_2)_2$$

The borate enters the slag phase.

> **Source-preservation note:** exact historical reagent sequences vary by process and era. The website keeps the conceptual purification steps without presenting unsafe operating instructions.
`;
export default content;
