
import { AtomicPartShell, AuditComment, FormulaLine, MathText, SourcePage } from "./_shared";
import { ConceptCard, DerivationPanel, FormulaCard, ImportantNote, LearningObjectives, SummaryStrip } from "../_components/AtomicLearning";

export default function Part36() {
  return <AtomicPartShell part={36} title="Schrödinger Wave Equation — Time Dependence and Hamiltonian" pages="113-115">
    <LearningObjectives items={["derive the one-dimensional time-dependent equation", "identify momentum, kinetic-energy and Hamiltonian operators", "read the stationary-state equation in one and three dimensions", "connect ψ, energy and the Laplacian"]} />
    <SourcePage page={113}><DerivationPanel title="From a plane matter wave to time evolution"><p>At constant x,</p><FormulaLine math="\frac{\partial\psi}{\partial t}=A\,e^{\frac{i}{\hbar}(px-Et)}\left(-E\,\frac{i}{\hbar}\right)=-\frac{i}{\hbar}\,E\,\psi" /><p>Side working:</p><FormulaLine math="E\psi=-\frac{\hbar}{i}\,\frac{\partial\psi}{\partial t}=i\hbar\,\frac{\partial\psi}{\partial t}\qquad(i^{2}=-1,\ -\tfrac{1}{i}=i)" /><FormulaLine math="\text{for free particle }E\psi=\frac{p^{2}}{2m}\,\psi" /><FormulaLine math="\boxed{-i\hbar\,\frac{\partial\psi}{\partial t}=\frac{\hbar^{2}}{2m}\,\frac{\partial^{2}\psi}{\partial x^{2}}}" /><p>We obtain a differential equation free from p and E.</p><FormulaLine math="E=KE+PE=\frac{p^{2}}{2m}+V(x)\qquad\text{one dimension}" /><FormulaLine math="E\psi=\frac{p^{2}}{2m}\,\psi+V(x)\,\psi" /><FormulaLine math="\boxed{-\frac{\hbar^{2}}{2m}\,\frac{\partial^{2}\psi}{\partial x^{2}}+V(x)\,\psi=i\hbar\,\frac{\partial\psi}{\partial t}}\quad\text{Schrödinger wave equation}" /><p>On solving it, we obtain how the wave function of a particle varies with time.</p></DerivationPanel>
      <FormulaCard label="Momentum and kinetic-energy operators"><FormulaLine math="p\,\psi=-i\hbar\,\frac{\partial\psi}{\partial x}\qquad p=-i\hbar\,\frac{\partial}{\partial x}" /><p className="mt-3 text-sm text-slate-200">The ψ is formally omitted to name the operator (but it cannot be removed in actual operation). P is the linear-momentum operator.</p><p className="mt-3 text-sm text-slate-200">Similarly,</p><FormulaLine math="p^{2}\psi=-\hbar^{2}\,\frac{\partial^{2}\psi}{\partial x^{2}}" /><p className="mt-3 text-sm text-slate-200">Divide by 2m:</p><FormulaLine math="\frac{p^{2}\psi}{2m}=-\frac{\hbar^{2}}{2m}\,\frac{\partial^{2}\psi}{\partial x^{2}}" /><FormulaLine math="KE=\frac{p^{2}}{2m}=-\frac{\hbar^{2}}{2m}\,\frac{\partial^{2}}{\partial x^{2}}" /><FormulaLine math="\frac{p^{2}}{2m}\,\psi+V(x)\,\psi=i\hbar\,\frac{\partial\psi}{\partial t}" /><FormulaLine math="\underbrace{\left(-\frac{\hbar^{2}}{2m}\,\frac{\partial^{2}}{\partial x^{2}}\right)}_{\text{K.E. operator}}\psi+\underbrace{V(x)}_{\text{P.E. operator}}\psi=i\hbar\,\frac{\partial\psi}{\partial t}" /></FormulaCard>
      <FormulaCard label="Time-independent form"><FormulaLine math="\boxed{\frac{\partial^{2}\psi}{\partial x^{2}}+\frac{8\pi^{2}m}{h^{2}}\,(E-V)\,\psi=0}\quad\text{for one dimension}" /><FormulaLine math="\boxed{\frac{\partial^{2}\psi}{\partial x^{2}}+\frac{\partial^{2}\psi}{\partial y^{2}}+\frac{\partial^{2}\psi}{\partial z^{2}}+\frac{8\pi^{2}m}{h^{2}}\,(E-V)\,\psi=0}\quad\text{for 3D}" /></FormulaCard></SourcePage>
    <SourcePage page={114}><ConceptCard title="Laplacian form and the Hamiltonian operator"><FormulaLine math="\left(\frac{\partial^{2}}{\partial x^{2}}+\frac{\partial^{2}}{\partial y^{2}}+\frac{\partial^{2}}{\partial z^{2}}\right)\psi+\frac{8\pi^{2}m}{h^{2}}\,(E-V)\,\psi=0" /><FormulaLine math="\boxed{\nabla^{2}\psi+\frac{8\pi^{2}m}{h^{2}}\,(E-V)\,\psi=0}" /><FormulaLine math="-\frac{h^{2}}{8\pi^{2}m}\,\nabla^{2}\psi=(E-V)\,\psi" /><FormulaLine math="\left(-\frac{h^{2}}{8\pi^{2}m}\,\nabla^{2}+V\right)\psi=E\,\psi" /><FormulaLine math="\boxed{\hat{H}\psi=E\,\psi}\qquad \hat{H}=\left(-\frac{h^{2}}{8\pi^{2}m}\,\nabla^{2}+V\right)" /><p><MathText math="\hat{H}" /> is the Hamiltonian operator; it gives information about the total energy of the electron.</p></ConceptCard></SourcePage>
    <SourcePage page={115}><ConceptCard title="Wave mechanical model of the atom"><p>Schrödinger gave a general equation for moving objects showing wave–particle duality. For a state whose energy does not change with time, it is written as follows.</p></ConceptCard><ConceptCard title="Schrödinger wave equation"><p>Wave function = <MathText math="\psi" /> (Psi)</p><p>For one dimension</p><FormulaLine math="\frac{\partial^{2}\psi}{\partial x^{2}}+\frac{8\pi^{2}m}{h^{2}}\,(E-V)\,\psi=0" /><p>For three dimensions</p><FormulaLine math="\frac{\partial^{2}\psi}{\partial x^{2}}+\frac{\partial^{2}\psi}{\partial y^{2}}+\frac{\partial^{2}\psi}{\partial z^{2}}+\frac{8\pi^{2}m}{h^{2}}\,(E-V)\,\psi=0" /><FormulaLine math="\nabla^{2}\psi+\frac{8\pi^{2}m}{h^{2}}\,(E-V)\,\psi=0" /><FormulaLine math="\nabla^{2}=\frac{\partial^{2}}{\partial x^{2}}+\frac{\partial^{2}}{\partial y^{2}}+\frac{\partial^{2}}{\partial z^{2}}=\text{Laplacian operator}" /><ul className="list-disc space-y-2 pl-5"><li><MathText math="\psi" /> = wave function of matter waves</li><li>m = mass of <MathText math="e^{-}" /></li><li>E = total energy</li><li>V = potential energy</li></ul><FormulaLine math="-\frac{h^{2}}{8\pi^{2}m}\,\nabla^{2}\psi=(E-V)\,\psi" /><FormulaLine math="-\frac{h^{2}}{8\pi^{2}m}\,\nabla^{2}\psi+V\psi=E\,\psi" /><FormulaLine math="\left(-\frac{h^{2}}{8\pi^{2}m}\,\nabla^{2}+V\right)\psi=E\,\psi" /></ConceptCard><ImportantNote title="Stationary-state scope">The time-independent form applies when the potential is time-independent and the state has a definite energy.</ImportantNote></SourcePage>
    <SummaryStrip items={["Time dependence is carried by iħ ∂ψ/∂t.", "p̂ = −iħ ∂/∂x and T̂ = −ħ²∂²/(2m∂x²).", "For stationary states, Ĥψ = Eψ."]} /><AuditComment pages="113-115" unclear={0} />
  </AtomicPartShell>;
}