"use client";
import { AtomicPartShell, AuditComment, DiagramBox, FormulaLine, ImportantNote, LearningObjectives, NoteBlock, SourcePage, SummaryStrip } from "./_shared";
import { DOrbitalGalleryVisual, OrbitalNodeSeriesVisual, PenetrationComparisonVisual } from "../_components/AtomicVisuals";
export default function Part49() { return <AtomicPartShell part={49} title="Orbital Reach, Bonding and Higher-Series Galleries" pages="154-156">
  <LearningObjectives items={["Compare radial reach of 3d, 4d and 5d orbitals.", "Contrast buried 4f with more bonding-accessible 5f density.", "Track radial-node growth across np and nd galleries."]} />
  <SourcePage page={154}><NoteBlock title="3d orbitals vs 4d, 5d orbitals"><PenetrationComparisonVisual /><p>From radial probability distribution curve, it is evident that for the 3d-orbital, the maximum (i.e. r_max) lies within the maxima of 3s, 3p, 4s and 4p orbitals. Thus, the 3d-orbitals are deeply seated and they cannot generally participate in making covalent bonds.</p><p>In contrast, for the 4d and 5d series, the r_max of the d-orbitals lies relatively closer to the r_max of the relevant valence s- and p-orbitals. Because of relativistic expansion (caused by the contracted inner s- and p-orbitals) r_max of the (n−1)d orbitals of the heavy congeners increases. In fact, r_max of the 5d and 6s orbitals become comparable. Thus bonding ability of the 5d orbitals is increased. In other words, relativistic expansion increases attainment of higher oxidation state.</p><FormulaLine math="\text{The relativistic expansion effect runs as: }5d>4d>3d" /><p>The d-orbital of the heavier congeners can participate better in bonding activities. In fact, this makes the higher oxidation state more common in the heavier congeners of the d-block elements.</p><ImportantNote title="Trend context"><p>This is a qualitative radial-overlap argument; the availability of a particular oxidation state also depends on the element, ligands and energetics.</p></ImportantNote></NoteBlock><NoteBlock title="4f orbital vs 5f orbitals"><p>The 4f orbitals of the lanthanides are more deeply buried than the 5f orbitals of actinides.</p><p>Thus the 5f-orbitals can participate better in bonding activities and this also favours the attainment of their higher oxidation states.</p><DiagramBox title="RDF vs r for 4f/6s and 5f/7s"><PenetrationComparisonVisual /><p>(a) RDF vs distance: several small inner 4f humps (dotted) are buried under a large outer 6s peak. (b) RDF vs distance: larger 5f humps reach out toward the 7s peak—the 5f density extends farther than the 4f density.</p></DiagramBox></NoteBlock></SourcePage>
  <SourcePage page={155}><NoteBlock title="Shape of Orbitals — np series"><DiagramBox title="2p / 3p / 4p / 5p / 6p / 7p"><OrbitalNodeSeriesVisual /><p>Six 3-D renderings of the np orbitals (2p through 7p), each shown as three mutually perpendicular dumbbells (one per axis) with opposite-sign lobes. As n increases, extra inner nodal shells appear nested inside the outer dumbbell lobes while the overall dumbbell orientation is preserved.</p></DiagramBox></NoteBlock></SourcePage>
  <SourcePage page={156}><NoteBlock title="Shape of Orbitals — nd series"><DiagramBox title="3d / 4d / 5d / 6d"><DOrbitalGalleryVisual n={3} /><DOrbitalGalleryVisual n={6} /><p>Four 3-D galleries of the five d orbitals (3d, 4d, 5d, 6d). Each set shows d z² (two lobes plus an equatorial ring) and the four cloverleaf orbitals d(xy), d(yz), d(zx), d(x²−y²) with opposite-sign lobes. As n increases, additional nested radial shells appear inside each lobe.</p></DiagramBox></NoteBlock></SourcePage>
  <SummaryStrip items={["Deeply seated 3d density is less available for covalent overlap.", "5f is generally less buried than 4f.", "Increasing n adds radial structure while retaining angular shape."]} /><AuditComment pages="154-156" unclear={0} />
</AtomicPartShell>; }
