"use client";
import { AtomicPartShell, AuditComment, DiagramBox, ImportantNote, LearningObjectives, MathText, NoteBlock, SourcePage, SummaryStrip } from "./_shared";
import { DOrbitalGalleryVisual, FOrbitalGalleryVisual } from "../_components/AtomicVisuals";
const general = (n: number) => <><MathText math={`${n}f_{z^{3}}`} />; <MathText math={`${n}f_{yz^{2}}`} />, <MathText math={`${n}f_{xz^{2}}`} />; <MathText math={`${n}f_{xyz}`} />, <MathText math={`${n}f_{z(x^{2}-y^{2})}`} />; <MathText math={`${n}f_{y(3x^{2}-y^{2})}`} />, <MathText math={`${n}f_{x(x^{2}-3y^{2})}`} />.</>;
const cubic = (n: number) => <>(top row) <MathText math={`${n}f_{y^{3}}`} />, <MathText math={`${n}f_{z^{3}}`} />, <MathText math={`${n}f_{x^{3}}`} />; (middle row) <MathText math={`${n}f_{y(z^{2}-x^{2})}`} />, <MathText math={`${n}f_{z(x^{2}-y^{2})}`} />, <MathText math={`${n}f_{x(z^{2}-y^{2})}`} />; (bottom row) <MathText math={`${n}f_{xyz}`} />.</>;
export default function Part50() { return <AtomicPartShell part={50} title="7d and the 4f–6f Orbital Sets" pages="157-160">
  <LearningObjectives items={["Relate the 7d radial-node count to n − l − 1.", "Distinguish the general and cubic ways of labelling f orbital sets.", "Track spherical radial nodes through 4f, 5f and 6f."]} />
  <SourcePage page={157}><NoteBlock title="Shape of Orbitals — 7d"><DiagramBox title="7d orbital set"><DOrbitalGalleryVisual n={7} /><p>A 3-D gallery of the five 7d orbitals: d z² (two lobes plus an equatorial ring) at top, and the four cloverleaf orbitals d(xy), d(yz), d(zx), d(x²−y²) below, each with opposite-sign lobes and several nested inner radial shells. The 7d orbitals have four radial nodes.</p></DiagramBox></NoteBlock></SourcePage>
  <SourcePage page={158}><NoteBlock title="4f atomic orbitals — general and cubic sets"><p>For any atom, there are seven 4f orbitals. The f-orbitals are unusual in that there are two sets of orbitals in common use. The first set is known as the general set. The second set is the cubic set and these might be appropriate to use if the atom is in a cubic environment, for instance. Three orbitals are common to both sets: <MathText math="4f_{xyz}" />, <MathText math="4f_{z^{3}}" />, and <MathText math="4f_{z(x^{2}-y^{2})}" />. The higher f-orbitals (5f, 6f, and 7f) are more complex since they have one or more spherical nodes.</p><DiagramBox title="4f general set">
    <FOrbitalGalleryVisual n={4} set="general" /><p>Seven f-orbitals, green (+) / white (−) lobes. From left to right: (top row) <MathText math="4f_{z^{3}}" />; (next to top row) <MathText math="4f_{yz^{2}}" />, <MathText math="4f_{xz^{2}}" />; (next to bottom row) <MathText math="4f_{xyz}" />, <MathText math="4f_{z(x^{2}-y^{2})}" />; (bottom row) <MathText math="4f_{y(3x^{2}-y^{2})}" />, <MathText math="4f_{x(x^{2}-3y^{2})}" />.</p></DiagramBox><DiagramBox title="4f cubic set">
      <FOrbitalGalleryVisual n={4} set="cubic" /><p>From left to right: {cubic(4)}</p></DiagramBox></NoteBlock></SourcePage>
  <SourcePage page={159}><NoteBlock title="5f atomic orbitals — general and cubic sets"><DiagramBox title="5f general set">
    <FOrbitalGalleryVisual n={5} set="general" /><p>The seven 5f orbitals (general set), green (+) / white (−): same labelling as the 4f general set: {general(5)} Each has an extra inner (radial) shell compared with the 4f set.</p></DiagramBox><DiagramBox title="5f cubic set">
      <FOrbitalGalleryVisual n={5} set="cubic" /><p>From left to right: {cubic(5)}</p></DiagramBox></NoteBlock></SourcePage>
  <SourcePage page={160}><NoteBlock title="6f atomic orbitals — general and cubic sets"><DiagramBox title="6f general set">
    <FOrbitalGalleryVisual n={6} set="general" /><p>The seven 6f orbitals (general set), green (+) / white (−): {general(6)} Additional nested radial shells appear (two spherical nodes).</p></DiagramBox><DiagramBox title="6f cubic set">
      <FOrbitalGalleryVisual n={6} set="cubic" /><p>From left to right: {cubic(6)}</p></DiagramBox><ImportantNote title="Naming convention"><p>The two sets are alternative real-orbital bases for the same seven-dimensional f subshell; their usefulness depends on the symmetry context.</p></ImportantNote></NoteBlock></SourcePage>
  <SummaryStrip items={["7d has 7 − 2 − 1 = 4 radial nodes.", "An f subshell contains seven orbitals.", "5f and 6f add one and two spherical radial nodes relative to 4f."]} /><AuditComment pages="157-160" unclear={0} />
</AtomicPartShell>; }
