"use client";
import { AtomicPartShell, AuditComment, DataTable, DiagramBox, FormulaLine, ImportantNote, LearningObjectives, NoteBlock, SourcePage, SummaryStrip } from "./_shared";
import { DOrbitalGalleryVisual, DOrbitalNodalMapVisual, Dz2OrbitalVisual, OrbitalNodeSeriesVisual } from "../_components/AtomicVisuals";

export default function Part47() { return <AtomicPartShell part={47} title="p Density, d-Orbital Geometry and Parity" pages="148-150">
  <LearningObjectives items={["Read radial-node growth from np density patterns.", "Identify all five real d orbitals from their nodes and orientation.", "Connect l with inversion parity and m assignments."]} />
  <SourcePage page={148}><NoteBlock title="Electron-density pictures of 2p, 3p, 4p, 5p"><DiagramBox title="2p / 3p / 4p / 5p density clouds"><OrbitalNodeSeriesVisual /><p>Four dot-density plots: 2p is a clean two-lobe dumbbell with a single nodal gap across the middle. 3p has the dumbbell plus one bright inner core (one radial node). 4p has two inner bright regions. 5p has additional concentric bright shells—the inner structure grows with n while the outer dumbbell shape persists.</p></DiagramBox></NoteBlock></SourcePage>
  <SourcePage page={149}><NoteBlock title="d-orbital shapes"><DiagramBox title="dxy / dyz / dzx"><DOrbitalNodalMapVisual /><p>Three four-lobe cloverleaves lie between axes: dxy in x–y (nodal planes zx, yz), dyz in y–z (xy, zx), dzx in z–x (xy, yz). Each has four lobes and two nodal planes.</p></DiagramBox><FormulaLine math="d_{xy}:\ \text{nodal plane}=2\ (zx,\ yz)" /><FormulaLine math="d_{yz}:\ \text{nodal plane}=2\ (xy,\ zx)" /><FormulaLine math="d_{zx}:\ \text{nodal plane}=2\ (xy,\ yz)" /><DiagramBox title="d(x²−y²)"><DOrbitalNodalMapVisual /><p>Four-lobe cloverleaf along the x and y axes; nodal planes at x = y and x = −y (45°, 135°).</p></DiagramBox><FormulaLine math="d_{x^{2}-y^{2}}:\ x^{2}-y^{2}=0\ \Rightarrow\ x=y,\ x=-y\ (45^{\circ},135^{\circ})\ \text{four lobe}" /><DiagramBox title="d z²"><Dz2OrbitalVisual /><p>Two lobes along z with an equatorial ring; nodal surfaces are two cones at θ = 54.7° and 125.3°.</p></DiagramBox><FormulaLine math="d_{z^{2}}:\ \theta=54.7^{\circ},125.3^{\circ}\ \text{— Nodal surfaces are conical}" /><p>d-subshell — two axial, three non-axial orbitals.</p><DiagramBox title="4d / 5d radial growth"><DOrbitalGalleryVisual n={4} /><DOrbitalGalleryVisual n={5} /><p>Nested cloverleaves: 4d adds one inner shell, 5d adds two inner shells (increasing radial nodes).</p></DiagramBox></NoteBlock></SourcePage>
  <SourcePage page={150}><NoteBlock title="Gerade and ungerade"><p>Orbitals with even l values are symmetrical on inversion and are known as <strong>gerade</strong>; orbitals with odd l values are antisymmetrical on inversion and are known as <strong>ungerade</strong>.</p><ImportantNote title="Scope of the label"><p>This is the parity of an orbital angular function under inversion, not a statement that its electron density is asymmetric.</p></ImportantNote></NoteBlock><NoteBlock title="m (magnetic quantum number) assignments"><FormulaLine math="s:\ m=0" /><FormulaLine math="p:\ m=-1,0,+1\qquad p_x,p_y=\pm1;\ p_z=0" /><FormulaLine math="d:\ m=-2,-1,0,+1,+2" /><DataTable headers={["d orbital", "m"]} rows={[["d(xy), d(x²−y²)", "±2"], ["d(yz), d(zx)", "±1"], ["d(z²)", "0"]]} /></NoteBlock></SourcePage>
  <SummaryStrip items={["np orbitals preserve their dumbbell angular form as radial nodes increase.", "Every d orbital has two angular nodes.", "Even l is gerade; odd l is ungerade."]} /><AuditComment pages="148-150" unclear={0} />
</AtomicPartShell>; }
