"use client";

import { HighAngularOrbitalVisual } from "../_components/AtomicVisuals";
import { AtomicPartShell, AuditComment, DiagramBox, ImportantNote, LearningObjectives, MathText, NoteBlock, SourcePage, SummaryStrip } from "./_shared";

const g = ["z^{4}", "z^{3}x", "z^{3}y", "z^{2}xy", "z^{2}(x^{2}-y^{2})", "zx^{3}", "zy^{3}", "xy(x^{2}-y^{2})", "x^{4}+y^{4}"];
const h = ["z^{5}", "yz^{4}", "xz^{4}", "z^{3}xy", "z^{3}(x^{2}-y^{2})", "z^{2}y^{3}", "z^{2}x^{3}", "z(4x^{3}y-4xy^{3})", "z(x^{4}-6x^{2}y^{2}+y^{4})", "yx^{4}", "xy^{4}"];

export default function Part52() {
  return <AtomicPartShell part={52} title="The Nine 7g Orbitals and the Eleven 6h and 7h Orbitals" pages="164-166">
    <LearningObjectives items={[<>Use <MathText math="2l+1" /> to count g and h orbitals.</>, <>Track the extra radial node from <MathText math="6h" /> to <MathText math="7h" />.</>, <>Read phase-coloured real angular-function labels.</>]} />
    <SourcePage page={164}><NoteBlock title="7g atomic orbitals"><DiagramBox title="Nine 7g orbitals"><HighAngularOrbitalVisual n={7} l={4} family="g" labels={g.map((x) => `7g_{${x}}`)} radialNodes={2} /><p>The nine <MathText math="7g" /> orbitals, purple (+) / white (−). From left to right: (top row) <MathText math="7g_{z^{4}}" />; (next to top row) <MathText math="7g_{z^{3}x}" /> and <MathText math="7g_{z^{3}y}" />; (middle row) <MathText math="7g_{z^{2}xy}" /> and <MathText math="7g_{z^{2}(x^{2}-y^{2})}" />; (next to bottom row) <MathText math="7g_{zx^{3}}" /> and <MathText math="7g_{zy^{3}}" />; (bottom row) <MathText math="7g_{xy(x^{2}-y^{2})}" /> and <MathText math="7g_{x^{4}+y^{4}}" />. Each orbital sits inside a faint spherical node shell.</p></DiagramBox></NoteBlock></SourcePage>
    <SourcePage page={165}><NoteBlock title="6h atomic orbitals"><p>There are eleven <MathText math="6h" /> orbitals. These are labelled {h.map((x, i) => <span key={x}><MathText math={`6h_{${x}}`} />{i === h.length - 1 ? "." : ", "}</span>)}</p><DiagramBox title="Eleven 6h orbitals"><HighAngularOrbitalVisual n={6} l={5} family="h" labels={h.map((x) => `6h_{${x}}`)} radialNodes={0} /><p>Eleven 3-D orbital shapes, turquoise/cyan (+) and white (−). Progressing from the axial <MathText math="6h_{z^{5}}" /> (stacked rings and lobes along z) through increasingly multi-lobed cloverleaf and rosette shapes down to the equatorial <MathText math="6h_{xy^{4}}" /> — the number of angular lobes increases across the set.</p></DiagramBox></NoteBlock></SourcePage>
    <SourcePage page={166}><NoteBlock title="7h atomic orbitals"><p>There are eleven <MathText math="7h" /> orbitals. These are labelled {h.map((x, i) => <span key={x}><MathText math={`7h_{${x}}`} />{i === h.length - 1 ? "." : ", "}</span>)}</p><DiagramBox title="Eleven 7h orbitals"><HighAngularOrbitalVisual n={7} l={5} family="h" labels={h.map((x) => `7h_{${x}}`)} radialNodes={1} /><p>Eleven 3-D orbital shapes, turquoise/cyan (+) and white (−), each enclosed in a faint spherical (radial) node shell. Same labelling family as <MathText math="6h" /> but with an added radial node, so extra concentric shells appear inside every lobe.</p></DiagramBox></NoteBlock></SourcePage>
    <ImportantNote title="Counting rule">For a subshell with azimuthal quantum number <MathText math="l" />, there are <MathText math="2l+1" /> orbitals: g has <MathText math="l=4" /> and h has <MathText math="l=5" />.</ImportantNote><SummaryStrip items={[<>g: <MathText math="l=4\Rightarrow9" /> orbitals.</>, <>h: <MathText math="l=5\Rightarrow11" /> orbitals.</>, <><MathText math="7h" /> has one more radial node than <MathText math="6h" />.</>]} />
    <AuditComment pages="164-166" unclear={0} />
  </AtomicPartShell>;
}
