"use client";

import { HighAngularOrbitalVisual } from "../_components/AtomicVisuals";
import { AtomicPartShell, AuditComment, DiagramBox, ImportantNote, LearningObjectives, MathText, NoteBlock, SourcePage, SummaryStrip } from "./_shared";

const fGeneral = ["7f_{z^{3}}", "7f_{yz^{2}}", "7f_{xz^{2}}", "7f_{xyz}", "7f_{z(x^{2}-y^{2})}", "7f_{y(3x^{2}-y^{2})}", "7f_{x(x^{2}-3y^{2})}"];
const gLabels = ["z^{4}", "z^{3}x", "z^{3}y", "z^{2}xy", "z^{2}(x^{2}-y^{2})", "zx^{3}", "zy^{3}", "xy(x^{2}-y^{2})", "x^{4}+y^{4}"];

export default function Part51() {
  return <AtomicPartShell part={51} title="7f Orbitals and the Nine 5g and 6g Orbitals" pages="161-163">
    <LearningObjectives items={[<>Recognise the seven real <MathText math="7f" /> angular forms.</>, <>Relate g orbitals to <MathText math="2l+1=9" />.</>, <>Distinguish angular forms from radial-node shells.</>]} />
    <SourcePage page={161}><NoteBlock title="7f atomic orbitals — general and cubic sets"><p>The seven <MathText math="7f" /> orbitals (general set), green (+) / white (−): <MathText math="7f_{z^{3}}" />; <MathText math="7f_{yz^{2}}" />, <MathText math="7f_{xz^{2}}" />; <MathText math="7f_{xyz}" />, <MathText math="7f_{z(x^{2}-y^{2})}" />; <MathText math="7f_{y(3x^{2}-y^{2})}" />, <MathText math="7f_{x(x^{2}-3y^{2})}" />. Each carries additional nested radial shells (more spherical nodes) than the <MathText math="6f" /> set.</p><DiagramBox title="7f general set"><HighAngularOrbitalVisual n={7} l={3} family="f" labels={fGeneral} radialNodes={3} /><p>Green (+) and white (−) identify opposite wave-function phases; the dashed circles are a schematic of the extra spherical nodes, not electron trajectories.</p></DiagramBox><DiagramBox title="7f cubic set"><p>From left to right: (top row) <MathText math="7f_{y^{3}}" />, <MathText math="7f_{z^{3}}" />, <MathText math="7f_{x^{3}}" />; (middle row) <MathText math="7f_{y(z^{2}-x^{2})}" />, <MathText math="7f_{z(x^{2}-y^{2})}" />, <MathText math="7f_{x(z^{2}-y^{2})}" />; (bottom row) <MathText math="7f_{xyz}" />.</p></DiagramBox></NoteBlock></SourcePage>
    <SourcePage page={162}><NoteBlock title="5g atomic orbitals"><p>For any atom, there are nine <MathText math="5g" /> orbitals. The higher g-orbitals (<MathText math="6g" /> and <MathText math="7g" />) are more complex since they have spherical nodes.</p><DiagramBox title="Nine 5g orbitals"><HighAngularOrbitalVisual n={5} l={4} family="g" labels={gLabels.map((label) => `5g_{${label}}`)} radialNodes={0} /><p>The nine <MathText math="5g" /> orbitals, purple (+) / white (−). From left to right: (top row) <MathText math="5g_{z^{4}}" />; (next to top row) <MathText math="5g_{z^{3}y}" /> and <MathText math="5g_{z^{3}x}" />; (centre row) <MathText math="5g_{z^{2}xy}" /> and <MathText math="5g_{z^{2}(x^{2}-y^{2})}" />; (next to bottom row) <MathText math="5g_{zy^{3}}" /> and <MathText math="5g_{zx^{3}}" />; (bottom row) <MathText math="5g_{xy(x^{2}-y^{2})}" /> and <MathText math="5g_{x^{4}+y^{4}}" />.</p></DiagramBox></NoteBlock></SourcePage>
    <SourcePage page={163}><NoteBlock title="6g atomic orbitals"><DiagramBox title="Nine 6g orbitals"><HighAngularOrbitalVisual n={6} l={4} family="g" labels={gLabels.map((label) => `6g_{${label}}`)} radialNodes={1} /><p>The nine <MathText math="6g" /> orbitals, purple (+) / white (−). From left to right: (top row) <MathText math="6g_{z^{4}}" />; (next to top row) <MathText math="6g_{z^{3}x}" /> and <MathText math="6g_{z^{3}y}" />; (middle row) <MathText math="6g_{z^{2}xy}" /> and <MathText math="6g_{z^{2}(x^{2}-y^{2})}" />; (next to bottom row) <MathText math="6g_{zx^{3}}" /> and <MathText math="6g_{zy^{3}}" />; (bottom row) <MathText math="6g_{xy(x^{2}-y^{2})}" /> and <MathText math="6g_{x^{4}+y^{4}}" />. Additional inner shells appear relative to the <MathText math="5g" /> set.</p></DiagramBox></NoteBlock></SourcePage>
    <ImportantNote title="How to read an orbital gallery">The listed polynomials distinguish real angular functions. A picture’s +/− colour represents phase; it is not positive or negative charge.</ImportantNote>
    <SummaryStrip items={[<><MathText math="f: l=3\Rightarrow7" /> orbitals.</>, <><MathText math="g:l=4\Rightarrow9" /> orbitals.</>, <>For fixed <MathText math="l" />, increasing <MathText math="n" /> adds radial nodes.</>]} />
    <AuditComment pages="161-163" unclear={0} />
  </AtomicPartShell>;
}
