import type { NoteBlock } from "../types";

export const part16Source: NoteBlock[] = [
  {
    "kind": "theory",
    "title": "Abnormal colligative properties and the van’t Hoff factor",
    "paragraphs": [
      "If a solute dissociates into more particles or associates into fewer particles in solution, the observed colligative property differs from the value calculated from formula-unit concentration. The source defines van’t Hoff factor i as observed colligative property divided by the theoretical value for no association or dissociation.",
      "The same factor can be written as theoretical molar mass divided by observed colligative molar mass. Dissociation usually gives i>1; association gives i<1. For a nonelectrolyte with no reaction, i≈1 in the dilute ideal limit.",
      "Every ideal colligative equation is corrected by multiplying the particle concentration or molality by i."
    ],
    "equations": [
      "i=(observed colligative effect)/(calculated effect without reaction)",
      "i=M_normal/M_observed",
      "ΔT_b=iK_bm",
      "ΔT_f=iK_fm",
      "π=iCRT"
    ],
    "sourcePages": "Pages 73–74",
    "visual": "vant-hoff"
  },
  {
    "kind": "derivation",
    "title": "Relation between i and degree of dissociation",
    "introduction": "The source considers one mole of A dissociating into n particles with degree of dissociation α.",
    "steps": [
      "Initial formula units of A =1 mol.",
      "Undissociated A remaining =1−α mol.",
      "Dissociated amount α mol produces nα mol particles.",
      "Total solute particles=(1−α)+nα=1+α(n−1).",
      "Divide by the original one mole of formula units."
    ],
    "result": "i=1+α(n−1), so α=(i−1)/(n−1)",
    "assumptions": [
      "All dissociation steps represented by one overall stoichiometry.",
      "Ideal particle contributions.",
      "No simultaneous association or complex formation."
    ],
    "sourcePages": "Page 74",
    "visual": "vant-hoff"
  },
  {
    "kind": "derivation",
    "title": "Relation between i and degree of association",
    "introduction": "For association of n monomers to one n-mer, the particle count decreases.",
    "steps": [
      "Start with one mole of monomer units.",
      "If fraction α of monomer units associates, unassociated monomer is 1−α mol.",
      "The associated α mol monomer units form α/n mol n-mer particles.",
      "Total particles=1−α+α/n.",
      "Divide by the original one mole of monomer units."
    ],
    "result": "i=1−α(1−1/n), so α=n(1−i)/(n−1)",
    "assumptions": [
      "Only one associated species forms.",
      "Association stoichiometry is nA⇌A_n.",
      "Ideal dilute behaviour."
    ],
    "sourcePages": "Pages 74 and 76"
  },
  {
    "kind": "table",
    "title": "van’t Hoff factors in the source electrolyte table",
    "headers": [
      "Electrolyte",
      "Ideal limiting i",
      "Observed trend on dilution",
      "Interpretation"
    ],
    "rows": [
      [
        "NaCl",
        "2",
        "i rises toward 2 as concentration falls",
        "Interionic attraction is weaker at greater dilution."
      ],
      [
        "KCl",
        "2",
        "i rises toward 2 as concentration falls",
        "Nearly complete dissociation in the dilute limit."
      ],
      [
        "MgSO₄",
        "2",
        "i remains below 2 at finite concentration",
        "Doubly charged ions show stronger ion pairing and nonideality."
      ],
      [
        "K₂SO₄",
        "3",
        "i rises toward 3 on dilution",
        "Three ideal ions per formula unit, but finite-concentration interactions reduce effective i."
      ]
    ],
    "note": "The numerical values in the source table illustrate concentration dependence; i is not exactly the stoichiometric ion count except at the ideal infinite-dilution limit.",
    "sourcePages": "Page 75"
  },
  {
    "kind": "theory",
    "title": "Aluminium sulfate dissociation problem retained from the source",
    "paragraphs": [
      "The source asks for osmotic pressure of an aluminium sulfate solution when a degree of dissociation is supplied. Al₂(SO₄)₃ produces five ions in the ideal complete-dissociation limit, so i=1+4α.",
      "The osmotic calculation is then π=iCRT. The source also verifies the result by explicitly counting final concentrations: undissociated salt concentration plus concentrations of Al³⁺ and SO₄²⁻ generated by the dissociated fraction. Both methods must agree.",
      "Solved Question 16.1 changes concentration, temperature and degree of dissociation while preserving both solution routes."
    ],
    "equations": [
      "Al₂(SO₄)₃→2Al³⁺+3SO₄²⁻",
      "i=1+4α",
      "π=iCRT"
    ],
    "sourcePages": "Page 75"
  },
  {
    "kind": "theory",
    "title": "Dimerisation of an organic acid in benzene",
    "paragraphs": [
      "Carboxylic acids often form hydrogen-bonded dimers in nonpolar solvents such as benzene. For 2A⇌A₂, association lowers particle count. If the degree of dimerisation is α, i=1−α/2.",
      "The source calculates the boiling point of a benzene solution containing acetic acid with partial dimerisation. First determine molality from monomer molar mass and masses as prepared; then use ΔT_b=iK_bm and add the elevation to the pure benzene boiling point.",
      "Solved Question 16.3 retains this structure with modified masses and association extent."
    ],
    "equations": [
      "For dimerisation: i=1−α/2",
      "ΔT_b=iK_bm"
    ],
    "sourcePages": "Page 76"
  },
  {
    "kind": "theory",
    "title": "Descriptive ranking of freezing points",
    "paragraphs": [
      "The final source item compares equal-molar aqueous solutions of urea, NaCl, CaCl₂ and AlCl₃. Rather than retaining the objective format, the rebuilt notes ask for a reasoned ranking. For equal molality and the same solvent, ΔT_f is proportional to i.",
      "In the ideal complete-dissociation limit, urea gives i=1, NaCl i=2, CaCl₂ i=3 and AlCl₃ i=4. Larger i means larger depression and therefore a lower freezing point. Hence the highest freezing point belongs to urea and the lowest to AlCl₃.",
      "At finite concentration, actual factors are below stoichiometric values because of interionic interactions, but the qualitative order normally remains."
    ],
    "equations": [
      "T_f=T_f°−iK_fm",
      "For equal m: urea > NaCl > CaCl₂ > AlCl₃ in freezing temperature"
    ],
    "sourcePages": "Page 77"
  }
];
