import fs from "node:fs";
import path from "node:path";
import {
  createPYQContentHash,
  getVerifiedNEETQuestions,
  validatePYQDataset,
  withPYQContentHashes,
  type NEETChemistryPYQQuestion,
} from "../lib/pyq/neetChemistry";
import { VERIFIED_NEET_CHEMISTRY_QUESTIONS } from "../lib/pyq/neetChemistryDataset";

const DATASET_PATH = path.join(process.cwd(), "lib/pyq/neetChemistryDataset.ts");

function readArg(name: string) {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : undefined;
}

function usage() {
  console.log("Usage: npx tsx scripts/import-verified-neet-pyq.ts --input ./verified.json --dry-run");
}

function readInput(inputPath: string): NEETChemistryPYQQuestion[] {
  const absolutePath = path.resolve(process.cwd(), inputPath);
  const raw = fs.readFileSync(absolutePath, "utf8");
  const parsed = JSON.parse(raw);
  if (!Array.isArray(parsed)) {
    throw new Error("Input must be a JSON array of verified NEET Chemistry PYQ records.");
  }
  return parsed as NEETChemistryPYQQuestion[];
}

function formatDataset(questions: NEETChemistryPYQQuestion[]) {
  return `import type { NEETChemistryPYQQuestion } from "./neetChemistry";

// Production source of verified NEET/AIPMT Chemistry PYQs.
// Records in this file must be generated by scripts/import-verified-neet-pyq.ts
// after official examination-authority provenance validation.
export const VERIFIED_NEET_CHEMISTRY_QUESTIONS: NEETChemistryPYQQuestion[] = ${JSON.stringify(questions, null, 2)};

export const NEET_CHEMISTRY_PYQ_STATS = {
  totalRecords: VERIFIED_NEET_CHEMISTRY_QUESTIONS.length,
  verifiedOfficial: VERIFIED_NEET_CHEMISTRY_QUESTIONS.filter((question) => question.verificationStatus === "verified-official").length,
  pending: VERIFIED_NEET_CHEMISTRY_QUESTIONS.filter((question) => question.verificationStatus === "pending-verification").length,
  rejected: VERIFIED_NEET_CHEMISTRY_QUESTIONS.filter((question) => question.verificationStatus === "rejected").length,
  neet: VERIFIED_NEET_CHEMISTRY_QUESTIONS.filter((question) => question.program === "neet").length,
  aipmt: VERIFIED_NEET_CHEMISTRY_QUESTIONS.filter((question) => question.program === "aipmt").length,
} as const;
`;
}

const input = readArg("--input");
const dryRun = process.argv.includes("--dry-run");

if (!input) {
  usage();
  process.exit(1);
}

const incoming = withPYQContentHashes(readInput(input));
const existing = withPYQContentHashes(VERIFIED_NEET_CHEMISTRY_QUESTIONS);
const merged = [...existing, ...incoming];
const validation = validatePYQDataset(merged);
const verified = getVerifiedNEETQuestions(merged);

const existingHashes = new Set(existing.map((question) => question.contentHash || createPYQContentHash(question)));
const duplicateIncoming = incoming.filter((question) => existingHashes.has(question.contentHash || createPYQContentHash(question)));

console.log(JSON.stringify({
  input,
  dryRun,
  incoming: incoming.length,
  existing: existing.length,
  merged: merged.length,
  verifiedOfficial: verified.length,
  duplicateIncoming: duplicateIncoming.length,
  validationIssues: validation.issues.length,
}, null, 2));

if (duplicateIncoming.length > 0) {
  console.error("Import rejected: input contains records already present in the verified dataset.");
  process.exit(1);
}

if (!validation.ok) {
  console.error("Import rejected. First validation issues:");
  for (const issue of validation.issues.slice(0, 20)) {
    console.error(`- ${issue.id}: ${issue.message}`);
  }
  process.exit(1);
}

if (verified.length !== merged.length) {
  console.error("Import rejected: all records must be verified official NEET/AIPMT Chemistry records.");
  process.exit(1);
}

if (dryRun) {
  console.log("Dry run passed. No production data was modified.");
} else {
  fs.writeFileSync(DATASET_PATH, formatDataset(merged));
  console.log(`Wrote ${merged.length} verified records to ${path.relative(process.cwd(), DATASET_PATH)}.`);
}
