import type { KnowledgeOrder } from "../schema";

// ─────────────────────────────────────────────────────────────────────────────
// Organic Chemistry — Important Orders
// ─────────────────────────────────────────────────────────────────────────────

export const ORGANIC_ORDERS: KnowledgeOrder[] = [

  {
    id: "oc-cation-stability",
    title: "Carbocation Stability Order",
    category: "Organic",
    chapter: "General Organic Chemistry",
    property: "Carbocation stability",
    order: "C₆H₅CH₂⁺ ≈ (CH₃)₂C=CH–CH₂⁺ > (CH₃)₃C⁺ > (CH₃)₂CH⁺ > CH₃CH₂⁺ > CH₃⁺",
    direction: "Decreasing",
    explanation: "Benzylic/allylic carbocations are stabilised by resonance (delocalization into π system). Tertiary stabilised by hyperconjugation and inductive effect of alkyl groups. Secondary and primary are progressively less stable.",
    exceptions: [
      "C₆H₅CH₂⁺ (benzylic) ≈ allylic when extended conjugation present",
      "Bridgehead carbocations (norbornyl) violate Bredt's rule and are extremely unstable despite substitution",
      "Cyclopropylmethyl cation is exceptionally stable (ring opening provides extended resonance)",
    ],
    relatedConcepts: ["Carbocation stability", "Resonance", "Hyperconjugation", "SN1 rate"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "High",
      pyqCount: 45,
      lastAsked: 2024,
      tags: ["carbocation", "stability-order", "SN1"],
    },
    ncertReferences: ["Class 11 Ch. 12 — Stability of Carbocations"],
    memoryTriggers: [
      "Benzyl > Allyl > Tertiary > Secondary > Primary > Methyl",
      "More resonance = more stable cation",
    ],
    verified: true,
  },

  {
    id: "oc-carbanion-stability",
    title: "Carbanion Stability Order",
    category: "Organic",
    chapter: "General Organic Chemistry",
    property: "Carbanion stability",
    order: "C₆H₅CH₂⁻ > (CH₂=CH–CH₂⁻) > CH₃⁻ < CH₃CH₂⁻ < (CH₃)₂CH⁻ < (CH₃)₃C⁻",
    direction: "Mixed",
    explanation: "Carbanions are OPPOSITE to carbocations in terms of inductive effect: electron-withdrawing groups stabilise carbanions, electron-donating groups destabilise them. Benzylic/allylic carbanions are stabilised by resonance. Alkyl carbanion order: methyl > primary > secondary > tertiary (alkyl groups are +I = destabilising for carbanion).",
    exceptions: [
      "Unlike carbocations, alkyl groups DESTABILiSE carbanions",
      "sp carbon (e.g., alkynyl, RC≡C⁻) carbanions are more stable than sp³ (orbital character: more s = more electronegative = better holds negative charge)",
    ],
    relatedConcepts: ["Carbanion", "sp orbital character", "Acidic C–H bonds", "Resonance stabilisation"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Very High",
      neet: "Medium",
      pyqCount: 20,
      lastAsked: 2024,
      tags: ["carbanion", "stability", "basicity"],
    },
    ncertReferences: ["Class 11 Ch. 12 — Reactive Intermediates"],
    memoryTriggers: [
      "Carbanion: OPPOSITE to carbocation for inductive effect",
      "Methyl carbanion most stable (among alkyl); tertiary least stable",
    ],
    verified: true,
  },

  {
    id: "oc-radical-stability",
    title: "Free Radical Stability Order",
    category: "Organic",
    chapter: "General Organic Chemistry",
    property: "Free radical stability",
    order: "C₆H₅CH₂• > (CH₃)₂C=CHCH₂• > (CH₃)₃C• > (CH₃)₂CH• > CH₃CH₂• > CH₃•",
    direction: "Decreasing",
    explanation: "Radicals stabilised by same principles as carbocations (hyperconjugation for alkyl, resonance for benzylic/allylic). Sp³ radical more stable than sp² or sp. Benzylic radical is most stable (ring resonance).",
    exceptions: [
      "Radical stability order is SAME as carbocation (both benefit from hyperconjugation and resonance)",
      "Unlike carbocations, lone pair donation from heteroatoms doesn't stabilise radicals effectively",
    ],
    relatedConcepts: ["Free radical", "Radical halogenation", "NBS", "Stability"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "Medium",
      pyqCount: 18,
      lastAsked: 2023,
      tags: ["free-radical", "stability", "NBS", "allylic"],
    },
    ncertReferences: ["Class 11 Ch. 12 — Free Radicals"],
    memoryTriggers: [
      "Radical stability = carbocation stability order (both love electron density)",
    ],
    verified: true,
  },

  {
    id: "oc-acidity-ch",
    title: "Acidity of C–H Bonds (pKa Order)",
    category: "Organic",
    chapter: "General Organic Chemistry",
    property: "C–H bond acidity (pKa)",
    order: "RC≡C–H (pKa≈25) < H₂C=CH₂ (pKa≈44) < CH₄ (pKa≈50) << H₂O (pKa≈16) < CH₃OH (pKa≈16) << HCl (pKa≈−7)",
    direction: "Decreasing",
    explanation: "The acidity of C–H bonds depends on the orbital character of the C. sp carbon (25% s character) holds electrons closer to nucleus → more acidic. sp² (33% s): intermediate. sp³ (25% s): least acidic. Alkyne (sp C–H) is most acidic among C–H bonds.",
    exceptions: [
      "Terminal alkyne pKa ≈ 25 — this is why NaNH₂ (pKa ≈ 38) can deprotonate alkynes",
      "DMSO solvent raises apparent acidities of C–H bonds significantly",
    ],
    relatedConcepts: ["pKa", "sp orbital character", "Alkyne acidity", "Carbanion formation"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Very High",
      neet: "Low",
      pyqCount: 14,
      lastAsked: 2024,
      tags: ["C-H-acidity", "pKa", "sp-character", "alkyne"],
    },
    ncertReferences: [],
    memoryTriggers: [
      "sp C–H most acidic (alkyne). sp³ C–H least acidic (methane).",
      "More s character = more electronegative carbon = better holds negative charge",
    ],
    verified: true,
  },

  {
    id: "oc-basicity-amines",
    title: "Basicity of Amines in Aqueous Solution",
    category: "Organic",
    chapter: "Amines",
    property: "Amine basicity (pKb) in water",
    order: "(CH₃)₂NH (pKb≈3.4) > CH₃NH₂ (pKb≈3.4) > (CH₃)₃N (pKb≈4.2) > NH₃ (pKb≈4.7) > C₆H₅NH₂ (pKb≈9.4)",
    direction: "Decreasing",
    explanation: "In water, solvation of conjugate acid is critical. Secondary ammonium ion (R₂NH₂⁺) has 2 N–H bonds available for H-bonding (best solvation). Tertiary ammonium ion (R₃NH⁺) has only 1 N–H → poor solvation despite highest inductive +I. Aniline: N lone pair conjugated with ring → very weak base.",
    exceptions: [
      "In gas phase: (CH₃)₃N > (CH₃)₂NH > CH₃NH₂ > NH₃ (pure induction, no solvation)",
      "In water: 2° > 1° > 3° (solvation reverses 1° and 3° order)",
      "Aniline is far weaker than all aliphatic amines due to resonance",
    ],
    relatedConcepts: ["Basicity", "Solvation", "Inductive effect", "Resonance", "Amine"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "Very High",
      pyqCount: 40,
      lastAsked: 2024,
      tags: ["amine-basicity", "aqueous", "solvation", "inductive"],
    },
    ncertReferences: ["Class 12 Ch. 13 — Basicity of Amines"],
    memoryTriggers: [
      "Water: 2° > 1° > 3° > NH₃ >> aniline",
      "Gas phase: 3° > 2° > 1° > NH₃ (opposite for 1° vs 3°)",
    ],
    verified: true,
  },

  {
    id: "oc-carbonyl-reactivity",
    title: "Reactivity of Carbonyl Compounds towards Nucleophiles",
    category: "Organic",
    chapter: "Aldehydes Ketones",
    property: "Nucleophilic addition reactivity",
    order: "HCHO > RCHO > CH₃COCH₃ > RCOCH₃ > RCOR' > RCOCl > RCOOCOR > RCOOR > RCONHR > RCOO⁻",
    direction: "Decreasing",
    explanation: "Reactivity decreases as (1) steric hindrance at carbonyl C increases and (2) electron density at carbonyl C increases (resonance donation from lone pair). Acid chlorides most reactive (Cl is poor donor, strong −I). Carboxylate least reactive (two lone pairs stabilise by strong resonance).",
    exceptions: [
      "Acid anhydrides more reactive than esters but less than acid chlorides",
      "Amides are much less reactive than esters due to strong N→C=O resonance",
      "Carboxylate ion (RCOO⁻): almost no nucleophilic addition due to resonance stabilisation",
    ],
    relatedConcepts: ["Nucleophilic addition", "Acyl substitution", "Reactivity", "Steric effects"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Very High",
      neet: "Medium",
      pyqCount: 22,
      lastAsked: 2024,
      tags: ["carbonyl-reactivity", "nucleophilic-addition", "acyl"],
    },
    ncertReferences: ["Class 12 Ch. 12 — Reactivity of Carbonyl Compounds"],
    memoryTriggers: [
      "HCHO (no substituent) = most reactive; carboxylate = least (resonance-locked)",
      "Aldehyde > Ketone (more sterically open, less electron-donating substituents)",
    ],
    verified: true,
  },

  {
    id: "oc-acidity-carboxylic",
    title: "Acidity Order of Carboxylic Acids",
    category: "Organic",
    chapter: "Carboxylic Acids",
    property: "Acid strength (pKa)",
    order: "HCOOH (pKa 3.75) > CH₃COOH (pKa 4.74) > CH₃CH₂COOH (pKa 4.87) > (CH₃)₃CCOOH",
    direction: "Decreasing",
    explanation: "More alkyl groups on α-carbon: +I effect increases electron density at COOH → destabilises carboxylate → weaker acid. HCOOH (no alkyl) is most acidic among saturated carboxylic acids. Halogenated acids are more acidic due to −I effect of halogens.",
    exceptions: [
      "Formic acid (HCOOH) is MOST acidic among simple carboxylic acids",
      "Haloacids: CHCl₂COOH > CH₂ClCOOH > CH₃COOH (−I effect increases acidity)",
      "Benzoic acid (pKa 4.19) is stronger than acetic acid due to ring −I effect",
    ],
    relatedConcepts: ["Inductive effect", "Acidity", "Carboxylate stability", "pKa"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "Very High",
      pyqCount: 35,
      lastAsked: 2024,
      tags: ["carboxylic-acid", "acidity", "inductive", "pKa"],
    },
    ncertReferences: ["Class 12 Ch. 12 — Acidity of Carboxylic Acids"],
    memoryTriggers: [
      "More alkyl = less acidic (chain grows = acidity drops)",
      "Formic acid = most acidic simple carboxylic acid",
    ],
    verified: true,
  },

  {
    id: "oc-sn1-rate",
    title: "SN1 Reaction Rate Order",
    category: "Organic",
    chapter: "Haloalkanes and Haloarenes",
    property: "SN1 reaction rate",
    order: "C₆H₅CH₂X > (CH₃)₃CX > (CH₃)₂CHX > CH₃CH₂X > CH₃X",
    direction: "Decreasing",
    explanation: "SN1 rate determined by stability of carbocation intermediate. Benzylic > tertiary > secondary > primary > methyl — same as carbocation stability.",
    exceptions: [
      "Allyl halides also react fast (allyl carbocation, resonance stabilised)",
      "Vinyl and aryl halides essentially unreactive in SN1 (no stable vinyl/aryl cation)",
      "Neopentyl halide: despite primary, does not undergo SN1 normally; undergoes rearrangement first",
    ],
    relatedConcepts: ["SN1", "Carbocation", "Rate-determining step", "Stereochemistry"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "High",
      pyqCount: 30,
      lastAsked: 2024,
      tags: ["SN1", "rate-order", "carbocation"],
    },
    ncertReferences: ["Class 12 Ch. 10 — SN1 Mechanism"],
    memoryTriggers: [
      "SN1: same order as carbocation stability (more stable cation = faster SN1)",
    ],
    verified: true,
  },

  {
    id: "oc-sn2-rate",
    title: "SN2 Reaction Rate Order",
    category: "Organic",
    chapter: "Haloalkanes and Haloarenes",
    property: "SN2 reaction rate",
    order: "CH₃X > CH₃CH₂X > (CH₃)₂CHX >> (CH₃)₃CX",
    direction: "Decreasing",
    explanation: "SN2 rate determined by steric accessibility of the carbon under attack (backside attack). Methyl: no steric hindrance = fastest. Primary: one alkyl group = moderate hindrance. Secondary: two alkyl groups = slow. Tertiary: three groups = essentially no SN2.",
    exceptions: [
      "Tertiary: essentially no SN2 (steric blocking)",
      "Neopentyl halide (primary but bulky β-carbon): very slow SN2 despite being primary",
    ],
    relatedConcepts: ["SN2", "Backside attack", "Steric hindrance", "Inversion of configuration"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "High",
      pyqCount: 32,
      lastAsked: 2024,
      tags: ["SN2", "rate-order", "steric-hindrance"],
    },
    ncertReferences: ["Class 12 Ch. 10 — SN2 Mechanism"],
    memoryTriggers: [
      "SN2: Methyl > 1° > 2° >> 3° (steric hindrance controls rate)",
      "OPPOSITE to SN1 — SN2 hates bulky groups",
    ],
    verified: true,
  },

  {
    id: "oc-leaving-group",
    title: "Leaving Group Ability Order",
    category: "Organic",
    chapter: "Haloalkanes and Haloarenes",
    property: "Leaving group ability",
    order: "I⁻ > Br⁻ > Cl⁻ > F⁻ (and TsO⁻ > I⁻ among common leaving groups)",
    direction: "Decreasing",
    explanation: "Good leaving groups are the conjugate bases of strong acids (they can stabilise negative charge). HI strongest acid → I⁻ best leaving group. HF weakest acid → F⁻ poorest leaving group. This correlates with C–X bond strength: I–C weakest (easiest to break).",
    exceptions: [
      "F⁻ is the worst leaving group among halogens (C–F strongest bond, F⁻ too basic)",
      "Tosylate (TsO⁻) is an excellent leaving group (even better than I⁻) because p-toluenesulphonate is extremely stable",
      "OH⁻ is a poor leaving group; must be protonated to H₂O (neutral, good leaving group) or converted to OTs",
    ],
    relatedConcepts: ["Leaving group", "pKa", "C–X bond strength", "Nucleofugality"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "Very High",
      neet: "Medium",
      pyqCount: 18,
      lastAsked: 2024,
      tags: ["leaving-group", "SN1", "SN2", "halides"],
    },
    ncertReferences: ["Class 12 Ch. 10 — Nucleophilic Substitution"],
    memoryTriggers: [
      "Best leaving group = weakest base = conjugate base of strongest acid: I⁻ (HI very strong acid)",
      "F⁻ = poorest leaving group (HF is weak acid → F⁻ is strong base → bad leaving group)",
    ],
    verified: true,
  },

];
