import type { KnowledgeOrder } from "../schema";

// ─────────────────────────────────────────────────────────────────────────────
// Physical Chemistry — Important Orders
// ─────────────────────────────────────────────────────────────────────────────

export const PHYSICAL_ORDERS: KnowledgeOrder[] = [

  {
    id: "pc-ie1-period2",
    title: "IE₁ Order in Period 2",
    category: "Physical",
    chapter: "Periodic Table",
    property: "First ionisation energy",
    order: "Ne > F > N > O > C > Be > B > Li",
    direction: "Decreasing",
    explanation: "General trend: increases left to right. Exceptions: (1) B < Be — B loses 2p electron (easier than Be's 2s); (2) O < N — N has half-filled 2p³ (extra stable by exchange energy), O pairs one 2p electron (lowers IE). Ne and F follow the trend; noble gas highest.",
    exceptions: [
      "IE₁(B) < IE₁(Be) — 2p electron removed from B (higher energy, less penetrating than 2s of Be)",
      "IE₁(O) < IE₁(N) — N has half-filled 2p³ stability",
      "Similar pattern in Period 3: IE₁(Al) < IE₁(Mg) and IE₁(S) < IE₁(P)",
    ],
    relatedConcepts: ["IE₁ trend", "Half-filled stability", "Exchange energy", "2s vs 2p energy"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "Very High",
      neet: "Very High",
      pyqCount: 55,
      lastAsked: 2024,
      tags: ["IE1", "Period-2", "exceptions", "N-O", "B-Be"],
    },
    ncertReferences: ["Class 11 Ch. 3 — Ionisation Enthalpy"],
    memoryTriggers: [
      "IE₁ Period 2: Ne > F > N > O > C > Be > B > Li (two exceptions: N>O and Be>B)",
    ],
    verified: true,
  },

  {
    id: "pc-ea-halogens",
    title: "Electron Affinity Order of Halogens",
    category: "Physical",
    chapter: "Periodic Table",
    property: "Electron affinity",
    order: "Cl > F > Br > I",
    direction: "Decreasing",
    explanation: "Cl has highest EA (−349 kJ/mol) among halogens. F is SECOND despite being smallest (F's compact 2p orbital repels incoming electron). Br and I: larger atoms with weaker nuclear attraction for added electron → lower EA.",
    exceptions: [
      "F is NOT the element with highest EA despite being most electronegative",
      "Cl > F anomaly: F's 2p orbital too compact, repulsion > attraction for incoming electron",
      "Among ALL elements: Cl has very high EA, only surpassed by some 6th period elements",
    ],
    relatedConcepts: ["Electron affinity", "Periodic trend", "Electronegativity vs EA", "Orbital compactness"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "Very High",
      pyqCount: 42,
      lastAsked: 2024,
      tags: ["EA", "halogens", "Cl-vs-F", "exception"],
    },
    ncertReferences: ["Class 11 Ch. 3 — Electron Gain Enthalpy"],
    memoryTriggers: [
      "EA order: Cl > F > Br > I (Cl beats F despite F being more electronegative)",
      "F's house is too crowded — electron can't fit comfortably",
    ],
    verified: true,
  },

  {
    id: "pc-boiling-group16-hydrides",
    title: "Boiling Point Order of Group 16 Hydrides",
    category: "Physical",
    chapter: "Hydrogen",
    property: "Boiling point",
    order: "H₂O (100°C) >> H₂Te (−2°C) > H₂Se (−41°C) > H₂S (−60°C)",
    direction: "Mixed",
    explanation: "H₂S, H₂Se, H₂Te: boiling point increases with molar mass (stronger London dispersion forces). H₂O is anomalously high (100°C) due to strong intermolecular H-bonding. Among H₂S, H₂Se, H₂Te the regular trend holds (no H-bonding in these).",
    exceptions: [
      "H₂O zigzags above the expected trend (should be lowest bp in group if only van der Waals)",
      "Same pattern: HF > HCl < HBr < HI (zigzag in Group 17)",
      "NH₃ > PH₃ < AsH₃ < SbH₃ (zigzag in Group 15)",
    ],
    relatedConcepts: ["Hydrogen bonding", "Van der Waals forces", "Anomalous properties of water", "Boiling point trend"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "Very High",
      pyqCount: 35,
      lastAsked: 2024,
      tags: ["boiling-point", "H2O", "H2S", "Group-16", "H-bonding"],
    },
    ncertReferences: ["Class 11 Ch. 4 — Hydrogen Bonding", "Class 11 Ch. 9 — Water"],
    memoryTriggers: [
      "H₂O = outlier (H-bonds). H₂S < H₂Se < H₂Te = normal van der Waals trend",
    ],
    verified: true,
  },

  {
    id: "pc-lattice-energy-alkali-halides",
    title: "Lattice Energy Order of Alkali Metal Halides",
    category: "Physical",
    chapter: "s-Block Elements",
    property: "Lattice energy",
    order: "LiF > NaF > KF > RbF > CsF (at constant anion); LiF > LiCl > LiBr > LiI (at constant cation)",
    direction: "Decreasing",
    explanation: "Lattice energy ∝ (|Z⁺||Z⁻|) / r₀, where r₀ is interionic distance. Smaller cation = shorter distance = higher lattice energy. Smaller anion = shorter distance = higher lattice energy. LiF has the highest lattice energy among alkali halides.",
    exceptions: [
      "LiF is sparingly soluble in water despite high lattice energy — high hydration energy of F⁻ partially compensates but lattice energy wins",
      "Cs salts of large anions have lower lattice energy but may be soluble due to entropy effects",
    ],
    relatedConcepts: ["Lattice energy", "Born-Haber cycle", "Ionic radius", "Charge density"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "Medium",
      pyqCount: 20,
      lastAsked: 2023,
      tags: ["lattice-energy", "alkali-halides", "ionic", "Born-Haber"],
    },
    ncertReferences: ["Class 11 Ch. 4 — Lattice Enthalpy"],
    memoryTriggers: [
      "Smaller ion = higher lattice energy (distance decreases = force increases)",
      "LiF has highest lattice energy among alkali halides",
    ],
    verified: true,
  },

  {
    id: "pc-hydration-enthalpy-cations",
    title: "Hydration Enthalpy Order of Cations",
    category: "Physical",
    chapter: "Solutions",
    property: "Hydration enthalpy",
    order: "Li⁺ > Na⁺ > K⁺ > Rb⁺ > Cs⁺ (most negative = most hydrated = highest energy released)",
    direction: "Decreasing",
    explanation: "Hydration enthalpy ∝ charge density (charge/radius). Li⁺ is the smallest alkali metal cation (highest charge density) → strongest electrostatic attraction for water dipoles → highest hydration enthalpy. Despite this, Li⁺ is the LEAST mobile in solution (bulky hydration shell).",
    exceptions: [
      "Li⁺ has highest hydration enthalpy but LOWEST ionic mobility (large hydrated radius)",
      "Cs⁺ has lowest hydration enthalpy but HIGHEST ionic mobility (small hydrated radius)",
      "Order of hydrated ionic radius is REVERSE of bare ionic radius",
    ],
    relatedConcepts: ["Hydration enthalpy", "Charge density", "Ionic mobility", "Conductance"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "Medium",
      pyqCount: 18,
      lastAsked: 2023,
      tags: ["hydration-enthalpy", "Li+", "Na+", "K+", "charge-density"],
    },
    ncertReferences: ["Class 11 Ch. 10 — s-Block Elements"],
    memoryTriggers: [
      "Smaller ion = higher hydration enthalpy (Li⁺ most, Cs⁺ least)",
      "Paradox: Li⁺ most hydrated → slowest moving ion in solution",
    ],
    verified: true,
  },

  {
    id: "pc-acidic-strength-oxyacids",
    title: "Acidic Strength of Oxyacids of Halogens",
    category: "Physical",
    chapter: "p-Block Elements",
    property: "Acid strength",
    order: "HClO₄ > HClO₃ > HClO₂ > HClO (at constant halogen)",
    direction: "Decreasing",
    explanation: "More oxygen atoms on the central halogen = higher oxidation state = more electron withdrawal from O–H = weaker O–H bond = stronger acid. Rule: acid strength increases with oxidation state of central atom (more =O groups increase acid strength).",
    exceptions: [
      "At constant oxidation state, going down Group 17: HIO₄ < HBrO₄ < HClO₄ (more electronegative central atom → stronger acid)",
      "This applies to ALL oxyacids: more =O groups = stronger acid",
    ],
    relatedConcepts: ["Oxyacid strength", "Central atom oxidation state", "Inductive effect", "Electronegativity"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "High",
      pyqCount: 28,
      lastAsked: 2024,
      tags: ["oxyacids", "halogen", "acidity-order", "oxidation-state"],
    },
    ncertReferences: ["Class 12 Ch. 7 — Oxyacids of Halogens"],
    memoryTriggers: [
      "More oxygens on central halogen = more acidic",
      "HClO₄ > HClO₃ > HClO₂ > HClO (perchloric strongest)",
    ],
    verified: true,
  },

  {
    id: "pc-ionic-radii-isoelectronic",
    title: "Ionic Radii Order of Isoelectronic Species",
    category: "Physical",
    chapter: "Periodic Table",
    property: "Ionic radius (isoelectronic series)",
    order: "N³⁻ > O²⁻ > F⁻ > Ne > Na⁺ > Mg²⁺ > Al³⁺ (all have 10 electrons)",
    direction: "Decreasing",
    explanation: "Isoelectronic species have the same number of electrons. Radius decreases as nuclear charge (protons) increases. More protons pull the same electron cloud inward → smaller radius. N (7p, 10e) has least attraction → largest; Al³⁺ (13p, 10e) has most → smallest.",
    exceptions: [
      "More negative charge = larger radius (more electron repulsion, same nuclear charge if iso-electron)",
      "Ne (noble gas) fits in the middle of the isoelectronic series",
    ],
    relatedConcepts: ["Isoelectronic species", "Ionic radius", "Effective nuclear charge"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "High",
      pyqCount: 30,
      lastAsked: 2024,
      tags: ["ionic-radius", "isoelectronic", "nuclear-charge"],
    },
    ncertReferences: ["Class 11 Ch. 3 — Ionic Radius"],
    memoryTriggers: [
      "Isoelectronic: more protons = smaller radius",
      "N³⁻ (7p) biggest; Al³⁺ (13p) smallest (same 10 electrons)",
    ],
    verified: true,
  },

  {
    id: "pc-conductivity-ions",
    title: "Ionic Conductance Order of Common Ions",
    category: "Physical",
    chapter: "Electrochemistry",
    property: "Molar ionic conductance",
    order: "H⁺ > OH⁻ > Cs⁺ > Rb⁺ > K⁺ > Na⁺ > Li⁺ (cations); F⁻ > Cl⁻ > Br⁻ > I⁻ is NOT the order — actual: OH⁻ > I⁻ > Br⁻ > Cl⁻ > F⁻",
    direction: "Mixed",
    explanation: "H⁺ and OH⁻ have anomalously high conductance via the Grotthuss (proton-jumping) mechanism. Among alkali metal cations: smaller ionic radius → larger hydrated radius → slower movement → lower conductance. Cs⁺ (large ion, small hydration shell) moves fastest. Li⁺ (small ion, large hydration shell) moves slowest.",
    exceptions: [
      "H⁺ and OH⁻: anomalously high conductance (Grotthuss mechanism — no actual ion movement, just proton transfer)",
      "Li⁺ has LOWEST conductance despite being smallest ion (large hydrated ion moves slowly)",
      "Anion conductance: I⁻ > Br⁻ > Cl⁻ > F⁻ (larger anions have smaller hydration shells)",
    ],
    relatedConcepts: ["Ionic conductance", "Grotthuss mechanism", "Hydrated ionic radius", "Kohlrausch's law"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "Medium",
      pyqCount: 16,
      lastAsked: 2023,
      tags: ["ionic-conductance", "Grotthuss", "hydration", "H+"],
    },
    ncertReferences: ["Class 12 Ch. 3 — Conductance of Electrolytic Solutions"],
    memoryTriggers: [
      "H⁺ and OH⁻ are superfast conductors (Grotthuss — no actual movement needed)",
      "Li⁺ = slowest alkali ion despite being smallest (largest hydrated ion)",
    ],
    verified: true,
  },

  {
    id: "pc-bond-energy-hx",
    title: "Bond Energy Order of H–X Bonds",
    category: "Physical",
    chapter: "p-Block Elements",
    property: "Bond dissociation enthalpy",
    order: "H–F (568 kJ/mol) > H–Cl (432) > H–Br (366) > H–I (298)",
    direction: "Decreasing",
    explanation: "H–X bond energy decreases as X increases in size. F is smallest → shortest H–F bond → strongest. As X gets larger (Cl, Br, I), the orbital overlap with H 1s decreases and the bond weakens.",
    exceptions: [
      "This is the DIRECT ORDER — opposite to acid strength of HX (HI > HBr > HCl > HF)",
      "F₂–F₂ bond energy is anomalously LOW (F₂ bond energy < Cl₂) due to lone-pair repulsion in the small F atom",
      "Acid strength is INVERSELY proportional to H–X bond strength (stronger bond → harder to ionise → weaker acid)",
    ],
    relatedConcepts: ["Bond energy", "Acid strength", "Orbital overlap", "H-X bond"],
    examRelevance: {
      jeeMain: "Very High",
      jeeAdvanced: "High",
      neet: "Very High",
      pyqCount: 32,
      lastAsked: 2024,
      tags: ["H-X-bond-energy", "acid-strength", "inverse-relationship", "HF"],
    },
    ncertReferences: ["Class 12 Ch. 7 — Hydrogen Halides"],
    memoryTriggers: [
      "H–F bond strongest (highest BE). HF is weakest acid (hardest to break)",
      "Bond energy order = OPPOSITE of acid strength for HX",
    ],
    verified: true,
  },

  {
    id: "pc-compressibility-factor",
    title: "Compressibility Factor Z Order for Real Gases",
    category: "Physical",
    chapter: "States of Matter",
    property: "Compressibility factor Z = PV/nRT",
    order: "At very high P: Z > 1 for all gases. At moderate P: Z < 1 for most gases (except H₂, He always Z > 1 at RT)",
    direction: "Mixed",
    explanation: "Z < 1: intermolecular attractions dominant (gas more compressible than ideal). Z > 1: repulsions/excluded volume dominant (gas occupies more volume than ideal). H₂ and He: very low attractive forces, so repulsions dominate even at moderate pressures → Z > 1 always at RT.",
    exceptions: [
      "H₂ and He: Z > 1 at all pressures at room temperature (weak attractions, hard sphere repulsions dominate)",
      "All gases: Z → 1 as P → 0 (approach ideal gas behaviour at low pressure)",
      "Boyle temperature: temperature at which Z = 1 over a range of pressures (gas behaves ideally)",
    ],
    relatedConcepts: ["Compressibility factor", "Van der Waals equation", "Real gas", "Boyle temperature"],
    examRelevance: {
      jeeMain: "High",
      jeeAdvanced: "High",
      neet: "Medium",
      pyqCount: 20,
      lastAsked: 2024,
      tags: ["Z-factor", "real-gas", "H2", "He", "compressibility"],
    },
    ncertReferences: ["Class 11 Ch. 5 — Real Gases — Compressibility Factor"],
    memoryTriggers: [
      "Z < 1 = attractions pulling molecules together (moderate P)",
      "Z > 1 = repulsions pushing molecules apart (high P, or always for H₂/He)",
      "H₂ and He are exceptional: always Z > 1 at room temperature",
    ],
    verified: true,
  },

];
