"use client";
import React, { useState } from "react";

const K={bg:"#0a1622",panel:"#102538",panel2:"#153149",line:"#294b67",text:"#eef4f8",dim:"#a5bbcb",gold:"#f2bd48",cyan:"#60d8ef",violet:"#bd9cff",mint:"#75dfb7",coral:"#f28d76",s:"#7fb7ed",p:"#f29a7b",d:"#78d8b6",f:"#c8a3e5",serif:"Georgia,'Iowan Old Style','Times New Roman',serif",sans:"-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif",mono:"'SFMono-Regular',Consolas,monospace"};
type Block="s"|"p"|"d"|"f";
type E={z:number;symbol:string;name:string;period:number;group:number;block:Block};
const ELEMENTS:E[]=[
  {z:1,symbol:"H",name:"Hydrogen",period:1,group:1,block:"s" as const},
  {z:2,symbol:"He",name:"Helium",period:1,group:18,block:"s" as const},
  {z:3,symbol:"Li",name:"Lithium",period:2,group:1,block:"s" as const},
  {z:4,symbol:"Be",name:"Beryllium",period:2,group:2,block:"s" as const},
  {z:5,symbol:"B",name:"Boron",period:2,group:13,block:"p" as const},
  {z:6,symbol:"C",name:"Carbon",period:2,group:14,block:"p" as const},
  {z:7,symbol:"N",name:"Nitrogen",period:2,group:15,block:"p" as const},
  {z:8,symbol:"O",name:"Oxygen",period:2,group:16,block:"p" as const},
  {z:9,symbol:"F",name:"Fluorine",period:2,group:17,block:"p" as const},
  {z:10,symbol:"Ne",name:"Neon",period:2,group:18,block:"p" as const},
  {z:11,symbol:"Na",name:"Sodium",period:3,group:1,block:"s" as const},
  {z:12,symbol:"Mg",name:"Magnesium",period:3,group:2,block:"s" as const},
  {z:13,symbol:"Al",name:"Aluminium",period:3,group:13,block:"p" as const},
  {z:14,symbol:"Si",name:"Silicon",period:3,group:14,block:"p" as const},
  {z:15,symbol:"P",name:"Phosphorus",period:3,group:15,block:"p" as const},
  {z:16,symbol:"S",name:"Sulfur",period:3,group:16,block:"p" as const},
  {z:17,symbol:"Cl",name:"Chlorine",period:3,group:17,block:"p" as const},
  {z:18,symbol:"Ar",name:"Argon",period:3,group:18,block:"p" as const},
  {z:19,symbol:"K",name:"Potassium",period:4,group:1,block:"s" as const},
  {z:20,symbol:"Ca",name:"Calcium",period:4,group:2,block:"s" as const},
  {z:21,symbol:"Sc",name:"Scandium",period:4,group:3,block:"d" as const},
  {z:22,symbol:"Ti",name:"Titanium",period:4,group:4,block:"d" as const},
  {z:23,symbol:"V",name:"Vanadium",period:4,group:5,block:"d" as const},
  {z:24,symbol:"Cr",name:"Chromium",period:4,group:6,block:"d" as const},
  {z:25,symbol:"Mn",name:"Manganese",period:4,group:7,block:"d" as const},
  {z:26,symbol:"Fe",name:"Iron",period:4,group:8,block:"d" as const},
  {z:27,symbol:"Co",name:"Cobalt",period:4,group:9,block:"d" as const},
  {z:28,symbol:"Ni",name:"Nickel",period:4,group:10,block:"d" as const},
  {z:29,symbol:"Cu",name:"Copper",period:4,group:11,block:"d" as const},
  {z:30,symbol:"Zn",name:"Zinc",period:4,group:12,block:"d" as const},
  {z:31,symbol:"Ga",name:"Gallium",period:4,group:13,block:"p" as const},
  {z:32,symbol:"Ge",name:"Germanium",period:4,group:14,block:"p" as const},
  {z:33,symbol:"As",name:"Arsenic",period:4,group:15,block:"p" as const},
  {z:34,symbol:"Se",name:"Selenium",period:4,group:16,block:"p" as const},
  {z:35,symbol:"Br",name:"Bromine",period:4,group:17,block:"p" as const},
  {z:36,symbol:"Kr",name:"Krypton",period:4,group:18,block:"p" as const},
  {z:37,symbol:"Rb",name:"Rubidium",period:5,group:1,block:"s" as const},
  {z:38,symbol:"Sr",name:"Strontium",period:5,group:2,block:"s" as const},
  {z:39,symbol:"Y",name:"Yttrium",period:5,group:3,block:"d" as const},
  {z:40,symbol:"Zr",name:"Zirconium",period:5,group:4,block:"d" as const},
  {z:41,symbol:"Nb",name:"Niobium",period:5,group:5,block:"d" as const},
  {z:42,symbol:"Mo",name:"Molybdenum",period:5,group:6,block:"d" as const},
  {z:43,symbol:"Tc",name:"Technetium",period:5,group:7,block:"d" as const},
  {z:44,symbol:"Ru",name:"Ruthenium",period:5,group:8,block:"d" as const},
  {z:45,symbol:"Rh",name:"Rhodium",period:5,group:9,block:"d" as const},
  {z:46,symbol:"Pd",name:"Palladium",period:5,group:10,block:"d" as const},
  {z:47,symbol:"Ag",name:"Silver",period:5,group:11,block:"d" as const},
  {z:48,symbol:"Cd",name:"Cadmium",period:5,group:12,block:"d" as const},
  {z:49,symbol:"In",name:"Indium",period:5,group:13,block:"p" as const},
  {z:50,symbol:"Sn",name:"Tin",period:5,group:14,block:"p" as const},
  {z:51,symbol:"Sb",name:"Antimony",period:5,group:15,block:"p" as const},
  {z:52,symbol:"Te",name:"Tellurium",period:5,group:16,block:"p" as const},
  {z:53,symbol:"I",name:"Iodine",period:5,group:17,block:"p" as const},
  {z:54,symbol:"Xe",name:"Xenon",period:5,group:18,block:"p" as const},
  {z:55,symbol:"Cs",name:"Caesium",period:6,group:1,block:"s" as const},
  {z:56,symbol:"Ba",name:"Barium",period:6,group:2,block:"s" as const},
  {z:57,symbol:"La",name:"Lanthanum",period:6,group:3,block:"f" as const},
  {z:58,symbol:"Ce",name:"Cerium",period:6,group:3,block:"f" as const},
  {z:59,symbol:"Pr",name:"Praseodymium",period:6,group:3,block:"f" as const},
  {z:60,symbol:"Nd",name:"Neodymium",period:6,group:3,block:"f" as const},
  {z:61,symbol:"Pm",name:"Promethium",period:6,group:3,block:"f" as const},
  {z:62,symbol:"Sm",name:"Samarium",period:6,group:3,block:"f" as const},
  {z:63,symbol:"Eu",name:"Europium",period:6,group:3,block:"f" as const},
  {z:64,symbol:"Gd",name:"Gadolinium",period:6,group:3,block:"f" as const},
  {z:65,symbol:"Tb",name:"Terbium",period:6,group:3,block:"f" as const},
  {z:66,symbol:"Dy",name:"Dysprosium",period:6,group:3,block:"f" as const},
  {z:67,symbol:"Ho",name:"Holmium",period:6,group:3,block:"f" as const},
  {z:68,symbol:"Er",name:"Erbium",period:6,group:3,block:"f" as const},
  {z:69,symbol:"Tm",name:"Thulium",period:6,group:3,block:"f" as const},
  {z:70,symbol:"Yb",name:"Ytterbium",period:6,group:3,block:"f" as const},
  {z:71,symbol:"Lu",name:"Lutetium",period:6,group:3,block:"f" as const},
  {z:72,symbol:"Hf",name:"Hafnium",period:6,group:4,block:"d" as const},
  {z:73,symbol:"Ta",name:"Tantalum",period:6,group:5,block:"d" as const},
  {z:74,symbol:"W",name:"Tungsten",period:6,group:6,block:"d" as const},
  {z:75,symbol:"Re",name:"Rhenium",period:6,group:7,block:"d" as const},
  {z:76,symbol:"Os",name:"Osmium",period:6,group:8,block:"d" as const},
  {z:77,symbol:"Ir",name:"Iridium",period:6,group:9,block:"d" as const},
  {z:78,symbol:"Pt",name:"Platinum",period:6,group:10,block:"d" as const},
  {z:79,symbol:"Au",name:"Gold",period:6,group:11,block:"d" as const},
  {z:80,symbol:"Hg",name:"Mercury",period:6,group:12,block:"d" as const},
  {z:81,symbol:"Tl",name:"Thallium",period:6,group:13,block:"p" as const},
  {z:82,symbol:"Pb",name:"Lead",period:6,group:14,block:"p" as const},
  {z:83,symbol:"Bi",name:"Bismuth",period:6,group:15,block:"p" as const},
  {z:84,symbol:"Po",name:"Polonium",period:6,group:16,block:"p" as const},
  {z:85,symbol:"At",name:"Astatine",period:6,group:17,block:"p" as const},
  {z:86,symbol:"Rn",name:"Radon",period:6,group:18,block:"p" as const},
  {z:87,symbol:"Fr",name:"Francium",period:7,group:1,block:"s" as const},
  {z:88,symbol:"Ra",name:"Radium",period:7,group:2,block:"s" as const},
  {z:89,symbol:"Ac",name:"Actinium",period:7,group:3,block:"f" as const},
  {z:90,symbol:"Th",name:"Thorium",period:7,group:3,block:"f" as const},
  {z:91,symbol:"Pa",name:"Protactinium",period:7,group:3,block:"f" as const},
  {z:92,symbol:"U",name:"Uranium",period:7,group:3,block:"f" as const},
  {z:93,symbol:"Np",name:"Neptunium",period:7,group:3,block:"f" as const},
  {z:94,symbol:"Pu",name:"Plutonium",period:7,group:3,block:"f" as const},
  {z:95,symbol:"Am",name:"Americium",period:7,group:3,block:"f" as const},
  {z:96,symbol:"Cm",name:"Curium",period:7,group:3,block:"f" as const},
  {z:97,symbol:"Bk",name:"Berkelium",period:7,group:3,block:"f" as const},
  {z:98,symbol:"Cf",name:"Californium",period:7,group:3,block:"f" as const},
  {z:99,symbol:"Es",name:"Einsteinium",period:7,group:3,block:"f" as const},
  {z:100,symbol:"Fm",name:"Fermium",period:7,group:3,block:"f" as const},
  {z:101,symbol:"Md",name:"Mendelevium",period:7,group:3,block:"f" as const},
  {z:102,symbol:"No",name:"Nobelium",period:7,group:3,block:"f" as const},
  {z:103,symbol:"Lr",name:"Lawrencium",period:7,group:3,block:"f" as const},
  {z:104,symbol:"Rf",name:"Rutherfordium",period:7,group:4,block:"d" as const},
  {z:105,symbol:"Db",name:"Dubnium",period:7,group:5,block:"d" as const},
  {z:106,symbol:"Sg",name:"Seaborgium",period:7,group:6,block:"d" as const},
  {z:107,symbol:"Bh",name:"Bohrium",period:7,group:7,block:"d" as const},
  {z:108,symbol:"Hs",name:"Hassium",period:7,group:8,block:"d" as const},
  {z:109,symbol:"Mt",name:"Meitnerium",period:7,group:9,block:"d" as const},
  {z:110,symbol:"Ds",name:"Darmstadtium",period:7,group:10,block:"d" as const},
  {z:111,symbol:"Rg",name:"Roentgenium",period:7,group:11,block:"d" as const},
  {z:112,symbol:"Cn",name:"Copernicium",period:7,group:12,block:"d" as const},
  {z:113,symbol:"Nh",name:"Nihonium",period:7,group:13,block:"p" as const},
  {z:114,symbol:"Fl",name:"Flerovium",period:7,group:14,block:"p" as const},
  {z:115,symbol:"Mc",name:"Moscovium",period:7,group:15,block:"p" as const},
  {z:116,symbol:"Lv",name:"Livermorium",period:7,group:16,block:"p" as const},
  {z:117,symbol:"Ts",name:"Tennessine",period:7,group:17,block:"p" as const},
  {z:118,symbol:"Og",name:"Oganesson",period:7,group:18,block:"p" as const}
];
const BC:Record<Block,string>={s:K.s,p:K.p,d:K.d,f:K.f};


type Accent = "gold"|"cyan"|"violet"|"mint"|"coral";
const A:Record<Accent,string>={gold:K.gold,cyan:K.cyan,violet:K.violet,mint:K.mint,coral:K.coral};
const css=`
.hmla-v2{--line:#2a506d;--panel:#0d2233;--panel2:#123149;max-width:1160px;margin:0 auto;padding:0 4px 64px;color:${K.text}}
.hmla-v2 *{box-sizing:border-box}.hmla-v2 button{font:inherit}.hmla-v2 .hero{position:relative;overflow:hidden;border:1px solid var(--line);border-radius:18px;padding:24px 26px;background:radial-gradient(circle at 88% 8%,rgba(96,216,239,.18),transparent 30%),radial-gradient(circle at 8% 100%,rgba(189,156,255,.12),transparent 34%),linear-gradient(135deg,#14344c,#0b1d2b 72%);box-shadow:0 18px 55px rgba(0,0,0,.22)}
.hmla-v2 .hero:after{content:"";position:absolute;inset:auto -80px -100px auto;width:280px;height:280px;border-radius:50%;border:1px solid rgba(255,255,255,.08)}
.hmla-v2 .eyebrow{color:${K.gold};font:800 11px ${K.sans};letter-spacing:1.5px;text-transform:uppercase}.hmla-v2 h1{margin:8px 0 9px;max-width:880px;font:700 clamp(30px,4.4vw,49px)/1.06 ${K.serif};color:${K.text}}.hmla-v2 .hero p{max-width:900px;margin:0;color:${K.dim};font:400 15px/1.65 ${K.sans}}
.hmla-v2 .section{padding:27px 0 2px;border-top:1px solid rgba(96,216,239,.16)}.hmla-v2 .section:first-of-type{border-top:0}.hmla-v2 .section-head{display:flex;gap:10px;align-items:center;margin-bottom:10px}.hmla-v2 .num{width:32px;height:32px;border-radius:10px;display:grid;place-items:center;color:#07131d;font:900 12px ${K.mono};box-shadow:0 6px 20px rgba(0,0,0,.22)}.hmla-v2 h2{margin:0;font:700 clamp(22px,2.8vw,30px)/1.12 ${K.serif};color:${K.text}}.hmla-v2 h3{margin:18px 0 8px;font:700 19px ${K.serif}}
.hmla-v2 p{margin:0 0 10px;color:${K.text};font:400 15px/1.68 ${K.sans}}.hmla-v2 .muted{color:${K.dim}}
.hmla-v2 .grid2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px;align-items:start}.hmla-v2 .grid3{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.hmla-v2 .figure{position:relative;overflow:hidden;border:1px solid var(--line);border-radius:14px;padding:11px;background:radial-gradient(circle at 88% 10%,rgba(96,216,239,.10),transparent 32%),linear-gradient(145deg,#123149,#0b1e2d 76%);box-shadow:0 12px 35px rgba(0,0,0,.18)}.hmla-v2 .figure:before{content:"";position:absolute;inset:0;pointer-events:none;background:linear-gradient(115deg,rgba(255,255,255,.04),transparent 26%,transparent 72%,rgba(255,255,255,.025))}.hmla-v2 .figure-title{position:relative;margin:0 0 7px;color:${K.text};font:800 13px ${K.sans};letter-spacing:.1px}.hmla-v2 .figure-caption{position:relative;margin:7px 2px 0;color:${K.dim};font:400 11.5px/1.48 ${K.sans}}.hmla-v2 .figure svg{position:relative;width:100%;height:auto;display:block;max-height:275px}.hmla-v2 .figure.full svg{max-height:430px}.hmla-v2 .figure.compact svg{max-height:225px}
.hmla-v2 .note{border-left:3px solid currentColor;border-radius:0 10px 10px 0;padding:9px 11px;margin:10px 0;background:rgba(255,255,255,.025);font:400 13.5px/1.55 ${K.sans};color:${K.text}}.hmla-v2 .note b{display:block;margin-bottom:3px;font-size:11px;letter-spacing:.8px;text-transform:uppercase}
.hmla-v2 .table-wrap{overflow:auto;border:1px solid var(--line);border-radius:12px;background:#0b1f2e;margin:10px 0 14px}.hmla-v2 table{border-collapse:collapse;width:100%;font-family:${K.sans}}.hmla-v2 th,.hmla-v2 td{padding:8px 9px;border-bottom:1px solid #23455f;text-align:left;vertical-align:top;font-size:12.5px;line-height:1.4}.hmla-v2 th{position:sticky;top:0;z-index:1;background:#102a3e;color:${K.gold};font-weight:800}.hmla-v2 td{color:${K.dim}}.hmla-v2 td:first-child{color:${K.text};font-weight:650}.hmla-v2 tr:last-child td{border-bottom:0}
.hmla-v2 .law{display:grid;grid-template-columns:1fr auto 1fr;gap:10px;align-items:center;margin:11px 0}.hmla-v2 .lawbox{border:1px solid var(--line);border-radius:12px;padding:12px;background:linear-gradient(145deg,#14334a,#0b1e2d);font:700 15px/1.45 ${K.serif};color:${K.text}}.hmla-v2 .arrow{color:${K.gold};font-size:22px}.hmla-v2 .chiprow{display:flex;flex-wrap:wrap;gap:6px;margin:8px 0}.hmla-v2 .chip{border:1px solid var(--line);border-radius:999px;padding:5px 8px;background:#0b2030;color:${K.dim};font:700 10.5px ${K.sans}}
.hmla-v2 .timeline{display:grid;grid-template-columns:repeat(8,minmax(110px,1fr));gap:6px;min-width:920px}.hmla-v2 .timeline-card{border:1px solid var(--line);border-top:3px solid var(--accent);border-radius:11px;padding:9px;background:linear-gradient(155deg,#143149,#0b1e2d);min-height:88px}.hmla-v2 .timeline-year{color:var(--accent);font:900 10.5px ${K.mono}}.hmla-v2 .timeline-name{color:${K.text};font:700 13px ${K.serif};margin:4px 0}.hmla-v2 .timeline-idea{color:${K.dim};font:400 10.5px/1.35 ${K.sans}}
.hmla-v2 .newlands{min-width:620px}.hmla-v2 .newlands th,.hmla-v2 .newlands td{text-align:center;white-space:nowrap}.hmla-v2 .newlands .note-row td{color:${K.violet};font-weight:800}.hmla-v2 .newlands .match{background:rgba(242,189,72,.09);color:${K.gold};font-weight:800}
.hmla-v2 .mendeleev{min-width:1000px}.hmla-v2 .mendeleev th,.hmla-v2 .mendeleev td{text-align:center;padding:6px 5px;font-size:10.5px;white-space:pre-line}.hmla-v2 .mendeleev td{min-width:88px}.hmla-v2 .mendeleev td.viii{min-width:170px;color:${K.mint}}.hmla-v2 .formula-band{display:grid;grid-template-columns:repeat(8,minmax(78px,1fr));gap:5px;min-width:720px;padding:8px}.hmla-v2 .formula-cell{border:1px solid #294d68;border-radius:8px;padding:7px;text-align:center;background:#10293d;color:${K.cyan};font:700 11px ${K.mono}}
.hmla-v2 .modern-scroll{overflow:auto;padding-bottom:2px}.hmla-v2 .modern-grid{display:grid;grid-template-columns:26px repeat(18,minmax(38px,1fr));grid-template-rows:20px repeat(7,42px);gap:3px;min-width:850px}.hmla-v2 .group-label,.hmla-v2 .period-label{display:grid;place-items:center;color:${K.dim};font:700 9px ${K.sans}}.hmla-v2 .element{position:relative;border:1px solid var(--ec);border-radius:7px;background:linear-gradient(145deg,color-mix(in srgb,var(--ec) 18%,#10283a),#0b1f2e);color:var(--ec);cursor:pointer;box-shadow:inset 0 1px rgba(255,255,255,.08);font-family:${K.mono}}.hmla-v2 .element:hover{transform:translateY(-1px);filter:brightness(1.18)}.hmla-v2 .element .z{position:absolute;top:2px;left:3px;color:${K.dim};font-size:7px}.hmla-v2 .element b{font-size:13px}.hmla-v2 .frow{display:grid;grid-template-columns:70px repeat(15,minmax(38px,1fr));gap:3px;min-width:850px;margin-top:3px}.hmla-v2 .frow-label{display:grid;place-items:center;color:${K.f};font:800 9px ${K.sans}}.hmla-v2 .selected{margin-top:8px;border:1px solid var(--ec);border-radius:10px;padding:9px 11px;background:#0b2030;display:flex;gap:10px;align-items:center}.hmla-v2 .selected .symbol{width:48px;height:48px;border:2px solid var(--ec);border-radius:10px;display:grid;place-items:center;color:var(--ec);font:900 20px ${K.mono}}.hmla-v2 .selected strong{display:block;color:${K.text};font:700 15px ${K.serif}}.hmla-v2 .selected span{color:${K.dim};font:400 11.5px ${K.sans}}
.hmla-v2 .facts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.hmla-v2 .fact{border:1px solid var(--line);border-radius:10px;padding:9px 10px;background:#0b2030;color:${K.dim};font:400 12.5px/1.45 ${K.sans}}.hmla-v2 .fact b{color:${K.text}}
@media(max-width:820px){.hmla-v2 .grid2,.hmla-v2 .grid3,.hmla-v2 .facts{grid-template-columns:1fr}.hmla-v2 .hero{padding:20px}.hmla-v2 .law{grid-template-columns:1fr}.hmla-v2 .arrow{transform:rotate(90deg);text-align:center}.hmla-v2 .figure svg{max-height:none}.hmla-v2 .section{padding-top:23px}}
`;

function Section({n,title,accent="gold",children}:{n:number;title:string;accent?:Accent;children:React.ReactNode}){const c=A[accent];return <section className="section"><div className="section-head"><span className="num" style={{background:c}}>{n}</span><h2>{title}</h2></div>{children}</section>}
function Figure({title,caption,children,full=false,compact=false}:{title:string;caption?:string;children:React.ReactNode;full?:boolean;compact?:boolean}){return <figure className={`figure${full?" full":""}${compact?" compact":""}`}><figcaption className="figure-title">{title}</figcaption>{children}{caption&&<div className="figure-caption">{caption}</div>}</figure>}
function Note({title,children,color=K.cyan}:{title:string;children:React.ReactNode;color?:string}){return <div className="note" style={{color}}><b style={{color}}>{title}</b><span style={{color:K.text}}>{children}</span></div>}
function DataTable({headers,rows,min=620}:{headers:string[];rows:React.ReactNode[][];min?:number}){return <div className="table-wrap"><table style={{minWidth:min}}><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>}

const timeline=[
  ["1789","Lavoisier","broad classes","coral"],["1817–29","Döbereiner","triads","gold"],["1862","de Chancourtois","telluric screw","violet"],["1865","Newlands","octaves","cyan"],["1869","Lothar Meyer","periodic curves","mint"],["1869–71","Mendeleev","prediction","gold"],["1913","Moseley","atomic number","cyan"],["1944 onward","Seaborg","actinoid concept","violet"],
] as [string,string,string,Accent][];

function ClassificationMini(){return <svg viewBox="0 0 600 210" role="img" aria-label="Classification transforms isolated facts into families trends and predictions"><defs><linearGradient id="funnel" x1="0" x2="1"><stop stopColor={K.cyan}/><stop offset=".5" stopColor={K.violet}/><stop offset="1" stopColor={K.gold}/></linearGradient><filter id="glow"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>{Array.from({length:18},(_,i)=><circle key={i} cx={35+(i%6)*30} cy={42+Math.floor(i/6)*45} r={6+(i%3)} fill={[K.gold,K.cyan,K.mint,K.violet,K.coral][i%5]} opacity=".9"/>)}<text x="105" y="185" fill={K.dim} textAnchor="middle" fontFamily={K.sans} fontSize="13">isolated facts</text><path d="M215 105H292" stroke="url(#funnel)" strokeWidth="7" strokeLinecap="round"/><path d="M288 88L315 105L288 122Z" fill={K.violet}/><circle cx="390" cy="105" r="70" fill="#14364f" stroke={K.cyan} strokeWidth="3" filter="url(#glow)"/><text x="390" y="82" fill={K.gold} textAnchor="middle" fontFamily={K.sans} fontWeight="800" fontSize="17">families</text><text x="390" y="108" fill={K.mint} textAnchor="middle" fontFamily={K.sans} fontWeight="800" fontSize="17">trends</text><text x="390" y="134" fill={K.violet} textAnchor="middle" fontFamily={K.sans} fontWeight="800" fontSize="17">predictions</text><path d="M464 105H535" stroke={K.gold} strokeWidth="6" strokeLinecap="round"/><path d="M530 89L558 105L530 121Z" fill={K.gold}/><text x="548" y="82" fill={K.gold} textAnchor="middle" fontFamily={K.sans} fontWeight="800" fontSize="13">unknown</text><text x="548" y="145" fill={K.text} textAnchor="middle" fontFamily={K.sans} fontSize="12">becomes testable</text></svg>}

function TriadCompact(){return <svg viewBox="0 0 520 230" role="img" aria-label="Döbereiner triad arithmetic and chemical similarity"><defs><linearGradient id="beam" x1="0" x2="1"><stop stopColor={K.cyan}/><stop offset=".5" stopColor={K.gold}/><stop offset="1" stopColor={K.coral}/></linearGradient></defs><line x1="75" x2="445" y1="126" y2="126" stroke="url(#beam)" strokeWidth="6" strokeLinecap="round"/>{[["Li","7",120,K.cyan],["Na","23",260,K.gold],["K","39",400,K.coral]].map(([s,m,x,c])=><g key={String(s)}><circle cx={Number(x)} cy="92" r={41} fill="#143149" stroke={String(c)} strokeWidth="3"/><text x={Number(x)} y="89" fill={String(c)} textAnchor="middle" fontFamily={K.mono} fontSize="21" fontWeight="900">{s}</text><text x={Number(x)} y="111" fill={K.dim} textAnchor="middle" fontFamily={K.sans} fontSize="11">A ≈ {m}</text></g>)}<path d="M260 126V183" stroke={K.gold} strokeWidth="5"/><path d="M230 183H290L260 218Z" fill={K.gold}/><text x="260" y="158" fill={K.text} textAnchor="middle" fontFamily={K.mono} fontSize="15">(7 + 39) / 2 = 23</text></svg>}

function TelluricScrew(){const labs=["H","Li","Be","B","C","N","O","F","Na","Mg","Al","Si","P","S","Cl","K","Ca"];return <svg viewBox="0 0 520 270" role="img" aria-label="de Chancourtois telluric screw original teaching diagram"><defs><linearGradient id="cyl" x1="0" x2="1"><stop stopColor="#0b1d2c"/><stop offset=".5" stopColor="#26516f"/><stop offset="1" stopColor="#0b1d2c"/></linearGradient></defs><ellipse cx="260" cy="35" rx="122" ry="25" fill="#173b55" stroke={K.cyan}/><rect x="138" y="35" width="244" height="188" fill="url(#cyl)" stroke={K.cyan}/><ellipse cx="260" cy="223" rx="122" ry="25" fill="#0b1f2e" stroke={K.cyan}/><path d="M145 42C370 65 150 89 375 112C150 136 370 159 145 183C370 206 150 225 375 244" fill="none" stroke={K.mint} strokeWidth="3"/>{labs.map((lab,i)=>{const t=i/(labs.length-1),x=260+112*Math.sin(t*Math.PI*6),y=44+t*190;return <g key={lab}><circle cx={x} cy={y} r="8" fill="#0c2030" stroke={i%2?K.gold:K.violet}/><text x={x} y={y+3} fill={K.text} textAnchor="middle" fontFamily={K.mono} fontSize="7.5">{lab}</text></g>})}<text x="260" y="261" fill={K.dim} textAnchor="middle" fontFamily={K.sans} fontSize="11">~16 mass-unit circumference</text></svg>}

const meyerPoints=[
  [7,13.1,"Li","a"],[9,4.9,"Be","e"],[11,4.6,"B","m"],[12,5.3,"C","m"],[23,23.7,"Na","a"],[24.3,14.0,"Mg","e"],[27,10.0,"Al","m"],[28.1,12.1,"Si","m"],[31,17.0,"P","r"],[32.1,15.5,"S","r"],[35.5,22.7,"Cl","h"],[39.1,45.4,"K","a"],[40.1,25.9,"Ca","e"],[45,15.0,"Sc","m"],[47.9,10.6,"Ti","m"],[50.9,8.3,"V","m"],[52,7.2,"Cr","m"],[54.9,7.4,"Mn","m"],[55.9,7.1,"Fe","m"],[58.9,6.7,"Co","m"],[58.7,6.6,"Ni","m"],[63.5,7.1,"Cu","m"],[65.4,9.2,"Zn","m"],[69.7,11.8,"Ga","r"],[72.6,13.6,"Ge","r"],[74.9,13.1,"As","r"],[79,16.4,"Se","r"],[79.9,19.8,"Br","h"],[85.5,55.9,"Rb","a"],[87.6,33.7,"Sr","e"],[88.9,19.9,"Y","m"],[91.2,14.1,"Zr","m"],[92.9,10.8,"Nb","m"],[95.9,9.4,"Mo","m"],[101.1,8.3,"Ru","m"],[102.9,8.3,"Rh","m"],[106.4,8.9,"Pd","m"],[107.9,10.3,"Ag","m"],[112.4,13.0,"Cd","m"],[114.8,15.7,"In","r"],[118.7,16.3,"Sn","r"],[121.8,18.2,"Sb","r"],[126.9,25.7,"I","h"],[127.6,20.5,"Te","r"],[132.9,70.9,"Cs","a"],[137.3,39.2,"Ba","e"],
] as [number,number,string,string][];
function MeyerGraph(){const W=980,H=420,L=66,R=24,T=34,B=55,x=(m:number)=>L+(m/145)*(W-L-R),y=(v:number)=>H-B-(v/75)*(H-T-B),d=meyerPoints.map((p,i)=>`${i?"L":"M"}${x(p[0]).toFixed(1)},${y(p[1]).toFixed(1)}`).join(" "),col=(f:string)=>f==="a"?K.gold:f==="e"?K.cyan:f==="h"?K.violet:f==="m"?K.mint:K.coral;return <svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="NCERT aligned original reconstruction of Lothar Meyer atomic volume curve"><defs><linearGradient id="meyerLine" x1="0" x2="1"><stop stopColor={K.gold}/><stop offset=".45" stopColor={K.mint}/><stop offset=".75" stopColor={K.cyan}/><stop offset="1" stopColor={K.violet}/></linearGradient><filter id="meyerGlow"><feGaussianBlur stdDeviation="2.2" result="g"/><feMerge><feMergeNode in="g"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>{[0,15,30,45,60,75].map(v=><g key={v}><line x1={L} x2={W-R} y1={y(v)} y2={y(v)} stroke="#254b66" strokeDasharray="3 7"/><text x={L-9} y={y(v)+4} fill={K.dim} textAnchor="end" fontFamily={K.mono} fontSize="9">{v}</text></g>)}{[0,20,40,60,80,100,120,140].map(m=><g key={m}><text x={x(m)} y={H-B+18} fill={K.dim} textAnchor="middle" fontFamily={K.mono} fontSize="9">{m}</text></g>)}<line x1={L} x2={W-R} y1={H-B} y2={H-B} stroke={K.dim}/><line x1={L} x2={L} y1={T} y2={H-B} stroke={K.dim}/><path d={d} fill="none" stroke="url(#meyerLine)" strokeWidth="3.2" filter="url(#meyerGlow)"/>{meyerPoints.map(([m,v,s,f])=><g key={`${s}-${m}`}><circle cx={x(m)} cy={y(v)} r={f==="a"?4.5:2.6} fill={col(f)} stroke="#07131d" strokeWidth="1.3"/><text x={x(m)} y={y(v)-(f==="a"?8:5)} fill={col(f)} textAnchor="middle" fontFamily={K.mono} fontSize={f==="a"?9.5:7.2} fontWeight={f==="a"?800:600}>{s}</text></g>)}<text x={W/2} y={H-11} fill={K.text} textAnchor="middle" fontFamily={K.sans} fontSize="12">relative atomic mass →</text><text x="18" y={H/2} fill={K.text} textAnchor="middle" fontFamily={K.sans} fontSize="12" transform={`rotate(-90 18 ${H/2})`}>atomic volume / cm³ mol⁻¹</text><text x={x(39.1)} y={y(45.4)-26} fill={K.gold} textAnchor="middle" fontFamily={K.sans} fontSize="10" fontWeight="800">alkali peak</text><text x={x(59)} y={y(6.6)+30} fill={K.mint} textAnchor="middle" fontFamily={K.sans} fontSize="10" fontWeight="800">transition minimum</text><text x={x(127)} y={y(25.7)-22} fill={K.violet} textAnchor="middle" fontFamily={K.sans} fontSize="10" fontWeight="800">halogen-side rise</text></svg>}

const mRows:[string,Record<string,string>][]=[
  ["1",{"I":"H\n1.008"}],
  ["2",{"0":"He\n4.0","I":"Li\n7.03","II":"Be\n9.1","III":"B\n11.0","IV":"C\n12.0","V":"N\n14.04","VI":"O\n16.00","VII":"F\n19.0"}],
  ["3",{"0":"Ne\n19.9","I":"Na\n23.05","II":"Mg\n24.3","III":"Al\n27.0","IV":"Si\n28.4","V":"P\n31.0","VI":"S\n32.06","VII":"Cl\n35.45"}],
  ["4",{"0":"Ar\n38","I":"K\n39.1","II":"Ca\n40.1","III":"Sc\n44.1","IV":"Ti\n48.1","V":"V\n51.4","VI":"Cr\n52.1","VII":"Mn\n55.0","VIII":"Fe 55.9 · Co 59 · Ni 59"}],
  ["5",{"I":"Cu\n63.6","II":"Zn\n65.4","III":"Ga\n70.0","IV":"Ge\n72.3","V":"As\n75","VI":"Se\n79","VII":"Br\n79.95"}],
  ["6",{"0":"Kr\n81.8","I":"Rb\n85.4","II":"Sr\n87.6","III":"Y\n89.0","IV":"Zr\n90.6","V":"Nb\n94","VI":"Mo\n96","VII":"—","VIII":"Ru 101.7 · Rh 103.0 · Pd 106.5"}],
  ["7",{"I":"Ag\n107.9","II":"Cd\n112.4","III":"In\n114.0","IV":"Sn\n118.0","V":"Sb\n120.0","VI":"Te\n127.6","VII":"I\n126.9"}],
  ["8",{"0":"Xe\n128","I":"Cs\n132.9","II":"Ba\n137.4","III":"La\n139","IV":"Ce\n140","V":"Ta\n183","VI":"W\n184","VII":"—","VIII":"Os 191 · Ir 193 · Pt 194.9"}],
  ["9",{"I":"Au\n197.2","II":"Hg\n200.0","III":"Tl\n204.1","IV":"Pb\n206.9","V":"Bi\n208"}],
  ["10",{"II":"Ra\n224","IV":"Th\n232","VI":"U\n238"}],
  ["11",{}],["12",{}],
];
function MendeleevTable(){const groups=["0","I","II","III","IV","V","VI","VII","VIII"];return <><div className="table-wrap"><table className="mendeleev"><thead><tr><th>Series</th>{groups.map(g=><th key={g}>Group {g}</th>)}</tr></thead><tbody>{mRows.map(([s,c])=><tr key={s}><td>{s}</td>{groups.map(g=><td key={g} className={g==="VIII"?"viii":""}>{c[g]||""}</td>)}</tr>)}</tbody></table></div><div className="table-wrap"><div className="formula-band">{[["I","R₂O · RH"],["II","RO · RH₂"],["III","R₂O₃ · RH₃"],["IV","RO₂ · RH₄"],["V","R₂O₅ · RH₃"],["VI","RO₃ · RH₂"],["VII","R₂O₇ · RH"],["VIII","variable oxides"]].map(([g,f])=><div className="formula-cell" key={g}><b style={{color:K.gold}}>G {g}</b><br/>{f}</div>)}</div></div></>}

function AnomalousPairs(){const pairs=[["Ar 39.95","K 39.10","18 < 19"],["Co 58.93","Ni 58.69","27 < 28"],["Te 127.60","I 126.90","52 < 53"]];return <svg viewBox="0 0 580 250" role="img" aria-label="Atomic number resolves anomalous mass pairs"><defs><marker id="pairArrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill={K.gold}/></marker></defs>{pairs.map(([a,b,z],i)=>{const y=48+i*70;return <g key={a}><rect x="25" y={y-26} width="205" height="48" rx="11" fill="#143149" stroke={K.coral}/><text x="127" y={y+4} fill={K.text} textAnchor="middle" fontFamily={K.mono} fontSize="13" fontWeight="700">{a} → {b}</text><path d={`M245 ${y-2}H325`} stroke={K.gold} strokeWidth="4" markerEnd="url(#pairArrow)"/><rect x="345" y={y-26} width="205" height="48" rx="11" fill="#143149" stroke={K.mint}/><text x="447" y={y+4} fill={K.mint} textAnchor="middle" fontFamily={K.mono} fontSize="15" fontWeight="800">Z: {z}</text></g>})}</svg>}

function MoseleyExperiment(){return <svg viewBox="0 0 560 245" role="img" aria-label="Moseley characteristic X-ray experiment"><defs><marker id="beamA" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill={K.cyan}/></marker></defs><rect x="25" y="83" width="110" height="65" rx="14" fill="#143149" stroke={K.cyan} strokeWidth="2"/><text x="80" y="112" fill={K.cyan} textAnchor="middle" fontFamily={K.sans} fontWeight="800" fontSize="14">electron gun</text><text x="80" y="133" fill={K.text} textAnchor="middle" fontFamily={K.sans} fontSize="10">fast e⁻ beam</text><path d="M140 116H235" stroke={K.cyan} strokeWidth="5" markerEnd="url(#beamA)"/><rect x="235" y="67" width="82" height="98" rx="12" fill="#4a2b31" stroke={K.coral} strokeWidth="3" transform="rotate(10 276 116)"/><text x="276" y="119" fill={K.coral} textAnchor="middle" fontFamily={K.sans} fontWeight="800" fontSize="13" transform="rotate(10 276 116)">metal target</text><path d="M317 116L405 62M317 116L405 116M317 116L405 174" stroke={K.gold} strokeWidth="3"/><path d="M408 50L468 116L408 182Z" fill="#143149" stroke={K.gold} strokeWidth="3"/><text x="426" y="120" fill={K.gold} fontFamily={K.sans} fontWeight="800" fontSize="12">crystal</text><path d="M470 116Q515 78 542 48M470 116Q515 155 542 190" stroke={K.violet} strokeWidth="3" fill="none"/><text x="520" y="31" fill={K.gold} textAnchor="middle" fontFamily={K.sans} fontSize="11">detector</text><text x="520" y="218" fill={K.violet} textAnchor="middle" fontFamily={K.sans} fontSize="11">detector</text></svg>}
function MoseleyGraph(){const W=560,H=245,L=53,R=20,T=32,B=45,pts=[20,25,30,35,40,45,50,55,60,65,70].map(z=>({z,v:.62*z-7})),x=(z:number)=>L+((z-18)/55)*(W-L-R),y=(v:number)=>H-B-((v-3)/38)*(H-T-B),d=pts.map((p,i)=>`${i?"L":"M"}${x(p.z)},${y(p.v)}`).join(" ");return <svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Moseley graph square root frequency versus atomic number"><defs><filter id="lineGlow"><feGaussianBlur stdDeviation="2" result="g"/><feMerge><feMergeNode in="g"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><line x1={L} x2={W-R} y1={H-B} y2={H-B} stroke={K.dim}/><line x1={L} x2={L} y1={T} y2={H-B} stroke={K.dim}/><path d={d} fill="none" stroke={K.gold} strokeWidth="4" filter="url(#lineGlow)"/>{pts.map((p,i)=><circle key={p.z} cx={x(p.z)} cy={y(p.v)} r="5" fill={i%2?K.mint:K.cyan} stroke="#07131d" strokeWidth="2"/>)}<text x={W-155} y="48" fill={K.gold} textAnchor="middle" fontFamily={K.serif} fontSize="21" fontWeight="800">√ν = a(Z − b)</text><text x={W/2} y={H-10} fill={K.text} textAnchor="middle" fontFamily={K.sans} fontSize="11">atomic number, Z →</text><text x="16" y={H/2} fill={K.text} textAnchor="middle" fontFamily={K.sans} fontSize="11" transform={`rotate(-90 16 ${H/2})`}>√ν</text></svg>}

function ModernTable(){const [sel,setSel]=useState<E|null>(null),main=ELEMENTS.filter(e=>e.block!=="f"),f=ELEMENTS.filter(e=>e.block==="f");return <div><div className="modern-scroll"><div className="modern-grid">{Array.from({length:18},(_,i)=><div className="group-label" key={i} style={{gridColumn:i+2,gridRow:1}}>{i+1}</div>)}{Array.from({length:7},(_,i)=><div className="period-label" key={i} style={{gridColumn:1,gridRow:i+2}}>{i+1}</div>)}{main.map(e=><button className="element" key={e.z} onClick={()=>setSel(e)} aria-label={`${e.name}, atomic number ${e.z}`} style={{gridColumn:e.group+1,gridRow:e.period+1,"--ec":BC[e.block]} as React.CSSProperties}><span className="z">{e.z}</span><b>{e.symbol}</b></button>)}<button className="element" onClick={()=>setSel(ELEMENTS[56])} style={{gridColumn:4,gridRow:7,"--ec":K.f} as React.CSSProperties}>57–71</button><button className="element" onClick={()=>setSel(ELEMENTS[88])} style={{gridColumn:4,gridRow:8,"--ec":K.f} as React.CSSProperties}>89–103</button></div>{[f.slice(0,15),f.slice(15)].map((row,i)=><div className="frow" key={i}><div className="frow-label">{i?"Actinoids":"Lanthanoids"}</div>{row.map(e=><button className="element" key={e.z} onClick={()=>setSel(e)} style={{height:40,"--ec":K.f} as React.CSSProperties}><span className="z">{e.z}</span><b>{e.symbol}</b></button>)}</div>)}</div>{sel&&<div className="selected" style={{"--ec":BC[sel.block]} as React.CSSProperties}><div className="symbol">{sel.symbol}</div><div><strong>{sel.name}</strong><span>Z = {sel.z} · Period {sel.period} · Group {sel.group} · {sel.block}-block</span></div><button onClick={()=>setSel(null)} style={{marginLeft:"auto",border:`1px solid ${K.line}`,borderRadius:8,padding:"5px 8px",background:"transparent",color:K.dim,cursor:"pointer"}}>Close</button></div>}</div>}

export default function HistoryModernLawAuthority(){const [showClinic,setShowClinic]=useState(false);return <div className="hmla-v2" data-implementation="history-modern-law-authority-v2"><style>{css}</style><span style={{display:"none"}}>history-modern-law-authority-v2</span>
<header className="hero"><div className="eyebrow">History, periodic law and modern architecture</div><h1>From scattered facts to a predictive periodic system</h1><p>Compact NCERT-aligned theory, verified historical examples and original glossy scientific visuals—without oversized decorative cards or duplicated content from the other chapter tabs.</p></header>

<Section n={1} title="Why classification became necessary" accent="gold"><div className="grid2"><div><p>As the number of known elements grew, studying each element and its compounds as unrelated facts became impractical. A useful classification had to group chemically similar elements, reveal recurrence, permit comparison and support prediction.</p><div className="facts"><div className="fact"><b>1800:</b> about 31 elements were known.</div><div className="fact"><b>1865:</b> the count had risen to 63.</div><div className="fact"><b>Periodicity:</b> recurrence of related properties at regular stages.</div><div className="fact"><b>Modern cause:</b> recurring valence-shell configurations.</div></div></div><Figure title="Classification as scientific compression" compact><ClassificationMini/></Figure></div><div className="table-wrap" style={{marginTop:12}}><div style={{overflowX:"auto",padding:8}}><div className="timeline">{timeline.map(([y,n,idea,a])=><div className="timeline-card" key={y} style={{"--accent":A[a]} as React.CSSProperties}><div className="timeline-year">{y}</div><div className="timeline-name">{n}</div><div className="timeline-idea">{idea}</div></div>)}</div></div></div></Section>

<Section n={2} title="Early numerical patterns: triads and the telluric screw" accent="mint"><div className="grid2"><div><p><b>Döbereiner’s Law of Triads:</b> for three chemically similar elements arranged by increasing atomic mass, the mass and properties of the middle member are approximately intermediate.</p><Figure title="Triad test: arithmetic plus chemical resemblance" compact><TriadCompact/></Figure><DataTable headers={["Triad","Masses","Mean test"]} rows={[["Li–Na–K","7, 23, 39","23"],["Ca–Sr–Ba","40, 88, 137","88.5 ≈ 88"],["Cl–Br–I","35.5, 80, 127","81.25 ≈ 80"]]} min={420}/><Note title="Do not use the shortcut as the law" color={K.coral}>Equal atomic-number spacing is a modern recognition aid; Döbereiner’s original criterion used approximate atomic masses and chemical similarity.</Note></div><div><p><b>de Chancourtois (1862):</b> elements were placed in increasing atomic-weight order along a helix on a cylinder. Vertical approaches suggested recurrence.</p><Figure title="Telluric screw — original reconstruction" caption="The geometry displayed recurrence, but it was difficult to read and did not align heavier families consistently." compact><TelluricScrew/></Figure><Note title="Parallel numerical proposals" color={K.violet}>Prout’s whole-number hypothesis and Pettenkofer’s multiples-of-eight observation were suggestive but not universal classification laws.</Note></div></div></Section>

<Section n={3} title="Newlands’ Law of Octaves — corrected NCERT sequence" accent="cyan"><p>Newlands arranged elements by increasing atomic weight and observed that every eighth element resembled the first, like the recurrence of a musical note after seven intervening notes.</p><div className="table-wrap"><table className="newlands"><tbody><tr className="note-row"><td>Musical cue</td>{["Sa","Re","Ga","Ma","Pa","Dha","Ni"].map(x=><td key={x}>{x}</td>)}</tr><tr><td>Elements</td>{[["Li","7"],["Be","9"],["B","11"],["C","12"],["N","14"],["O","16"],["F","19"]].map(([s,m],i)=><td className={i<2?"match":""} key={s}><b>{s}</b><br/><span className="muted">{m}</span></td>)}</tr><tr><td>Next octave</td>{[["Na","23"],["Mg","24"],["Al","27"],["Si","29"],["P","31"],["S","32"],["Cl","35.5"]].map(([s,m],i)=><td className={i<2?"match":""} key={s}><b>{s}</b><br/><span className="muted">{m}</span></td>)}</tr><tr><td>Following</td><td><b>K</b><br/><span className="muted">39</span></td><td><b>Ca</b><br/><span className="muted">40</span></td>{Array.from({length:5},(_,i)=><td key={i}></td>)}</tr></tbody></table></div><div className="grid2"><Note title="What works" color={K.mint}>Li resembles Na; Be resembles Mg. The relation was meaningful for several light elements.</Note><Note title="Why it failed" color={K.coral}>It worked mainly up to Ca, left no reliable gaps, forced some unlike elements together and was disrupted when noble gases were inserted.</Note></div></Section>

<Section n={4} title="Lothar Meyer’s periodic curves" accent="gold"><p>Working independently in 1869, Lothar Meyer showed that physical properties vary periodically with atomic weight. NCERT specifically identifies atomic volume, melting point and boiling point as plotted properties. The graph below is an original, detailed atomic-volume reconstruction rather than a copied source figure.</p><Figure title="Atomic volume versus relative atomic mass — NCERT-aligned reconstruction" caption="Sharp peaks: alkali metals; descending branches: alkaline-earth metals; broad minima: transition regions; rising branches: halogen side. Atomic volume is molar mass divided by density when compatible units are used." full><MeyerGraph/></Figure><div className="chiprow"><span className="chip" style={{color:K.gold}}>peaks · Li, Na, K, Rb, Cs</span><span className="chip" style={{color:K.cyan}}>descent · Be, Mg, Ca, Sr, Ba</span><span className="chip" style={{color:K.mint}}>minima · transition region</span><span className="chip" style={{color:K.violet}}>rise · F, Cl, Br, I side</span></div></Section>

<Section n={5} title="Mendeleev’s periodic law and NCERT historical table" accent="violet"><div className="law"><div className="lawbox" style={{borderColor:K.violet}}>Properties of elements are periodic functions of their atomic weights.</div><div className="arrow">→</div><div><p>Mendeleev used atomic weight together with valency, empirical formulae and chemical resemblance. Where strict mass order conflicted with chemistry, similarity received priority.</p></div></div><Figure title="Mendeleev’s table — NCERT Fig. 3.1 aligned teaching reconstruction" caption="Groups 0–VIII and series are preserved; historical atomic weights are rounded. This is newly composed and not a scan or facsimile." full><MendeleevTable/></Figure><h3 style={{color:K.gold}}>Why the table succeeded</h3><DataTable headers={["Achievement","Scientific value"]} rows={[["Systematic grouping","Similar elements became comparable as families."],["Deliberate gaps","Unknown elements could be predicted instead of forcing a poor fit."],["Chemical priority","Te was placed with Se and I with the halogens despite mass order."],["Correction of data","Periodic position helped reconsider doubtful atomic weights and valencies."],["Noble gases","A new group could later be added without destroying the arrangement."]]} min={680}/><h3 style={{color:K.cyan}}>NCERT prediction comparison</h3><DataTable headers={["Property","Eka-Al predicted","Gallium found","Eka-Si predicted","Germanium found"]} rows={[["Atomic weight","68","70","72","72.6"],["Density / g cm⁻³","5.9","5.94","5.5","5.36"],["Melting point / K","low","302.93","high","1231"],["Oxide","E₂O₃","Ga₂O₃","EO₂","GeO₂"],["Chloride","ECl₃","GaCl₃","ECl₄","GeCl₄"]]} min={820}/><Note title="Classic third confirmation" color={K.mint}>Scandium confirmed the eka-boron position; NCERT’s quantitative comparison table focuses on gallium and germanium.</Note></Section>

<Section n={6} title="Limits of mass order and the Moseley resolution" accent="coral"><div className="grid2"><div><p>Mendeleev’s arrangement could not explain isotopes, hydrogen’s dual resemblance or why some mass pairs had to be reversed. Atomic number resolves the order exactly.</p><Figure title="Anomalous mass pairs resolved by Z" compact><AnomalousPairs/></Figure><DataTable headers={["Mass-based problem","Atomic-number solution"]} rows={[["Ar before K despite 39.95 > 39.10","Z: 18 < 19"],["Co before Ni despite 58.93 > 58.69","Z: 27 < 28"],["Te before I despite 127.60 > 126.90","Z: 52 < 53"]]} min={500}/></div><div><p>In 1913, Moseley studied characteristic X-rays. A plot of √ν against atomic number gave a straight line, establishing Z as the fundamental ordering variable.</p><Figure title="Characteristic X-ray experiment" compact><MoseleyExperiment/></Figure><Figure title="Moseley relation" compact><MoseleyGraph/></Figure></div></div><div className="law"><div className="lawbox" style={{borderColor:K.violet}}>Mendeleev: periodic function of atomic weight</div><div className="arrow">→</div><div className="lawbox" style={{borderColor:K.cyan}}>Modern law: physical and chemical properties are periodic functions of atomic number</div></div></Section>

<Section n={7} title="Modern long-form periodic table" accent="mint"><p>The present long form arranges elements by increasing atomic number into seven periods and eighteen IUPAC groups. The lanthanoid and actinoid series belong within periods 6 and 7 but are displayed below to keep the table compact.</p><div className="chiprow">{[2,8,8,18,18,32,32].map((n,i)=><span className="chip" key={i} style={{color:[K.gold,K.cyan,K.violet,K.mint][i%4]}}>Period {i+1}: {n} elements</span>)}</div><Figure title="Live 118-element long form — click any element" caption="Colour indicates differentiating block; helium is electronically s-block but placed in Group 18 because of its chemistry." full><ModernTable/></Figure><DataTable headers={["Block","General differentiating pattern","Location"]} rows={[["s","ns¹–²","Groups 1–2; He is in Group 18"],["p","ns²np¹–⁶","Groups 13–18"],["d","(n−1)d¹–¹⁰ns⁰–²","Groups 3–12"],["f","(n−2)f⁰–¹⁴(n−1)d⁰–²ns²","inner-transition portions of periods 6 and 7"]]} min={690}/></Section>

<Section n={8} title="High-yield facts, mnemonics and verified reasoning" accent="gold"><div className="grid3">{[["Pattern ladder","triads → helix → octaves → curves → predictive table → atomic number"],["Newlands cue","Sa–Re–Ga–Ma–Pa–Dha–Ni; the next Sa begins the next octave"],["Meyer map","alkali peak → alkaline-earth descent → transition minimum → halogen-side rise"],["Mendeleev key","chemical similarity and compound formulae could override rigid mass order"],["Moseley key","√ν versus Z is linear; Z is the fundamental ordering variable"],["Modern cause","recurrence of outer electronic configurations produces periodic families"]].map(([a,b],i)=><div className="fact" key={a} style={{borderTop:`3px solid ${[K.gold,K.cyan,K.violet,K.mint,K.coral,K.cyan][i]}`}}><b>{a}</b><br/>{b}</div>)}</div><h3 style={{color:K.gold}}>Worked reasoning</h3><DataTable headers={["Task","Resolution"]} rows={[["Test Ca–Sr–Ba","(40 + 137)/2 = 88.5 ≈ 88, and all three are chemically similar."],["Why leave a gap below Si?","Neighbouring group chemistry predicted valency, oxide and chloride formulae; the blank was experimentally testable."],["Why place Te before I?","Their chemistry required Te with Group VI and I with halogens; atomic number later gave Z = 52 then 53."],["Why periods have unequal lengths","Actual lengths follow the subshells filled between successive noble gases, not a fixed octave."]]} min={720}/><button type="button" onClick={()=>setShowClinic(v=>!v)} style={{border:`1px solid ${K.gold}`,borderRadius:9,padding:"8px 11px",background:`${K.gold}12`,color:K.gold,font:`800 11px ${K.sans}`,cursor:"pointer"}}>{showClinic?"Hide misconception clinic":"Open misconception clinic"}</button>{showClinic&&<DataTable headers={["Incorrect claim","Correction"]} rows={[["Every eighth element works throughout the table.","Newlands’ relation was mainly successful only up to calcium."],["Lothar Meyer and Mendeleev made the same contribution.","Meyer demonstrated periodic physical curves; Mendeleev produced a chemically predictive table."],["Mendeleev followed atomic mass without deviation.","He prioritized chemical similarity when the two conflicted."],["The f-block creates extra periods.","It is part of periods 6 and 7."]]} min={720}/>}</Section>

<div style={{marginTop:26,textAlign:"center",color:K.dim,font:`400 10.5px/1.5 ${K.sans}`}}>Original Synergic Bond implementation · history-modern-law-authority-v2 · compact glossy rebuild · no source artwork embedded</div>
</div>}
