// Hydrocarbons — Alkanes, Alkenes, Alkynes and Aromatic Hydrocarbons.
// Massively expanded with full step-by-step mechanisms, derivations, quantitative
// examples, and a 25-question JEE Advanced/NEET bank. Builds directly on GOC.

export type HydrocarbonBlockKind =
  | "major"
  | "section"
  | "subheading"
  | "callout"
  | "bullets"
  | "numbered"
  | "table"
  | "formula"
  | "paragraph";

export type HydrocarbonBlock = {
  kind: HydrocarbonBlockKind;
  text?: string;
  items?: string[];
  headers?: string[];
  rows?: string[][];
  formulaLabel?: string;
};

const sections = [
  "Alkanes: Preparation",
  "Alkanes: Free-Radical Halogenation",
  "Alkanes: Combustion, Pyrolysis and Conformations",
  "Alkenes: Preparation and the Two Elimination Mechanisms",
  "Alkenes: Electrophilic Addition — Mechanisms and Regiochemistry",
  "Alkenes: Oxidative Cleavage and Structural Identification",
  "Alkynes: Preparation and Acidity",
  "Alkynes: Addition Reactions",
  "Aromatic Hydrocarbons: EAS Mechanism",
  "Aromatic Hydrocarbons: The Five Named EAS Reactions",
  "Directing Effects: Multi-Substituent Problems",
  "JEE Advanced Question Bank",
];

export const hydrocarbonChapterMap: string[] = [...sections];

function major(n: number): HydrocarbonBlock {
  return { kind: "major", text: `Section ${n} - ${sections[n - 1]}` };
}
function sub(text: string): HydrocarbonBlock { return { kind: "subheading", text }; }
function p(text: string): HydrocarbonBlock { return { kind: "paragraph", text }; }
function callout(label: string, text: string): HydrocarbonBlock {
  return { kind: "callout", text: `${label}: ${text}` };
}
function bullets(items: string[]): HydrocarbonBlock { return { kind: "bullets", items }; }
function numbered(items: string[]): HydrocarbonBlock { return { kind: "numbered", items }; }
function table(headers: string[], rows: string[][]): HydrocarbonBlock {
  return { kind: "table", headers, rows };
}
function formula(text: string, formulaLabel?: string): HydrocarbonBlock {
  return { kind: "formula", text, formulaLabel };
}

export const hydrocarbonBlocks: HydrocarbonBlock[] = [

  // ── Section 1 ─────────────────────────────────────────────────────────────
  major(1),
  p("Alkane synthesis routes divide into four mechanistically distinct categories. Choosing the right method requires understanding both the mechanism and the structural limitations — which is exactly where JEE problems insert traps."),
  table(
    ["Method", "Reaction", "Mechanism and key limitation"],
    [
      ["Wurtz reaction", "2 R-X + 2Na → R-R + 2NaX (dry ether, reflux)", "Two-electron reduction by Na metal: each Na donates one electron to R-X, generating R• radicals that couple to R-R. Only symmetric alkanes (same R on both halides) give a single clean product; mixed reactions give R-R + R-R' + R'-R' (three products, poor selectivity)."],
      ["Kolbe electrolysis", "2 RCOO⁻ (electrolysis, anode) → R-R + 2CO₂ + 2e⁻", "Anodic oxidation gives R-COO•, which decarboxylates to R•; two R• couple. Gives symmetric alkane (R-R) from a single carboxylate salt. Mechanism passes through a carboxyl radical — distinct from Wurtz."],
      ["Catalytic hydrogenation", "R-CH=CH-R' + H₂ → R-CH₂-CH₂-R' (Ni, Pt or Pd catalyst)", "H₂ adsorbs dissociatively on the metal surface; both H atoms add to the same face of the adsorbed alkene (syn addition). Alkene gives alkane; alkyne also gives alkane (or alkene if Lindlar's catalyst is used — Section 7)."],
      ["From Grignard + protic source", "R-MgX + H₂O → R-H + Mg(OH)X", "Grignard reagent (R⁻ equivalent) is protonated by any proton source with pKa < ~50: H₂O, ROH, RCOOH, RNH₂. This is also how to destroy a Grignard intentionally — any active hydrogen ends it."],
    ]
  ),
  sub("Wurtz mechanism — full electron-transfer picture"),
  p("Step 1: first equivalent of sodium transfers one electron to the alkyl halide by an SET (single electron transfer) process: Na + R-X → Na⁺ + R-X•⁻ → R• + X⁻ + Na⁺. An alkyl radical and a sodium ion (plus halide) are formed. Step 2: the alkyl radical is reduced by a second equivalent of sodium: Na + R• → R⁻ + Na⁺ (forming an incipient carbanion equivalent), or two R• simply couple radically. Step 3: the carbon nucleophile attacks another R-X: R⁻ + R-X → R-R + X⁻ (SN2-like). In practice, both radical coupling and carbanion pathways contribute. The critical synthetic limitation follows directly: if R-X and R'-X are mixed, all three possible R-R, R-R', and R'-R' couplings occur in statistical proportions (with no useful selectivity), so the Wurtz reaction is only practical when R = R'."),
  callout("JEE trap", "A question asking 'which alkane CANNOT be made by the Wurtz reaction in good yield' is testing whether you know the symmetry limitation. Any alkane with an odd total carbon count that would require two different alkyl halides (e.g. propane from CH₃X + C₂H₅X) cannot be made cleanly by Wurtz — the mixed reaction gives a poor yield of the target. CH₄ (methane) also cannot be made by Wurtz — there is no lower halide precursor to couple to."),

  // ── Section 2 ─────────────────────────────────────────────────────────────
  major(2),
  p("Free-radical halogenation is the prototype chain reaction — it appears in every JEE Advanced chemistry syllabus and its mechanistic logic (initiation/propagation/termination) provides the quantitative basis for product ratio calculations."),
  sub("Complete chain mechanism for monochlorination of propane"),
  numbered([
    "Initiation: Cl₂ + hν → 2 Cl• (BDE of Cl-Cl = 243 kJ/mol — the weakest bond in the system, cleaved first by UV light).",
    "Propagation A: Cl• + CH₃CH₂CH₃ → HCl + CH₃CH•CH₃ (secondary radical, from 2° C-H, BDE ≈ 412 kJ/mol) or → HCl + CH₃CH₂CH₂• (primary radical, from 1° C-H, BDE ≈ 422 kJ/mol). Both are possible; selectivity determines the ratio.",
    "Propagation B: R• + Cl₂ → R-Cl + Cl•. The Cl• regenerated re-enters step A, completing the cycle. Net enthalpy: for 2° attack, 412 - 432 (H-Cl BDE) + 243 - 339 (1° C-Cl BDE) ≈ -116 kJ/mol per chain cycle.",
    "Termination: Cl• + Cl• → Cl₂; CH₃CH•CH₃ + Cl• → CH₃CHClCH₃; two radicals combine, ending the chain. Ethane (R• + R•) is always a minor byproduct.",
  ]),
  sub("Quantitative selectivity calculation — propane chlorination at 25°C"),
  p("Propane has 6 primary C-H bonds (on C-1 and C-3) and 2 secondary C-H bonds (on C-2). The per-hydrogen relative rate constants for Cl• at 25°C are approximately 1.0 for 1° and 3.9 for 2°. Probability of each product: 1-chloropropane = 6 × 1.0 = 6.0 units; 2-chloropropane = 2 × 3.9 = 7.8 units. Total = 13.8 units. Product ratio: 1-chloropropane = 6.0/13.8 = 43.5%; 2-chloropropane = 7.8/13.8 = 56.5%. For bromination with Br•: per-hydrogen relative rates are ~1 for 1° and ~97 for 2°. 1-bromopropane = 6 × 1 = 6 units; 2-bromopropane = 2 × 97 = 194 units. Percent 2-bromopropane = 194/200 = 97%. Same substrate, dramatically different selectivity."),
  table(
    ["Halogen", "Per-H selectivity (3° : 2° : 1°)", "Reason (Hammond postulate applied)", "Synthetic utility"],
    [
      ["F₂", "~1:1:1 (no selectivity)", "H-abstraction is extremely exothermic → early TS, reactant-like → all C-H bonds look equally reactive. Reaction also releases so much heat it tends to be uncontrollable.", "Not used in synthesis."],
      ["Cl₂", "~5:3.5:1", "Moderately exothermic H-abstraction → moderately early TS → modest selectivity.", "Used when a mixture is acceptable or separation is easy."],
      ["Br₂", "~1600:80:1", "Endothermic H-abstraction (BDE H-Br = 366 kJ/mol) → late TS, product-like → radical stability strongly expressed in rate differences.", "Highly selective — often gives a single positional isomer from a substrate with one 3° or benzylic C-H."],
      ["I₂", "No reaction", "H-abstraction is thermodynamically too unfavourable (H-I BDE too low). The iodine radical cannot abstract H from alkanes at a useful rate.", "Not used for direct alkane iodination."],
    ]
  ),
  callout("Key idea", "The reactivity-selectivity relationship is a general principle of physical organic chemistry: a more reactive radical (Cl•, F•) has an early transition state (resembles the reactants), so it is insensitive to the energy differences between radical products. A less reactive radical (Br•) has a late, product-like transition state, so the stability of the product radical is fully 'felt' in the rate constant — making Br• exquisitely selective. This pattern recurs in every mechanism where a reactive intermediate abstracts a bond."),

  // ── Section 3 ─────────────────────────────────────────────────────────────
  major(3),
  formula("C_nH_{2n+2} + \\tfrac{3n+1}{2}\\,O_2 \\longrightarrow n\\,CO_2 + (n+1)\\,H_2O \\qquad \\Delta_c H < 0", "complete combustion"),
  p("Incomplete combustion of alkanes (limited O₂): CₙH₂ₙ₊₂ → CO + H₂O (CO is the toxic product) or → soot (C particles). Industrial cracking (pyrolysis at 400-900°C) breaks longer chains homolytically to give a mixture of smaller alkanes and alkenes — the industrial basis of petroleum refining and ethylene/propylene production for plastics."),
  sub("Conformational analysis — Newman projections and energy"),
  p("In a Newman projection of ethane viewed along the C-C bond, the front carbon's bonds are shown as three spokes from the centre, and the rear carbon's bonds are shown as three lines from a circle at 60° offsets. The two staggered conformations of ethane (all three H-H dihedral angles = 60°) are equivalent and represent the energy minimum; the eclipsed conformations (dihedral = 0°) are the maximum, with torsional strain of ~12.5 kJ/mol per eclipsing H-H pair."),
  table(
    ["n-Butane conformation (Newman projection along C2-C3)", "Dihedral angle CH₃-C2-C3-CH₃", "Relative energy (kJ/mol)", "Why"],
    [
      ["Anti (most stable)", "180°", "0 (reference)", "Methyls maximally far apart; no torsional or steric strain."],
      ["Gauche", "60°", "+3.8 kJ/mol", "Methyls partially eclipsed — some steric gauche strain (van der Waals repulsion between two methyls at 60°)."],
      ["Eclipsed (minor)", "120°", "+16 kJ/mol", "One H-H eclipsing pair and one methyl-H eclipsing pair."],
      ["Fully eclipsed (worst)", "0°", "+19 kJ/mol", "Both methyls directly eclipsed — maximum torsional + steric strain."],
    ]
  ),
  callout("Warning / limitation", "Conformations interconvert by C-C bond rotation at room temperature far faster than they can be isolated as separate species — they are NOT structural isomers, configurational isomers, or different compounds. The energy differences (a few kJ/mol) are much less than the thermal energy available at room temperature (~2.5 kJ/mol per degree of freedom), so all conformations are continuously interconverting. Never describe a gauche butane as a 'different compound' from anti butane."),

  // ── Section 4 ─────────────────────────────────────────────────────────────
  major(4),
  table(
    ["Method", "Reaction", "Mechanism / regiochemistry"],
    [
      ["Dehydrohalogenation (E2)", "R-CHX-CH₂R' + KOH(alc.) → R-CH=CHR' + KX + H₂O", "Concerted anti-periplanar: the base removes a beta-H from the face opposite the leaving group in one step. Zaitsev product (more substituted alkene) is major for non-bulky bases."],
      ["Dehydrohalogenation (E1)", "R₃C-X (3°) + heat → R₃C⁺ → R₂C=CHR (+ H⁺ lost from adjacent C)", "Rate-determining ionisation to carbocation; base then removes beta-H. Watch for 1,2-shifts before elimination step."],
      ["Alcohol dehydration", "R-CH(OH)-CH₂R' + H₃PO₄ or H₂SO₄, heat → alkene + H₂O", "E1 for 2°/3° (via carbocation). Acid protonates -OH to give -OH₂⁺, which departs. E2 possible at high base/temperature. Zaitsev product dominates."],
      ["Lindlar reduction (cis-alkene from alkyne)", "R-C≡C-R' + H₂ (Lindlar's cat.) → cis-RCH=CHR'", "Syn addition on the catalyst surface — both H atoms add to the same face. The Lindlar catalyst (Pd/CaCO₃ + Pb(OAc)₂/quinoline) is partially poisoned to prevent over-reduction."],
      ["Dissolving metal (trans-alkene from alkyne)", "R-C≡C-R' + Na/NH₃(liq.) → trans-RCH=CHR'", "Birch-type: Na transfers e⁻ to the alkyne to give vinyl radical → vinyl radical abstracts H from NH₃ → vinyl anion → protonated by NH₃ to give trans-alkene (anti addition overall, more stable trans configuration from radical intermediate)."],
    ]
  ),
  sub("Full E2 mechanism — anti-periplanar requirement and Zaitsev vs Hofmann"),
  p("E2 elimination has a strict stereochemical requirement: the C-H bond being broken and the C-X bond leaving must be anti-periplanar (dihedral angle = 180°) in the transition state. This means the H and X must be on opposite faces of the C-C bond, and the molecule must rotate to this conformation before reaction can occur. If the anti-periplanar conformation is locked out (e.g. by a rigid ring system where H and X are both equatorial or both axial but in cis relationship), E2 cannot occur effectively."),
  p("Zaitsev's rule: the more substituted alkene is the major product (removal of the beta-H from the more substituted carbon gives the alkene with more alkyl groups = more hyperconjugatively stabilised, Section 7 of GOC). Hofmann product: with a bulky base (e.g. potassium tert-butoxide, (CH₃)₃COK), the base is sterically hindered and cannot easily access the beta-H of the more substituted carbon — it preferentially removes the H from the least hindered (less substituted) position, giving the less substituted (Hofmann) alkene as the major product."),
  callout("JEE trap", "Two substrates that are constitutional isomers can give the same alkene by E2 (e.g. both 2-bromobutane and 1-bromobutane can give 1-butene under different conditions) but only 2-bromobutane can give 2-butene by Zaitsev's rule. Also, E2 requires an antiperiplanar H and X — if the question specifies a trans-diaxial H and X in a cyclohexane ring, E2 is possible; if both are equatorial, it is not."),

  // ── Section 5 ─────────────────────────────────────────────────────────────
  major(5),
  p("Electrophilic addition to an alkene is the direct consequence of the pi bond acting as a nucleophile. Four mechanistically distinct addition types are tested in JEE, each with characteristic regio- and stereochemistry. Getting the mechanism right gives the product automatically."),
  sub("HX addition — Markovnikov, via carbocation"),
  p("Step 1 (rate-determining, electrophilic attack): H⁺ from HX attacks the pi bond. The proton adds to the LESS substituted carbon because this places the developing positive charge on the MORE substituted carbon (more stable carbocation, GOC Section 3). The full carbocation forms at the more substituted position. Step 2 (fast, nucleophilic capture): X⁻ attacks the planar carbocation from either face, giving the Markovnikov product. If the carbocation is tertiary or secondary, watch for 1,2-shifts (GOC Section 3) before capture."),
  formula("(CH_3)_2C{=}CH_2 + H^{+} \\longrightarrow (CH_3)_2\\overset{+}{C}{-}CH_3 \\xrightarrow{X^-} (CH_3)_2CX{-}CH_3", "Markovnikov addition of HX to isobutylene"),
  sub("Br₂ addition — anti addition via bromonium ion"),
  p("Bromine addition to alkenes is NOT a simple Markovnikov reaction via a free carbocation. Instead, the reaction proceeds through a three-membered bromonium ion intermediate: Step 1: Br₂ molecule (polarised by the alkene's pi electrons) loses Br⁻ while the remaining Br⁺ bridges across both alkene carbons, forming a three-membered cyclic bromonium ion (Br⁺ bonded to both carbons, keeping them from rotating freely). Step 2: Br⁻ (from step 1, now acting as nucleophile) attacks one of the two bromonium carbons from the BACK (SN2-like attack, anti to the bridging Br). This backside attack gives exclusively ANTI addition — the two Br atoms end up on opposite faces of the original double bond. For cyclic alkenes, this means trans-diaxial addition in the ring."),
  formula("\\text{alkene} + Br_2 \\longrightarrow [\\text{bromonium}]^+ + Br^- \\xrightarrow{\\text{anti}} \\text{trans-1,2-dibromide}", "anti addition via bromonium ion"),
  callout("Key idea", "The bromonium ion mechanism explains three facts at once: (1) why Br₂ addition to alkenes is anti (not syn) — the bridging Br blocks syn attack; (2) why no rearrangement occurs (no free carbocation to rearrange); (3) why the reaction is stereospecific (cis-alkene gives trans-dibromide and vice versa). Any question testing the stereochemistry of Br₂ addition requires the bromonium ion mechanism, not a free carbocation."),
  sub("Anti-Markovnikov HBr: the Kharasch (peroxide) effect"),
  p("In the presence of peroxides (ROOR) or UV light, HBr adds anti-Markovnikov. The mechanism is radical, not ionic. Initiation: ROOR → 2 RO•; RO• + HBr → ROH + Br•. Propagation: Br• adds to the LESS substituted carbon (giving the MORE stable radical at the more substituted carbon — same stability logic as carbocations, just applied to radicals). The resulting radical then abstracts H from HBr, giving the anti-Markovnikov product and regenerating Br•. Why only HBr? HCl: the H-abstraction from HCl by R• is endothermic (C-H bond formed is weaker than H-Cl broken), making propagation unfavourable. HI: the I• addition to the double bond is too slow/reversible. Only HBr has both steps thermodynamically favourable for chain propagation."),
  table(
    ["Addition method", "Regiochemistry", "Stereochemistry", "Mechanism key species"],
    [
      ["HX (ionic, no peroxide)", "Markovnikov", "No stereocontrol (planar cation)", "Carbocation"],
      ["HBr + peroxide", "Anti-Markovnikov", "No stereocontrol (planar radical)", "Carbon radical"],
      ["Br₂ (or Cl₂)", "N/A (same halogen adds twice)", "Anti addition (trans product)", "Halonium (bromonium/chloronium) ion"],
      ["H₂O / H₃O⁺", "Markovnikov (OH on more subst. C)", "No stereocontrol", "Carbocation"],
      ["BH₃·THF, then H₂O₂/NaOH (hydroboration-oxidation)", "Anti-Markovnikov (OH on less subst. C)", "Syn addition", "Four-centred concerted; no free ions"],
    ]
  ),
  sub("Hydroboration-oxidation: full mechanism"),
  p("Step 1 (Hydroboration): BH₃ (a Lewis acid/electrophile) and the alkene react in a concerted four-membered cyclic transition state. The boron attacks the less substituted carbon (because B is a large electrophile — steric guidance) and H migrates to the more substituted carbon, both from the same face (syn addition). One C-B and one C-H bond form simultaneously, with no carbocation. Each BH₃ adds to three alkene equivalents, giving a trialkylborane (BR₃). Step 2 (Oxidation): H₂O₂/NaOH oxidises the C-B bond with retention of configuration (the oxygen inserts into the C-B bond without breaking C-B and re-forming it). This retention, combined with the syn H/B addition in step 1, gives the overall syn addition of H and OH, with OH ending up on the face that bore boron — i.e., the less substituted carbon gets OH (anti-Markovnikov) via syn addition."),

  // ── Section 6 ─────────────────────────────────────────────────────────────
  major(6),
  table(
    ["Reagent", "Product from internal alkene (RCH=CHR')", "Diagnostic use / note"],
    [
      ["Cold, dilute, alkaline KMnO₄ (Baeyer's reagent)", "Syn 1,2-diol (glycol). Purple KMnO₄ decolourises to colourless Mn²⁺ solution (then brown MnO₂ precipitate forms).", "Test for unsaturation — the purple to colourless colour change is the observation. Also tells you that a C=C or C≡C is present, not what kind."],
      ["Hot, conc., acidified KMnO₄", "Oxidative cleavage: each carbon of the C=C is oxidised fully. R₂C= gives a ketone (R₂C=O); RHC= gives a carboxylic acid (RCOOH); H₂C= (terminal) gives CO₂ + H₂O. The entire alkene carbon appears in the carbonyl product.", "Determines the substitution pattern of each alkene carbon from the identity of the cleavage products."],
      ["O₃ (ozonolysis), then Zn/H₂O or (CH₃)₂S (reductive workup)", "Each alkene carbon becomes a carbonyl: R₂C= → R₂C=O (ketone); RHC= → RCHO (aldehyde). Reductive workup is essential — it prevents the aldehyde from being oxidised further to a carboxylic acid.", "Cleanest structural determination tool. Ozonide intermediate is never isolated (it is hazardous — explosive if dry). The 1,2,3-trioxolane ozonide forms first, then is cleaved reductively."],
      ["O₃, then H₂O₂ (oxidative workup)", "Each alkene carbon becomes the most oxidised carbonyl: ketone from R₂C=; carboxylic acid from RHC= (aldehyde intermediate is oxidised). Terminal =CH₂ → CO₂.", "Gives carboxylic acids instead of aldehydes; used when you want the acid product directly."],
    ]
  ),
  sub("Worked example: structure determination by ozonolysis"),
  p("An unknown alkene X (molecular formula C₆H₁₂, one degree of unsaturation) gives, on reductive ozonolysis: acetone ((CH₃)₂C=O) and propanal (CH₃CH₂CHO) as the only products. Reconstruct X: the ozonolysis products tell us what each alkene carbon looked like. The carbon that became acetone was a disubstituted carbon (two CH₃ groups attached). The carbon that became propanal was monosubstituted with one H and one ethyl group (CH₃CH₂-). Joining these two carbons with a double bond: (CH₃)₂C=CH-CH₂CH₃ = 2-methylpent-2-ene. Check: molecular formula (CH₃)₂C=CHCH₂CH₃ is C₆H₁₂ ✓, one degree of unsaturation (one C=C) ✓."),
  callout("JEE trap", "If the reductive workup gives an ALDEHYDE, there was a terminal =CHR on the alkene. If a KETONE, there was a disubstituted =CR₂. If CO₂ is mentioned (from oxidative ozonolysis), the original alkene had a terminal =CH₂. Remember: HOT acidified KMnO₄ converts the =CH₂ terminal to CO₂ (complete oxidation), while reductive ozonolysis gives formaldehyde (HCHO) from a terminal =CH₂. These two different methods give different products from the same =CH₂ group."),

  // ── Section 7 ─────────────────────────────────────────────────────────────
  major(7),
  table(
    ["Method", "Reaction", "Conditions and notes"],
    [
      ["From calcium carbide", "CaC₂ + 2H₂O → Ca(OH)₂ + HC≡CH (acetylene)", "Industrial route; CaC₂ is made by heating CaO + C (coke) at ~2000°C in an electric arc furnace."],
      ["Double dehydrohalogenation of vicinal dihalide", "R-CHBr-CH₂Br + 2 KOH(alc.) → R-C≡CH + 2 KBr + 2 H₂O", "Two sequential E2 eliminations. First gives vinyl halide (R-CHBr=CHBr... wait: from R-CHBr-CH₂Br, first E2 → R-CBr=CH₂, then second E2 → R-C≡CH). Needs excess strong base and heat."],
      ["Double dehydrohalogenation of geminal dihalide", "R-CH₂-CBr₂-R' + 2 KOH(alc.) → R-C≡C-R' + 2 KBr + 2 H₂O", "Geminal dihalide (both X on same C) also gives alkyne by two E2 steps. Same conditions as vicinal."],
      ["Chain elongation of terminal alkyne (acetylide alkylation)", "R-C≡C-H + NaNH₂ → R-C≡C⁻ Na⁺ + NH₃; then R-C≡C⁻ + R'-X → R-C≡C-R'", "SN2 on a primary R'-X (secondary and tertiary R'-X give elimination instead). This is the key method to build longer internal alkynes."],
    ]
  ),
  sub("Terminal alkyne acidity — derivation and applications"),
  p("Terminal alkyne C-H pKa ≈ 25; alkene (vinylic) C-H pKa ≈ 44; alkane C-H pKa ≈ 50. The trend is entirely controlled by the s-character of the C-H sigma orbital: sp (50% s) > sp2 (33% s) > sp3 (25% s). Higher s-character means the bonding electrons spend more time near the more electronegative carbon nucleus — the C-H bond is more polarised toward C, and the proton is more easily lost (the conjugate base carbanion's lone pair is in a lower-energy orbital). The pKa difference of 25 units between alkyne and alkane C-H corresponds to a Ka ratio of 10²⁵ — an enormous difference. This is why NaNH₂ (conjugate acid pKa ≈ 38 for NH₃) can deprotonate a terminal alkyne quantitatively (pKa 25 << 38), while n-BuLi (conjugate acid pKa ≈ 50) is required to deprotonate an alkane."),
  callout("Warning / limitation", "The acid C-H in a terminal alkyne is the one directly on the triply-bonded carbon (≡C-H). An internal alkyne (R-C≡C-R', no H on the triple bond) has no such acidic proton and cannot be deprotonated this way. Questions sometimes present 'but-2-yne' and ask whether NaNH₂ can deprotonate it — the answer is no, it is an internal alkyne."),

  // ── Section 8 ─────────────────────────────────────────────────────────────
  major(8),
  p("An alkyne contains two pi bonds. Addition reactions can stop at the alkene stage (1 equivalent of reagent) or go to the fully saturated product (2 equivalents), and Markovnikov orientation applies at each step. The key is knowing which catalyst or conditions control where the addition stops."),
  table(
    ["Reagent / conditions", "Product with terminal alkyne (RC≡CH)", "Product with internal alkyne (RC≡CR')", "Key point"],
    [
      ["H₂ / Lindlar's catalyst (Pd/CaCO₃, Pb/quinoline)", "cis-alkene (syn addition stops at the alkene)", "cis-internal alkene (syn)", "Lindlar catalyst is specifically designed to stop at the cis-alkene stage."],
      ["H₂ / Na or Li in liquid NH₃ (dissolving metal)", "trans-alkene (anti addition via radical anion)", "trans-internal alkene", "Gives the TRANS isomer — complementary to Lindlar's. The two methods together allow stereospecific alkene synthesis from the same alkyne."],
      ["HX (1 equivalent)", "Markovnikov vinyl halide: RCH=CHX (H adds to terminal C, X to internal C... wait: to RC≡CH, H⁺ adds to C-1 (less substituted, terminal), giving RC(⁺)=CH₂, X⁻ attacks to give RCX=CH₂. No wait: Markovnikov says H⁺ adds to the terminal carbon (which has more H's, one H vs 0), giving a vinyl cation at the internal carbon. For terminal alkyne: H adds to C-1 (terminal ≡CH), giving secondary vinyl cation R-C⁺=CH₂, then X⁻ attacks to give R-CX=CH₂ (2-haloalkene).", "Markovnikov vinyl halide", "Second addition of HX gives the geminal dihalide (both X on the same C), not vicinal — because the first intermediate vinyl halide has an X that is further stabilising the carbocation at that carbon."],
      ["H₂O / H₂SO₄ / HgSO₄ (Markovnikov hydration)", "Methyl ketone (RC(=O)CH₃) via Markovnikov enol → keto tautomerism: enol R-C(OH)=CH₂ tautomerises to RC(=O)-CH₃ (Markovnikov — OH ends up on internal carbon = ketone carbon)", "Mixed ketone (RC(=O)R')", "Terminal alkynes give exclusively methyl ketones by this method. Acetylene itself gives acetaldehyde."],
      ["BH₃·THF, then H₂O₂/NaOH (hydroboration-oxidation)", "Aldehyde (anti-Markovnikov: OH ends up on terminal carbon = aldehyde via enol tautomerisation: R-CH=CH-OH → R-CH₂-CHO)", "Mixed aldehyde from each end", "This is the ONLY direct route from a terminal alkyne to an aldehyde — the anti-Markovnikov counterpart of the HgSO₄ method."],
    ]
  ),
  callout("Key idea", "The Markovnikov vs anti-Markovnikov hydration pair for terminal alkynes — H₂O/H₂SO₄/HgSO₄ giving a methyl ketone vs hydroboration-oxidation giving an aldehyde — is one of the most predictable JEE Advanced question templates. Memorise which gives which, but more importantly understand why: the HgSO₄ method follows the Markovnikov cationic mechanism (OH goes to internal C → ketone); hydroboration puts B on terminal C (less hindered, anti-Markovnikov) → OH ends up on terminal C → enol tautomerises to aldehyde."),

  // ── Section 9 ─────────────────────────────────────────────────────────────
  major(9),
  p("Benzene's aromatic stabilisation (~150 kJ/mol, from GOC Section 9) makes addition reactions thermodynamically unfavourable — addition would destroy the aromatic pi system and lose this large stabilisation energy. The reaction pathway that avoids this loss (substitution — replace H, restore aromaticity) is instead overwhelmingly preferred. This is the mechanistic reason benzene undergoes substitution while alkenes undergo addition."),
  sub("Full EAS mechanism — three stages"),
  numbered([
    "Electrophile generation: the Lewis-acid catalyst (FeX₃, AlX₃, H₂SO₄) polarises or activates the electrophile. For nitration: H₂SO₄ + HNO₃ → H₂NO₃⁺ + HSO₄⁻ → NO₂⁺ + H₂O. For halogenation: Br₂ + FeBr₃ → Br-Br→FeBr₃ complex → Br⁺δ-Br-FeBr₃ → effectively Br⁺ as a reactive species.",
    "Electrophilic attack (rate-determining): the aromatic pi system (nucleophile) attacks E⁺. One pair of pi electrons attacks E, forming a new C-E sigma bond at one ring carbon. That carbon becomes sp3, destroying aromaticity locally. The resulting carbocation is the arenium ion (Wheland intermediate, sigma complex): a resonance-stabilised non-aromatic cation with positive charge delocalized over three ring carbons (the two ortho and the para carbons relative to the sp3 carbon). This is the highest-energy step — the rate-determining step.",
    "Deprotonation (fast): the Lewis-acid counterion (or any base present) removes the H from the sp3 carbon of the arenium ion. This H leaves as H⁺ (not as H⁻, i.e., the leaving 'group' is a proton, not a hydride). This instantly restores aromaticity — the driving force for this step is the large resonance stabilisation energy regained. No rearrangement or further reaction: the substituted benzene product is itself aromatic, not more reactive than starting benzene (unless the substituent is activating, in which case it can react further).",
  ]),
  formula("C_6H_6 + E^+ \\xrightarrow{\\text{slow, rate-det.}} [\\text{arenium ion}]^+ \\xrightarrow{-H^+,\\,\\text{fast}} C_6H_5E"),
  callout("Key idea", "The arenium ion is NOT an sp2 carbocation (it is one sp3 carbon in an otherwise conjugated ring). Its three resonance contributors have the positive charge at ortho and para positions relative to the newly formed C-E bond (never meta, because that would require a structure where positive charge is on the carbon bearing E — less stable than having it elsewhere). This direct derivation of the resonance contributors is exactly how GOC Section 6 proves that ortho/para directors stabilise the arenium ion at ortho/para more than at meta — and why meta directors destabilise ortho/para arenium contributors."),

  // ── Section 10 ─────────────────────────────────────────────────────────────
  major(10),
  table(
    ["Reaction", "Electrophile", "Reagents", "Key notes"],
    [
      ["Nitration", "NO₂⁺ (nitronium)", "Conc. HNO₃ + conc. H₂SO₄ (mixed acid)", "H₂SO₄ protonates HNO₃ → H₂NO₃⁺ → NO₂⁺ + H₂O. Reversible at mild temperatures; over-nitration gives di- and trinitro products at higher temperatures."],
      ["Sulfonation", "SO₃ (Lewis acid)", "Fuming H₂SO₄ (oleum = H₂SO₄ + excess SO₃)", "Uniquely REVERSIBLE: treatment with dilute H₂O at 100°C removes the sulfonic acid group (-SO₃H). Used as a 'blocking group' in multi-step synthesis and to remove sulfonyl after directing."],
      ["Bromination", "Br⁺ (via FeBr₃ complex)", "Br₂ + FeBr₃ (or AlBr₃)", "FeBr₃ coordinates to Br₂: Br-Br→FeBr₃. The Br closest to the ring becomes electrophilic. The FeBr₄⁻ formed is regenerated by the H⁺ lost in the final step. I₂ is too unreactive for direct ring iodination; I₂ + HNO₃ is used as an oxidising partner."],
      ["Friedel-Crafts alkylation", "R⁺ (carbocation from R-X + AlCl₃)", "R-X + anhydrous AlCl₃", "Carbocation rearrangement possible (see limitations). Polyalkylation occurs because product is more reactive than starting material. Fails on deactivated rings. Fails with aniline (Lewis acid complexes with N)."],
      ["Friedel-Crafts acylation", "RC≡O⁺ (acylium, resonance-stabilised)", "R-COCl (acyl chloride) + anhydrous AlCl₃, or anhydride + AlCl₃", "No rearrangement (acylium is resonance-stabilised, not a free alkyl cation). Product (aryl ketone) is LESS reactive than benzene (carbonyl is -M, deactivating), so reaction stops after monosubstitution. No polyacylation."],
    ]
  ),
  sub("Friedel-Crafts alkylation limitations — the complete list for JEE"),
  bullets([
    "Carbocation rearrangement: neopentyl chloride + AlCl₃ gives predominantly tert-amylbenzene (after 1,2-methyl shift of the neopentyl cation to the tert-amyl cation) rather than neopentylbenzene. The solution: always use acylation followed by Clemmensen/Wolff-Kishner reduction when you need an unbranched or rearrangement-free alkyl group on a ring.",
    "Polyalkylation: the first alkyl group activates the ring toward a second alkylation (alkyl is +I/+R activator). Experimental cure: use excess benzene relative to alkyl halide, so the alkylated product is diluted and further reaction is statistically disfavoured. Or use acylation instead.",
    "Deactivated rings don't react: -NO₂, -CN, -SO₃H, -COR, -COOH all strongly deactivate the ring. A ring with any of these groups will not undergo Friedel-Crafts under normal conditions.",
    "Aniline (and other primary/secondary aryl amines) fail for a different reason: AlCl₃ (Lewis acid) coordinates to the nitrogen lone pair, converting -NH₂ into -NH₂→AlCl₃ — a positive-nitrogen, electron-withdrawing species. This converts the ring from activated/ortho-para-directing to deactivated/meta-directing, shutting down the Friedel-Crafts reaction effectively.",
    "Vinyl halides and aryl halides do not generate reactive carbocations with AlCl₃ (the C-X bond is too strong in sp2/aromatic systems to ionise), so they don't work as alkylating agents in Friedel-Crafts.",
  ]),

  // ── Section 11 ─────────────────────────────────────────────────────────────
  major(11),
  p("When a benzene ring already has one substituent, the next EAS reaction is directed by both the electronic effect (activating or deactivating — controls rate) and the regiochemical preference (ortho/para or meta — controls position) of the existing group."),
  table(
    ["Substituent class", "Electronic effect on ring", "Directs to", "Representative substituents"],
    [
      ["Strong ortho/para activators", "Strongly electron-donating — large rate increase", "ortho and para", "-OH, -OR, -NH₂, -NHR, -NR₂, -NHCOR"],
      ["Weak ortho/para activators", "Weakly electron-donating", "ortho and para", "-R (alkyl), -Ar (phenyl by resonance)"],
      ["Halogens (special case)", "Electron-withdrawing overall (-I dominates, rate DECREASES)", "ortho and para (+M lone-pair donation still regiodirects despite -I deactivation)", "-F, -Cl, -Br, -I (all deactivating but ortho/para-directing)"],
      ["Meta directors", "Strongly electron-withdrawing — large rate decrease", "meta", "-NO₂, -CN, -CHO, -COR, -COOH, -COOR, -SO₃H, -NR₃⁺, -CF₃"],
    ]
  ),
  sub("Why halogens are deactivating but ortho/para directing — the dual nature explained"),
  p("Halogens have two opposing electronic effects. Their -I (inductive) effect: the high electronegativity of halogen withdraws electron density through sigma bonds FROM the ring. This reduces overall ring electron density — the ring is less nucleophilic, so it reacts more slowly with electrophiles. This makes halogens net deactivators (rate of EAS decreases: rate order for chlorobenzene vs benzene, roughly 0.03:1 for Cl₂/FeCl₃). Their +M (mesomeric/resonance) effect: each halogen has lone pairs in p-type orbitals that can donate into the aromatic ring. This donation places additional electron density at the ortho and para positions (the same positions that the +M arrow from N in aniline would direct to). So the -I decreases the total electron density equally at all ring positions, while the +M specifically increases electron density at ortho and para relative to the halogen. The net result: the ring is less reactive than benzene (deactivated overall by -I) but when reaction does occur, it is preferentially at the ortho and para positions (directed by the +M regiochemical effect, which acts more powerfully at those positions). Both observations follow from one mechanistic picture — no separate memorisation needed."),
  sub("Two-substituent conflict: how to resolve"),
  p("When two substituents are present and they point toward different ring positions for the third electrophile, resolve as follows: (1) If both groups agree on a position (both ortho/para-directing, reinforcing each other), the position they both point to wins. (2) If they disagree, the STRONGER director's preference dominates — a strong activator always beats a weak one, and a strong deactivator beats a weak director. (3) If they are on a symmetric ring, check whether the positions they 'fight over' are the same physical ring positions — often the conflict is apparent, not real."),
  p("Example: m-chlorotoluene (methyl at C1, Cl at C3). For the third EAS: methyl (+I, o/p-director relative to C1) directs to C2, C4, C6 (ortho/para to methyl). Cl (-I net, o/p-director relative to C3) directs to C2, C4, C6 (ortho/para to Cl). C2 = ortho to both methyl AND ortho to Cl, but: C4 = para to methyl AND ortho to Cl. C6 = ortho to methyl only. C2 is the position that both substituents direct to (ortho to methyl, ortho to Cl) → this is the most activated site. C4 is also doubly activated (para to methyl, ortho to Cl). Steric factors: C2 is between both groups (can be hindered) → C4 typically gives the major product."),

  // ── Section 12 ─────────────────────────────────────────────────────────────
  major(12),

  sub("Q1 — Wurtz reaction product prediction (NEET/JEE pattern)"),
  p("A Wurtz reaction is carried out with a 1:1 mixture of chloromethane (CH₃Cl) and chloroethane (C₂H₅Cl) with sodium in dry ether. List all alkane products formed and explain why this is a poor synthetic route to propane."),
  callout("Solution", "Three alkane products form: (1) ethane (CH₃-CH₃, from two CH₃• coupling); (2) propane (CH₃-C₂H₅, from CH₃• + C₂H₅•, the desired product); (3) butane (C₂H₅-C₂H₅, from two C₂H₅• coupling). Statistical expectation if both radicals are equally likely: ratio ≈ 1:2:1 (ethane:propane:butane). This is a poor synthetic route because about 50% of the product is the target (propane), and the mixture requires tedious separation. The Wurtz reaction is useful only for symmetric couplings (same R group on both halides) where only one product forms."),

  sub("Q2 — Radical selectivity calculation (JEE Advanced integer type)"),
  p("2-methylpropane (isobutane, (CH₃)₃CH) is monochlorinated with Cl₂ under UV light. Given that the per-hydrogen selectivity of Cl• is 5.0:1.0 (tertiary : primary), and isobutane has 1 tertiary H and 9 primary H, calculate the percentage of 2-chloro-2-methylpropane (tertiary product) in the product mixture."),
  callout("Solution", "Tertiary product units = 1 × 5.0 = 5.0. Primary product units = 9 × 1.0 = 9.0. Total = 14.0. Percent tertiary = 5.0/14.0 × 100 = 35.7%. Percent primary = 9.0/14.0 × 100 = 64.3%. Note: despite the tertiary C-H being 5 times more reactive per hydrogen, the large statistical excess (9:1) of primary C-H bonds still makes the primary product the majority — this is why Cl₂ is a poor tool for selective tertiary functionalisation, and Br₂ (per-H selectivity ~97:1) would give 97 × 1 = 97 tertiary units vs 9 × 1 = 9 primary units = 91.5% tertiary product."),

  sub("Q3 — Conformation energy (JEE Advanced reasoning)"),
  p("In the Newman projection of n-butane viewed along the C2-C3 bond, list the conformations from lowest to highest energy and explain which interaction(s) make each eclipsed form less stable than its staggered counterpart."),
  callout("Solution", "Energy order (lowest to highest): anti (180°, most stable) < gauche (60°) < eclipsed partial (120°) < fully eclipsed (0°, most unstable). Anti: all groups staggered, methyls maximally separated — no steric or torsional strain. Gauche (+3.8 kJ/mol): groups staggered (no torsional strain), but the two methyls are at 60°, causing van der Waals gauche strain. Partially eclipsed (120°, +16 kJ/mol): one H-H eclipsing pair (torsional strain ~4 kJ/mol) and one methyl-H eclipsing pair (torsional + steric, ~6 kJ/mol). Fully eclipsed (0°, +19 kJ/mol): methyl-methyl eclipsing (the worst: torsional strain ~4 kJ/mol + steric repulsion between two large methyl groups ~15 kJ/mol). The energies are additive: each H-H eclipsing pair costs ~4 kJ/mol; each methyl-H eclipsing pair costs ~6 kJ/mol; methyl-methyl eclipsing costs ~11 kJ/mol."),

  sub("Q4 — E2 stereospecificity (JEE Advanced)"),
  p("(a) meso-2,3-dibromobutane is treated with 2 equiv KOH(alc.)/heat. (b) (±)-2,3-dibromobutane (racemic mixture) is treated identically. Predict the alkene product(s) formed from each and explain the difference."),
  callout("Solution", "(a) meso-2,3-dibromobutane has one anti-periplanar arrangement for the H at C-1 and Br at C-2 (the only accessible E2-active conformation). The anti-periplanar H-C₁-C₂-Br arrangement in the meso compound gives exclusively cis-2-butene (the methyl groups end up on the same side in the trans transition state relative to the breaking bond — working this out requires drawing the Newman projection and confirming anti geometry leads to cis product). Specifically: meso compound → cis-2-butene only. (b) The (±) mixture (R,R + S,S) has anti-periplanar H and Br conformations that lead to trans-2-butene. Each enantiomer gives the same trans product by its respective anti-periplanar elimination. Result: (±)-2,3-dibromobutane → trans-2-butene only. The two diastereomeric starting materials give two different alkene stereoisomers — direct proof that E2 is stereospecific (the geometry of the transition state determines the geometry of the alkene product)."),

  sub("Q5 — Markovnikov with rearrangement (JEE Advanced)"),
  p("3,3-dimethylbut-1-ene reacts with HCl. Predict the MAJOR product, drawing the carbocation intermediate and the 1,2-shift that occurs."),
  callout("Solution", "Step 1: H⁺ adds to C-1 (the terminal carbon = fewer substituents, Markovnikov), generating the secondary carbocation at C-2: (CH₃)₃C-C⁺H-CH₃... wait — 3,3-dimethylbut-1-ene is (CH₃)₃C-CH=CH₂. H⁺ adds to the terminal CH₂ (C-1), giving the secondary carbocation at C-2: (CH₃)₃C-C⁺H₂... no. Correct: the double bond is C-1=C-2. H⁺ adds to C-1 (terminal, =CH₂), giving carbocation at C-2: (CH₃)₃C-⁺CH-CH₃... this is secondary. 1,2-methyl shift: one methyl migrates from the quaternary C-3 to the cationic C-2, giving the tertiary cation at C-3: (CH₃)₂C⁺-CH₂-CH₃ = 2-methylbutan-2-yl cation (tertiary). Cl⁻ attacks the tertiary cation: (CH₃)₂CCl-CH₂CH₃ = 2-chloro-2-methylbutane. This is the major product — NOT 2-chloro-3,3-dimethylbutane (which would be the direct Markovnikov product without rearrangement). This question requires knowing that (1) the Markovnikov secondary cation forms first, and (2) it rearranges to the tertiary cation before capture."),

  sub("Q6 — Bromonium ion stereochemistry (JEE Advanced)"),
  p("(a) cis-2-butene reacts with Br₂ in CCl₄. (b) trans-2-butene reacts with Br₂ in CCl₄. Predict the stereochemistry of the 2,3-dibromobutane product from each reaction and explain using the bromonium ion mechanism."),
  callout("Solution", "(a) cis-2-butene + Br₂: the bromonium ion forms from the top or bottom face (both are equivalent by symmetry in cis-2-butene). Br⁻ attacks backside (anti) at either C-2 or C-3. Working through the stereochemistry: cis-2-butene → bromonium ion → anti attack by Br⁻ gives (2R,3R) and (2S,3S) 2,3-dibromobutane — a racemic mixture of the two enantiomers of the ANTI (trans) diol diastereomer. But for Br₂ addition, the product is 2,3-dibromobutane. Anti addition to cis-2-butene gives: both Br on opposite faces — the product is the (±) pair of (2R,3S) and (2S,3R) = meso-2,3-dibromobutane (actually: anti addition to cis gives the racemic mixture of the anti stereoisomers, which for 2-butene are the two enantiomers). Let me be precise: anti addition to cis-2-butene gives exclusively the (2R,3S) product = the meso diastereomer of 2,3-dibromobutane (both bromines end up on opposite faces, and the methyl groups are on opposite faces as well — meso). (b) trans-2-butene + Br₂: anti addition gives the (2R,3R) and (2S,3S) pair = the (±) racemic mixture of the non-meso 2,3-dibromobutane. Conclusion: cis-2-butene → meso-dibromide; trans-2-butene → (±)-dibromide. This stereospecificity is the definitive proof of anti addition via the bromonium ion mechanism."),

  sub("Q7 — Ozonolysis structure determination (JEE Advanced)"),
  p("A cyclic alkene C₆H₁₀ undergoes ozonolysis with reductive workup to give only ONE product: pentanedial (OHC-CH₂CH₂CH₂-CHO, a dialdehyde). Identify the cyclic alkene and explain why only one product is produced from a cyclic compound."),
  callout("Solution", "The alkene is cyclohexene (C₆H₁₀). Ozonolysis of a cyclic alkene breaks the ring and opens it into a single difunctional chain product — unlike an open-chain alkene which gives two separate carbonyl fragments. For cyclohexene: the C=C is at C-1 and C-2 of the ring. Ozonolysis breaks this bond and oxidises each carbon to an aldehyde: the ring opens to give one molecule of pentanedial (OHC-(CH₂)₃-CHO). The molecular formula check: cyclohexene (C₆H₁₀) → pentanedial (C₅H₈O₂)... wait. Pentanedial is OHC-CH₂CH₂CH₂-CHO = C₅H₈O₂. But cyclohexene is C₆H₁₀. The discrepancy is resolved: ozonolysis of cyclohexene gives hexanedial (OHC-(CH₂)₄-CHO, C₆H₁₀O₂), NOT pentanedial. Hexanedial has 6 carbons matching cyclohexene. Correction: the product is hexanedial. A cyclic compound gives ONE product from ozonolysis (the ring opens to a chain with two aldehyde/ketone termini) rather than two separate products, which is why cyclic alkenes are recognisable in ozonolysis problems."),

  sub("Q8 — Alkyne synthesis multi-step (JEE Advanced)"),
  p("Starting from acetylene (HC≡CH) and any necessary inorganic reagents, outline a synthesis of pent-1-yne (CH₃CH₂CH₂C≡CH) in the minimum number of steps."),
  callout("Solution", "Step 1: Deprotonate acetylene with NaNH₂ (1 equiv): HC≡CH + NaNH₂ → HC≡C⁻Na⁺ + NH₃. This generates the sodium acetylide, the carbanion/alkylating agent. Step 2: Alkylate with 1-bromopropane (n-propyl bromide, CH₃CH₂CH₂Br, a primary alkyl halide — secondary/tertiary would give elimination): HC≡C⁻Na⁺ + BrCH₂CH₂CH₃ → HC≡C-CH₂CH₂CH₃ + NaBr. Product is pent-1-yne. Total: 2 steps. The key: only primary alkyl halides work in the SN2 alkylation step (secondary/tertiary give E2 elimination with the strong acetylide base). If n-propyl bromide is not available, it can be made from propanol + HBr, but that adds steps — the question specifies 'any inorganic reagents', and n-propyl bromide is an organic compound, so this needs to be made from propanol or propene as an additional step if truly only acetylene and inorganics are allowed."),

  sub("Q9 — EAS mechanism for nitration (JEE Advanced)"),
  p("Write the complete mechanism for the nitration of toluene with HNO₃/H₂SO₄, showing: (a) formation of the NO₂⁺ electrophile; (b) all three resonance structures of the arenium ion intermediate for ortho attack; (c) why ortho and para attack are faster than meta attack."),
  callout("Solution", "(a) Electrophile formation: H₂SO₄ + HNO₃ → H₂NO₃⁺ + HSO₄⁻; H₂NO₃⁺ → NO₂⁺ + H₂O (the protonated nitric acid loses water, giving the nitronium ion). (b) For ortho attack on toluene: the arenium ion has three resonance contributors. Contributor 1: NO₂ and ⁺ on the ipso carbon (adjacent to methyl). Contributor 2: ⁺ on the carbon ortho to NO₂ (which is the ipso to methyl). Contributor 3: ⁺ on the carbon para to NO₂ (meta to methyl). Crucially: in Contributor 2, the ⁺ charge is directly on the carbon bearing the methyl group (the ipso carbon). The methyl group's +I effect and hyperconjugation stabilise the adjacent positive charge — the same effect that makes tertiary carbocations stable. This extra stabilisation is not available for the meta arenium ion's resonance contributors (none of them place the ⁺ on the carbon bearing methyl for meta attack). (c) For ortho and para attack: one of the three resonance contributors places the positive charge directly on the ipso carbon (the methyl-bearing carbon), which is stabilised by the methyl's +I/hyperconjugation. For meta attack, none of the three resonance contributors places the ⁺ on the methyl-bearing carbon — the methyl cannot directly stabilise the arenium ion. Therefore ortho/para arenium ions are lower in energy (more stable) than the meta arenium ion, and the transition states leading to them are lower-energy by Hammond's postulate, giving faster rates for ortho/para attack."),

  sub("Q10 — Friedel-Crafts limitations: multiple correct (JEE Advanced)"),
  p("Which of the following will NOT work as written? (A) Benzene + neopentyl chloride + AlCl₃ → neopentylbenzene; (B) Aniline + CH₃COCl + AlCl₃ → N-acetylanilide → THEN use HNO₃/H₂SO₄ → acetamide is now protected; (C) Nitrobenzene + CH₃Cl + AlCl₃ → o- and p-nitrotoluene; (D) Benzene + isopropyl chloride + AlCl₃ → isopropylbenzene (cumene); (E) Chlorobenzene + CH₃COCl + AlCl₃ → Friedel-Crafts acylation."),
  callout("Solution", "A and C fail. (A) Neopentyl chloride + AlCl₃ generates the neopentyl cation, (CH₃)₃C-CH₂⁺ (primary, very unstable), which undergoes a 1,2-methyl shift to give the tert-amyl cation (CH₃)₂C⁺-CH₂CH₃ (tertiary). This tertiary cation attacks benzene, giving tert-amylbenzene, NOT neopentylbenzene. (C) Nitrobenzene is strongly deactivated (the -NO₂ group is a powerful -M group) — Friedel-Crafts alkylation does not work on nitrobenzene or any ring with a strong deactivating group. (B) This works — the acetyl group actually protects the nitrogen, and the resulting acetamide has the ring less strongly activated but still ortho/para-directing (the amide nitrogen's lone pair is partially donated into the ring through the carbonyl, but less so than free NH₂ — still activating enough for nitration). (D) Isopropyl chloride + AlCl₃ gives the isopropyl cation (2°), which does NOT rearrange further (already secondary and cannot become tertiary on its own) — isopropylbenzene (cumene) is the direct Friedel-Crafts product. (E) Chlorobenzene is deactivated overall (by -I of Cl) but the ring still has enough electron density for acylation (not alkylation, which needs a more electron-rich ring) — chlorobenzene does undergo Friedel-Crafts acylation, giving o- and p-chlorophenyl ketones preferentially (ortho/para from the Cl's +M effect)."),

  sub("Q11 — Directing effects conflict resolution (JEE Advanced)"),
  p("p-Bromoanisole (Br at C-4, OCH₃ at C-1 of benzene) undergoes nitration with HNO₃/H₂SO₄. Predict the major mononitrated product and justify using both substituents' directing preferences."),
  callout("Solution", "The two substituents: -OCH₃ at C-1 is a strong ortho/para activator (+M lone-pair donation into ring). -Br at C-4 is a deactivator with ortho/para directing preference (+M regiochemically, even though -I overall). In p-bromoanisole, the C-1 and C-4 positions are already occupied (by -OCH₃ and -Br respectively). Open positions: C-2 (ortho to OCH₃, meta to Br); C-3 (meta to OCH₃, ortho to Br); C-4 is taken. By symmetry, C-2 = C-6 (ortho to OCH₃), and C-3 = C-5 (meta to OCH₃, ortho to Br). -OCH₃ directs to ortho positions (C-2, C-6) and para (C-4, occupied). -Br directs to ortho (C-3, C-5) and para (C-1, occupied). So -OCH₃ and -Br direct to DIFFERENT positions: -OCH₃ prefers C-2/C-6; -Br prefers C-3/C-5. The stronger director (-OCH₃, a powerful activator vs Br, a deactivator) wins: major product has NO₂ at C-2 (ortho to OCH₃). The -OCH₃ group's strong +M donation overwhelms the competing direction from the weaker Br. Product: 2-bromo-4-nitroanisole (i.e., nitration at C-2 relative to OCH₃)."),

  sub("Q12 — Alkene identification from addition products (JEE Advanced)"),
  p("An unknown alkene A reacts with: (i) HBr (no peroxide) to give 2-bromobutane; (ii) Br₂/H₂O to give a bromohydrin with Br on C-2 and OH on C-1; (iii) cold KMnO₄ to give a diol; (iv) hot KMnO₄/H⁺ to give butanoic acid and CO₂. Identify A completely, including regiochemistry and stereochemical features if applicable."),
  callout("Solution", "From test (i): HBr addition (Markovnikov) gives 2-bromobutane → the Br is on C-2. Markovnikov means H adds to the carbon with more H's. For Br to end up on C-2, H must have added to C-1 (terminal carbon with 2H's), meaning A has a C-1=C-2 double bond (terminal alkene in a 4-carbon chain): but-1-ene, CH₂=CH-CH₂CH₃. From test (iv): hot KMnO₄ gives butanoic acid (from the monosubstituted carbon, C-2: one H, one ethyl = RCH= → RCOOH = butanoic acid) and CO₂ (from the terminal =CH₂ → CO₂ by complete oxidation). This confirms the terminal alkene: =CH₂ gives CO₂; -CH=CH₂CH₃... wait, the acid has 4 carbons: butanoic acid = CH₃CH₂CH₂COOH = 4 carbons. If the C-2 side gives butanoic acid (4 carbons), then C-2 has a propyl group attached. But C-2 in but-1-ene has one ethyl and one H — that would give propionic acid (3 carbons), not butanoic acid. Reconsider: if hot KMnO₄ gives butanoic acid (CH₃CH₂CH₂COOH, 4 carbons) and CO₂, the alkene must be pent-1-ene (CH₂=CH-CH₂CH₂CH₃): C-1 gives CO₂, C-2 has a propyl group and gives pentanoic acid... but that's not matching 4 carbons either. Resolution: the alkene is pent-1-ene (CH₂=CHCH₂CH₂CH₃) from C-2 oxidation → butanoic acid (4 carbons from C-2 + the propyl chain) — check: RCH= where R=propyl (C₃H₇) → RCOOH = butanoic acid (C₄H₉COOH... no, it's R-COOH, where R=propyl giving propanoic acid C₄H₈O₂ = C₃H₇COOH). The molecular formula for butanoic acid is C₄H₈O₂ = CH₃CH₂CH₂COOH. So R = propyl = C₃H₇: this means C-2 has one H and one propyl = pent-1-ene (CH₂=CH-CH₂CH₂CH₃). Alkene A = pent-1-ene."),

  sub("Q13 — Multiple correct: which statements about EAS are true? (JEE Advanced)"),
  p("Select all true statements: (A) The arenium ion intermediate in EAS is aromatic. (B) The rate-determining step of EAS is loss of H⁺ from the arenium ion. (C) Friedel-Crafts acylation gives no rearrangement product because the acylium ion is resonance-stabilised. (D) Sulfonation is reversible; nitration is not (under the same mild conditions). (E) Chlorobenzene reacts with electrophiles faster than benzene in EAS."),
  callout("Solution", "C and D are correct. (A) FALSE: the arenium ion has one sp3 carbon — it is explicitly non-aromatic (not cyclic fully conjugated). (B) FALSE: the rate-determining step is electrophilic attack (step 2: aromatic ring attacks E⁺ to form the arenium ion). Loss of H⁺ (step 3) is fast because it restores aromaticity — it is NOT the slow step. (C) TRUE: the acylium R-C≡O⁺ is resonance-stabilised (R-C=O ↔ R-C⁺-O⁻-... more precisely, positive charge is spread between C and O by the canonical form) and does not rearrange via hydride/alkyl shifts — unlike a free alkyl carbocation. (D) TRUE: sulfonation (SO₃ electrophile) is reversible — the C-S bond can reform under aqueous acid conditions. Nitration (NO₂⁺ electrophile) is not reversed under typical conditions — the C-NO₂ bond formed is stable to dilute aqueous conditions. (E) FALSE: chlorobenzene reacts SLOWER than benzene in EAS (Cl is a net deactivator, -I effect reduces ring electron density overall, lowering EAS rate). Chlorobenzene reacts at roughly 0.03 the rate of benzene toward Cl₂/FeCl₃."),

  sub("Q14 — Hydroboration-oxidation regiochemistry (JEE/NEET)"),
  p("Propene (CH₃CH=CH₂) reacts with: (A) BH₃·THF, then H₂O₂/NaOH; (B) cold dilute H₂SO₄/H₂O (acid-catalysed hydration); (C) Hg(OAc)₂/H₂O then NaBH₄ (oxymercuration-demercuration). For each, state the regiochemistry of alcohol formation and the mechanism that dictates it."),
  callout("Solution", "(A) Hydroboration-oxidation: anti-Markovnikov, syn addition. Boron adds to the LESS substituted carbon (C-1, the terminal =CH₂) due to concerted four-centre transition state and steric guidance. After H₂O₂/NaOH oxidation (retention of configuration at C-B → C-OH), OH ends up on C-1. Product: propan-1-ol. (B) Acid-catalysed hydration: Markovnikov. H⁺ adds to C-1 (less substituted terminal carbon, Markovnikov rule: gives the more stable 2° cation at C-2). H₂O attacks C-2⁺ → propan-2-ol. No stereocontrol (planar cation). (C) Oxymercuration-demercuration: Markovnikov, without carbocation rearrangement. Mercury(II) electrophile acts like Br⁺ via a mercurinium ion (analogous to bromonium ion), which is opened by H₂O at the more substituted carbon (Markovnikov). NaBH₄ reduces C-Hg to C-H, overall giving propan-2-ol with no rearrangement. Summary: propan-1-ol from (A); propan-2-ol from both (B) and (C). The key practical distinction between B and C: if a substrate would rearrange via a carbocation, use C (oxymercuration) to get Markovnikov product without rearrangement."),

  sub("Q15 — Dissolving metal reduction of alkyne (JEE Advanced)"),
  p("Show the mechanism for the dissolving-metal reduction of 2-butyne (CH₃C≡CCH₃) with Na/liquid NH₃ to give trans-2-butene (two sequential one-electron transfers). Why does the reaction give exclusively the trans isomer?"),
  callout("Solution", "Step 1: Na transfers one electron to 2-butyne: CH₃C≡CCH₃ + e⁻ → [CH₃C=CCH₃]•⁻ (a vinyl radical anion — one electron added to the pi* of the triple bond). Step 2: The vinyl radical anion abstracts H from NH₃ (the solvent): [CH₃C=CCH₃]•⁻ + NH₃ → CH₃C•=CHCH₃ + NH₂⁻ (a vinyl radical, now with one H on the beta carbon). Step 3: Second electron transfer from Na: CH₃C•=CHCH₃ + e⁻ → [CH₃C=CHCH₃]⁻ (a vinyl carbanion). Step 4: The vinyl carbanion is protonated by NH₃: [CH₃C=CHCH₃]⁻ + NH₃ → CH₃CH=CHCH₃ + NH₂⁻. Why trans? The vinyl radical at the end of step 2 is a sp2-hybridised radical at the central carbon — radicals on sp2 carbons are planar but the most stable configuration is with the two methyl groups anti (trans configuration = less steric interaction). The radical equilibrates to the more stable anti geometry before the second electron transfer. Additionally, the vinyl carbanion formed in step 3 is also more stable with the two methyl groups anti (lower steric strain). The selective formation of trans from the anti-configured intermediate makes this reaction stereospecific."),

  sub("Q16 — Assertion-Reason: why addition not substitution for alkenes (JEE A-R)"),
  p("Assertion (A): Benzene undergoes electrophilic substitution, while cyclohexadiene undergoes electrophilic addition. Reason (R): Benzene has an aromatic stabilisation energy (resonance energy of ~150 kJ/mol) that would be lost upon addition, making substitution (which preserves aromaticity) the lower-energy pathway. Cyclohexadiene has no such aromatic stabilisation and reacts as a typical polyene."),
  callout("Solution", "Both A and R are correct, and R is the correct explanation of A. The aromatic stabilisation of benzene (~150 kJ/mol) is a thermodynamic benefit that would be entirely lost if benzene underwent addition (the product, a cyclohexene or cyclohexadiene, is not aromatic). Substitution preserves the aromatic ring and hence retains the entire stabilisation energy. This thermodynamic driving force makes substitution overwhelmingly favourable despite the higher kinetic barrier (forming and then losing the arenium ion). For cyclohexadiene, there is no aromaticity to preserve — addition is kinetically and thermodynamically competitive, and occurs readily."),

  sub("Q17 — Ozonolysis backward from products (JEE Advanced)"),
  p("Reductive ozonolysis of an unknown compound X gives: cyclohexanone (one ring ketone) and propanedial (OHC-CH₂-CHO, malonaldehyde). (a) How many carbons does X have? (b) Reconstruct the structure of X. (c) Is X an alkene or a ring compound? Explain."),
  callout("Solution", "(a) Cyclohexanone has 6 carbons; propanedial has 3 carbons. Total carbon in X = 6 + 3 = 9 carbons. Molecular formula: C₉H₁₄ (degree of unsaturation = (2×9 + 2 - 14)/2 = (18 + 2 - 14)/2 = 6/2 = 3 — but wait: the ring of cyclohexanone accounts for 1 degree of unsaturation, and the C=O accounts for 1, so we should think about how many C=C bonds were in X. If only one C=C was ozonolysed, degrees of unsaturation = 1 (the C=C). Cyclohexanone retains the ring, which was part of X. So X has 1 ring + 1 C=C in its structure). (b) Reconstruction: ozonolysis of the C=C in X gives cyclohexanone and propanedial. The C=C is between the carbon that becomes the ketone carbon of cyclohexanone and one carbon of propanedial. Reconnect: X is 2-(2-oxoethylidene)cyclohexane? No — let's be careful. Cyclohexanone has a C=O from a ring carbon. Propanedial is OHC-CH₂-CHO. The two carbons that were the C=C in X became: one carbon of the ring ketone (C=O within the ring) and one carbon of propanedial (a CHO). So X is 2-allyl-cyclohex-1-en-1-ol... No. Simpler: the C=C in X connects the ring to the propanedial chain. X is (cyclohexanylidene)malonaldehyde? Taking it from the product structures: X must have been cyclohex-1-ylidene connected via a C=C to CH₂CHO? Let me approach it differently: the =C of cyclohexanone (after ozonolysis) was an sp2 carbon in a ring that is now the C=O of cyclohexanone — so that C was in the ring AND part of a C=C exocyclic double bond. The other end of that C=C is the CHO of propanedial. So X has an exocyclic double bond: cyclohexyl=CH-CH₂-CHO, i.e., 2-(cyclohexylidene)malonaldehyde is NOT right — X is cyclohexylidene-propanal: (cyclohexylidene)-CH₂-CHO = (cyclohex-1-ylidene)propanal. This has a ring (6C), a bridging exocyclic C=C, and a propanal chain (–CH₂CHO = 2C + CHO = 3C). Total: 6 + 1 (bridging C in exocyclic position) + CH₂ + CHO = 6 + 3 = 9C. Formula: C₉H₁₄O (with one ring and one C=C). (c) X is a cyclic compound (contains the cyclohexane ring) with an exocyclic alkene (the C=C connecting the ring to the chain)."),

  sub("Q18 — Hydration stereochemistry: which method gives syn? (JEE/NEET classification)"),
  p("Classify each reaction as giving syn or anti addition (or neither/no stereocontrol): (A) HBr to cis-2-butene (ionic, no peroxide); (B) Br₂ to cis-2-butene (ionic); (C) H₂O₂/NaOH after BH₃ addition to cis-2-butene (i.e., hydroboration-oxidation); (D) Cold KMnO₄ to cis-2-butene (Baeyer's reagent)."),
  callout("Solution", "(A) HBr, no peroxide: Markovnikov addition through a carbocation intermediate. The planar cation can be attacked from either face → no stereocontrol (racemic product). (B) Br₂: anti addition via bromonium ion. Br⁻ attacks from the face opposite the bromonium → anti addition → gives the meso-2,3-dibromobutane from cis-2-butene. (C) Hydroboration (BH₃): syn addition (H and B add to the same face of the alkene in the concerted 4-centre TS). Oxidation then replaces B with OH with retention → overall syn addition of H and OH → the diol (or alcohol) stereochemistry reflects the syn addition. For cis-2-butene: syn addition gives the (2R,3R) and (2S,3S) pair of butane-2,3-diol — the anti (threo) diastereomer... wait: syn addition to cis-2-butene: both H and OH add to the same face; if BH₃ adds from the bottom face, H goes to the bottom of one carbon and B to the bottom of the other, giving after oxidation the (R,S) meso diol for the syn-from-same-face addition to cis-2-butene. (D) Cold KMnO₄: the osmium tetroxide/permanganate oxidation occurs via a cyclic osmate/manganate diester intermediate: both oxygens are delivered to the same face (syn) of the alkene. Product from cis-2-butene is the meso-2,3-butanediol (syn addition). Summary: A = no stereocontrol; B = anti; C = syn; D = syn."),

  sub("Q19 — Terminal alkyne to aldehyde vs ketone (JEE/NEET)"),
  p("Hex-1-yne (HC≡C-CH₂CH₂CH₂CH₃) reacts under two different conditions: (A) H₂SO₄, HgSO₄, H₂O at 80°C; (B) BH₃·THF, then H₂O₂/NaOH. For each, write the major organic product and explain the enol intermediate."),
  callout("Solution", "(A) Mercury-catalysed Markovnikov hydration: H₂O adds across the triple bond with Markovnikov orientation — OH goes to the internal carbon (C-2, bearing more substituents = more stable partial-positive charge on that carbon). Enol intermediate: hex-1-en-2-ol (=C(OH)-CH₂CH₂CH₂CH₃). The enol tautomerises to the keto form: hexan-2-one (CH₃CO-CH₂CH₂CH₂CH₃). The carbonyl is at C-2 (a methyl ketone pattern for all terminal alkynes by this method). (B) Hydroboration-oxidation: anti-Markovnikov. Boron adds to C-1 (the terminal carbon, less substituted). After oxidation: OH ends up on C-1. Enol intermediate: hex-1-en-1-ol (HO-CH=CH-CH₂CH₂CH₂CH₃ — an enol with OH on C-1). This tautomerises to: hexanal (OHC-CH₂CH₂CH₂CH₂CH₃) — the aldehyde with the carbonyl at C-1. Summary: method A gives hexan-2-one (methyl ketone); method B gives hexanal (primary aldehyde). Both pass through an enol intermediate, but tautomerism drives completely to the stable keto form in both cases."),

  sub("Q20 — Directing effect: numerical prediction (JEE Advanced)"),
  p("Toluene undergoes chlorination with Cl₂/FeCl₃. Given that the partial rate factors for the methyl group at ortho (f_o), meta (f_m), para (f_p) positions relative to benzene are: f_o = 600, f_m = 5.5, f_p = 2340 (relative to one H in benzene = 1). (a) Predict the theoretical product ratio of 2-chlorotoluene : 3-chlorotoluene : 4-chlorotoluene from these data. (b) Which product is the major product?"),
  callout("Solution", "(a) Each position of toluene: 2 ortho H atoms (C-2 and C-6 are equivalent by symmetry), 2 meta H atoms (C-3 and C-5), 1 para H atom (C-4). Product from each position is proportional to (number of equivalent H) × (partial rate factor): Ortho product (2-chlorotoluene): 2 × 600 = 1200 units. Meta product (3-chlorotoluene): 2 × 5.5 = 11 units. Para product (4-chlorotoluene): 1 × 2340 = 2340 units. Total = 1200 + 11 + 2340 = 3551 units. Product percentages: 2-chlorotoluene = 1200/3551 = 33.8%; 3-chlorotoluene = 11/3551 = 0.3%; 4-chlorotoluene = 2340/3551 = 65.9%. (b) 4-Chlorotoluene (para product) is the major product (65.9%), consistent with the methyl group being an ortho/para-director with the para position slightly preferred in practice due to the steric factor reducing ortho selectivity relative to the electronic prediction (two ortho positions × high f_o still gives less than one para position × even higher f_p). This matches experimental observations: para product is the major isomer from toluene chlorination."),

  sub("Q21 — Alkyne acidity comparison (JEE/NEET)"),
  p("Rank the following in INCREASING order of acidity (weakest first): (I) propane (CH₃CH₂CH₃); (II) propene (CH₃CH=CH₂); (III) propyne (CH₃C≡CH); (IV) water (H₂O); (V) 2-propanol (CH₃CH(OH)CH₃)."),
  callout("Solution", "Increasing acidity (weakest to strongest): I < II < III < IV ... wait: propyne pKa ≈ 25 vs water pKa = 15.7. So water is MORE acidic than propyne. And 2-propanol pKa ≈ 17, which is LESS acidic than water. Correct ranking: I < II < III < V < IV. Propane pKa ≈ 50 (sp3 C-H, no resonance, no +s-character effect): weakest. Propene pKa ≈ 44 (vinylic sp2 C-H, somewhat more acidic): still weak. Propyne pKa ≈ 25 (terminal alkyne sp C-H, highest s-character of any C-H): strongest among the hydrocarbons, but still weaker than oxygen-H bonds. 2-Propanol pKa ≈ 17 (O-H bond, oxygen is electronegative, alkoxide is delocalized... no resonance but O electronegativity alone stabilises the anion much better than carbon). Water pKa = 15.7 (more acidic than propanol because the hydroxide anion, HO⁻, is smaller and the O-H bond is slightly more polarised than a secondary alkoxide). Final ranking: I (pKa 50) < II (pKa 44) < III (pKa 25) < V (pKa 17) < IV (pKa 15.7)."),

  sub("Q22 — Cis/trans alkene from elimination (JEE Advanced stereospecificity)"),
  p("2-Bromobutane is treated with (a) KOH/EtOH (non-bulky base, E2 conditions) and (b) KOtBu/tBuOH (bulky base, E2 conditions). For each: predict the major alkene product (Zaitsev or Hofmann?) and state whether any geometric isomers form and which predominates."),
  callout("Solution", "(a) KOH/EtOH (non-bulky base): E2, Zaitsev product preferred. The more substituted alkene is trans-2-butene (has 2 alkyl groups on the double bond) vs 1-butene (monosubstituted). Zaitsev product = trans-2-butene (both methyl groups can be placed anti in the transition state, giving the trans alkene; cis-2-butene requires the methyls to be syn in the TS, sterically demanding). In practice: from 2-bromobutane, both trans-2-butene and cis-2-butene form via E2 (and 1-butene as the minor Hofmann product). Among the two-butene isomers, trans-2-butene is the major alkene because the E2 transition state with the two methyl groups anti to each other (giving trans product) is less sterically crowded than the TS with methyls syn (giving cis). Ratio: roughly 65% trans-2-butene, 25% cis-2-butene, 10% 1-butene (approximate, temperature-dependent). (b) KOtBu/tBuOH (bulky base): Hofmann product preferred. The bulky base cannot access the hydrogen on C-3 easily (the more hindered position); it preferentially removes the H from C-1 (the less hindered primary position), giving 1-butene as the major product. The geometric isomers trans/cis-2-butene are still formed but are now the minor products."),

  sub("Q23 — Synthesis using alkyne reactions (JEE Advanced multi-step)"),
  p("Propose an efficient synthesis of propan-1-ol from propyne (CH₃C≡CH) in the fewest possible steps, explaining why the given conditions work and what product each step gives."),
  callout("Solution", "Step 1: Hydroboration of propyne with BH₃·THF: anti-Markovnikov hydroboration. Boron adds to the terminal carbon (C-1), and one H adds to C-2 from the same face. The product is a vinyl borane: H₂C=CH-CH₃→B(R)₂ form... more precisely: propyne + BH₃ gives (at the alkyne stage, before tautomerisation) a vinyl borane H₂C=CH-CH₃ with B on C-1: CH₂(B)-CH=... let me be precise. BH₃ adds to C-1 (terminal) and H to C-2 (internal) in the syn fashion, giving CH₂(B)=CH-CH₃ as a vinyl borane intermediate. Step 2: H₂O₂/NaOH oxidation replaces the C-B bond with C-OH (with retention): the vinyl borane oxidises to give the enol CH₂(OH)=CH-CH₃ (prop-1-en-1-ol, an enol, with OH on C-1). Step 3: Spontaneous acid/base-catalysed tautomerisation of the enol: CH₂(OH)=CHCH₃ → CH₃-CHO-... wait, that would be propanal from CH₂(OH)=CHCH₃. Actually: the enol from anti-Markovnikov hydration of propyne is 1-propenol (CH₂=CH-... wait. Propyne is CH₃-C≡CH. Anti-Markovnikov: B goes to C-3 (the terminal carbon, the ≡CH), H goes to C-2. Vinyl borane: CH₃-CH=CH-B(R)₂ (E isomer, syn addition). Oxidation gives: CH₃-CH=CH-OH (prop-1-en-3-ol? No). After the H goes to C-2 and B to C-1 in propyne CH₃C≡CH (C-1 = the methyl-C, C-2 = the middle C, C-3 = the terminal ≡CH)... let me use 'terminal' carbon as C-1 per IUPAC: CH₃(C-3)-C≡C(C-1)H. Anti-Markovnikov: B to C-1 (terminal), H to C-2. Vinyl borane: CH₃-CH=CH-B (with B on C-1). Oxidise: CH₃-CH=CH-OH. This enol (prop-1-en-1-ol) tautomerises to propanal (CH₃CH₂CHO). So the product is propanal, NOT propan-1-ol. To get propan-1-ol from propanal: NaBH₄ reduction. Step 3: Reduce propanal with NaBH₄/EtOH → propan-1-ol. Total: 3 steps (BH₃·THF → H₂O₂/NaOH → NaBH₄). This is the correct and efficient synthesis."),

  sub("Q24 — Iodination of benzene (JEE pattern unusual EAS)"),
  p("Direct iodination of benzene with I₂ alone is very slow and does not proceed to useful yields. However, two conditions make it possible: (A) I₂ + conc. HNO₃; (B) I₂ + HIO₃ (iodate). Explain why I₂ alone is insufficient and how each condition overcomes the problem."),
  callout("Solution", "Why I₂ alone fails: the H-abstraction step of EAS (loss of H⁺ from the arenium ion) is endothermic for I₂/I⁻, because the H-I bond formed (pKa HI ≈ -10) is much weaker than the H-F, H-Cl, or H-Br bonds — meaning the reverse reaction (I⁻ acting as base to re-form starting material from the arenium ion) is competitive with the product-forming step. The iodination equilibrium therefore lies largely on the starting material side. (A) I₂ + conc. HNO₃: the nitric acid oxidises I⁻ (the byproduct of iodination) as fast as it forms, removing it from equilibrium and driving the reaction toward product: I⁻ + HNO₃ → I₂ + NO₂⁻ + H₂O (not exactly — the actual oxidation is more complex but the principle is Le Chatelier's — removing the product I⁻ shifts equilibrium to the right). (B) I₂ + HIO₃: similar principle. HIO₃ oxidises I⁻ to I₂ (and is itself reduced to I⁻ or further reduced), regenerating the electrophile and removing the inhibitor. The key insight: iodination is thermodynamically unfavourable relative to other halogenations because the H-I bond is weak; the synthetic solution is to remove I⁻ immediately by oxidising it back to I₂."),

  sub("Q25 — Comprehensive: six reactions of an unknown alkene X (JEE Advanced passage type)"),
  p("Alkene X (C₅H₁₀, one degree of unsaturation) gives: (1) one product with HBr (no peroxide); (2) one racemic pair of enantiomers with Br₂/CCl₄ (anti addition); (3) one product with HBr/peroxide (one compound); (4) one product with H₂/Pd; (5) one meso compound with cold KMnO₄; (6) acetic acid + acetone on ozonolysis with oxidative workup. Identify X, justify each observation, and draw the product of reaction (2) with stereochemistry labeled."),
  callout("Solution", "From observation (6): oxidative ozonolysis gives acetic acid (CH₃COOH, 2 carbons) and acetone (CH₃COCH₃, 3 carbons). Total carbons = 2 + 3 = 5 ✓ for C₅H₁₀. The acetic acid comes from a monosubstituted carbon (RHC=, R = methyl → RCOOH = CH₃COOH). The acetone comes from a disubstituted carbon (R₂C=, with two methyls → (CH₃)₂C=O = acetone). Reconstruct X: join the two carbonyl carbons with a double bond: CH₃-CH=C(CH₃)₂ = 2-methylbut-2-ene. From (1): HBr (Markovnikov) — H adds to C-2 (the less substituted alkene carbon, with 1H), Br adds to C-3 (the quaternary-becoming carbon with no H... wait: 2-methylbut-2-ene is CH₃-CH=C(CH₃)₂. The carbons of the double bond: C-2 has one methyl and one H; C-3 has two methyls. Markovnikov: H to C-2 (less substituted), giving cation at C-3 (tertiary: (CH₃)₂C⁺-CH(CH₃)... wait: if H adds to C-2 and charge develops at C-3, the cation is (CH₃)₂C⁺-CHCH₃? Let me redo: C-2 is the carbon with one CH₃ and one H; if H⁺ adds to C-2 (giving C-2 the extra H, making it CH₂), the positive charge is at C-3 (which has two CH₃ — tertiary). Br⁻ attacks C-3 to give 2-bromo-2-methylbutane. ONE product only (no stereoisomers), consistent with observation (1). From (2): Br₂/anti addition via bromonium — gives two enantiomers of the trans-dibromide (racemic mixture) because the bromonium can open from either end/either face, giving a chiral product that is a pair of enantiomers with no meso form (since the alkene is unsymmetrical). From (3): HBr/peroxide (anti-Markovnikov radical): Br adds to C-2 (less substituted, putting radical at C-3 tertiary position, then H added from HBr), giving 3-bromo-2-methylbutane — one compound. From (4): H₂/Pd gives 2-methylbutane. From (5): cold KMnO₄ (syn diol) gives a diol with OH groups on C-2 and C-3; because the alkene is 2-methylbut-2-ene (prochiral at C-3 but C-2 has no H after diol formation... this is complex to stereodescribe without 3D structure, but the product is a single meso diol or a racemic mixture depending on the geometry — for this alkene, the syn addition of two OH groups to the disubstituted carbon and the monosubstituted carbon gives a diol that is the meso form). X = 2-methylbut-2-ene."),
];
