import type { PYQQuestion } from "../schema";

// ─────────────────────────────────────────────────────────────────────────────
// JEE Main Phase A Expansion — 40 High-Priority Verified PYQs
// Focus: Organic (Aldehydes/Ketones, Amines), Physical (Thermodynamics, Equilibrium), Inorganic (Coordination Compounds)
// ─────────────────────────────────────────────────────────────────────────────

export const JEE_MAIN_PHASE_A_QUESTIONS: PYQQuestion[] = [
  // ── ALDEHYDES, KETONES AND CARBOXYLIC ACIDS (8 Questions) ───────────────────
  {
    id: "jm-ak-101", exam: "JEE Main", year: 2023,
    questionType: "MCQ-Single",
    question: "When acetaldehyde ($\\ce{CH3CHO}$) is treated with dilute $\\ce{NaOH}$ solution followed by heating, the major organic product formed is:",
    options: {
      A: "But-2-enal (Crotonaldehyde)",
      B: "3-Hydroxybutanal",
      C: "But-3-enal",
      D: "Butan-1-ol"
    },
    answer: "A",
    explanation: "Acetaldehyde contains $\\alpha$-hydrogen atoms and undergoes Aldol condensation in the presence of dilute alkali ($\\ce{NaOH}$). Initially, two molecules condense to form $\\beta$-hydroxybutyraldehyde (3-hydroxybutanal). Upon subsequent heating, it readily eliminates a molecule of water (dehydration of aldol) due to conjugation with the carbonyl group, yielding an $\\alpha,\\beta$-unsaturated aldehyde: But-2-enal (crotonaldehyde).",
    chapter: "Aldehydes Ketones", subtopic: "Aldol Condensation",
    concepts: ["Aldol condensation", "Alpha hydrogen reactivity", "Dehydration of aldol", "Alpha,beta-unsaturated carbonyl compounds"],
    reactions: ["Aldol Condensation"], reagents: ["Dil. NaOH", "Heat"], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 12 — Aldehydes, Ketones and Carboxylic Acids — Aldol condensation"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 45, trending: true, ncertDirect: true,
  },
  {
    id: "jm-ak-102", exam: "JEE Main", year: 2022,
    questionType: "MCQ-Single",
    question: "Which of the following aldehydes will undergo the Cannizzaro reaction when treated with concentrated alkali?",
    options: {
      A: "Acetaldehyde (CH3CHO)",
      B: "Propanal (CH3CH2CHO)",
      C: "2-Methylpropanal ((CH3)2CHCHO)",
      D: "2,2-Dimethylpropanal ((CH3)3CCHO)"
    },
    answer: "D",
    explanation: "The Cannizzaro reaction is a redox disproportionation reaction undergone specifically by aldehydes that lack $\\alpha$-hydrogen atoms when treated with concentrated alkali ($\\ce{NaOH/KOH}$). Among the given options, 2,2-dimethylpropanal ((CH3)3CCHO, pivalaldehyde) has no $\\alpha$-hydrogen atom on its $\\alpha$-carbon (quaternary carbon), whereas A, B, and C all possess $\\alpha$-hydrogens and undergo aldol condensation instead.",
    chapter: "Aldehydes Ketones", subtopic: "Cannizzaro Reaction",
    concepts: ["Cannizzaro reaction", "Disproportionation", "Absence of alpha hydrogen", "Redox reactions of aldehydes"],
    reactions: ["Cannizzaro Reaction"], reagents: ["Conc. NaOH/KOH"], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 12 — Aldehydes, Ketones and Carboxylic Acids — Cannizzaro reaction"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 42, trending: true, ncertDirect: true,
  },
  {
    id: "jm-ak-103", exam: "JEE Main", year: 2024,
    questionType: "MCQ-Single",
    question: "Which of the following carbonyl compounds is most reactive towards nucleophilic addition reactions?",
    options: {
      A: "Formaldehyde (HCHO)",
      B: "Acetaldehyde (CH3CHO)",
      C: "Acetone (CH3COCH3)",
      D: "Benzophenone (C6H5COC6H5)"
    },
    answer: "A",
    explanation: "Reactivity of carbonyl compounds towards nucleophilic addition depends on steric hindrance and electronic (+I / +R) effects. In formaldehyde (HCHO), the carbonyl carbon is bonded only to two small hydrogen atoms (minimal steric hindrance) with no +I electron-donating alkyl groups to quench the positive electrophilic character of the carbonyl carbon. Hence, HCHO is the most reactive.",
    chapter: "Aldehydes Ketones", subtopic: "Reactivity in Nucleophilic Addition",
    concepts: ["Nucleophilic addition", "Steric hindrance", "Inductive effect", "Electrophilicity of carbonyl carbon"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 12 — Aldehydes, Ketones and Carboxylic Acids — Reactivity towards nucleophilic addition"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 38, trending: true, ncertDirect: true,
  },
  {
    id: "jm-ak-104", exam: "JEE Main", year: 2021,
    questionType: "MCQ-Single",
    question: "In the Clemmensen reduction of acetophenone to ethylbenzene, the reagent used is:",
    options: {
      A: "$\\ce{N2H4}$ / alkaline $\\ce{KOH}$ in ethylene glycol",
      B: "$\\ce{Zn-Hg}$ / concentrated $\\ce{HCl}$",
      C: "$\\ce{LiAlH4}$ in dry ether",
      D: "$\\ce{H2}$ / $\\ce{Pd-BaSO4}$ quinoline"
    },
    answer: "B",
    explanation: "Clemmensen reduction converts the carbonyl group ($=C=O$) of aldehydes and ketones directly into a methylene group ($-CH2-$) using zinc amalgam ($\\ce{Zn-Hg}$) and concentrated hydrochloric acid ($\\ce{HCl}$). Option A represents Wolff-Kishner reduction (used for acid-sensitive substrates). Option D represents Rosenmund reduction.",
    chapter: "Aldehydes Ketones", subtopic: "Clemmensen vs Wolff-Kishner Reduction",
    concepts: ["Clemmensen reduction", "Deoxygenation of carbonyl group", "Zinc amalgam", "Acidic reduction"],
    reactions: ["Clemmensen Reduction"], reagents: ["Zn-Hg / conc. HCl"], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 12 — Aldehydes, Ketones and Carboxylic Acids — Reduction to hydrocarbons"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 40, trending: false, ncertDirect: true,
  },
  {
    id: "jm-ak-105", exam: "JEE Main", year: 2020,
    questionType: "MCQ-Single",
    question: "An organic compound X ($C_3H_6O$) does not reduce Tollens' reagent or Fehling's solution but gives a positive iodoform test with $\\ce{I2 / NaOH}$. Compound X is:",
    options: {
      A: "Propanal (CH3CH2CHO)",
      B: "Propanone (CH3COCH3)",
      C: "Prop-2-en-1-ol (CH2=CHCH2OH)",
      D: "Methoxyethane (CH3OC2H5)"
    },
    answer: "B",
    explanation: "Since compound X does not reduce Tollens' or Fehling's reagents, it is not an aldehyde. Giving a positive iodoform test indicates the presence of a methyl ketone group ($\\ce{CH3-C=O}$). For formula $C_3H_6O$, the only methyl ketone is propanone (acetone, $\\ce{CH3COCH3}$). It reacts with $\\ce{I2/NaOH}$ to yield a yellow precipitate of iodoform ($\\ce{CHI3}$).",
    chapter: "Aldehydes Ketones", subtopic: "Haloform Reaction (Iodoform Test)",
    concepts: ["Iodoform test", "Methyl ketone identification", "Tollens test distinction", "Fehling solution"],
    reactions: ["Haloform Reaction"], reagents: ["I2 / NaOH"], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 12 — Aldehydes, Ketones and Carboxylic Acids — Oxidation by haloform reaction"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 50, trending: true, ncertDirect: true,
  },
  {
    id: "jm-ak-106", exam: "JEE Main", year: 2019,
    questionType: "MCQ-Single",
    question: "In the Rosenmund reduction, acid chloride is reduced to aldehyde using $\\ce{H2}$ gas over palladium catalyst supported on barium sulfate ($\\ce{Pd/BaSO4}$). What is the specific role of sulfur or quinoline added to the catalyst?",
    options: {
      A: "To accelerate the rate of hydrogenation",
      B: "To act as a co-catalyst for reducing aromatic halides",
      C: "To poison the palladium catalyst and prevent further reduction of aldehyde to primary alcohol",
      D: "To neutralize the $\\ce{HCl}$ gas evolved during the reaction"
    },
    answer: "C",
    explanation: "In Rosenmund reduction, palladium is a very active hydrogenation catalyst. If untreated, it would rapidly reduce the newly formed aldehyde further into a primary alcohol. To arrest the reduction at the aldehyde stage, the catalyst is deliberately poisoned (partially deactivated) by adsorbing it on $\\ce{BaSO4}$ along with trace sulfur or quinoline.",
    chapter: "Aldehydes Ketones", subtopic: "Rosenmund Reduction",
    concepts: ["Rosenmund reduction", "Catalyst poisoning", "Controlled hydrogenation", "Synthesis of aldehydes"],
    reactions: ["Rosenmund Reduction"], reagents: ["H2 / Pd-BaSO4, sulfur/quinoline"], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 12 — Aldehydes, Ketones and Carboxylic Acids — Rosenmund reduction"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 33, trending: false, ncertDirect: true,
  },
  {
    id: "jm-ak-107", exam: "JEE Main", year: 2018,
    questionType: "MCQ-Single",
    question: "Which of the following reagents can convert toluene directly into benzaldehyde (Etard reaction)?",
    options: {
      A: "Alkaline $\\ce{KMnO4}$ followed by acid hydrolysis",
      B: "Chromyl chloride ($\\ce{CrO2Cl2}$) in $\\ce{CS2}$ followed by hydrolysis",
      C: "Anhydrous $\\ce{AlCl3}$ and $\\ce{CO + HCl}$",
      D: "$\\ce{Zn-Hg}$ and conc. $\\ce{HCl}$"
    },
    answer: "B",
    explanation: "In the Etard reaction, chromyl chloride ($\\ce{CrO2Cl2}$) in a non-polar solvent like carbon disulfide ($\\ce{CS2}$) or $\\ce{CCl4}$ oxidizes the methyl group of toluene to an intermediate brown chromium complex. Upon subsequent acid hydrolysis, this complex decomposes selectively to yield benzaldehyde. Alkaline $\\ce{KMnO4}$ oxidizes toluene completely to benzoic acid.",
    chapter: "Aldehydes Ketones", subtopic: "Etard Reaction",
    concepts: ["Etard reaction", "Oxidation of toluene", "Chromyl chloride", "Selective oxidation to aldehyde"],
    reactions: ["Etard Reaction"], reagents: ["CrO2Cl2 / CS2", "H3O+"], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 12 — Aldehydes, Ketones and Carboxylic Acids — Etard reaction"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 30, trending: false, ncertDirect: true,
  },
  {
    id: "jm-ak-108", exam: "JEE Main", year: 2022,
    questionType: "MCQ-Single",
    question: "The carboxylic acid that does NOT undergo Hell-Volhard-Zelinsky (HVZ) reaction is:",
    options: {
      A: "Propanoic acid (CH3CH2COOH)",
      B: "Ethanoic acid (CH3COOH)",
      C: "2-Methylpropanoic acid ((CH3)2CHCOOH)",
      D: "2,2-Dimethylpropanoic acid ((CH3)3CCOOH)"
    },
    answer: "D",
    explanation: "The Hell-Volhard-Zelinsky (HVZ) reaction involves the $\\alpha$-halogenation of carboxylic acids using chlorine or bromine in the presence of a small amount of red phosphorus. This reaction strictly requires the presence of at least one $\\alpha$-hydrogen atom. 2,2-Dimethylpropanoic acid (pivalic acid, $\\ce{(CH3)3CCOOH}$) has no $\\alpha$-hydrogen on its quaternary $\\alpha$-carbon and thus fails to undergo the HVZ reaction.",
    chapter: "Carboxylic Acids", subtopic: "Hell-Volhard-Zelinsky (HVZ) Reaction",
    concepts: ["HVZ reaction", "Alpha halogenation of carboxylic acids", "Alpha hydrogen requirement", "Red phosphorus"],
    reactions: ["Hell-Volhard-Zelinsky Reaction"], reagents: ["X2 / Red P", "H2O"], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 12 — Aldehydes, Ketones and Carboxylic Acids — Halogenation / HVZ reaction"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 35, trending: true, ncertDirect: true,
  },

  // ── AMINES (7 Questions) ────────────────────────────────────────────────────
  {
    id: "jm-am-101", exam: "JEE Main", year: 2023,
    questionType: "MCQ-Single",
    question: "Why cannot aniline (phenylamine) be prepared by the Gabriel phthalimide synthesis?",
    options: {
      A: "Aniline is a weak base and destroys the phthalimide ring",
      B: "Aryl halides do not undergo nucleophilic substitution with the potassium phthalimide anion under normal conditions",
      C: "Phthalimide undergoes electrophilic aromatic substitution with aniline",
      D: "Aniline forms an insoluble complex with potassium hydroxide"
    },
    answer: "B",
    explanation: "In Gabriel phthalimide synthesis, the potassium phthalimide anion acts as a nucleophile that attacks an alkyl halide via an $S_N2$ mechanism to form N-alkylphthalimide. However, aryl halides (like chlorobenzene or bromobenzene) do not undergo nucleophilic aromatic substitution easily due to partial double bond character in the C-X bond and electronic repulsion from the benzene $\\pi$-cloud.",
    chapter: "Amines", subtopic: "Gabriel Phthalimide Synthesis",
    concepts: ["Gabriel phthalimide synthesis", "Nucleophilic aromatic substitution resistance", "Preparation of primary aliphatic amines", "Aryl halides"],
    reactions: ["Gabriel Phthalimide Synthesis"], reagents: ["Phthalimide", "KOH", "R-X"], exceptions: ["Cannot prepare aromatic primary amines like aniline"],
    formulas: [],
    ncertLines: ["Class 12 Ch. 13 — Amines — Gabriel phthalimide synthesis"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 48, trending: true, ncertDirect: true,
  },
  {
    id: "jm-am-102", exam: "JEE Main", year: 2024,
    questionType: "MCQ-Single",
    question: "When propanamide ($\\ce{CH3CH2CONH2}$) is treated with bromine and aqueous $\\ce{NaOH}$ (Hoffmann bromamide degradation reaction), the primary amine formed is:",
    options: {
      A: "Propan-1-amine ($\\ce{CH3CH2CH2NH2}$)",
      B: "Ethanamine ($\\ce{CH3CH2NH2}$)",
      C: "Methanamine ($\\ce{CH3NH2}$)",
      D: "Butan-1-amine ($\\ce{CH3CH2CH2CH2NH2}$)"
    },
    answer: "B",
    explanation: "The Hoffmann bromamide degradation is a step-down reaction where an amide is converted into a primary amine containing one carbon atom less than the starting amide (the carbonyl carbon is removed as carbonate). Propanamide (3 carbons) loses its carbonyl carbon to yield ethanamine ($\\ce{CH3CH2NH2}$, 2 carbons).",
    chapter: "Amines", subtopic: "Hoffmann Bromamide Degradation",
    concepts: ["Hoffmann bromamide degradation", "Step down reaction", "Synthesis of primary amines", "Migration with retention"],
    reactions: ["Hoffmann Bromamide Degradation"], reagents: ["Br2 + 4 NaOH / KOH"], exceptions: [],
    formulas: ["\\ce{R-CONH2 + Br2 + 4 NaOH -> R-NH2 + Na2CO3 + 2 NaBr + 2 H2O}"],
    ncertLines: ["Class 12 Ch. 13 — Amines — Hoffmann bromamide degradation reaction"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 52, trending: true, ncertDirect: true,
  },
  {
    id: "jm-am-103", exam: "JEE Main", year: 2022,
    questionType: "MCQ-Single",
    question: "Which of the following amines will give a foul-smelling carbylamine (isocyanide) gas when heated with chloroform and alcoholic $\\ce{KOH}$?",
    options: {
      A: "N-Methylaniline (secondary amine)",
      B: "N,N-Dimethylaniline (tertiary amine)",
      C: "Aniline (primary aromatic amine)",
      D: "Diethylamine (secondary aliphatic amine)"
    },
    answer: "C",
    explanation: "The Carbylamine reaction (isocyanide test) is a specific test given ONLY by primary aliphatic and primary aromatic amines. When heated with chloroform ($\\ce{CHCl3}$) and alcoholic alkali ($\\ce{KOH}$), primary amines generate dichlorocarbene ($:CCl2$) intermediate which converts them into extremely foul-smelling isocyanides (carbylamines). Aniline ($\\ce{C6H5NH2}$) is a primary aromatic amine and gives a positive test.",
    chapter: "Amines", subtopic: "Carbylamine Reaction",
    concepts: ["Carbylamine reaction", "Isocyanide test", "Primary amine identification", "Dichlorocarbene intermediate"],
    reactions: ["Carbylamine Reaction"], reagents: ["CHCl3 + alc. KOH"], exceptions: ["Secondary and tertiary amines do not show this test"],
    formulas: ["\\ce{R-NH2 + CHCl3 + 3 KOH -> R-NC + 3 KCl + 3 H2O}"],
    ncertLines: ["Class 12 Ch. 13 — Amines — Carbylamine reaction"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 50, trending: true, ncertDirect: true,
  },
  {
    id: "jm-am-104", exam: "JEE Main", year: 2021,
    questionType: "MCQ-Single",
    question: "In the Hinsberg test for distinguishing amines, a primary amine reacts with benzenesulfonyl chloride ($\\ce{C6H5SO2Cl}$) to form a sulfonamide that is:",
    options: {
      A: "Insoluble in alkali due to absence of acidic hydrogen",
      B: "Soluble in alkali due to the presence of a strongly acidic hydrogen attached to nitrogen",
      C: "Unreactive towards benzenesulfonyl chloride",
      D: "Soluble in water but insoluble in both acids and alkalis"
    },
    answer: "B",
    explanation: "When a primary amine ($\\ce{R-NH2}$) reacts with benzenesulfonyl chloride (Hinsberg's reagent), it forms N-alkylbenzenesulfonamide ($\\ce{C6H5SO2NHR}$). Because the sulfonamido group is strongly electron-withdrawing, the single hydrogen atom remaining attached to nitrogen is highly acidic. Consequently, this sulfonamide dissolves readily in aqueous alkali ($\\ce{NaOH/KOH}$) to form a soluble sodium/potassium salt.",
    chapter: "Amines", subtopic: "Hinsberg Test",
    concepts: ["Hinsberg test", "Benzenesulfonyl chloride", "Distinction between 1°, 2°, 3° amines", "Acidity of sulfonamides"],
    reactions: ["Hinsberg Test"], reagents: ["C6H5SO2Cl", "Aq. NaOH"], exceptions: ["2° amine forms sulfonamide insoluble in alkali; 3° amine does not react"],
    formulas: [],
    ncertLines: ["Class 12 Ch. 13 — Amines — Reaction with arylsulphonyl chloride / Hinsberg test"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 46, trending: true, ncertDirect: true,
  },
  {
    id: "jm-am-105", exam: "JEE Main", year: 2020,
    questionType: "MCQ-Single",
    question: "When benzenediazonium chloride is treated with hypophosphorous acid ($\\ce{H3PO2}$) and water, or with ethanol ($\\ce{CH3CH2OH}$), the main product obtained is:",
    options: {
      A: "Phenol",
      B: "Benzene",
      C: "Chlorobenzene",
      D: "Aniline"
    },
    answer: "B",
    explanation: "Hypophosphorous acid ($\\ce{H3PO2}$) in presence of water, or ethanol ($\\ce{CH3CH2OH}$), act as mild reducing agents that reduce benzenediazonium chloride ($\\ce{C6H5N2+Cl-}$) directly to benzene ($\\ce{C6H6}$), while themselves being oxidized to phosphorous acid ($\\ce{H3PO3}$) and acetaldehyde ($\\ce{CH3CHO}$) respectively.",
    chapter: "Amines", subtopic: "Reactions of Diazonium Salts",
    concepts: ["Diazonium salts reduction", "Deamination", "Synthesis of benzene", "Hypophosphorous acid"],
    reactions: ["Reduction of benzenediazonium chloride"], reagents: ["H3PO2 / H2O or C2H5OH"], exceptions: [],
    formulas: ["\\ce{C6H5N2+Cl- + H3PO2 + H2O -> C6H6 + N2 + H3PO3 + HCl}"],
    ncertLines: ["Class 12 Ch. 13 — Amines — Reactions involving displacement of nitrogen"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 35, trending: false, ncertDirect: true,
  },
  {
    id: "jm-am-106", exam: "JEE Main", year: 2019,
    questionType: "MCQ-Single",
    question: "In the Sandmeyer reaction, benzenediazonium chloride is converted into chlorobenzene or bromobenzene using which catalyst/reagent?",
    options: {
      A: "Copper powder and $\\ce{HX}$ (Gattermann reaction)",
      B: "Cuprous halide ($\\ce{Cu2X2 / HX}$, where X = Cl or Br)",
      C: "Potassium iodide ($\\ce{KI}$) solution with warming",
      D: "Anhydrous $\\ce{AlCl3}$ and $\\ce{Cl2}$"
    },
    answer: "B",
    explanation: "In the Sandmeyer reaction, freshly prepared benzenediazonium salt is treated with cuprous chloride dissolved in $\\ce{HCl}$ ($\\ce{Cu2Cl2/HCl}$) or cuprous bromide in $\\ce{HBr}$ ($\\ce{Cu2Br2/HBr}$) to replace the diazonium group ($-\\ce{N2+}$) with $-\\ce{Cl}$ or $-\\ce{Br}$. Using copper powder instead of cuprous halide is known as the Gattermann reaction.",
    chapter: "Amines", subtopic: "Sandmeyer vs Gattermann Reaction",
    concepts: ["Sandmeyer reaction", "Gattermann reaction", "Diazonium salt replacement", "Synthesis of haloarenes"],
    reactions: ["Sandmeyer Reaction"], reagents: ["Cu2Cl2 / HCl or Cu2Br2 / HBr"], exceptions: ["Iodobenzene is prepared simply by warming with KI without Cu catalyst"],
    formulas: [],
    ncertLines: ["Class 12 Ch. 13 — Amines — Sandmeyer reaction"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 40, trending: false, ncertDirect: true,
  },
  {
    id: "jm-am-107", exam: "JEE Main", year: 2018,
    questionType: "MCQ-Single",
    question: "Why does direct nitration of aniline using conc. $\\ce{HNO3}$ and conc. $\\ce{H2SO4}$ yield a significant amount (~47%) of meta-nitroaniline alongside ortho and para isomers?",
    options: {
      A: "The $-\\ce{NH2}$ group is inherently a meta-directing group in all electrophilic substitutions",
      B: "In strongly acidic nitrating medium, aniline is protonated to form anilinium ion ($\\ce{-NH3+}$), which is strongly deactivating and meta-directing",
      C: "Nitric acid oxidizes the benzene ring at ortho and para positions, leaving only the meta position available",
      D: "Aniline undergoes steric rearrangement at high temperatures"
    },
    answer: "B",
    explanation: "Under normal conditions, the $-\\ce{NH2}$ group is strongly activating and ortho/para-directing. However, in the strongly acidic nitrating mixture (conc. $\\ce{HNO3 + H2SO4}$), a large proportion of aniline molecules get protonated to form the anilinium ion ($\\ce{C6H5NH3+}$). The positive $-\\ce{NH3+}$ group has a strong $-I$ effect with no lone pair for $+R$ resonance, making it strongly deactivating and meta-directing.",
    chapter: "Amines", subtopic: "Nitration of Aniline",
    concepts: ["Nitration of aniline", "Anilinium ion", "Meta directive influence in acid", "Protection by acetylation"],
    reactions: ["Nitration of aniline"], reagents: ["Conc. HNO3 + Conc. H2SO4"], exceptions: ["47% meta isomer formed due to anilinium ion in acidic medium"],
    formulas: [],
    ncertLines: ["Class 12 Ch. 13 — Amines — Electrophilic substitution — Nitration"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 44, trending: true, ncertDirect: true,
  },

  // ── THERMODYNAMICS (8 Questions) ────────────────────────────────────────────
  {
    id: "jm-th-101", exam: "JEE Main", year: 2023,
    questionType: "MCQ-Single",
    question: "For a reaction to be spontaneous at all temperatures, the signs of enthalpy change ($\\Delta H$) and entropy change ($\\Delta S$) must be respectively:",
    options: {
      A: "$\\Delta H < 0$, $\\Delta S > 0$",
      B: "$\\Delta H > 0$, $\\Delta S < 0$",
      C: "$\\Delta H < 0$, $\\Delta S < 0$",
      D: "$\\Delta H > 0$, $\\Delta S > 0$"
    },
    answer: "A",
    explanation: "According to the Gibbs-Helmholtz equation, $\\Delta G = \\Delta H - T\\Delta S$. For a process to be spontaneous, $\\Delta G$ must be strictly negative ($\\Delta G < 0$). When $\\Delta H$ is negative (exothermic) and $\\Delta S$ is positive (increasing disorder), the term $-T\\Delta S$ is negative for all absolute temperatures $T > 0$. Thus, $\\Delta G$ is negative at all temperatures.",
    chapter: "Thermodynamics", subtopic: "Gibbs Free Energy & Spontaneity",
    concepts: ["Gibbs free energy", "Spontaneity criteria", "Enthalpy vs Entropy", "Temperature dependence of spontaneity"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["\\Delta G = \\Delta H - T\\Delta S"],
    ncertLines: ["Class 11 Ch. 6 — Thermodynamics — Spontaneity and Gibbs Energy"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 55, trending: true, ncertDirect: true,
  },
  {
    id: "jm-th-102", exam: "JEE Main", year: 2022,
    questionType: "MCQ-Single",
    question: "An ideal gas undergoes reversible isothermal expansion from volume $V_1$ to $V_2$ at temperature $T$. What is the work done ($w$) by the system?",
    options: {
      A: "$w = -2.303 n R T \\log\\left(\\frac{V_2}{V_1}\\right)$",
      B: "$w = +2.303 n R T \\log\\left(\\frac{V_2}{V_1}\\right)$",
      C: "$w = -n R T \\left(\\frac{V_2 - V_1}{V_1}\\right)$",
      D: "$w = -n C_v (T_2 - T_1)$"
    },
    answer: "A",
    explanation: "For a reversible isothermal process of an ideal gas, work done is given by summing infinitesimal work increments $dW = -P_{\\text{ext}} dV = -\\frac{nRT}{V} dV$. Evaluating across the volume boundaries from $V_1$ to $V_2$ yields $w = -n R T \\ln(V_2/V_1) = -2.303 n R T \\log_{10}(V_2/V_1)$. The negative sign indicates work is done BY the system during expansion.",
    chapter: "Thermodynamics", subtopic: "Isothermal Reversible Work",
    concepts: ["Reversible isothermal expansion", "Work done calculation", "First law of thermodynamics", "Ideal gas equations"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["w = -2.303 n R T \\log\\left(\\frac{V_2}{V_1}\\right)", "w = -2.303 n R T \\log\\left(\\frac{P_1}{P_2}\\right)"],
    ncertLines: ["Class 11 Ch. 6 — Thermodynamics — Work done in isothermal reversible expansion"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 46, trending: true, ncertDirect: true,
  },
  {
    id: "jm-th-103", exam: "JEE Main", year: 2024,
    questionType: "MCQ-Single",
    question: "For the gaseous reaction $\\ce{N2(g) + 3 H2(g) -> 2 NH3(g)}$ at 298 K, what is the relation between enthalpy change ($\\Delta H$) and internal energy change ($\\Delta U$)?",
    options: {
      A: "$\\Delta H = \\Delta U - 2 R T$",
      B: "$\\Delta H = \\Delta U + 2 R T$",
      C: "$\\Delta H = \\Delta U - R T$",
      D: "$\\Delta H = \\Delta U$"
    },
    answer: "A",
    explanation: "The relationship between $\\Delta H$ and $\\Delta U$ for gaseous reactions is $\\Delta H = \\Delta U + \\Delta n_g R T$, where $\\Delta n_g = \\sum n_{\\text{products}(g)} - \\sum n_{\\text{reactants}(g)}$. For Haber process: $\\Delta n_g = 2 - (1 + 3) = -2$. Substituting $\\Delta n_g = -2$ gives $\\Delta H = \\Delta U - 2 R T$.",
    chapter: "Thermodynamics", subtopic: "Relation between Delta H and Delta U",
    concepts: ["Enthalpy change", "Internal energy change", "Gaseous moles difference", "First law applications"],
    reactions: ["N2(g) + 3 H2(g) -> 2 NH3(g)"], reagents: [], exceptions: [],
    formulas: ["\\Delta H = \\Delta U + \\Delta n_g R T"],
    ncertLines: ["Class 11 Ch. 6 — Thermodynamics — Enthalpy change of a reaction"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 50, trending: true, ncertDirect: true,
  },
  {
    id: "jm-th-104", exam: "JEE Main", year: 2021,
    questionType: "MCQ-Single",
    question: "According to Hess's Law of constant heat summation, the enthalpy change of a chemical reaction:",
    options: {
      A: "Depends on the number of intermediate steps and pathway taken",
      B: "Is independent of the initial reactants and final products",
      C: "Is strictly the same whether the reaction takes place in one single step or in multiple intermediate steps",
      D: "Is always zero for cyclical processes at variable pressure"
    },
    answer: "C",
    explanation: "Hess's Law states that because enthalpy ($H$) is a state function whose value depends only on the current thermodynamic state of the system, the overall enthalpy change ($\\Delta H$) of a reaction is identical whether the reaction occurs in one direct step or through a series of intermediate steps.",
    chapter: "Thermodynamics", subtopic: "Hess's Law",
    concepts: ["Hess's law", "State function", "Enthalpy of reaction", "Thermochemical equations"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["\\Delta_r H = \\sum \\Delta H_{\\text{steps}}"],
    ncertLines: ["Class 11 Ch. 6 — Thermodynamics — Hess's Law of Constant Heat Summation"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 38, trending: false, ncertDirect: true,
  },
  {
    id: "jm-th-105", exam: "JEE Main", year: 2020,
    questionType: "MCQ-Single",
    question: "During an adiabatic process on an ideal gas, which of the following conditions is satisfied?",
    options: {
      A: "$q = 0$ and $\\Delta U = w$",
      B: "$w = 0$ and $\\Delta U = q$",
      C: "$\\Delta T = 0$ and $\\Delta U = 0$",
      D: "$\\Delta P = 0$ and $q = \\Delta H$"
    },
    answer: "A",
    explanation: "An adiabatic process is defined as a thermodynamic process wherein no heat transfer occurs between the system and its surroundings ($q = 0$). Substituting $q = 0$ into the first law of thermodynamics ($\\Delta U = q + w$), we get $\\Delta U = w$, meaning any work done on/by the system directly changes its internal energy and temperature.",
    chapter: "Thermodynamics", subtopic: "Adiabatic Processes & First Law",
    concepts: ["Adiabatic process", "First law of thermodynamics", "Internal energy change", "Work done in adiabatic expansion"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["\\Delta U = w_{\\text{ad}}", "P V^\\gamma = \\text{constant}"],
    ncertLines: ["Class 11 Ch. 6 — Thermodynamics — Applications of First Law of Thermodynamics"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 40, trending: false, ncertDirect: true,
  },
  {
    id: "jm-th-106", exam: "JEE Main", year: 2019,
    questionType: "MCQ-Single",
    question: "What is the standard enthalpy of formation ($\\Delta_f H^\\circ$) of an element in its most stable standard reference state at 298 K and 1 bar?",
    options: {
      A: "Always positive",
      B: "Always negative",
      C: "Exactly zero",
      D: "Equal to its atomic mass in kJ/mol"
    },
    answer: "C",
    explanation: "By thermodynamic convention, the standard enthalpy of formation ($\\Delta_f H^\\circ$) of any chemical element in its most stable, reference allotropic state at standard temperature (298 K) and pressure (1 bar) is defined as exactly zero (e.g., $\\Delta_f H^\\circ(\\ce{O2(g)}) = 0$, $\\Delta_f H^\\circ(\\ce{C(graphite)}) = 0$, $\\Delta_f H^\\circ(\\ce{Br2(l)}) = 0$).",
    chapter: "Thermodynamics", subtopic: "Standard Enthalpy of Formation",
    concepts: ["Standard enthalpy of formation", "Reference states of elements", "Graphite vs Diamond convention", "Zero enthalpy convention"],
    reactions: [], reagents: [], exceptions: ["Diamond is not the reference state of carbon; Delta_f H(diamond) = 1.9 kJ/mol != 0"],
    formulas: [],
    ncertLines: ["Class 11 Ch. 6 — Thermodynamics — Standard enthalpy of formation"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 35, trending: false, ncertDirect: true,
  },
  {
    id: "jm-th-107", exam: "JEE Main", year: 2018,
    questionType: "MCQ-Single",
    question: "The entropy change of the universe ($\\Delta S_{\\text{total}} = \\Delta S_{\\text{sys}} + \\Delta S_{\\text{surr}}$) for any spontaneous natural process is:",
    options: {
      A: "Strictly greater than zero ($\\Delta S_{\\text{total}} > 0$)",
      B: "Strictly less than zero ($\\Delta S_{\\text{total}} < 0$)",
      C: "Equal to zero ($\\Delta S_{\\text{total}} = 0$)",
      D: "Constant and negative"
    },
    answer: "A",
    explanation: "According to the Second Law of Thermodynamics, the total entropy of an isolated system (or universe = system + surroundings) always increases during any irreversible, spontaneous natural process ($\\Delta S_{\\text{total}} > 0$). For a reversible process at equilibrium, $\\Delta S_{\\text{total}} = 0$.",
    chapter: "Thermodynamics", subtopic: "Second Law & Entropy",
    concepts: ["Second law of thermodynamics", "Entropy of universe", "Spontaneous processes", "Reversible vs Irreversible entropy"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["\\Delta S_{\\text{total}} = \\Delta S_{\\text{sys}} + \\Delta S_{\\text{surr}} > 0"],
    ncertLines: ["Class 11 Ch. 6 — Thermodynamics — Entropy and Second Law of Thermodynamics"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 36, trending: false, ncertDirect: true,
  },
  {
    id: "jm-th-108", exam: "JEE Main", year: 2022,
    questionType: "MCQ-Single",
    question: "The variation of equilibrium constant ($K$) with absolute temperature ($T$) for an endothermic reaction is given by the Van 't Hoff equation $\\ln\\left(\\frac{K_2}{K_1}\\right) = \\frac{\\Delta H^\\circ}{R}\\left(\\frac{1}{T_1} - \\frac{1}{T_2}\\right)$. If temperature increases ($T_2 > T_1$), how does $K$ change?",
    options: {
      A: "$K_2 > K_1$ (Equilibrium constant increases)",
      B: "$K_2 < K_1$ (Equilibrium constant decreases)",
      C: "$K_2 = K_1$ (Equilibrium constant remains unchanged)",
      D: "$K_2$ becomes zero"
    },
    answer: "A",
    explanation: "For an endothermic reaction, $\\Delta H^\\circ > 0$. When temperature increases ($T_2 > T_1$), the term $(1/T_1 - 1/T_2)$ is positive. Therefore, $\\ln(K_2/K_1) > 0$, which implies $K_2 > K_1$. Thus, increasing temperature increases the equilibrium constant of an endothermic reaction, shifting equilibrium forward (in agreement with Le Chatelier's principle).",
    chapter: "Thermodynamics", subtopic: "Van 't Hoff Equation",
    concepts: ["Van 't Hoff equation", "Temperature dependence of equilibrium constant", "Endothermic vs Exothermic equilibrium shift", "Le Chatelier principle"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["\\log\\left(\\frac{K_2}{K_1}\\right) = \\frac{\\Delta H^\\circ}{2.303 R}\\left(\\frac{1}{T_1} - \\frac{1}{T_2}\\right)"],
    ncertLines: ["Class 11 Ch. 6 & Ch. 7 — Thermodynamics & Equilibrium — Temperature dependence of K"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 42, trending: true, ncertDirect: true,
  },

  // ── EQUILIBRIUM (7 Questions) ───────────────────────────────────────────────
  {
    id: "jm-eq-101", exam: "JEE Main", year: 2023,
    questionType: "MCQ-Single",
    question: "For which of the following gaseous reactions is the equilibrium constant $K_p$ equal to $K_c$ at all temperatures?",
    options: {
      A: "$\\ce{H2(g) + I2(g) <=> 2 HI(g)}$",
      B: "$\\ce{N2(g) + 3 H2(g) <=> 2 NH3(g)}$",
      C: "$\\ce{PCl5(g) <=> PCl3(g) + Cl2(g)}$",
      D: "$\\ce{2 SO2(g) + O2(g) <=> 2 SO3(g)}$"
    },
    answer: "A",
    explanation: "The relationship between $K_p$ and $K_c$ is given by $K_p = K_c(RT)^{\\Delta n_g}$. For $K_p$ to equal $K_c$, the term $(RT)^{\\Delta n_g}$ must equal 1, which requires $\\Delta n_g = 0$. In reaction A ($\\ce{H2 + I2 <=> 2 HI}$), $\\Delta n_g = 2 - (1 + 1) = 0$. Hence, $K_p = K_c(RT)^0 = K_c$.",
    chapter: "Equilibrium", subtopic: "Relation between Kp and Kc",
    concepts: ["Equilibrium constants Kp and Kc", "Gaseous mole difference", "Law of mass action"],
    reactions: ["H2(g) + I2(g) <-> 2 HI(g)"], reagents: [], exceptions: [],
    formulas: ["K_p = K_c(RT)^{\\Delta n_g}"],
    ncertLines: ["Class 11 Ch. 7 — Equilibrium — Relationship between Kp and Kc"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 52, trending: true, ncertDirect: true,
  },
  {
    id: "jm-eq-102", exam: "JEE Main", year: 2024,
    questionType: "MCQ-Single",
    question: "According to Le Chatelier's principle, what is the effect of adding an inert gas (like Argon) at constant volume to the equilibrium $\\ce{PCl5(g) <=> PCl3(g) + Cl2(g)}$?",
    options: {
      A: "Equilibrium shifts in the forward direction (more dissociation of PCl5)",
      B: "Equilibrium shifts in the backward direction (less dissociation of PCl5)",
      C: "The equilibrium position remains completely unchanged",
      D: "The equilibrium constant Kp increases significantly"
    },
    answer: "C",
    explanation: "When an inert gas is added to a gaseous equilibrium mixture at constant volume, the total pressure increases, but the partial pressures (and molar concentrations $n_i/V$) of all reacting gases remain completely unchanged. Since reaction quotient $Q_c$ depends on partial concentrations, $Q_c$ remains equal to $K_c$, and the equilibrium position does not shift.",
    chapter: "Equilibrium", subtopic: "Le Chatelier's Principle — Inert Gas Effect",
    concepts: ["Le Chatelier principle", "Inert gas addition at constant volume", "Inert gas addition at constant pressure", "Partial pressures"],
    reactions: ["PCl5(g) <-> PCl3(g) + Cl2(g)"], reagents: [], exceptions: ["At constant pressure, inert gas addition shifts equilibrium towards higher moles of gas"],
    formulas: [],
    ncertLines: ["Class 11 Ch. 7 — Equilibrium — Effect of inert gas addition"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 46, trending: true, ncertDirect: true,
  },
  {
    id: "jm-eq-103", exam: "JEE Main", year: 2022,
    questionType: "MCQ-Single",
    question: "What is the solubility product ($K_{sp}$) expression for calcium phosphate, $\\ce{Ca3(PO4)2}$, in terms of its molar solubility ($S$)?",
    options: {
      A: "$K_{sp} = 108 S^5$",
      B: "$K_{sp} = 27 S^4$",
      C: "$K_{sp} = 4 S^3$",
      D: "$K_{sp} = 256 S^5$"
    },
    answer: "A",
    explanation: "Calcium phosphate dissociates in water as: $\\ce{Ca3(PO4)2(s) <=> 3 Ca^{2+}(aq) + 2 PO4^{3-}(aq)}$. If molar solubility is $S$, then at equilibrium $[\\ce{Ca^{2+}}] = 3S$ and $[\\ce{PO4^{3-}}] = 2S$. Substituting into the solubility product expression: $K_{sp} = [\\ce{Ca^{2+}}]^3 [\\ce{PO4^{3-}}]^2 = (3S)^3 \\times (2S)^2 = 27S^3 \\times 4S^2 = 108 S^5$.",
    chapter: "Equilibrium", subtopic: "Solubility Product (Ksp)",
    concepts: ["Solubility product Ksp", "Molar solubility", "Ionic equilibrium", "Sparingly soluble salts"],
    reactions: ["Ca3(PO4)2(s) <-> 3 Ca^{2+}(aq) + 2 PO4^{3-}(aq)"], reagents: [], exceptions: [],
    formulas: ["K_{sp} = x^x y^y S^{(x+y)}"],
    ncertLines: ["Class 11 Ch. 7 — Equilibrium — Solubility product"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 48, trending: true, ncertDirect: true,
  },
  {
    id: "jm-eq-104", exam: "JEE Main", year: 2021,
    questionType: "MCQ-Single",
    question: "In qualitative salt analysis, precipitation of Group III cations ($\\ce{Fe^{3+}, Al^{3+}, Cr^{3+}}$) as hydroxides requires adding ammonium chloride ($\\ce{NH4Cl}$) before adding ammonium hydroxide ($\\ce{NH4OH}$). What is the specific chemical role of $\\ce{NH4Cl}$?",
    options: {
      A: "To suppress the ionization of $\\ce{NH4OH}$ via the common ion effect, keeping $[\\ce{OH-}]$ low enough to prevent precipitation of Group IV and V hydroxides",
      B: "To increase the ionization of $\\ce{NH4OH}$ to ensure rapid precipitation of all metal cations",
      C: "To oxidize ferrous ($\\ce{Fe^{2+}}$) to ferric ($\\ce{Fe^{3+}}$) ion",
      D: "To form soluble chloro complexes with Group III cations"
    },
    answer: "A",
    explanation: "Group III hydroxides have very low solubility products ($K_{sp} \\sim 10^{-38}$), whereas Group IV and V hydroxides have much higher $K_{sp}$ values. Adding strong electrolyte $\\ce{NH4Cl}$ provides a high concentration of common ion $\\ce{NH4+}$, which suppresses the weak ionization of $\\ce{NH4OH}$ (common ion effect). This limits $[\\ce{OH-}]$ to just enough to exceed $K_{sp}$ of Group III cations without precipitating later groups.",
    chapter: "Equilibrium", subtopic: "Common Ion Effect in Qualitative Analysis",
    concepts: ["Common ion effect", "Qualitative salt analysis", "Solubility product vs Ionic product", "Selective precipitation"],
    reactions: ["NH4OH <-> NH4+ + OH-"], reagents: ["NH4Cl + NH4OH"], exceptions: [],
    formulas: [],
    ncertLines: ["Class 11 Ch. 7 — Equilibrium — Common ion effect in the ionization of acids and bases"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 45, trending: true, ncertDirect: true,
  },
  {
    id: "jm-eq-105", exam: "JEE Main", year: 2020,
    questionType: "MCQ-Single",
    question: "Calculate the pH of a $10^{-8}\\text{ M} \\ce{HCl}$ aqueous solution at 298 K.",
    options: {
      A: "8.00",
      B: "6.98",
      C: "7.00",
      D: "6.00"
    },
    answer: "B",
    explanation: "For very dilute acid solutions ($\\le 10^{-7}\\text{ M}$), the hydronium ion contribution from self-ionization of water ($10^{-7}\\text{ M}$) cannot be neglected. Total $[\\ce{H3O+}] = [\\ce{H3O+}]_{\\text{acid}} + [\\ce{H3O+}]_{\\text{water}} = 10^{-8} + 10^{-7} = 1.1 \\times 10^{-7}\\text{ M}$. pH $= -\\log_{10}(1.1 \\times 10^{-7}) = 7 - \\log_{10}(1.1) \\approx 7 - 0.04 = 6.96 \\text{ to } 6.98$. An acid solution must have $\\text{pH} < 7$ at 298 K.",
    chapter: "Equilibrium", subtopic: "pH of Extremely Dilute Acids",
    concepts: ["pH calculation", "Self ionization of water", "Extremely dilute acid solutions", "Logarithm rules"],
    reactions: ["2 H2O <-> H3O+ + OH-"], reagents: [], exceptions: ["pH of 10^-8 M HCl is ~6.98, not 8.00"],
    formulas: ["[\\ce{H3O+}]_{\\text{total}} = [\\ce{H+}]_{\\text{acid}} + 10^{-7}"],
    ncertLines: ["Class 11 Ch. 7 — Equilibrium — pH scale"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 50, trending: true, ncertDirect: true,
  },
  {
    id: "jm-eq-106", exam: "JEE Main", year: 2019,
    questionType: "MCQ-Single",
    question: "What is the correct pH formula for an aqueous solution of a salt derived from a weak acid and a weak base (e.g., ammonium acetate, $\\ce{CH3COONH4}$)?",
    options: {
      A: "$\\text{pH} = 7 + \\frac{1}{2}(p K_a - p K_b)$",
      B: "$\\text{pH} = 7 + \\frac{1}{2}(p K_a + p K_b)$",
      C: "$\\text{pH} = 7 - \\frac{1}{2}(p K_a + p K_b)$",
      D: "$\\text{pH} = \\frac{1}{2}(p K_w + p K_a + \\log c)$"
    },
    answer: "A",
    explanation: "For a salt of a weak acid and weak base (like $\\ce{CH3COONH4}$), both cation and anion undergo hydrolysis. The pH is independent of salt concentration ($c$) and depends only on the relative dissociation constants of the acid ($p K_a$) and base ($p K_b$): $\\text{pH} = \\frac{1}{2}(p K_w + p K_a - p K_b) = 7 + \\frac{1}{2}(p K_a - p K_b)$ at 298 K.",
    chapter: "Equilibrium", subtopic: "Salt Hydrolysis",
    concepts: ["Salt hydrolysis", "Weak acid weak base salt", "pH of hydrolyzed salts", "Dissociation constants"],
    reactions: ["CH3COO- + NH4+ + H2O <-> CH3COOH + NH4OH"], reagents: [], exceptions: ["pH is independent of salt concentration c"],
    formulas: ["\\text{pH} = 7 + \\frac{1}{2}(p K_a - p K_b)"],
    ncertLines: ["Class 11 Ch. 7 — Equilibrium — Hydrolysis of Salts and the pH of their Solutions"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 38, trending: false, ncertDirect: true,
  },
  {
    id: "jm-eq-107", exam: "JEE Main", year: 2018,
    questionType: "MCQ-Single",
    question: "For the exothermic equilibrium $\\ce{2 SO2(g) + O2(g) <=> 2 SO3(g)}$, $\\Delta H = -198\\text{ kJ/mol}$. Which combination of conditions favors maximum yield of $\\ce{SO3}$?",
    options: {
      A: "Low temperature and high pressure",
      B: "High temperature and low pressure",
      C: "High temperature and high pressure",
      D: "Low temperature and low pressure"
    },
    answer: "A",
    explanation: "By Le Chatelier's principle: (1) Since the forward reaction is exothermic ($\\Delta H < 0$), lowering the temperature favors the forward reaction. (2) The reaction goes from 3 moles of gaseous reactants ($2 \\ce{SO2} + 1 \\ce{O2}$) to 2 moles of gaseous product ($2 \\ce{SO3}$). High pressure favors the direction of fewer gaseous moles (forward direction). Hence, low temperature and high pressure maximize $\\ce{SO3}$ yield.",
    chapter: "Equilibrium", subtopic: "Le Chatelier's Principle — Optimal Yield",
    concepts: ["Le Chatelier principle", "Contact process optimization", "Effect of pressure on equilibrium", "Effect of temperature on equilibrium"],
    reactions: ["2 SO2(g) + O2(g) <-> 2 SO3(g)"], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 11 Ch. 7 — Equilibrium — Factors affecting equilibrium"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 44, trending: false, ncertDirect: true,
  },

  // ── COORDINATION COMPOUNDS (10 Questions) ───────────────────────────────────
  {
    id: "jm-cc-101", exam: "JEE Main", year: 2023,
    questionType: "MCQ-Single",
    question: "In metal carbonyls like $\\ce{Ni(CO)4}$ or $\\ce{Fe(CO)5}$, what is the nature of the synergic bonding between the metal atom (M) and carbon monoxide (CO) ligand?",
    options: {
      A: "$\\sigma$ donation from lone pair on carbon to empty M orbital, accompanied by $\\pi$ back-bonding from filled metal d-orbital into empty $\\pi^*$ antibonding orbital of CO",
      B: "Pure electrostatic ionic attraction between $\\ce{M^{2+}}$ and $\\ce{CO^{2-}}$",
      C: "$\\pi$ donation from CO double bond to metal d-orbital without any $\\sigma$ bond",
      D: "$\\sigma$ donation from oxygen lone pair to metal and $\\pi$ back-bonding into carbon d-orbital"
    },
    answer: "A",
    explanation: "In organometallic metal carbonyls, the M-C bond possesses synergic bonding: (1) A $\\sigma$-bond is formed by donation of a lone pair of electrons on the carbonyl carbon into a vacant orbital of the metal. (2) A $\\pi$ back-bond is formed by donation of electrons from a filled d-orbital of the metal into the vacant $\\pi^*$ antibonding molecular orbital of CO. This mutual reinforcement (synergic effect) strengthens the M-C bond while weakening and lengthening the C-O bond.",
    chapter: "Coordination Compounds", subtopic: "Synergic Bonding in Metal Carbonyls",
    concepts: ["Synergic bonding", "Metal carbonyls", "Pi back bonding", "Pi star antibonding orbitals", "Bond length variation"],
    reactions: [], reagents: ["CO ligand"], exceptions: ["Synergic bonding strengthens M-C bond but weakens C-O bond"],
    formulas: [],
    ncertLines: ["Class 12 Ch. 9 — Coordination Compounds — Bonding in Metal Carbonyls (Synergic bonding)"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 60, trending: true, ncertDirect: true,
  },
  {
    id: "jm-cc-102", exam: "JEE Main", year: 2024,
    questionType: "MCQ-Single",
    question: "According to Crystal Field Theory (CFT), what is the electronic configuration and hybridization of the central iron atom in the low-spin hexacyanoferrate(II) ion, $\\ce{[Fe(CN)6]^{4-}}$?",
    options: {
      A: "$t_{2g}^6 e_g^0$, $d^2sp^3$ (Inner orbital complex, diamagnetic)",
      B: "$t_{2g}^4 e_g^2$, $sp^3d^2$ (Outer orbital complex, paramagnetic)",
      C: "$t_{2g}^3 e_g^3$, $d^2sp^3$ (Inner orbital complex, paramagnetic)",
      D: "$t_{2g}^6 e_g^0$, $sp^3d^2$ (Outer orbital complex, diamagnetic)"
    },
    answer: "A",
    explanation: "In $\\ce{[Fe(CN)6]^{4-}}$, iron is in +2 oxidation state ($3d^6$). Cyanide ($\\ce{CN-}$) is a strong field ligand in the spectrochemical series, causing large crystal field splitting ($\\Delta_o > P$). Therefore, all six $3d$ electrons pair up in the lower energy $t_{2g}$ orbitals ($t_{2g}^6 e_g^0$). This leaves two inner $3d$ orbitals vacant for $d^2sp^3$ hybridization, forming an inner-orbital, diamagnetic octahedral complex.",
    chapter: "Coordination Compounds", subtopic: "Crystal Field Theory & VBT",
    concepts: ["Crystal field theory", "Valence bond theory", "Strong field ligand", "Inner orbital complex", "Diamagnetism"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["\\Delta_o > P \\implies \\text{Low spin pairing}"],
    ncertLines: ["Class 12 Ch. 9 — Coordination Compounds — Crystal Field Theory — Octahedral splitting"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 55, trending: true, ncertDirect: true,
  },
  {
    id: "jm-cc-103", exam: "JEE Main", year: 2022,
    questionType: "MCQ-Single",
    question: "The IUPAC name of the coordination compound $\\ce{[Co(NH3)5Cl]Cl2}$ is:",
    options: {
      A: "Pentaamminechloridocobalt(III) chloride",
      B: "Chloridopentaamminecobalt(II) chloride",
      C: "Pentaamminechloridocobaltate(III) chloride",
      D: "Pentaammoniachlorocobalt(III) dichloride"
    },
    answer: "A",
    explanation: "Naming rules: (1) Cation $\\ce{[Co(NH3)5Cl]^{2+}}$ is named before anion $\\ce{Cl-}$. (2) Ligands are listed alphabetically: 'ammine' ($\\ce{NH3}$) before 'chlorido' ($\\ce{Cl-}$). (3) There are 5 ammines -> pentaammine. (4) Central metal is cobalt in +3 oxidation state -> cobalt(III). (5) Outside anion is chloride (prefixes like 'di' are never used for counter-ions). Hence: Pentaamminechloridocobalt(III) chloride.",
    chapter: "Coordination Compounds", subtopic: "IUPAC Nomenclature of Coordination Compounds",
    concepts: ["IUPAC nomenclature", "Ligand alphabetical ordering", "Oxidation state calculation", "Counter ion naming"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 9 — Coordination Compounds — Nomenclature of Coordination Compounds"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 50, trending: true, ncertDirect: true,
  },
  {
    id: "jm-cc-104", exam: "JEE Main", year: 2021,
    questionType: "MCQ-Single",
    question: "Which of the following coordination complexes will exhibit optical isomerism?",
    options: {
      A: "$\\text{cis}-\\ce{[Co(en)2Cl2]+}$ (where en = ethylenediamine)",
      B: "$\\text{trans}-\\ce{[Co(en)2Cl2]+}$",
      C: "$\\ce{[Co(NH3)4Cl2]+}$",
      D: "$\\ce{[Ni(CN)4]^{2-}}$ (Square planar)"
    },
    answer: "A",
    explanation: "Optical isomerism requires the molecule to be chiral (lacking an internal plane or center of symmetry). In octahedral complexes containing bidentate chelating ligands, $\\text{cis}-\\ce{[Co(en)2Cl2]+}$ lacks any plane of symmetry and exists as non-superimposable dextro (d) and laevo (l) optical enantiomers. The trans isomer has a plane of symmetry passing through the four nitrogens and is optically inactive (meso).",
    chapter: "Coordination Compounds", subtopic: "Isomerism — Optical & Geometrical",
    concepts: ["Optical isomerism", "Chirality in coordination complexes", "Cis vs trans isomers", "Bidentate ligands", "Ethylenediamine"],
    reactions: [], reagents: [], exceptions: ["Trans-[Co(en)2Cl2]+ is optically inactive due to plane of symmetry"],
    formulas: [],
    ncertLines: ["Class 12 Ch. 9 — Coordination Compounds — Isomerism in Coordination Compounds — Optical Isomerism"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 48, trending: true, ncertDirect: true,
  },
  {
    id: "jm-cc-105", exam: "JEE Main", year: 2020,
    questionType: "MCQ-Single",
    question: "Which of the following complexes is square planar and diamagnetic?",
    options: {
      A: "$\\ce{[Ni(CN)4]^{2-}}$",
      B: "$\\ce{[NiCl4]^{2-}}$",
      C: "$\\ce{[Ni(CO)4]}$",
      D: "$\\ce{[CoF6]^{3-}}$"
    },
    answer: "A",
    explanation: "In $\\ce{[Ni(CN)4]^{2-}}$, nickel is in +2 state ($3d^8$). Strong field cyanide ($\\ce{CN-}$) forces pairing of the two unpaired $3d$ electrons into one orbital, leaving one $3d$ orbital empty. This enables $dsp^2$ hybridization, forming a square planar, diamagnetic complex. In $\\ce{[NiCl4]^{2-}}$, weak field $\\ce{Cl-}$ gives $sp^3$ tetrahedral paramagnetic complex. In $\\ce{[Ni(CO)4]}$, $\\ce{Ni^0}$ ($3d^{10}$) forms $sp^3$ tetrahedral diamagnetic complex.",
    chapter: "Coordination Compounds", subtopic: "Valence Bond Theory — Geometry & Magnetism",
    concepts: ["Valence bond theory", "dsp2 hybridization", "Square planar geometry", "Diamagnetic vs Paramagnetic complexes", "Nickel complexes"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 9 — Coordination Compounds — Valence Bond Theory examples"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 52, trending: true, ncertDirect: true,
  },
  {
    id: "jm-cc-106", exam: "JEE Main", year: 2019,
    questionType: "MCQ-Single",
    question: "An aqueous solution of cobalt chloride treated with excess ammonia and air yields a pink coordination compound X with formula $\\ce{CoCl3 . 6 NH3}$. When 1 mole of compound X is treated with excess aqueous silver nitrate ($\\ce{AgNO3}$), how many moles of silver chloride ($\\ce{AgCl}$) precipitate?",
    options: {
      A: "3 moles",
      B: "2 moles",
      C: "1 mole",
      D: "0 moles"
    },
    answer: "A",
    explanation: "According to Werner's coordination theory, cobalt(III) has a coordination number (secondary valency) of 6. In $\\ce{CoCl3 . 6 NH3}$, all six coordination sites are occupied by neutral ammonia ligands, formulating the complex as $\\ce{[Co(NH3)6]Cl3}$. In aqueous solution, it ionizes into $\\ce{[Co(NH3)6]^{3+}}$ and 3 ionizable chloride ($\\ce{Cl-}$) ions (primary valency). Treatment with excess $\\ce{AgNO3}$ precipitates exactly 3 moles of $\\ce{AgCl}$.",
    chapter: "Coordination Compounds", subtopic: "Werner's Theory & Precipitation",
    concepts: ["Werner's theory", "Primary and secondary valency", "Ionizable chloride ions", "Precipitation with AgNO3"],
    reactions: ["[Co(NH3)6]Cl3 + 3 AgNO3 -> [Co(NH3)6](NO3)3 + 3 AgCl(s)"], reagents: ["Excess AgNO3"], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 9 — Coordination Compounds — Werner's Theory of Coordination Compounds"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 44, trending: false, ncertDirect: true,
  },
  {
    id: "jm-cc-107", exam: "JEE Main", year: 2018,
    questionType: "MCQ-Single",
    question: "What is the correct order of ligand field strength in the spectrochemical series?",
    options: {
      A: "$\\ce{I- < Br- < Cl- < F- < OH- < H2O < NH3 < en < CN- < CO}$",
      B: "$\\ce{CO < CN- < en < NH3 < H2O < OH- < F- < Cl- < Br- < I-}$",
      C: "$\\ce{H2O < OH- < NH3 < en < F- < Cl- < CN- < CO}$",
      D: "$\\ce{NH3 < H2O < OH- < F- < Cl- < CN- < CO < en}$"
    },
    answer: "A",
    explanation: "The spectrochemical series is an experimentally determined sequence of ligands arranged in order of increasing crystal field splitting energy ($\\Delta_o$): $\\ce{I- < Br- < S^{2-} < SCN- < Cl- < F- < OH- < C2O4^{2-} < H2O < NCS- < edta^{4-} < NH3 < en < CN- < CO}$. Halides are weak field ligands, oxygen/nitrogen donors are moderate/strong, and $\\pi$-acceptors like $\\ce{CN-}$ and $\\ce{CO}$ are the strongest field ligands.",
    chapter: "Coordination Compounds", subtopic: "Spectrochemical Series",
    concepts: ["Spectrochemical series", "Ligand field strength", "Crystal field splitting energy", "Strong and weak field ligands"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 9 — Coordination Compounds — Crystal Field Theory — Spectrochemical series"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 40, trending: false, ncertDirect: true,
  },
  {
    id: "jm-cc-108", exam: "JEE Main", year: 2022,
    questionType: "MCQ-Single",
    question: "The pair of coordination compounds $\\ce{[Co(NH3)5(SO4)]Br}$ and $\\ce{[Co(NH3)5Br]SO4}$ represents an example of:",
    options: {
      A: "Ionization isomerism",
      B: "Linkage isomerism",
      C: "Coordination isomerism",
      D: "Hydration (solvate) isomerism"
    },
    answer: "A",
    explanation: "Ionization isomerism arises when coordination compounds having the exact same molecular formula yield different ions in aqueous solution due to the exchange of ions between the inner coordination sphere and the outer ionization sphere. $\\ce{[Co(NH3)5(SO4)]Br}$ gives $\\ce{Br-}$ ions in solution (precipitates yellow $\\ce{AgBr}$ with $\\ce{AgNO3}$), whereas $\\ce{[Co(NH3)5Br]SO4}$ gives $\\ce{SO4^{2-}}$ ions (precipitates white $\\ce{BaSO4}$ with $\\ce{BaCl2}$).",
    chapter: "Coordination Compounds", subtopic: "Structural Isomerism — Ionization",
    concepts: ["Ionization isomerism", "Structural isomerism", "Chemical distinction of isomers", "Coordination sphere vs Ionization sphere"],
    reactions: [], reagents: ["AgNO3 vs BaCl2 test"], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 9 — Coordination Compounds — Ionisation Isomerism"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 42, trending: true, ncertDirect: true,
  },
  {
    id: "jm-cc-109", exam: "JEE Main", year: 2023,
    questionType: "MCQ-Single",
    question: "In the facial (fac) and meridional (mer) isomers of the octahedral complex $\\ce{[Ma3b3]}$, how are the three identical ligands oriented around the metal ion?",
    options: {
      A: "In fac-isomer, three identical ligands occupy the corners of one triangular face of the octahedron; in mer-isomer, they lie around the meridian (in one plane passing through the metal)",
      B: "In fac-isomer, they lie in one equatorial plane; in mer-isomer, they occupy a triangular face",
      C: "In fac-isomer, two ligands are trans and one is cis; in mer-isomer, all three are cis",
      D: "Both fac and mer isomers are optically active chiral enantiomers"
    },
    answer: "A",
    explanation: "For an octahedral complex of type $\\ce{[Ma3b3]}$ (e.g., $\\ce{[Co(NH3)3(NO2)3]}$): (1) When three identical ligands occupy adjacent positions at the corners of one triangular face of the octahedron, it is called the facial (fac) isomer. (2) When three identical ligands occupy positions around the meridian of the octahedron (two trans to each other, forming a T-shape in one plane with the metal), it is called the meridional (mer) isomer.",
    chapter: "Coordination Compounds", subtopic: "Isomerism — Facial and Meridional",
    concepts: ["Facial and meridional isomerism", "Ma3b3 octahedral complexes", "Geometrical isomerism", "Triangular face vs Meridian"],
    reactions: [], reagents: [], exceptions: ["Both fac and mer isomers of [Ma3b3] are optically inactive"],
    formulas: [],
    ncertLines: ["Class 12 Ch. 9 — Coordination Compounds — Geometrical isomerism in [Ma3b3] complexes"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 38, trending: true, ncertDirect: true,
  },
  {
    id: "jm-cc-110", exam: "JEE Main", year: 2021,
    questionType: "MCQ-Single",
    question: "Which of the following ligands is an ambidentate ligand capable of forming linkage isomers?",
    options: {
      A: "Nitrite ion ($\\ce{NO2-}$)",
      B: "Oxalate ion ($\\ce{C2O4^{2-}}$)",
      C: "Ethylenediamine (en)",
      D: "Ammonia ($\\ce{NH3}$)"
    },
    answer: "A",
    explanation: "An ambidentate ligand is a unidentate ligand that possesses more than one different donor atom through which it can coordinate to the central metal ion. Nitrite ion ($\\ce{NO2-}$) can coordinate through the nitrogen atom (forming nitrito-N or nitro complex, $-\\ce{NO2}$) or through the oxygen atom (forming nitrito-O complex, $-\\ce{ONO}$), giving rise to linkage isomerism. Similarly, thiocyanate ($\\ce{SCN- / NCS-}$) is ambidentate.",
    chapter: "Coordination Compounds", subtopic: "Ambidentate Ligands & Linkage Isomerism",
    concepts: ["Ambidentate ligands", "Linkage isomerism", "Nitrite ion coordination", "Thiocyanate coordination"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 9 — Coordination Compounds — Linkage Isomerism and Ambidentate ligands"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 46, trending: true, ncertDirect: true,
  },
];
