import type { PYQQuestion } from "../schema";

// ─────────────────────────────────────────────────────────────────────────────
// NEET Phase A Expansion — 60 High-Priority Verified PYQs
// Focus: Organic (GOC, Hydrocarbons), Inorganic (p-Block, d/f Block), Physical (Kinetics, Electrochemistry)
// ─────────────────────────────────────────────────────────────────────────────

export const NEET_PHASE_A_QUESTIONS: PYQQuestion[] = [
  // ── GENERAL ORGANIC CHEMISTRY (10 Questions) ────────────────────────────────
  {
    id: "nt-goc-101", exam: "NEET", year: 2023,
    questionType: "MCQ-Single",
    question: "Which of the following carbocations is the most stable?",
    options: {
      A: "(CH3)3C+",
      B: "(CH3)2CH+",
      C: "CH3CH2+",
      D: "C6H5CH2+"
    },
    answer: "D",
    explanation: "Benzyl carbocation (C6H5CH2+) is exceptionally stabilized by resonance involving the aromatic ring, delocalizing the positive charge over the ortho and para positions. While (CH3)3C+ has 9 hyperconjugative structures, resonance stabilization in benzyl carbocation makes it thermodynamically more stable under standard protic solvent conditions.",
    chapter: "General Organic Chemistry", subtopic: "Carbocation Stability",
    concepts: ["Resonance effect", "Hyperconjugation", "Carbocation stability"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 11 Ch. 12 — Reaction Intermediates — Carbocations"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 32, trending: true, ncertDirect: true,
  },
  {
    id: "nt-goc-102", exam: "NEET", year: 2022,
    questionType: "MCQ-Single",
    question: "The correct order of acidic strength of the following carboxylic acids is:\nI. FCH2COOH\nII. ClCH2COOH\nIII. BrCH2COOH\nIV. CH3COOH",
    options: {
      A: "I > II > III > IV",
      B: "IV > III > II > I",
      C: "I > III > II > IV",
      D: "II > I > III > IV"
    },
    answer: "A",
    explanation: "The -I (electron-withdrawing inductive effect) increases the acidity of carboxylic acids by stabilizing the carboxylate conjugate base. The electronegativity order of halogens is F > Cl > Br. Therefore, the -I effect follows the order FCH2- > ClCH2- > BrCH2- > CH3- (which has +I effect). Hence, the acidic strength order is I > II > III > IV.",
    chapter: "General Organic Chemistry", subtopic: "Inductive Effect & Acidity",
    concepts: ["Inductive effect", "Acidity of carboxylic acids", "Electronegativity"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 11 Ch. 12 — Electronic Displacements in Covalent Bonds — Inductive Effect"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 28, trending: true, ncertDirect: true,
  },
  {
    id: "nt-goc-103", exam: "NEET", year: 2024,
    questionType: "MCQ-Single",
    question: "Among the following compounds, the one that is non-aromatic is:",
    options: {
      A: "Benzene",
      B: "Cyclopentadienyl anion",
      C: "Cycloheptatrienyl cation",
      D: "Cyclooctatetraene"
    },
    answer: "D",
    explanation: "According to Hückel's rule of aromaticity, a compound must be cyclic, planar, fully conjugated, and possess (4n + 2) π electrons. Cyclooctatetraene has 8 π electrons (4n system where n=2). To avoid anti-aromatic destabilization, it adopts a non-planar tub conformation, rendering it non-aromatic.",
    chapter: "General Organic Chemistry", subtopic: "Aromaticity",
    concepts: ["Hückel's rule", "Aromaticity", "Non-aromatic compounds", "Tub conformation"],
    reactions: [], reagents: [], exceptions: ["Cyclooctatetraene is non-planar (tub shape)"],
    formulas: ["(4n + 2) π electrons"],
    ncertLines: ["Class 11 Ch. 13 — Aromatic Hydrocarbons — Hückel's Rule"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 25, trending: true, ncertDirect: true,
  },
  {
    id: "nt-goc-104", exam: "NEET", year: 2021,
    questionType: "MCQ-Single",
    question: "The IUPAC name of the compound CH3–CH(OH)–CH2–CH(CH3)–COOH is:",
    options: {
      A: "4-Hydroxy-2-methylpentanoic acid",
      B: "2-Hydroxy-4-methylpentanoic acid",
      C: "4-Methyl-2-hydroxypentanoic acid",
      D: "2-Methyl-4-hydroxypentanoic acid"
    },
    answer: "A",
    explanation: "The principal functional group is carboxylic acid (-COOH), which receives carbon number 1. Numbering the chain: C1(COOH)-C2(CH3)-C3H2-C4(OH)-C5H3. The substituents are hydroxy at C4 and methyl at C2. Alphabetically, 'hydroxy' precedes 'methyl'. Thus, the IUPAC name is 4-hydroxy-2-methylpentanoic acid.",
    chapter: "General Organic Chemistry", subtopic: "IUPAC Nomenclature",
    concepts: ["IUPAC nomenclature", "Priority order of functional groups", "Alphabetical ordering of prefixes"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 11 Ch. 12 — Nomenclature of Organic Compounds"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 35, trending: false, ncertDirect: true,
  },
  {
    id: "nt-goc-105", exam: "NEET", year: 2020,
    questionType: "MCQ-Single",
    question: "Which of the following species is an electrophile?",
    options: {
      A: "NH3",
      B: "H2O",
      C: "BF3",
      D: "ROH"
    },
    answer: "C",
    explanation: "An electrophile is an electron-deficient species capable of accepting an electron pair. In BF3, boron has only 6 electrons in its valence shell (incomplete octet) and possesses an empty p-orbital, making it a strong Lewis acid and electrophile. NH3, H2O, and ROH contain lone pairs on central atoms, acting as nucleophiles.",
    chapter: "General Organic Chemistry", subtopic: "Electrophiles & Nucleophiles",
    concepts: ["Electrophiles", "Lewis acids", "Incomplete octet"],
    reactions: [], reagents: ["BF3"], exceptions: [],
    formulas: [],
    ncertLines: ["Class 11 Ch. 12 — Nucleophiles and Electrophiles"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 30, trending: false, ncertDirect: true,
  },
  {
    id: "nt-goc-106", exam: "NEET", year: 2019,
    questionType: "MCQ-Single",
    question: "How many structural isomers are possible for the molecular formula C4H10O that are alcohols?",
    options: {
      A: "2",
      B: "3",
      C: "4",
      D: "5"
    },
    answer: "C",
    explanation: "For C4H10O alcohols, four structural isomers exist:\n1. Butan-1-ol (CH3CH2CH2CH2OH)\n2. Butan-2-ol (CH3CH2CH(OH)CH3)\n3. 2-Methylpropan-1-ol ((CH3)2CHCH2OH)\n4. 2-Methylpropan-2-ol ((CH3)3COH)",
    chapter: "General Organic Chemistry", subtopic: "Structural Isomerism",
    concepts: ["Structural isomerism", "Chain isomerism", "Position isomerism", "Alcohols"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 11 Ch. 12 — Isomerism"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 22, trending: false, ncertDirect: true,
  },
  {
    id: "nt-goc-107", exam: "NEET", year: 2018,
    questionType: "MCQ-Single",
    question: "In which of the following compounds is the C–Cl bond length the shortest?",
    options: {
      A: "CH3–Cl",
      B: "CH2=CH–Cl",
      C: "CH3–CH2–Cl",
      D: "C6H5–CH2–Cl"
    },
    answer: "B",
    explanation: "In vinyl chloride (CH2=CH–Cl), the lone pair on chlorine participates in resonance with the adjacent C=C double bond, imparting partial double bond character to the C–Cl bond. Moreover, the carbon is sp2 hybridized (more electronegative and smaller than sp3 carbon). Both factors significantly shorten the C–Cl bond length compared to alkyl chlorides.",
    chapter: "General Organic Chemistry", subtopic: "Resonance & Bond Length",
    concepts: ["Resonance effect", "Partial double bond character", "Hybridization and bond length"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 11 Ch. 12 — Resonance Effect"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 19, trending: false, ncertDirect: true,
  },
  {
    id: "nt-goc-108", exam: "NEET", year: 2022,
    questionType: "MCQ-Single",
    question: "The correct statement regarding electrophilic aromatic substitution is:",
    options: {
      A: "An electron-donating group activates the ring and directs ortho/para",
      B: "An electron-withdrawing group activates the ring and directs meta",
      C: "Halogens are deactivating and meta-directing",
      D: "The nitro group is activating and ortho/para-directing"
    },
    answer: "A",
    explanation: "Electron-donating groups (e.g., -OH, -OCH3, -NH2, -CH3) release electrons via +R or +I effects, increasing electron density on the benzene ring (activating it) particularly at ortho and para positions. Halogens are deactivating due to strong -I effect but remain ortho/para-directing due to +R effect.",
    chapter: "General Organic Chemistry", subtopic: "Directive Influence",
    concepts: ["Activating and deactivating groups", "Ortho-para directors", "Meta directors"],
    reactions: ["Electrophilic Aromatic Substitution"], reagents: [], exceptions: ["Halogens are deactivating yet ortho/para directing"],
    formulas: [],
    ncertLines: ["Class 11 Ch. 13 — Directive influence of a functional group in monosubstituted benzene"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 40, trending: true, ncertDirect: true,
  },
  {
    id: "nt-goc-109", exam: "NEET", year: 2023,
    questionType: "MCQ-Single",
    question: "Which of the following compounds will exhibit geometrical (cis-trans) isomerism?",
    options: {
      A: "1-Butene",
      B: "2-Butene",
      C: "2-Methyl-2-butene",
      D: "Propene"
    },
    answer: "B",
    explanation: "Geometrical isomerism across a double bond requires each doubly bonded carbon atom to be attached to two different atoms or groups. In 2-butene (CH3-CH=CH-CH3), each olefinic carbon is bonded to one H and one CH3 group, allowing distinct cis and trans isomers. 1-butene and propene have two terminal hydrogens on C1.",
    chapter: "General Organic Chemistry", subtopic: "Geometrical Isomerism",
    concepts: ["Geometrical isomerism", "Cis-trans isomerism", "Restricted rotation"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 11 Ch. 13 — Geometrical Isomerism"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 31, trending: true, ncertDirect: true,
  },
  {
    id: "nt-goc-110", exam: "NEET", year: 2021,
    questionType: "MCQ-Single",
    question: "The basicity order of amines in aqueous solution for methyl substituted amines is:",
    options: {
      A: "3° > 2° > 1° > NH3",
      B: "2° > 1° > 3° > NH3",
      C: "2° > 3° > 1° > NH3",
      D: "1° > 2° > 3° > NH3"
    },
    answer: "B",
    explanation: "In aqueous medium, the basic strength of amines depends on three competing factors: inductive (+I) effect, hydration (solvation) of the conjugate cation by H-bonding, and steric hindrance. For methylamines, the subtle balance of these factors yields the experimental basicity order: (CH3)2NH (2°) > CH3NH2 (1°) > (CH3)3N (3°) > NH3.",
    chapter: "General Organic Chemistry", subtopic: "Basicity of Amines",
    concepts: ["Basicity of amines", "Inductive effect", "Solvation effect", "Steric hindrance"],
    reactions: [], reagents: [], exceptions: ["2° > 1° > 3° order in aqueous methylamines"],
    formulas: [],
    ncertLines: ["Class 12 Ch. 13 — Amines — Structure-Basicity relationship of amines in aqueous medium"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 38, trending: true, ncertDirect: true,
  },

  // ── HYDROCARBONS (10 Questions) ─────────────────────────────────────────────
  {
    id: "nt-hc-101", exam: "NEET", year: 2023,
    questionType: "MCQ-Single",
    question: "An alkene on ozonolysis gives a mixture of ethanal and propanone. The IUPAC name of the alkene is:",
    options: {
      A: "2-Methyl-2-butene",
      B: "2-Methyl-1-butene",
      C: "3-Methyl-2-butene",
      D: "2,3-Dimethyl-2-butene"
    },
    answer: "A",
    explanation: "Ozonolysis cleaves the C=C double bond, replacing it with carbonyl oxygen atoms (=O). Reversing this process: combine ethanal (CH3-CH=O) and propanone (O=C(CH3)2) by removing oxygen atoms and joining the carbons with a double bond: CH3-CH=C(CH3)2. Its IUPAC name is 2-methyl-2-butene.",
    chapter: "Hydrocarbons", subtopic: "Ozonolysis of Alkenes",
    concepts: ["Ozonolysis", "Alkenes", "Structure elucidation"],
    reactions: ["Ozonolysis"], reagents: ["O3", "Zn/H2O"], exceptions: [],
    formulas: [],
    ncertLines: ["Class 11 Ch. 13 — Hydrocarbons — Ozonolysis"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 34, trending: true, ncertDirect: true,
  },
  {
    id: "nt-hc-102", exam: "NEET", year: 2024,
    questionType: "MCQ-Single",
    question: "When propene is treated with HBr in the presence of peroxide, the major product obtained is:",
    options: {
      A: "2-Bromopropane",
      B: "1-Bromopropane",
      C: "1,2-Dibromopropane",
      D: "Propane"
    },
    answer: "B",
    explanation: "In the presence of peroxides (e.g., benzoyl peroxide), HBr adds to unsymmetrical alkenes via a free radical mechanism following anti-Markovnikov's rule (Kharasch effect / peroxide effect). Br radical attacks the terminal carbon to generate the more stable secondary free radical intermediate, yielding 1-bromopropane as the major product.",
    chapter: "Hydrocarbons", subtopic: "Anti-Markovnikov Addition",
    concepts: ["Peroxide effect", "Anti-Markovnikov addition", "Free radical mechanism", "Kharasch effect"],
    reactions: ["Addition of HBr to alkenes"], reagents: ["HBr", "Peroxide"], exceptions: ["Peroxide effect is observed only with HBr, not HCl or HI"],
    formulas: [],
    ncertLines: ["Class 11 Ch. 13 — Hydrocarbons — Anti Markovnikov addition or peroxide effect"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 36, trending: true, ncertDirect: true,
  },
  {
    id: "nt-hc-103", exam: "NEET", year: 2022,
    questionType: "MCQ-Single",
    question: "Which of the following alkynes will give a white precipitate when treated with ammoniacal silver nitrate solution (Tollens' reagent)?",
    options: {
      A: "2-Butyne",
      B: "1-Butyne",
      C: "2-Pentyne",
      D: "3-Hexyne"
    },
    answer: "B",
    explanation: "Terminal alkynes (containing a sp-hybridized C-H bond, such as 1-butyne, CH3CH2C≡CH) possess acidic hydrogen atoms. When treated with ammoniacal silver nitrate (Tollens' reagent), they undergo deprotonation and form a white precipitate of silver acetylide (CH3CH2C≡C-Ag+). Internal alkynes (2-butyne, 2-pentyne, 3-hexyne) lack acidic hydrogen and do not react.",
    chapter: "Hydrocarbons", subtopic: "Acidity of Alkynes",
    concepts: ["Terminal alkynes", "Acidity of alkynes", "Tollens' reagent test", "Silver acetylide"],
    reactions: ["Reaction with Tollens' reagent"], reagents: ["Ammoniacal AgNO3"], exceptions: [],
    formulas: [],
    ncertLines: ["Class 11 Ch. 13 — Hydrocarbons — Acidic character of alkyne"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 29, trending: true, ncertDirect: true,
  },
  {
    id: "nt-hc-104", exam: "NEET", year: 2021,
    questionType: "MCQ-Single",
    question: "In the Friedel-Crafts alkylation of benzene with methyl chloride, the active electrophile is:",
    options: {
      A: "CH3+",
      B: "CH3Cl",
      C: "[CH3–Cl–AlCl3]+",
      D: "AlCl4-"
    },
    answer: "A",
    explanation: "In Friedel-Crafts alkylation, anhydrous AlCl3 (a Lewis acid) coordinates with the halogen of methyl chloride (CH3Cl), heterolytically cleaving the C-Cl bond to form the methyl carbocation electrophile (CH3+) and AlCl4- tetrachloroaluminate ion.",
    chapter: "Hydrocarbons", subtopic: "Electrophilic Aromatic Substitution",
    concepts: ["Friedel-Crafts alkylation", "Electrophile generation", "Lewis acid catalyst"],
    reactions: ["Friedel-Crafts Alkylation"], reagents: ["CH3Cl", "Anhydrous AlCl3"], exceptions: [],
    formulas: [],
    ncertLines: ["Class 11 Ch. 13 — Hydrocarbons — Friedel-Crafts alkylation reaction mechanism"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 24, trending: false, ncertDirect: true,
  },
  {
    id: "nt-hc-105", exam: "NEET", year: 2020,
    questionType: "MCQ-Single",
    question: "Which of the following alkanes cannot be synthesized in high yield by the Wurtz reaction?",
    options: {
      A: "Ethane",
      B: "n-Butane",
      C: "n-Hexane",
      D: "n-Heptane"
    },
    answer: "D",
    explanation: "The Wurtz reaction involves coupling two alkyl halide molecules with sodium metal in dry ether (2 R-X + 2 Na → R-R + 2 NaX), making it suitable only for synthesizing symmetrical alkanes with an even number of carbon atoms (e.g., ethane, butane, hexane). Attempting to synthesize an unsymmetrical alkane with an odd number of carbons (like n-heptane, C7H16) requires two different alkyl halides, resulting in a complex mixture of three alkanes that is difficult to separate.",
    chapter: "Hydrocarbons", subtopic: "Wurtz Reaction",
    concepts: ["Wurtz reaction", "Synthesis of symmetrical alkanes", "Limitations of Wurtz reaction"],
    reactions: ["Wurtz Reaction"], reagents: ["Na / dry ether"], exceptions: ["Cannot synthesize methane or odd-carbon alkanes efficiently"],
    formulas: [],
    ncertLines: ["Class 11 Ch. 13 — Hydrocarbons — Wurtz reaction"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 27, trending: false, ncertDirect: true,
  },
  {
    id: "nt-hc-106", exam: "NEET", year: 2019,
    questionType: "MCQ-Single",
    question: "When acetylene (ethyne) is passed through red hot iron tube at 873 K, the product formed is:",
    options: {
      A: "Benzene",
      B: "Toluene",
      C: "Mesitylene",
      D: "Cyclooctatetraene"
    },
    answer: "A",
    explanation: "When ethyne (CH≡CH) gas is passed through a red-hot iron or quartz tube at 873 K, it undergoes cyclic polymerization (trimerization). Three molecules of ethyne combine to form a ring of benzene (3 C2H2 → C6H6).",
    chapter: "Hydrocarbons", subtopic: "Cyclic Polymerization of Alkynes",
    concepts: ["Cyclic polymerization", "Trimerization of ethyne", "Synthesis of benzene"],
    reactions: ["Cyclic polymerization of ethyne"], reagents: ["Red hot iron tube at 873 K"], exceptions: [],
    formulas: ["3 C2H2 → C6H6"],
    ncertLines: ["Class 11 Ch. 13 — Hydrocarbons — Cyclic polymerization"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 33, trending: false, ncertDirect: true,
  },
  {
    id: "nt-hc-107", exam: "NEET", year: 2018,
    questionType: "MCQ-Single",
    question: "Which of the following reagents can distinguish between 1-butyne and 2-butyne?",
    options: {
      A: "Bromine water",
      B: "Alkaline KMnO4 (Baeyer's reagent)",
      C: "Ammoniacal cuprous chloride solution",
      D: "H2 / Ni"
    },
    answer: "C",
    explanation: "1-Butyne is a terminal alkyne possessing an acidic acetylenic hydrogen, whereas 2-butyne is an internal alkyne. Ammoniacal cuprous chloride (Cu2Cl2 + NH4OH) reacts selectively with terminal alkynes to precipitate red copper acetylide (CH3CH2C≡CCu). Both 1-butyne and 2-butyne react with bromine water, alkaline KMnO4, and H2/Ni without distinction.",
    chapter: "Hydrocarbons", subtopic: "Chemical Tests for Alkynes",
    concepts: ["Terminal vs internal alkynes", "Ammoniacal cuprous chloride test", "Red precipitate of copper acetylide"],
    reactions: ["Test for terminal alkynes"], reagents: ["Ammoniacal Cu2Cl2"], exceptions: [],
    formulas: [],
    ncertLines: ["Class 11 Ch. 13 — Hydrocarbons — Distinction between terminal and non-terminal alkynes"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 22, trending: false, ncertDirect: true,
  },
  {
    id: "nt-hc-108", exam: "NEET", year: 2022,
    questionType: "MCQ-Single",
    question: "In the nitration of benzene using a mixture of concentrated HNO3 and concentrated H2SO4, the role of H2SO4 is:",
    options: {
      A: "To act as a reducing agent",
      B: "To act as an acid and protonate HNO3 to generate NO2+ electrophile",
      C: "To act as a base",
      D: "To absorb the water produced to prevent reversible hydrolysis"
    },
    answer: "B",
    explanation: "In the nitrating mixture (conc. HNO3 + conc. H2SO4), sulfuric acid is a stronger acid than nitric acid. H2SO4 protonates HNO3 to form H2NO3+, which rapidly loses a molecule of water to generate the nitronium ion (NO2+) electrophile: HNO3 + 2H2SO4 → NO2+ + 2HSO4- + H3O+. Here, HNO3 acts as a base relative to H2SO4.",
    chapter: "Hydrocarbons", subtopic: "Nitration of Benzene",
    concepts: ["Nitronium ion generation", "Electrophilic aromatic substitution", "Role of nitrating mixture"],
    reactions: ["Nitration of benzene"], reagents: ["Conc. HNO3 + Conc. H2SO4"], exceptions: ["HNO3 acts as a base relative to conc. H2SO4"],
    formulas: [],
    ncertLines: ["Class 11 Ch. 13 — Hydrocarbons — Mechanism of nitration"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 30, trending: true, ncertDirect: true,
  },
  {
    id: "nt-hc-109", exam: "NEET", year: 2023,
    questionType: "MCQ-Single",
    question: "Which of the following conformations of n-butane is the most stable around the C2–C3 bond?",
    options: {
      A: "Eclipsed",
      B: "Gauche",
      C: "Anti",
      D: "Partially eclipsed"
    },
    answer: "C",
    explanation: "In the anti-conformation of n-butane around the C2-C3 bond, the two bulky methyl groups are oriented at a dihedral angle of 180° to each other. This maximizes spatial separation, minimizing torsional strain and van der Waals steric repulsion, making it the most stable conformation.",
    chapter: "Hydrocarbons", subtopic: "Conformations of Alkanes",
    concepts: ["Conformations of n-butane", "Dihedral angle", "Torsional strain", "Steric hindrance"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 11 Ch. 13 — Hydrocarbons — Conformations of butane"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 26, trending: true, ncertDirect: true,
  },
  {
    id: "nt-hc-110", exam: "NEET", year: 2021,
    questionType: "MCQ-Single",
    question: "When 2-bromobutane is treated with alcoholic KOH, the major alkene formed is:",
    options: {
      A: "1-Butene",
      B: "trans-2-Butene",
      C: "cis-2-Butene",
      D: "2-Methylpropene"
    },
    answer: "B",
    explanation: "Dehydrohalogenation of 2-bromobutane with alcoholic KOH follows Zaitsev's (Saytzeff's) rule, where elimination occurs preferentially to yield the more highly substituted, more stable alkene: 2-butene. Between cis-2-butene and trans-2-butene, trans-2-butene is the major product because it has less steric repulsion between the two methyl groups.",
    chapter: "Hydrocarbons", subtopic: "Elimination Reactions (Zaitsev Rule)",
    concepts: ["Zaitsev's rule", "Dehydrohalogenation", "E2 elimination", "Trans alkene stability"],
    reactions: ["Dehydrohalogenation"], reagents: ["Alc. KOH"], exceptions: [],
    formulas: [],
    ncertLines: ["Class 11 Ch. 13 — Hydrocarbons — β-elimination / Zaitsev rule"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 38, trending: true, ncertDirect: true,
  },

  // ── p-BLOCK ELEMENTS (10 Questions) ─────────────────────────────────────────
  {
    id: "nt-pb-101", exam: "NEET", year: 2023,
    questionType: "MCQ-Single",
    question: "In diborane (B2H6), the structure contains:",
    options: {
      A: "Four 2-center-2-electron bonds and two 3-center-2-electron bonds",
      B: "Six 2-center-2-electron bonds",
      C: "Two 2-center-2-electron bonds and four 3-center-2-electron bonds",
      D: "Four 2-center-3-electron bonds and two 2-center-2-electron bonds"
    },
    answer: "A",
    explanation: "Diborane (B2H6) is an electron-deficient hydride. Each boron atom forms four terminal B-H bonds which are normal covalent 2-center-2-electron (2c-2e) bonds. The remaining two hydrogen atoms act as bridges between the two boron atoms, forming two banana-shaped 3-center-2-electron (3c-2e) bonds.",
    chapter: "p-Block Elements", subtopic: "Group 13 — Diborane Structure",
    concepts: ["Diborane structure", "Banana bond", "3c-2e bond", "Electron deficient compounds"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 11 Ch. 11 — The p-Block Elements — Diborane"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 39, trending: true, ncertDirect: true,
  },
  {
    id: "nt-pb-102", exam: "NEET", year: 2022,
    questionType: "MCQ-Single",
    question: "The correct order of boiling points of Group 15 hydrides is:",
    options: {
      A: "PH3 < AsH3 < SbH3 < NH3 < BiH3",
      B: "PH3 < AsH3 < NH3 < SbH3 < BiH3",
      C: "NH3 < PH3 < AsH3 < SbH3 < BiH3",
      D: "PH3 < NH3 < AsH3 < SbH3 < BiH3"
    },
    answer: "B",
    explanation: "Generally, boiling point increases down the group with increasing molecular mass and van der Waals forces (PH3 < AsH3 < SbH3 < BiH3). However, ammonia (NH3) exhibits anomalous behavior due to strong intermolecular hydrogen bonding, elevating its boiling point above PH3 and AsH3, placing it between AsH3 and SbH3: PH3 < AsH3 < NH3 < SbH3 < BiH3.",
    chapter: "p-Block Elements", subtopic: "Group 15 Hydrides",
    concepts: ["Anomalous boiling point of ammonia", "Hydrogen bonding", "van der Waals forces", "Group 15 hydrides"],
    reactions: [], reagents: [], exceptions: ["NH3 has higher boiling point than PH3 and AsH3 due to H-bonding"],
    formulas: [],
    ncertLines: ["Class 12 Ch. 7 — The p-Block Elements — Group 15 Hydrides properties table"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 35, trending: true, ncertDirect: true,
  },
  {
    id: "nt-pb-103", exam: "NEET", year: 2024,
    questionType: "MCQ-Single",
    question: "Which of the following oxoacids of sulfur contains a peroxide linkage (-O-O-)?",
    options: {
      A: "H2SO4",
      B: "H2S2O7",
      C: "H2S2O8",
      D: "H2S2O6"
    },
    answer: "C",
    explanation: "Peroxodisulfuric acid (H2S2O8, Marshall's acid) contains a peroxide linkage (-O-O-) bridging two SO3H groups: HO-S(=O)2-O-O-S(=O)2-OH. In oleum (H2S2O7), the bridge is a single oxygen (-O-). In sulfuric acid and dithionic acid (-S-S- bond), no peroxide linkage exists.",
    chapter: "p-Block Elements", subtopic: "Oxoacids of Sulfur",
    concepts: ["Oxoacids of sulfur", "Marshall's acid", "Peroxide linkage", "Oleum structure"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["H2S2O8"],
    ncertLines: ["Class 12 Ch. 7 — The p-Block Elements — Oxoacids of Sulphur"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 31, trending: true, ncertDirect: true,
  },
  {
    id: "nt-pb-104", exam: "NEET", year: 2021,
    questionType: "MCQ-Single",
    question: "What is the hybridization and molecular geometry of XeF4?",
    options: {
      A: "sp3d, Trigonal bipyramidal",
      B: "sp3d2, Square planar",
      C: "sp3d2, Octahedral",
      D: "sp3d3, Pentagonal bipyramidal"
    },
    answer: "B",
    explanation: "In XeF4, xenon has 8 valence electrons. Four electrons form 4 sigma bonds with fluorine atoms, leaving 4 electrons as 2 lone pairs. Total electron pairs = 4 + 2 = 6, corresponding to sp3d2 hybridization and octahedral electron geometry. To minimize lone pair-lone pair repulsion, the two lone pairs occupy trans positions, resulting in a square planar molecular geometry.",
    chapter: "p-Block Elements", subtopic: "Group 18 — Xenon Compounds",
    concepts: ["VSEPR theory", "Xenon fluorides", "sp3d2 hybridization", "Square planar geometry"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 7 — The p-Block Elements — Xenon-fluorine compounds"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 42, trending: true, ncertDirect: true,
  },
  {
    id: "nt-pb-105", exam: "NEET", year: 2020,
    questionType: "MCQ-Single",
    question: "Which of the following halogens has the highest negative electron gain enthalpy?",
    options: {
      A: "Fluorine (F)",
      B: "Chlorine (Cl)",
      C: "Bromine (Br)",
      D: "Iodine (I)"
    },
    answer: "B",
    explanation: "Although electronegativity decreases down Group 17, chlorine has a more negative electron gain enthalpy (-349 kJ/mol) than fluorine (-333 kJ/mol). Fluorine atom is exceptionally small, causing compact 2p orbitals to experience strong interelectronic repulsion when an incoming electron is added. In chlorine's larger 3p orbital, electron-electron repulsion is significantly lower.",
    chapter: "p-Block Elements", subtopic: "Group 17 — Electron Gain Enthalpy Exception",
    concepts: ["Electron gain enthalpy exception", "Halogens", "Interelectronic repulsion"],
    reactions: [], reagents: [], exceptions: ["Cl has higher negative electron gain enthalpy than F"],
    formulas: [],
    ncertLines: ["Class 12 Ch. 7 — The p-Block Elements — Group 17 Elements Electron Gain Enthalpy"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 45, trending: false, ncertDirect: true,
  },
  {
    id: "nt-pb-106", exam: "NEET", year: 2019,
    questionType: "MCQ-Single",
    question: "The basicity of orthophosphoric acid (H3PO4), pyrophosphoric acid (H4P2O7), and metaphosphoric acid ((HPO3)3) are respectively:",
    options: {
      A: "3, 4, 3",
      B: "3, 2, 3",
      C: "2, 4, 3",
      D: "3, 4, 1"
    },
    answer: "A",
    explanation: "Basicity of phosphorus oxoacids equals the number of ionizable P-OH bonds. In orthophosphoric acid (H3PO4), there are 3 P-OH bonds (basicity = 3). In pyrophosphoric acid (H4P2O7), there are 4 P-OH bonds (basicity = 4). In cyclic trimetaphosphoric acid (HPO3)3, there are 3 P-OH bonds (basicity = 3).",
    chapter: "p-Block Elements", subtopic: "Oxoacids of Phosphorus",
    concepts: ["Basicity of oxoacids", "Phosphorus acids", "P-OH vs P-H bonds"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["H3PO4", "H4P2O7", "(HPO3)3"],
    ncertLines: ["Class 12 Ch. 7 — The p-Block Elements — Oxoacids of Phosphorus"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 28, trending: false, ncertDirect: true,
  },
  {
    id: "nt-pb-107", exam: "NEET", year: 2018,
    questionType: "MCQ-Single",
    question: "In the structure of boric acid (H3BO3), the boron atom is:",
    options: {
      A: "sp2 hybridized and forms a planar layered structure via H-bonding",
      B: "sp3 hybridized and forms a tetrahedral structure",
      C: "sp2 hybridized and forms discrete monomeric units without H-bonding",
      D: "sp hybridized and linear"
    },
    answer: "A",
    explanation: "In orthoboric acid (H3BO3 or B(OH)3), boron is sp2 hybridized, forming planar BO3(3-) units. These units are joined together by extensive two-dimensional hydrogen bonding, forming a slippery layered sheet structure where adjacent layers are held by weak van der Waals forces.",
    chapter: "p-Block Elements", subtopic: "Group 13 — Boric Acid Structure",
    concepts: ["Boric acid structure", "sp2 hybridization", "Layered structure", "Hydrogen bonding"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["B(OH)3"],
    ncertLines: ["Class 11 Ch. 11 — The p-Block Elements — Orthoboric acid"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 24, trending: false, ncertDirect: true,
  },
  {
    id: "nt-pb-108", exam: "NEET", year: 2022,
    questionType: "MCQ-Single",
    question: "Which of the following statements about ozone (O3) is incorrect?",
    options: {
      A: "It is a thermodynamically unstable compound relative to oxygen",
      B: "The two O–O bond lengths in ozone are identical due to resonance",
      C: "It acts as a strong oxidizing agent because it easily liberates nascent oxygen",
      D: "The O–O–O bond angle in ozone is 180° (linear geometry)"
    },
    answer: "D",
    explanation: "Ozone (O3) is an angular (bent) molecule with an O-O-O bond angle of approximately 117° and identical O-O bond lengths (128 pm) due to resonance. It is not linear. Statements A, B, and C are correct: ozone is thermodynamically unstable ($\Delta H < 0, \Delta S > 0$ for decomposition to O2) and is a powerful oxidizing agent.",
    chapter: "p-Block Elements", subtopic: "Group 16 — Ozone",
    concepts: ["Ozone structure and geometry", "Resonance in ozone", "Oxidizing action of ozone", "Thermodynamic instability of O3"],
    reactions: ["O3 -> O2 + [O]"], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 7 — The p-Block Elements — Ozone"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 26, trending: true, ncertDirect: true,
  },
  {
    id: "nt-pb-109", exam: "NEET", year: 2023,
    questionType: "MCQ-Single",
    question: "Silicones are water-repelling polymers containing repeating units of:",
    options: {
      A: "(-Si-O-Si-)",
      B: "(-Si-C-Si-)",
      C: "(-Si-S-Si-)",
      D: "(-Si-N-Si-)"
    },
    answer: "A",
    explanation: "Silicones are organosilicon polymers containing repeating siloxane (-R2Si-O-SiR2-) linkages surrounded by hydrophobic organic alkyl/aryl groups (R). The siloxane (-Si-O-Si-) backbone imparts high thermal and chemical stability, while the organic side chains confer strong water-repelling (hydrophobic) properties.",
    chapter: "p-Block Elements", subtopic: "Group 14 — Silicones",
    concepts: ["Silicones", "Siloxane linkage", "Organosilicon polymers", "Hydrophobic nature"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["(-R2Si-O-)n"],
    ncertLines: ["Class 11 Ch. 11 — The p-Block Elements — Silicones"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 22, trending: true, ncertDirect: true,
  },
  {
    id: "nt-pb-110", exam: "NEET", year: 2021,
    questionType: "MCQ-Single",
    question: "In the contact process for the industrial manufacture of sulfuric acid, the catalyst used in the oxidation of SO2 to SO3 is:",
    options: {
      A: "Finely divided iron",
      B: "Vanadium pentoxide (V2O5)",
      C: "Platinized asbestos",
      D: "Nickel catalyst"
    },
    answer: "B",
    explanation: "In the Contact Process for H2SO4 manufacture, the key exothermic step is the catalytic oxidation of sulfur dioxide to sulfur trioxide (2 SO2 + O2 ⇌ 2 SO3). Vanadium pentoxide (V2O5) is the industrial catalyst used because it is resistant to arsenic poisoning and highly efficient at optimal temperature (720 K).",
    chapter: "p-Block Elements", subtopic: "Group 16 — Contact Process",
    concepts: ["Contact process", "Manufacture of sulfuric acid", "Vanadium pentoxide catalyst"],
    reactions: ["2 SO2 + O2 <-> 2 SO3"], reagents: ["V2O5 catalyst"], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 7 — The p-Block Elements — Sulphuric Acid — Manufacture"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 30, trending: false, ncertDirect: true,
  },

  // ── d AND f BLOCK ELEMENTS (10 Questions) ───────────────────────────────────
  {
    id: "nt-df-101", exam: "NEET", year: 2023,
    questionType: "MCQ-Single",
    question: "What is the spin-only magnetic moment (in Bohr Magneton, BM) of Mn2+ ion? (Atomic number of Mn = 25)",
    options: {
      A: "3.87 BM",
      B: "4.90 BM",
      C: "5.92 BM",
      D: "1.73 BM"
    },
    answer: "C",
    explanation: "Manganese (Z=25) has electronic configuration [Ar]3d5 4s2. In Mn2+, two 4s electrons are removed, leaving [Ar]3d5. In a d5 configuration, there are 5 unpaired electrons (n=5). Using the spin-only magnetic moment formula $\\mu = \\sqrt{n(n+2)} = \\sqrt{5(5+2)} = \\sqrt{35} \\approx 5.92\\text{ BM}$.",
    chapter: "d and f Block Elements", subtopic: "Magnetic Properties",
    concepts: ["Spin-only magnetic moment", "Unpaired electrons", "d-block electronic configuration"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["\\mu = \\sqrt{n(n+2)}\\text{ BM}"],
    ncertLines: ["Class 12 Ch. 8 — The d- and f-Block Elements — Magnetic Properties"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 45, trending: true, ncertDirect: true,
  },
  {
    id: "nt-df-102", exam: "NEET", year: 2022,
    questionType: "MCQ-Single",
    question: "Lanthanoid contraction is responsible for the fact that:",
    options: {
      A: "Zr and Y have about the same radius",
      B: "Zr and Nb have similar oxidation state",
      C: "Zr and Hf have almost identical ionic and atomic radii",
      D: "Zr and Zn have the same valency"
    },
    answer: "C",
    explanation: "Lanthanoid contraction refers to the steady decrease in atomic and ionic radii along the lanthanoid series due to poor shielding by 4f electrons. Consequently, elements of the 5d transition series (post-lanthanoids, e.g., Hf, Z=72, radius ~159 pm) have almost identical atomic radii to their corresponding 4d transition series elements (e.g., Zr, Z=40, radius ~160 pm), making their chemical properties remarkably similar.",
    chapter: "d and f Block Elements", subtopic: "Lanthanoid Contraction",
    concepts: ["Lanthanoid contraction", "Poor shielding of 4f electrons", "Atomic radii of 4d and 5d series", "Zr and Hf similarity"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 8 — The d- and f-Block Elements — Lanthanoid Contraction consequences"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 48, trending: true, ncertDirect: true,
  },
  {
    id: "nt-df-103", exam: "NEET", year: 2024,
    questionType: "MCQ-Single",
    question: "When acidified potassium dichromate (K2Cr2O7) solution is treated with ferrous sulfate (FeSO4), the color change observed and the chromium product formed are:",
    options: {
      A: "Orange to green; Cr3+",
      B: "Orange to yellow; CrO4(2-)",
      C: "Yellow to green; Cr2+",
      D: "Green to orange; Cr2O7(2-)"
    },
    answer: "A",
    explanation: "In acidic medium, orange dichromate ion (Cr2O7(2-), Cr in +6 oxidation state) acts as a strong oxidizing agent, oxidizing ferrous (Fe2+) to ferric (Fe3+) while itself being reduced to green chromic ion (Cr3+): Cr2O7(2-) + 6 Fe2+ + 14 H+ → 2 Cr3+ (green) + 6 Fe3+ + 7 H2O.",
    chapter: "d and f Block Elements", subtopic: "Potassium Dichromate Oxidizing Action",
    concepts: ["Potassium dichromate", "Oxidizing action in acidic medium", "Color change of transition metal ions"],
    reactions: ["Cr2O7(2-) + 6 Fe2+ + 14 H+ -> 2 Cr3+ + 6 Fe3+ + 7 H2O"], reagents: ["Acidified K2Cr2O7"], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 8 — The d- and f-Block Elements — Potassium dichromate properties"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 33, trending: true, ncertDirect: true,
  },
  {
    id: "nt-df-104", exam: "NEET", year: 2021,
    questionType: "MCQ-Single",
    question: "Which transition metal exhibits the highest oxidation state (+7) among the 3d series elements?",
    options: {
      A: "Chromium (Cr)",
      B: "Manganese (Mn)",
      C: "Iron (Fe)",
      D: "Vanadium (V)"
    },
    answer: "B",
    explanation: "Manganese (Z=25, [Ar]3d5 4s2) has 7 valence electrons across its 3d and 4s subshells. By involving all five 3d electrons and two 4s electrons in bonding (e.g., in KMnO4 or Mn2O7), manganese exhibits the maximum oxidation state of +7 among all 3d transition elements.",
    chapter: "d and f Block Elements", subtopic: "Oxidation States of 3d Series",
    concepts: ["Variable oxidation states", "Maximum oxidation state of Mn", "3d transition series"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 8 — The d- and f-Block Elements — Oxidation States"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 36, trending: false, ncertDirect: true,
  },
  {
    id: "nt-df-105", exam: "NEET", year: 2020,
    questionType: "MCQ-Single",
    question: "The catalytic activity of transition metals and their compounds is primarily ascribed to:",
    options: {
      A: "Their high density and high melting points",
      B: "Their ability to adopt multiple oxidation states and form complexes",
      C: "Their paramagnetic nature and unpaired electrons",
      D: "Their metallic bonding and ductility"
    },
    answer: "B",
    explanation: "Transition metals make excellent catalysts because they have partially filled d-orbitals which allow them to adopt variable oxidation states and form temporary coordination complexes with reactants. This lowers the activation energy of the reaction pathway (e.g., V2O5 in Contact process, Fe in Haber process, Ni/Pt in hydrogenation).",
    chapter: "d and f Block Elements", subtopic: "Catalytic Properties",
    concepts: ["Catalytic properties of transition metals", "Variable oxidation states", "Complex formation"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 8 — The d- and f-Block Elements — Catalytic properties"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 28, trending: false, ncertDirect: true,
  },
  {
    id: "nt-df-106", exam: "NEET", year: 2019,
    questionType: "MCQ-Single",
    question: "In neutral or faintly alkaline medium, potassium permanganate (KMnO4) oxidizes iodide (I-) to:",
    options: {
      A: "Iodine (I2)",
      B: "Iodate ion (IO3-)",
      C: "Periodate ion (IO4-)",
      D: "Hypoiodite ion (IO-)"
    },
    answer: "B",
    explanation: "While acidic KMnO4 oxidizes iodide (I-) only up to elemental iodine (I2), in neutral or faintly alkaline medium, permanganate (MnO4-) acts as a powerful oxidant that oxidizes iodide all the way to iodate ion (IO3-): 2 MnO4- + H2O + I- → 2 MnO2 + 2 OH- + IO3-.",
    chapter: "d and f Block Elements", subtopic: "Potassium Permanganate Reactions",
    concepts: ["Potassium permanganate", "Oxidation in neutral/alkaline medium", "Iodate formation"],
    reactions: ["2 MnO4- + H2O + I- -> 2 MnO2 + 2 OH- + IO3-"], reagents: ["Neutral/Alkaline KMnO4"], exceptions: ["In neutral/alkaline medium I- oxidizes to IO3- not I2"],
    formulas: [],
    ncertLines: ["Class 12 Ch. 8 — The d- and f-Block Elements — Permanganate titration in neutral medium"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 32, trending: true, ncertDirect: true,
  },
  {
    id: "nt-df-107", exam: "NEET", year: 2018,
    questionType: "MCQ-Single",
    question: "Which of the following ions is colorless in aqueous solution?",
    options: {
      A: "Ti3+ (Z=22)",
      B: "V3+ (Z=23)",
      C: "Cu+ (Z=29)",
      D: "Fe2+ (Z=26)"
    },
    answer: "C",
    explanation: "Color in transition metal ions arises from d-d electronic transitions of unpaired d electrons. Cu+ (Z=29) has electronic configuration [Ar]3d10 with a completely filled d subshell and zero unpaired electrons. Thus, d-d transition is forbidden/impossible, rendering Cu+ salts colorless and diamagnetic.",
    chapter: "d and f Block Elements", subtopic: "Color of Transition Metal Ions",
    concepts: ["d-d transition", "Colorless ions", "Completely filled d-orbitals", "Cu+ configuration"],
    reactions: [], reagents: [], exceptions: ["Cu+ and Zn2+ are colorless due to 3d10 configuration"],
    formulas: [],
    ncertLines: ["Class 12 Ch. 8 — The d- and f-Block Elements — Formation of Coloured Ions"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 38, trending: false, ncertDirect: true,
  },
  {
    id: "nt-df-108", exam: "NEET", year: 2022,
    questionType: "MCQ-Single",
    question: "Actinoids exhibit a greater range of oxidation states than lanthanoids because:",
    options: {
      A: "5f orbitals are more buried than 4f orbitals",
      B: "The energy difference between 5f, 6d, and 7s orbitals is much smaller than between 4f, 5d, and 6s orbitals",
      C: "Actinoids are radioactive and unstable",
      D: "Actinoids have higher ionization enthalpies than lanthanoids"
    },
    answer: "B",
    explanation: "In actinoids, the 5f, 6d, and 7s subshells have very small energy differences (comparable energies), allowing electrons from all three subshells to participate in chemical bonding. In lanthanoids, 4f orbitals are deeply buried with a larger energy gap from 5d and 6s, restricting them primarily to the +3 oxidation state.",
    chapter: "d and f Block Elements", subtopic: "Actinoids vs Lanthanoids",
    concepts: ["Actinoids oxidation states", "Energy gap between subshells", "5f vs 4f orbitals"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 8 — The d- and f-Block Elements — Actinoids — Oxidation States"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 29, trending: true, ncertDirect: true,
  },
  {
    id: "nt-df-109", exam: "NEET", year: 2023,
    questionType: "MCQ-Single",
    question: "Interstitial compounds formed by transition metals have which of the following characteristics?",
    options: {
      A: "They are chemically very reactive and soft",
      B: "They are extremely hard, have higher melting points than pure metals, and retain metallic conductivity",
      C: "They are strictly stoichiometric compounds with ionic bonding",
      D: "They are volatile liquids at room temperature"
    },
    answer: "B",
    explanation: "Interstitial compounds are formed when small atoms (H, C, N, B) are trapped inside the crystal lattice voids of transition metals. They are non-stoichiometric, chemically inert, extremely hard (some approaching diamond hardness), have higher melting points than the parent pure metals, and retain metallic electrical and thermal conductivity.",
    chapter: "d and f Block Elements", subtopic: "Interstitial Compounds",
    concepts: ["Interstitial compounds", "Properties of transition metal alloys", "Lattice voids"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 8 — The d- and f-Block Elements — Interstitial Compounds"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 25, trending: true, ncertDirect: true,
  },
  {
    id: "nt-df-110", exam: "NEET", year: 2021,
    questionType: "MCQ-Single",
    question: "The stability of Cu2+(aq) is greater than Cu+(aq) in aqueous solution despite Cu2+ having an incomplete d9 configuration because:",
    options: {
      A: "Cu2+ has a much higher negative hydration enthalpy that more than compensates for the second ionization enthalpy",
      B: "Cu+ has a higher nuclear charge",
      C: "Cu2+ forms insoluble precipitates in water",
      D: "Cu+ undergoes rapid evaporation"
    },
    answer: "A",
    explanation: "Although Cu+ has a stable 3d10 configuration in the gas phase, in aqueous medium Cu2+ is significantly more stable. Because Cu2+ is smaller and carries a +2 charge, it has an exceptionally high negative hydration enthalpy ($\Delta_{\\text{hyd}}H^\\circ = -2121\\text{ kJ/mol}$). This large energy release more than compensates for the high second ionization enthalpy required to convert Cu+ to Cu2+.",
    chapter: "d and f Block Elements", subtopic: "Stability of Cu2+ vs Cu+",
    concepts: ["Hydration enthalpy", "Ionization enthalpy", "Aqueous stability of Cu2+", "Disproportionation of Cu+"],
    reactions: ["2 Cu+(aq) -> Cu2+(aq) + Cu(s)"], reagents: [], exceptions: ["Cu2+ is more stable than Cu+ in aqueous medium despite 3d9 vs 3d10"],
    formulas: [],
    ncertLines: ["Class 12 Ch. 8 — The d- and f-Block Elements — Trends in the M2+/M Standard Electrode Potentials"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 34, trending: true, ncertDirect: true,
  },

  // ── CHEMICAL KINETICS (10 Questions) ────────────────────────────────────────
  {
    id: "nt-ck-102", exam: "NEET", year: 2022,
    questionType: "MCQ-Single",
    question: "Which of the following graphs represents a zero-order reaction?",
    options: {
      A: "Plot of concentration [R] vs time (t) is a straight line with a negative slope (-k)",
      B: "Plot of ln[R] vs time (t) is a straight line with a negative slope (-k)",
      C: "Plot of 1/[R] vs time (t) is a straight line with a positive slope (+k)",
      D: "Plot of rate vs concentration [R] is a straight line passing through the origin"
    },
    answer: "A",
    explanation: "For a zero-order reaction, rate is independent of reactant concentration: Rate = k[R]^0 = k. The integrated rate equation is $[R] = -kt + [R]_0$. Comparing with y = mx + c, a plot of reactant concentration [R] against time t yields a straight line with slope = -k and intercept = $[R]_0$.",
    chapter: "Chemical Kinetics", subtopic: "Zero Order Kinetics",
    concepts: ["Zero order reaction", "Integrated rate equation", "Graphical representation of kinetics"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["[R] = -kt + [R]_0"],
    ncertLines: ["Class 12 Ch. 4 — Chemical Kinetics — Zero order reaction graphs"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 38, trending: true, ncertDirect: true,
  },
  {
    id: "nt-ck-104", exam: "NEET", year: 2021,
    questionType: "MCQ-Single",
    question: "What is the unit of the rate constant (k) for a second-order reaction?",
    options: {
      A: "mol L-1 s-1",
      B: "s-1",
      C: "L mol-1 s-1",
      D: "L2 mol-2 s-1"
    },
    answer: "C",
    explanation: "In general, the unit of rate constant for an nth-order reaction is given by $(\\text{mol L}^{-1})^{1-n} \\text{ s}^{-1}$. For a second-order reaction (n = 2): $(\\text{mol L}^{-1})^{1-2} \\text{ s}^{-1} = \\text{mol}^{-1} \\text{ L s}^{-1}$ or $\\text{L mol}^{-1} \\text{ s}^{-1}$.",
    chapter: "Chemical Kinetics", subtopic: "Units of Rate Constant",
    concepts: ["Order of reaction", "Units of rate constant", "Dimensional analysis in kinetics"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["(\\text{mol L}^{-1})^{1-n} \\text{ s}^{-1}"],
    ncertLines: ["Class 12 Ch. 4 — Chemical Kinetics — Units of rate constant"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 33, trending: false, ncertDirect: true,
  },
  {
    id: "nt-ck-106", exam: "NEET", year: 2019,
    questionType: "MCQ-Single",
    question: "Acid-catalyzed hydrolysis of ethyl acetate in excess water ($\\ce{CH3COOC2H5 + H2O ->[H+] CH3COOH + C2H5OH}$) is an example of:",
    options: {
      A: "Zero-order reaction",
      B: "Pseudo first-order reaction",
      C: "Second-order reaction",
      D: "Third-order reaction"
    },
    answer: "B",
    explanation: "Molecularity of ester hydrolysis is 2 (bimolecular: involving ester and water). However, because water is present in large excess, its concentration remains practically constant during the reaction. Consequently, the rate depends experimentally only on the concentration of ester ($\\text{Rate} = k' [\\text{ester}]$), making it a pseudo first-order reaction.",
    chapter: "Chemical Kinetics", subtopic: "Pseudo First Order Reactions",
    concepts: ["Pseudo first-order reaction", "Ester hydrolysis", "Molecularity vs Order"],
    reactions: ["CH3COOC2H5 + H2O ->[H+] CH3COOH + C2H5OH"], reagents: ["Excess H2O", "H+ catalyst"], exceptions: ["Bimolecular reaction exhibiting first order kinetics"],
    formulas: [],
    ncertLines: ["Class 12 Ch. 4 — Chemical Kinetics — Pseudo first order reaction"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 36, trending: false, ncertDirect: true,
  },
  {
    id: "nt-ck-107", exam: "NEET", year: 2018,
    questionType: "MCQ-Single",
    question: "How does the addition of a positive catalyst affect the activation energy ($E_a$) and enthalpy change ($\\Delta H$) of a chemical reaction?",
    options: {
      A: "Lowers both $E_a$ and $\\Delta H$",
      B: "Lowers $E_a$ but leaves $\\Delta H$ unchanged",
      C: "Increases $E_a$ and lowers $\\Delta H$",
      D: "Leaves $E_a$ unchanged but lowers $\\Delta H$"
    },
    answer: "B",
    explanation: "A positive catalyst provides an alternative reaction pathway or mechanism with a lower activation energy ($E_a$), thereby increasing the rate of both forward and reverse reactions equally. However, $\\Delta H$ (enthalpy difference between reactants and products) is a state function independent of the pathway; hence, $\\Delta H$ remains completely unchanged.",
    chapter: "Chemical Kinetics", subtopic: "Effect of Catalyst",
    concepts: ["Catalysis", "Activation energy lowering", "Enthalpy of reaction as state function", "Energy profile diagram"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 4 — Chemical Kinetics — Effect of catalyst"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 39, trending: false, ncertDirect: true,
  },
  {
    id: "nt-ck-108", exam: "NEET", year: 2022,
    questionType: "MCQ-Single",
    question: "For a chemical reaction, the activation energy for the forward reaction is $E_{a(\\text{fwd})} = 60\\text{ kJ/mol}$ and for the backward reaction is $E_{a(\\text{bwd})} = 80\\text{ kJ/mol}$. The enthalpy change ($\\Delta H$) of the reaction is:",
    options: {
      A: "-20 kJ/mol (Exothermic)",
      B: "+20 kJ/mol (Endothermic)",
      C: "-140 kJ/mol (Exothermic)",
      D: "+140 kJ/mol (Endothermic)"
    },
    answer: "A",
    explanation: "The enthalpy change of a reaction is related to activation energies by: $\\Delta H = E_{a(\\text{fwd})} - E_{a(\\text{bwd})}$. Substituting values: $\\Delta H = 60\\text{ kJ/mol} - 80\\text{ kJ/mol} = -20\\text{ kJ/mol}$. Since $\\Delta H$ is negative, the reaction is exothermic.",
    chapter: "Chemical Kinetics", subtopic: "Activation Energy & Enthalpy",
    concepts: ["Activation energy of forward and backward reactions", "Enthalpy change calculation", "Exothermic vs Endothermic profiles"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["\\Delta H = E_{a(\\text{fwd})} - E_{a(\\text{bwd})}"],
    ncertLines: ["Class 12 Ch. 4 — Chemical Kinetics — Potential energy diagram"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 32, trending: true, ncertDirect: true,
  },
  {
    id: "nt-ck-109", exam: "NEET", year: 2023,
    questionType: "MCQ-Single",
    question: "In collision theory of bimolecular gaseous reactions ($\\text{Rate} = P Z_{AB} e^{-E_a/RT}$), what does the steric factor P represent?",
    options: {
      A: "The fraction of molecules possessing energy greater than $E_a$",
      B: "The total collision frequency per second per unit volume",
      C: "The orientation factor accounting for proper spatial alignment of colliding molecules",
      D: "The pressure of gaseous reactants in atmospheres"
    },
    answer: "C",
    explanation: "In collision theory, effective collisions require both adequate kinetic energy ($\\ge E_a$) and proper spatial orientation. The factor P (steric factor or probability factor) accounts for the requirement that reacting molecules must collide with the correct geometric orientation for bond breaking and bond formation to occur.",
    chapter: "Chemical Kinetics", subtopic: "Collision Theory",
    concepts: ["Collision theory", "Steric factor P", "Collision frequency Z", "Effective collisions"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["\\text{Rate} = P Z_{AB} e^{-E_a/RT}"],
    ncertLines: ["Class 12 Ch. 4 — Chemical Kinetics — Collision theory of chemical reactions"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 24, trending: true, ncertDirect: true,
  },
  {
    id: "nt-ck-110", exam: "NEET", year: 2021,
    questionType: "MCQ-Single",
    question: "If a first-order reaction takes 40 minutes for 75% completion, what is the half-life ($t_{1/2}$) of the reaction?",
    options: {
      A: "10 minutes",
      B: "20 minutes",
      C: "30 minutes",
      D: "15 minutes"
    },
    answer: "B",
    explanation: "For a first-order reaction, 75% completion corresponds to two half-lives (after 1st half-life: 50% remains, after 2nd half-life: 25% remains, meaning 75% is completed). Therefore, $t_{75\\%} = 2 \\times t_{1/2}$. Given $t_{75\\%} = 40\\text{ minutes}$, we get $t_{1/2} = 40 / 2 = 20\\text{ minutes}$.",
    chapter: "Chemical Kinetics", subtopic: "First Order Kinetics — Percentage Completion",
    concepts: ["First order reaction time relations", "75% completion rule", "Half-life multiples"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["t_{75\\%} = 2 \\times t_{1/2}", "t_{87.5\\%} = 3 \\times t_{1/2}", "t_{99.9\\%} \\approx 10 \\times t_{1/2}"],
    ncertLines: ["Class 12 Ch. 4 — Chemical Kinetics — Integrated rate equations"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 42, trending: true, ncertDirect: true,
  },

  // ── ELECTROCHEMISTRY (10 Questions) ─────────────────────────────────────────
  {
    id: "nt-el-101", exam: "NEET", year: 2023,
    questionType: "MCQ-Single",
    question: "Calculate the standard cell potential ($E^\\circ_{\\text{cell}}$) for the galvanic cell: $\\ce{Zn(s) | Zn^{2+}(aq) || Cu^{2+}(aq) | Cu(s)}$, given $E^\\circ_{\\ce{Zn^{2+}/Zn}} = -0.76\\text{ V}$ and $E^\\circ_{\\ce{Cu^{2+}/Cu}} = +0.34\\text{ V}$.",
    options: {
      A: "+1.10 V",
      B: "-1.10 V",
      C: "+0.42 V",
      D: "-0.42 V"
    },
    answer: "A",
    explanation: "In the Daniell cell, zinc undergoes oxidation at the anode and copper undergoes reduction at the cathode. Standard cell potential: $E^\\circ_{\\text{cell}} = E^\\circ_{\\text{cathode}} - E^\\circ_{\\text{anode}} = E^\\circ_{\\ce{Cu^{2+}/Cu}} - E^\\circ_{\\ce{Zn^{2+}/Zn}} = +0.34\\text{ V} - (-0.76\\text{ V}) = +1.10\\text{ V}$.",
    chapter: "Electrochemistry", subtopic: "Galvanic Cells & EMF",
    concepts: ["Daniell cell", "Standard electrode potential", "Cell EMF calculation", "Anode and cathode identification"],
    reactions: ["Zn(s) + Cu^{2+}(aq) -> Zn^{2+}(aq) + Cu(s)"], reagents: [], exceptions: [],
    formulas: ["E^\\circ_{\\text{cell}} = E^\\circ_{\\text{cathode}} - E^\\circ_{\\text{anode}}"],
    ncertLines: ["Class 12 Ch. 3 — Electrochemistry — Galvanic cells"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 48, trending: true, ncertDirect: true,
  },
  {
    id: "nt-el-102", exam: "NEET", year: 2024,
    questionType: "MCQ-Single",
    question: "Which of the following expressions correctly relates standard Gibbs free energy change ($\\Delta G^\\circ$) and standard cell potential ($E^\\circ_{\\text{cell}}$)?",
    options: {
      A: "$\\Delta G^\\circ = -n F E^\\circ_{\\text{cell}}$",
      B: "$\\Delta G^\\circ = +n F E^\\circ_{\\text{cell}}$",
      C: "$\\Delta G^\\circ = -\\frac{n F}{E^\\circ_{\\text{cell}}}$",
      D: "$\\Delta G^\\circ = -R T \\ln E^\\circ_{\\text{cell}}$"
    },
    answer: "A",
    explanation: "Electrical work done by an electrochemical cell equals the decrease in Gibbs free energy. For n moles of electrons transferred (where F is Faraday's constant = 96487 C/mol), the standard Gibbs free energy change is strictly given by $\\Delta G^\\circ = -n F E^\\circ_{\\text{cell}}$. A spontaneous reaction requires $E^\\circ_{\\text{cell}} > 0$ and $\\Delta G^\\circ < 0$.",
    chapter: "Electrochemistry", subtopic: "Gibbs Free Energy & EMF",
    concepts: ["Gibbs free energy", "Spontaneity of electrochemical cells", "Faraday constant"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["\\Delta G^\\circ = -n F E^\\circ_{\\text{cell}}", "\\Delta G^\\circ = -2.303 R T \\log K_c"],
    ncertLines: ["Class 12 Ch. 3 — Electrochemistry — Electrochemical Cell and Gibbs Energy of the Reaction"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 42, trending: true, ncertDirect: true,
  },
  {
    id: "nt-el-103", exam: "NEET", year: 2022,
    questionType: "MCQ-Single",
    question: "According to Kohlrausch's law of independent migration of ions, the limiting molar conductivity of acetic acid ($\\Lambda^\\circ_m(\\ce{CH3COOH})$) can be calculated from which combination of strong electrolytes?",
    options: {
      A: "$\\Lambda^\\circ_m(\\ce{CH3COONa}) + \\Lambda^\\circ_m(\\ce{HCl}) - \\Lambda^\\circ_m(\\ce{NaCl})$",
      B: "$\\Lambda^\\circ_m(\\ce{CH3COONa}) + \\Lambda^\\circ_m(\\ce{NaCl}) - \\Lambda^\\circ_m(\\ce{HCl})$",
      C: "$\\Lambda^\\circ_m(\\ce{CH3COONa}) + \\Lambda^\\circ_m(\\ce{NaOH}) - \\Lambda^\\circ_m(\\ce{NaCl})$",
      D: "$\\Lambda^\\circ_m(\\ce{CH3COONa}) - \\Lambda^\\circ_m(\\ce{HCl}) - \\Lambda^\\circ_m(\\ce{NaCl})$"
    },
    answer: "A",
    explanation: "Kohlrausch's law states that at infinite dilution, each ion contributes independently to the total molar conductivity. To calculate $\\Lambda^\\circ_m$ for weak electrolyte $\\ce{CH3COOH}$: add $\\Lambda^\\circ_m(\\ce{CH3COONa})$ (provides $\\ce{CH3COO-}$ ion) and $\\Lambda^\\circ_m(\\ce{HCl})$ (provides $\\ce{H+}$ ion), then subtract $\\Lambda^\\circ_m(\\ce{NaCl})$ to eliminate spectator ions $\\ce{Na+}$ and $\\ce{Cl-}$.",
    chapter: "Electrochemistry", subtopic: "Kohlrausch's Law & Applications",
    concepts: ["Kohlrausch's law", "Limiting molar conductivity", "Weak electrolyte conductivity", "Independent migration of ions"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["\\Lambda^\\circ_m(\\ce{CH3COOH}) = \\lambda^\\circ(\\ce{CH3COO-}) + \\lambda^\\circ(\\ce{H+})"],
    ncertLines: ["Class 12 Ch. 3 — Electrochemistry — Kohlrausch law of independent migration of ions"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 44, trending: true, ncertDirect: true,
  },
  {
    id: "nt-el-104", exam: "NEET", year: 2021,
    questionType: "MCQ-Single",
    question: "How many Faradays of electricity are required to reduce 1 mole of $\\ce{MnO4-}$ ions to $\\ce{Mn^{2+}}$ in acidic medium?",
    options: {
      A: "1 F",
      B: "3 F",
      C: "5 F",
      D: "7 F"
    },
    answer: "C",
    explanation: "In acidic medium, permanganate ion undergoes 5-electron reduction: $\\ce{MnO4- + 8 H+ + 5 e- -> Mn^{2+} + 4 H2O}$. Here, oxidation state of manganese changes from +7 in $\\ce{MnO4-}$ to +2 in $\\ce{Mn^{2+}}$ ($\\Delta = 5$). Since 1 mole of electrons = 1 Faraday (1 F), reducing 1 mole of $\\ce{MnO4-}$ requires exactly 5 Faradays of charge.",
    chapter: "Electrochemistry", subtopic: "Faraday's Laws of Electrolysis",
    concepts: ["Faraday's first law of electrolysis", "Electrolytic reduction", "Charge calculation in Faradays", "Oxidation state change"],
    reactions: ["MnO4- + 8 H+ + 5 e- -> Mn^{2+} + 4 H2O"], reagents: [], exceptions: [],
    formulas: ["Q = n \\times F"],
    ncertLines: ["Class 12 Ch. 3 — Electrochemistry — Faraday's laws of electrolysis"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 40, trending: false, ncertDirect: true,
  },
  {
    id: "nt-el-105", exam: "NEET", year: 2020,
    questionType: "MCQ-Single",
    question: "During the electrolysis of aqueous NaCl solution using inert Pt electrodes, which product is discharged at the cathode and which at the anode?",
    options: {
      A: "Cathode: Na metal; Anode: Cl2 gas",
      B: "Cathode: H2 gas; Anode: Cl2 gas",
      C: "Cathode: H2 gas; Anode: O2 gas",
      D: "Cathode: Na metal; Anode: O2 gas"
    },
    answer: "B",
    explanation: "In aqueous NaCl, cathode competes between reduction of $\\ce{Na+}$ ($E^\\circ = -2.71\\text{ V}$) and water/$\\ce{H+}$ ($E^\\circ = 0.00\\text{ V}$). Higher reduction potential wins: $\\ce{H2}$ gas evolves at cathode. At anode, oxidation competes between $\\ce{Cl-}$ and water. Although oxidation of water has lower standard potential ($E^\\circ = 1.23\\text{ V}$ vs $1.36\\text{ V}$ for $\\ce{Cl-}$), due to overpotential (overvoltage) of oxygen evolution, $\\ce{Cl2}$ gas is discharged at anode.",
    chapter: "Electrochemistry", subtopic: "Products of Electrolysis & Overpotential",
    concepts: ["Electrolysis of aqueous NaCl", "Overpotential / Overvoltage", "Preferential discharge theory", "Chlor-alkali process"],
    reactions: ["Cathode: 2 H2O + 2 e- -> H2 + 2 OH-", "Anode: 2 Cl- -> Cl2 + 2 e-"], reagents: ["Aqueous NaCl", "Pt electrode"], exceptions: ["Cl2 evolves at anode instead of O2 due to overpotential"],
    formulas: [],
    ncertLines: ["Class 12 Ch. 3 — Electrochemistry — Products of Electrolysis"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 37, trending: false, ncertDirect: true,
  },
  {
    id: "nt-el-106", exam: "NEET", year: 2019,
    questionType: "MCQ-Single",
    question: "How does molar conductivity ($\\Lambda_m$) change with decreasing concentration (dilution) for strong and weak electrolytes?",
    options: {
      A: "Decreases for both strong and weak electrolytes",
      B: "Increases slightly for strong electrolytes and increases sharply for weak electrolytes",
      C: "Increases for strong electrolytes but decreases for weak electrolytes",
      D: "Remains constant for strong electrolytes and increases for weak electrolytes"
    },
    answer: "B",
    explanation: "Molar conductivity ($\\Lambda_m = \\kappa \\times 1000 / M$) increases with dilution for all electrolytes. For strong electrolytes (already 100% ionized), dilution decreases interionic attractions, causing a slight linear increase in $\\Lambda_m$ (Debye-Huckel-Onsager equation). For weak electrolytes, dilution significantly increases the degree of dissociation ($\\alpha$), causing a sharp, exponential rise in total ions and $\\Lambda_m$.",
    chapter: "Electrochemistry", subtopic: "Conductance & Dilution",
    concepts: ["Molar conductivity variation with dilution", "Debye-Huckel-Onsager equation", "Degree of dissociation", "Strong vs weak electrolytes"],
    reactions: [], reagents: [], exceptions: [],
    formulas: ["\\Lambda_m = \\Lambda^\\circ_m - A\\sqrt{c}", "\\alpha = \\frac{\\Lambda_m}{\\Lambda^\\circ_m}"],
    ncertLines: ["Class 12 Ch. 3 — Electrochemistry — Variation of Conductivity and Molar Conductivity with Concentration"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 35, trending: false, ncertDirect: true,
  },
  {
    id: "nt-el-107", exam: "NEET", year: 2018,
    questionType: "MCQ-Single",
    question: "In a lead storage battery, during discharging, what happens at the anode and cathode?",
    options: {
      A: "Both lead (Pb) anode and lead dioxide (PbO2) cathode are converted into white insoluble lead sulfate (PbSO4)",
      B: "Pb is converted to PbO2 and sulfuric acid is regenerated",
      C: "PbSO4 is reduced to Pb at cathode and oxidized to PbO2 at anode",
      D: "Sulfuric acid concentration increases continuously"
    },
    answer: "A",
    explanation: "During discharging of a lead storage battery, spongy lead anode is oxidized ($\\ce{Pb + SO4^{2-} -> PbSO4 + 2 e-}$) and lead dioxide cathode is reduced ($\\ce{PbO2 + SO4^{2-} + 4 H+ + 2 e- -> PbSO4 + 2 H2O}$). Thus, both electrodes convert into insoluble white $\\ce{PbSO4}$ while sulfuric acid ($\\ce{H2SO4}$) is consumed, decreasing electrolyte density.",
    chapter: "Electrochemistry", subtopic: "Commercial Batteries & Cells",
    concepts: ["Lead storage battery", "Secondary batteries", "Discharging and charging reactions", "Electrolyte consumption"],
    reactions: ["Pb + PbO2 + 2 H2SO4 -> 2 PbSO4 + 2 H2O"], reagents: ["38% H2SO4 electrolyte"], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 3 — Electrochemistry — Batteries — Lead storage battery"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 31, trending: false, ncertDirect: true,
  },
  {
    id: "nt-el-108", exam: "NEET", year: 2022,
    questionType: "MCQ-Single",
    question: "The Nernst equation for the electrode reaction $\\ce{M^{n+}(aq) + n e- -> M(s)}$ at 298 K is:",
    options: {
      A: "$E = E^\\circ - \\frac{0.059}{n} \\log[\\ce{M^{n+}}]$",
      B: "$E = E^\\circ + \\frac{0.059}{n} \\log[\\ce{M^{n+}}]$",
      C: "$E = E^\\circ - \\frac{2.303 R T}{n F} \\ln[\\ce{M^{n+}}]$",
      D: "$E = E^\\circ + \\frac{0.059}{n^2} \\log[\\ce{M^{n+}}]$"
    },
    answer: "B",
    explanation: "Nernst equation: $E = E^\\circ - \\frac{2.303 R T}{n F} \\log \\frac{[\\text{Product}]}{[\\text{Reactant}]}$. For metal reduction $\\ce{M^{n+} + n e- -> M(s)}$, concentration of solid metal $[\\ce{M(s)}] = 1$. Substituting $R = 8.314$, $T = 298\\text{ K}$, $F = 96487\\text{ C/mol}$: $E = E^\\circ - \\frac{0.059}{n} \\log \\frac{1}{[\\ce{M^{n+}}]} = E^\\circ + \\frac{0.059}{n} \\log[\\ce{M^{n+}}]$.",
    chapter: "Electrochemistry", subtopic: "Nernst Equation",
    concepts: ["Nernst equation", "Electrode potential calculation", "Effect of concentration on EMF", "Standard state of solids"],
    reactions: ["M^{n+} + n e- -> M(s)"], reagents: [], exceptions: [],
    formulas: ["E = E^\\circ + \\frac{0.059}{n} \\log[\\ce{M^{n+}}]"],
    ncertLines: ["Class 12 Ch. 3 — Electrochemistry — Nernst equation"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 46, trending: true, ncertDirect: true,
  },
  {
    id: "nt-el-109", exam: "NEET", year: 2023,
    questionType: "MCQ-Single",
    question: "In the hydrogen-oxygen ($\\ce{H2 - O2}$) fuel cell used in the Apollo space program, the electrolyte used and the reaction at cathode are:",
    options: {
      A: "Concentrated KOH solution; $\\ce{O2 + 2 H2O + 4 e- -> 4 OH-}$",
      B: "Concentrated H2SO4 solution; $\\ce{2 H+ + 2 e- -> H2}$",
      C: "Molten NaCl; $\\ce{O2 + 4 e- -> 2 O^{2-}}$",
      D: "Concentrated KOH solution; $\\ce{2 H2 + 4 OH- -> 4 H2O + 4 e-}$"
    },
    answer: "A",
    explanation: "In the Bacon $\\ce{H2-O2}$ fuel cell, concentrated aqueous KOH is used as electrolyte between porous carbon electrodes. At anode (oxidation): $\\ce{2 H2 + 4 OH- -> 4 H2O + 4 e-}$. At cathode (reduction): oxygen is reduced in presence of water: $\\ce{O2 + 2 H2O + 4 e- -> 4 OH-}$. Overall net reaction yields pure potable water: $\\ce{2 H2 + O2 -> 2 H2O}$.",
    chapter: "Electrochemistry", subtopic: "Fuel Cells",
    concepts: ["Fuel cells", "H2-O2 fuel cell", "Apollo space program", "Thermodynamic efficiency of fuel cells"],
    reactions: ["Cathode: O2 + 2 H2O + 4 e- -> 4 OH-", "Anode: 2 H2 + 4 OH- -> 4 H2O + 4 e-"], reagents: ["Conc. KOH electrolyte", "Porous carbon electrode with Pt/Pd catalyst"], exceptions: [],
    formulas: ["\\text{Efficiency } \\eta = \\frac{\\Delta G}{\\Delta H} \\times 100\\%"],
    ncertLines: ["Class 12 Ch. 3 — Electrochemistry — Fuel cells"],
    difficulty: "Moderate", marks: 4, negMarks: 1, frequency: 27, trending: true, ncertDirect: true,
  },
  {
    id: "nt-el-110", exam: "NEET", year: 2021,
    questionType: "MCQ-Single",
    question: "The standard reduction potentials of four metals A, B, C, and D are $-2.90\\text{ V}$, $-0.76\\text{ V}$, $+0.34\\text{ V}$, and $+0.80\\text{ V}$ respectively. Which metal is the strongest reducing agent?",
    options: {
      A: "Metal A ($E^\\circ = -2.90\\text{ V}$)",
      B: "Metal B ($E^\\circ = -0.76\\text{ V}$)",
      C: "Metal C ($E^\\circ = +0.34\\text{ V}$)",
      D: "Metal D ($E^\\circ = +0.80\\text{ V}$)"
    },
    answer: "A",
    explanation: "A more negative standard reduction potential ($E^\\circ$) indicates a stronger tendency for the metal atom to lose electrons (undergo oxidation). Therefore, the metal with the lowest/most negative reduction potential (Metal A, $-2.90\\text{ V}$, similar to potassium/lithium) is the most easily oxidized and acts as the strongest reducing agent.",
    chapter: "Electrochemistry", subtopic: "Electrochemical Series & Reducing Power",
    concepts: ["Electrochemical series", "Reducing and oxidizing power", "Standard reduction potential"],
    reactions: [], reagents: [], exceptions: [],
    formulas: [],
    ncertLines: ["Class 12 Ch. 3 — Electrochemistry — Electrochemical series table and applications"],
    difficulty: "Easy", marks: 4, negMarks: 1, frequency: 45, trending: true, ncertDirect: true,
  },
];
