import type { ProgramSyllabus } from "./types";

// JEE Advanced Chemistry — transcribed from the official JEE (Advanced) 2026
// syllabus (uploaded PDF; 2026 = same as 2025). Unlike JEE Main, it INCLUDES
// States of Matter, Solid State, Surface Chemistry, Hydrogen, s-Block,
// Environmental Chemistry, Polymers and Chemistry in Everyday Life.

export const JEE_ADVANCED_SYLLABUS: ProgramSyllabus = {
  programId: "jee-advanced",
  name: "JEE Advanced Chemistry",
  source: "Official JEE (Advanced) 2026 Chemistry syllabus (uploaded PDF)",
  units: [
    { id: "general-topics", title: "General Topics", branch: "physical", topics: ["Mole concept; chemical formulae; balanced equations", "Stoichiometry of redox, neutralisation and displacement reactions", "Concentration: mole fraction, molarity, molality, normality"] },
    { id: "states-of-matter", title: "States of Matter: Gases and Liquids", branch: "physical", topics: ["Gas laws, ideal gas equation, absolute temperature", "van der Waals equation; kinetic theory; molecular speeds", "Partial pressures; diffusion", "Intermolecular interactions; liquids: vapour pressure, surface tension, viscosity"] },
    { id: "atomic-structure", title: "Atomic Structure", branch: "physical", topics: ["Bohr model, hydrogen spectrum", "Wave–particle duality, de Broglie, uncertainty principle", "Quantum-mechanical H atom: energies, quantum numbers, plots of ψ", "Shapes of s/p/d orbitals; Aufbau, Pauli, Hund"] },
    { id: "chemical-bonding", title: "Chemical Bonding and Molecular Structure", branch: "physical", topics: ["Orbital overlap; hybridisation (s, p, d)", "MO energy diagrams of homonuclear diatomics (up to Ne₂)", "Hydrogen bond; polarity, dipole moment", "VSEPR shapes: linear → octahedral"] },
    { id: "thermodynamics", title: "Chemical Thermodynamics", branch: "physical", topics: ["First law: internal energy, PV-work, heat; enthalpy, heat capacity, Hess's law", "Reaction/fusion/vaporization/lattice enthalpies", "Second law: entropy, Gibbs energy, spontaneity criteria"] },
    { id: "equilibrium", title: "Chemical and Ionic Equilibrium", branch: "physical", topics: ["Law of mass action; ΔG and ΔG⊖; Kp/Kc, reaction quotient", "Le Chatelier's principle", "Solubility product, common-ion effect, pH, buffers", "Brønsted & Lewis acids/bases; salt hydrolysis"] },
    { id: "redox-reactions", title: "Redox Reactions", branch: "physical", topics: ["Oxidation states and calculation of oxidation numbers", "Equivalent weight and n-factor evaluation for elements, oxides, acids, bases and salts", "Stoichiometry of redox, neutralisation and displacement reactions", "Disproportionation reactions and balancing of redox half-reactions", "Volumetric titration, iodometry vs iodimetry and equivalent law (W1/E1 = W2/E2)"] },
    { id: "electrochemistry", title: "Electrochemistry", branch: "physical", topics: ["Cells & cell reactions; standard electrode potentials", "Nernst equation; electrochemical series; emf", "Faraday's laws; conductance & Kohlrausch", "Batteries, fuel cells, corrosion"] },
    { id: "kinetics", title: "Chemical Kinetics", branch: "physical", topics: ["Rates, order & molecularity; rate law, half-life", "Zero & first order integrated expressions", "Arrhenius equation, activation energy", "Homogeneous/heterogeneous catalysis; enzyme catalysis mechanism"] },
    { id: "solid-state", title: "Solid State", branch: "physical", topics: ["Seven crystal systems; cubic & hexagonal close packing", "fcc/bcc/hcp packing, nearest neighbours", "Ionic radii & radius ratio; point defects"] },
    { id: "solutions", title: "Solutions", branch: "physical", topics: ["Henry's & Raoult's laws; ideal solutions", "All four colligative properties; van't Hoff factor"] },
    { id: "surface-chemistry", title: "Surface Chemistry", branch: "physical", topics: ["Physisorption vs chemisorption; Freundlich isotherm", "Colloids: types, preparation, properties", "Emulsions, surfactants, micelles"] },
    { id: "periodicity", title: "Classification of Elements and Periodicity", branch: "inorganic", topics: ["Modern periodic law; electronic configurations", "Trends: radii, ionization enthalpy, electron gain enthalpy, valence, oxidation states, electronegativity, reactivity"] },
    { id: "hydrogen", title: "Hydrogen", branch: "inorganic", topics: ["Position, isotopes, preparation, properties", "Hydrides: ionic, covalent, interstitial", "Water, heavy water; H₂O₂; hydrogen as fuel"] },
    { id: "s-block", title: "s-Block Elements", branch: "inorganic", topics: ["Alkali & alkaline-earth reactivity; liquid-ammonia solutions", "Oxides, hydroxides, halides, oxoacid salts", "Anomalous Li & Be", "Na₂CO₃, NaCl, NaOH, NaHCO₃; CaO, Ca(OH)₂, CaCO₃, CaSO₄"] },
    { id: "p-block", title: "p-Block Elements", branch: "inorganic", topics: ["Groups 13–17 trends; anomalies of B, C, N, O, F", "Group 13: borax, boric acid, diborane, BF₃, AlCl₃, alums", "Group 14: CO, CO₂, SiO₂, silicones, silicates, zeolites", "Group 15: N₂, NH₃, HNO₃, PH₃, PCl₃, PCl₅; N oxides, P oxoacids", "Group 16: O₂, O₃, SO₂, H₂SO₄; S oxoacids", "Group 17: Cl₂, HCl, interhalogens, halogen oxoacids, bleaching powder", "Group 18: xenon–fluorine/oxygen compounds"] },
    { id: "d-block", title: "d-Block Elements", branch: "inorganic", topics: ["Oxidation states & stability; electrode potentials", "Interstitial compounds, alloys, catalysis", "Cr & Mn oxoanions: preparation, structure, reactions"] },
    { id: "f-block", title: "f-Block Elements", branch: "inorganic", topics: ["Lanthanoid & actinoid contractions", "Oxidation states; general characteristics"] },
    { id: "coordination", title: "Coordination Compounds", branch: "inorganic", topics: ["Werner's theory; nomenclature; cis–trans & ionization isomerism", "Hybridisation & geometries; VBT and CFT (Oh & Td)", "Spin-only magnetism, colour; spectrochemical series; stability", "Metal carbonyls"] },
    { id: "metallurgy", title: "Isolation of Metals", branch: "inorganic", topics: ["Ore concentration; thermodynamic principles (Fe, Cu, Zn)", "Electrochemical extraction (Al); cyanide process (Ag, Au); refining"] },
    { id: "qualitative-analysis", title: "Principles of Qualitative Analysis", branch: "inorganic", topics: ["Groups I–V: Ag⁺, Hg²⁺, Cu²⁺, Pb²⁺, Fe³⁺, Cr³⁺, Al³⁺, Ca²⁺, Ba²⁺, Zn²⁺, Mn²⁺, Mg²⁺", "Nitrate, halides (no fluoride), carbonate/bicarbonate, sulphate, sulphide"] },
    { id: "environmental", title: "Environmental Chemistry", branch: "inorganic", topics: ["Atmospheric, water & soil pollution; industrial waste", "Control strategies; green chemistry"] },
    { id: "goc", title: "Basic Principles of Organic Chemistry", branch: "organic", topics: ["Hybridisation; σ/π bonds; aromaticity", "Isomerism incl. enantiomers/diastereomers/meso (≤2 stereocentres; R/S & E/Z excluded)", "IUPAC nomenclature (mono & bifunctional)", "Inductive/resonance/hyperconjugation; acidity & basicity", "Reactive intermediates: carbocations, carbanions, radicals"] },
    { id: "alkanes", title: "Alkanes", branch: "organic", topics: ["Physical properties & branching effects", "Conformations of ethane & butane (Newman)", "Preparation from alkyl halides & carboxylic acids", "Combustion, halogenation (incl. allylic/benzylic), oxidation"] },
    { id: "alkenes-alkynes", title: "Alkenes and Alkynes", branch: "organic", topics: ["Preparation by elimination; acid-catalysed hydration", "Metal acetylides; KMnO₄ & ozone reactions", "Electrophilic additions X₂/HX/HOX; peroxide effect", "Cyclic polymerization of alkynes"] },
    { id: "benzene", title: "Benzene", branch: "organic", topics: ["Structure; electrophilic substitutions", "Friedel–Crafts alkylation/acylation; directing effects"] },
    { id: "phenols", title: "Phenols", branch: "organic", topics: ["Electrophilic substitutions; Reimer–Tiemann, Kolbe", "Esterification, etherification; aspirin synthesis; oxidation/reduction"] },
    { id: "alkyl-halides", title: "Alkyl Halides", branch: "organic", topics: ["Carbocation rearrangements; Grignard reactions", "Nucleophilic substitution & stereochemistry"] },
    { id: "alcohols", title: "Alcohols", branch: "organic", topics: ["Esterification; dehydration to alkenes & ethers", "Na, PX₃/PX₅, ZnCl₂/HCl, SOCl₂ reactions", "Oxidation to aldehydes, ketones, acids"] },
    { id: "ethers", title: "Ethers", branch: "organic", topics: ["Williamson synthesis; C–O cleavage reactions"] },
    { id: "aldehydes-ketones", title: "Aldehydes and Ketones", branch: "organic", topics: ["Preparations (acid chlorides, nitriles, esters; benzaldehyde routes)", "Oxidation/reduction; oximes & hydrazones", "Aldol, Cannizzaro, haloform", "Additions: RMgX, NaHSO₃, HCN, alcohols, amines"] },
    { id: "carboxylic-acids", title: "Carboxylic Acids", branch: "organic", topics: ["Preparations: nitriles, Grignard, ester/amide hydrolysis, alkylbenzene oxidation", "Reduction, halogenation; esters, acid chlorides, amides"] },
    { id: "amines", title: "Amines", branch: "organic", topics: ["Preparation from nitro, nitriles, amides", "Hofmann bromamide; Gabriel synthesis", "HNO₂ reaction; azo coupling; Sandmeyer", "Carbylamine, Hinsberg, alkylation/acylation"] },
    { id: "haloarenes", title: "Haloarenes", branch: "organic", topics: ["Fittig & Wurtz–Fittig", "Nucleophilic aromatic substitution (benzyne/cine excluded)"] },
    { id: "biomolecules", title: "Biomolecules", branch: "organic", topics: ["Glucose & sucrose; oxidation/reduction; glycosides; anomers", "Amino acids; peptides (1°/2° structure); fibrous vs globular proteins", "DNA & RNA composition and structure"] },
    { id: "polymers", title: "Polymers", branch: "organic", topics: ["Addition & condensation polymerization; homo/copolymers", "Natural rubber, cellulose, nylon, teflon, bakelite, PVC", "Biodegradable polymers; applications"] },
    { id: "everyday-life", title: "Chemistry in Everyday Life", branch: "organic", topics: ["Drug–target interaction; therapeutic classes (structures excluded)", "Artificial sweeteners; soaps & detergents, cleansing action"] },
    { id: "practical-organic", title: "Practical Organic Chemistry", branch: "practical", topics: ["Detection of N, S, halogens", "Identification: hydroxyl, carbonyl, carboxyl, amino, nitro groups"] },
  ],
  questionTypes: [
    { key: "scq", label: "SCQ", source: "bank" },
    { key: "multi-correct", label: "Multiple Correct (MCQ)", source: "ai-self" },
    { key: "integer", label: "Integer", source: "ai-numeric" },
    { key: "matrix-match", label: "Matrix Match", source: "ai-self" },
    { key: "list-match", label: "List Match", source: "ai-self" },
    { key: "paragraph", label: "Paragraph Based", source: "ai-self" },
    { key: "numerical-response", label: "Numerical Response", source: "ai-numeric" },
    { key: "comprehension", label: "Comprehension", source: "ai-self" },
    { key: "challenge", label: "Advanced Challenge", source: "ai-self" },
  ],
  features: { notes: true, pyqs: true, mocks: true, analytics: true, practicals: false, projects: false, viva: false },
};
