import { notFound } from "next/navigation";
import { ChapterLessonPager, ChapterPartStrip, ChapterShell } from "@/components/notes/canonical";
import { P_BLOCK_PARTS, pBlockPartBySlug, pBlockPartMarkdown } from "../parts";
import { pBlockLessonRef, pBlockTabs, sectionRangeLabel } from "../_chapter";
import { PBlockMarkdown } from "../_markdown";
import { PBlockVisual } from "../visuals";
export const dynamic = "force-dynamic";
export function generateStaticParams() { return P_BLOCK_PARTS.map((part) => ({ part: part.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ part: string }> }) { const part = pBlockPartBySlug((await params).part); return part ? { title: `P-block Elements — ${part.title} | SYNERGIC BOND`, description: `P-block JEE Advanced notes, Lesson ${part.number}: ${part.title}.` } : {}; }
export default async function PBlockPartPage({ params }: { params: Promise<{ part: string }> }) { const part = pBlockPartBySlug((await params).part); if (!part) notFound(); return <ChapterShell kicker="JEE Inorganic Chemistry" subtitle="P-block Elements" tabs={pBlockTabs(part.number)}><ChapterPartStrip hubHref="/notes/p-block" hubLabel="P-block — all lessons" positionLabel={`Lesson ${part.number} of ${P_BLOCK_PARTS.length}`}/><article className="mx-auto max-w-5xl space-y-6 text-white"><header style={{ background: "#122232", border: "1px solid #24405c", borderLeft: "4px solid #5fd4ea", borderRadius: 13, padding: "18px 20px" }}><p style={{ color: "#5fd4ea", fontSize: 11.5, fontWeight: 900, letterSpacing: ".14em", textTransform: "uppercase" }}>P-block Elements · Lesson {part.number} · {sectionRangeLabel(part)}</p><h1 style={{ marginTop: 8, color: "#eef3f8", fontSize: 30, fontWeight: 900, lineHeight: 1.15, fontFamily: "Georgia, 'Iowan Old Style', 'Times New Roman', serif" }}>{part.title}</h1></header><PBlockVisual part={part.number} /><div className="space-y-5 rounded-lg border border-[#24405c] bg-[#122232]/60 px-5 py-8 sm:px-8 lg:px-10"><PBlockMarkdown markdown={pBlockPartMarkdown(part)}/></div><ChapterLessonPager prev={pBlockLessonRef(part.number - 1)} next={pBlockLessonRef(part.number + 1)} hubHref="/notes/p-block" hubLabel="All lessons"/></article></ChapterShell>; }
